RELIC: include/relic_pp.h File Reference
relic_pp.h File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_fpx.h"
#include "relic_epx.h"
#include "relic_types.h"
Macros
#define pp_map_sim_k2(R, P, Q, M) pp_map_sim_tatep_k2(R, P, Q, M)
Functions
void pp_map_init (void)
void pp_map_clean (void)
void pp_add_k2_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
void pp_add_k2_projc_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
void pp_add_k2_projc_lazyr (fp2_t l, ep_t r, ep_t p, ep_t q)
void pp_add_k8_basic (fp8_t l, ep2_t r, ep2_t q, ep_t p)
void pp_add_k8_projc_basic (fp8_t l, ep2_t r, ep2_t q, ep_t p)
void pp_add_k8_projc_lazyr (fp8_t l, ep2_t r, ep2_t q, ep_t p)
void pp_add_k12_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
void pp_add_k12_projc_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
void pp_add_k12_projc_lazyr (fp12_t l, ep2_t r, ep2_t q, ep_t p)
void pp_add_lit_k12 (fp12_t l, ep_t r, ep_t p, ep2_t q)
void pp_add_k48_basic (fp48_t l, fp8_t rx, fp8_t ry, fp8_t qx, fp8_t qy, ep_t p)
void pp_add_k48_projc (fp48_t l, fp8_t rx, fp8_t ry, fp8_t rz, fp8_t qx, fp8_t qy, ep_t p)
void pp_add_k54_basic (fp54_t l, fp9_t rx, fp9_t ry, fp9_t qx, fp9_t qy, ep_t p)
void pp_add_k54_projc (fp54_t l, fp9_t rx, fp9_t ry, fp9_t rz, fp9_t qx, fp9_t qy, ep_t p)
void pp_dbl_k2_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
void pp_dbl_k2_projc_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
void pp_dbl_k2_projc_lazyr (fp2_t l, ep_t r, ep_t p, ep_t q)
void pp_dbl_k8_basic (fp8_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k8_projc_basic (fp8_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k8_projc_lazyr (fp8_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k12_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k12_projc_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k12_projc_lazyr (fp12_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k48_basic (fp48_t l, fp8_t rx, fp8_t ry, ep_t p)
void pp_dbl_k48_projc (fp48_t l, fp8_t rx, fp8_t ry, fp8_t rz, ep_t p)
void pp_dbl_k54_basic (fp54_t l, fp9_t rx, fp9_t ry, ep_t p)
void pp_dbl_k54_projc (fp54_t l, fp9_t rx, fp9_t ry, fp9_t rz, ep_t p)
void pp_dbl_lit_k12 (fp12_t l, ep_t r, ep_t p, ep2_t q)
void pp_exp_k2 (fp2_t c, fp2_t a)
void pp_exp_k8 (fp8_t c, fp8_t a)
void pp_exp_k12 (fp12_t c, fp12_t a)
void pp_exp_k48 (fp48_t c, fp48_t a)
void pp_exp_k54 (fp54_t c, fp54_t a)
void pp_norm_k2 (ep_t c, ep_t a)
void pp_norm_k8 (ep2_t c, ep2_t a)
void pp_norm_k12 (ep2_t c, ep2_t a)
void pp_map_tatep_k2 (fp2_t r, ep_t p, ep_t q)
void pp_map_sim_tatep_k2 (fp2_t r, ep_t *p, ep_t *q, int m)
void pp_map_weilp_k2 (fp2_t r, ep_t p, ep_t q)
void pp_map_oatep_k8 (fp8_t r, ep_t p, ep2_t q)
void pp_map_sim_weilp_k2 (fp2_t r, ep_t *p, ep_t *q, int m)
void pp_map_tatep_k12 (fp12_t r, ep_t p, ep2_t q)
void pp_map_sim_tatep_k12 (fp12_t r, ep_t *p, ep2_t *q, int m)
void pp_map_weilp_k12 (fp12_t r, ep_t p, ep2_t q)
void pp_map_sim_weilp_k12 (fp12_t r, ep_t *p, ep2_t *q, int m)
void pp_map_oatep_k12 (fp12_t r, ep_t p, ep2_t q)
void pp_map_sim_oatep_k12 (fp12_t r, ep_t *p, ep2_t *q, int m)
void pp_map_k48 (fp48_t r, ep_t p, fp8_t qx, fp8_t qy)
void pp_map_k54 (fp54_t r, ep_t p, fp9_t qx, fp9_t qy)
Detailed Description
Interface of the module for computing bilinear pairings over prime elliptic curves.
Definition in file relic_pp.h.
Macro Definition Documentation
pp_map_sim_k2
#define pp_map_sim_k2 (R, P, Q, M) pp_map_sim_tatep_k2(R, P, Q, M)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2.
Parameters
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] P - the second point to add.
[in] Q - the affine point to evaluate the line function. Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using projective coordinates.
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] P - the second point to add.
[in] Q - the affine point to evaluate the line function. Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8.
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function. Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates.
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function. Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12.
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function. Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function. Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48.
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function. Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54.
[out] L - the result of the evaluation.
[in,out] R - the resulting point and first point to add.
[in] Q - the second point to add.
[in] P - the affine point to evaluate the line function. Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2.
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] P - the point to double.
[in] Q - the affine point to evaluate the line function. Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8.
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function. Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12.
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function. Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
[out] L - the result of the evaluation.
[in,out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function. Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using projective coordinates.
[out] L - the result of the evaluation.
[in,out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function. Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
[out] L - the result of the evaluation.
[in,out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function. Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48.
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function. Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54.
[out] L - the result of the evaluation.
[out] R - the resulting point.
[in] Q - the point to double.
[in] P - the affine point to evaluate the line function. Computes a pairing of two prime elliptic curve points defined on an elliptic curves of embedding degree 2. Computes e(P, Q).
[out] R - the result.
[in] P - the first elliptic curve point.
[in] Q - the second elliptic curve point. Computes a pairing of two prime elliptic curve points defined on an elliptic curve of embedding degree 12. Computes e(P, Q).
[out] R - the result.
[in] P - the first elliptic curve point.
[in] Q - the second elliptic curve point. Computes a multi-pairing of elliptic curve points defined on an elliptic curve of embedding degree 2. Computes \prod e(P_i, Q_i).
[out] R - the result.
[in] P - the first pairing arguments.
[in] Q - the second pairing arguments.
[in] M - the number of pairings to evaluate.
Definition at line 338 of file relic_pp.h.
Function Documentation
pp_map_init()
void pp_map_init (void)
Computes a multi-pairing of elliptic curve points defined on an elliptic curve of embedding degree 12. Computes \prod e(P_i, Q_i).
Parameters
[out] R - the result.
[in] P - the first pairing arguments.
[in] Q - the second pairing arguments.
[in] M - the number of pairings to evaluate. Initializes the pairing over prime fields.
Definition at line 40 of file relic_pp_map.c.
References ep2_curve_init().
Referenced by core_init().
pp_map_clean()
void pp_map_clean (void)
Finalizes the pairing over prime fields.
Definition at line 44 of file relic_pp_map.c.
References ep2_curve_clean().
Referenced by core_clean().
pp_add_k2_basic()
void pp_add_k2_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_add_k2.c.
References CATCH_ANY, ep_add_slp_basic(), ep_copy(), ep_null, ERR_CAUGHT, FINALLY, fp_null, THROW, TRY, ep_st::x, and ep_st::y.
pp_add_k2_projc_basic()
void pp_add_k2_projc_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 75 of file relic_pp_add_k2.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_null, ep_st::norm, THROW, TRY, ep_st::x, ep_st::y, and ep_st::z.
pp_add_k2_projc_lazyr()
void pp_add_k2_projc_lazyr (fp2_t l, ep_t r, ep_t p, ep_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 157 of file relic_pp_add_k2.c.
References CATCH_ANY, dv_null, ERR_CAUGHT, FINALLY, fp_muln_low(), fp_null, fp_rdcn_low(), fp_subc_low(), ep_st::norm, THROW, TRY, ep_st::x, ep_st::y, and ep_st::z.
pp_add_k8_basic()
void pp_add_k8_basic (fp8_t l, ep2_t r, ep2_t q, ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_add_k8.c.
References CATCH_ANY, ep2_add_slp_basic(), ep2_copy(), ep2_curve_is_twist(), ep2_null, EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, fp_copy(), THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, and ep_st::y.
pp_add_k8_projc_basic()
void pp_add_k8_projc_basic (fp8_t l, ep2_t r, ep2_t q, ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 85 of file relic_pp_add_k8.c.
References CATCH_ANY, ep2_curve_is_twist(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_new, fp2_null, ep2_st::norm, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_add_k8_projc_lazyr()
void pp_add_k8_projc_lazyr (fp8_t l, ep2_t r, ep2_t q, ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 178 of file relic_pp_add_k8.c.
References CATCH_ANY, ep2_curve_is_twist(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_new, fp2_null, ep2_st::norm, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_add_k12_basic()
void pp_add_k12_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_add_k12.c.
References CATCH_ANY, ep2_add_slp_basic(), ep2_copy(), ep2_curve_is_twist(), ep2_null, EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, and ep_st::y.
pp_add_k12_projc_basic()
void pp_add_k12_projc_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 85 of file relic_pp_add_k12.c.
References CATCH_ANY, ep2_curve_is_twist(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_free, fp2_neg(), fp2_new, fp2_null, ep2_st::norm, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_add_k12_projc_lazyr()
void pp_add_k12_projc_lazyr (fp12_t l, ep2_t r, ep2_t q, ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 173 of file relic_pp_add_k12.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ep2_curve_is_twist(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_free, fp2_mulc_low(), fp2_muln_low(), fp2_neg(), fp2_new, fp2_null, fp2_rdcn_low(), fp2_subc_low(), ep2_st::norm, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_add_lit_k12()
void pp_add_lit_k12 (fp12_t l, ep_t r, ep_t p, ep2_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 261 of file relic_pp_add_k12.c.
References CATCH_ANY, ep2_curve_is_twist(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_neg(), fp_null, ep_st::norm, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep_st::z.
Referenced by pp_mil_lit_k12().
pp_add_k48_basic()
void pp_add_k48_basic (fp48_t l, fp8_t rx, fp8_t ry, fp8_t qx, fp8_t qy, ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 107 of file relic_pp_add_k48.c.
References CATCH_ANY, ep8_add_basic(), ERR_CAUGHT, FINALLY, fp48_zero(), fp8_copy(), fp8_free, fp8_new, fp8_null, fp8_sub(), THROW, TRY, ep_st::x, and ep_st::y.
pp_add_k48_projc()
void pp_add_k48_projc (fp48_t l, fp8_t rx, fp8_t ry, fp8_t rz, fp8_t qx, fp8_t qy, ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 152 of file relic_pp_add_k48.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_free, fp8_neg(), fp8_new, fp8_null, fp8_sub(), THROW, TRY, ep_st::x, and ep_st::y.
pp_add_k54_basic()
void pp_add_k54_basic (fp54_t l, fp9_t rx, fp9_t ry, fp9_t qx, fp9_t qy, ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 107 of file relic_pp_add_k54.c.
References CATCH_ANY, ep9_add_basic(), ERR_CAUGHT, FINALLY, fp54_zero(), fp9_copy(), fp9_free, fp9_new, fp9_null, fp9_sub(), THROW, TRY, ep_st::x, and ep_st::y.
pp_add_k54_projc()
void pp_add_k54_projc (fp54_t l, fp9_t rx, fp9_t ry, fp9_t rz, fp9_t qx, fp9_t qy, ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 153 of file relic_pp_add_k54.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_add(), fp9_free, fp9_neg(), fp9_new, fp9_null, fp9_sub(), THROW, TRY, ep_st::x, and ep_st::y.
pp_dbl_k2_basic()
void pp_dbl_k2_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k2.c.
References CATCH_ANY, ep_copy(), ep_dbl_slp_basic(), ep_null, ERR_CAUGHT, FINALLY, fp_copy(), fp_null, THROW, TRY, ep_st::x, and ep_st::y.
pp_dbl_k2_projc_basic()
void pp_dbl_k2_projc_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 75 of file relic_pp_dbl_k2.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_null, ep_st::norm, THROW, TRY, ep_st::x, ep_st::y, and ep_st::z.
pp_dbl_k2_projc_lazyr()
void pp_dbl_k2_projc_lazyr (fp2_t l, ep_t r, ep_t p, ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 164 of file relic_pp_dbl_k2.c.
References CATCH_ANY, dv_null, ERR_CAUGHT, FINALLY, fp_addc_low(), fp_muln_low(), fp_null, fp_rdcn_low(), fp_sqrn_low(), fp_subc_low(), fp_subm_low(), ep_st::norm, THROW, TRY, ep_st::x, ep_st::y, and ep_st::z.
pp_dbl_k8_basic()
void pp_dbl_k8_basic (fp8_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k8.c.
References CATCH_ANY, ep2_copy(), ep2_curve_is_twist(), ep2_dbl_slp_basic(), ep2_null, EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, fp_copy(), THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, and ep_st::y.
pp_dbl_k8_projc_basic()
void pp_dbl_k8_projc_basic (fp8_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 153 of file relic_pp_dbl_k8.c.
References CATCH_ANY, ep2_curve_is_twist(), ep_curve_get_a(), ep_curve_opt_a(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_mul_art(), fp2_new, fp2_null, fp2_zero(), fp_mul_dig(), RLC_ONE, RLC_TINY, RLC_ZERO, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_dbl_k8_projc_lazyr()
void pp_dbl_k8_projc_lazyr (fp8_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 261 of file relic_pp_dbl_k8.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ep2_curve_is_twist(), ep_curve_get_a(), ep_curve_opt_a(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_mul_art(), fp2_new, fp2_null, fp2_zero(), fp_mul_dig(), RLC_ONE, RLC_TINY, RLC_TWO, RLC_ZERO, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_dbl_k12_basic()
void pp_dbl_k12_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k12.c.
References CATCH_ANY, ep2_copy(), ep2_curve_is_twist(), ep2_dbl_slp_basic(), ep2_null, EP_MTYPE, ERR_CAUGHT, FINALLY, fp12_zero(), fp2_free, fp2_new, fp2_null, fp_copy(), THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, and ep_st::y.
pp_dbl_k12_projc_basic()
void pp_dbl_k12_projc_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 85 of file relic_pp_dbl_k12.c.
References CATCH_ANY, ep2_curve_get_b(), ep2_curve_is_twist(), ep_curve_opt_b(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, ep2_st::norm, RLC_TWO, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_dbl_k12_projc_lazyr()
void pp_dbl_k12_projc_lazyr (fp12_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 239 of file relic_pp_dbl_k12.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ep2_curve_get_b(), ep2_curve_is_twist(), ep_curve_opt_b(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_addd_low(), fp2_free, fp2_new, fp2_null, fp2_rdcn_low(), fp2_sqrn_low(), fp2_subc_low(), ep2_st::norm, RLC_TWO, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_dbl_k48_basic()
void pp_dbl_k48_basic (fp48_t l, fp8_t rx, fp8_t ry, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 101 of file relic_pp_dbl_k48.c.
References CATCH_ANY, ep8_dbl_basic(), ERR_CAUGHT, FINALLY, fp48_zero(), fp8_copy(), fp8_free, fp8_new, fp8_null, fp8_sub(), fp_copy(), THROW, TRY, ep_st::x, and ep_st::y.
pp_dbl_k48_projc()
void pp_dbl_k48_projc (fp48_t l, fp8_t rx, fp8_t ry, fp8_t rz, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 145 of file relic_pp_dbl_k48.c.
References CATCH_ANY, ep_curve_get_b(), ERR_CAUGHT, FINALLY, fp8_add(), fp8_dbl(), fp8_free, fp8_new, fp8_null, fp8_sub(), fp8_zero(), fp_copy(), THROW, TRY, ep_st::x, and ep_st::y.
pp_dbl_k54_basic()
void pp_dbl_k54_basic (fp54_t l, fp9_t rx, fp9_t ry, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 101 of file relic_pp_dbl_k54.c.
References CATCH_ANY, ep9_dbl_basic(), ERR_CAUGHT, FINALLY, fp54_zero(), fp9_copy(), fp9_free, fp9_new, fp9_null, fp9_sub(), fp_copy(), THROW, TRY, ep_st::x, and ep_st::y.
pp_dbl_k54_projc()
void pp_dbl_k54_projc (fp54_t l, fp9_t rx, fp9_t ry, fp9_t rz, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 54 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 146 of file relic_pp_dbl_k54.c.
References CATCH_ANY, ep_curve_get_b(), ERR_CAUGHT, FINALLY, fp9_add(), fp9_dbl(), fp9_free, fp9_new, fp9_null, fp9_sub(), fp9_zero(), fp_copy(), THROW, TRY, ep_st::x, and ep_st::y.
pp_dbl_lit_k12()
void pp_dbl_lit_k12 (fp12_t l, ep_t r, ep_t p, ep2_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 408 of file relic_pp_dbl_k12.c.
References CATCH_ANY, ep2_curve_is_twist(), ep_curve_get_b(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp_null, fp_zero(), ep_st::norm, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep_st::z.
Referenced by pp_mil_lit_k12().
pp_exp_k2()
void pp_exp_k2 (fp2_t c, fp2_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 2. Computes c = a^(p^2 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 40 of file relic_pp_exp_k2.c.
References bn_add_dig(), bn_div(), bn_free(), bn_null, CATCH_ANY, bn_st::dp, dv_copy(), ep_curve_get_ord(), ERR_CAUGHT, FINALLY, fp2_conv_cyc(), fp2_exp_cyc(), fp_prime_get(), RLC_FP_DIGS, RLC_POS, bn_st::sign, THROW, TRY, and bn_st::used.
Referenced by gt_rand(), pp_map_sim_tatep_k2(), and pp_map_tatep_k2().
pp_exp_k8()
void pp_exp_k8 (fp8_t c, fp8_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 8. Computes c = a^(p^8 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 40 of file relic_pp_exp_k8.c.
References bn_add_dig(), bn_free(), bn_lsh(), bn_null, bn_rsh(), bn_set_dig(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_conv_cyc(), fp8_copy(), fp8_exp_cyc(), fp8_frb(), fp8_free, fp8_inv_cyc(), fp8_new, fp8_null, fp8_sqr_cyc(), fp_prime_get_par(), THROW, and TRY.
Referenced by pp_map_oatep_k8().
pp_exp_k12()
void pp_exp_k12 (fp12_t c, fp12_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 12. Computes c = a^(p^12 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 220 of file relic_pp_exp_k12.c.
References EP_B12, EP_BN, ep_curve_is_pairf(), pp_exp_b12(), and pp_exp_bn().
Referenced by gt_rand(), pp_map_oatep_k12(), pp_map_sim_oatep_k12(), pp_map_sim_tatep_k12(), and pp_map_tatep_k12().
pp_exp_k48()
void pp_exp_k48 (fp48_t c, fp48_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 48. Computes c = a^(p^48 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 40 of file relic_pp_exp_k48.c.
References bn_free(), bn_null, bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp48_conv_cyc(), fp48_exp_cyc_sps(), fp48_frb(), fp48_free, fp48_inv_cyc(), fp48_new, fp48_null, fp_prime_get_par(), fp_prime_get_par_sps(), THROW, and TRY.
Referenced by pp_map_k48().
pp_exp_k54()
void pp_exp_k54 (fp54_t c, fp54_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 54. Computes c = a^(p^54 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 41 of file relic_pp_exp_k54.c.
References bn_free(), bn_null, bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp54_conv_cyc(), fp54_copy(), fp54_exp_cyc_sps(), fp54_frb(), fp54_free, fp54_inv_cyc(), fp54_new, fp54_null, fp_prime_get_par(), fp_prime_get_par_sps(), THROW, and TRY.
Referenced by pp_map_k54().
pp_norm_k2()
void pp_norm_k2 (ep_t c, ep_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 2.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 42 of file relic_pp_norm.c.
References ep_norm().
pp_norm_k8()
void pp_norm_k8 (ep2_t c, ep2_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 8.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 46 of file relic_pp_norm.c.
References ep2_copy(), ep2_is_infty(), ep2_set_infty(), fp2_inv(), fp2_set_dig(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
pp_norm_k12()
void pp_norm_k12 (ep2_t c, ep2_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 12.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 66 of file relic_pp_norm.c.
References ep2_copy(), ep2_is_infty(), ep2_set_infty(), fp2_inv(), fp_set_dig(), fp_zero(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
pp_map_tatep_k2()
void pp_map_tatep_k2 (fp2_t r, ep_t p, ep_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 161 of file relic_pp_map_k2.c.
References bn_free(), bn_null, bn_sub_dig(), CATCH_ANY, ep_curve_get_ord(), ep_is_infty(), ep_norm(), ep_null, ERR_CAUGHT, FINALLY, fp2_set_dig(), pp_exp_k2(), pp_mil_k2(), THROW, and TRY.
pp_map_sim_tatep_k2()
void pp_map_sim_tatep_k2 (fp2_t r, ep_t * p, ep_t * q, int m)
Computes the Tate multi-pairing of in a parameterized elliptic curve with embedding degree 2.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 197 of file relic_pp_map_k2.c.
References bn_free(), bn_null, bn_sub_dig(), CATCH_ANY, ep_curve_get_ord(), ep_is_infty(), ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp2_set_dig(), pp_exp_k2(), pp_mil_k2(), RLC_ALLOCA, RLC_FREE, THROW, and TRY.
pp_map_weilp_k2()
void pp_map_weilp_k2 (fp2_t r, ep_t p, ep_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 2.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 255 of file relic_pp_map_k2.c.
References bn_free(), bn_null, bn_sub_dig(), CATCH_ANY, ep_curve_get_ord(), ep_is_infty(), ep_norm(), ep_null, ERR_CAUGHT, FINALLY, fp2_free, fp2_inv(), fp2_inv_cyc(), fp2_new, fp2_null, fp2_set_dig(), pp_mil_k2(), pp_mil_lit_k2(), THROW, and TRY.
pp_map_oatep_k8()
void pp_map_oatep_k8 (fp8_t r, ep_t p, ep2_t q)
Computes the optimal ate pairing of two points in a parameterized elliptic curve with embedding degree 8.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 123 of file relic_pp_map_k8.c.
References bn_free(), bn_null, bn_sign(), CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, ep_is_infty(), ep_norm(), ep_null, ERR_CAUGHT, FINALLY, fp8_inv_cyc(), fp8_set_dig(), fp_prime_get_par(), pp_exp_k8(), pp_mil_k8(), RLC_NEG, THROW, and TRY.
pp_map_sim_weilp_k2()
void pp_map_sim_weilp_k2 (fp2_t r, ep_t * p, ep_t * q, int m)
Computes the Weil multi-pairing of in a parameterized elliptic curve with embedding degree 2.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 309 of file relic_pp_map_k2.c.
References bn_free(), bn_null, bn_sub_dig(), CATCH_ANY, ep_curve_get_ord(), ep_is_infty(), ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp2_free, fp2_inv(), fp2_inv_cyc(), fp2_new, fp2_null, fp2_set_dig(), pp_mil_k2(), pp_mil_lit_k2(), RLC_ALLOCA, RLC_FREE, THROW, and TRY.
pp_map_tatep_k12()
void pp_map_tatep_k12 (fp12_t r, ep_t p, ep2_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 239 of file relic_pp_map_k12.c.
References bn_free(), bn_null, CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, ep_curve_get_ord(), ep_is_infty(), ep_norm(), ep_null, ERR_CAUGHT, FINALLY, fp12_set_dig(), pp_exp_k12(), pp_mil_lit_k12(), THROW, and TRY.
pp_map_sim_tatep_k12()
void pp_map_sim_tatep_k12 (fp12_t r, ep_t * p, ep2_t * q, int m)
Computes the Tate multi-pairing of in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 276 of file relic_pp_map_k12.c.
References bn_free(), bn_null, CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, ep_curve_get_ord(), ep_is_infty(), ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp12_set_dig(), pp_exp_k12(), pp_mil_lit_k12(), RLC_ALLOCA, RLC_FREE, THROW, and TRY.
pp_map_weilp_k12()
void pp_map_weilp_k12 (fp12_t r, ep_t p, ep2_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 333 of file relic_pp_map_k12.c.
References bn_free(), bn_null, bn_sub_dig(), CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, ep_curve_get_ord(), ep_is_infty(), ep_norm(), ep_null, ERR_CAUGHT, FINALLY, fp12_free, fp12_inv(), fp12_inv_cyc(), fp12_new, fp12_null, fp12_set_dig(), pp_mil_k12(), pp_mil_lit_k12(), THROW, and TRY.
pp_map_sim_weilp_k12()
void pp_map_sim_weilp_k12 (fp12_t r, ep_t * p, ep2_t * q, int m)
Computes the Weil multi-pairing of in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 387 of file relic_pp_map_k12.c.
References bn_free(), bn_null, bn_sub_dig(), CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, ep_curve_get_ord(), ep_is_infty(), ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp12_free, fp12_inv(), fp12_inv_cyc(), fp12_new, fp12_null, fp12_set_dig(), pp_mil_k12(), pp_mil_lit_k12(), RLC_ALLOCA, RLC_FREE, THROW, and TRY.
pp_map_oatep_k12()
void pp_map_oatep_k12 (fp12_t r, ep_t p, ep2_t q)
Computes the optimal ate pairing of two points in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 463 of file relic_pp_map_k12.c.
References bn_add_dig(), bn_free(), bn_mul_dig(), bn_null, bn_sign(), CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, EP_B12, EP_BN, ep_curve_is_pairf(), ep_is_infty(), ep_norm(), ep_null, ERR_CAUGHT, FINALLY, fp12_inv_cyc(), fp12_set_dig(), fp_prime_get_par(), pp_exp_k12(), pp_fin_k12_oatep(), pp_mil_k12(), RLC_NEG, THROW, and TRY.
pp_map_sim_oatep_k12()
void pp_map_sim_oatep_k12 (fp12_t r, ep_t * p, ep2_t * q, int m)
Computes the optimal ate multi-pairing of in a parameterized elliptic curve with embedding degree 12.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 523 of file relic_pp_map_k12.c.
References bn_add_dig(), bn_free(), bn_mul_dig(), bn_null, bn_sign(), CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, EP_B12, EP_BN, ep_curve_is_pairf(), ep_is_infty(), ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp12_inv_cyc(), fp12_set_dig(), fp_prime_get_par(), pp_exp_k12(), pp_fin_k12_oatep(), pp_mil_k12(), RLC_ALLOCA, RLC_FREE, RLC_NEG, THROW, and TRY.
pp_map_k48()
void pp_map_k48 (fp48_t r, ep_t p, fp8_t qx, fp8_t qy)
Computes the Optimal Ate pairing of two points in a parameterized elliptic curve with embedding degree 48.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 105 of file relic_pp_map_k48.c.
References bn_free(), bn_null, bn_sign(), CATCH_ANY, EP_B48, ep_curve_is_pairf(), ep_is_infty(), ERR_CAUGHT, FINALLY, fp48_inv_cyc(), fp48_set_dig(), fp8_is_zero(), fp_prime_get_par(), pp_exp_k48(), pp_mil_k48(), RLC_NEG, THROW, and TRY.
pp_map_k54()
void pp_map_k54 (fp54_t r, ep_t p, fp9_t qx, fp9_t qy)
Computes the Optimal Ate pairing of two points in a parameterized elliptic curve with embedding degree 54.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 162 of file relic_pp_map_k54.c.
References bn_free(), bn_null, bn_sign(), CATCH_ANY, ep_curve_is_pairf(), ep_is_infty(), EP_K54, ERR_CAUGHT, FINALLY, fp54_inv_cyc(), fp54_set_dig(), fp9_is_zero(), fp_prime_get_par(), pp_exp_k54(), pp_mil_k54(), RLC_NEG, THROW, and TRY.