RELIC: src/fp/relic_fp_inv.c File Reference
relic_fp_inv.c File Reference
Prime field arithmetic
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_bn_low.h"
#include "assert.h"
Functions
void fp_inv_basic (fp_t c, const fp_t a)
void fp_inv_binar (fp_t c, const fp_t a)
void fp_inv_monty (fp_t c, const fp_t a)
void fp_inv_exgcd (fp_t c, const fp_t a)
void fp_inv_divst (fp_t c, const fp_t a)
void fp_inv_lower (fp_t c, const fp_t a)
void fp_inv_sim (fp_t *c, const fp_t *a, int n)
Detailed Description
Implementation of the prime field inversion functions.
Definition in file relic_fp_inv.c.
Function Documentation
fp_inv_basic()
void fp_inv_basic (fp_t c, const fp_t a)
Inverts a prime field element using Fermat's Little Theorem.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 42 of file relic_fp_inv.c.
References bn_free(), bn_null, bn_sub_dig(), CATCH_ANY, bn_st::dp, dv_copy(), ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp_is_zero(), fp_prime_get(), RLC_FP_DIGS, THROW, TRY, and bn_st::used.
fp_inv_binar()
void fp_inv_binar (fp_t c, const fp_t a)
Inverts a prime field element using the binary method.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 72 of file relic_fp_inv.c.
References bn_add(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free(), bn_hlv(), bn_null, bn_set_dig(), bn_sign(), bn_sub(), bn_zero(), CATCH_ANY, bn_st::dp, dv_copy(), ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp_is_zero(), fp_prime_back(), fp_prime_conv(), fp_prime_get(), fp_rsh1_low(), RLC_EQ, RLC_FP_DIGS, RLC_GT, RLC_LT, RLC_NEG, THROW, TRY, and bn_st::used.
fp_inv_monty()
void fp_inv_monty (fp_t c, const fp_t a)
Inverts a prime field element using Montgomery inversion.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 188 of file relic_fp_inv.c.
References bn_add(), bn_cmp(), bn_dbl(), bn_free(), bn_is_zero(), bn_mod_monty_back(), bn_mod_monty_conv(), bn_null, bn_read_raw(), bn_set_2b(), bn_set_dig(), bn_sub1_low(), bn_subn_low(), bn_trim(), bn_zero(), CATCH_ANY, bn_st::dp, dv_cmp(), dv_copy(), dv_zero(), ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp_copy(), fp_is_zero(), fp_prime_get(), fp_prime_get_conv(), fp_rsh1_low(), fp_subn_low(), fp_zero(), RLC_DIG, RLC_FP_DIGS, RLC_GT, RLC_LT, THROW, TRY, and bn_st::used.
fp_inv_exgcd()
void fp_inv_exgcd (fp_t c, const fp_t a)
Inverts a prime field element using the Euclidean Extended Algorithm.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 330 of file relic_fp_inv.c.
References bn_add(), bn_cmp_dig(), bn_copy(), bn_div_rem(), bn_free(), bn_null, bn_set_dig(), bn_sign(), bn_sub(), bn_zero(), CATCH_ANY, bn_st::dp, dv_copy(), ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp_is_zero(), fp_prime_back(), fp_prime_conv(), fp_prime_get(), RLC_EQ, RLC_FP_DIGS, RLC_NEG, THROW, TRY, and bn_st::used.
fp_inv_divst()
void fp_inv_divst (fp_t c, const fp_t a)
Inverts a prime field element using the constant-time division step approach by Bernstein and Bo-Yin Yang.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 402 of file relic_fp_inv.c.
References bn_free(), bn_null, bn_set_dig(), CATCH_ANY, bn_st::dp, dv_copy(), dv_copy_cond(), dv_null, dv_swap_cond(), dv_zero(), ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp_add1_low(), fp_add_dig(), fp_addm_low(), fp_addn_low(), fp_is_zero(), fp_negm_low(), fp_null, FP_PRIME, fp_prime_back(), fp_prime_get(), fp_rsh1_low(), fp_set_dig(), fp_zero(), RLC_DIG, RLC_FP_DIGS, RLC_POS, RLC_SEL, THROW, TRY, and bn_st::used.
fp_inv_lower()
void fp_inv_lower (fp_t c, const fp_t a)
Inverts a prime field element using a direct call to the lower layer.
Parameters
[out] c - the result.
[in] a - the prime field element to invert.
Exceptions
ERR_NO_VALID - if the field element is not invertible.
Definition at line 506 of file relic_fp_inv.c.
References fp_invn_low().
fp_inv_sim()
void fp_inv_sim (fp_t * c, const fp_t * a, int n)
Inverts multiple prime field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the prime field elements to invert.
[in] n - the number of elements.
Definition at line 512 of file relic_fp_inv.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp_copy(), fp_null, RLC_ALLOCA, RLC_FREE, THROW, and TRY.
Referenced by ed_norm_sim(), and ep_norm_sim().