RELIC: src/cp/relic_cp_zss.c File Reference
relic_cp_zss.c File Reference
Cryptographic protocols
#include "relic.h"
#include "relic_test.h"
#include "relic_bench.h"
Functions
int cp_zss_gen (bn_t d, g1_t q, gt_t z)
int cp_zss_sig (g2_t s, uint8_t *msg, int len, int hash, bn_t d)
int cp_zss_ver (g2_t s, uint8_t *msg, int len, int hash, g1_t q, gt_t z)
Detailed Description
Implementation of the Zhang-Safavi-Naini-Susilo short signature protocol.
Definition in file relic_cp_zss.c.
Function Documentation
cp_zss_gen()
int cp_zss_gen (bn_t d, g1_t q, gt_t z)
Generates a Zhang-Safavi-Naini-Susilo (ZSS) key pair.
Parameters
[out] d - the private key.
[out] q - the first component of the public key.
[out] z - the second component of the public key.
Definition at line 41 of file relic_cp_zss.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, FINALLY, g1_get_gen, g1_mul_gen, g2_free, g2_get_gen, g2_get_ord, g2_new, g2_null, pc_map, result, RLC_ERR, RLC_OK, and TRY.
cp_zss_sig()
int cp_zss_sig (g2_t s, uint8_t * msg, int len, int hash, bn_t d)
Signs a message using ZSS scheme.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[in] d - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 74 of file relic_cp_zss.c.
References bn_add(), bn_free(), bn_mod, bn_null, bn_read_bin(), bn_sign(), CATCH_ANY, FINALLY, g1_get_ord, g2_mul_gen, result, RLC_ERR, RLC_NEG, RLC_OK, and TRY.
cp_zss_ver()
int cp_zss_ver (g2_t s, uint8_t * msg, int len, int hash, g1_t q, gt_t z)
Verifies a message signed with ZSS scheme.
Parameters
[in] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] hash - the flag to indicate the message format.
[out] q - the first component of the public key.
[out] z - the second component of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 124 of file relic_cp_zss.c.
References bn_free(), bn_mod, bn_null, bn_read_bin(), CATCH_ANY, ERR_CAUGHT, FINALLY, g1_add, g1_free, g1_get_ord, g1_mul_gen, g1_new, g1_norm, g1_null, gt_cmp, gt_free, gt_new, gt_null, pc_map, result, RLC_EQ, THROW, and TRY.