RELIC: src/epx/relic_ep8_cmp.c File Reference
relic_ep8_cmp.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
int ep8_cmp (const ep8_t p, const ep8_t q)
Detailed Description
Implementation of utilities for prime elliptic curves over an octic extension field.
Definition in file relic_ep8_cmp.c.
Function Documentation
ep8_cmp()
int ep8_cmp (const ep8_t p, const ep8_t q)
Compares two elliptic curve points.
Parameters
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 39 of file relic_ep8_cmp.c.
References ep8_copy(), ep8_free, ep8_is_infty(), ep8_new, ep8_null, ERR_CAUGHT, fp8_cmp(), fp8_mul, fp8_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.