RELIC: src/fpx/relic_fp8_mul.c File Reference
relic_fp8_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp8_mul_basic (fp8_t c, fp8_t a, fp8_t b)
static void fp4_mul_dxs_unr (dv4_t c, fp4_t a, fp4_t b)
void fp8_mul_dxs (fp8_t c, fp8_t a, fp8_t b)
void fp8_mul_unr (dv8_t c, fp8_t a, fp8_t b)
void fp8_mul_lazyr (fp8_t c, fp8_t a, fp8_t b)
void fp8_mul_art (fp8_t c, fp8_t a)
Detailed Description
Implementation of multiplication in an octic extension of a prime field.
Definition in file relic_fp8_mul.c.
Function Documentation
fp8_mul_basic()
void fp8_mul_basic (fp8_t c, fp8_t a, fp8_t b)
Multiples two octic extension field elements.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 42 of file relic_fp8_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp4_add(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sub(), THROW, and TRY.
fp4_mul_dxs_unr()
static void fp4_mul_dxs_unr (dv4_t c, fp4_t a, fp4_t b) static
Definition at line 87 of file relic_fp8_mul.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ERR_CAUGHT, FINALLY, fp2_addm_low(), fp2_addn_low(), fp2_free, fp2_mulc_low(), fp2_muln_low(), fp2_new, fp2_norh_low(), fp2_null, fp2_subc_low(), THROW, and TRY.
Referenced by fp8_mul_dxs().
fp8_mul_dxs()
void fp8_mul_dxs (fp8_t c, fp8_t a, fp8_t b)
Multiples a dense octic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - an octic extension field element.
[in] b - a sparse octic extension field element.
Definition at line 124 of file relic_fp8_mul.c.
References CATCH_ANY, dv4_free, dv4_new, dv4_null, dv_copy(), ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp4_add(), fp4_free, fp4_mul_dxs_unr(), fp4_mul_unr(), fp4_new, fp4_null, RLC_FP_DIGS, THROW, and TRY.
Referenced by pp_mil_k8().
fp8_mul_unr()
void fp8_mul_unr (dv8_t c, fp8_t a, fp8_t b)
Multiples two octic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 182 of file relic_fp8_mul.c.
References CATCH_ANY, dv4_free, dv4_new, dv4_null, dv_copy(), ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp4_add(), fp4_free, fp4_mul_unr(), fp4_new, fp4_null, RLC_FP_DIGS, THROW, and TRY.
Referenced by fp24_mul_unr(), fp24_sqr_unr(), and fp8_mul_lazyr().
fp8_mul_lazyr()
void fp8_mul_lazyr (fp8_t c, fp8_t a, fp8_t b)
Multiples two octic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 237 of file relic_fp8_mul.c.
References CATCH_ANY, dv8_free, dv8_new, dv8_null, ERR_CAUGHT, FINALLY, fp2_rdcn_low(), fp8_mul_unr(), THROW, and TRY.
fp8_mul_art()
void fp8_mul_art (fp8_t c, fp8_t a)
Multiplies an octic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the octic extension field element to multiply.
Definition at line 258 of file relic_fp8_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp4_copy(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, THROW, and TRY.
Referenced by fp24_inv(), fp24_mul_art(), fp24_mul_basic(), fp24_mul_dxs(), fp24_sqr_basic(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_frb(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), and fp48_sqr_pck_lazyr().