RELIC: src/epx/relic_ep8_neg.c File Reference
relic_ep8_neg.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
void ep8_neg (ep8_t r, const ep8_t p)
Detailed Description
Implementation of point negation on elliptic prime curves over an octic extension field.
Definition in file relic_ep8_neg.c.
Function Documentation
ep8_neg()
void ep8_neg (ep8_t r, const ep8_t p)
Negates a point represented in affine coordinates in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 39 of file relic_ep8_neg.c.
References ep8_is_infty(), ep8_set_infty(), fp8_copy(), and fp8_neg().
Referenced by ep8_mul_basic(), ep8_mul_fix_combd(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_sub(), and pp_mil_k48().