RELIC: src/pp/relic_pp_dbl_k24.c File Reference
relic_pp_dbl_k24.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
void pp_dbl_k24_basic (fp24_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_dbl_k24_projc (fp24_t l, ep4_t r, const ep4_t q, const ep_t p)
Detailed Description
Implementation of pairing computation for curves with embedding degree 24.
Definition in file relic_pp_dbl_k24.c.
Function Documentation
pp_dbl_k24_basic()
void pp_dbl_k24_basic (fp24_t l, ep4_t r, const ep4_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 24 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 42 of file relic_pp_dbl_k24.c.
References ep4_copy(), ep4_curve_is_twist(), ep4_dbl_slp_basic(), ep4_free, ep4_new, ep4_null, ERR_CAUGHT, fp24_zero(), fp2_free, fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_sub(), fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k24_projc()
void pp_dbl_k24_projc (fp24_t l, ep4_t r, const ep4_t q, const ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 24 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 89 of file relic_pp_dbl_k24.c.
References ep4_curve_get_b(), ep4_curve_is_twist(), ERR_CAUGHT, fp4_add(), fp4_dbl(), fp4_free, fp4_mul, fp4_mul_art(), fp4_new, fp4_null, fp4_sqr, fp4_sub(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.