RELIC: include/relic_fpx.h File Reference
relic_fpx.h File Reference
Prime field extensions.
#include "relic_fp.h"
#include "relic_types.h"
Macros
#define dv2_null(A) dv_null(A[0]); dv_null(A[1]); \
#define dv2_new(A) dv_new(A[0]); dv_new(A[1]); \
#define dv2_free(A) dv_free(A[0]); dv_free(A[1]); \
#define fp2_null(A) fp_null(A[0]); fp_null(A[1]); \
#define fp2_new(A) fp_new(A[0]); fp_new(A[1]); \
#define fp2_free(A) fp_free(A[0]); fp_free(A[1]); \
#define dv3_null(A) dv_null(A[0]); dv_null(A[1]); dv_null(A[2]); \
#define dv3_new(A) dv_new(A[0]); dv_new(A[1]); dv_new(A[2]); \
#define dv3_free(A) dv_free(A[0]); dv_free(A[1]); dv_free(A[2]); \
#define fp3_null(A) fp_null(A[0]); fp_null(A[1]); fp_null(A[2]); \
#define fp3_new(A) fp_new(A[0]); fp_new(A[1]); fp_new(A[2]); \
#define fp3_free(A) fp_free(A[0]); fp_free(A[1]); fp_free(A[2]); \
#define dv4_null(A) dv2_null(A[0]); dv2_null(A[1]); \
#define dv4_new(A) dv2_new(A[0]); dv2_new(A[1]); \
#define dv4_free(A) dv2_free(A[0]); dv2_free(A[1]); \
#define fp4_null(A) fp2_null(A[0]); fp2_null(A[1]); \
#define fp4_new(A) fp2_new(A[0]); fp2_new(A[1]); \
#define fp4_free(A) fp2_free(A[0]); fp2_free(A[1]); \
#define dv6_null(A) dv2_null(A[0]); dv2_null(A[1]); dv2_null(A[2]); \
#define dv6_new(A) dv2_new(A[0]); dv2_new(A[1]); dv2_new(A[2]); \
#define dv6_free(A) dv2_free(A[0]); dv2_free(A[1]); dv2_free(A[2]); \
#define fp6_null(A) fp2_null(A[0]); fp2_null(A[1]); fp2_null(A[2]); \
#define fp6_new(A) fp2_new(A[0]); fp2_new(A[1]); fp2_new(A[2]); \
#define fp6_free(A) fp2_free(A[0]); fp2_free(A[1]); fp2_free(A[2]); \
#define dv8_null(A) dv4_null(A[0]); dv4_null(A[1]); \
#define dv8_new(A) dv4_new(A[0]); dv4_new(A[1]); \
#define dv8_free(A) dv4_free(A[0]); dv4_free(A[1]); \
#define fp8_null(A) fp4_null(A[0]); fp4_null(A[1]); \
#define fp8_new(A) fp4_new(A[0]); fp4_new(A[1]); \
#define fp8_free(A) fp4_free(A[0]); fp4_free(A[1]); \
#define dv9_null(A) dv3_null(A[0]); dv3_null(A[1]); dv3_null(A[2]); \
#define dv9_new(A) dv3_new(A[0]); dv3_new(A[1]); dv3_new(A[2]); \
#define dv9_free(A) dv3_free(A[0]); dv3_free(A[1]); dv3_free(A[2]); \
#define fp9_null(A) fp3_null(A[0]); fp3_null(A[1]); fp3_null(A[2]); \
#define fp9_new(A) fp3_new(A[0]); fp3_new(A[1]); fp3_new(A[2]); \
#define fp9_free(A) fp3_free(A[0]); fp3_free(A[1]); fp3_free(A[2]); \
#define dv12_null(A) dv6_null(A[0]); dv6_null(A[1]); \
#define dv12_new(A) dv6_new(A[0]); dv6_new(A[1]); \
#define dv12_free(A) dv6_free(A[0]); dv6_free(A[1]); \
#define fp12_null(A) fp6_null(A[0]); fp6_null(A[1]); \
#define fp12_new(A) fp6_new(A[0]); fp6_new(A[1]); \
#define fp12_free(A) fp6_free(A[0]); fp6_free(A[1]); \
#define dv18_null(A) dv9_null(A[0]); dv9_null(A[1]); \
#define dv18_new(A) dv9_new(A[0]); dv9_new(A[1]); \
#define dv18_free(A) dv9_free(A[0]); dv9_free(A[1]); \
#define fp18_null(A) fp9_null(A[0]); fp9_null(A[1]); \
#define fp18_new(A) fp9_new(A[0]); fp9_new(A[1]); \
#define fp18_free(A) fp9_free(A[0]); fp9_free(A[1]); \
#define dv24_null(A) dv8_null(A[0]); dv8_null(A[1]); dv8_null(A[2]); \
#define dv24_new(A) dv8_new(A[0]); dv8_new(A[1]); dv8_new(A[2]); \
#define dv24_free(A) dv8_free(A[0]); dv8_free(A[1]); dv8_free(A[2]); \
#define fp24_null(A) fp8_null(A[0]); fp8_null(A[1]); fp8_null(A[2]); \
#define fp24_new(A) fp8_new(A[0]); fp8_new(A[1]); fp8_new(A[2]); \
#define fp24_free(A) fp8_free(A[0]); fp8_free(A[1]); fp8_free(A[2]); \
#define dv48_null(A) dv24_null(A[0]); dv24_null(A[1]); \
#define dv48_new(A) dv24_new(A[0]); dv24_new(A[1]); \
#define dv48_free(A) dv24_free(A[0]); dv24_free(A[1]); \
#define fp48_null(A) fp24_null(A[0]); fp24_null(A[1]); \
#define fp48_new(A) fp24_new(A[0]); fp24_new(A[1]); \
#define fp48_free(A) fp24_free(A[0]); fp24_free(A[1]); \
#define dv54_null(A) dv18_null(A[0]); dv18_null(A[1]); dv18_null(A[2]); \
#define dv54_new(A) dv18_new(A[0]); dv18_new(A[1]); dv18_new(A[2]); \
#define dv54_free(A) dv18_free(A[0]); dv18_free(A[1]); dv18_free(A[2]); \
#define fp54_null(A) fp18_null(A[0]); fp18_null(A[1]); fp18_null(A[2]); \
#define fp54_new(A) fp18_new(A[0]); fp18_new(A[1]); fp18_new(A[2]); \
#define fp54_free(A) fp18_free(A[0]); fp18_free(A[1]); fp18_free(A[2]); \
Typedefs
typedef fp_t fp2_t[2]
typedef dv_t dv2_t[2]
typedef fp_st fp2_st[2]
typedef fp_t fp3_t[3]
typedef dv_t dv3_t[3]
typedef fp_st fp3_st[3]
typedef fp2_t fp4_t[2]
typedef dv2_t dv4_t[2]
typedef fp2_st fp4_st[2]
typedef fp2_t fp6_t[3]
typedef dv2_t dv6_t[3]
typedef fp4_t fp8_t[2]
typedef dv4_t dv8_t[2]
typedef fp4_st fp8_st[2]
typedef fp3_t fp9_t[3]
typedef dv3_t dv9_t[3]
typedef fp3_st fp9_st[3]
typedef dv6_t dv12_t[2]
typedef fp6_t fp12_t[2]
typedef dv9_t dv18_t[2]
typedef fp9_t fp18_t[2]
typedef dv8_t dv24_t[3]
typedef fp8_t fp24_t[3]
typedef dv24_t dv48_t[2]
typedef fp24_t fp48_t[2]
typedef dv18_t dv54_t[3]
typedef fp18_t fp54_t[3]
Functions
void fp2_field_init (void)
int fp2_field_get_qnr (void)
void fp2_copy (fp2_t c, fp2_t a)
void fp2_zero (fp2_t a)
int fp2_is_zero (fp2_t a)
void fp2_rand (fp2_t a)
void fp2_print (fp2_t a)
int fp2_size_bin (fp2_t a, int pack)
void fp2_read_bin (fp2_t a, const uint8_t *bin, int len)
void fp2_write_bin (uint8_t *bin, int len, fp2_t a, int pack)
int fp2_cmp (fp2_t a, fp2_t b)
int fp2_cmp_dig (fp2_t a, dig_t b)
void fp2_set_dig (fp2_t a, dig_t b)
void fp2_add_basic (fp2_t c, fp2_t a, fp2_t b)
void fp2_add_integ (fp2_t c, fp2_t a, fp2_t b)
void fp2_sub_basic (fp2_t c, fp2_t a, fp2_t b)
void fp2_sub_integ (fp2_t c, fp2_t a, fp2_t b)
void fp2_neg (fp2_t c, fp2_t a)
void fp2_dbl_basic (fp2_t c, fp2_t a)
void fp2_dbl_integ (fp2_t c, fp2_t a)
void fp2_mul_basic (fp2_t c, fp2_t a, fp2_t b)
void fp2_mul_integ (fp2_t c, fp2_t a, fp2_t b)
void fp2_mul_art (fp2_t c, fp2_t a)
void fp2_mul_nor_basic (fp2_t c, fp2_t a)
void fp2_mul_nor_integ (fp2_t c, fp2_t a)
void fp2_mul_frb (fp2_t c, fp2_t a, int i, int j)
void fp2_sqr_basic (fp2_t c, fp2_t a)
void fp2_sqr_integ (fp2_t c, fp2_t a)
void fp2_inv (fp2_t c, fp2_t a)
void fp2_inv_cyc (fp2_t c, fp2_t a)
void fp2_inv_sim (fp2_t *c, fp2_t *a, int n)
int fp2_test_cyc (fp2_t a)
void fp2_conv_cyc (fp2_t c, fp2_t a)
void fp2_exp (fp2_t c, fp2_t a, bn_t b)
void fp2_exp_dig (fp2_t c, fp2_t a, dig_t b)
void fp2_exp_cyc (fp2_t c, fp2_t a, bn_t b)
void fp2_frb (fp2_t c, fp2_t a, int i)
int fp2_srt (fp2_t c, fp2_t a)
void fp2_pck (fp2_t c, fp2_t a)
int fp2_upk (fp2_t c, fp2_t a)
void fp3_field_init (void)
void fp3_copy (fp3_t c, fp3_t a)
void fp3_zero (fp3_t a)
int fp3_is_zero (fp3_t a)
void fp3_rand (fp3_t a)
void fp3_print (fp3_t a)
int fp3_size_bin (fp3_t a)
void fp3_read_bin (fp3_t a, const uint8_t *bin, int len)
void fp3_write_bin (uint8_t *bin, int len, fp3_t a)
int fp3_cmp (fp3_t a, fp3_t b)
int fp3_cmp_dig (fp3_t a, dig_t b)
void fp3_set_dig (fp3_t a, dig_t b)
void fp3_add_basic (fp3_t c, fp3_t a, fp3_t b)
void fp3_add_integ (fp3_t c, fp3_t a, fp3_t b)
void fp3_sub_basic (fp3_t c, fp3_t a, fp3_t b)
void fp3_sub_integ (fp3_t c, fp3_t a, fp3_t b)
void fp3_neg (fp3_t c, fp3_t a)
void fp3_dbl_basic (fp3_t c, fp3_t a)
void fp3_dbl_integ (fp3_t c, fp3_t a)
void fp3_mul_basic (fp3_t c, fp3_t a, fp3_t b)
void fp3_mul_integ (fp3_t c, fp3_t a, fp3_t b)
void fp3_mul_nor (fp3_t c, fp3_t a)
void fp3_mul_frb (fp3_t c, fp3_t a, int i, int j)
void fp3_sqr_basic (fp3_t c, fp3_t a)
void fp3_sqr_integ (fp3_t c, fp3_t a)
void fp3_inv (fp3_t c, fp3_t a)
void fp3_inv_sim (fp3_t *c, fp3_t *a, int n)
void fp3_exp (fp3_t c, fp3_t a, bn_t b)
void fp3_frb (fp3_t c, fp3_t a, int i)
int fp3_srt (fp3_t c, fp3_t a)
void fp4_copy (fp4_t c, fp4_t a)
void fp4_zero (fp4_t a)
int fp4_is_zero (fp4_t a)
void fp4_rand (fp4_t a)
void fp4_print (fp4_t a)
int fp4_size_bin (fp4_t a)
void fp4_read_bin (fp4_t a, const uint8_t *bin, int len)
void fp4_write_bin (uint8_t *bin, int len, fp4_t a)
int fp4_cmp (fp4_t a, fp4_t b)
int fp4_cmp_dig (fp4_t a, dig_t b)
void fp4_set_dig (fp4_t a, dig_t b)
void fp4_add (fp4_t c, fp4_t a, fp4_t b)
void fp4_sub (fp4_t c, fp4_t a, fp4_t b)
void fp4_neg (fp4_t c, fp4_t a)
void fp4_dbl (fp4_t c, fp4_t a)
void fp4_mul_unr (dv4_t c, fp4_t a, fp4_t b)
void fp4_mul_basic (fp4_t c, fp4_t a, fp4_t b)
void fp4_mul_lazyr (fp4_t c, fp4_t a, fp4_t b)
void fp4_mul_art (fp4_t c, fp4_t a)
void fp4_mul_dxs (fp4_t c, fp4_t a, fp4_t b)
void fp4_sqr_unr (dv6_t c, fp4_t a)
void fp4_sqr_basic (fp4_t c, fp4_t a)
void fp4_sqr_lazyr (fp4_t c, fp4_t a)
void fp4_inv (fp4_t c, fp4_t a)
void fp4_inv_cyc (fp4_t c, fp4_t a)
void fp4_exp (fp4_t c, fp4_t a, bn_t b)
void fp4_frb (fp4_t c, fp4_t a, int i)
void fp6_copy (fp6_t c, fp6_t a)
void fp6_zero (fp6_t a)
int fp6_is_zero (fp6_t a)
void fp6_rand (fp6_t a)
void fp6_print (fp6_t a)
int fp6_size_bin (fp6_t a)
void fp6_read_bin (fp6_t a, const uint8_t *bin, int len)
void fp6_write_bin (uint8_t *bin, int len, fp6_t a)
int fp6_cmp (fp6_t a, fp6_t b)
int fp6_cmp_dig (fp6_t a, dig_t b)
void fp6_set_dig (fp6_t a, dig_t b)
void fp6_add (fp6_t c, fp6_t a, fp6_t b)
void fp6_sub (fp6_t c, fp6_t a, fp6_t b)
void fp6_neg (fp6_t c, fp6_t a)
void fp6_dbl (fp6_t c, fp6_t a)
void fp6_mul_unr (dv6_t c, fp6_t a, fp6_t b)
void fp6_mul_basic (fp6_t c, fp6_t a, fp6_t b)
void fp6_mul_lazyr (fp6_t c, fp6_t a, fp6_t b)
void fp6_mul_art (fp6_t c, fp6_t a)
void fp6_mul_dxs (fp6_t c, fp6_t a, fp6_t b)
void fp6_sqr_unr (dv6_t c, fp6_t a)
void fp6_sqr_basic (fp6_t c, fp6_t a)
void fp6_sqr_lazyr (fp6_t c, fp6_t a)
void fp6_inv (fp6_t c, fp6_t a)
void fp6_exp (fp6_t c, fp6_t a, bn_t b)
void fp6_frb (fp6_t c, fp6_t a, int i)
void fp8_copy (fp8_t c, fp8_t a)
void fp8_zero (fp8_t a)
int fp8_is_zero (fp8_t a)
void fp8_rand (fp8_t a)
void fp8_print (fp8_t a)
int fp8_size_bin (fp8_t a, int pack)
void fp8_read_bin (fp8_t a, const uint8_t *bin, int len)
void fp8_write_bin (uint8_t *bin, int len, fp8_t a)
int fp8_cmp (fp8_t a, fp8_t b)
int fp8_cmp_dig (fp8_t a, dig_t b)
void fp8_set_dig (fp8_t a, dig_t b)
void fp8_add (fp8_t c, fp8_t a, fp8_t b)
void fp8_sub (fp8_t c, fp8_t a, fp8_t b)
void fp8_neg (fp8_t c, fp8_t a)
void fp8_dbl (fp8_t c, fp8_t a)
void fp8_mul_unr (dv8_t c, fp8_t a, fp8_t b)
void fp8_mul_basic (fp8_t c, fp8_t a, fp8_t b)
void fp8_mul_lazyr (fp8_t c, fp8_t a, fp8_t b)
void fp8_mul_art (fp8_t c, fp8_t a)
void fp8_mul_dxs (fp8_t c, fp8_t a, fp8_t b)
void fp8_sqr_unr (dv8_t c, fp8_t a)
void fp8_sqr_basic (fp8_t c, fp8_t a)
void fp8_sqr_lazyr (fp8_t c, fp8_t a)
void fp8_sqr_cyc (fp8_t c, fp8_t a)
void fp8_inv (fp8_t c, fp8_t a)
void fp8_inv_cyc (fp8_t c, fp8_t a)
void fp8_inv_sim (fp8_t *c, fp8_t *a, int n)
int fp8_test_cyc (fp8_t a)
void fp8_conv_cyc (fp8_t c, fp8_t a)
void fp8_exp (fp8_t c, fp8_t a, bn_t b)
void fp8_exp_cyc (fp8_t c, fp8_t a, bn_t b)
void fp8_frb (fp8_t c, fp8_t a, int i)
void fp9_copy (fp9_t c, fp9_t a)
void fp9_zero (fp9_t a)
int fp9_is_zero (fp9_t a)
void fp9_rand (fp9_t a)
void fp9_print (fp9_t a)
int fp9_size_bin (fp9_t a)
void fp9_read_bin (fp9_t a, const uint8_t *bin, int len)
void fp9_write_bin (uint8_t *bin, int len, fp9_t a)
int fp9_cmp (fp9_t a, fp9_t b)
int fp9_cmp_dig (fp9_t a, dig_t b)
void fp9_set_dig (fp9_t a, dig_t b)
void fp9_add (fp9_t c, fp9_t a, fp9_t b)
void fp9_sub (fp9_t c, fp9_t a, fp9_t b)
void fp9_neg (fp9_t c, fp9_t a)
void fp9_dbl (fp9_t c, fp9_t a)
void fp9_mul_unr (dv9_t c, fp9_t a, fp9_t b)
void fp9_mul_basic (fp9_t c, fp9_t a, fp9_t b)
void fp9_mul_lazyr (fp9_t c, fp9_t a, fp9_t b)
void fp9_mul_art (fp9_t c, fp9_t a)
void fp9_mul_dxs (fp9_t c, fp9_t a, fp9_t b)
void fp9_sqr_unr (dv9_t c, fp9_t a)
void fp9_sqr_basic (fp9_t c, fp9_t a)
void fp9_sqr_lazyr (fp9_t c, fp9_t a)
void fp9_inv (fp9_t c, fp9_t a)
void fp9_inv_sim (fp9_t *c, fp9_t *a, int n)
void fp9_exp (fp9_t c, fp9_t a, bn_t b)
void fp9_frb (fp9_t c, fp9_t a, int i)
void fp12_copy (fp12_t c, fp12_t a)
void fp12_zero (fp12_t a)
int fp12_is_zero (fp12_t a)
void fp12_rand (fp12_t a)
void fp12_print (fp12_t a)
int fp12_size_bin (fp12_t a, int pack)
void fp12_read_bin (fp12_t a, const uint8_t *bin, int len)
void fp12_write_bin (uint8_t *bin, int len, fp12_t a, int pack)
int fp12_cmp (fp12_t a, fp12_t b)
int fp12_cmp_dig (fp12_t a, dig_t b)
void fp12_set_dig (fp12_t a, dig_t b)
void fp12_add (fp12_t c, fp12_t a, fp12_t b)
void fp12_sub (fp12_t c, fp12_t a, fp12_t b)
void fp12_neg (fp12_t c, fp12_t a)
void fp12_dbl (fp12_t c, fp12_t a)
void fp12_mul_unr (dv12_t c, fp12_t a, fp12_t b)
void fp12_mul_basic (fp12_t c, fp12_t a, fp12_t b)
void fp12_mul_lazyr (fp12_t c, fp12_t a, fp12_t b)
void fp12_mul_art (fp12_t c, fp12_t a)
void fp12_mul_dxs_basic (fp12_t c, fp12_t a, fp12_t b)
void fp12_mul_dxs_lazyr (fp12_t c, fp12_t a, fp12_t b)
void fp12_sqr_unr (dv12_t c, fp12_t a)
void fp12_sqr_basic (fp12_t c, fp12_t a)
void fp12_sqr_lazyr (fp12_t c, fp12_t a)
void fp12_sqr_cyc_basic (fp12_t c, fp12_t a)
void fp12_sqr_cyc_lazyr (fp12_t c, fp12_t a)
void fp12_sqr_pck_basic (fp12_t c, fp12_t a)
void fp12_sqr_pck_lazyr (fp12_t c, fp12_t a)
int fp12_test_cyc (fp12_t a)
void fp12_conv_cyc (fp12_t c, fp12_t a)
void fp12_back_cyc (fp12_t c, fp12_t a)
void fp12_back_cyc_sim (fp12_t *c, fp12_t *a, int n)
void fp12_inv (fp12_t c, fp12_t a)
void fp12_inv_cyc (fp12_t c, fp12_t a)
void fp12_frb (fp12_t c, fp12_t a, int i)
void fp12_exp (fp12_t c, fp12_t a, bn_t b)
void fp12_exp_dig (fp12_t c, fp12_t a, dig_t b)
void fp12_exp_cyc (fp12_t c, fp12_t a, bn_t b)
void fp12_exp_cyc_sps (fp12_t c, fp12_t a, const int *b, int l, int s)
void fp12_pck (fp12_t c, fp12_t a)
int fp12_upk (fp12_t c, fp12_t a)
void fp18_copy (fp18_t c, fp18_t a)
void fp18_zero (fp18_t a)
int fp18_is_zero (fp18_t a)
void fp18_rand (fp18_t a)
void fp18_print (fp18_t a)
int fp18_size_bin (fp18_t a)
void fp18_read_bin (fp18_t a, const uint8_t *bin, int len)
void fp18_write_bin (uint8_t *bin, int len, fp18_t a)
int fp18_cmp (fp18_t a, fp18_t b)
int fp18_cmp_dig (fp18_t a, dig_t b)
void fp18_set_dig (fp18_t a, dig_t b)
void fp18_add (fp18_t c, fp18_t a, fp18_t b)
void fp18_sub (fp18_t c, fp18_t a, fp18_t b)
void fp18_neg (fp18_t c, fp18_t a)
void fp18_dbl (fp18_t c, fp18_t a)
void fp18_mul_unr (dv18_t c, fp18_t a, fp18_t b)
void fp18_mul_basic (fp18_t c, fp18_t a, fp18_t b)
void fp18_mul_lazyr (fp18_t c, fp18_t a, fp18_t b)
void fp18_mul_art (fp18_t c, fp18_t a)
void fp18_mul_dxs_basic (fp18_t c, fp18_t a, fp18_t b)
void fp18_mul_dxs_lazyr (fp18_t c, fp18_t a, fp18_t b)
void fp18_sqr_unr (dv18_t c, fp18_t a)
void fp18_sqr_basic (fp18_t c, fp18_t a)
void fp18_sqr_lazyr (fp18_t c, fp18_t a)
void fp18_inv (fp18_t c, fp18_t a)
void fp18_inv_cyc (fp18_t c, fp18_t a)
void fp18_conv_cyc (fp18_t c, fp18_t a)
void fp18_frb (fp18_t c, fp18_t a, int i)
void fp18_exp (fp18_t c, fp18_t a, bn_t b)
void fp24_copy (fp24_t c, fp24_t a)
void fp24_zero (fp24_t a)
int fp24_is_zero (fp24_t a)
void fp24_rand (fp24_t a)
void fp24_print (fp24_t a)
int fp24_size_bin (fp24_t a)
void fp24_read_bin (fp24_t a, const uint8_t *bin, int len)
void fp24_write_bin (uint8_t *bin, int len, fp24_t a)
int fp24_cmp (fp24_t a, fp24_t b)
int fp24_cmp_dig (fp24_t a, dig_t b)
void fp24_set_dig (fp24_t a, dig_t b)
void fp24_add (fp24_t c, fp24_t a, fp24_t b)
void fp24_sub (fp24_t c, fp24_t a, fp24_t b)
void fp24_neg (fp24_t c, fp24_t a)
void fp24_dbl (fp24_t c, fp24_t a)
void fp24_mul_unr (dv24_t c, fp24_t a, fp24_t b)
void fp24_mul_basic (fp24_t c, fp24_t a, fp24_t b)
void fp24_mul_lazyr (fp24_t c, fp24_t a, fp24_t b)
void fp24_mul_art (fp24_t c, fp24_t a)
void fp24_mul_dxs (fp24_t c, fp24_t a, fp24_t b)
void fp24_sqr_unr (dv24_t c, fp24_t a)
void fp24_sqr_basic (fp24_t c, fp24_t a)
void fp24_sqr_lazyr (fp24_t c, fp24_t a)
void fp24_inv (fp24_t c, fp24_t a)
void fp24_frb (fp24_t c, fp24_t a, int i)
void fp24_exp (fp24_t c, fp24_t a, bn_t b)
void fp48_copy (fp48_t c, fp48_t a)
void fp48_zero (fp48_t a)
int fp48_is_zero (fp48_t a)
void fp48_rand (fp48_t a)
void fp48_print (fp48_t a)
int fp48_size_bin (fp48_t a, int pack)
void fp48_read_bin (fp48_t a, const uint8_t *bin, int len)
void fp48_write_bin (uint8_t *bin, int len, fp48_t a, int pack)
int fp48_cmp (fp48_t a, fp48_t b)
int fp48_cmp_dig (fp48_t a, dig_t b)
void fp48_set_dig (fp48_t a, dig_t b)
void fp48_add (fp48_t c, fp48_t a, fp48_t b)
void fp48_sub (fp48_t c, fp48_t a, fp48_t b)
void fp48_neg (fp48_t c, fp48_t a)
void fp48_dbl (fp48_t c, fp48_t a)
void fp48_mul_unr (dv48_t c, fp48_t a, fp48_t b)
void fp48_mul_basic (fp48_t c, fp48_t a, fp48_t b)
void fp48_mul_lazyr (fp48_t c, fp48_t a, fp48_t b)
void fp48_mul_art (fp48_t c, fp48_t a)
void fp48_mul_dxs (fp48_t c, fp48_t a, fp48_t b)
void fp48_sqr_unr (dv48_t c, fp48_t a)
void fp48_sqr_basic (fp48_t c, fp48_t a)
void fp48_sqr_lazyr (fp48_t c, fp48_t a)
void fp48_sqr_cyc_basic (fp48_t c, fp48_t a)
void fp48_sqr_cyc_lazyr (fp48_t c, fp48_t a)
void fp48_sqr_pck_basic (fp48_t c, fp48_t a)
void fp48_sqr_pck_lazyr (fp48_t c, fp48_t a)
int fp48_test_cyc (fp48_t a)
void fp48_conv_cyc (fp48_t c, fp48_t a)
void fp48_back_cyc (fp48_t c, fp48_t a)
void fp48_back_cyc_sim (fp48_t *c, fp48_t *a, int n)
void fp48_inv (fp48_t c, fp48_t a)
void fp48_inv_cyc (fp48_t c, fp48_t a)
void fp48_frb (fp48_t c, fp48_t a, int i)
void fp48_exp (fp48_t c, fp48_t a, bn_t b)
void fp48_exp_dig (fp48_t c, fp48_t a, dig_t b)
void fp48_exp_cyc (fp48_t c, fp48_t a, bn_t b)
void fp48_exp_cyc_sps (fp48_t c, fp48_t a, const int *b, int l, int s)
void fp48_pck (fp48_t c, fp48_t a)
int fp48_upk (fp48_t c, fp48_t a)
void fp54_copy (fp54_t c, fp54_t a)
void fp54_zero (fp54_t a)
int fp54_is_zero (fp54_t a)
void fp54_rand (fp54_t a)
void fp54_print (fp54_t a)
int fp54_size_bin (fp54_t a, int pack)
void fp54_read_bin (fp54_t a, const uint8_t *bin, int len)
void fp54_write_bin (uint8_t *bin, int len, fp54_t a, int pack)
int fp54_cmp (fp54_t a, fp54_t b)
int fp54_cmp_dig (fp54_t a, dig_t b)
void fp54_set_dig (fp54_t a, dig_t b)
void fp54_add (fp54_t c, fp54_t a, fp54_t b)
void fp54_sub (fp54_t c, fp54_t a, fp54_t b)
void fp54_neg (fp54_t c, fp54_t a)
void fp54_dbl (fp54_t c, fp54_t a)
void fp54_mul_unr (dv54_t c, fp54_t a, fp54_t b)
void fp54_mul_basic (fp54_t c, fp54_t a, fp54_t b)
void fp54_mul_lazyr (fp54_t c, fp54_t a, fp54_t b)
void fp54_mul_art (fp54_t c, fp54_t a)
void fp54_mul_dxs (fp54_t c, fp54_t a, fp54_t b)
void fp54_sqr_unr (dv54_t c, fp54_t a)
void fp54_sqr_basic (fp54_t c, fp54_t a)
void fp54_sqr_lazyr (fp54_t c, fp54_t a)
void fp54_sqr_cyc_basic (fp54_t c, fp54_t a)
void fp54_sqr_cyc_lazyr (fp54_t c, fp54_t a)
void fp54_sqr_pck_basic (fp54_t c, fp54_t a)
void fp54_sqr_pck_lazyr (fp54_t c, fp54_t a)
int fp54_test_cyc (fp54_t a)
void fp54_conv_cyc (fp54_t c, fp54_t a)
void fp54_back_cyc (fp54_t c, fp54_t a)
void fp54_back_cyc_sim (fp54_t *c, fp54_t *a, int n)
void fp54_inv (fp54_t c, fp54_t a)
void fp54_inv_cyc (fp54_t c, fp54_t a)
void fp54_frb (fp54_t c, fp54_t a, int i)
void fp54_exp (fp54_t c, fp54_t a, bn_t b)
void fp54_exp_dig (fp54_t c, fp54_t a, dig_t b)
void fp54_exp_cyc (fp54_t c, fp54_t a, bn_t b)
void fp54_exp_cyc_sps (fp54_t c, fp54_t a, const int *b, int l, int s)
void fp54_pck (fp54_t c, fp54_t a)
int fp54_upk (fp54_t c, fp54_t a)
Detailed Description
Interface of the module for prime extension field arithmetic.
Definition in file relic_fpx.h.
Macro Definition Documentation
dv2_null
#define dv2_null (A) dv_null(A[0]); dv_null(A[1]); \
Initializes a double-precision quadratic extension field element with null.
Parameters
[out] A - the quadratic extension element to initialize.
Definition at line 228 of file relic_fpx.h.
dv2_new
#define dv2_new (A) dv_new(A[0]); dv_new(A[1]); \
Allocates a double-precision quadratic extension field element.
Parameters
[out] A - the new quadratic extension field element.
Definition at line 237 of file relic_fpx.h.
dv2_free
#define dv2_free (A) dv_free(A[0]); dv_free(A[1]); \
Frees a double-precision quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to free.
Definition at line 245 of file relic_fpx.h.
fp2_null
#define fp2_null (A) fp_null(A[0]); fp_null(A[1]); \
Initializes a quadratic extension field element with null.
Parameters
[out] A - the quadratic extension element to initialize.
Definition at line 253 of file relic_fpx.h.
fp2_new
#define fp2_new (A) fp_new(A[0]); fp_new(A[1]); \
Allocates a quadratic extension field element.
Parameters
[out] A - the new quadratic extension field element.
Definition at line 261 of file relic_fpx.h.
fp2_free
#define fp2_free (A) fp_free(A[0]); fp_free(A[1]); \
Frees a quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to free.
Definition at line 269 of file relic_fpx.h.
dv3_null
#define dv3_null (A) dv_null(A[0]); dv_null(A[1]); dv_null(A[2]); \
Adds two quadratic extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element. Subtracts a quadratic extension field element from another. Computes C = A - B.
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element. Doubles a quadratic extension field element. Computes C = A + A.
[out] C - the result.
[in] A - the quadratic extension field element. Multiplies two quadratic extension field elements. Computes C = A * B.
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element. Multiplies a quadratic extension field by the quadratic/cubic non-residue. Computes C = A * E, where E is a non-square/non-cube in the quadratic extension.
[out] C - the result.
[in] A - the quadratic extension field element to multiply. Squares a quadratic extension field element. Computes C = A * A.
[out] C - the result.
[in] A - the quadratic extension field element to square. Initializes a double-precision cubic extension field element with a null value.
[out] A - the cubic extension element to initialize.
Definition at line 356 of file relic_fpx.h.
dv3_new
#define dv3_new (A) dv_new(A[0]); dv_new(A[1]); dv_new(A[2]); \
Allocates a double-precision cubic extension field element.
Parameters
[out] A - the new cubic extension field element.
Definition at line 364 of file relic_fpx.h.
dv3_free
#define dv3_free (A) dv_free(A[0]); dv_free(A[1]); dv_free(A[2]); \
Frees a double-precision cubic extension field element.
Parameters
[out] A - the cubic extension field element to free.
Definition at line 372 of file relic_fpx.h.
fp3_null
#define fp3_null (A) fp_null(A[0]); fp_null(A[1]); fp_null(A[2]); \
Initializes a cubic extension field element with null.
Parameters
[out] A - the cubic extension element to initialize.
Definition at line 380 of file relic_fpx.h.
fp3_new
#define fp3_new (A) fp_new(A[0]); fp_new(A[1]); fp_new(A[2]); \
Allocates a cubic extension field element.
Parameters
[out] A - the new cubic extension field element.
Definition at line 388 of file relic_fpx.h.
fp3_free
#define fp3_free (A) fp_free(A[0]); fp_free(A[1]); fp_free(A[2]); \
Frees a cubic extension field element.
Parameters
[out] A - the cubic extension field element to free.
Definition at line 396 of file relic_fpx.h.
dv4_null
#define dv4_null (A) dv2_null(A[0]); dv2_null(A[1]); \
Adds two cubic extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first cubic extension field element.
[in] B - the second cubic extension field element. Subtracts a cubic extension field element from another. Computes C = A - B.
[out] C - the result.
[in] A - the first cubic extension field element.
[in] B - the second cubic extension field element. Doubles a cubic extension field element. Computes C = A + A.
[out] C - the result.
[in] A - the cubic extension field element. Multiplies two cubic extension field elements. Computes C = A * B.
[out] C - the result.
[in] A - the first cubic extension field element.
[in] B - the second cubic extension field element. Squares a cubic extension field element. Computes C = A * A.
[out] C - the result.
[in] A - the cubic extension field element to square. Initializes a double-precision quartic extension field with null.
[out] A - the quartic extension element to initialize.
Definition at line 468 of file relic_fpx.h.
dv4_new
#define dv4_new (A) dv2_new(A[0]); dv2_new(A[1]); \
Allocates a double-precision quartic extension field element.
Parameters
[out] A - the new quartic extension field element.
Definition at line 476 of file relic_fpx.h.
dv4_free
#define dv4_free (A) dv2_free(A[0]); dv2_free(A[1]); \
Frees a double-precision quartic extension field element.
Parameters
[out] A - the quartic extension field element to free.
Definition at line 484 of file relic_fpx.h.
fp4_null
#define fp4_null (A) fp2_null(A[0]); fp2_null(A[1]); \
Initializes a quartic extension field with null.
Parameters
[out] A - the quartic extension element to initialize.
Definition at line 492 of file relic_fpx.h.
fp4_new
#define fp4_new (A) fp2_new(A[0]); fp2_new(A[1]); \
Allocates a quartic extension field element.
Parameters
[out] A - the new quartic extension field element.
Definition at line 500 of file relic_fpx.h.
fp4_free
#define fp4_free (A) fp2_free(A[0]); fp2_free(A[1]); \
Frees a quartic extension field element.
Parameters
[out] A - the quartic extension field element to free.
Definition at line 508 of file relic_fpx.h.
dv6_null
#define dv6_null (A) dv2_null(A[0]); dv2_null(A[1]); dv2_null(A[2]); \
Multiplies two quartic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first quartic extension field element.
[in] B - the second quartic extension field element. Squares a quartic extension field element. Computes C = A * A.
[out] C - the result.
[in] A - the quartic extension field element to square. Initializes a double-precision sextic extension field with null.
[out] A - the sextic extension element to initialize.
Definition at line 541 of file relic_fpx.h.
dv6_new
#define dv6_new (A) dv2_new(A[0]); dv2_new(A[1]); dv2_new(A[2]); \
Allocates a double-precision sextic extension field element.
Parameters
[out] A - the new sextic extension field element.
Definition at line 549 of file relic_fpx.h.
dv6_free
#define dv6_free (A) dv2_free(A[0]); dv2_free(A[1]); dv2_free(A[2]); \
Frees a double-precision sextic extension field element.
Parameters
[out] A - the sextic extension field element to free.
Definition at line 557 of file relic_fpx.h.
fp6_null
#define fp6_null (A) fp2_null(A[0]); fp2_null(A[1]); fp2_null(A[2]); \
Initializes a sextic extension field with null.
Parameters
[out] A - the sextic extension element to initialize.
Definition at line 565 of file relic_fpx.h.
fp6_new
#define fp6_new (A) fp2_new(A[0]); fp2_new(A[1]); fp2_new(A[2]); \
Allocates a sextic extension field element.
Parameters
[out] A - the new sextic extension field element.
Definition at line 573 of file relic_fpx.h.
fp6_free
#define fp6_free (A) fp2_free(A[0]); fp2_free(A[1]); fp2_free(A[2]); \
Frees a sextic extension field element.
Parameters
[out] A - the sextic extension field element to free.
Definition at line 581 of file relic_fpx.h.
dv8_null
#define dv8_null (A) dv4_null(A[0]); dv4_null(A[1]); \
Multiplies two sextic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first sextic extension field element.
[in] B - the second sextic extension field element. Squares a sextic extension field element. Computes C = A * A.
[out] C - the result.
[in] A - the sextic extension field element to square. Initializes a double-precision octic extension field with null.
[out] A - the octic extension element to initialize.
Definition at line 614 of file relic_fpx.h.
dv8_new
#define dv8_new (A) dv4_new(A[0]); dv4_new(A[1]); \
Allocates a double-precision octic extension field element.
Parameters
[out] A - the new octic extension field element.
Definition at line 622 of file relic_fpx.h.
dv8_free
#define dv8_free (A) dv4_free(A[0]); dv4_free(A[1]); \
Frees a double-precision octic extension field element.
Parameters
[out] A - the octic extension field element to free.
Definition at line 630 of file relic_fpx.h.
fp8_null
#define fp8_null (A) fp4_null(A[0]); fp4_null(A[1]); \
Initializes an octic extension field with null.
Parameters
[out] A - the octic extension element to initialize.
Definition at line 638 of file relic_fpx.h.
fp8_new
#define fp8_new (A) fp4_new(A[0]); fp4_new(A[1]); \
Allocates an octic extension field element.
Parameters
[out] A - the new octic extension field element.
Definition at line 646 of file relic_fpx.h.
fp8_free
#define fp8_free (A) fp4_free(A[0]); fp4_free(A[1]); \
Frees an octic extension field element.
Parameters
[out] A - the octic extension field element to free.
Definition at line 654 of file relic_fpx.h.
dv9_null
#define dv9_null (A) dv3_null(A[0]); dv3_null(A[1]); dv3_null(A[2]); \
Multiplies two octic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first octic extension field element.
[in] B - the second octic extension field element. Squares an octic extension field element. Computes C = A * A.
[out] C - the result.
[in] A - the octic extension field element to square. Initializes a double-precision nonic extension field with null.
[out] A - the octic extension element to initialize.
Definition at line 687 of file relic_fpx.h.
dv9_new
#define dv9_new (A) dv3_new(A[0]); dv3_new(A[1]); dv3_new(A[2]); \
Allocates a double-precision nonic extension field element.
Parameters
[out] A - the new nonic extension field element.
Definition at line 695 of file relic_fpx.h.
dv9_free
#define dv9_free (A) dv3_free(A[0]); dv3_free(A[1]); dv3_free(A[2]); \
Frees a double-precision nonic extension field element.
Parameters
[out] A - the nonic extension field element to free.
Definition at line 703 of file relic_fpx.h.
fp9_null
#define fp9_null (A) fp3_null(A[0]); fp3_null(A[1]); fp3_null(A[2]); \
Initializes a nonic extension field with null.
Parameters
[out] A - the nonic extension element to initialize.
Definition at line 711 of file relic_fpx.h.
fp9_new
#define fp9_new (A) fp3_new(A[0]); fp3_new(A[1]); fp3_new(A[2]); \
Allocates a nonic extension field element.
Parameters
[out] A - the new nonic extension field element.
Definition at line 719 of file relic_fpx.h.
fp9_free
#define fp9_free (A) fp3_free(A[0]); fp3_free(A[1]); fp3_free(A[2]); \
Frees a nonic extension field element.
Parameters
[out] A - the nonic extension field element to free.
Definition at line 727 of file relic_fpx.h.
dv12_null
#define dv12_null (A) dv6_null(A[0]); dv6_null(A[1]); \
Multiplies two nonic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first nonic extension field element.
[in] B - the second nonic extension field element. Squares a nonic extension field element. Computes C = A * A.
[out] C - the result.
[in] A - the nonic extension field element to square. Initializes a double-precision dodecic extension field with null.
[out] A - the dodecic extension element to initialize.
Definition at line 760 of file relic_fpx.h.
dv12_new
#define dv12_new (A) dv6_new(A[0]); dv6_new(A[1]); \
Allocates a double-precision dodecic extension field element.
Parameters
[out] A - the new dodecic extension field element.
Definition at line 768 of file relic_fpx.h.
dv12_free
#define dv12_free (A) dv6_free(A[0]); dv6_free(A[1]); \
Frees a double-precision dodecic extension field element.
Parameters
[out] A - the dodecic extension field element to free.
Definition at line 776 of file relic_fpx.h.
fp12_null
#define fp12_null (A) fp6_null(A[0]); fp6_null(A[1]); \
Initializes a dodecic extension field with null.
Parameters
[out] A - the dodecic extension element to initialize.
Definition at line 784 of file relic_fpx.h.
fp12_new
#define fp12_new (A) fp6_new(A[0]); fp6_new(A[1]); \
Allocates a dodecic extension field element.
Parameters
[out] A - the new dodecic extension field element.
Definition at line 792 of file relic_fpx.h.
fp12_free
#define fp12_free (A) fp6_free(A[0]); fp6_free(A[1]); \
Frees a dodecic extension field element.
Parameters
[out] A - the dodecic extension field element to free.
Definition at line 800 of file relic_fpx.h.
dv18_null
#define dv18_null (A) dv9_null(A[0]); dv9_null(A[1]); \
Multiplies two dodecic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first dodecic extension field element.
[in] B - the second dodecic extension field element. Multiplies a dense and a sparse dodecic extension field elements. Computes C = A * B.
[out] C - the result.
[in] A - the dense dodecic extension field element.
[in] B - the sparse dodecic extension field element. Squares a dodecic extension field element. Computes C = A * A.
[out] C - the result.
[in] A - the dodecic extension field element to square. Squares a dodecic extension field element in the cyclotomic subgroup. Computes C = A * A.
[out] C - the result.
[in] A - the dodecic extension field element to square. Squares a dodecic extension field element in the cyclotomic subgroup in compressed form. Computes C = A * A.
[out] C - the result.
[in] A - the dodecic extension field element to square. Initializes a double-precision sextic extension field with null.
[out] A - the sextic extension element to initialize.
Definition at line 873 of file relic_fpx.h.
dv18_new
#define dv18_new (A) dv9_new(A[0]); dv9_new(A[1]); \
Allocates a double-precision sextic extension field element.
Parameters
[out] A - the new sextic extension field element.
Definition at line 881 of file relic_fpx.h.
dv18_free
#define dv18_free (A) dv9_free(A[0]); dv9_free(A[1]); \
Frees a double-precision sextic extension field element.
Parameters
[out] A - the sextic extension field element to free.
Definition at line 889 of file relic_fpx.h.
fp18_null
#define fp18_null (A) fp9_null(A[0]); fp9_null(A[1]); \
Initializes an octdecic extension field with null.
Parameters
[out] A - the octdecic extension element to initialize.
Definition at line 897 of file relic_fpx.h.
fp18_new
#define fp18_new (A) fp9_new(A[0]); fp9_new(A[1]); \
Allocates an octdecic extension field element.
Parameters
[out] A - the new octdecic extension field element.
Definition at line 905 of file relic_fpx.h.
fp18_free
#define fp18_free (A) fp9_free(A[0]); fp9_free(A[1]); \
Frees an octdecic extension field element.
Parameters
[out] A - the octdecic extension field element to free.
Definition at line 913 of file relic_fpx.h.
dv24_null
#define dv24_null (A) dv8_null(A[0]); dv8_null(A[1]); dv8_null(A[2]); \
Multiplies two octdecic extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first octdecic extension field element.
[in] B - the second octdecic extension field element. Multiplies a dense and a sparse octdecic extension field elements. Computes C = A * B.
[out] C - the result.
[in] A - the dense octdecic extension field element.
[in] B - the sparse octdecic extension field element. Squares an octdecic extension field element. Computes C = A * A.
[out] C - the result.
[in] A - the octdecic extension field element to square. Initializes a double-precision 24-degree extension field with null.
[out] A - the 24-degree extension element to initialize.
Definition at line 960 of file relic_fpx.h.
dv24_new
#define dv24_new (A) dv8_new(A[0]); dv8_new(A[1]); dv8_new(A[2]); \
Allocates a double-precision 24-degree extension field element.
Parameters
[out] A - the new 24-degree extension field element.
Definition at line 968 of file relic_fpx.h.
dv24_free
#define dv24_free (A) dv8_free(A[0]); dv8_free(A[1]); dv8_free(A[2]); \
Frees a double-precision 24-degree extension field element.
Parameters
[out] A - the 24-degree extension field element to free.
Definition at line 976 of file relic_fpx.h.
fp24_null
#define fp24_null (A) fp8_null(A[0]); fp8_null(A[1]); fp8_null(A[2]); \
Initializes a 24-degree extension field with null.
Parameters
[out] A - the 24-degree extension element to initialize.
Definition at line 984 of file relic_fpx.h.
fp24_new
#define fp24_new (A) fp8_new(A[0]); fp8_new(A[1]); fp8_new(A[2]); \
Allocates a 24-degree extension field element.
Parameters
[out] A - the new 24-degree extension field element.
Definition at line 992 of file relic_fpx.h.
fp24_free
#define fp24_free (A) fp8_free(A[0]); fp8_free(A[1]); fp8_free(A[2]); \
Frees a 24-degree extension field element.
Parameters
[out] A - the 24-degree extension field element to free.
Definition at line 1000 of file relic_fpx.h.
dv48_null
#define dv48_null (A) dv24_null(A[0]); dv24_null(A[1]); \
Multiplies two 24-degree extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first 24-degree extension field element.
[in] B - the second 24-degree extension field element. Squares a 24-degree extension field element. Computes C = A * A.
[out] C - the result.
[in] A - the 24-degree extension field element to square. Initializes a double-precision 48-degree extension field with null.
[out] A - the 48-degree extension element to initialize.
Definition at line 1033 of file relic_fpx.h.
dv48_new
#define dv48_new (A) dv24_new(A[0]); dv24_new(A[1]); \
Allocates a double-precision 48-degree extension field element.
Parameters
[out] A - the new 48-degree extension field element.
Definition at line 1041 of file relic_fpx.h.
dv48_free
#define dv48_free (A) dv24_free(A[0]); dv24_free(A[1]); \
Frees a double-precision 48-degree extension field element.
Parameters
[out] A - the 48-degree extension field element to free.
Definition at line 1049 of file relic_fpx.h.
fp48_null
#define fp48_null (A) fp24_null(A[0]); fp24_null(A[1]); \
Initializes a 48-degree extension field with null.
Parameters
[out] A - the 48-degree extension element to initialize.
Definition at line 1057 of file relic_fpx.h.
fp48_new
#define fp48_new (A) fp24_new(A[0]); fp24_new(A[1]); \
Allocates a 48-degree extension field element.
Parameters
[out] A - the new 48-degree extension field element.
Definition at line 1065 of file relic_fpx.h.
fp48_free
#define fp48_free (A) fp24_free(A[0]); fp24_free(A[1]); \
Frees a 48-degree extension field element.
Parameters
[out] A - the 48-degree extension field element to free.
Definition at line 1073 of file relic_fpx.h.
dv54_null
#define dv54_null (A) dv18_null(A[0]); dv18_null(A[1]); dv18_null(A[2]); \
Multiplies two 48-degree extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first 48-degree extension field element.
[in] B - the second 48-degree extension field element. Squares a 48-degree extension field element. Computes C = A * A.
[out] C - the result.
[in] A - the 48-degree extension field element to square. Squares a 48-degree extension field element in the cyclotomic subgroup. Computes C = A * A.
[out] C - the result.
[in] A - the 48-degree extension field element to square. Squares a 48-degree extension field element in the cyclotomic subgroup in compressed form. Computes C = A * A.
[out] C - the result.
[in] A - the 48-degree extension field element to square. Initializes a double-precision 54-degree extension field with null.
[out] A - the 54-degree extension element to initialize.
Definition at line 1132 of file relic_fpx.h.
dv54_new
#define dv54_new (A) dv18_new(A[0]); dv18_new(A[1]); dv18_new(A[2]); \
Allocates a double-precision 54-degree extension field element.
Parameters
[out] A - the new 54-degree extension field element.
Definition at line 1140 of file relic_fpx.h.
dv54_free
#define dv54_free (A) dv18_free(A[0]); dv18_free(A[1]); dv18_free(A[2]); \
Frees a double-precision 54-degree extension field element.
Parameters
[out] A - the 54-degree extension field element to free.
Definition at line 1148 of file relic_fpx.h.
fp54_null
#define fp54_null (A) fp18_null(A[0]); fp18_null(A[1]); fp18_null(A[2]); \
Initializes a 54-degree extension field with null.
Parameters
[out] A - the 54-degree extension element to initialize.
Definition at line 1156 of file relic_fpx.h.
fp54_new
#define fp54_new (A) fp18_new(A[0]); fp18_new(A[1]); fp18_new(A[2]); \
Allocates a 54-degree extension field element.
Parameters
[out] A - the new 54-degree extension field element.
Definition at line 1164 of file relic_fpx.h.
fp54_free
#define fp54_free (A) fp18_free(A[0]); fp18_free(A[1]); fp18_free(A[2]); \
Frees a 54-degree extension field element.
Parameters
[out] A - the 54-degree extension field element to free.
Definition at line 1172 of file relic_fpx.h.
Typedef Documentation
fp2_t
typedef fp_t fp2_t[2]
Represents a quadratic extension prime field element.
This extension is constructed with the basis {1, i}, where i is an adjoined square root in the prime field.
Definition at line 52 of file relic_fpx.h.
dv2_t
typedef dv_t dv2_t[2]
Represents a double-precision quadratic extension field element.
Definition at line 57 of file relic_fpx.h.
fp2_st
typedef fp_st fp2_st[2]
Represents a quadratic extension field element with automatic memory allocation.
Definition at line 63 of file relic_fpx.h.
fp3_t
typedef fp_t fp3_t[3]
Represents a cubic extension prime field element.
This extension is constructed with the basis {1, j}, where j is an adjoined cube root in the prime field.
Definition at line 71 of file relic_fpx.h.
dv3_t
typedef dv_t dv3_t[3]
Represents a double-precision cubic extension field element.
Definition at line 76 of file relic_fpx.h.
fp3_st
typedef fp_st fp3_st[3]
Represents a cubic extension field element with automatic memory allocation.
Definition at line 82 of file relic_fpx.h.
fp4_t
typedef fp2_t fp4_t[2]
Represents a quartic extension prime field element.
This extension is constructed with the basis {1, v}, where v^2 = E is an adjoined root in the underlying quadratic extension.
Definition at line 90 of file relic_fpx.h.
dv4_t
typedef dv2_t dv4_t[2]
Represents a double-precision quartic extension field element.
Definition at line 95 of file relic_fpx.h.
fp4_st
typedef fp2_st fp4_st[2]
Represents a quartic extension field element with automatic memory allocation.
Definition at line 101 of file relic_fpx.h.
fp6_t
typedef fp2_t fp6_t[3]
Represents a sextic extension field element.
This extension is constructed with the basis {1, v, v^2}, where v^3 = E is an adjoined root in the underlying quadratic extension.
Definition at line 109 of file relic_fpx.h.
dv6_t
typedef dv2_t dv6_t[3]
Represents a double-precision sextic extension field element.
Definition at line 114 of file relic_fpx.h.
fp8_t
typedef fp4_t fp8_t[2]
Represents an octic extension prime field element.
This extension is constructed with the basis {1, w}, where w^2 = v is an adjoined root in the underlying quadratic extension.
Definition at line 122 of file relic_fpx.h.
dv8_t
typedef dv4_t dv8_t[2]
Represents a double-precision octic extension field element.
Definition at line 127 of file relic_fpx.h.
fp8_st
typedef fp4_st fp8_st[2]
Represents an octic extension field element with automatic memory allocation.
Definition at line 133 of file relic_fpx.h.
fp9_t
typedef fp3_t fp9_t[3]
Represents an octic extension prime field element.
This extension is constructed with the basis {1, w, w^2}, where w^3 = v is an adjoined root in the underlying quadratic extension.
Definition at line 141 of file relic_fpx.h.
dv9_t
typedef dv3_t dv9_t[3]
Represents a double-precision octic extension field element.
Definition at line 146 of file relic_fpx.h.
fp9_st
typedef fp3_st fp9_st[3]
Represents an octic extension field element with automatic memory allocation.
Definition at line 152 of file relic_fpx.h.
dv12_t
typedef dv6_t dv12_t[2]
Represents a double-precision dodecic extension field element.
Definition at line 157 of file relic_fpx.h.
fp12_t
typedef fp6_t fp12_t[2]
Represents a dodecic extension field element.
This extension is constructed with the basis {1, w}, where w^2 = v is an adjoined root in the underlying sextic extension.
Definition at line 165 of file relic_fpx.h.
dv18_t
typedef dv9_t dv18_t[2]
Represents a double-precision octdecic extension field element.
Definition at line 170 of file relic_fpx.h.
fp18_t
typedef fp9_t fp18_t[2]
Represents an octdecic extension field element.
This extension is constructed with the basis {1, w}, where w^2 = v is an adjoined root in the underlying sextic extension.
Definition at line 178 of file relic_fpx.h.
dv24_t
typedef dv8_t dv24_t[3]
Represents a double-precision 24-degree extension field element.
Definition at line 183 of file relic_fpx.h.
fp24_t
typedef fp8_t fp24_t[3]
Represents a 24-degree extension field element.
This extension is constructed with the basis {1, t, t^2}, where t^3 = w is an adjoined root in the underlying dodecic extension.
Definition at line 191 of file relic_fpx.h.
dv48_t
typedef dv24_t dv48_t[2]
Represents a double-precision 48-degree extension field element.
Definition at line 196 of file relic_fpx.h.
fp48_t
typedef fp24_t fp48_t[2]
Represents a 48-degree extension field element.
This extension is constructed with the basis {1, u}, where u^2 = t is an adjoined root in the underlying dodecic extension.
Definition at line 204 of file relic_fpx.h.
dv54_t
typedef dv18_t dv54_t[3]
Represents a double-precision 48-degree extension field element.
Definition at line 209 of file relic_fpx.h.
fp54_t
typedef fp18_t fp54_t[3]
Represents a 54-degree extension field element.
This extension is constructed with the basis {1, t, t^2}, where u^3 = w is an adjoined root in the underlying dodecic extension.
Definition at line 217 of file relic_fpx.h.
Function Documentation
fp2_field_init()
void fp2_field_init (void)
Multiplies two 54-degree extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first 54-degree extension field element.
[in] B - the second 54-degree extension field element. Squares a 54-degree extension field element. Computes C = A * A.
[out] C - the result.
[in] A - the 54-degree extension field element to square. Squares a 54-degree extension field element in the cyclotomic subgroup. Computes C = A * A.
[out] C - the result.
[in] A - the 54-degree extension field element to square. Squares a 54-degree extension field element in the cyclotomic subgroup in compressed form. Computes C = A * A.
[out] C - the result.
[in] A - the 54-degree extension field element to square. Initializes the quadratic extension field arithmetic module.
Definition at line 50 of file relic_fpx_field.c.
References bn_div_dig(), bn_free(), bn_null, bn_sub_dig(), CATCH_ANY, core_get(), bn_st::dp, dv_copy(), ERR_CAUGHT, FINALLY, fp2_exp(), fp2_free, fp2_new, fp2_null, _ctx_t::fp2_p1, _ctx_t::fp2_p2, fp2_set_dig(), fp2_srt(), fp_copy(), fp_prime_get(), fp_set_dig(), fp_zero(), _ctx_t::qnr2, RLC_FP_DIGS, THROW, TRY, and bn_st::used.
Referenced by fp_prime_calc().
fp2_field_get_qnr()
int fp2_field_get_qnr (void)
Return the integer part (u) of the quadratic non-residue (i + u).
Definition at line 39 of file relic_fpx_field.c.
References core_get(), and _ctx_t::qnr2.
Referenced by fp2_mul_nor_basic().
fp2_copy()
void fp2_copy (fp2_t c, fp2_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the quadratic extension field element to copy.
Definition at line 39 of file relic_fpx_util.c.
References fp_copy().
Referenced by ep2_add_basic_imp(), ep2_add_projc_mix(), ep2_copy(), ep2_dbl_basic_imp(), ep2_neg_basic(), ep2_neg_projc(), ep2_norm_imp(), ep2_norm_sim(), ep2_pck(), ep2_rhs(), ep2_upk(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_sqr_unr(), fp2_exp(), fp2_exp_cyc(), fp2_exp_dig(), fp2_frb(), fp2_inv_sim(), fp2_mul_nor_basic(), fp2_pck(), fp2_upk(), fp4_copy(), fp4_inv_cyc(), fp4_mul_art(), fp6_copy(), fp6_mul_art(), fp6_mul_basic(), fp6_mul_dxs(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_dbl_k8_projc_basic(), and pp_dbl_k8_projc_lazyr().
fp2_zero()
void fp2_zero (fp2_t a)
Assigns zero to a quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to zero.
Definition at line 44 of file relic_fpx_util.c.
References fp_zero().
Referenced by ep2_curve_set_twist(), ep2_pck(), ep2_read_bin(), ep2_set_infty(), fp12_pck(), fp12_read_bin(), fp4_set_dig(), fp4_zero(), fp6_set_dig(), fp6_zero(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), and pp_mil_k2().
fp2_is_zero()
int fp2_is_zero (fp2_t a)
Tests if a quadratic extension field element is zero or not.
Parameters
[in] A - the quadratic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 49 of file relic_fpx_util.c.
References fp_is_zero().
Referenced by ep2_add_basic_imp(), ep2_add_projc_imp(), ep2_add_projc_mix(), ep2_is_infty(), fp12_upk(), fp4_cmp_dig(), fp4_is_zero(), fp6_cmp_dig(), and fp6_is_zero().
fp2_rand()
void fp2_rand (fp2_t a)
Assigns a random value to a quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to assign.
Definition at line 53 of file relic_fpx_util.c.
References fp_rand().
Referenced by fp4_rand(), and fp6_rand().
fp2_print()
void fp2_print (fp2_t a)
Prints a quadratic extension field element to standard output.
Parameters
[in] A - the quadratic extension field element to print.
Definition at line 58 of file relic_fpx_util.c.
References fp_print().
Referenced by ep2_print(), fp4_print(), and fp6_print().
fp2_size_bin()
int fp2_size_bin (fp2_t a, int pack)
Returns the number of bytes necessary to store a quadratic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 63 of file relic_fpx_util.c.
References fp2_test_cyc(), and RLC_FP_BYTES.
fp2_read_bin()
void fp2_read_bin (fp2_t a, const uint8_t * bin, int len)
Reads a quadratic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 75 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_upk(), fp_read_bin(), fp_set_bit(), fp_zero(), RLC_FP_BYTES, and THROW.
Referenced by ep2_read_bin(), fp12_read_bin(), fp4_read_bin(), and fp6_read_bin().
fp2_write_bin()
void fp2_write_bin (uint8_t * bin, int len, fp2_t a, int pack)
Writes a quadratic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 91 of file relic_fpx_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, fp2_free, fp2_new, fp2_null, fp2_pck(), fp2_test_cyc(), fp_get_bit(), fp_write_bin(), RLC_FP_BYTES, THROW, and TRY.
Referenced by ep2_write_bin(), fp12_write_bin(), fp4_write_bin(), and fp6_write_bin().
fp2_cmp()
int fp2_cmp (fp2_t a, fp2_t b)
Returns the result of a comparison between two quadratic extension field elements.
Parameters
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 39 of file relic_fpx_cmp.c.
References fp_cmp(), RLC_EQ, and RLC_NE.
Referenced by ep2_cmp(), ep2_is_valid(), fp4_cmp(), and fp6_cmp().
fp2_cmp_dig()
int fp2_cmp_dig (fp2_t a, dig_t b)
Returns the result of a signed comparison between a quadratic extension field element and a digit.
Parameters
[in] a - the quadratic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 44 of file relic_fpx_cmp.c.
References fp_cmp_dig(), fp_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp2_test_cyc(), fp4_cmp_dig(), and fp6_cmp_dig().
fp2_set_dig()
void fp2_set_dig (fp2_t a, dig_t b)
Assigns a quadratic extension field element to a digit.
Parameters
[in] a - the quadratic extension field element.
[in] b - the digit.
Definition at line 123 of file relic_fpx_util.c.
References fp_set_dig(), and fp_zero().
Referenced by ep2_norm_imp(), fp2_exp(), fp2_exp_cyc(), fp2_exp_dig(), fp2_field_init(), fp4_set_dig(), fp6_set_dig(), pp_fin_k12_oatep(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k2(), pp_map_tatep_k2(), pp_map_weilp_k2(), and pp_norm_k8().
fp2_add_basic()
void fp2_add_basic (fp2_t c, fp2_t a, fp2_t b)
Adds two quadratic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 41 of file relic_fpx_add.c.
fp2_add_integ()
void fp2_add_integ (fp2_t c, fp2_t a, fp2_t b)
Adds two quadratic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 61 of file relic_fpx_add.c.
References fp2_addm_low().
fp2_sub_basic()
void fp2_sub_basic (fp2_t c, fp2_t a, fp2_t b)
Subtracts a quadratic extension field element from another using basic arithmetic.
Parameters
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Definition at line 46 of file relic_fpx_add.c.
fp2_sub_integ()
void fp2_sub_integ (fp2_t c, fp2_t a, fp2_t b)
Subtracts a quadratic extension field element from another using integrated modular reduction.
Parameters
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Definition at line 65 of file relic_fpx_add.c.
References fp2_subm_low().
fp2_neg()
void fp2_neg (fp2_t c, fp2_t a)
Negates a quadratic extension field element.
Parameters
[out] C - the result.
[out] A - the quadratic extension field element to negate.
Definition at line 75 of file relic_fpx_add.c.
Referenced by ep2_neg_basic(), ep2_neg_projc(), ep2_upk(), fp4_inv(), fp4_inv_cyc(), fp4_neg(), fp6_neg(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), and pp_add_lit_k12().
fp2_dbl_basic()
void fp2_dbl_basic (fp2_t c, fp2_t a)
Doubles a quadratic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to double.
Definition at line 51 of file relic_fpx_add.c.
fp2_dbl_integ()
void fp2_dbl_integ (fp2_t c, fp2_t a)
Doubles a quadratic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to double.
Definition at line 69 of file relic_fpx_add.c.
References fp2_dblm_low().
fp2_mul_basic()
void fp2_mul_basic (fp2_t c, fp2_t a, fp2_t b)
Multiples two quadratic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 42 of file relic_fp2_mul.c.
References CATCH_ANY, dv_null, ERR_CAUGHT, FINALLY, fp_addc_low(), fp_muln_low(), fp_prime_get_qnr(), fp_subc_low(), THROW, and TRY.
fp2_mul_integ()
void fp2_mul_integ (fp2_t c, fp2_t a, fp2_t b)
Multiples two quadratic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 166 of file relic_fp2_mul.c.
References fp2_mulm_low().
fp2_mul_art()
void fp2_mul_art (fp2_t c, fp2_t a)
Multiplies a quadratic extension field element by the adjoined root. Computes c = a * u.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 176 of file relic_fp2_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_copy(), fp_null, fp_prime_get_qnr(), THROW, and TRY.
Referenced by ep2_frb(), fp2_mul_nor_basic(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), and pp_dbl_k8_projc_new().
fp2_mul_nor_basic()
void fp2_mul_nor_basic (fp2_t c, fp2_t a)
Multiplies a quadratic extension field element by a quadratic/cubic non-residue.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 106 of file relic_fp2_mul.c.
References bn_free(), bn_null, CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp2_copy(), fp2_field_get_qnr(), fp2_free, fp2_mul_art(), fp2_new, fp2_null, fp_prime_get_mod8(), THROW, and TRY.
fp2_mul_nor_integ()
void fp2_mul_nor_integ (fp2_t c, fp2_t a)
Multiplies a quadratic extension field element by a quadratic/cubic non-residue using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to multiply.
Definition at line 170 of file relic_fp2_mul.c.
References fp2_norm_low().
fp2_mul_frb()
void fp2_mul_frb (fp2_t c, fp2_t a, int i, int j)
Multiplies a quadratic extension field element by a power of the constant needed to compute a power of the Frobenius map.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the power of the Frobenius map.
[in] j - the power of the constant.
Definition at line 210 of file relic_fp2_mul.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, _ctx_t::fp2_p1, _ctx_t::fp2_p2, fp_copy(), THROW, and TRY.
Referenced by ep2_frb(), fp12_frb(), fp24_frb(), fp48_frb(), fp4_frb(), fp6_frb(), and fp8_frb().
fp2_sqr_basic()
void fp2_sqr_basic (fp2_t c, fp2_t a)
Computes the square of a quadratic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to square.
Definition at line 41 of file relic_fp2_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_null, fp_prime_get_qnr(), THROW, and TRY.
fp2_sqr_integ()
void fp2_sqr_integ (fp2_t c, fp2_t a)
Computes the square of a quadratic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to square.
Definition at line 106 of file relic_fp2_sqr.c.
References fp2_sqrm_low().
fp2_inv()
void fp2_inv (fp2_t c, fp2_t a)
Inverts a quadratic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to invert.
Definition at line 39 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_mul_dig(), fp_null, fp_prime_get_qnr(), THROW, and TRY.
Referenced by ep2_add_basic_imp(), ep2_dbl_basic_imp(), ep2_norm_imp(), fp12_back_cyc(), fp2_conv_cyc(), fp2_exp(), fp2_inv_sim(), fp4_inv(), fp6_inv(), pp_map_sim_weilp_k2(), pp_map_weilp_k2(), pp_norm_k12(), and pp_norm_k8().
fp2_inv_cyc()
void fp2_inv_cyc (fp2_t c, fp2_t a)
Computes the inverse of a cyclotomic quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to invert.
Definition at line 92 of file relic_fpx_inv.c.
References fp_copy().
Referenced by fp2_conv_cyc(), fp2_exp_cyc(), pp_map_sim_weilp_k2(), and pp_map_weilp_k2().
fp2_inv_sim()
void fp2_inv_sim (fp2_t * c, fp2_t * a, int n)
Inverts multiple quadratic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the quadratic extension field elements to invert.
[in] n - the number of elements.
Definition at line 97 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_inv(), fp2_new, fp2_null, RLC_ALLOCA, THROW, and TRY.
Referenced by ep2_norm_sim(), and fp12_back_cyc_sim().
fp2_test_cyc()
int fp2_test_cyc (fp2_t a)
Tests if a quadratic extension field element is cyclotomic.
Parameters
[in] a - the quadratic extension field element to test.
Returns
1 if the extension field element is cyclotomic, 0 otherwise.
Definition at line 62 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_cmp_dig(), fp2_frb(), fp2_free, fp2_new, fp2_null, result, RLC_EQ, THROW, and TRY.
Referenced by fp2_pck(), fp2_size_bin(), and fp2_write_bin().
fp2_conv_cyc()
void fp2_conv_cyc (fp2_t c, fp2_t a)
Converts a quadratic extension field element to a cyclotomic element. Computes c = a^(p - 1).
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
Definition at line 39 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_inv(), fp2_inv_cyc(), fp2_new, fp2_null, THROW, and TRY.
Referenced by pp_exp_k2().
fp2_exp()
void fp2_exp (fp2_t c, fp2_t a, bn_t b)
Computes a power of a quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension element to exponentiate.
[in] b - the exponent.
Definition at line 38 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_inv(), fp2_new, fp2_null, fp2_set_dig(), RLC_NEG, THROW, and TRY.
Referenced by fp2_field_init().
fp2_exp_dig()
void fp2_exp_dig (fp2_t c, fp2_t a, dig_t b)
Computes a power of a quadratic extension field element by a small exponent.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 73 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_new, fp2_null, fp2_set_dig(), THROW, TRY, and util_bits_dig().
fp2_exp_cyc()
void fp2_exp_cyc (fp2_t c, fp2_t a, bn_t b)
Computes a power of a cyclotomic quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic element to exponentiate.
[in] b - the exponent.
Definition at line 84 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_inv_cyc(), fp2_new, fp2_null, fp2_set_dig(), FP_WIDTH, RLC_FP_BITS, RLC_NEG, THROW, and TRY.
Referenced by pp_exp_k2().
fp2_frb()
void fp2_frb (fp2_t c, fp2_t a, int i)
Computes a power of the Frobenius map of a quadratic extension field element. When i is odd, this is the same as computing the conjugate of the extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension element to conjugate.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_fpx_frb.c.
References fp2_copy(), and fp_copy().
Referenced by ep2_frb(), fp12_frb(), fp2_test_cyc(), fp4_frb(), and fp6_frb().
fp2_srt()
int fp2_srt (fp2_t c, fp2_t a)
Extracts the square root of a quadratic extension field element. Computes c = sqrt(a). The other square root is the negation of c.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 39 of file relic_fpx_srt.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_copy(), fp_null, fp_prime_get_qnr(), fp_srt(), THROW, and TRY.
Referenced by ep2_map(), ep2_upk(), and fp2_field_init().
fp2_pck()
void fp2_pck (fp2_t c, fp2_t a)
Compresses an extension field element.
Parameters
[out] r - the result.
[in] p - the extension field element to compress.
Definition at line 38 of file relic_fpx_pck.c.
References fp2_copy(), fp2_test_cyc(), fp_copy(), fp_get_bit(), fp_set_bit(), and fp_zero().
Referenced by fp2_write_bin().
fp2_upk()
int fp2_upk (fp2_t c, fp2_t a)
Decompresses a quadratic extension field element.
Parameters
[out] r - the result.
[in] p - the quadratic extension field element.
Returns
if the decompression was successful
Definition at line 48 of file relic_fpx_pck.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp_bits(), fp_copy(), fp_get_bit(), fp_null, fp_srt(), fp_sub_dig(), result, THROW, and TRY.
Referenced by fp2_read_bin().
fp3_field_init()
void fp3_field_init (void)
Initializes the cubic extension field arithmetic module.
Definition at line 146 of file relic_fpx_field.c.
References bn_div_dig(), bn_free(), bn_null, CATCH_ANY, core_get(), bn_st::dp, dv_copy(), ERR_CAUGHT, FINALLY, fp3_exp(), fp3_free, fp3_new, fp3_null, _ctx_t::fp3_p0, _ctx_t::fp3_p1, _ctx_t::fp3_p2, fp3_zero(), fp_copy(), fp_is_zero(), fp_prime_get(), fp_prime_get_cnr(), fp_set_dig(), _ctx_t::frb3, RLC_FP_DIGS, THROW, TRY, and bn_st::used.
Referenced by fp_prime_calc().
fp3_copy()
void fp3_copy (fp3_t c, fp3_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the cubic extension field element to copy.
Definition at line 128 of file relic_fpx_util.c.
References fp_copy().
Referenced by fp3_exp(), fp3_frb(), fp3_inv_sim(), fp3_mul_frb(), fp9_copy(), fp9_mul_art(), fp9_mul_basic(), and fp9_mul_dxs().
fp3_zero()
void fp3_zero (fp3_t a)
Assigns zero to a cubic extension field element.
Parameters
[out] A - the cubic extension field element to zero.
Definition at line 134 of file relic_fpx_util.c.
References fp_zero().
Referenced by fp3_field_init(), fp3_srt(), fp9_set_dig(), and fp9_zero().
fp3_is_zero()
int fp3_is_zero (fp3_t a)
Tests if a cubic extension field element is zero or not.
Parameters
[in] A - the cubic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 140 of file relic_fpx_util.c.
References fp_is_zero().
Referenced by fp9_cmp_dig(), and fp9_is_zero().
fp3_rand()
void fp3_rand (fp3_t a)
Assigns a random value to a cubic extension field element.
Parameters
[out] A - the cubic extension field element to assign.
Definition at line 144 of file relic_fpx_util.c.
References fp_rand().
Referenced by fp9_rand().
fp3_print()
void fp3_print (fp3_t a)
Prints a cubic extension field element to standard output.
Parameters
[in] A - the cubic extension field element to print.
Definition at line 150 of file relic_fpx_util.c.
References fp_print().
Referenced by fp9_print().
fp3_size_bin()
int fp3_size_bin (fp3_t a)
Returns the number of bytes necessary to store a cubic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 156 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp3_read_bin()
void fp3_read_bin (fp3_t a, const uint8_t * bin, int len)
Reads a cubic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 160 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp9_read_bin().
fp3_write_bin()
void fp3_write_bin (uint8_t * bin, int len, fp3_t a)
Writes a cubic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 169 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp9_write_bin().
fp3_cmp()
int fp3_cmp (fp3_t a, fp3_t b)
Returns the result of a comparison between two cubic extension field elements.
Parameters
[in] A - the first cubic extension field element.
[in] B - the second cubic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 49 of file relic_fpx_cmp.c.
References fp_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp3_srt(), and fp9_cmp().
fp3_cmp_dig()
int fp3_cmp_dig (fp3_t a, dig_t b)
Returns the result of a signed comparison between a cubic extension field element and a digit.
Parameters
[in] a - the cubic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 54 of file relic_fpx_cmp.c.
References fp_cmp_dig(), fp_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp9_cmp_dig().
fp3_set_dig()
void fp3_set_dig (fp3_t a, dig_t b)
Assigns a cubic extension field element to a digit.
Parameters
[in] a - the cubic extension field element.
[in] b - the digit.
Definition at line 178 of file relic_fpx_util.c.
References fp_set_dig(), and fp_zero().
Referenced by fp3_exp(), fp9_set_dig(), and pp_mil_k54().
fp3_add_basic()
void fp3_add_basic (fp3_t c, fp3_t a, fp3_t b)
Adds two cubic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
fp3_add_integ()
void fp3_add_integ (fp3_t c, fp3_t a, fp3_t b)
Adds two cubic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
fp3_sub_basic()
void fp3_sub_basic (fp3_t c, fp3_t a, fp3_t b)
Subtracts a cubic extension field element from another using basic arithmetic.
Parameters
[out] C - the result.
[in] A - the first cubic extension field element.
[in] B - the second cubic extension field element.
fp3_sub_integ()
void fp3_sub_integ (fp3_t c, fp3_t a, fp3_t b)
Subtracts a cubic extension field element from another using integrated modular reduction.
Parameters
[out] C - the result.
[in] A - the first cubic extension field element.
[in] B - the second cubic extension field element.
fp3_neg()
void fp3_neg (fp3_t c, fp3_t a)
Negates a cubic extension field element. Computes c = -a.
Parameters
[out] C - the result.
[out] A - the cubic extension field element to negate.
Definition at line 103 of file relic_fpx_add.c.
Referenced by fp9_neg().
fp3_dbl_basic()
void fp3_dbl_basic (fp3_t c, fp3_t a)
Doubles a cubic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to double.
fp3_dbl_integ()
void fp3_dbl_integ (fp3_t c, fp3_t a)
Doubles a cubic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to double.
fp3_mul_basic()
void fp3_mul_basic (fp3_t c, fp3_t a, fp3_t b)
Multiples two cubic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 42 of file relic_fp3_mul.c.
References CATCH_ANY, dv_null, ERR_CAUGHT, FINALLY, fp_addc_low(), fp_addd_low(), fp_muln_low(), fp_prime_get_cnr(), fp_subc_low(), THROW, and TRY.
fp3_mul_integ()
void fp3_mul_integ (fp3_t c, fp3_t a, fp3_t b)
Multiples two cubic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first cubic extension field element.
[in] b - the second cubic extension field element.
Definition at line 146 of file relic_fp3_mul.c.
References fp3_mulm_low().
fp3_mul_nor()
void fp3_mul_nor (fp3_t c, fp3_t a)
Multiplies a cubic extension field element by a cubic non-residue.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to multiply.
Definition at line 152 of file relic_fp3_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_copy(), fp_null, fp_prime_get_cnr(), THROW, and TRY.
Referenced by fp3_mul_frb(), fp9_inv(), fp9_mul_art(), fp9_mul_basic(), fp9_mul_dxs(), fp9_sqr_basic(), and pp_mil_k54().
fp3_mul_frb()
void fp3_mul_frb (fp3_t c, fp3_t a, int i, int j)
Multiplies a cubic extension field element by a power of the constant needed to compute a power of the Frobenius map. If the flag is zero, the map is computed on the cubic extension directly; otherwise the map is computed on a higher extension.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
[in] i - the power of the Frobenius map.
[in] j - the power of the constant.
Definition at line 180 of file relic_fp3_mul.c.
References core_get(), fp3_copy(), fp3_mul_nor(), _ctx_t::fp3_p0, _ctx_t::fp3_p1, _ctx_t::fp3_p2, and _ctx_t::frb3.
Referenced by fp18_frb(), fp3_frb(), fp54_frb(), and fp9_frb().
fp3_sqr_basic()
void fp3_sqr_basic (fp3_t c, fp3_t a)
Computes the square of a cubic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to square.
Definition at line 42 of file relic_fp3_sqr.c.
References CATCH_ANY, dv_null, ERR_CAUGHT, FINALLY, fp_addc_low(), fp_addd_low(), fp_hlvd_low(), fp_muln_low(), fp_prime_get_cnr(), fp_sqrn_low(), fp_subc_low(), THROW, and TRY.
fp3_sqr_integ()
void fp3_sqr_integ (fp3_t c, fp3_t a)
Computes the square of a cubic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to square.
Definition at line 126 of file relic_fp3_sqr.c.
References fp3_sqrm_low().
fp3_inv()
void fp3_inv (fp3_t c, fp3_t a)
Inverts a cubic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to invert.
Definition at line 139 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_copy(), fp_null, fp_prime_get_cnr(), THROW, and TRY.
Referenced by fp3_exp(), fp3_inv_sim(), and fp9_inv().
fp3_inv_sim()
void fp3_inv_sim (fp3_t * c, fp3_t * a, int n)
Inverts multiple cubic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the cubic extension field elements to invert.
[in] n - the number of elements.
Definition at line 222 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp3_copy(), fp3_free, fp3_inv(), fp3_new, fp3_null, RLC_ALLOCA, THROW, and TRY.
fp3_exp()
void fp3_exp (fp3_t c, fp3_t a, bn_t b)
Computes a power of a cubic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the cubic extension element to exponentiate.
[in] b - the exponent.
Definition at line 104 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp3_copy(), fp3_free, fp3_inv(), fp3_new, fp3_null, fp3_set_dig(), RLC_NEG, THROW, and TRY.
Referenced by fp3_field_init(), and fp3_srt().
fp3_frb()
void fp3_frb (fp3_t c, fp3_t a, int i)
Computes a power of the Frobenius map of a cubic extension field element.
Parameters
[out] c - the result.
[in] a - the cubic extension element to exponentiate.
[in] i - the power of the Frobenius map.
Definition at line 52 of file relic_fpx_frb.c.
References fp3_copy(), and fp3_mul_frb().
Referenced by fp18_frb(), fp3_srt(), and fp9_frb().
fp3_srt()
int fp3_srt (fp3_t c, fp3_t a)
Extracts the square root of a cubic extension field element. Computes c = sqrt(a). The other square root is the negation of c.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 93 of file relic_fpx_srt.c.
References bn_div_dig(), bn_free(), bn_null, CATCH_ANY, bn_st::dp, dv_copy(), ERR_CAUGHT, FINALLY, fp3_cmp(), fp3_exp(), fp3_frb(), fp3_free, fp3_new, fp3_null, fp3_zero(), fp_prime_get(), fp_prime_get_mod8(), fp_sub_dig(), RLC_EQ, RLC_FP_DIGS, THROW, TRY, and bn_st::used.
fp4_copy()
void fp4_copy (fp4_t c, fp4_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the sextic extension field element to copy.
Definition at line 184 of file relic_fpx_util.c.
References fp2_copy().
Referenced by fp4_exp(), fp4_frb(), fp8_copy(), fp8_inv_cyc(), and fp8_mul_art().
fp4_zero()
void fp4_zero (fp4_t a)
Assigns zero to a quartic extension field element.
Parameters
[out] A - the quartic extension field element to zero.
Definition at line 189 of file relic_fpx_util.c.
References fp2_zero().
Referenced by fp8_set_dig(), and fp8_zero().
fp4_is_zero()
int fp4_is_zero (fp4_t a)
Tests if a quartic extension field element is zero or not.
Parameters
[in] A - the quartic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 194 of file relic_fpx_util.c.
References fp2_is_zero().
Referenced by fp8_cmp_dig(), and fp8_is_zero().
fp4_rand()
void fp4_rand (fp4_t a)
Assigns a random value to a quartic extension field element.
Parameters
[out] A - the quartic extension field element to assign.
Definition at line 198 of file relic_fpx_util.c.
References fp2_rand().
Referenced by fp8_rand().
fp4_print()
void fp4_print (fp4_t a)
Prints a quartic extension field element to standard output.
Parameters
[in] A - the quartic extension field element to print.
Definition at line 203 of file relic_fpx_util.c.
References fp2_print().
Referenced by fp8_print().
fp4_size_bin()
int fp4_size_bin (fp4_t a)
Returns the number of bytes necessary to store a quartic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 208 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp4_read_bin()
void fp4_read_bin (fp4_t a, const uint8_t * bin, int len)
Reads a quartic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 212 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp8_read_bin().
fp4_write_bin()
void fp4_write_bin (uint8_t * bin, int len, fp4_t a)
Writes a quartic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 220 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp8_write_bin().
fp4_cmp()
int fp4_cmp (fp4_t a, fp4_t b)
Returns the result of a comparison between two quartic extension field elements.
Parameters
[in] A - the first quartic extension field element.
[in] B - the second quartic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 59 of file relic_fpx_cmp.c.
References fp2_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp8_cmp().
fp4_cmp_dig()
int fp4_cmp_dig (fp4_t a, dig_t b)
Returns the result of a signed comparison between a quartic extension field element and a digit.
Parameters
[in] a - the quartic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 64 of file relic_fpx_cmp.c.
References fp2_cmp_dig(), fp2_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp8_cmp_dig().
fp4_set_dig()
void fp4_set_dig (fp4_t a, dig_t b)
Assigns a quartic extension field element to a digit.
Parameters
[in] a - the quartic extension field element.
[in] b - the digit.
Definition at line 228 of file relic_fpx_util.c.
References fp2_set_dig(), and fp2_zero().
Referenced by fp4_exp(), and fp8_set_dig().
fp4_add()
void fp4_add (fp4_t c, fp4_t a, fp4_t b)
Adds two quartic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Definition at line 125 of file relic_fpx_add.c.
Referenced by fp8_add(), fp8_mul_basic(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_basic(), fp8_sqr_cyc(), and fp8_sqr_unr().
fp4_sub()
void fp4_sub (fp4_t c, fp4_t a, fp4_t b)
Subtracts a quartic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 130 of file relic_fpx_add.c.
Referenced by fp8_inv(), fp8_mul_basic(), fp8_sqr_basic(), fp8_sqr_cyc(), and fp8_sub().
fp4_neg()
void fp4_neg (fp4_t c, fp4_t a)
Negates a quartic extension field element. Computes c = -a.
Parameters
[out] C - the result.
[out] A - the quartic extension field element to negate.
Definition at line 141 of file relic_fpx_add.c.
References fp2_neg().
Referenced by fp8_inv(), fp8_inv_cyc(), and fp8_neg().
fp4_dbl()
void fp4_dbl (fp4_t c, fp4_t a)
Doubles a quartic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to double.
Definition at line 135 of file relic_fpx_add.c.
Referenced by fp8_dbl(), fp8_sqr_basic(), and fp8_sqr_cyc().
fp4_mul_unr()
void fp4_mul_unr (dv4_t c, fp4_t a, fp4_t b)
Multiples two quartic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 87 of file relic_fp4_mul.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_addm_low(), fp2_addn_low(), fp2_free, fp2_mulc_low(), fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_norh_low(), fp2_null, fp2_subc_low(), THROW, and TRY.
Referenced by fp12_sqr_unr(), fp4_mul_lazyr(), fp8_mul_dxs(), and fp8_mul_unr().
fp4_mul_basic()
void fp4_mul_basic (fp4_t c, fp4_t a, fp4_t b)
Multiples two quartic extension field elements.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 42 of file relic_fp4_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, THROW, and TRY.
fp4_mul_lazyr()
void fp4_mul_lazyr (fp4_t c, fp4_t a, fp4_t b)
Multiples two quartic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 132 of file relic_fp4_mul.c.
References CATCH_ANY, dv4_free, dv4_new, dv4_null, ERR_CAUGHT, FINALLY, fp2_rdcn_low(), fp4_mul_unr(), THROW, and TRY.
fp4_mul_art()
void fp4_mul_art (fp4_t c, fp4_t a)
Multiplies a quartic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to multiply.
Definition at line 151 of file relic_fp4_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_new, fp2_null, THROW, and TRY.
Referenced by fp24_frb(), fp48_frb(), fp8_frb(), fp8_inv(), fp8_mul_art(), fp8_mul_basic(), fp8_sqr_basic(), and fp8_sqr_cyc().
fp4_mul_dxs()
void fp4_mul_dxs (fp4_t c, fp4_t a, fp4_t b)
Multiples a dense quartic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - a quartic extension field element.
[in] b - a sparse quartic extension field element.
fp4_sqr_unr()
void fp4_sqr_unr (dv6_t c, fp4_t a)
Computes the square of a quartic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to square.
fp4_sqr_basic()
void fp4_sqr_basic (fp4_t c, fp4_t a)
Computes the squares of a quartic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to square.
Definition at line 42 of file relic_fp4_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, THROW, and TRY.
fp4_sqr_lazyr()
void fp4_sqr_lazyr (fp4_t c, fp4_t a)
Computes the square of a quartic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to square.
Definition at line 110 of file relic_fp4_sqr.c.
References CATCH_ANY, dv4_free, dv4_new, dv4_null, ERR_CAUGHT, FINALLY, fp2_rdcn_low(), fp4_sqr_unr(), THROW, and TRY.
fp4_inv()
void fp4_inv (fp4_t c, fp4_t a)
Inverts a quartic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to invert.
Definition at line 269 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_inv(), fp2_neg(), fp2_new, fp2_null, THROW, and TRY.
Referenced by fp4_exp(), and fp8_inv().
fp4_inv_cyc()
void fp4_inv_cyc (fp4_t c, fp4_t a)
Computes the inverse of a cyclotomic quartic extension field element.
For cyclotomic elements, this is equivalent to computing the conjugate. A cyclotomic element is one previously raised to the (p^2 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to invert.
Definition at line 264 of file relic_fpx_inv.c.
References fp2_copy(), and fp2_neg().
fp4_exp()
void fp4_exp (fp4_t c, fp4_t a, bn_t b)
Computes a power of a quartic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the quartic extension element to exponentiate.
[in] b - the exponent.
Definition at line 140 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp4_copy(), fp4_free, fp4_inv(), fp4_new, fp4_null, fp4_set_dig(), RLC_NEG, THROW, and TRY.
fp4_frb()
void fp4_frb (fp4_t c, fp4_t a, int i)
Computes a power of the Frobenius endomorphism of a quartic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a quartic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 64 of file relic_fpx_frb.c.
References fp2_frb(), fp2_mul_frb(), and fp4_copy().
Referenced by fp8_frb().
fp6_copy()
void fp6_copy (fp6_t c, fp6_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the sextic extension field element to copy.
Definition at line 233 of file relic_fpx_util.c.
References fp2_copy().
Referenced by fp12_copy(), fp12_inv_cyc(), fp12_mul_art(), fp6_exp(), and fp6_frb().
fp6_zero()
void fp6_zero (fp6_t a)
Assigns zero to a sextic extension field element.
Parameters
[out] A - the sextic extension field element to zero.
Definition at line 239 of file relic_fpx_util.c.
References fp2_zero().
Referenced by fp12_set_dig(), and fp12_zero().
fp6_is_zero()
int fp6_is_zero (fp6_t a)
Tests if a sextic extension field element is zero or not.
Parameters
[in] A - the sextic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 245 of file relic_fpx_util.c.
References fp2_is_zero().
Referenced by fp12_cmp_dig(), and fp12_is_zero().
fp6_rand()
void fp6_rand (fp6_t a)
Assigns a random value to a sextic extension field element.
Parameters
[out] A - the sextic extension field element to assign.
Definition at line 249 of file relic_fpx_util.c.
References fp2_rand().
Referenced by fp12_rand().
fp6_print()
void fp6_print (fp6_t a)
Prints a sextic extension field element to standard output.
Parameters
[in] A - the sextic extension field element to print.
Definition at line 255 of file relic_fpx_util.c.
References fp2_print().
Referenced by fp12_print().
fp6_size_bin()
int fp6_size_bin (fp6_t a)
Returns the number of bytes necessary to store a quadratic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 261 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp6_read_bin()
void fp6_read_bin (fp6_t a, const uint8_t * bin, int len)
Reads a quadratic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 265 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp12_read_bin().
fp6_write_bin()
void fp6_write_bin (uint8_t * bin, int len, fp6_t a)
Writes a sextic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 274 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp12_write_bin().
fp6_cmp()
int fp6_cmp (fp6_t a, fp6_t b)
Returns the result of a comparison between two sextic extension field elements.
Parameters
[in] A - the first sextic extension field element.
[in] B - the second sextic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 69 of file relic_fpx_cmp.c.
References fp2_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp12_cmp().
fp6_cmp_dig()
int fp6_cmp_dig (fp6_t a, dig_t b)
Returns the result of a signed comparison between a sextic extension field element and a digit.
Parameters
[in] a - the sextic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 74 of file relic_fpx_cmp.c.
References fp2_cmp_dig(), fp2_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp12_cmp_dig().
fp6_set_dig()
void fp6_set_dig (fp6_t a, dig_t b)
Assigns a sextic extension field element to a digit.
Parameters
[in] a - the sextic extension field element.
[in] b - the digit.
Definition at line 283 of file relic_fpx_util.c.
References fp2_set_dig(), and fp2_zero().
Referenced by fp12_set_dig(), and fp6_exp().
fp6_add()
void fp6_add (fp6_t c, fp6_t a, fp6_t b)
Adds two sextic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first sextic extension field element.
[in] b - the second sextic extension field element.
Definition at line 146 of file relic_fpx_add.c.
Referenced by fp12_add(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_mul_unr(), and fp12_sqr_basic().
fp6_sub()
void fp6_sub (fp6_t c, fp6_t a, fp6_t b)
Subtracts a sextic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 152 of file relic_fpx_add.c.
Referenced by fp12_inv(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_sqr_basic(), and fp12_sub().
fp6_neg()
void fp6_neg (fp6_t c, fp6_t a)
Negates a sextic extension field element. Computes c = -a.
Parameters
[out] C - the result.
[out] A - the sextic extension field element to negate.
Definition at line 164 of file relic_fpx_add.c.
References fp2_neg().
Referenced by fp12_inv(), fp12_inv_cyc(), and fp12_neg().
fp6_dbl()
void fp6_dbl (fp6_t c, fp6_t a)
Doubles a sextic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to double.
Definition at line 158 of file relic_fpx_add.c.
Referenced by fp12_dbl(), and fp12_sqr_basic().
fp6_mul_unr()
void fp6_mul_unr (dv6_t c, fp6_t a, fp6_t b) inline
Multiples two sextic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 112 of file relic_fp6_mul.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_addd_low(), fp2_addm_low(), fp2_addn_low(), fp2_free, fp2_mulc_low(), fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_norh_low(), fp2_null, fp2_subc_low(), THROW, and TRY.
Referenced by fp12_mul_unr(), and fp6_mul_lazyr().
fp6_mul_basic()
void fp6_mul_basic (fp6_t c, fp6_t a, fp6_t b)
Multiples two sextic extension field elements.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 41 of file relic_fp6_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_new, fp2_null, THROW, and TRY.
fp6_mul_lazyr()
void fp6_mul_lazyr (fp6_t c, fp6_t a, fp6_t b)
Multiples two sextic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 203 of file relic_fp6_mul.c.
References CATCH_ANY, dv6_free, dv6_new, dv6_null, ERR_CAUGHT, FINALLY, fp2_rdcn_low(), fp6_mul_unr(), THROW, and TRY.
fp6_mul_art()
void fp6_mul_art (fp6_t c, fp6_t a)
Multiplies a sextic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to multiply.
Definition at line 280 of file relic_fp6_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_new, fp2_null, THROW, and TRY.
Referenced by fp12_inv(), fp12_mul_art(), fp12_mul_basic(), fp12_mul_dxs_basic(), and fp12_sqr_basic().
fp6_mul_dxs()
void fp6_mul_dxs (fp6_t c, fp6_t a, fp6_t b)
Multiples a dense sextic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - a sextic extension field element.
[in] b - a sparse sextic extension field element.
Definition at line 223 of file relic_fp6_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_new, fp2_null, THROW, and TRY.
Referenced by fp12_mul_dxs_basic().
fp6_sqr_unr()
void fp6_sqr_unr (dv6_t c, fp6_t a)
Computes the square of a sextic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to square.
Definition at line 114 of file relic_fp6_sqr.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_addd_low(), fp2_addm_low(), fp2_dblm_low(), fp2_free, fp2_mulc_low(), fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_null, fp2_sqrn_low(), fp2_subc_low(), fp2_subm_low(), fp_hlvd_low(), THROW, and TRY.
Referenced by fp6_sqr_lazyr().
fp6_sqr_basic()
void fp6_sqr_basic (fp6_t c, fp6_t a)
Computes the squares of a sextic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to square.
Definition at line 42 of file relic_fp6_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, THROW, and TRY.
fp6_sqr_lazyr()
void fp6_sqr_lazyr (fp6_t c, fp6_t a)
Computes the square of a sextic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to square.
Definition at line 215 of file relic_fp6_sqr.c.
References CATCH_ANY, dv6_free, dv6_new, dv6_null, ERR_CAUGHT, FINALLY, fp2_rdcn_low(), fp6_sqr_unr(), THROW, and TRY.
fp6_inv()
void fp6_inv (fp6_t c, fp6_t a)
Inverts a sextic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to invert.
Definition at line 297 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_inv(), fp2_new, fp2_null, THROW, and TRY.
Referenced by fp12_inv(), and fp6_exp().
fp6_exp()
void fp6_exp (fp6_t c, fp6_t a, bn_t b)
Computes a power of a sextic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the sextic extension element to exponentiate.
[in] b - the exponent.
Definition at line 176 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_copy(), fp6_free, fp6_inv(), fp6_new, fp6_null, fp6_set_dig(), RLC_NEG, THROW, and TRY.
fp6_frb()
void fp6_frb (fp6_t c, fp6_t a, int i)
Computes a power of the Frobenius endomorphism of a sextic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a sextic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 74 of file relic_fpx_frb.c.
References fp2_frb(), fp2_mul_frb(), and fp6_copy().
Referenced by fp12_frb().
fp8_copy()
void fp8_copy (fp8_t c, fp8_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the octic extension field element to copy.
Definition at line 289 of file relic_fpx_util.c.
References fp4_copy().
Referenced by ep8_add_basic(), ep8_dbl_basic(), fp24_copy(), fp24_mul_art(), fp24_mul_basic(), fp24_mul_dxs(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_mul_dxs(), fp8_exp(), fp8_exp_cyc(), fp8_frb(), fp8_inv_sim(), pp_add_k48_basic(), pp_dbl_k48_basic(), pp_exp_k8(), and pp_mil_k48().
fp8_zero()
void fp8_zero (fp8_t a)
Assigns zero to an octic extension field element.
Parameters
[out] A - the octic extension field element to zero.
Definition at line 294 of file relic_fpx_util.c.
References fp4_zero().
Referenced by ep8_add_basic(), fp24_set_dig(), fp24_zero(), fp48_pck(), fp48_read_bin(), pp_dbl_k48_projc(), and pp_mil_k8().
fp8_is_zero()
int fp8_is_zero (fp8_t a)
Tests if an octic extension field element is zero or not.
Parameters
[in] A - the octic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 299 of file relic_fpx_util.c.
References fp4_is_zero().
Referenced by ep8_add_basic(), fp24_cmp_dig(), fp24_is_zero(), fp48_upk(), and pp_map_k48().
fp8_rand()
void fp8_rand (fp8_t a)
Assigns a random value to an octic extension field element.
Parameters
[out] A - the octic extension field element to assign.
Definition at line 303 of file relic_fpx_util.c.
References fp4_rand().
Referenced by fp24_rand().
fp8_print()
void fp8_print (fp8_t a)
Prints an octic extension field element to standard output.
Parameters
[in] A - the octic extension field element to print.
Definition at line 308 of file relic_fpx_util.c.
References fp4_print().
Referenced by fp24_print().
fp8_size_bin()
int fp8_size_bin (fp8_t a, int pack)
Returns the number of bytes necessary to store an octic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 313 of file relic_fpx_util.c.
References fp8_test_cyc(), and RLC_FP_BYTES.
fp8_read_bin()
void fp8_read_bin (fp8_t a, const uint8_t * bin, int len)
Reads an octic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 325 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp4_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp24_read_bin(), and fp48_read_bin().
fp8_write_bin()
void fp8_write_bin (uint8_t * bin, int len, fp8_t a)
Writes an octic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 333 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp4_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp24_write_bin(), and fp48_write_bin().
fp8_cmp()
int fp8_cmp (fp8_t a, fp8_t b)
Returns the result of a comparison between two octic extension field elements.
Parameters
[in] A - the first octic extension field element.
[in] B - the second octic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 89 of file relic_fpx_cmp.c.
References fp4_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp24_cmp().
fp8_cmp_dig()
int fp8_cmp_dig (fp8_t a, dig_t b)
Returns the result of a signed comparison between an octic extension field element and a digit.
Parameters
[in] a - the octic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 94 of file relic_fpx_cmp.c.
References fp4_cmp_dig(), fp4_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp24_cmp_dig(), and fp8_test_cyc().
fp8_set_dig()
void fp8_set_dig (fp8_t a, dig_t b)
Assigns an octic extension field element to a digit.
Parameters
[in] a - the octic extension field element.
[in] b - the digit.
Definition at line 341 of file relic_fpx_util.c.
References fp4_set_dig(), and fp4_zero().
Referenced by fp24_set_dig(), fp8_exp(), fp8_exp_cyc(), pp_map_oatep_k8(), and pp_mil_k48().
fp8_add()
void fp8_add (fp8_t c, fp8_t a, fp8_t b)
Adds two octic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first octic extension field element.
[in] b - the second octic extension field element.
Definition at line 170 of file relic_fpx_add.c.
References fp4_add().
Referenced by ep8_dbl_basic(), fp24_add(), fp24_inv(), fp24_mul_basic(), fp24_mul_dxs(), fp24_mul_unr(), fp24_sqr_basic(), fp24_sqr_unr(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_mul_dxs(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), pp_add_k48_projc(), and pp_dbl_k48_projc().
fp8_sub()
void fp8_sub (fp8_t c, fp8_t a, fp8_t b)
Subtracts an octic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 175 of file relic_fpx_add.c.
References fp4_sub().
Referenced by ep8_add_basic(), ep8_dbl_basic(), fp24_inv(), fp24_mul_basic(), fp24_mul_dxs(), fp24_sqr_basic(), fp24_sqr_unr(), fp24_sub(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), pp_add_k48_basic(), pp_add_k48_projc(), pp_dbl_k48_basic(), and pp_dbl_k48_projc().
fp8_neg()
void fp8_neg (fp8_t c, fp8_t a)
Negates an octic extension field element. Computes c = -a.
Parameters
[out] C - the result.
[out] A - the octic extension field element to negate.
Definition at line 185 of file relic_fpx_add.c.
References fp4_neg().
Referenced by fp24_neg(), pp_add_k48_projc(), and pp_mil_k48().
fp8_dbl()
void fp8_dbl (fp8_t c, fp8_t a)
Doubles an octic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the octic extension field element to double.
Definition at line 180 of file relic_fpx_add.c.
References fp4_dbl().
Referenced by ep8_dbl_basic(), fp24_dbl(), fp24_sqr_basic(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), and pp_dbl_k48_projc().
fp8_mul_unr()
void fp8_mul_unr (dv8_t c, fp8_t a, fp8_t b)
Multiples two octic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 182 of file relic_fp8_mul.c.
References CATCH_ANY, dv4_free, dv4_new, dv4_null, dv_copy(), ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp4_add(), fp4_free, fp4_mul_unr(), fp4_new, fp4_null, RLC_FP_DIGS, THROW, and TRY.
Referenced by fp24_mul_unr(), fp24_sqr_unr(), and fp8_mul_lazyr().
fp8_mul_basic()
void fp8_mul_basic (fp8_t c, fp8_t a, fp8_t b)
Multiples two octic extension field elements.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 42 of file relic_fp8_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp4_add(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sub(), THROW, and TRY.
fp8_mul_lazyr()
void fp8_mul_lazyr (fp8_t c, fp8_t a, fp8_t b)
Multiples two octic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 237 of file relic_fp8_mul.c.
References CATCH_ANY, dv8_free, dv8_new, dv8_null, ERR_CAUGHT, FINALLY, fp2_rdcn_low(), fp8_mul_unr(), THROW, and TRY.
fp8_mul_art()
void fp8_mul_art (fp8_t c, fp8_t a)
Multiplies an octic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the octic extension field element to multiply.
Definition at line 258 of file relic_fp8_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp4_copy(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, THROW, and TRY.
Referenced by fp24_inv(), fp24_mul_art(), fp24_mul_basic(), fp24_mul_dxs(), fp24_sqr_basic(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_frb(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), and fp48_sqr_pck_lazyr().
fp8_mul_dxs()
void fp8_mul_dxs (fp8_t c, fp8_t a, fp8_t b)
Multiples a dense octic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - an octic extension field element.
[in] b - a sparse octic extension field element.
Definition at line 124 of file relic_fp8_mul.c.
References CATCH_ANY, dv4_free, dv4_new, dv4_null, dv_copy(), ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp4_add(), fp4_free, fp4_mul_dxs_unr(), fp4_mul_unr(), fp4_new, fp4_null, RLC_FP_DIGS, THROW, and TRY.
Referenced by pp_mil_k8().
fp8_sqr_unr()
void fp8_sqr_unr (dv8_t c, fp8_t a)
Computes the square of an octic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element to square.
Definition at line 73 of file relic_fp8_sqr.c.
References CATCH_ANY, dv4_free, dv4_new, dv4_null, dv_copy(), ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp4_add(), fp4_free, fp4_new, fp4_null, fp4_sqr_unr(), RLC_FP_DIGS, THROW, and TRY.
Referenced by fp24_sqr_unr(), fp48_sqr_pck_lazyr(), and fp8_sqr_lazyr().
fp8_sqr_basic()
void fp8_sqr_basic (fp8_t c, fp8_t a)
Computes the squares of an octic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the octic extension field element to square.
Definition at line 42 of file relic_fp8_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp4_add(), fp4_dbl(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sub(), THROW, and TRY.
fp8_sqr_lazyr()
void fp8_sqr_lazyr (fp8_t c, fp8_t a)
Computes the square of an octic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octic extension field element to square.
Definition at line 119 of file relic_fp8_sqr.c.
References CATCH_ANY, dv8_free, dv8_new, dv8_null, ERR_CAUGHT, FINALLY, fp2_rdcn_low(), fp8_sqr_unr(), THROW, and TRY.
fp8_sqr_cyc()
void fp8_sqr_cyc (fp8_t c, fp8_t a)
Computes the square of a cyclotomic octic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 140 of file relic_fp8_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp4_add(), fp4_dbl(), fp4_free, fp4_mul_art(), fp4_new, fp4_null, fp4_sub(), fp_add_dig(), fp_sub_dig(), THROW, and TRY.
Referenced by fp8_exp_cyc(), and pp_exp_k8().
fp8_inv()
void fp8_inv (fp8_t c, fp8_t a)
Inverts an octic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the octic extension field element to invert.
Definition at line 361 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp4_free, fp4_inv(), fp4_mul_art(), fp4_neg(), fp4_new, fp4_null, fp4_sub(), THROW, and TRY.
Referenced by ep8_add_basic(), ep8_dbl_basic(), fp24_inv(), fp48_back_cyc(), fp8_conv_cyc(), fp8_exp(), and fp8_inv_sim().
fp8_inv_cyc()
void fp8_inv_cyc (fp8_t c, fp8_t a)
Computes the inverse of a cyclotomic octic extension field element.
For cyclotomic elements, this is equivalent to computing the conjugate. A cyclotomic element is one previously raised to the (p^4 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the octic extension field element to invert.
Definition at line 356 of file relic_fpx_inv.c.
References fp4_copy(), and fp4_neg().
Referenced by fp8_conv_cyc(), fp8_exp_cyc(), fp8_test_cyc(), pp_exp_k8(), and pp_map_oatep_k8().
fp8_inv_sim()
void fp8_inv_sim (fp8_t * c, fp8_t * a, int n)
Inverts multiple octic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the octic extension field elements to invert.
[in] n - the number of elements.
Definition at line 389 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_copy(), fp8_free, fp8_inv(), fp8_new, fp8_null, RLC_ALLOCA, THROW, and TRY.
Referenced by fp48_back_cyc_sim().
fp8_test_cyc()
int fp8_test_cyc (fp8_t a)
Tests if an octic extension field element is cyclotomic.
Parameters
[in] a - the octic extension field element to test.
Returns
1 if the extension field element is cyclotomic, 0 otherwise.
Definition at line 173 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_cmp_dig(), fp8_free, fp8_inv_cyc(), fp8_new, fp8_null, result, RLC_EQ, THROW, and TRY.
Referenced by fp8_exp(), and fp8_size_bin().
fp8_conv_cyc()
void fp8_conv_cyc (fp8_t c, fp8_t a)
Converts an octic extension field element to a cyclotomic element. Computes c = a^(p^4 - 1).
Parameters
[out] c - the result.
[in] a - the octic extension field element.
Definition at line 150 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_free, fp8_inv(), fp8_inv_cyc(), fp8_new, fp8_null, THROW, and TRY.
Referenced by pp_exp_k8().
fp8_exp()
void fp8_exp (fp8_t c, fp8_t a, bn_t b)
Computes a power of an octic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the octic extension element to exponentiate.
[in] b - the exponent.
Definition at line 212 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_copy(), fp8_exp_cyc(), fp8_free, fp8_inv(), fp8_new, fp8_null, fp8_set_dig(), fp8_test_cyc(), RLC_NEG, THROW, and TRY.
fp8_exp_cyc()
void fp8_exp_cyc (fp8_t c, fp8_t a, bn_t b)
Computes a power of a cyclotomic octic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 195 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_copy(), fp8_free, fp8_inv_cyc(), fp8_new, fp8_null, fp8_set_dig(), fp8_sqr_cyc(), FP_WIDTH, RLC_FP_BITS, RLC_NEG, THROW, and TRY.
Referenced by fp8_exp(), and pp_exp_k8().
fp8_frb()
void fp8_frb (fp8_t c, fp8_t a, int i)
Computes a power of the Frobenius endomorphism of an octic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - an octic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 86 of file relic_fpx_frb.c.
References fp2_mul_frb(), fp4_frb(), fp4_mul_art(), fp8_copy(), and fp_prime_get_mod8().
Referenced by fp24_frb(), and pp_exp_k8().
fp9_copy()
void fp9_copy (fp9_t c, fp9_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the nonic extension field element to copy.
Definition at line 346 of file relic_fpx_util.c.
References fp3_copy().
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_copy(), fp18_inv_cyc(), fp18_mul_art(), fp18_mul_dxs(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_mul_dxs(), fp9_exp(), fp9_frb(), fp9_inv_sim(), pp_add_k54_basic(), pp_dbl_k54_basic(), and pp_mil_k54().
fp9_zero()
void fp9_zero (fp9_t a)
Assigns zero to a nonic extension field element.
Parameters
[out] A - the nonic extension field element to zero.
Definition at line 352 of file relic_fpx_util.c.
References fp3_zero().
Referenced by ep9_add_basic(), fp18_set_dig(), fp18_zero(), fp54_pck(), fp54_read_bin(), pp_dbl_k54_projc(), and pp_mil_k54().
fp9_is_zero()
int fp9_is_zero (fp9_t a)
Tests if a nonic extension field element is zero or not.
Parameters
[in] A - the nonic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 358 of file relic_fpx_util.c.
References fp3_is_zero().
Referenced by ep9_add_basic(), fp18_cmp_dig(), fp18_is_zero(), fp54_upk(), and pp_map_k54().
fp9_rand()
void fp9_rand (fp9_t a)
Assigns a random value to a nonic extension field element.
Parameters
[out] A - the nonic extension field element to assign.
Definition at line 362 of file relic_fpx_util.c.
References fp3_rand().
Referenced by fp18_rand().
fp9_print()
void fp9_print (fp9_t a)
Prints a nonic extension field element to standard output.
Parameters
[in] A - the nonic extension field element to print.
Definition at line 368 of file relic_fpx_util.c.
References fp3_print().
Referenced by fp18_print().
fp9_size_bin()
int fp9_size_bin (fp9_t a)
Returns the number of bytes necessary to store a quadratic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 374 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp9_read_bin()
void fp9_read_bin (fp9_t a, const uint8_t * bin, int len)
Reads a quadratic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 378 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp3_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp18_read_bin(), and fp54_read_bin().
fp9_write_bin()
void fp9_write_bin (uint8_t * bin, int len, fp9_t a)
Writes a nonic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 387 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp3_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp18_write_bin(), and fp54_write_bin().
fp9_cmp()
int fp9_cmp (fp9_t a, fp9_t b)
Returns the result of a comparison between two nonic extension field elements.
Parameters
[in] A - the first nonic extension field element.
[in] B - the second nonic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 79 of file relic_fpx_cmp.c.
References fp3_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp18_cmp().
fp9_cmp_dig()
int fp9_cmp_dig (fp9_t a, dig_t b)
Returns the result of a signed comparison between a nonic extension field element and a digit.
Parameters
[in] a - the nonic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 84 of file relic_fpx_cmp.c.
References fp3_cmp_dig(), fp3_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp18_cmp_dig().
fp9_set_dig()
void fp9_set_dig (fp9_t a, dig_t b)
Assigns a nonic extension field element to a digit.
Parameters
[in] a - the nonic extension field element.
[in] b - the digit.
Definition at line 396 of file relic_fpx_util.c.
References fp3_set_dig(), and fp3_zero().
Referenced by fp18_set_dig(), fp9_exp(), and pp_mil_k54().
fp9_add()
void fp9_add (fp9_t c, fp9_t a, fp9_t b)
Adds two nonic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first nonic extension field element.
[in] b - the second nonic extension field element.
Definition at line 190 of file relic_fpx_add.c.
Referenced by ep9_dbl_basic(), fp18_add(), fp18_mul_basic(), fp18_mul_dxs(), fp18_mul_unr(), fp18_sqr_basic(), fp18_sqr_unr(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_mul_dxs(), fp54_sqr_cyc_basic(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), pp_add_k54_projc(), and pp_dbl_k54_projc().
fp9_sub()
void fp9_sub (fp9_t c, fp9_t a, fp9_t b)
Subtracts a nonic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 196 of file relic_fpx_add.c.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp18_mul_basic(), fp18_mul_dxs(), fp18_sqr_basic(), fp18_sub(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_sqr_cyc_basic(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), pp_add_k54_basic(), pp_add_k54_projc(), pp_dbl_k54_basic(), and pp_dbl_k54_projc().
fp9_neg()
void fp9_neg (fp9_t c, fp9_t a)
Negates a nonic extension field element. Computes c = -a.
Parameters
[out] C - the result.
[out] A - the nonic extension field element to negate.
Definition at line 208 of file relic_fpx_add.c.
References fp3_neg().
Referenced by fp18_inv(), fp18_inv_cyc(), fp18_neg(), pp_add_k54_projc(), and pp_mil_k54().
fp9_dbl()
void fp9_dbl (fp9_t c, fp9_t a)
Doubles a nonic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to double.
Definition at line 202 of file relic_fpx_add.c.
Referenced by ep9_dbl_basic(), fp18_dbl(), fp18_sqr_basic(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_sqr_cyc_basic(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), and pp_dbl_k54_projc().
fp9_mul_unr()
void fp9_mul_unr (dv9_t c, fp9_t a, fp9_t b)
Multiples two nonic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 112 of file relic_fp9_mul.c.
References CATCH_ANY, dv3_free, dv3_new, dv3_null, ERR_CAUGHT, FINALLY, fp3_addc_low(), fp3_addm_low(), fp3_free, fp3_muln_low(), fp3_new, fp3_nord_low(), fp3_null, fp3_subc_low(), THROW, and TRY.
Referenced by fp18_mul_unr(), and fp9_mul_lazyr().
fp9_mul_basic()
void fp9_mul_basic (fp9_t c, fp9_t a, fp9_t b)
Multiples two nonic extension field elements.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 41 of file relic_fp9_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp3_copy(), fp3_free, fp3_mul_nor(), fp3_new, fp3_null, THROW, and TRY.
fp9_mul_lazyr()
void fp9_mul_lazyr (fp9_t c, fp9_t a, fp9_t b)
Multiples two nonic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 185 of file relic_fp9_mul.c.
References CATCH_ANY, dv9_free, dv9_new, dv9_null, ERR_CAUGHT, FINALLY, fp3_rdcn_low(), fp9_mul_unr(), THROW, and TRY.
fp9_mul_art()
void fp9_mul_art (fp9_t c, fp9_t a)
Multiplies a nonic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to multiply.
Definition at line 262 of file relic_fp9_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp3_copy(), fp3_free, fp3_mul_nor(), fp3_new, fp3_null, THROW, and TRY.
Referenced by fp18_inv(), fp18_mul_art(), fp18_mul_basic(), fp18_mul_dxs(), fp18_sqr_basic(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_frb(), fp54_sqr_cyc_basic(), fp54_sqr_pck_basic(), and fp54_sqr_pck_lazyr().
fp9_mul_dxs()
void fp9_mul_dxs (fp9_t c, fp9_t a, fp9_t b)
Multiples a dense nonic extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - a nonic extension field element.
[in] b - a sparse nonic extension field element.
Definition at line 205 of file relic_fp9_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp3_copy(), fp3_free, fp3_mul_nor(), fp3_new, fp3_null, THROW, and TRY.
fp9_sqr_unr()
void fp9_sqr_unr (dv9_t c, fp9_t a)
Computes the square of a nonic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to square.
Definition at line 115 of file relic_fp9_sqr.c.
References CATCH_ANY, dv3_free, dv3_new, dv3_null, ERR_CAUGHT, FINALLY, fp3_addc_low(), fp3_addm_low(), fp3_dblm_low(), fp3_free, fp3_muln_low(), fp3_new, fp3_nord_low(), fp3_null, fp3_sqrn_low(), fp3_subc_low(), fp3_subm_low(), fp_hlvd_low(), THROW, and TRY.
Referenced by fp18_sqr_unr(), fp54_sqr_pck_lazyr(), and fp9_sqr_lazyr().
fp9_sqr_basic()
void fp9_sqr_basic (fp9_t c, fp9_t a)
Computes the squares of a nonic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to square.
Definition at line 42 of file relic_fp9_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp3_free, fp3_mul_nor(), fp3_new, fp3_null, THROW, and TRY.
fp9_sqr_lazyr()
void fp9_sqr_lazyr (fp9_t c, fp9_t a)
Computes the square of a nonic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to square.
Definition at line 204 of file relic_fp9_sqr.c.
References CATCH_ANY, dv9_free, dv9_new, dv9_null, ERR_CAUGHT, FINALLY, fp3_rdcn_low(), fp9_sqr_unr(), THROW, and TRY.
fp9_inv()
void fp9_inv (fp9_t c, fp9_t a)
Inverts a nonic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to invert.
Definition at line 431 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp3_free, fp3_inv(), fp3_mul_nor(), fp3_new, fp3_null, THROW, and TRY.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp54_back_cyc(), fp9_exp(), fp9_inv_sim(), and pp_mil_k54().
fp9_inv_sim()
void fp9_inv_sim (fp9_t * c, fp9_t * a, int n)
Inverts multiple noinc extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the nonic extension field elements to invert.
[in] n - the number of elements.
Definition at line 490 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_copy(), fp9_free, fp9_inv(), fp9_new, fp9_null, RLC_ALLOCA, THROW, and TRY.
Referenced by fp54_back_cyc_sim().
fp9_exp()
void fp9_exp (fp9_t c, fp9_t a, bn_t b)
Computes a power of a nonic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the nonic extension element to exponentiate.
[in] b - the exponent.
Definition at line 252 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_copy(), fp9_free, fp9_inv(), fp9_new, fp9_null, fp9_set_dig(), RLC_NEG, THROW, and TRY.
fp9_frb()
void fp9_frb (fp9_t c, fp9_t a, int i)
Computes a power of the Frobenius endomorphism of a nonic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a nonic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 100 of file relic_fpx_frb.c.
References fp3_frb(), fp3_mul_frb(), and fp9_copy().
Referenced by fp18_frb(), and pp_mil_k54().
fp12_copy()
void fp12_copy (fp12_t c, fp12_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the dodecic extension field element to copy.
Definition at line 402 of file relic_fpx_util.c.
References fp6_copy().
Referenced by fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sps(), fp12_exp_dig(), fp12_frb(), fp12_pck(), and fp12_upk().
fp12_zero()
void fp12_zero (fp12_t a)
Assigns zero to a dodecic extension field element.
Parameters
[out] A - the dodecic extension field element to zero.
Definition at line 407 of file relic_fpx_util.c.
References fp6_zero().
Referenced by pp_dbl_k12_basic(), pp_fin_k12_oatep(), pp_mil_k12(), and pp_mil_lit_k12().
fp12_is_zero()
int fp12_is_zero (fp12_t a)
Tests if a dodecic extension field element is zero or not.
Parameters
[in] A - the dodecic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 412 of file relic_fpx_util.c.
References fp6_is_zero().
fp12_rand()
void fp12_rand (fp12_t a)
Assigns a random value to a dodecic extension field element.
Parameters
[out] A - the dodecic extension field element to assign.
Definition at line 416 of file relic_fpx_util.c.
References fp6_rand().
fp12_print()
void fp12_print (fp12_t a)
Prints a dodecic extension field element to standard output.
Parameters
[in] A - the dodecic extension field element to print.
Definition at line 421 of file relic_fpx_util.c.
References fp6_print().
fp12_size_bin()
int fp12_size_bin (fp12_t a, int pack)
Returns the number of bytes necessary to store a dodecic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 426 of file relic_fpx_util.c.
References fp12_test_cyc(), and RLC_FP_BYTES.
fp12_read_bin()
void fp12_read_bin (fp12_t a, const uint8_t * bin, int len)
Reads a dodecic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 438 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp12_back_cyc(), fp2_read_bin(), fp2_zero(), fp6_read_bin(), RLC_FP_BYTES, and THROW.
fp12_write_bin()
void fp12_write_bin (uint8_t * bin, int len, fp12_t a, int pack)
Writes a dodecic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 457 of file relic_fpx_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, fp12_free, fp12_new, fp12_null, fp12_pck(), fp2_write_bin(), fp6_write_bin(), RLC_FP_BYTES, THROW, and TRY.
fp12_cmp()
int fp12_cmp (fp12_t a, fp12_t b)
Returns the result of a comparison between two dodecic extension field elements.
Parameters
[in] a - the first dodecic extension field element.
[in] b - the second dodecic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 99 of file relic_fpx_cmp.c.
References fp6_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp12_test_cyc().
fp12_cmp_dig()
int fp12_cmp_dig (fp12_t a, dig_t b)
Returns the result of a signed comparison between a dodecic extension field element and a digit.
Parameters
[in] a - the dodecic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 104 of file relic_fpx_cmp.c.
References fp6_cmp_dig(), fp6_is_zero(), RLC_EQ, and RLC_NE.
fp12_set_dig()
void fp12_set_dig (fp12_t a, dig_t b)
Assigns a dodecic extension field element to a digit.
Parameters
[in] a - the dodecic extension field element.
[in] b - the digit.
Definition at line 488 of file relic_fpx_util.c.
References fp6_set_dig(), and fp6_zero().
Referenced by fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sps(), fp12_exp_dig(), pp_map_oatep_k12(), pp_map_sim_oatep_k12(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), and pp_map_weilp_k12().
fp12_add()
void fp12_add (fp12_t c, fp12_t a, fp12_t b)
Adds two dodecic extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first dodecic extension field element.
[in] B - the second dodecic extension field element.
Definition at line 214 of file relic_fpx_add.c.
References fp6_add().
fp12_sub()
void fp12_sub (fp12_t c, fp12_t a, fp12_t b)
Subtracts a dodecic extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first dodecic extension field element.
[in] B - the second dodecic extension field element.
Definition at line 219 of file relic_fpx_add.c.
References fp6_sub().
fp12_neg()
void fp12_neg (fp12_t c, fp12_t a)
Negates a dodecic extension field element.
Parameters
[out] C - the result.
[out] A - the dodecic extension field element to negate.
Definition at line 224 of file relic_fpx_add.c.
References fp6_neg().
fp12_dbl()
void fp12_dbl (fp12_t c, fp12_t a)
Doubles a dodecic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to double.
Definition at line 229 of file relic_fpx_add.c.
References fp6_dbl().
fp12_mul_unr()
void fp12_mul_unr (dv12_t c, fp12_t a, fp12_t b)
Multiples two dodecic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
[in] b - the dodecic extension field element.
Definition at line 248 of file relic_fp12_mul.c.
References CATCH_ANY, dv6_free, dv6_new, dv6_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp6_add(), fp6_free, fp6_mul_unr(), fp6_new, fp6_null, THROW, and TRY.
Referenced by fp12_mul_lazyr().
fp12_mul_basic()
void fp12_mul_basic (fp12_t c, fp12_t a, fp12_t b)
Multiples two dodecic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
[in] b - the dodecic extension field element.
Definition at line 120 of file relic_fp12_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_add(), fp6_free, fp6_mul_art(), fp6_new, fp6_null, fp6_sub(), THROW, and TRY.
fp12_mul_lazyr()
void fp12_mul_lazyr (fp12_t c, fp12_t a, fp12_t b)
Multiples two dodecic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
[in] b - the dodecic extension field element.
Definition at line 301 of file relic_fp12_mul.c.
References CATCH_ANY, dv12_free, dv12_new, dv12_null, ERR_CAUGHT, FINALLY, fp12_mul_unr(), fp2_rdcn_low(), THROW, and TRY.
fp12_mul_art()
void fp12_mul_art (fp12_t c, fp12_t a)
Multiplies a dodecic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to multiply.
Definition at line 424 of file relic_fp12_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_copy(), fp6_free, fp6_mul_art(), fp6_new, fp6_null, THROW, and TRY.
fp12_mul_dxs_basic()
void fp12_mul_dxs_basic (fp12_t c, fp12_t a, fp12_t b)
Multiples a dense dodecic extension field element by a sparse element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dense dodecic extension field element.
[in] b - the sparse dodecic extension field element.
Definition at line 161 of file relic_fp12_mul.c.
References CATCH_ANY, ep2_curve_is_twist(), EP_DTYPE, ERR_CAUGHT, FINALLY, fp2_copy(), fp6_add(), fp6_free, fp6_mul_art(), fp6_mul_dxs(), fp6_new, fp6_null, fp6_sub(), fp_copy(), THROW, and TRY.
fp12_mul_dxs_lazyr()
void fp12_mul_dxs_lazyr (fp12_t c, fp12_t a, fp12_t b)
Multiples a dense dodecic extension field element by a sparse element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dense dodecic extension field element.
[in] b - the sparse dodecic extension field element.
Definition at line 320 of file relic_fp12_mul.c.
References CATCH_ANY, dv6_free, dv6_new, dv6_null, ep2_curve_is_twist(), EP_DTYPE, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_copy(), fp2_mulc_low(), fp2_muln_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp6_add(), fp6_free, fp6_mul_dxs_unr_lazyr(), fp6_new, fp6_null, fp_copy(), fp_muln_low(), THROW, and TRY.
fp12_sqr_unr()
void fp12_sqr_unr (dv12_t c, fp12_t a)
Computes the square of a dodecic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to square.
Definition at line 237 of file relic_fp12_sqr.c.
References CATCH_ANY, dv4_free, dv4_new, dv4_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_addd_low(), fp2_addm_low(), fp2_copy(), fp2_nord_low(), fp2_subc_low(), fp2_subm_low(), fp4_free, fp4_mul_unr(), fp4_new, fp4_null, fp4_sqr_unr(), fp_hlvd_low(), THROW, and TRY.
Referenced by fp12_sqr_lazyr().
fp12_sqr_basic()
void fp12_sqr_basic (fp12_t c, fp12_t a)
Computes the square of a dodecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to square.
Definition at line 42 of file relic_fp12_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_add(), fp6_dbl(), fp6_free, fp6_mul_art(), fp6_new, fp6_null, fp6_sub(), THROW, and TRY.
fp12_sqr_lazyr()
void fp12_sqr_lazyr (fp12_t c, fp12_t a)
Computes the square of a dodecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to square.
Definition at line 340 of file relic_fp12_sqr.c.
References CATCH_ANY, dv12_free, dv12_new, dv12_null, ERR_CAUGHT, FINALLY, fp12_sqr_unr(), fp2_rdcn_low(), THROW, and TRY.
fp12_sqr_cyc_basic()
void fp12_sqr_cyc_basic (fp12_t c, fp12_t a)
Computes the square of a cyclotomic dodecic extension field element using basic arithmetic.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 69 of file relic_fp12_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, THROW, and TRY.
fp12_sqr_cyc_lazyr()
void fp12_sqr_cyc_lazyr (fp12_t c, fp12_t a)
Computes the square of a cyclotomic dodecic extension field element using lazy reduction.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 359 of file relic_fp12_sqr.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_addm_low(), fp2_dblm_low(), fp2_free, fp2_new, fp2_norh_low(), fp2_norm_low(), fp2_null, fp2_rdcn_low(), fp2_sqrm_low(), fp2_sqrn_low(), fp2_subc_low(), fp2_subm_low(), THROW, and TRY.
fp12_sqr_pck_basic()
void fp12_sqr_pck_basic (fp12_t c, fp12_t a)
Computes the square of a compressed cyclotomic extension field element.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 163 of file relic_fp12_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, THROW, and TRY.
fp12_sqr_pck_lazyr()
void fp12_sqr_pck_lazyr (fp12_t c, fp12_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 455 of file relic_fp12_sqr.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_addm_low(), fp2_dblm_low(), fp2_free, fp2_new, fp2_norh_low(), fp2_norm_low(), fp2_null, fp2_rdcn_low(), fp2_sqrm_low(), fp2_sqrn_low(), fp2_subc_low(), fp2_subm_low(), THROW, and TRY.
fp12_test_cyc()
int fp12_test_cyc (fp12_t a)
Tests if a dodecic extension field element belongs to the cyclotomic subgroup.
Parameters
[in] a - the dodecic extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 292 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_back_cyc(), fp12_cmp(), fp12_free, fp12_new, fp12_null, result, RLC_EQ, THROW, and TRY.
Referenced by fp12_exp(), fp12_exp_dig(), fp12_pck(), fp12_size_bin(), and fp12_upk().
fp12_conv_cyc()
void fp12_conv_cyc (fp12_t c, fp12_t a)
Converts a dodecic extension field element to a cyclotomic element. Computes c = a^(p^6 - 1)*(p^2 + 1).
Parameters
[out] c - the result.
[in] a - a dodecic extension field element.
Definition at line 261 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_frb(), fp12_free, fp12_inv(), fp12_inv_cyc(), fp12_new, fp12_null, THROW, and TRY.
Referenced by pp_exp_b12(), and pp_exp_bn().
fp12_back_cyc()
void fp12_back_cyc (fp12_t c, fp12_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to decompress.
Definition at line 315 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_inv(), fp2_new, fp2_null, fp_add_dig(), THROW, and TRY.
Referenced by fp12_read_bin(), fp12_test_cyc(), and fp12_upk().
fp12_back_cyc_sim()
void fp12_back_cyc_sim (fp12_t * c, fp12_t * a, int n)
Decompresses multiple compressed cyclotomic extension field elements.
Parameters
[out] c - the result.
[in] a - the dodecic field elements to decompress.
[in] n - the number of field elements to decompress.
fp12_inv()
void fp12_inv (fp12_t c, fp12_t a)
Inverts a dodecic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to invert.
Definition at line 532 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_free, fp6_inv(), fp6_mul_art(), fp6_neg(), fp6_new, fp6_null, fp6_sub(), THROW, and TRY.
Referenced by fp12_conv_cyc(), fp12_exp(), pp_map_sim_weilp_k12(), and pp_map_weilp_k12().
fp12_inv_cyc()
void fp12_inv_cyc (fp12_t c, fp12_t a)
Computes the inverse of a cyclotomic dodecic extension field element. For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^6 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to invert.
Definition at line 560 of file relic_fpx_inv.c.
References fp6_copy(), and fp6_neg().
Referenced by fp12_conv_cyc(), fp12_exp_cyc(), fp12_exp_cyc_sps(), pp_exp_b12(), pp_exp_bn(), pp_map_oatep_k12(), pp_map_sim_oatep_k12(), pp_map_sim_weilp_k12(), and pp_map_weilp_k12().
fp12_frb()
void fp12_frb (fp12_t c, fp12_t a, int i)
Computes the Frobenius endomorphism of a dodecic extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a dodecic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 112 of file relic_fpx_frb.c.
References fp12_copy(), fp2_frb(), fp2_mul_frb(), and fp6_frb().
Referenced by fp12_conv_cyc(), fp12_exp_cyc(), gt_is_valid(), pp_exp_b12(), and pp_exp_bn().
fp12_exp()
void fp12_exp (fp12_t c, fp12_t a, bn_t b)
Computes a power of a dodecic extension field element. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 288 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_copy(), fp12_exp_cyc(), fp12_free, fp12_inv(), fp12_new, fp12_null, fp12_set_dig(), fp12_test_cyc(), RLC_NEG, THROW, and TRY.
fp12_exp_dig()
void fp12_exp_dig (fp12_t c, fp12_t a, dig_t b)
Computes a power of a dodecic extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 328 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_copy(), fp12_free, fp12_new, fp12_null, fp12_set_dig(), fp12_test_cyc(), THROW, TRY, and util_bits_dig().
fp12_exp_cyc()
void fp12_exp_cyc (fp12_t c, fp12_t a, bn_t b)
Computes a power of a cyclotomic dodecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 451 of file relic_fpx_cyc.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_dbl(), bn_div(), bn_free(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_mod, bn_neg(), bn_null, bn_sign(), bn_sub(), bn_sub_dig(), bn_zero(), CATCH_ANY, ep2_curve_get_ord(), ep2_curve_get_vs(), EP_B12, EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp12_back_cyc_sim(), fp12_copy(), fp12_frb(), fp12_free, fp12_inv_cyc(), fp12_new, fp12_null, fp12_set_dig(), fp_prime_get_par(), RLC_ALLOCA, RLC_DIG, RLC_FREE, RLC_MAX, RLC_NEG, RLC_POS, bn_st::sign, THROW, and TRY.
Referenced by fp12_exp().
fp12_exp_cyc_sps()
void fp12_exp_cyc_sps (fp12_t c, fp12_t a, const int * b, int l, int s)
Computes a power of a cyclotomic dodecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 691 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp12_back_cyc_sim(), fp12_copy(), fp12_free, fp12_inv_cyc(), fp12_new, fp12_null, fp12_set_dig(), RLC_ALLOCA, RLC_FREE, RLC_NEG, THROW, and TRY.
Referenced by pp_exp_b12(), and pp_exp_bn().
fp12_pck()
void fp12_pck (fp12_t c, fp12_t a)
Compresses a dodecic extension field element.
Parameters
[out] r - the result.
[in] p - the dodecic extension field element to compress.
Definition at line 87 of file relic_fpx_pck.c.
References fp12_copy(), fp12_test_cyc(), and fp2_zero().
Referenced by fp12_write_bin().
fp12_upk()
int fp12_upk (fp12_t c, fp12_t a)
Decompresses a dodecic extension field element.
Parameters
[out] r - the result.
[in] p - the dodecic extension field element to decompress.
Returns
if the decompression was successful
Definition at line 95 of file relic_fpx_pck.c.
References fp12_back_cyc(), fp12_copy(), fp12_test_cyc(), and fp2_is_zero().
fp18_copy()
void fp18_copy (fp18_t c, fp18_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the octdecic extension field element to copy.
Definition at line 493 of file relic_fpx_util.c.
References fp9_copy().
Referenced by fp18_exp(), fp18_frb(), fp54_copy(), fp54_mul_art(), fp54_mul_basic(), and fp54_mul_dxs().
fp18_zero()
void fp18_zero (fp18_t a)
Assigns zero to an octdecic extension field element.
Parameters
[out] A - the octdecic extension field element to zero.
Definition at line 498 of file relic_fpx_util.c.
References fp9_zero().
Referenced by fp54_set_dig(), and fp54_zero().
fp18_is_zero()
int fp18_is_zero (fp18_t a)
Tests if an octdecic extension field element is zero or not.
Parameters
[in] A - the octdecic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 503 of file relic_fpx_util.c.
References fp9_is_zero().
Referenced by fp54_cmp_dig(), and fp54_is_zero().
fp18_rand()
void fp18_rand (fp18_t a)
Assigns a random value to an octdecic extension field element.
Parameters
[out] A - the octdecic extension field element to assign.
Definition at line 507 of file relic_fpx_util.c.
References fp9_rand().
Referenced by fp54_rand().
fp18_print()
void fp18_print (fp18_t a)
Prints an octdecic extension field element to standard output.
Parameters
[in] A - the octdecic extension field element to print.
Definition at line 512 of file relic_fpx_util.c.
References fp9_print().
Referenced by fp54_print().
fp18_size_bin()
int fp18_size_bin (fp18_t a)
Returns the number of bytes necessary to store an octdecic extension field element.
Parameters
[in] a - the extension field element.
Returns
the number of bytes.
Definition at line 517 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp18_read_bin()
void fp18_read_bin (fp18_t a, const uint8_t * bin, int len)
Reads an octdecic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 521 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp9_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp54_read_bin().
fp18_write_bin()
void fp18_write_bin (uint8_t * bin, int len, fp18_t a)
Writes an octdecic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 529 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp9_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp54_write_bin().
fp18_cmp()
int fp18_cmp (fp18_t a, fp18_t b)
Returns the result of a comparison between two octdecic extension field elements.
Parameters
[in] a - the first octdecic extension field element.
[in] b - the second octdecic extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 109 of file relic_fpx_cmp.c.
References fp9_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp54_cmp().
fp18_cmp_dig()
int fp18_cmp_dig (fp18_t a, dig_t b)
Returns the result of a signed comparison between an octdecic extension field element and a digit.
Parameters
[in] a - the octdecic extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 114 of file relic_fpx_cmp.c.
References fp9_cmp_dig(), fp9_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp54_cmp_dig().
fp18_set_dig()
void fp18_set_dig (fp18_t a, dig_t b)
Assigns an octdecic extension field element to a digit.
Parameters
[in] a - the octdecic extension field element.
[in] b - the digit.
Definition at line 537 of file relic_fpx_util.c.
References fp9_set_dig(), and fp9_zero().
Referenced by fp18_exp(), and fp54_set_dig().
fp18_add()
void fp18_add (fp18_t c, fp18_t a, fp18_t b)
Adds two octdecic extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first octdecic extension field element.
[in] B - the second octdecic extension field element.
Definition at line 234 of file relic_fpx_add.c.
References fp9_add().
Referenced by fp54_add(), fp54_inv(), fp54_mul_basic(), fp54_mul_dxs(), and fp54_sqr_basic().
fp18_sub()
void fp18_sub (fp18_t c, fp18_t a, fp18_t b)
Subtracts an octdecic extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first octdecic extension field element.
[in] B - the second octdecic extension field element.
Definition at line 239 of file relic_fpx_add.c.
References fp9_sub().
Referenced by fp54_inv(), fp54_mul_basic(), fp54_mul_dxs(), fp54_sqr_basic(), and fp54_sub().
fp18_neg()
void fp18_neg (fp18_t c, fp18_t a)
Negates an octdecic extension field element.
Parameters
[out] C - the result.
[out] A - the octdecic extension field element to negate.
Definition at line 249 of file relic_fpx_add.c.
References fp9_neg().
Referenced by fp54_inv_cyc(), and fp54_neg().
fp18_dbl()
void fp18_dbl (fp18_t c, fp18_t a)
Doubles an octdecic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to double.
Definition at line 244 of file relic_fpx_add.c.
References fp9_dbl().
Referenced by fp54_dbl(), and fp54_sqr_basic().
fp18_mul_unr()
void fp18_mul_unr (dv18_t c, fp18_t a, fp18_t b)
Multiples two octdecic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element.
[in] b - the octdecic extension field element.
Definition at line 87 of file relic_fp18_mul.c.
References CATCH_ANY, dv9_free, dv9_new, dv9_null, ERR_CAUGHT, FINALLY, fp3_addc_low(), fp3_nord_low(), fp3_subc_low(), fp9_add(), fp9_free, fp9_mul_unr(), fp9_new, fp9_null, THROW, and TRY.
Referenced by fp18_mul_lazyr().
fp18_mul_basic()
void fp18_mul_basic (fp18_t c, fp18_t a, fp18_t b)
Multiples two octdecic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element.
[in] b - the octdecic extension field element.
Definition at line 42 of file relic_fp18_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_add(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sub(), THROW, and TRY.
fp18_mul_lazyr()
void fp18_mul_lazyr (fp18_t c, fp18_t a, fp18_t b)
Multiples two octdecic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element.
[in] b - the octdecic extension field element.
Definition at line 140 of file relic_fp18_mul.c.
References CATCH_ANY, dv18_free, dv18_new, dv18_null, ERR_CAUGHT, FINALLY, fp18_mul_unr(), fp3_rdcn_low(), THROW, and TRY.
fp18_mul_art()
void fp18_mul_art (fp18_t c, fp18_t a)
Multiplies an octdecic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to multiply.
Definition at line 208 of file relic_fp18_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_copy(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, THROW, and TRY.
Referenced by fp54_inv(), fp54_mul_art(), fp54_mul_basic(), fp54_mul_dxs(), and fp54_sqr_basic().
fp18_mul_dxs_basic()
void fp18_mul_dxs_basic (fp18_t c, fp18_t a, fp18_t b)
Multiples a dense octdecic extension field element by a sparse element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dense octdecic extension field element.
[in] b - the sparse octdecic extension field element.
fp18_mul_dxs_lazyr()
void fp18_mul_dxs_lazyr (fp18_t c, fp18_t a, fp18_t b)
Multiples a dense octdecic extension field element by a sparse element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dense octdecic extension field element.
[in] b - the sparse octdecic extension field element.
fp18_sqr_unr()
void fp18_sqr_unr (dv18_t c, fp18_t a)
Computes the square of an octdecic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to square.
Definition at line 73 of file relic_fp18_sqr.c.
References CATCH_ANY, dv9_free, dv9_new, dv9_null, dv_copy(), ERR_CAUGHT, FINALLY, fp3_addc_low(), fp3_nord_low(), fp3_subc_low(), fp9_add(), fp9_free, fp9_new, fp9_null, fp9_sqr_unr(), RLC_FP_DIGS, THROW, and TRY.
Referenced by fp18_sqr_lazyr().
fp18_sqr_basic()
void fp18_sqr_basic (fp18_t c, fp18_t a)
Computes the square of an octdecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to square.
Definition at line 42 of file relic_fp18_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_add(), fp9_dbl(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sub(), THROW, and TRY.
fp18_sqr_lazyr()
void fp18_sqr_lazyr (fp18_t c, fp18_t a)
Computes the square of an octdecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to square.
Definition at line 126 of file relic_fp18_sqr.c.
References CATCH_ANY, dv18_free, dv18_new, dv18_null, ERR_CAUGHT, FINALLY, fp18_sqr_unr(), fp3_rdcn_low(), THROW, and TRY.
fp18_inv()
void fp18_inv (fp18_t c, fp18_t a)
Inverts an octdecic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to invert.
Definition at line 565 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_free, fp9_inv(), fp9_mul_art(), fp9_neg(), fp9_new, fp9_null, fp9_sub(), THROW, and TRY.
Referenced by fp18_exp(), and fp54_inv().
fp18_inv_cyc()
void fp18_inv_cyc (fp18_t c, fp18_t a)
Computes the inverse of a cyclotomic octdecic extension field element. For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^9 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to invert.
Definition at line 593 of file relic_fpx_inv.c.
References fp9_copy(), and fp9_neg().
Referenced by fp54_inv_cyc().
fp18_conv_cyc()
void fp18_conv_cyc (fp18_t c, fp18_t a)
Converts an octdecic extension field element to a cyclotomic element. Computes c = a^(p^9 - 1).
Parameters
[out] c - the result.
[in] a - an octdecic extension field element.
fp18_frb()
void fp18_frb (fp18_t c, fp18_t a, int i)
Computes the Frobenius endomorphism of an octdecic extension element. Computes c = a^(p^i).
Parameters
[out] c - the result.
[in] a - an octdecic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 126 of file relic_fpx_frb.c.
References fp18_copy(), fp3_frb(), fp3_mul_frb(), and fp9_frb().
Referenced by fp54_frb().
fp18_exp()
void fp18_exp (fp18_t c, fp18_t a, bn_t b)
Computes a power of an octdecic extension field element. Faster formulas are used if the field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 369 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_copy(), fp18_free, fp18_inv(), fp18_new, fp18_null, fp18_set_dig(), RLC_NEG, THROW, and TRY.
fp24_copy()
void fp24_copy (fp24_t c, fp24_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the 24-degree extension field element to copy.
Definition at line 542 of file relic_fpx_util.c.
References fp8_copy().
Referenced by fp24_exp(), fp24_frb(), fp48_copy(), fp48_inv_cyc(), and fp48_mul_art().
fp24_zero()
void fp24_zero (fp24_t a)
Assigns zero to a 24-degree extension field element.
Parameters
[out] A - the 24-degree extension field element to zero.
Definition at line 548 of file relic_fpx_util.c.
References fp8_zero().
Referenced by fp48_set_dig(), and fp48_zero().
fp24_is_zero()
int fp24_is_zero (fp24_t a)
Tests if a 24-degree extension field element is zero or not.
Parameters
[in] A - the 24-degree extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 554 of file relic_fpx_util.c.
References fp8_is_zero().
Referenced by fp48_cmp_dig(), and fp48_is_zero().
fp24_rand()
void fp24_rand (fp24_t a)
Assigns a random value to a 24-degree extension field element.
Parameters
[out] A - the 24-degree extension field element to assign.
Definition at line 558 of file relic_fpx_util.c.
References fp8_rand().
Referenced by fp48_rand().
fp24_print()
void fp24_print (fp24_t a)
Prints a 24-degree extension field element to standard output.
Parameters
[in] A - the 24-degree extension field element to print.
Definition at line 564 of file relic_fpx_util.c.
References fp8_print().
Referenced by fp48_print().
fp24_size_bin()
int fp24_size_bin (fp24_t a)
Returns the number of bytes necessary to store a 24-degree extension field element.
Parameters
[in] a - the extension field element.
Returns
the number of bytes.
Definition at line 570 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp24_read_bin()
void fp24_read_bin (fp24_t a, const uint8_t * bin, int len)
Reads a 24-degree extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 574 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp8_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp48_read_bin().
fp24_write_bin()
void fp24_write_bin (uint8_t * bin, int len, fp24_t a)
Writes a 24-degree extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 583 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp8_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp48_write_bin().
fp24_cmp()
int fp24_cmp (fp24_t a, fp24_t b)
Returns the result of a comparison between two 24-degree extension field elements.
Parameters
[in] a - the first 24-degree extension field element.
[in] b - the second 24-degree extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 119 of file relic_fpx_cmp.c.
References fp8_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp48_cmp().
fp24_cmp_dig()
int fp24_cmp_dig (fp24_t a, dig_t b)
Returns the result of a signed comparison between a 24-degree extension field element and a digit.
Parameters
[in] a - the 24-degree extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 124 of file relic_fpx_cmp.c.
References fp8_cmp_dig(), fp8_is_zero(), RLC_EQ, and RLC_NE.
Referenced by fp48_cmp_dig().
fp24_set_dig()
void fp24_set_dig (fp24_t a, dig_t b)
Assigns a 24-degree extension field element to a digit.
Parameters
[in] a - the 24-degree extension field element.
[in] b - the digit.
Definition at line 592 of file relic_fpx_util.c.
References fp8_set_dig(), and fp8_zero().
Referenced by fp24_exp(), and fp48_set_dig().
fp24_add()
void fp24_add (fp24_t c, fp24_t a, fp24_t b)
Adds two 24-degree extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first 24-degree extension field element.
[in] B - the second 24-degree extension field element.
Definition at line 254 of file relic_fpx_add.c.
References fp8_add().
Referenced by fp48_add(), fp48_mul_basic(), fp48_mul_dxs(), and fp48_sqr_basic().
fp24_sub()
void fp24_sub (fp24_t c, fp24_t a, fp24_t b)
Subtracts a 24-degree extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first 24-degree extension field element.
[in] B - the second 24-degree extension field element.
Definition at line 260 of file relic_fpx_add.c.
References fp8_sub().
Referenced by fp48_inv(), fp48_mul_basic(), fp48_mul_dxs(), fp48_sqr_basic(), and fp48_sub().
fp24_neg()
void fp24_neg (fp24_t c, fp24_t a)
Negates a 24-degree extension field element.
Parameters
[out] C - the result.
[out] A - the 24-degree extension field element to negate.
Definition at line 266 of file relic_fpx_add.c.
References fp8_neg().
Referenced by fp48_inv(), fp48_inv_cyc(), and fp48_neg().
fp24_dbl()
void fp24_dbl (fp24_t c, fp24_t a)
Doubles a 24-degree extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the octic extension field element to double.
Definition at line 272 of file relic_fpx_add.c.
References fp8_dbl().
Referenced by fp48_dbl(), and fp48_sqr_basic().
fp24_mul_unr()
void fp24_mul_unr (dv24_t c, fp24_t a, fp24_t b)
Multiples two 24-degree extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element.
[in] b - the 24-degree extension field element.
Definition at line 109 of file relic_fp24_mul.c.
References CATCH_ANY, dv8_free, dv8_new, dv8_null, dv_copy(), ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp8_add(), fp8_free, fp8_mul_unr(), fp8_new, fp8_null, RLC_FP_DIGS, THROW, and TRY.
Referenced by fp24_mul_lazyr().
fp24_mul_basic()
void fp24_mul_basic (fp24_t c, fp24_t a, fp24_t b)
Multiples two 24-degree extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element.
[in] b - the 24-degree extension field element.
Definition at line 42 of file relic_fp24_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_copy(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), THROW, and TRY.
fp24_mul_lazyr()
void fp24_mul_lazyr (fp24_t c, fp24_t a, fp24_t b)
Multiples two 24-degree extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element.
[in] b - the 24-degree extension field element.
Definition at line 197 of file relic_fp24_mul.c.
References CATCH_ANY, dv24_free, dv24_new, dv24_null, ERR_CAUGHT, FINALLY, fp24_mul_unr(), fp2_rdcn_low(), THROW, and TRY.
fp24_mul_art()
void fp24_mul_art (fp24_t c, fp24_t a)
Multiplies a 24-degree extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to multiply.
Definition at line 220 of file relic_fp24_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_copy(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, THROW, and TRY.
Referenced by fp48_inv(), fp48_mul_art(), fp48_mul_basic(), fp48_mul_dxs(), and fp48_sqr_basic().
fp24_mul_dxs()
void fp24_mul_dxs (fp24_t c, fp24_t a, fp24_t b)
Multiples a dense 24-degree extension field element by a sparse element.
Parameters
[out] c - the result.
[in] a - a 24-degree extension field element.
[in] b - a 24-degree quartic extension field element.
Definition at line 240 of file relic_fp24_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_copy(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), THROW, and TRY.
Referenced by fp48_mul_dxs().
fp24_sqr_unr()
void fp24_sqr_unr (dv24_t c, fp24_t a)
Computes the square of a 24-degree extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to square.
Definition at line 119 of file relic_fp24_sqr.c.
References CATCH_ANY, dv8_free, dv8_new, dv8_null, dv_copy(), ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp8_add(), fp8_free, fp8_mul_unr(), fp8_new, fp8_null, fp8_sqr_unr(), fp8_sub(), fp_hlvd_low(), RLC_FP_DIGS, THROW, and TRY.
Referenced by fp24_sqr_lazyr().
fp24_sqr_basic()
void fp24_sqr_basic (fp24_t c, fp24_t a)
Computes the square of a 24-degree extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to square.
Definition at line 42 of file relic_fp24_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), THROW, and TRY.
fp24_sqr_lazyr()
void fp24_sqr_lazyr (fp24_t c, fp24_t a)
Computes the square of a 24-degree extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to square.
Definition at line 221 of file relic_fp24_sqr.c.
References CATCH_ANY, dv24_free, dv24_new, dv24_null, ERR_CAUGHT, FINALLY, fp24_sqr_unr(), fp2_rdcn_low(), THROW, and TRY.
fp24_inv()
void fp24_inv (fp24_t c, fp24_t a)
Inverts a 24-degree extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to invert.
Definition at line 598 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_free, fp8_inv(), fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), THROW, and TRY.
Referenced by fp24_exp(), and fp48_inv().
fp24_frb()
void fp24_frb (fp24_t c, fp24_t a, int i)
Computes the Frobenius endomorphism of a 24-degree extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a 24-degree extension field element.
[in] i - the power of the Frobenius map.
Definition at line 140 of file relic_fpx_frb.c.
References fp24_copy(), fp2_mul_frb(), fp4_mul_art(), fp8_frb(), and fp_prime_get_mod8().
Referenced by fp48_frb().
fp24_exp()
void fp24_exp (fp24_t c, fp24_t a, bn_t b)
Computes a power of a 24-degree extension field element. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 405 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp24_copy(), fp24_free, fp24_inv(), fp24_new, fp24_null, fp24_set_dig(), RLC_NEG, THROW, and TRY.
fp48_copy()
void fp48_copy (fp48_t c, fp48_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the 48-extension field element to copy.
Definition at line 598 of file relic_fpx_util.c.
References fp24_copy().
Referenced by fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sps(), fp48_exp_dig(), fp48_frb(), fp48_pck(), and fp48_upk().
fp48_zero()
void fp48_zero (fp48_t a)
Assigns zero to a 48-extension field element.
Parameters
[out] A - the 48-extension field element to zero.
Definition at line 603 of file relic_fpx_util.c.
References fp24_zero().
Referenced by pp_add_k48_basic(), pp_dbl_k48_basic(), and pp_mil_k48().
fp48_is_zero()
int fp48_is_zero (fp48_t a)
Tests if a 48-extension field element is zero or not.
Parameters
[in] A - the 48-extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 608 of file relic_fpx_util.c.
References fp24_is_zero().
fp48_rand()
void fp48_rand (fp48_t a)
Assigns a random value to a 48-extension field element.
Parameters
[out] A - the 48-extension field element to assign.
Definition at line 612 of file relic_fpx_util.c.
References fp24_rand().
fp48_print()
void fp48_print (fp48_t a)
Prints a 48-extension field element to standard output.
Parameters
[in] A - the 48-extension field element to print.
Definition at line 617 of file relic_fpx_util.c.
References fp24_print().
fp48_size_bin()
int fp48_size_bin (fp48_t a, int pack)
Returns the number of bytes necessary to store a 48-extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 622 of file relic_fpx_util.c.
References fp48_test_cyc(), and RLC_FP_BYTES.
fp48_read_bin()
void fp48_read_bin (fp48_t a, const uint8_t * bin, int len)
Reads a 48-extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 634 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp24_read_bin(), fp48_back_cyc(), fp8_read_bin(), fp8_zero(), RLC_FP_BYTES, and THROW.
fp48_write_bin()
void fp48_write_bin (uint8_t * bin, int len, fp48_t a, int pack)
Writes a 48-extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 653 of file relic_fpx_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, fp24_write_bin(), fp48_free, fp48_new, fp48_null, fp48_pck(), fp8_write_bin(), RLC_FP_BYTES, THROW, and TRY.
fp48_cmp()
int fp48_cmp (fp48_t a, fp48_t b)
Returns the result of a comparison between two 48-extension field elements.
Parameters
[in] a - the first 48-extension field element.
[in] b - the second 48-extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 129 of file relic_fpx_cmp.c.
References fp24_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp48_test_cyc().
fp48_cmp_dig()
int fp48_cmp_dig (fp48_t a, dig_t b)
Returns the result of a signed comparison between a 48-extension field element and a digit.
Parameters
[in] a - the 48-extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 134 of file relic_fpx_cmp.c.
References fp24_cmp_dig(), fp24_is_zero(), RLC_EQ, and RLC_NE.
fp48_set_dig()
void fp48_set_dig (fp48_t a, dig_t b)
Assigns a 48-extension field element to a digit.
Parameters
[in] a - the 48-extension field element.
[in] b - the digit.
Definition at line 684 of file relic_fpx_util.c.
References fp24_set_dig(), and fp24_zero().
Referenced by fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sps(), fp48_exp_dig(), and pp_map_k48().
fp48_add()
void fp48_add (fp48_t c, fp48_t a, fp48_t b)
Adds two 48-extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first 48-extension field element.
[in] B - the second 48-extension field element.
Definition at line 278 of file relic_fpx_add.c.
References fp24_add().
fp48_sub()
void fp48_sub (fp48_t c, fp48_t a, fp48_t b)
Subtracts a 48-extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first 48-extension field element.
[in] B - the second 48-extension field element.
Definition at line 283 of file relic_fpx_add.c.
References fp24_sub().
fp48_neg()
void fp48_neg (fp48_t c, fp48_t a)
Negates a 48-extension field element.
Parameters
[out] C - the result.
[out] A - the 48-extension field element to negate.
Definition at line 288 of file relic_fpx_add.c.
References fp24_neg().
fp48_dbl()
void fp48_dbl (fp48_t c, fp48_t a)
Doubles a 48-extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to double.
Definition at line 293 of file relic_fpx_add.c.
References fp24_dbl().
fp48_mul_unr()
void fp48_mul_unr (dv48_t c, fp48_t a, fp48_t b)
Multiples two 48-extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the 48-extension field element.
[in] b - the 48-extension field element.
fp48_mul_basic()
void fp48_mul_basic (fp48_t c, fp48_t a, fp48_t b)
Multiples two 48-extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 48-extension field element.
[in] b - the 48-extension field element.
Definition at line 42 of file relic_fp48_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp24_add(), fp24_free, fp24_mul_art(), fp24_new, fp24_null, fp24_sub(), THROW, and TRY.
Referenced by fp48_mul_lazyr().
fp48_mul_lazyr()
void fp48_mul_lazyr (fp48_t c, fp48_t a, fp48_t b)
Multiples two 48-extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 48-extension field element.
[in] b - the 48-extension field element.
Definition at line 87 of file relic_fp48_mul.c.
References fp48_mul_basic().
fp48_mul_art()
void fp48_mul_art (fp48_t c, fp48_t a)
Multiplies a 48-extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to multiply.
Definition at line 157 of file relic_fp48_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp24_copy(), fp24_free, fp24_mul_art(), fp24_new, fp24_null, THROW, and TRY.
fp48_mul_dxs()
void fp48_mul_dxs (fp48_t c, fp48_t a, fp48_t b)
Multiples a dense 48-extension field element by a sparse element using basic arithmetic. Computes C = A * B.
Parameters
[out] c - the result.
[in] a - the dense 48-extension field element.
[in] b - the sparse 48-extension field element.
Definition at line 94 of file relic_fp48_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp24_add(), fp24_free, fp24_mul_art(), fp24_mul_dxs(), fp24_new, fp24_null, fp24_sub(), fp8_add(), fp8_copy(), THROW, and TRY.
Referenced by pp_mil_k48().
fp48_sqr_unr()
void fp48_sqr_unr (dv48_t c, fp48_t a)
Computes the square of a 48-extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to square.
fp48_sqr_basic()
void fp48_sqr_basic (fp48_t c, fp48_t a)
Computes the square of a 48-extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to square.
Definition at line 42 of file relic_fp48_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp24_add(), fp24_dbl(), fp24_free, fp24_mul_art(), fp24_new, fp24_null, fp24_sub(), THROW, and TRY.
Referenced by fp48_sqr_lazyr().
fp48_sqr_lazyr()
void fp48_sqr_lazyr (fp48_t c, fp48_t a)
Computes the square of a 48-extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to square.
Definition at line 232 of file relic_fp48_sqr.c.
References fp48_sqr_basic().
fp48_sqr_cyc_basic()
void fp48_sqr_cyc_basic (fp48_t c, fp48_t a)
Computes the square of a cyclotomic 48-extension field element using basic arithmetic.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 69 of file relic_fp48_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), THROW, and TRY.
fp48_sqr_cyc_lazyr()
void fp48_sqr_cyc_lazyr (fp48_t c, fp48_t a)
Computes the square of a cyclotomic 48-extension field element using lazy reduction.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 237 of file relic_fp48_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), THROW, and TRY.
fp48_sqr_pck_basic()
void fp48_sqr_pck_basic (fp48_t c, fp48_t a)
Computes the square of a compressed cyclotomic extension field element.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 158 of file relic_fp48_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), THROW, and TRY.
fp48_sqr_pck_lazyr()
void fp48_sqr_pck_lazyr (fp48_t c, fp48_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 326 of file relic_fp48_sqr.c.
References CATCH_ANY, dv8_free, dv8_new, dv8_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr_unr(), fp8_sub(), THROW, and TRY.
fp48_test_cyc()
int fp48_test_cyc (fp48_t a)
Tests if a 48-extension field element belongs to the cyclotomic subgroup.
Parameters
[in] a - the 48-extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 800 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp48_back_cyc(), fp48_cmp(), fp48_free, fp48_new, fp48_null, result, RLC_EQ, THROW, and TRY.
Referenced by fp48_exp(), fp48_exp_dig(), fp48_pck(), fp48_size_bin(), and fp48_upk().
fp48_conv_cyc()
void fp48_conv_cyc (fp48_t c, fp48_t a)
Converts a 48-extension field element to a cyclotomic element. Computes c = a^(p^6 - 1)*(p^2 + 1).
Parameters
[out] c - the result.
[in] a - a 48-extension field element.
Converts a 48-extension field element to a cyclotomic element. Computes c = a^(p^6 - 1).
Parameters
[out] c - the result.
[in] a - the 48-extension field element.
Definition at line 769 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp48_frb(), fp48_free, fp48_inv(), fp48_inv_cyc(), fp48_new, fp48_null, THROW, and TRY.
Referenced by pp_exp_k48().
fp48_back_cyc()
void fp48_back_cyc (fp48_t c, fp48_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to decompress.
Definition at line 822 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_copy(), fp8_dbl(), fp8_free, fp8_inv(), fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), fp_add_dig(), THROW, and TRY.
Referenced by fp48_read_bin(), fp48_test_cyc(), and fp48_upk().
fp48_back_cyc_sim()
void fp48_back_cyc_sim (fp48_t * c, fp48_t * a, int n)
Decompresses multiple compressed cyclotomic extension field elements.
Parameters
[out] c - the result.
[in] a - the 48 field elements to decompress.
[in] n - the number of field elements to decompress.
fp48_inv()
void fp48_inv (fp48_t c, fp48_t a)
Inverts a 48-extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to invert.
Definition at line 657 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp24_free, fp24_inv(), fp24_mul_art(), fp24_neg(), fp24_new, fp24_null, fp24_sub(), THROW, and TRY.
Referenced by fp48_conv_cyc(), and fp48_exp().
fp48_inv_cyc()
void fp48_inv_cyc (fp48_t c, fp48_t a)
Computes the inverse of a cyclotomic 48-extension field element.
For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^24 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to invert.
Definition at line 685 of file relic_fpx_inv.c.
References fp24_copy(), and fp24_neg().
Referenced by fp48_conv_cyc(), fp48_exp_cyc(), fp48_exp_cyc_sps(), pp_exp_k48(), and pp_map_k48().
fp48_frb()
void fp48_frb (fp48_t c, fp48_t a, int i)
Computes the Frobenius endomorphism of a 48-extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a 48-extension field element.
[in] i - the power of the Frobenius map.
Definition at line 159 of file relic_fpx_frb.c.
References fp24_frb(), fp2_mul_frb(), fp48_copy(), fp4_mul_art(), fp8_mul_art(), and fp_prime_get_mod8().
Referenced by fp48_conv_cyc(), and pp_exp_k48().
fp48_exp()
void fp48_exp (fp48_t c, fp48_t a, bn_t b)
Computes a power of a 48-extension field element. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 441 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp48_copy(), fp48_exp_cyc(), fp48_free, fp48_inv(), fp48_new, fp48_null, fp48_set_dig(), fp48_test_cyc(), RLC_NEG, THROW, and TRY.
fp48_exp_dig()
void fp48_exp_dig (fp48_t c, fp48_t a, dig_t b)
Computes a power of a 48-extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 481 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp48_copy(), fp48_free, fp48_new, fp48_null, fp48_set_dig(), fp48_test_cyc(), THROW, TRY, and util_bits_dig().
fp48_exp_cyc()
void fp48_exp_cyc (fp48_t c, fp48_t a, bn_t b)
Computes a power of a cyclotomic 48-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 958 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp48_back_cyc_sim(), fp48_copy(), fp48_free, fp48_inv_cyc(), fp48_new, fp48_null, fp48_set_dig(), RLC_ALLOCA, RLC_DIG, RLC_FREE, RLC_NEG, THROW, and TRY.
Referenced by fp48_exp().
fp48_exp_cyc_sps()
void fp48_exp_cyc_sps (fp48_t c, fp48_t a, const int * b, int l, int s)
Computes a power of a cyclotomic 48-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 1051 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp48_back_cyc_sim(), fp48_copy(), fp48_free, fp48_inv_cyc(), fp48_new, fp48_null, fp48_set_dig(), RLC_ALLOCA, RLC_FREE, RLC_NEG, THROW, and TRY.
Referenced by pp_exp_k48().
fp48_pck()
void fp48_pck (fp48_t c, fp48_t a)
Compresses a 48-extension field element.
Parameters
[out] r - the result.
[in] p - the 48-extension field element to compress.
Definition at line 109 of file relic_fpx_pck.c.
References fp48_copy(), fp48_test_cyc(), and fp8_zero().
Referenced by fp48_write_bin().
fp48_upk()
int fp48_upk (fp48_t c, fp48_t a)
Decompresses a 48-extension field element.
Parameters
[out] r - the result.
[in] p - the 48-extension field element to decompress.
Returns
if the decompression was successful
Definition at line 117 of file relic_fpx_pck.c.
References fp48_back_cyc(), fp48_copy(), fp48_test_cyc(), and fp8_is_zero().
fp54_copy()
void fp54_copy (fp54_t c, fp54_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the 54-extension field element to copy.
Definition at line 689 of file relic_fpx_util.c.
References fp18_copy().
Referenced by fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), fp54_frb(), fp54_pck(), fp54_upk(), and pp_exp_k54().
fp54_zero()
void fp54_zero (fp54_t a)
Assigns zero to a 54-extension field element.
Parameters
[out] A - the 54-extension field element to zero.
Definition at line 695 of file relic_fpx_util.c.
References fp18_zero().
Referenced by pp_add_k54_basic(), pp_dbl_k54_basic(), and pp_mil_k54().
fp54_is_zero()
int fp54_is_zero (fp54_t a)
Tests if a 54-extension field element is zero or not.
Parameters
[in] A - the 54-extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 701 of file relic_fpx_util.c.
References fp18_is_zero().
fp54_rand()
void fp54_rand (fp54_t a)
Assigns a random value to a 54-extension field element.
Parameters
[out] A - the 54-extension field element to assign.
Definition at line 705 of file relic_fpx_util.c.
References fp18_rand().
fp54_print()
void fp54_print (fp54_t a)
Prints a 54-extension field element to standard output.
Parameters
[in] A - the 54-extension field element to print.
Definition at line 711 of file relic_fpx_util.c.
References fp18_print().
fp54_size_bin()
int fp54_size_bin (fp54_t a, int pack)
Returns the number of bytes necessary to store a 54-extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 717 of file relic_fpx_util.c.
References fp54_test_cyc(), and RLC_FP_BYTES.
fp54_read_bin()
void fp54_read_bin (fp54_t a, const uint8_t * bin, int len)
Reads a 54-extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 729 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp18_read_bin(), fp54_back_cyc(), fp9_read_bin(), fp9_zero(), RLC_FP_BYTES, and THROW.
fp54_write_bin()
void fp54_write_bin (uint8_t * bin, int len, fp54_t a, int pack)
Writes a 54-extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 749 of file relic_fpx_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, fp18_write_bin(), fp54_free, fp54_new, fp54_null, fp54_pck(), fp9_write_bin(), RLC_FP_BYTES, THROW, and TRY.
fp54_cmp()
int fp54_cmp (fp54_t a, fp54_t b)
Returns the result of a comparison between two 54-extension field elements.
Parameters
[in] a - the first 54-extension field element.
[in] b - the second 54-extension field element.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 139 of file relic_fpx_cmp.c.
References fp18_cmp(), RLC_EQ, and RLC_NE.
Referenced by fp54_test_cyc().
fp54_cmp_dig()
int fp54_cmp_dig (fp54_t a, dig_t b)
Returns the result of a signed comparison between a 54-extension field element and a digit.
Parameters
[in] a - the 54-extension field element.
[in] b - the digit.
Returns
RLC_EQ if a == b, and RLC_NE otherwise.
Definition at line 144 of file relic_fpx_cmp.c.
References fp18_cmp_dig(), fp18_is_zero(), RLC_EQ, and RLC_NE.
fp54_set_dig()
void fp54_set_dig (fp54_t a, dig_t b)
Assigns a 54-extension field element to a digit.
Parameters
[in] a - the 54-extension field element.
[in] b - the digit.
Definition at line 781 of file relic_fpx_util.c.
References fp18_set_dig(), and fp18_zero().
Referenced by fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), and pp_map_k54().
fp54_add()
void fp54_add (fp54_t c, fp54_t a, fp54_t b)
Adds two 54-extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first 54-extension field element.
[in] B - the second 54-extension field element.
Definition at line 298 of file relic_fpx_add.c.
References fp18_add().
fp54_sub()
void fp54_sub (fp54_t c, fp54_t a, fp54_t b)
Subtracts a 54-extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first 54-extension field element.
[in] B - the second 54-extension field element.
Definition at line 304 of file relic_fpx_add.c.
References fp18_sub().
fp54_neg()
void fp54_neg (fp54_t c, fp54_t a)
Negates a 54-extension field element.
Parameters
[out] C - the result.
[out] A - the 54-extension field element to negate.
Definition at line 310 of file relic_fpx_add.c.
References fp18_neg().
fp54_dbl()
void fp54_dbl (fp54_t c, fp54_t a)
Doubles a 54-extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to double.
Definition at line 316 of file relic_fpx_add.c.
References fp18_dbl().
fp54_mul_unr()
void fp54_mul_unr (dv54_t c, fp54_t a, fp54_t b)
Multiples two 54-extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the 54-extension field element.
[in] b - the 54-extension field element.
fp54_mul_basic()
void fp54_mul_basic (fp54_t c, fp54_t a, fp54_t b)
Multiples two 54-extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 54-extension field element.
[in] b - the 54-extension field element.
Definition at line 42 of file relic_fp54_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_add(), fp18_copy(), fp18_free, fp18_mul_art(), fp18_new, fp18_null, fp18_sub(), THROW, and TRY.
Referenced by fp54_mul_lazyr().
fp54_mul_lazyr()
void fp54_mul_lazyr (fp54_t c, fp54_t a, fp54_t b)
Multiples two 54-extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 54-extension field element.
[in] b - the 54-extension field element.
Definition at line 109 of file relic_fp54_mul.c.
References fp54_mul_basic().
fp54_mul_art()
void fp54_mul_art (fp54_t c, fp54_t a)
Multiplies a 54-extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to multiply.
Definition at line 184 of file relic_fp54_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_copy(), fp18_free, fp18_mul_art(), fp18_new, fp18_null, THROW, and TRY.
fp54_mul_dxs()
void fp54_mul_dxs (fp54_t c, fp54_t a, fp54_t b)
Multiples a dense 54-extension field element by a sparse element using basic arithmetic. Computes C = A * B.
Parameters
[out] c - the result.
[in] a - the dense 54-extension field element.
[in] b - the sparse 54-extension field element.
Definition at line 116 of file relic_fp54_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_add(), fp18_copy(), fp18_free, fp18_mul_art(), fp18_mul_dxs(), fp18_new, fp18_null, fp18_sub(), fp9_add(), fp9_copy(), THROW, and TRY.
Referenced by pp_mil_k54().
fp54_sqr_unr()
void fp54_sqr_unr (dv54_t c, fp54_t a)
Computes the square of a 54-extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to square.
fp54_sqr_basic()
void fp54_sqr_basic (fp54_t c, fp54_t a)
Computes the square of a 54-extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to square.
Definition at line 42 of file relic_fp54_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_add(), fp18_dbl(), fp18_free, fp18_mul_art(), fp18_new, fp18_null, fp18_sub(), THROW, and TRY.
Referenced by fp54_sqr_lazyr().
fp54_sqr_lazyr()
void fp54_sqr_lazyr (fp54_t c, fp54_t a)
Computes the square of a 54-extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to square.
Definition at line 277 of file relic_fp54_sqr.c.
References fp54_sqr_basic().
fp54_sqr_cyc_basic()
void fp54_sqr_cyc_basic (fp54_t c, fp54_t a)
Computes the square of a cyclotomic 54-extension field element using basic arithmetic.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 114 of file relic_fp54_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_add(), fp9_dbl(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sub(), THROW, and TRY.
Referenced by fp54_sqr_cyc_lazyr().
fp54_sqr_cyc_lazyr()
void fp54_sqr_cyc_lazyr (fp54_t c, fp54_t a)
Computes the square of a cyclotomic 54-extension field element using lazy reduction.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 282 of file relic_fp54_sqr.c.
References fp54_sqr_cyc_basic().
fp54_sqr_pck_basic()
void fp54_sqr_pck_basic (fp54_t c, fp54_t a)
Computes the square of a compressed cyclotomic extension field element.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 203 of file relic_fp54_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_add(), fp9_dbl(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sub(), THROW, and TRY.
fp54_sqr_pck_lazyr()
void fp54_sqr_pck_lazyr (fp54_t c, fp54_t a)
Computes the square of a compressed cyclotomic extension field element using lazy reduction.
A cyclotomic element is one raised to the (p^6 - 1)(p^2 + 1)-th power.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 287 of file relic_fp54_sqr.c.
References CATCH_ANY, dv9_free, dv9_new, dv9_null, ERR_CAUGHT, FINALLY, fp3_addc_low(), fp3_nord_low(), fp3_rdcn_low(), fp3_subc_low(), fp9_add(), fp9_dbl(), fp9_free, fp9_mul_art(), fp9_new, fp9_null, fp9_sqr_unr(), fp9_sub(), THROW, and TRY.
fp54_test_cyc()
int fp54_test_cyc (fp54_t a)
Tests if a 54-extension field element belongs to the cyclotomic subgroup.
Parameters
[in] a - the 54-extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 1160 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp54_back_cyc(), fp54_cmp(), fp54_free, fp54_new, fp54_null, result, RLC_EQ, THROW, and TRY.
Referenced by fp54_exp_dig(), fp54_pck(), fp54_size_bin(), and fp54_upk().
fp54_conv_cyc()
void fp54_conv_cyc (fp54_t c, fp54_t a)
Converts a 54-extension field element to a cyclotomic element. Computes c = a^(p^6 - 1)*(p^2 + 1).
Parameters
[out] c - the result.
[in] a - a 54-extension field element.
Converts a 54-extension field element to a cyclotomic element. Computes c = a^(p^6 - 1).
Parameters
[out] c - the result.
[in] a - the 54-extension field element.
Definition at line 1129 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp54_frb(), fp54_free, fp54_inv(), fp54_inv_cyc(), fp54_new, fp54_null, THROW, and TRY.
Referenced by pp_exp_k54().
fp54_back_cyc()
void fp54_back_cyc (fp54_t c, fp54_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to decompress.
Definition at line 1182 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_add(), fp9_copy(), fp9_dbl(), fp9_free, fp9_inv(), fp9_mul_art(), fp9_new, fp9_null, fp9_sub(), fp_add_dig(), THROW, and TRY.
Referenced by fp54_read_bin(), fp54_test_cyc(), and fp54_upk().
fp54_back_cyc_sim()
void fp54_back_cyc_sim (fp54_t * c, fp54_t * a, int n)
Decompresses multiple compressed cyclotomic extension field elements.
Parameters
[out] c - the result.
[in] a - the 54 field elements to decompress.
[in] n - the number of field elements to decompress.
fp54_inv()
void fp54_inv (fp54_t c, fp54_t a)
Inverts a 54-extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to invert.
Definition at line 690 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_add(), fp18_free, fp18_inv(), fp18_mul_art(), fp18_new, fp18_null, fp18_sub(), THROW, and TRY.
Referenced by fp54_conv_cyc(), and fp54_exp().
fp54_inv_cyc()
void fp54_inv_cyc (fp54_t c, fp54_t a)
Computes the inverse of a cyclotomic 54-extension field element.
For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^24 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to invert.
Definition at line 749 of file relic_fpx_inv.c.
References fp18_inv_cyc(), and fp18_neg().
Referenced by fp54_conv_cyc(), fp54_exp_cyc(), fp54_exp_cyc_sps(), pp_exp_k54(), and pp_map_k54().
fp54_frb()
void fp54_frb (fp54_t c, fp54_t a, int i)
Computes the Frobenius endomorphism of a 54-extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a 54-extension field element.
[in] i - the power of the Frobenius map.
Definition at line 181 of file relic_fpx_frb.c.
References fp18_frb(), fp3_mul_frb(), fp54_copy(), and fp9_mul_art().
Referenced by fp54_conv_cyc(), and pp_exp_k54().
fp54_exp()
void fp54_exp (fp54_t c, fp54_t a, bn_t b)
Computes a power of a 54-extension field element. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 522 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp54_copy(), fp54_free, fp54_inv(), fp54_new, fp54_null, fp54_set_dig(), RLC_NEG, THROW, and TRY.
fp54_exp_dig()
void fp54_exp_dig (fp54_t c, fp54_t a, dig_t b)
Computes a power of a 54-extension field element by a small exponent. Faster formulas are used if the extension field element is cyclotomic.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 558 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp54_copy(), fp54_free, fp54_new, fp54_null, fp54_set_dig(), fp54_test_cyc(), THROW, TRY, and util_bits_dig().
fp54_exp_cyc()
void fp54_exp_cyc (fp54_t c, fp54_t a, bn_t b)
Computes a power of a cyclotomic 54-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 1318 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp54_back_cyc_sim(), fp54_copy(), fp54_free, fp54_inv_cyc(), fp54_new, fp54_null, fp54_set_dig(), RLC_ALLOCA, RLC_DIG, RLC_FREE, RLC_NEG, THROW, and TRY.
fp54_exp_cyc_sps()
void fp54_exp_cyc_sps (fp54_t c, fp54_t a, const int * b, int l, int s)
Computes a power of a cyclotomic 54-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 1411 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp54_back_cyc_sim(), fp54_copy(), fp54_free, fp54_inv_cyc(), fp54_new, fp54_null, fp54_set_dig(), RLC_ALLOCA, RLC_FREE, RLC_NEG, THROW, and TRY.
Referenced by pp_exp_k54().
fp54_pck()
void fp54_pck (fp54_t c, fp54_t a)
Compresses a 54-extension field element.
Parameters
[out] r - the result.
[in] p - the 54-extension field element to compress.
Definition at line 131 of file relic_fpx_pck.c.
References fp54_copy(), fp54_test_cyc(), and fp9_zero().
Referenced by fp54_write_bin().
fp54_upk()
int fp54_upk (fp54_t c, fp54_t a)
Decompresses a 54-extension field element.
Parameters
[out] r - the result.
[in] p - the 54-extension field element to decompress.
Returns
if the decompression was successful
Definition at line 139 of file relic_fpx_pck.c.
References fp54_back_cyc(), fp54_copy(), fp54_test_cyc(), and fp9_is_zero().