RELIC: src/cp/relic_cp_pok.c File Reference
relic_cp_pok.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_pokdl_prv (bn_t c, bn_t r, const ec_t y, const bn_t x)
int cp_pokdl_ver (const bn_t c, const bn_t r, const ec_t y)
int cp_pokor_prv (bn_t c[2], bn_t r[2], const ec_t y[2], const bn_t x)
int cp_pokor_ver (const bn_t c[2], const bn_t r[2], const ec_t y[2])
Detailed Description
Implementation of protocols for proof of knowledge of discrete logarithms.
Definition in file relic_cp_pok.c.
Function Documentation
cp_pokdl_prv()
int cp_pokdl_prv (bn_t c, bn_t r, const ec_t y, const bn_t x)
Computes the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Proves that y = [x]G.
Parameters
[out] c - the challenge.
[out] r - the response.
[in] y - the elliptic curve point
[in] x - the discrete logarithm to prove.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 43 of file relic_cp_pok.c.
References bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_sub(), ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, md_map, RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_MD_LEN, RLC_OK, and RLC_TRY.
cp_pokdl_ver()
int cp_pokdl_ver (const bn_t c, const bn_t r, const ec_t y)
Verifies the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Verifies that y = [x]G.
Parameters
[in] c - the challenge.
[in] r - the response.
[in] y - the elliptic curve point.
Returns
a boolean value indicating the verification result.
Definition at line 90 of file relic_cp_pok.c.
References bn_cmp(), bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_sim_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, md_map, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_MD_LEN, and RLC_TRY.
cp_pokor_prv()
int cp_pokor_prv (bn_t c[2], bn_t r[2], const ec_t y[2], const bn_t x)
Computes the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Proves that y0 = [x]G or y[1] = [x]G.
Parameters
[out] c - the challenges.
[out] r - the responses.
[in] y - the elliptic curve points.
[in] x - the discrete logarithm to prove.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 137 of file relic_cp_pok.c.
References bn_copy(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_sub(), ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_gen, ec_mul_sim_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, md_map, RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_MD_LEN, RLC_OK, and RLC_TRY.
cp_pokor_ver()
int cp_pokor_ver (const bn_t c[2], const bn_t r[2], const ec_t y[2])
Verifies the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Verifies that y = [x]G.
Parameters
[in] c - the challenges.
[in] r - the responses.
[in] y - the elliptic curve points.
Returns
a boolean value indicating the verification result.
Definition at line 206 of file relic_cp_pok.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_read_bin(), bn_sub(), ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_sim_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, md_map, RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_MD_LEN, and RLC_TRY.