RELIC: src/ed/relic_ed_norm.c File Reference
relic_ed_norm.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
#include "assert.h"
Functions
static void ed_norm_imp (ed_t r, const ed_t p, int inverted)
void ed_norm (ed_t r, const ed_t p)
void ed_norm_sim (ed_t *r, const ed_t *t, int n)
Detailed Description
Implementation of point normalization on Edwards elliptic curves.
Definition in file relic_ed_norm.c.
Function Documentation
ed_norm_imp()
static void ed_norm_imp (ed_t r, const ed_t p, int inverted) static
Normalizes a point represented in projective coordinates.
Parameters
r - the result.
p - the point to normalize.
Definition at line 48 of file relic_ed_norm.c.
References fp_copy(), fp_set_dig(), ed_st::norm, ed_st::t, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_norm(), and ed_norm_sim().
ed_norm()
void ed_norm (ed_t r, const ed_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 73 of file relic_ed_norm.c.
References ed_copy(), ed_is_infty(), ed_norm_imp(), ed_set_infty(), and ed_st::norm.
Referenced by ed_cmp(), ed_is_valid(), ed_map(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_dig(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_reg_imp(), ed_mul_sim_basic(), ed_mul_sim_joint(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ed_tab(), and ed_write_bin().
ed_norm_sim()
void ed_norm_sim (ed_t * r, const ed_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 89 of file relic_ed_norm.c.
References CATCH_ANY, ed_is_infty(), ed_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp_copy(), fp_inv_sim(), fp_null, RLC_ALLOCA, RLC_FREE, THROW, and TRY.
Referenced by ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), and ed_tab().