RELIC: src/cp/relic_cp_ecies.c File Reference
relic_cp_ecies.c File Reference
Cryptographic protocols
#include <string.h>
#include "relic_core.h"
#include "relic_bn.h"
#include "relic_util.h"
#include "relic_cp.h"
#include "relic_md.h"
#include "relic_bc.h"
Functions
int cp_ecies_gen (bn_t d, ec_t q)
int cp_ecies_enc (ec_t r, uint8_t *out, int *out_len, uint8_t *in, int in_len, ec_t q)
int cp_ecies_dec (uint8_t *out, int *out_len, ec_t r, uint8_t *in, int in_len, bn_t d)
Detailed Description
Implementation of the ECIES cryptosystem.
Version
$Id$
Definition in file relic_cp_ecies.c.
Function Documentation
int cp_ecies_gen (bn_t d, ec_t q)
Generates an ECIES key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 45 of file relic_cp_ecies.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ec_curve_get_ord, ec_mul_gen, FINALLY, STS_ERR, STS_OK, and TRY.
int cp_ecies_enc (ec_t r, uint8_t * out, int * out_len, uint8_t * in, int in_len, ec_t q)
Encrypts using the ECIES cryptosystem.
Parameters
[out] r - the resulting elliptic curve point.
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] iv - the block cipher initialization vector.
[in] q - the public key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 73 of file relic_cp_ecies.c.
References bc_aes_cbc_enc(), BC_LEN, bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), bn_size_bin(), bn_write_bin(), CATCH_ANY, CEIL, ec_curve_get_ord, ec_free, ec_get_x, ec_mul, ec_mul_gen, ec_new, ec_null, ec_param_level, FC_BYTES, FINALLY, md_hmac(), md_kdf2(), MD_LEN, STS_ERR, STS_OK, and TRY.
int cp_ecies_dec (uint8_t * out, int * out_len, ec_t r, uint8_t * in, int in_len, bn_t d)
Decrypts using the ECIES cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] iv - the block cipher initialization vector.
[in] d - the private key.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 130 of file relic_cp_ecies.c.
References bc_aes_cbc_dec(), BC_LEN, bn_bits(), bn_free, bn_new, bn_null, bn_size_bin(), bn_write_bin(), CATCH_ANY, CEIL, ec_free, ec_get_x, ec_mul, ec_new, ec_null, ec_param_level, FC_BYTES, FINALLY, md_hmac(), md_kdf2(), MD_LEN, STS_ERR, STS_OK, TRY, and util_cmp_const().