RELIC: src/fpx/relic_fpx_inv.c File Reference
relic_fpx_inv.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
void fp2_inv (fp2_t c, fp2_t a)
void fp2_inv_cyc (fp2_t c, fp2_t a)
void fp2_inv_sim (fp2_t *c, fp2_t *a, int n)
void fp3_inv (fp3_t c, fp3_t a)
void fp3_inv_sim (fp3_t *c, fp3_t *a, int n)
void fp4_inv_cyc (fp4_t c, fp4_t a)
void fp4_inv (fp4_t c, fp4_t a)
void fp6_inv (fp6_t c, fp6_t a)
void fp8_inv_cyc (fp8_t c, fp8_t a)
void fp8_inv (fp8_t c, fp8_t a)
void fp8_inv_sim (fp8_t *c, fp8_t *a, int n)
void fp9_inv (fp9_t c, fp9_t a)
void fp9_inv_sim (fp9_t *c, fp9_t *a, int n)
void fp12_inv (fp12_t c, fp12_t a)
void fp12_inv_cyc (fp12_t c, fp12_t a)
void fp18_inv (fp18_t c, fp18_t a)
void fp18_inv_cyc (fp18_t c, fp18_t a)
void fp24_inv (fp24_t c, fp24_t a)
void fp48_inv (fp48_t c, fp48_t a)
void fp48_inv_cyc (fp48_t c, fp48_t a)
void fp54_inv (fp54_t c, fp54_t a)
void fp54_inv_cyc (fp54_t c, fp54_t a)
Detailed Description
Implementation of inversion in extensions defined over prime fields.
Definition in file relic_fpx_inv.c.
Function Documentation
fp2_inv()
void fp2_inv (fp2_t c, fp2_t a)
Inverts a quadratic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to invert.
Definition at line 39 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_mul_dig(), fp_null, fp_prime_get_qnr(), THROW, and TRY.
Referenced by ep2_add_basic_imp(), ep2_dbl_basic_imp(), ep2_norm_imp(), fp12_back_cyc(), fp2_conv_cyc(), fp2_exp(), fp2_inv_sim(), fp4_inv(), fp6_inv(), pp_map_sim_weilp_k2(), pp_map_weilp_k2(), pp_norm_k12(), and pp_norm_k8().
fp2_inv_cyc()
void fp2_inv_cyc (fp2_t c, fp2_t a)
Computes the inverse of a cyclotomic quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to invert.
Definition at line 92 of file relic_fpx_inv.c.
References fp_copy().
Referenced by fp2_conv_cyc(), fp2_exp_cyc(), pp_map_sim_weilp_k2(), and pp_map_weilp_k2().
fp2_inv_sim()
void fp2_inv_sim (fp2_t * c, fp2_t * a, int n)
Inverts multiple quadratic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the quadratic extension field elements to invert.
[in] n - the number of elements.
Definition at line 97 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_inv(), fp2_new, fp2_null, RLC_ALLOCA, THROW, and TRY.
Referenced by ep2_norm_sim(), and fp12_back_cyc_sim().
fp3_inv()
void fp3_inv (fp3_t c, fp3_t a)
Inverts a cubic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the cubic extension field element to invert.
Definition at line 139 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_copy(), fp_null, fp_prime_get_cnr(), THROW, and TRY.
Referenced by fp3_exp(), fp3_inv_sim(), and fp9_inv().
fp3_inv_sim()
void fp3_inv_sim (fp3_t * c, fp3_t * a, int n)
Inverts multiple cubic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the cubic extension field elements to invert.
[in] n - the number of elements.
Definition at line 222 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp3_copy(), fp3_free, fp3_inv(), fp3_new, fp3_null, RLC_ALLOCA, THROW, and TRY.
fp4_inv_cyc()
void fp4_inv_cyc (fp4_t c, fp4_t a)
Computes the inverse of a cyclotomic quartic extension field element.
For cyclotomic elements, this is equivalent to computing the conjugate. A cyclotomic element is one previously raised to the (p^2 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to invert.
Definition at line 264 of file relic_fpx_inv.c.
References fp2_copy(), and fp2_neg().
fp4_inv()
void fp4_inv (fp4_t c, fp4_t a)
Inverts a quartic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to invert.
Definition at line 269 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_inv(), fp2_neg(), fp2_new, fp2_null, THROW, and TRY.
Referenced by fp4_exp(), and fp8_inv().
fp6_inv()
void fp6_inv (fp6_t c, fp6_t a)
Inverts a sextic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to invert.
Definition at line 297 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_inv(), fp2_new, fp2_null, THROW, and TRY.
Referenced by fp12_inv(), and fp6_exp().
fp8_inv_cyc()
void fp8_inv_cyc (fp8_t c, fp8_t a)
Computes the inverse of a cyclotomic octic extension field element.
For cyclotomic elements, this is equivalent to computing the conjugate. A cyclotomic element is one previously raised to the (p^4 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the octic extension field element to invert.
Definition at line 356 of file relic_fpx_inv.c.
References fp4_copy(), and fp4_neg().
Referenced by fp8_conv_cyc(), fp8_exp_cyc(), fp8_test_cyc(), pp_exp_k8(), and pp_map_oatep_k8().
fp8_inv()
void fp8_inv (fp8_t c, fp8_t a)
Inverts an octic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the octic extension field element to invert.
Definition at line 361 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp4_free, fp4_inv(), fp4_mul_art(), fp4_neg(), fp4_new, fp4_null, fp4_sub(), THROW, and TRY.
Referenced by ep8_add_basic(), ep8_dbl_basic(), fp24_inv(), fp48_back_cyc(), fp8_conv_cyc(), fp8_exp(), and fp8_inv_sim().
fp8_inv_sim()
void fp8_inv_sim (fp8_t * c, fp8_t * a, int n)
Inverts multiple octic extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the octic extension field elements to invert.
[in] n - the number of elements.
Definition at line 389 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_copy(), fp8_free, fp8_inv(), fp8_new, fp8_null, RLC_ALLOCA, THROW, and TRY.
Referenced by fp48_back_cyc_sim().
fp9_inv()
void fp9_inv (fp9_t c, fp9_t a)
Inverts a nonic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to invert.
Definition at line 431 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp3_free, fp3_inv(), fp3_mul_nor(), fp3_new, fp3_null, THROW, and TRY.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp54_back_cyc(), fp9_exp(), fp9_inv_sim(), and pp_mil_k54().
fp9_inv_sim()
void fp9_inv_sim (fp9_t * c, fp9_t * a, int n)
Inverts multiple noinc extension field elements simultaneously.
Parameters
[out] c - the result.
[in] a - the nonic extension field elements to invert.
[in] n - the number of elements.
Definition at line 490 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_copy(), fp9_free, fp9_inv(), fp9_new, fp9_null, RLC_ALLOCA, THROW, and TRY.
Referenced by fp54_back_cyc_sim().
fp12_inv()
void fp12_inv (fp12_t c, fp12_t a)
Inverts a dodecic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to invert.
Definition at line 532 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_free, fp6_inv(), fp6_mul_art(), fp6_neg(), fp6_new, fp6_null, fp6_sub(), THROW, and TRY.
Referenced by fp12_conv_cyc(), fp12_exp(), pp_map_sim_weilp_k12(), and pp_map_weilp_k12().
fp12_inv_cyc()
void fp12_inv_cyc (fp12_t c, fp12_t a)
Computes the inverse of a cyclotomic dodecic extension field element. For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^6 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to invert.
Definition at line 560 of file relic_fpx_inv.c.
References fp6_copy(), and fp6_neg().
Referenced by fp12_conv_cyc(), fp12_exp_cyc(), fp12_exp_cyc_sps(), pp_exp_b12(), pp_exp_bn(), pp_map_oatep_k12(), pp_map_sim_oatep_k12(), pp_map_sim_weilp_k12(), and pp_map_weilp_k12().
fp18_inv()
void fp18_inv (fp18_t c, fp18_t a)
Inverts an octdecic extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to invert.
Definition at line 565 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_free, fp9_inv(), fp9_mul_art(), fp9_neg(), fp9_new, fp9_null, fp9_sub(), THROW, and TRY.
Referenced by fp18_exp(), and fp54_inv().
fp18_inv_cyc()
void fp18_inv_cyc (fp18_t c, fp18_t a)
Computes the inverse of a cyclotomic octdecic extension field element. For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^9 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to invert.
Definition at line 593 of file relic_fpx_inv.c.
References fp9_copy(), and fp9_neg().
Referenced by fp54_inv_cyc().
fp24_inv()
void fp24_inv (fp24_t c, fp24_t a)
Inverts a 24-degree extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to invert.
Definition at line 598 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_free, fp8_inv(), fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), THROW, and TRY.
Referenced by fp24_exp(), and fp48_inv().
fp48_inv()
void fp48_inv (fp48_t c, fp48_t a)
Inverts a 48-extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to invert.
Definition at line 657 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp24_free, fp24_inv(), fp24_mul_art(), fp24_neg(), fp24_new, fp24_null, fp24_sub(), THROW, and TRY.
Referenced by fp48_conv_cyc(), and fp48_exp().
fp48_inv_cyc()
void fp48_inv_cyc (fp48_t c, fp48_t a)
Computes the inverse of a cyclotomic 48-extension field element.
For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^24 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to invert.
Definition at line 685 of file relic_fpx_inv.c.
References fp24_copy(), and fp24_neg().
Referenced by fp48_conv_cyc(), fp48_exp_cyc(), fp48_exp_cyc_sps(), pp_exp_k48(), and pp_map_k48().
fp54_inv()
void fp54_inv (fp54_t c, fp54_t a)
Inverts a 54-extension field element. Computes c = 1/a.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to invert.
Definition at line 690 of file relic_fpx_inv.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_add(), fp18_free, fp18_inv(), fp18_mul_art(), fp18_new, fp18_null, fp18_sub(), THROW, and TRY.
Referenced by fp54_conv_cyc(), and fp54_exp().
fp54_inv_cyc()
void fp54_inv_cyc (fp54_t c, fp54_t a)
Computes the inverse of a cyclotomic 54-extension field element.
For unitary elements, this is equivalent to computing the conjugate. A unitary element is one previously raised to the (p^24 - 1)-th power.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to invert.
Definition at line 749 of file relic_fpx_inv.c.
References fp18_inv_cyc(), and fp18_neg().
Referenced by fp54_conv_cyc(), fp54_exp_cyc(), fp54_exp_cyc_sps(), pp_exp_k54(), and pp_map_k54().