RELIC: src/epx/relic_ep2_pck.c File Reference
relic_ep2_pck.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
void ep2_pck (ep2_t r, ep2_t p)
int ep2_upk (ep2_t r, ep2_t p)
Detailed Description
Implementation of point compression on prime elliptic curves over quadratic extensions.
Definition in file relic_ep2_pck.c.
Function Documentation
ep2_pck()
void ep2_pck (ep2_t r, ep2_t p)
Compresses a point in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to compress.
Definition at line 39 of file relic_ep2_pck.c.
References fp2_copy(), fp2_zero(), fp_get_bit(), fp_set_bit(), fp_set_dig(), fp_zero(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_write_bin().
ep2_upk()
int ep2_upk (ep2_t r, ep2_t p)
Decompresses a point in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
if the decompression was successful
Definition at line 50 of file relic_ep2_pck.c.
References CATCH_ANY, ep2_rhs(), ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_neg(), fp2_new, fp2_null, fp2_srt(), fp_get_bit(), fp_set_dig(), fp_zero(), ep2_st::norm, result, THROW, TRY, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_read_bin().