RELIC: src/pc/relic_pc_core.c File Reference
relic_pc_core.c File Reference
Pairing-based cryptography
#include "relic_pc.h"
#include "relic_core.h"
#include "relic_util.h"
Functions
void pc_core_init (void)
void pc_core_calc (void)
void pc_core_clean (void)
Detailed Description
Implementation core routines for pairing-based protocols.
Definition in file relic_pc_core.c.
Function Documentation
pc_core_init()
void pc_core_init (void)
Initializes the cryptographic protocol module.
Definition at line 40 of file relic_pc_core.c.
References core_get(), and gt_new.
Referenced by core_init().
pc_core_calc()
void pc_core_calc (void)
Computes constants internal to the cryptographic protocol module.
Definition at line 44 of file relic_pc_core.c.
References core_get(), ERR_CAUGHT, g1_free, g1_get_gen, g1_new, g1_null, g2_free, g2_get_gen, g2_new, g2_null, gt_copy, gt_free, gt_new, gt_null, pc_map, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_curve_set_twist(), ep3_curve_set_twist(), ep4_curve_set_twist(), ep8_curve_set_twist(), and ep_param_set_any_pairf().
pc_core_clean()
void pc_core_clean (void)
Finalizes the cryptographic protocol module.
Definition at line 72 of file relic_pc_core.c.
References core_get(), and gt_free.
Referenced by core_clean().