RELIC: src/pp/relic_pp_dbl_k48.c File Reference
relic_pp_dbl_k48.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void ep8_dbl_basic (fp8_t s, fp8_t rx, fp8_t ry)
void pp_dbl_k48_basic (fp48_t l, fp8_t rx, fp8_t ry, ep_t p)
void pp_dbl_k48_projc (fp48_t l, fp8_t rx, fp8_t ry, fp8_t rz, ep_t p)
Detailed Description
Implementation of Miller doubling for curves with embedding degree 48.
Definition in file relic_pp_dbl_k48.c.
Function Documentation
ep8_dbl_basic()
static void ep8_dbl_basic (fp8_t s, fp8_t rx, fp8_t ry) static
Definition at line 40 of file relic_pp_dbl_k48.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_copy(), fp8_dbl(), fp8_free, fp8_inv(), fp8_new, fp8_null, fp8_sub(), THROW, and TRY.
Referenced by pp_dbl_k48_basic().
pp_dbl_k48_basic()
void pp_dbl_k48_basic (fp48_t l, fp8_t rx, fp8_t ry, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 101 of file relic_pp_dbl_k48.c.
References CATCH_ANY, ep8_dbl_basic(), ERR_CAUGHT, FINALLY, fp48_zero(), fp8_copy(), fp8_free, fp8_new, fp8_null, fp8_sub(), fp_copy(), THROW, TRY, ep_st::x, and ep_st::y.
pp_dbl_k48_projc()
void pp_dbl_k48_projc (fp48_t l, fp8_t rx, fp8_t ry, fp8_t rz, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 48 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 145 of file relic_pp_dbl_k48.c.
References CATCH_ANY, ep_curve_get_b(), ERR_CAUGHT, FINALLY, fp8_add(), fp8_dbl(), fp8_free, fp8_new, fp8_null, fp8_sub(), fp8_zero(), fp_copy(), THROW, TRY, ep_st::x, and ep_st::y.