RELIC: src/eb/relic_eb_map.c File Reference
relic_eb_map.c File Reference
Elliptic curves over binary fields
#include "relic_core.h"
#include "relic_md.h"
#include "relic_eb.h"
Functions
void eb_map (eb_t p, const uint8_t *msg, int len)
Detailed Description
Implementation of hashing to a binary elliptic curve.
Version
Id
relic_eb_map.c 1789 2014-03-02 14:50:24Z dfaranha
Definition in file relic_eb_map.c.
Function Documentation
void eb_map (eb_t p, const uint8_t * msg, int len)
Maps a byte array to a point in a binary elliptic curve.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 40 of file relic_eb_map.c.
References bn_add_dig(), bn_bits(), BN_DIGIT, bn_free, bn_mod_2b(), bn_new, bn_null, bn_read_bin(), CATCH_ANY, dv_copy(), eb_curve_get_cof(), eb_mul, eb_mul_dig(), eb_rhs(), ERR_CAUGHT, FB_BITS, FB_BYTES, FB_DIGS, fb_free, fb_inv, fb_mul, fb_new, fb_null, fb_set_dig(), fb_slv, fb_sqr, fb_trc, FINALLY, MD_LEN, md_map, MIN, THROW, and TRY.