RELIC: src/fp/relic_fp_add.c File Reference
relic_fp_add.c File Reference
Prime field arithmetic
#include "relic_core.h"
#include "relic_fp_low.h"
Functions
void fp_add_basic (fp_t c, const fp_t a, const fp_t b)
void fp_add_integ (fp_t c, const fp_t a, const fp_t b)
void fp_add_dig (fp_t c, const fp_t a, dig_t b)
void fp_sub_basic (fp_t c, const fp_t a, const fp_t b)
void fp_sub_integ (fp_t c, const fp_t a, const fp_t b)
void fp_sub_dig (fp_t c, const fp_t a, dig_t b)
void fp_neg_basic (fp_t c, const fp_t a)
void fp_neg_integ (fp_t c, const fp_t a)
void fp_dbl_basic (fp_t c, const fp_t a)
void fp_dbl_integ (fp_t c, const fp_t a)
void fp_hlv_basic (fp_t c, const fp_t a)
void fp_hlv_integ (fp_t c, const fp_t a)
Detailed Description
Implementation of the prime field addition and subtraction functions.
Definition in file relic_fp_add.c.
Function Documentation
fp_add_basic()
void fp_add_basic (fp_t c, const fp_t a, const fp_t b)
Adds two prime field elements using basic addition. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first prime field element to add.
[in] b - the second prime field element to add.
Definition at line 41 of file relic_fp_add.c.
References dv_cmp(), fp_addn_low(), fp_prime_get(), fp_subn_low(), RLC_FP_DIGS, and RLC_LT.
fp_add_integ()
void fp_add_integ (fp_t c, const fp_t a, const fp_t b)
Adds two prime field elements with integrated modular reduction. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first prime field element to add.
[in] b - the second prime field element to add.
Definition at line 54 of file relic_fp_add.c.
References fp_addm_low().
fp_add_dig()
void fp_add_dig (fp_t c, const fp_t a, dig_t b)
Adds a prime field element and a digit. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first prime field element to add.
[in] b - the digit to add.
Definition at line 60 of file relic_fp_add.c.
References CATCH_ANY, core_get(), dv_cmp(), ERR_CAUGHT, FINALLY, fp_add1_low(), fp_null, fp_prime_get(), fp_set_dig(), fp_subn_low(), RLC_FP_DIGS, RLC_LT, THROW, and TRY.
Referenced by ed_add_basic(), ed_dbl_basic(), ed_map(), ep2_map(), ep_dbl_basic_imp(), ep_dbl_projc_imp(), ep_map(), ep_rhs(), ep_sw_b12(), ep_sw_bn(), fp12_back_cyc(), fp12_back_cyc_sim(), fp48_back_cyc(), fp48_back_cyc_sim(), fp54_back_cyc(), fp54_back_cyc_sim(), fp8_sqr_cyc(), and fp_inv_divst().
fp_sub_basic()
void fp_sub_basic (fp_t c, const fp_t a, const fp_t b)
Subtracts a prime field element from another using basic subtraction. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the prime field element.
[in] b - the prime field element to subtract.
Definition at line 92 of file relic_fp_add.c.
References fp_addn_low(), fp_prime_get(), and fp_subn_low().
fp_sub_integ()
void fp_sub_integ (fp_t c, const fp_t a, const fp_t b)
Subtracts a prime field element from another with integrated modular reduction. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the prime field element.
[in] b - the prime field element to subtract.
Definition at line 105 of file relic_fp_add.c.
References fp_subm_low().
fp_sub_dig()
void fp_sub_dig (fp_t c, const fp_t a, dig_t b)
Subtracts a digit from a prime field element. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the prime field element.
[in] b - the digit to subtract.
Definition at line 111 of file relic_fp_add.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, fp_addn_low(), fp_null, fp_prime_get(), fp_set_dig(), fp_sub1_low(), THROW, and TRY.
Referenced by ed_add_basic(), ed_dbl_basic(), ed_map(), ed_upk(), ep_sw_b12(), ep_sw_bn(), fp2_upk(), fp3_srt(), and fp8_sqr_cyc().
fp_neg_basic()
void fp_neg_basic (fp_t c, const fp_t a)
Negates a prime field element using basic negation.
Parameters
[out] c - the result.
[out] a - the prime field element to negate.
Definition at line 143 of file relic_fp_add.c.
References fp_prime_get(), and fp_subn_low().
fp_neg_integ()
void fp_neg_integ (fp_t c, const fp_t a)
Negates a prime field element using integrated negation.
Parameters
[out] c - the result.
[out] a - the prime field element to negate.
Definition at line 151 of file relic_fp_add.c.
References fp_negm_low().
fp_dbl_basic()
void fp_dbl_basic (fp_t c, const fp_t a)
Doubles a prime field element using basic addition.
Parameters
[out] c - the result.
[in] a - the first prime field element to add.
Definition at line 159 of file relic_fp_add.c.
References dv_cmp(), fp_lsh1_low(), fp_prime_get(), fp_subn_low(), RLC_FP_DIGS, and RLC_LT.
fp_dbl_integ()
void fp_dbl_integ (fp_t c, const fp_t a)
Doubles a prime field element with integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first prime field element to add.
Definition at line 172 of file relic_fp_add.c.
References fp_dblm_low().
fp_hlv_basic()
void fp_hlv_basic (fp_t c, const fp_t a)
Halves a prime field element.
Parameters
[out] c - the result.
[in] a - the prime field element to halve.
Definition at line 180 of file relic_fp_add.c.
References fp_addn_low(), fp_copy(), fp_prime_get(), fp_rsh1_low(), RLC_DIG, and RLC_FP_DIGS.
fp_hlv_integ()
void fp_hlv_integ (fp_t c, const fp_t a)
Halves a prime field element with integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the prime field element to halve.
Definition at line 198 of file relic_fp_add.c.
References fp_hlvm_low().