RELIC: src/cp/relic_cp_bls.c File Reference
relic_cp_bls.c File Reference
Cryptographic protocols
#include "relic.h"
#include "relic_test.h"
#include "relic_bench.h"
Functions
int cp_bls_gen (bn_t d, g2_t q)
int cp_bls_sig (g1_t s, uint8_t *msg, int len, bn_t d)
int cp_bls_ver (g1_t s, uint8_t *msg, int len, g2_t q)
Detailed Description
Implementation of the Boneh-Lynn-Schacham short signature protocol.
Version
Id
relic_cp_bls.c 1754 2014-02-05 17:17:34Z dfaranha
Definition in file relic_cp_bls.c.
Function Documentation
int cp_bls_gen (bn_t d, g2_t q)
Generates a BLS key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Definition at line 40 of file relic_cp_bls.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, FINALLY, g2_get_ord, g2_mul_gen, STS_ERR, STS_OK, and TRY.
int cp_bls_sig (g1_t s, uint8_t * msg, int len, bn_t d)
Signs a message using BLS.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] d - the private key.
Definition at line 67 of file relic_cp_bls.c.
References CATCH_ANY, FINALLY, g1_free, g1_map, g1_mul, g1_new, g1_null, STS_ERR, STS_OK, and TRY.
int cp_bls_ver (g1_t s, uint8_t * msg, int len, g2_t q)
Verifies a message signed with BLS using the basic method.
Parameters
[out] s - the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] q - the public key.
Returns
a boolean value indicating the verification result.
Definition at line 87 of file relic_cp_bls.c.
References CATCH_ANY, CMP_EQ, ERR_CAUGHT, FINALLY, g1_free, g1_map, g1_new, g1_null, g2_free, g2_get_gen, g2_new, g2_null, gt_cmp, gt_free, gt_new, gt_null, pc_map, THROW, and TRY.