RELIC: src/pp/relic_pp_exp_k18.c File Reference
relic_pp_exp_k18.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_exp_kss (fp18_t c, fp18_t a)
void pp_exp_sg (fp18_t c, fp18_t a)
void pp_exp_fm (fp18_t c, fp18_t a)
void pp_exp_k18 (fp18_t c, fp18_t a)
Detailed Description
Implementation of the final exponentiation for curves of embedding degree 18.
Definition in file relic_pp_exp_k18.c.
Function Documentation
pp_exp_kss()
static void pp_exp_kss (fp18_t c, fp18_t a) static
Computes the final exponentiation of a pairing defined over a KSS curve.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 46 of file relic_pp_exp_k18.c.
References bn_free, bn_new, bn_null, bn_sign(), ERR_CAUGHT, fp18_conv_cyc(), fp18_exp_cyc_sps(), fp18_frb(), fp18_free, fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_sqr_cyc, fp_prime_get_par(), fp_prime_get_par_sps(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k18().
pp_exp_sg()
void pp_exp_sg (fp18_t c, fp18_t a)
Computes the final exponentiation of a pairing defined over a SG curve.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 171 of file relic_pp_exp_k18.c.
References bn_free, bn_new, bn_null, bn_sign(), ERR_CAUGHT, fp18_conv_cyc(), fp18_copy(), fp18_exp_cyc_sps(), fp18_frb(), fp18_free, fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_sqr, fp18_sqr_cyc, fp_prime_get_par(), fp_prime_get_par_sps(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k18().
pp_exp_fm()
void pp_exp_fm (fp18_t c, fp18_t a)
Computes the final exponentiation of a pairing defined over an FM curve.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 267 of file relic_pp_exp_k18.c.
References bn_abs(), bn_add_dig(), bn_div_dig(), bn_free, bn_new, bn_null, bn_sign(), bn_sub_dig(), ERR_CAUGHT, fp18_conv_cyc(), fp18_exp_cyc(), fp18_exp_cyc_sps(), fp18_frb(), fp18_free, fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_sqr_cyc, fp_prime_get_par(), fp_prime_get_par_sps(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_POS, RLC_THROW, and RLC_TRY.
Referenced by pp_exp_k18().
pp_exp_k18()
void pp_exp_k18 (fp18_t c, fp18_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 18. Computes c = a^(p^18 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 376 of file relic_pp_exp_k18.c.
References ep_curve_is_pairf(), EP_FM18, EP_K18, EP_SG18, pp_exp_fm(), pp_exp_kss(), and pp_exp_sg().
Referenced by gt_rand(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_tatep_k18(), and pp_map_tatep_k18().