RELIC: src/fb/relic_fb_add.c File Reference
relic_fb_add.c File Reference
Binary field arithmetic
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "relic_core.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
Functions
void fb_add (fb_t c, const fb_t a, const fb_t b)
void fb_add_dig (fb_t c, const fb_t a, dig_t b)
Detailed Description
Implementation of binary field addition and subtraction functions.
Definition in file relic_fb_add.c.
Function Documentation
fb_add()
void fb_add (fb_t c, const fb_t a, const fb_t b)
Adds two binary field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first binary field element to add.
[in] b - the second binary field element to add.
Definition at line 44 of file relic_fb_add.c.
References fb_addn_low().
Referenced by eb_add_basic_imp(), eb_add_projc_imp(), eb_add_projc_mix(), eb_dbl_basic_imp(), eb_dbl_projc_imp(), eb_hlv(), eb_is_valid(), eb_mul_halve(), eb_mul_lodah(), eb_neg_basic(), eb_neg_projc(), eb_norm_hlv(), eb_rhs(), fb2_inv(), fb2_mul(), fb2_mul_nor(), fb2_slv(), fb2_sqr(), fb_inv_binar(), fb_inv_bruch(), fb_mul_basic(), fb_poly_add(), fb_slv_basic(), fb_trc_basic(), find_solve(), and find_trace().
fb_add_dig()
void fb_add_dig (fb_t c, const fb_t a, dig_t b)
Adds a binary field element and a small binary field element. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the binary field element to add.
[in] b - the small binary field element to add.
Definition at line 48 of file relic_fb_add.c.
References fb_add1_low().
Referenced by eb_add_basic_imp(), eb_dbl_basic_imp(), eb_hlv(), eb_mul_lodah(), eb_rhs(), eb_upk(), fb2_slv(), fb_read_str(), fb_slv_basic(), and fb_slv_quick().