RELIC: src/epx/relic_ep4_mul_cof.c File Reference
relic_ep4_mul_cof.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_md.h"
Functions
static void ep4_mul_cof_k16 (ep4_t r, const ep4_t p)
static void ep4_mul_cof_afg16 (ep4_t r, const ep4_t p)
static void ep4_mul_cof_fm16 (ep4_t r, const ep4_t p)
void ep4_mul_cof_b24 (ep4_t r, const ep4_t p)
void ep4_mul_cof (ep4_t r, const ep4_t p)
Detailed Description
Implementation of point multiplication of a prime elliptic curve over a quartic extension field by the curve cofactor.
Definition in file relic_ep4_mul_cof.c.
Function Documentation
ep4_mul_cof_k16()
static void ep4_mul_cof_k16 (ep4_t r, const ep4_t p) static
Multiplies a point by the cofactor in a KSS16 curve.
Parameters
[out] r - the result.
[in] p - the point to multiply.
Definition at line 46 of file relic_ep4_mul_cof.c.
References bn_free, bn_new, bn_null, ep4_add, ep4_dbl, ep4_frb(), ep4_free, ep4_mul_basic(), ep4_mul_dig(), ep4_new, ep4_norm(), ep4_null, ep4_sub(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_cof().
ep4_mul_cof_afg16()
static void ep4_mul_cof_afg16 (ep4_t r, const ep4_t p) static
Multiplies a point by the cofactor in a KSS16 curve.
Parameters
[out] r - the result.
[in] p - the point to multiply.
Definition at line 135 of file relic_ep4_mul_cof.c.
References bn_free, bn_new, bn_null, ep4_add, ep4_dbl, ep4_frb(), ep4_free, ep4_mul_basic(), ep4_new, ep4_norm(), ep4_null, ep4_sub(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_cof().
ep4_mul_cof_fm16()
static void ep4_mul_cof_fm16 (ep4_t r, const ep4_t p) static
Multiplies a point by the cofactor in a FM16 curve.
Parameters
[out] r - the result.
[in] p - the point to multiply.
Definition at line 208 of file relic_ep4_mul_cof.c.
References bn_dbl(), bn_free, bn_hlv(), bn_is_even(), bn_new, bn_null, ep4_add, ep4_dbl, ep4_frb(), ep4_free, ep4_mul_basic(), ep4_new, ep4_norm(), ep4_null, ep4_sub(), ERR_CAUGHT, ERR_NO_VALID, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_cof().
ep4_mul_cof_b24()
void ep4_mul_cof_b24 (ep4_t r, const ep4_t p)
Multiplies a point by the cofactor in a BLS24 curve.
Parameters
[out] r - the result.
[in] p - the point to multiply.
Definition at line 291 of file relic_ep4_mul_cof.c.
References bn_add_dig(), bn_free, bn_new, bn_null, bn_sub_dig(), ep4_add, ep4_dbl, ep4_frb(), ep4_free, ep4_mul_basic(), ep4_new, ep4_norm(), ep4_null, ep4_sub(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_cof().
ep4_mul_cof()
void ep4_mul_cof (ep4_t r, const ep4_t p)
Multiplies a point in an elliptic curve over a quartic extension field by the curve cofactor or a small multiple for which a short vector exists. In short, it takes a point in the curve to the large prime-order subgroup.
Parameters
[out] R - the result.
[in] P - the point to multiply.
Definition at line 350 of file relic_ep4_mul_cof.c.
References bn_free, bn_null, ep4_curve_get_cof(), ep4_mul_big, ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), EP_AFG16, EP_B24, ep_curve_is_pairf(), EP_FM16, EP_K16, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_map().