RELIC: src/epx/relic_ep8_curve.c File Reference
relic_ep8_curve.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Macros
#define ASSIGN(CURVE)
Functions
static void detect_opt (int *opt, fp8_t a)
void ep8_curve_init (void)
void ep8_curve_clean (void)
int ep8_curve_opt_a (void)
int ep8_curve_opt_b (void)
void ep8_curve_mul_a (fp8_t c, const fp8_t a)
void ep8_curve_mul_b (fp8_t c, const fp8_t a)
int ep8_curve_is_twist (void)
void ep8_curve_get_gen (ep8_t g)
fp4_t * ep8_curve_get_a (void)
fp4_t * ep8_curve_get_b (void)
void ep8_curve_get_ord (bn_t n)
void ep8_curve_get_cof (bn_t h)
ep8_t * ep8_curve_get_tab (void)
void ep8_curve_set_twist (int type)
void ep8_curve_set (const fp8_t a, const fp8_t b, const ep8_t g, const bn_t r, const bn_t h)
Detailed Description
Implementation of configuration of prime elliptic curves over an octic extension field.
Definition in file relic_ep8_curve.c.
Macro Definition Documentation
ASSIGN
#define ASSIGN (CURVE)
Assigns a set of ordinary elliptic curve parameters.
Parameters
[in] CURVE - the curve parameters to assign.
Definition at line 77 of file relic_ep8_curve.c.
Referenced by ep8_curve_set_twist().
Function Documentation
detect_opt()
static void detect_opt (int * opt, fp8_t a) static
Detects an optimization based on the curve coefficients.
Definition at line 134 of file relic_ep8_curve.c.
References ERR_CAUGHT, fp2_is_zero(), fp4_is_zero(), fp8_cmp(), fp8_cmp_dig(), fp8_free, fp8_is_zero(), fp8_neg(), fp8_new, fp8_null, fp8_set_dig(), fp_bits(), fp_is_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_EQ, RLC_FINALLY, RLC_HUGE, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep8_curve_set_twist().
ep8_curve_init()
void ep8_curve_init (void)
Initializes the elliptic curve over octic extension.
Definition at line 170 of file relic_ep8_curve.c.
References bn_make(), core_get(), _ctx_t::ep8_a, _ctx_t::ep8_b, _ctx_t::ep8_g, _ctx_t::ep8_h, ep8_new, _ctx_t::ep8_pre, _ctx_t::ep8_ptr, _ctx_t::ep8_r, fp8_new, RLC_EP_TABLE, RLC_FP_DIGS, ep8_st::x, ep8_st::y, and ep8_st::z.
Referenced by pp_map_init().
ep8_curve_clean()
void ep8_curve_clean (void)
Finalizes the elliptic curve over octic extension.
Definition at line 198 of file relic_ep8_curve.c.
References bn_clean(), core_get(), _ctx_t::ep8_a, _ctx_t::ep8_b, ep8_free, _ctx_t::ep8_g, _ctx_t::ep8_h, _ctx_t::ep8_pre, _ctx_t::ep8_r, fp8_free, RLC_EP_TABLE, ep8_st::x, ep8_st::y, and ep8_st::z.
Referenced by pp_map_clean().
ep8_curve_opt_a()
int ep8_curve_opt_a (void)
Returns a optimization identifier based on the 'a' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 216 of file relic_ep8_curve.c.
References core_get(), and _ctx_t::ep8_opt_a.
Referenced by ep8_rhs().
ep8_curve_opt_b()
int ep8_curve_opt_b (void)
Returns b optimization identifier based on the 'b' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 220 of file relic_ep8_curve.c.
References core_get(), and _ctx_t::ep8_opt_b.
Referenced by ep8_rhs().
ep8_curve_mul_a()
void ep8_curve_mul_a (fp8_t c, const fp8_t a)
Multiplies a field element by the a-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 224 of file relic_ep8_curve.c.
References core_get(), _ctx_t::ep8_a, _ctx_t::ep8_opt_a, fp8_copy(), fp8_dbl(), fp8_mul, fp8_mul_dig(), fp8_zero(), RLC_ONE, RLC_TINY, RLC_TWO, and RLC_ZERO.
ep8_curve_mul_b()
void ep8_curve_mul_b (fp8_t c, const fp8_t a)
Multiplies a field element by the b-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 247 of file relic_ep8_curve.c.
References core_get(), _ctx_t::ep8_b, _ctx_t::ep8_opt_b, fp8_copy(), fp8_mul, fp8_mul_dig(), fp8_zero(), RLC_ONE, RLC_TINY, and RLC_ZERO.
ep8_curve_is_twist()
int ep8_curve_is_twist (void)
Tests if the configured elliptic curve is a twist.
Returns
the type of the elliptic curve twist, 0 if non-twisted curve.
Definition at line 267 of file relic_ep8_curve.c.
References core_get(), and _ctx_t::ep8_is_twist.
ep8_curve_get_gen()
void ep8_curve_get_gen (ep8_t g)
Returns the generator of the group of points in the elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 271 of file relic_ep8_curve.c.
References core_get(), and ep8_copy().
Referenced by ep8_mul_gen(), and ep8_mul_sim_gen().
ep8_curve_get_a()
fp4_t * ep8_curve_get_a (void)
Returns the 'a' coefficient of the currently configured elliptic curve.
Returns
the 'a' coefficient of the elliptic curve.
Definition at line 275 of file relic_ep8_curve.c.
References core_get(), and _ctx_t::ep8_a.
Referenced by ep8_rhs().
ep8_curve_get_b()
fp4_t * ep8_curve_get_b (void)
Returns the 'b' coefficient of the currently configured elliptic curve.
Parameters
[out] b - the 'b' coefficient of the elliptic curve.
Definition at line 279 of file relic_ep8_curve.c.
References core_get(), and _ctx_t::ep8_b.
Referenced by ep8_rhs(), and pp_dbl_k48_projc().
ep8_curve_get_ord()
void ep8_curve_get_ord (bn_t n)
Returns the order of the group of points in the elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 283 of file relic_ep8_curve.c.
References bn_copy(), core_get(), _ctx_t::ep8_is_twist, _ctx_t::ep8_r, and ep_curve_get_ord().
Referenced by ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_gls_imp(), ep8_mul_monty(), ep8_mul_pre_basic(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_trick(), and ep8_rand().
ep8_curve_get_cof()
void ep8_curve_get_cof (bn_t h)
Returns the cofactor of the group order in the elliptic curve.
Parameters
[out] h - the returned cofactor.
Definition at line 292 of file relic_ep8_curve.c.
References bn_copy(), and core_get().
ep8_curve_get_tab()
ep8_t * ep8_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 298 of file relic_ep8_curve.c.
References core_get(), and _ctx_t::ep8_ptr.
Referenced by ep8_curve_set(), ep8_curve_set_twist(), ep8_mul_gen(), and ep8_mul_sim_gen().
ep8_curve_set_twist()
void ep8_curve_set_twist (int type)
Configures an elliptic curve by twisting the curve over the base prime field.
Parameters
- the type of twist (multiplicative or divisive)
Definition at line 308 of file relic_ep8_curve.c.
References ASSIGN, B48_P575, BASIC, bn_copy(), bn_free, bn_new, bn_null, core_get(), detect_opt(), _ctx_t::ep8_a, _ctx_t::ep8_b, ep8_copy(), ep8_curve_get_tab(), ep8_free, _ctx_t::ep8_g, _ctx_t::ep8_h, _ctx_t::ep8_is_twist, ep8_mul_pre, ep8_new, ep8_null, _ctx_t::ep8_opt_a, _ctx_t::ep8_opt_b, _ctx_t::ep8_r, ep_param_get(), ERR_CAUGHT, ERR_NO_VALID, fp8_copy(), fp8_free, fp8_inv(), fp8_new, fp8_null, _ctx_t::fp8_p1, fp8_set_dig(), fp8_zero(), fp_copy(), pc_core_calc(), RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_EP_MTYPE, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
Referenced by ep_param_set_any_pairf().
ep8_curve_set()
void ep8_curve_set (const fp8_t a, const fp8_t b, const ep8_t g, const bn_t r, const bn_t h)
Configures an elliptic curve over an octic extension by its coefficients.
Parameters
[in] a - the 'a' coefficient of the curve.
[in] b - the 'b' coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
Definition at line 392 of file relic_ep8_curve.c.
References bn_copy(), core_get(), _ctx_t::ep8_a, _ctx_t::ep8_b, ep8_curve_get_tab(), _ctx_t::ep8_g, _ctx_t::ep8_h, _ctx_t::ep8_is_twist, ep8_mul_pre, ep8_norm(), _ctx_t::ep8_r, and fp8_copy().