RELIC: src/pp/relic_pp_add_k16.c File Reference
relic_pp_add_k16.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
#include "relic_util.h"
Functions
void pp_add_k16_basic (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_add_k16_projc_basic (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_add_k16_projc_lazyr (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
void pp_add_lit_k16 (fp16_t l, ep_t r, const ep_t p, const ep4_t q)
Detailed Description
Implementation of Miller addition for curves of embedding degree 16.
Definition in file relic_pp_add_k16.c.
Function Documentation
pp_add_k16_basic()
void pp_add_k16_basic (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_add_k16.c.
References ep4_add_slp_basic(), ep4_copy(), ep4_curve_is_twist(), ep4_free, ep4_new, ep4_null, ERR_CAUGHT, fp4_free, fp4_mul, fp4_new, fp4_null, fp4_sub(), fp_copy(), fp_mul, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k16_projc_basic()
void pp_add_k16_projc_basic (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 87 of file relic_pp_add_k16.c.
References ep4_curve_is_twist(), ERR_CAUGHT, fp4_add(), fp4_copy(), fp4_dbl(), fp4_free, fp4_mul, fp4_new, fp4_null, fp4_sqr, fp4_sub(), fp_mul, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k16_projc_lazyr()
void pp_add_k16_projc_lazyr (fp16_t l, ep4_t r, const ep4_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 16 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 184 of file relic_pp_add_k16.c.
References ep4_curve_is_twist(), ERR_CAUGHT, fp4_add(), fp4_copy(), fp4_dbl(), fp4_free, fp4_mul, fp4_new, fp4_null, fp4_sqr, fp4_sub(), fp_mul, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_lit_k16()
void pp_add_lit_k16 (fp16_t l, ep_t r, const ep_t p, const ep4_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 16 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 281 of file relic_pp_add_k16.c.
References ep4_curve_is_twist(), ERR_CAUGHT, fp4_neg(), fp_add, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_lit_k16().