RELIC: src/pp/relic_pp_map_k24.c File Reference
relic_pp_map_k24.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_mil_k24 (fp24_t r, ep4_t *t, ep4_t *q, ep_t *p, int m, bn_t a)
void pp_map_k24 (fp24_t r, const ep_t p, const ep4_t q)
void pp_map_sim_k24 (fp24_t r, const ep_t *p, const ep4_t *q, int m)
Detailed Description
Implementation of pairing computation for curves with embedding degree 24.
Definition in file relic_pp_map_k24.c.
Function Documentation
pp_mil_k24()
static void pp_mil_k24 (fp24_t r, ep4_t * t, ep4_t * q, ep_t * p, int m, bn_t a) static
Compute the Miller loop for pairings of type G_2 x G_1 over the bits of a given parameter represented in sparse form.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] q - the vector of first arguments in affine coordinates.
[in] p - the vector of second arguments in affine coordinates.
[in] n - the number of pairings to evaluate.
[in] a - the loop parameter.
Definition at line 51 of file relic_pp_map_k24.c.
References bn_bits(), bn_rec_naf(), ep4_copy(), ep4_free, ep4_neg(), ep4_new, ep4_null, ep_free, ep_neg(), ep_new, ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp24_free, fp24_mul_dxs(), fp24_new, fp24_null, fp24_sqr, fp24_zero(), fp_add, fp_neg, pp_add_k24, pp_dbl_k24, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by pp_map_k24(), and pp_map_sim_k24().
pp_map_k24()
void pp_map_k24 (fp24_t r, const ep_t p, const ep4_t q)
Computes the Optimal Ate pairing of two points in a parameterized elliptic curve with embedding degree 24.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 142 of file relic_pp_map_k24.c.
References bn_free, bn_new, bn_null, bn_sign(), ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, EP_B24, ep_curve_is_pairf(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp24_inv_cyc(), fp24_set_dig(), fp_prime_get_par(), pp_exp_k24(), pp_mil_k24(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_sim_k24()
void pp_map_sim_k24 (fp24_t r, const ep_t * p, const ep4_t * q, int m)
Computes the optimal ate multi-pairing in a parameterized elliptic curve with embedding degree 24.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 188 of file relic_pp_map_k24.c.
References bn_free, bn_new, bn_null, bn_sign(), ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, EP_B24, ep_curve_is_pairf(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp24_inv_cyc(), fp24_set_dig(), fp_prime_get_par(), pp_exp_k24(), pp_mil_k24(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.