RELIC: src/cp/relic_cp_cls.c File Reference
relic_cp_cls.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_cls_gen (bn_t r, bn_t s, g2_t x, g2_t y)
int cp_cls_sig (g1_t a, g1_t b, g1_t c, uint8_t *msg, int len, bn_t r, bn_t s)
int cp_cls_ver (g1_t a, g1_t b, g1_t c, uint8_t *msg, int len, g2_t x, g2_t y)
int cp_cli_gen (bn_t t, bn_t u, bn_t v, g2_t x, g2_t y, g2_t z)
int cp_cli_sig (g1_t a, g1_t A, g1_t b, g1_t B, g1_t c, uint8_t *msg, int len, bn_t r, bn_t t, bn_t u, bn_t v)
int cp_cli_ver (g1_t a, g1_t A, g1_t b, g1_t B, g1_t c, uint8_t *msg, int len, bn_t r, g2_t x, g2_t y, g2_t z)
int cp_clb_gen (bn_t t, bn_t u, bn_t v[], g2_t x, g2_t y, g2_t z[], int l)
int cp_clb_sig (g1_t a, g1_t A[], g1_t b, g1_t B[], g1_t c, uint8_t *msgs[], int lens[], bn_t t, bn_t u, bn_t v[], int l)
int cp_clb_ver (g1_t a, g1_t A[], g1_t b, g1_t B[], g1_t c, uint8_t *msgs[], int lens[], g2_t x, g2_t y, g2_t z[], int l)
Detailed Description
Implementation of the Camenisch-Lysyanskaya signature protocols.
Definition in file relic_cp_cls.c.
Function Documentation
cp_cls_gen()
int cp_cls_gen (bn_t u, bn_t v, g2_t x, g2_t y)
Generates a key pair for the Camenisch-Lysyanskaya simple signature (CLS) protocol.
Parameters
[out] u - the first part of the private key.
[out] v - the second part of the private key.
[out] x - the first part of the public key.
[out] y - the second part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_cls.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, FINALLY, g2_get_ord, g2_mul_gen, result, RLC_ERR, RLC_OK, and TRY.
cp_cls_sig()
int cp_cls_sig (g1_t a, g1_t b, g1_t c, uint8_t * msg, int len, bn_t u, bn_t v)
Signs a message using the CLS protocol.
Parameters
[out] a - the first part of the signature.
[out] b - the second part of the signature.
[out] c - the third part of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] u - the first part of the private key.
[in] v - the second part of the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 62 of file relic_cp_cls.c.
References bn_add(), bn_free(), bn_mod, bn_null, bn_read_bin(), CATCH_ANY, FINALLY, g1_get_ord, g1_mul, g1_rand, result, RLC_ERR, RLC_OK, and TRY.
cp_cls_ver()
int cp_cls_ver (g1_t a, g1_t b, g1_t c, uint8_t * msg, int len, g2_t x, g2_t y)
Verifies a signature using the CLS protocol.
Parameters
[in] a - the first part of the signature.
[in] b - the second part of the signature.
[in] c - the third part of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] u - the first part of the public key.
[in] v - the second part of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 98 of file relic_cp_cls.c.
References bn_free(), bn_mod, bn_null, bn_read_bin(), CATCH_ANY, ERR_CAUGHT, FINALLY, g1_add, g1_copy, g1_free, g1_get_ord, g1_is_infty, g1_mul, g1_new, g1_norm, g1_null, g2_copy, g2_free, g2_get_gen, g2_neg, g2_new, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_map_sim, result, THROW, and TRY.
cp_cli_gen()
int cp_cli_gen (bn_t t, bn_t u, bn_t v, g2_t x, g2_t y, g2_t z)
Generates a key pair for the Camenisch-Lysyanskaya message-independent (CLI) signature protocol.
Parameters
[out] t - the first part of the private key.
[out] u - the second part of the private key.
[out] v - the third part of the private key.
[out] x - the first part of the public key.
[out] y - the second part of the public key.
[out] z - the third part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 166 of file relic_cp_cls.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, FINALLY, g2_get_ord, g2_mul_gen, result, RLC_ERR, RLC_OK, and TRY.
cp_cli_sig()
int cp_cli_sig (g1_t a, g1_t A, g1_t b, g1_t B, g1_t c, uint8_t * msg, int len, bn_t r, bn_t t, bn_t u, bn_t v)
Signs a message using the CLI protocol.
Parameters
[out] a - one of the components of the signature.
[out] A - one of the components of the signature.
[out] b - one of the components of the signature.
[out] B - one of the components of the signature.
[out] c - one of the components of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] r - the per-message randomness.
[in] t - the first part of the private key.
[in] u - the second part of the private key.
[in] v - the third part of the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 192 of file relic_cp_cls.c.
References bn_add(), bn_free(), bn_mod, bn_null, bn_read_bin(), CATCH_ANY, FINALLY, g1_add, g1_get_ord, g1_mul, g1_norm, g1_rand, result, RLC_ERR, RLC_OK, and TRY.
cp_cli_ver()
int cp_cli_ver (g1_t a, g1_t A, g1_t b, g1_t B, g1_t c, uint8_t * msg, int len, bn_t r, g2_t x, g2_t y, g2_t z)
Verifies a message signed using the CLI protocol.
Parameters
[in] a - one of the components of the signature.
[in] A - one of the components of the signature.
[in] b - one of the components of the signature.
[in] B - one of the components of the signature.
[in] c - one of the components of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] r - the per-message randomness.
[in] x - the first part of the public key.
[in] y - the second part of the public key.
[in] z - the third part of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 240 of file relic_cp_cls.c.
References bn_free(), bn_mod, bn_null, bn_read_bin(), CATCH_ANY, ERR_CAUGHT, FINALLY, g1_add, g1_copy, g1_free, g1_get_ord, g1_is_infty, g1_mul, g1_new, g1_norm, g1_null, g2_copy, g2_free, g2_get_gen, g2_neg, g2_new, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_map_sim, result, THROW, and TRY.
cp_clb_gen()
int cp_clb_gen (bn_t t, bn_t u, bn_t v[], g2_t x, g2_t y, g2_t z[], int l)
Generates a key pair for the Camenisch-Lysyanskaya message-block (CLB) signature protocol.
Parameters
[out] t - the first part of the private key.
[out] u - the second part of the private key.
[out] v - the remaining (l - 1) parts of the private key.
[out] x - the first part of the public key.
[out] y - the second part of the public key.
[out] z - the remaining (l - 1) parts of the public key.
[in] l - the number of messages to sign.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 328 of file relic_cp_cls.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, FINALLY, g2_get_ord, g2_mul_gen, result, RLC_ERR, RLC_OK, and TRY.
cp_clb_sig()
int cp_clb_sig (g1_t a, g1_t A[], g1_t b, g1_t B[], g1_t c, uint8_t * msgs[], int lens[], bn_t t, bn_t u, bn_t v[], int l)
Signs a block of messages using the CLB protocol.
Parameters
[out] a - the first component of the signature.
[out] A - the (l - 1) next components of the signature.
[out] b - the next component of the signature.
[out] B - the (l - 1) next components of the signature.
[out] c - the last component of the signature.
[in] msgs - the l messages to sign.
[in] lens - the l message lengths in bytes.
[in] t - the first part of the private key.
[in] u - the second part of the private key.
[in] v - the remaining (l - 1) parts of the private key.
[in] l - the number of messages to sign.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 356 of file relic_cp_cls.c.
References bn_add(), bn_free(), bn_mod, bn_null, bn_read_bin(), CATCH_ANY, FINALLY, g1_add, g1_get_ord, g1_mul, g1_norm, g1_rand, result, RLC_ERR, RLC_OK, and TRY.
cp_clb_ver()
int cp_clb_ver (g1_t a, g1_t A[], g1_t b, g1_t B[], g1_t c, uint8_t * msgs[], int lens[], g2_t x, g2_t y, g2_t z[], int l)
Verifies a block of messages signed using the CLB protocol.
Parameters
[out] a - the first component of the signature.
[out] A - the (l - 1) next components of the signature.
[out] b - the next component of the signature.
[out] B - the (l - 1) next components of the signature.
[out] c - the last component of the signature.
[in] msgs - the l messages to sign.
[in] lens - the l message lengths in bytes.
[in] x - the first part of the public key.
[in] y - the second part of the public key.
[in] z - the remaining (l - 1) parts of the public key.
[in] l - the number of messages to sign.
Returns
a boolean value indicating the verification result.
Definition at line 408 of file relic_cp_cls.c.
References bn_free(), bn_mod, bn_null, bn_read_bin(), CATCH_ANY, ERR_CAUGHT, FINALLY, g1_add, g1_copy, g1_free, g1_get_ord, g1_is_infty, g1_mul, g1_new, g1_norm, g1_null, g2_copy, g2_free, g2_get_gen, g2_neg, g2_new, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_map_sim, result, THROW, and TRY.