RELIC: src/fp/relic_fp_smb.c File Reference
relic_fp_smb.c File Reference
Prime field arithmetic
#include "relic_core.h"
#include "relic_bn_low.h"
#include "relic_fp_low.h"
Macros
#define RLC_LSH(H, L, I)
Functions
static dig_t porninstep (dis_t m[4], const dig_t f[2], const dig_t g[2], dig_t k, size_t s)
static dis_t jumpdivstep (dis_t m[4], dig_t *k, dis_t delta, dis_t y, dis_t x, int s)
int fp_smb_basic (const fp_t a)
int fp_smb_binar (const fp_t a)
int fp_smb_divst (const fp_t a)
int fp_smb_jmpds (const fp_t a)
int fp_smb_lower (const fp_t a)
Detailed Description
Implementation of Legendre and Jacobi symbols for prime fields.
Definition in file relic_fp_smb.c.
Macro Definition Documentation
RLC_LSH
#define RLC_LSH (H, L, I)
Value:
        (H << I) | (L & -(I != 0)) >> ((RLC_DIG - I) & (RLC_DIG - 1))
Definition at line 273 of file relic_fp_smb.c.
Referenced by fp_smb_binar().
Function Documentation
porninstep()
static dig_t porninstep (dis_t m[4], const dig_t f[2], const dig_t g[2], dig_t k, size_t s) static
Approach heavily inpired in the blst implementation of the algorithm.
Definition at line 44 of file relic_fp_smb.c.
References RLC_DIG.
Referenced by fp_smb_binar().
jumpdivstep()
static dis_t jumpdivstep (dis_t m[4], dig_t * k, dis_t delta, dis_t y, dis_t x, int s) static
Definition at line 165 of file relic_fp_smb.c.
References RLC_DIG, and RLC_SIGN.
Referenced by fp_smb_jmpds().
fp_smb_basic()
int fp_smb_basic (const fp_t a)
Computes Legendre symbol of a prime field element using exponentiation.
Parameters
[in] a - the prime field element to compute.
Returns
the result.
Definition at line 239 of file relic_fp_smb.c.
References bn_free, bn_hlv(), bn_new, bn_null, bn_sub_dig(), dv_copy(), ERR_CAUGHT, fp_cmp_dig(), fp_exp, fp_neg, fp_prime_get(), RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_POS, RLC_SEL, RLC_THROW, and RLC_TRY.
fp_smb_binar()
int fp_smb_binar (const fp_t a)
Computes Legendre symbol of a prime field element using the binary method.
Parameters
[in] a - the prime field element to compute.
Returns
the result.
Definition at line 276 of file relic_fp_smb.c.
References bn_addn_low(), bn_muls_low(), bn_negs_low(), bn_rshb_low(), dv_copy(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_copy(), fp_is_zero(), fp_prime_get(), fp_rdcn_low(), porninstep(), RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FP_DIGS, RLC_LSH, RLC_POS, RLC_SIGN, RLC_THROW, RLC_TRY, and util_bits_dig().
fp_smb_divst()
int fp_smb_divst (const fp_t a)
Computes Legendre symbol of a prime field element using the constant-time division step approach by Bernstein and Bo-Yin Yang.
Parameters
[in] a - the prime field element to compute.
Returns
the result.
Definition at line 364 of file relic_fp_smb.c.
References bn_add_dig(), bn_addn_low(), bn_free, bn_lsh(), bn_negs_low(), bn_new, bn_null, bn_set_dig(), dv_cmp(), dv_cmp_sec(), dv_copy(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_add1_low(), fp_copy(), fp_copy_sec(), fp_is_zero(), FP_PRIME, fp_prime_get(), fp_rdcn_low(), fp_rsh1_low(), fp_subn_low(), fp_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_LT, RLC_POS, RLC_SEL, RLC_THROW, and RLC_TRY.
fp_smb_jmpds()
int fp_smb_jmpds (const fp_t a)
Computes Legendre symbol of a prime field element using the constant-time jump division step approach by Bernstein and Bo-Yin Yang.
Parameters
[in] a - the prime field element to compute.
Returns
the result.
Definition at line 470 of file relic_fp_smb.c.
References bn_addn_low(), bn_muls_low(), bn_negs_low(), bn_rshs_low(), dv_cmp_sec(), dv_copy(), dv_free, dv_new, dv_null, dv_zero(), ERR_CAUGHT, fp_copy(), FP_PRIME, fp_prime_get(), fp_rdcn_low(), fp_zero(), jumpdivstep(), RLC_CATCH_ANY, RLC_DIG, RLC_EQ, RLC_FINALLY, RLC_FP_DIGS, RLC_SEL, RLC_SIGN, RLC_THROW, and RLC_TRY.
fp_smb_lower()
int fp_smb_lower (const fp_t a)
Computes Legendre symbol a prime field element using a direct call to the lower layer.
Parameters
[in] a - the prime field element to invert.
Returns
the result.
Definition at line 574 of file relic_fp_smb.c.
References fp_smbm_low().