RELIC: src/eb/relic_eb_pck.c File Reference
relic_eb_pck.c File Reference
Elliptic curves over binary fields
#include "string.h"
#include "relic_core.h"
#include "relic_eb.h"
Functions
void eb_pck (eb_t r, const eb_t p)
int eb_upk (eb_t r, const eb_t p)
Detailed Description
Implementation of point compression on binary elliptic curves.
Definition in file relic_eb_pck.c.
Function Documentation
eb_pck()
void eb_pck (eb_t r, const eb_t p)
Compresses a point.
Parameters
[out] r - the result.
[in] p - the point to compress.
Definition at line 41 of file relic_eb_pck.c.
References fb_copy(), fb_get_bit(), fb_set_dig(), eb_st::norm, eb_st::x, eb_st::y, and eb_st::z.
Referenced by eb_write_bin().
eb_upk()
int eb_upk (eb_t r, const eb_t p)
Decompresses a point.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
if the decompression was successful
Definition at line 55 of file relic_eb_pck.c.
References CATCH_ANY, eb_rhs(), ERR_CAUGHT, fb_add_dig(), fb_copy(), fb_get_bit(), fb_null, fb_set_dig(), FINALLY, eb_st::norm, result, THROW, TRY, eb_st::x, eb_st::y, and eb_st::z.
Referenced by eb_read_bin().