RELIC: src/epx/relic_ep3_frb.c File Reference
relic_ep3_frb.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
void ep3_frb (ep3_t r, const ep3_t p, int i)
Detailed Description
Implementation of frobenius action on prime elliptic curves over a cubic extension field.
Definition in file relic_ep3_frb.c.
Function Documentation
ep3_frb()
void ep3_frb (ep3_t r, const ep3_t p, int i)
Computes a power of the Gailbraith-Lin-Scott homomorphism of a point represented in affine coordinates on a twisted elliptic curve over a cubic exension. That is, Psi^i(P) = Twist(P)(Frob^i(unTwist(P)). On the trace-zero group of a cubic twist, consists of a power of the Frobenius map of a point represented in affine coordinates in an elliptic curve over a cubic exension. Computes Frob^i(P) = (p^i)P.
Parameters
[out] r - the result in affine coordinates.
[in] p - a point in affine coordinates.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_ep3_frb.c.
References core_get(), ep3_copy(), _ctx_t::ep3_frb, fp3_frb(), and fp3_mul.
Referenced by ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_sim_lot(), ep3_psi(), pp_fin_k18_oatep(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), and pp_map_weilp_k18().