RELIC: src/bn/relic_bn_mul.c File Reference
relic_bn_mul.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
#include "relic_bn_low.h"
Functions
static void bn_mul_karat_imp (bn_t c, const bn_t a, const bn_t b, int level)
void bn_mul_dig (bn_t c, const bn_t a, dig_t b)
void bn_mul_basic (bn_t c, const bn_t a, const bn_t b)
void bn_mul_comba (bn_t c, const bn_t a, const bn_t b)
void bn_mul_karat (bn_t c, const bn_t a, const bn_t b)
Detailed Description
Implementation of the multiple precision multiplication functions.
Version
Id
relic_bn_mul.c 1665 2013-12-28 03:06:13Z dfaranha
Definition in file relic_bn_mul.c.
Function Documentation
static void bn_mul_karat_imp (bn_t c, const bn_t a, const bn_t b, int level) static
Multiplies two multiple precision integers using recursive Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer.
[in] b - the second multiple precision integer.
[in] level - the number of Karatsuba steps to apply.
Definition at line 50 of file relic_bn_mul.c.
References bn_add(), bn_copy(), BN_DIGIT, bn_free, bn_lsh(), bn_mul_basic(), bn_mul_comba(), bn_new, bn_null, bn_sub(), bn_trim(), CATCH_ANY, ERR_CAUGHT, FINALLY, MIN, THROW, and TRY.
Referenced by bn_mul_karat().
void bn_mul_dig (bn_t c, const bn_t a, dig_t b)
Multiplies a multiple precision integer by a digit. Computes c = a * b.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to multiply.
[in] b - the digit to multiply.
Definition at line 177 of file relic_bn_mul.c.
References bn_grow(), bn_mul1_low(), and bn_trim().
Referenced by bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_lehme(), bn_gen_prime_stron(), bn_mod_pmers(), bn_read_str(), cp_bdpe_gen(), fp_param_set(), and pp_map_oatep_k12().
void bn_mul_basic (bn_t c, const bn_t a, const bn_t b)
Multiplies two multiple precision integers using Schoolbook multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to multiply.
[in] b - the second multiple precision integer to multiply.
Definition at line 193 of file relic_bn_mul.c.
References bn_copy(), bn_free, bn_mula_low(), bn_new_size, bn_null, bn_trim(), bn_zero(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by bn_mul_karat_imp().
void bn_mul_comba (bn_t c, const bn_t a, const bn_t b)
Multiplies two multiple precision integers using Comba multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to multiply.
[in] b - the second multiple precision integer to multiply.
Definition at line 228 of file relic_bn_mul.c.
References bn_copy(), bn_free, bn_muld_low(), bn_muln_low(), bn_new_size, bn_null, bn_trim(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by bn_mul_karat_imp(), and bn_sqr_karat_imp().
void bn_mul_karat (bn_t c, const bn_t a, const bn_t b)
Multiplies two multiple precision integers using Karatsuba multiplication.
Parameters
[out] c - the result.
[in] a - the first multiple precision integer to multiply.
[in] b - the second multiple precision integer to multiply.
Definition at line 269 of file relic_bn_mul.c.
References BN_KARAT, and bn_mul_karat_imp().