RELIC: include/relic_mpc.h File Reference
relic_mpc.h File Reference
Multiple precision integer arithmetic
#include "relic_conf.h"
#include "relic_pc.h"
Data Structures
struct mt_st
struct _pt_st
Macros
#define mt_null(A)
#define mt_new(A)
#define mt_free(A)
#define pt_null(A)
#define pt_new(A)
#define pt_free(A)
Typedefs
typedef mt_st mt_t[1]
typedef struct _pt_st pt_st
typedef pt_st pt_t[1]
Functions
void mpc_mt_gen (mt_t tri[2], const bn_t order)
void mpc_mt_lcl (bn_t d, bn_t e, const bn_t x, const bn_t y, const bn_t n, const mt_t tri)
void mpc_mt_bct (bn_t d[2], bn_t e[2], bn_t n)
void mpc_mt_mul (bn_t r, const bn_t d, const bn_t e, const bn_t n, const mt_t tri, int party)
int mpc_sss_gen (bn_t *x, bn_t *y, const bn_t key, const bn_t order, size_t k, size_t n)
int mpc_sss_key (bn_t key, const bn_t *x, const bn_t *y, const bn_t order, size_t k)
void g1_mul_lcl (bn_t d, g1_t q, const bn_t x, const g1_t p, const mt_t tri)
void g1_mul_bct (bn_t d[2], g1_t q[2])
void g1_mul_mpc (g1_t r, const bn_t d, const g1_t q, const mt_t tri, int party)
void g2_mul_lcl (bn_t d, g2_t q, const bn_t x, const g2_t p, const mt_t tri)
void g2_mul_bct (bn_t d[2], g2_t q[2])
void g2_mul_mpc (g2_t r, const bn_t d, const g2_t q, const mt_t tri, int party)
void gt_exp_lcl (bn_t d, gt_t q, const bn_t x, const gt_t p, const mt_t tri)
void gt_exp_bct (bn_t d[2], gt_t q[2])
void gt_exp_mpc (gt_t r, const bn_t d, const gt_t q, const mt_t tri, int party)
void pc_map_tri (pt_t t[2])
void pc_map_lcl (g1_t d, g2_t e, const g1_t p, const g2_t q, const pt_t t)
void pc_map_bct (g1_t d[2], g2_t e[2])
void pc_map_mpc (gt_t r, const g1_t d1, const g2_t d2, const pt_t triple, int party)
Detailed Description
Interface of the module for multi-party computation.
Definition in file relic_mpc.h.
Macro Definition Documentation
mt_null
#define mt_null (A)
Value:
/* empty */
Initializes a multiplication triple.
Parameters
[out] A - the multiple precision integer to initialize.
Definition at line 108 of file relic_mpc.h.
Referenced by pc_map_tri().
mt_new
#define mt_new (A)
Value:
    bn_new((A)->a);                                                         \
    bn_new((A)->b);                                                         \
    bn_new((A)->c);                                                         \
Calls a function to allocate and initialize a multiple precision integer.
Parameters
[in,out] A - the multiple precision integer to initialize.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 133 of file relic_mpc.h.
Referenced by pc_map_tri().
mt_free
#define mt_free (A)
Value:
/* empty */                                     \
Calls a function to clean and free a multiple precision integer.
Parameters
[in,out] A - the multiple precision integer to free.
Definition at line 156 of file relic_mpc.h.
Referenced by pc_map_tri().
pt_null
#define pt_null (A)
Value:
/* empty */
Initializes a pairing triple with a null value.
Parameters
[out] A - the key pair to initialize.
Definition at line 166 of file relic_mpc.h.
pt_new
#define pt_new (A)
Value:
/* empty */
Calls a function to allocate and initialize a pairing triple.
Parameters
[out] A - the new pairing triple.
Definition at line 187 of file relic_mpc.h.
pt_free
#define pt_free (A)
Value:
/* empty */
Calls a function to clean and free a pairing triple.
Parameters
[out] A - the pairing triple to clean and free.
Definition at line 207 of file relic_mpc.h.
Typedef Documentation
mt_t
typedef mt_st mt_t[1]
Pointer to a multiplication triple structure.
Definition at line 72 of file relic_mpc.h.
pt_st
typedef struct _pt_st pt_st
Represents a pairing triple.
pt_t
typedef pt_st pt_t[1]
Pointer to a pairing triple.
Definition at line 93 of file relic_mpc.h.
Function Documentation
mpc_mt_gen()
void mpc_mt_gen (mt_t tri[2], const bn_t order)
Generates a pair of multiplication triples for use in MPC protocols such that [a] * [b] = [c] modulo a certain order.
Parameters
[out] tri - the multiplication triples to generate.
[in] order - the order.
Definition at line 41 of file relic_mpc_mt.c.
References bn_add(), bn_mod, bn_mul, bn_rand_mod(), bn_sign(), and bn_sub().
Referenced by pc_map_tri().
mpc_mt_lcl()
void mpc_mt_lcl (bn_t d, bn_t e, const bn_t x, const bn_t y, const bn_t n, const mt_t tri)
Performs the local work for a MPC multiplication.
Parameters
[out] d - the masked first multiplication operand.
[out] e - the masked second multiplication operand.
[in] x - the first multiplication operand.
[in] y - the second multiplication operand.
[in] n - the order.
[in] tri - the multiplication triple.
Definition at line 61 of file relic_mpc_mt.c.
References bn_add(), bn_free, bn_mod, bn_new, bn_null, bn_sign(), bn_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by cp_mpss_sig().
mpc_mt_bct()
void mpc_mt_bct (bn_t d[2], bn_t e[2], bn_t n)
Opens the public values in an MPC multiplication.
Parameters
[out] d - the first public value.
[out] e - the second public value.
[in] n - the order.
Definition at line 92 of file relic_mpc_mt.c.
References bn_add(), bn_copy(), and bn_mod.
Referenced by cp_mpss_sig().
mpc_mt_mul()
void mpc_mt_mul (bn_t r, const bn_t d, const bn_t e, const bn_t n, const mt_t tri, int party)
Finishes an MPC multiplication by computing the multiplication result.
Parameters
[out] r - the share of the multiplication result.
[in] d - the first public value.
[in] e - the second public value.
[in] n - the order.
[in] tri - the multiplication triple.
[in] party - the party performing the computation.
Definition at line 102 of file relic_mpc_mt.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_sign(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by cp_mpss_sig().
mpc_sss_gen()
int mpc_sss_gen (bn_t * x, bn_t * y, const bn_t key, const bn_t order, size_t k, size_t n)
Generates shares (x, y) of a secret key using a (k, n)-threshold Shamir's Secret Sharing over a given finite field.
Parameters
[out] x - the indexes of the parties receiving shares.
[out] y - the evaluation points.
[in] key - the secret to share.
[in] order - the order of the finite field.
[in] k - the threshold.
[in] n - the number of parties.
Definition at line 40 of file relic_mpc_sss.c.
References bn_copy(), bn_evl(), bn_free, bn_new, bn_null, bn_rand_mod(), bn_set_dig(), ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, and RLC_TRY.
mpc_sss_key()
int mpc_sss_key (bn_t key, const bn_t * x, const bn_t * y, const bn_t order, size_t k)
Recovers a secret key using a k shares (x, y) of over a given finite field.
Parameters
[in] key - the recovered secret.
[in] x - the indexes of the parties contributing shares.
[in] y - the evaluation points.
[in] order - the order of the finite field.
[in] k - the threshold.
Definition at line 81 of file relic_mpc_sss.c.
References bn_add(), bn_free, bn_mod, bn_mod_inv_sim(), bn_mul, bn_new, bn_null, bn_set_dig(), bn_sub(), ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, and RLC_TRY.
g1_mul_lcl()
void g1_mul_lcl (bn_t d, g1_t q, const bn_t x, const g1_t p, const mt_t tri)
Performs the local work for a MPC scalar multiplication in G1.
Parameters
[out] d - the share of the masked scalar.
[out] q - the share of the masked point to multiply.
[in] x - the scalar.
[in] p - the point to multiply.
[in] tri - the multiplication triple.
Definition at line 40 of file relic_mpc_pc.c.
References bn_add(), bn_free, bn_mod, bn_new, bn_null, bn_sign(), bn_sub(), ERR_CAUGHT, g1_copy, g1_get_ord, g1_norm, g1_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
g1_mul_bct()
void g1_mul_bct (bn_t d[2], g1_t q[2])
Opens the public values in an MPC scalar multiplication in G1.
Parameters
[out] d - the first public value (masked scalar).
[out] q - the second public value (masked point).
[in] n - the order.
Definition at line 70 of file relic_mpc_pc.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_new, bn_null, ERR_CAUGHT, g1_add, g1_copy, g1_get_ord, g1_norm, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
g1_mul_mpc()
void g1_mul_mpc (g1_t r, const bn_t d, const g1_t q, const mt_t tri, int party)
Finishes an MPC scalar multiplication in G1 by computing the result.
Parameters
[out] r - the share of the result.
[in] d - the first public value.
[in] q - the second public value.
[in] tri - the multiplication triple.
[in] party - the party performing the computation.
Definition at line 92 of file relic_mpc_pc.c.
References ERR_CAUGHT, g1_add, g1_copy, g1_free, g1_mul_sim, g1_new, g1_norm, g1_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
g2_mul_lcl()
void g2_mul_lcl (bn_t d, g2_t q, const bn_t x, const g2_t p, const mt_t tri)
Performs the local work for a MPC scalar multiplication in G2.
Parameters
[out] d - the share of the masked scalar.
[out] q - the share of the masked point to multiply.
[in] x - the scalar.
[in] p - the point to multiply.
[in] tri - the multiplication triple.
Definition at line 119 of file relic_mpc_pc.c.
References bn_add(), bn_free, bn_mod, bn_new, bn_null, bn_sign(), bn_sub(), ERR_CAUGHT, g2_copy, g2_get_ord, g2_norm, g2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
g2_mul_bct()
void g2_mul_bct (bn_t d[2], g2_t q[2])
Opens the public values in an MPC scalar multiplication in G2.
Parameters
[out] d - the first public value (masked scalar).
[out] q - the second public value (masked point).
[in] n - the order.
Definition at line 149 of file relic_mpc_pc.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_new, bn_null, ERR_CAUGHT, g2_add, g2_copy, g2_get_ord, g2_norm, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
g2_mul_mpc()
void g2_mul_mpc (g2_t r, const bn_t d, const g2_t q, const mt_t tri, int party)
Finishes an MPC scalar multiplication in G2 by computing the result.
Parameters
[out] r - the share of the result.
[in] d - the first public value.
[in] q - the second public value.
[in] tri - the multiplication triple.
[in] party - the party performing the computation.
Definition at line 171 of file relic_mpc_pc.c.
References ERR_CAUGHT, g2_add, g2_copy, g2_free, g2_mul_sim, g2_new, g2_norm, g2_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
gt_exp_lcl()
void gt_exp_lcl (bn_t d, gt_t q, const bn_t x, const gt_t p, const mt_t tri)
Performs the local work for a MPC scalar multiplication in G2.
Parameters
[out] d - the share of the masked scalar.
[out] q - the share of the masked point to multiply.
[in] x - the scalar.
[in] p - the point to multiply.
[in] tri - the multiplication triple.
Definition at line 198 of file relic_mpc_pc.c.
References bn_add(), bn_free, bn_mod, bn_new, bn_null, bn_sign(), bn_sub(), ERR_CAUGHT, gt_copy, gt_get_ord, gt_inv, gt_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by cp_mpsb_ver(), and cp_mpss_ver().
gt_exp_bct()
void gt_exp_bct (bn_t d[2], gt_t q[2])
Opens the public values in an MPC scalar multiplication in G2.
Parameters
[out] d - the first public value (masked scalar).
[out] q - the second public value (masked point).
[in] n - the order.
Definition at line 229 of file relic_mpc_pc.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_new, bn_null, ERR_CAUGHT, gt_copy, gt_get_ord, gt_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by cp_mpsb_ver(), and cp_mpss_ver().
gt_exp_mpc()
void gt_exp_mpc (gt_t r, const bn_t d, const gt_t q, const mt_t tri, int party)
Finishes an MPC scalar multiplication in G2 by computing the result.
Parameters
[out] r - the share of the result.
[in] d - the first public value.
[in] q - the second public value.
[in] tri - the multiplication triple.
[in] party - the party performing the computation.
Definition at line 250 of file relic_mpc_pc.c.
References ERR_CAUGHT, gt_copy, gt_exp_sim(), gt_free, gt_mul, gt_new, gt_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by cp_mpsb_ver(), and cp_mpss_ver().
pc_map_tri()
void pc_map_tri (pt_t t[2])
Generates a pairing triple.
Parameters
[out] t - the pairing triple to generate.
Definition at line 275 of file relic_mpc_pc.c.
References bn_free, bn_new, bn_null, ERR_CAUGHT, g1_get_ord, g1_mul_gen(), g2_mul_gen(), gt_exp_gen(), mpc_mt_gen(), mt_free, mt_new, mt_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pc_map_lcl()
void pc_map_lcl (g1_t d, g2_t e, const g1_t p, const g2_t q, const pt_t t)
Computes the public values from the pairing inputs and triple.
Parameters
[out] d - the share of the first public value.
[out] e - the share of the second public value.
[in] p - the share of the first pairnig argument.
[in] q - the share of the second pairing argument.
[in] t - the pairing triple.
Definition at line 305 of file relic_mpc_pc.c.
References g1_norm, g1_sub, g2_norm, and g2_sub.
pc_map_bct()
void pc_map_bct (g1_t d[2], g2_t e[2])
Broadcasts the public values for pairing computation.
Parameters
[out] d - the first set of public values.
[out] e - the second set of public values.
Definition at line 313 of file relic_mpc_pc.c.
References g1_add, g1_copy, g1_norm, g2_add, g2_copy, and g2_norm.
pc_map_mpc()
void pc_map_mpc (gt_t r, const g1_t d1, const g2_t d2, const pt_t triple, int party)
Computes a pairing using a pairing triple.
Parameters
[out] r - the pairing result.
[in] d1 - the first public value.
[in] d2 - the second public value.
[in] triple - the pairing triple.
[in] party - the number of the party executing the computation.
Definition at line 323 of file relic_mpc_pc.c.
References ERR_CAUGHT, g1_add, g1_copy, g1_free, g1_new, g1_norm, g1_null, g2_copy, g2_free, g2_new, g2_null, gt_free, gt_mul, gt_new, gt_null, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.