RELIC: include/relic_bc.h File Reference
relic_bc.h File Reference
Block ciphers
#include "relic_conf.h"
#include "relic_types.h"
#include "relic_label.h"
Macros
#define BC_LEN 16
Functions
int bc_aes_cbc_enc (uint8_t *out, int *out_len, uint8_t *in, int in_len, uint8_t *key, int key_len, uint8_t *iv)
int bc_aes_cbc_dec (uint8_t *out, int *out_len, uint8_t *in, int in_len, uint8_t *key, int key_len, uint8_t *iv)
Detailed Description
Interface of the module for encrypting with block ciphers.
Version
$Id$
Definition in file relic_bc.h.
Macro Definition Documentation
#define BC_LEN 16
Length in bytes of default block cipher length.
Definition at line 50 of file relic_bc.h.
Referenced by bc_aes_cbc_dec(), bc_aes_cbc_enc(), cp_ecies_dec(), and cp_ecies_enc().
Function Documentation
int bc_aes_cbc_enc (uint8_t * out, int * out_len, uint8_t * in, int in_len, uint8_t * key, int key_len, uint8_t * iv)
Encrypts with AES in CBC mode.
Parameters
[out] out - the resulting ciphertext.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the bytes to be encrypted.
[in] in_len - the number of bytes to encrypt.
[in] key - the key.
[in] key_len - the key size in bytes.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 43 of file relic_bc_aes.c.
References BC_LEN, cipherInit(), DIR_ENCRYPT, cipherInstance::IV, makeKey2(), MODE_CBC, padEncrypt(), STS_ERR, STS_OK, and TRUE.
Referenced by cp_ecies_enc().
int bc_aes_cbc_dec (uint8_t * out, int * out_len, uint8_t * in, int in_len, uint8_t * key, int key_len, uint8_t * iv)
Decrypts with AES in CBC mode.
Parameters
[out] out - the resulting plaintext.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the bytes to be decrypted.
[in] in_len - the number of bytes to decrypt.
[in] key - the key.
[in] key_len - the key size in bytes.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 66 of file relic_bc_aes.c.
References BC_LEN, cipherInit(), DIR_DECRYPT, cipherInstance::IV, makeKey2(), MODE_CBC, padDecrypt(), STS_ERR, STS_OK, and TRUE.
Referenced by cp_ecies_dec().