RELIC: src/mpc/relic_mpc_pc.c File Reference
relic_mpc_pc.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_mpc.h"
#include "relic_util.h"
Functions
void g1_mul_lcl (bn_t d, g1_t q, const bn_t x, const g1_t p, const mt_t tri)
void g1_mul_bct (bn_t d[2], g1_t q[2])
void g1_mul_mpc (g1_t r, const bn_t d, const g1_t q, const mt_t tri, int party)
void g2_mul_lcl (bn_t d, g2_t q, const bn_t x, const g2_t p, const mt_t tri)
void g2_mul_bct (bn_t d[2], g2_t q[2])
void g2_mul_mpc (g2_t r, const bn_t d, const g2_t q, const mt_t tri, int party)
void gt_exp_lcl (bn_t d, gt_t q, const bn_t x, const gt_t p, const mt_t tri)
void gt_exp_bct (bn_t d[2], gt_t q[2])
void gt_exp_mpc (gt_t r, const bn_t d, const gt_t q, const mt_t tri, int party)
void pc_map_tri (pt_t t[2])
void pc_map_lcl (g1_t d, g2_t e, const g1_t p, const g2_t q, const pt_t t)
void pc_map_bct (g1_t d[2], g2_t e[2])
void pc_map_mpc (gt_t r, const g1_t d1, const g2_t d2, const pt_t triple, int party)
Detailed Description
Implementation of pairing triples for MPC applications.
Definition in file relic_mpc_pc.c.
Function Documentation
g1_mul_lcl()
void g1_mul_lcl (bn_t d, g1_t q, const bn_t x, const g1_t p, const mt_t tri)
Performs the local work for a MPC scalar multiplication in G1.
Parameters
[out] d - the share of the masked scalar.
[out] q - the share of the masked point to multiply.
[in] x - the scalar.
[in] p - the point to multiply.
[in] tri - the multiplication triple.
Definition at line 40 of file relic_mpc_pc.c.
References bn_add(), bn_free, bn_mod, bn_new, bn_null, bn_sign(), bn_sub(), ERR_CAUGHT, g1_copy, g1_get_ord, g1_norm, g1_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
g1_mul_bct()
void g1_mul_bct (bn_t d[2], g1_t q[2])
Opens the public values in an MPC scalar multiplication in G1.
Parameters
[out] d - the first public value (masked scalar).
[out] q - the second public value (masked point).
[in] n - the order.
Definition at line 70 of file relic_mpc_pc.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_new, bn_null, ERR_CAUGHT, g1_add, g1_copy, g1_get_ord, g1_norm, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
g1_mul_mpc()
void g1_mul_mpc (g1_t r, const bn_t d, const g1_t q, const mt_t tri, int party)
Finishes an MPC scalar multiplication in G1 by computing the result.
Parameters
[out] r - the share of the result.
[in] d - the first public value.
[in] q - the second public value.
[in] tri - the multiplication triple.
[in] party - the party performing the computation.
Definition at line 92 of file relic_mpc_pc.c.
References ERR_CAUGHT, g1_add, g1_copy, g1_free, g1_mul_sim, g1_new, g1_norm, g1_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
g2_mul_lcl()
void g2_mul_lcl (bn_t d, g2_t q, const bn_t x, const g2_t p, const mt_t tri)
Performs the local work for a MPC scalar multiplication in G2.
Parameters
[out] d - the share of the masked scalar.
[out] q - the share of the masked point to multiply.
[in] x - the scalar.
[in] p - the point to multiply.
[in] tri - the multiplication triple.
Definition at line 119 of file relic_mpc_pc.c.
References bn_add(), bn_free, bn_mod, bn_new, bn_null, bn_sign(), bn_sub(), ERR_CAUGHT, g2_copy, g2_get_ord, g2_norm, g2_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
g2_mul_bct()
void g2_mul_bct (bn_t d[2], g2_t q[2])
Opens the public values in an MPC scalar multiplication in G2.
Parameters
[out] d - the first public value (masked scalar).
[out] q - the second public value (masked point).
[in] n - the order.
Definition at line 149 of file relic_mpc_pc.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_new, bn_null, ERR_CAUGHT, g2_add, g2_copy, g2_get_ord, g2_norm, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
g2_mul_mpc()
void g2_mul_mpc (g2_t r, const bn_t d, const g2_t q, const mt_t tri, int party)
Finishes an MPC scalar multiplication in G2 by computing the result.
Parameters
[out] r - the share of the result.
[in] d - the first public value.
[in] q - the second public value.
[in] tri - the multiplication triple.
[in] party - the party performing the computation.
Definition at line 171 of file relic_mpc_pc.c.
References ERR_CAUGHT, g2_add, g2_copy, g2_free, g2_mul_sim, g2_new, g2_norm, g2_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
gt_exp_lcl()
void gt_exp_lcl (bn_t d, gt_t q, const bn_t x, const gt_t p, const mt_t tri)
Performs the local work for a MPC scalar multiplication in G2.
Parameters
[out] d - the share of the masked scalar.
[out] q - the share of the masked point to multiply.
[in] x - the scalar.
[in] p - the point to multiply.
[in] tri - the multiplication triple.
Definition at line 198 of file relic_mpc_pc.c.
References bn_add(), bn_free, bn_mod, bn_new, bn_null, bn_sign(), bn_sub(), ERR_CAUGHT, gt_copy, gt_get_ord, gt_inv, gt_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by cp_mpsb_ver(), and cp_mpss_ver().
gt_exp_bct()
void gt_exp_bct (bn_t d[2], gt_t q[2])
Opens the public values in an MPC scalar multiplication in G2.
Parameters
[out] d - the first public value (masked scalar).
[out] q - the second public value (masked point).
[in] n - the order.
Definition at line 229 of file relic_mpc_pc.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_new, bn_null, ERR_CAUGHT, gt_copy, gt_get_ord, gt_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by cp_mpsb_ver(), and cp_mpss_ver().
gt_exp_mpc()
void gt_exp_mpc (gt_t r, const bn_t d, const gt_t q, const mt_t tri, int party)
Finishes an MPC scalar multiplication in G2 by computing the result.
Parameters
[out] r - the share of the result.
[in] d - the first public value.
[in] q - the second public value.
[in] tri - the multiplication triple.
[in] party - the party performing the computation.
Definition at line 250 of file relic_mpc_pc.c.
References ERR_CAUGHT, gt_copy, gt_exp_sim(), gt_free, gt_mul, gt_new, gt_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by cp_mpsb_ver(), and cp_mpss_ver().
pc_map_tri()
void pc_map_tri (pt_t t[2])
Generates a pairing triple.
Parameters
[out] t - the pairing triple to generate.
Definition at line 275 of file relic_mpc_pc.c.
References bn_free, bn_new, bn_null, ERR_CAUGHT, g1_get_ord, g1_mul_gen(), g2_mul_gen(), gt_exp_gen(), mpc_mt_gen(), mt_free, mt_new, mt_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pc_map_lcl()
void pc_map_lcl (g1_t d, g2_t e, const g1_t p, const g2_t q, const pt_t t)
Computes the public values from the pairing inputs and triple.
Parameters
[out] d - the share of the first public value.
[out] e - the share of the second public value.
[in] p - the share of the first pairnig argument.
[in] q - the share of the second pairing argument.
[in] t - the pairing triple.
Definition at line 305 of file relic_mpc_pc.c.
References g1_norm, g1_sub, g2_norm, and g2_sub.
pc_map_bct()
void pc_map_bct (g1_t d[2], g2_t e[2])
Broadcasts the public values for pairing computation.
Parameters
[out] d - the first set of public values.
[out] e - the second set of public values.
Definition at line 313 of file relic_mpc_pc.c.
References g1_add, g1_copy, g1_norm, g2_add, g2_copy, and g2_norm.
pc_map_mpc()
void pc_map_mpc (gt_t r, const g1_t d1, const g2_t d2, const pt_t triple, int party)
Computes a pairing using a pairing triple.
Parameters
[out] r - the pairing result.
[in] d1 - the first public value.
[in] d2 - the second public value.
[in] triple - the pairing triple.
[in] party - the number of the party executing the computation.
Definition at line 323 of file relic_mpc_pc.c.
References ERR_CAUGHT, g1_add, g1_copy, g1_free, g1_new, g1_norm, g1_null, g2_copy, g2_free, g2_new, g2_null, gt_free, gt_mul, gt_new, gt_null, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.