RELIC: src/pp/relic_pp_map_k18.c File Reference
relic_pp_map_k18.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_mil_k18 (fp18_t r, ep3_t *t, ep3_t *q, ep_t *p, int m, bn_t a)
static void pp_mil_lit_k18 (fp18_t r, ep_t *t, ep_t *p, ep3_t *q, int m, bn_t a)
static void pp_fin_k18_oatep (fp18_t r, ep3_t t, const ep3_t q, const ep_t p, int f)
void pp_map_tatep_k18 (fp18_t r, const ep_t p, const ep3_t q)
void pp_map_sim_tatep_k18 (fp18_t r, const ep_t *p, const ep3_t *q, int m)
void pp_map_weilp_k18 (fp18_t r, const ep_t p, const ep3_t q)
void pp_map_sim_weilp_k18 (fp18_t r, const ep_t *p, const ep3_t *q, int m)
void pp_map_oatep_k18 (fp18_t r, const ep_t p, const ep3_t q)
void pp_map_sim_oatep_k18 (fp18_t r, const ep_t *p, const ep3_t *q, int m)
Detailed Description
Implementation of pairing computation for curves with embedding degree 18.
Definition in file relic_pp_map_k18.c.
Function Documentation
pp_mil_k18()
static void pp_mil_k18 (fp18_t r, ep3_t * t, ep3_t * q, ep_t * p, int m, bn_t a) static
Compute the Miller loop for pairings of type G_2 x G_1 over the bits of a given parameter represented in sparse form.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] q - the vector of first arguments in affine coordinates.
[in] p - the vector of second arguments in affine coordinates.
[in] n - the number of pairings to evaluate.
[in] a - the loop parameter.
Definition at line 51 of file relic_pp_map_k18.c.
References bn_bits(), bn_rec_naf(), ep3_copy(), ep3_free, ep3_neg(), ep3_new, ep3_null, ep_free, ep_neg(), ep_new, ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp18_free, fp18_mul_dxs, fp18_new, fp18_null, fp18_sqr, fp18_zero(), fp_add, fp_neg, pp_add_k18, pp_dbl_k18, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_weilp_k18(), and pp_map_weilp_k18().
pp_mil_lit_k18()
static void pp_mil_lit_k18 (fp18_t r, ep_t * t, ep_t * p, ep3_t * q, int m, bn_t a) static
Compute the Miller loop for pairings of type G_1 x G_2 over the bits of a given parameter.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] p - the first pairing argument in affine coordinates.
[in] q - the second pairing argument in affine coordinates.
[in] n - the number of pairings to evaluate.
[in] a - the loop parameter.
Definition at line 147 of file relic_pp_map_k18.c.
References bn_bits(), bn_get_bit(), ep3_free, ep3_neg(), ep3_new, ep3_null, ep_copy(), ERR_CAUGHT, ERR_NO_MEMORY, fp18_free, fp18_mul, fp18_new, fp18_null, fp18_sqr, fp18_zero(), pp_add_lit_k18(), pp_dbl_lit_k18(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), and pp_map_weilp_k18().
pp_fin_k18_oatep()
static void pp_fin_k18_oatep (fp18_t r, ep3_t t, const ep3_t q, const ep_t p, int f) static
Compute the final lines for optimal ate pairings.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] q - the first point of the pairing, in G_2.
[in] p - the second point of the pairing, in G_1.
[in] f - the flag to correct for the curve family.
Definition at line 201 of file relic_pp_map_k18.c.
References ep3_frb(), ep3_free, ep3_new, ep3_null, ep_curve_is_pairf(), ep_free, EP_K18, ep_neg(), ep_new, ep_null, EP_SG18, ERR_CAUGHT, fp18_frb(), fp18_free, fp18_mul, fp18_mul_dxs, fp18_new, fp18_null, fp18_zero(), fp_add, fp_neg, pp_add_k18, pp_dbl_k18, pp_norm_k18(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_map_oatep_k18(), and pp_map_sim_oatep_k18().
pp_map_tatep_k18()
void pp_map_tatep_k18 (fp18_t r, const ep_t p, const ep3_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 18.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 269 of file relic_pp_map_k18.c.
References bn_free, bn_new, bn_null, core_get(), ep3_frb(), ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp18_set_dig(), fp3_mul, pp_exp_k18(), pp_mil_lit_k18(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_tatep_k18()
void pp_map_sim_tatep_k18 (fp18_t r, const ep_t * p, const ep3_t * q, int m)
Computes the Tate multi-pairing in a parameterized elliptic curve with embedding degree 18.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 308 of file relic_pp_map_k18.c.
References bn_free, bn_new, bn_null, core_get(), ep3_frb(), ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp18_set_dig(), fp3_mul, pp_exp_k18(), pp_mil_lit_k18(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_weilp_k18()
void pp_map_weilp_k18 (fp18_t r, const ep_t p, const ep3_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 18.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 368 of file relic_pp_map_k18.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), core_get(), ep3_frb(), ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp18_free, fp18_inv(), fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr, fp3_mul, pp_mil_k18(), pp_mil_lit_k18(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_weilp_k18()
void pp_map_sim_weilp_k18 (fp18_t r, const ep_t * p, const ep3_t * q, int m)
Computes the Weil multi-pairing in a parameterized elliptic curve with embedding degree 18.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 426 of file relic_pp_map_k18.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), core_get(), ep3_frb(), ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp18_free, fp18_inv(), fp18_inv_cyc(), fp18_mul, fp18_new, fp18_null, fp18_set_dig(), fp18_sqr, fp3_mul, pp_mil_k18(), pp_mil_lit_k18(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_oatep_k18()
void pp_map_oatep_k18 (fp18_t r, const ep_t p, const ep3_t q)
Computes the optimal ate pairing of two points in a parameterized elliptic curve with embedding degree 18.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 507 of file relic_pp_map_k18.c.
References bn_free, bn_new, bn_null, bn_sign(), ep3_free, ep3_is_infty(), ep3_neg(), ep3_new, ep3_norm(), ep3_null, ep_curve_is_pairf(), EP_FM18, ep_free, ep_is_infty(), EP_K18, ep_new, ep_norm(), ep_null, EP_SG18, ERR_CAUGHT, fp18_inv_cyc(), fp18_set_dig(), fp_prime_get_par(), pp_exp_k18(), pp_fin_k18_oatep(), pp_mil_k18(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_sim_oatep_k18()
void pp_map_sim_oatep_k18 (fp18_t r, const ep_t * p, const ep3_t * q, int m)
Computes the optimal ate multi-pairing in a parameterized elliptic curve with embedding degree 18.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 577 of file relic_pp_map_k18.c.
References bn_free, bn_new, bn_null, bn_sign(), ep3_free, ep3_is_infty(), ep3_neg(), ep3_new, ep3_norm(), ep3_null, ep_curve_is_pairf(), EP_FM18, ep_free, ep_is_infty(), EP_K18, ep_new, ep_norm(), ep_null, EP_SG18, ERR_CAUGHT, ERR_NO_MEMORY, fp18_inv_cyc(), fp18_set_dig(), fp_prime_get_par(), pp_exp_k18(), pp_fin_k18_oatep(), pp_mil_k18(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.