RELIC: src/bn/relic_bn_mxp_sim.c File Reference
relic_bn_mxp_sim.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
Macros
#define XP_WIDTH RLC_MAX(8, RLC_WIDTH)
Functions
void bn_mxp_sim (bn_t c, const bn_t a, const bn_t b, const bn_t d, const bn_t e, const bn_t m)
void bn_mxp_sim_few (bn_t c, const bn_t *a, const bn_t *b, const bn_t m, size_t n)
void bn_mxp_sim_lot (bn_t c, const bn_t *a, const bn_t *b, const bn_t m, size_t n)
Detailed Description
Implementation of the multiple precision exponentiation functions.
Definition in file relic_bn_mxp_sim.c.
Macro Definition Documentation
XP_WIDTH
#define XP_WIDTH RLC_MAX(8, RLC_WIDTH)
Size of precomputation table.
Definition at line 41 of file relic_bn_mxp_sim.c.
Referenced by bn_mxp_sim_lot().
Function Documentation
bn_mxp_sim()
void bn_mxp_sim (bn_t c, const bn_t a, const bn_t b, const bn_t d, const bn_t e, const bn_t m)
Exponentiates simultaneously two integers modulo a positive integer using generalized Shamir's trick. Computes c = a^b * d^e mod m.
Parameters
[out] c - the result.
[in] a - the elements to exponentiate.
[in] b - the exponents.
[in] m - the modulus.
Definition at line 47 of file relic_bn_mxp_sim.c.
References bn_copy(), bn_free, bn_mxp_sim_few(), bn_new, bn_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
bn_mxp_sim_few()
void bn_mxp_sim_few (bn_t c, const bn_t * a, const bn_t * b, const bn_t m, size_t n)
Exponentiates simultaneously up to 8 integers modulo a positive integer using generalized Shamir's trick. Computes c = \prod a_i^{b_i} mod m.
Parameters
[out] c - the result.
[in] a - the elements to exponentiate.
[in] b - the exponents.
[in] m - the modulus.
Definition at line 80 of file relic_bn_mxp_sim.c.
References bn_bits(), bn_cmp_dig(), bn_copy(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_mod_monty_back(), bn_mod_monty_conv(), bn_mod_pre, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sqr, bn_zero(), ERR_CAUGHT, ERR_NO_MEMORY, ERR_NO_VALID, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_MAX, RLC_THROW, and RLC_TRY.
Referenced by bn_mxp_sim(), and bn_mxp_sim_lot().
bn_mxp_sim_lot()
void bn_mxp_sim_lot (bn_t c, const bn_t * a, const bn_t * b, const bn_t m, size_t n)
Exponentiates simultaneously many integers modulo a positive integer using generalized Shamir's trick. Computes c = \prod a_i^{b_i} mod m.
Parameters
[out] c - the result.
[in] a - the elements to exponentiate.
[in] b - the integer scalars.
[in] m - the modulus.
[in] n - the number of elements to multiply.
Definition at line 171 of file relic_bn_mxp_sim.c.
References bn_cmp_dig(), bn_copy(), bn_free, bn_mod, bn_mul, bn_mxp, bn_mxp_sim_few(), bn_new, bn_null, bn_set_dig(), bn_zero(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, RLC_TRY, and XP_WIDTH.