RELIC: src/ep/relic_ep_mul_cof.c File Reference
relic_ep_mul_cof.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_md.h"
Functions
void ep_mul_cof (ep_t r, const ep_t p)
Detailed Description
Implementation of point multiplication of a prime elliptic curve by the curve cofactor.
Definition in file relic_ep_mul_cof.c.
Function Documentation
ep_mul_cof()
void ep_mul_cof (ep_t r, const ep_t p)
Multiplies a point in an elliptic curve over by the curve cofactor. In short, it takes a point in the curve to the large prime-order subgroup.
Parameters
[out] R - the result.
[in] P - the point to multiply.
Definition at line 40 of file relic_ep_mul_cof.c.
References bn_add(), bn_add_dig(), bn_div_dig(), bn_free, bn_hlv(), bn_is_even(), bn_mul, bn_mul_dig(), bn_neg(), bn_new, bn_null, bn_sqr, bn_sub_dig(), ep_add, EP_AFG16, EP_B12, EP_B24, EP_B48, EP_BN, ep_curve_get_cof(), ep_curve_is_pairf(), ep_dbl, EP_FM16, EP_FM18, ep_free, EP_K16, EP_K18, ep_mul_basic(), ep_mul_big, ep_mul_dig(), ep_neg(), ep_new, ep_norm(), ep_null, ep_psi(), EP_SG18, ep_sub(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep_map_basic_impl(), ep_map_sswum_impl(), and ep_map_swift_impl().