RELIC: src/pp/relic_pp_add_k18.c File Reference
relic_pp_add_k18.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
#include "relic_util.h"
Functions
void pp_add_k18_basic (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
void pp_add_k18_projc_basic (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
void pp_add_k18_projc_lazyr (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
void pp_add_lit_k18 (fp18_t l, ep_t r, const ep_t p, const ep3_t q)
Detailed Description
Implementation of Miller addition for curves of embedding degree 18.
Definition in file relic_pp_add_k18.c.
Function Documentation
pp_add_k18_basic()
void pp_add_k18_basic (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_add_k18.c.
References ep3_add_slp_basic(), ep3_copy(), ep3_curve_is_twist(), ep3_free, ep3_new, ep3_null, ERR_CAUGHT, fp3_free, fp3_mul, fp3_new, fp3_null, fp3_sub, fp_mul, fp_neg, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k18_projc_basic()
void pp_add_k18_projc_basic (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 86 of file relic_pp_add_k18.c.
References ep3_curve_is_twist(), ERR_CAUGHT, fp3_add, fp3_free, fp3_mul, fp3_new, fp3_null, fp3_sqr, fp3_sub, fp_mul, fp_neg, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_k18_projc_lazyr()
void pp_add_k18_projc_lazyr (fp18_t l, ep3_t r, const ep3_t q, const ep_t p)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 18 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] q - the second point to add.
[in] p - the affine point to evaluate the line function.
Definition at line 176 of file relic_pp_add_k18.c.
References dv3_free, dv3_new, dv3_null, ep3_curve_is_twist(), ERR_CAUGHT, fp3_add, fp3_free, fp3_mul, fp3_muln_low(), fp3_new, fp3_null, fp3_rdcn_low(), fp3_sqr, fp3_sub, fp3_subc_low(), fp_mul, fp_neg, PROJC, RLC_CATCH_ANY, RLC_EP_MTYPE, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_add_lit_k18()
void pp_add_lit_k18 (fp18_t l, ep_t r, const ep_t p, const ep3_t q)
Adds two points and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 18 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point and first point to add.
[in] p - the second point to add.
[in] q - the affine point to evaluate the line function.
Definition at line 259 of file relic_pp_add_k18.c.
References ERR_CAUGHT, fp3_neg(), fp_add, fp_free, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_mil_lit_k18().