RELIC: src/cp/relic_cp_bgn.c File Reference
relic_cp_bgn.c File Reference
Cryptographic protocols
#include <limits.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_rand.h"
#include "relic_bn.h"
#include "relic_util.h"
#include "relic_cp.h"
#include "relic_md.h"
Functions
int cp_bgn_gen (bgn_t pub, bgn_t prv)
int cp_bgn_enc1 (g1_t out[2], dig_t in, bgn_t pub)
int cp_bgn_dec1 (dig_t *out, g1_t in[2], bgn_t prv)
int cp_bgn_enc2 (g2_t out[2], dig_t in, bgn_t pub)
int cp_bgn_dec2 (dig_t *out, g2_t in[2], bgn_t prv)
int cp_bgn_add (gt_t e[4], gt_t c[4], gt_t d[4])
int cp_bgn_mul (gt_t e[4], g1_t c[2], g2_t d[2])
int cp_bgn_dec (dig_t *out, gt_t in[4], bgn_t prv)
Detailed Description
Implementation of Freeman's prime-order version of the Boneh-Goh-Nissim cryptosystem.
Version
$Id$
Definition in file relic_cp_bgn.c.
Function Documentation
cp_bgn_gen()
int cp_bgn_gen (bgn_t pub, bgn_t prv)
Generates a key pair for the Boneh-Go-Nissim (BGN) cryptosystem.
Parameters
[out] pub - the public key.
[out] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 48 of file relic_cp_bgn.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, FINALLY, g1_get_ord, g1_mul_gen, g2_mul_gen, _bgn_t::gx, _bgn_t::gy, _bgn_t::gz, _bgn_t::hx, _bgn_t::hy, _bgn_t::hz, result, RLC_ERR, RLC_OK, TRY, _bgn_t::x, _bgn_t::y, and _bgn_t::z.
cp_bgn_enc1()
int cp_bgn_enc1 (g1_t out[2], dig_t in, bgn_t pub)
Encrypts in G_1 using the BGN cryptosystem.
Parameters
[out] out - the ciphertext.
[in] in - the plaintext as a small integer.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 81 of file relic_cp_bgn.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, FINALLY, g1_add, g1_free, g1_get_ord, g1_mul, g1_mul_dig, g1_mul_gen, g1_new, g1_norm, g1_null, _bgn_t::gx, _bgn_t::gy, _bgn_t::gz, result, RLC_ERR, RLC_OK, and TRY.
cp_bgn_dec1()
int cp_bgn_dec1 (dig_t * out, g1_t in[2], bgn_t prv)
Decrypts in G_1 using the BGN cryptosystem.
Parameters
[out] out - the decrypted small integer.
[in] in - the ciphertext.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 123 of file relic_cp_bgn.c.
References bn_free(), bn_mod, bn_null, bn_sub(), CATCH_ANY, FINALLY, g1_add, g1_cmp, g1_copy, g1_free, g1_get_ord, g1_is_infty, g1_mul, g1_mul_gen, g1_new, g1_norm, g1_null, g1_sub, result, RLC_EQ, RLC_ERR, RLC_OK, TRY, _bgn_t::x, _bgn_t::y, and _bgn_t::z.
cp_bgn_enc2()
int cp_bgn_enc2 (g2_t out[2], dig_t in, bgn_t pub)
Encrypts in G_2 using the BGN cryptosystem.
Parameters
[out] c - the ciphertext.
[in] m - the plaintext as a small integer.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 181 of file relic_cp_bgn.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, FINALLY, g2_add, g2_free, g2_get_ord, g2_mul, g2_mul_dig, g2_mul_gen, g2_new, g2_norm, g2_null, _bgn_t::hx, _bgn_t::hy, _bgn_t::hz, result, RLC_ERR, RLC_OK, and TRY.
cp_bgn_dec2()
int cp_bgn_dec2 (dig_t * out, g2_t in[2], bgn_t prv)
Decrypts in G_2 using the BGN cryptosystem.
Parameters
[out] out - the decrypted small integer.
[in] c - the ciphertext.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 222 of file relic_cp_bgn.c.
References bn_free(), bn_mod, bn_null, bn_sub(), CATCH_ANY, FINALLY, g2_add, g2_cmp, g2_copy, g2_free, g2_get_ord, g2_is_infty, g2_mul, g2_mul_gen, g2_new, g2_norm, g2_null, g2_sub, result, RLC_EQ, RLC_ERR, RLC_OK, TRY, _bgn_t::x, _bgn_t::y, and _bgn_t::z.
cp_bgn_add()
int cp_bgn_add (gt_t e[4], gt_t c[4], gt_t d[4])
Adds homomorphically two BGN ciphertexts in G_T.
Parameters
[out] e - the resulting ciphertext.
[in] c - the first ciphertext to add.
[in] d - the second ciphertext to add.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 280 of file relic_cp_bgn.c.
References gt_mul, and RLC_OK.
cp_bgn_mul()
int cp_bgn_mul (gt_t e[4], g1_t c[2], g2_t d[2])
Multiplies homomorphically two BGN ciphertexts in G_T.
Parameters
[out] e - the resulting ciphertext.
[in] c - the first ciphertext to add.
[in] d - the second ciphertext to add.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 287 of file relic_cp_bgn.c.
References pc_map, and RLC_OK.
cp_bgn_dec()
int cp_bgn_dec (dig_t * out, gt_t in[4], bgn_t prv)
Decrypts in G_T using the BGN cryptosystem.
Parameters
[out] out - the decrypted small integer.
[in] c - the ciphertext.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 296 of file relic_cp_bgn.c.
References bn_add(), bn_free(), bn_mod, bn_null, bn_sub(), CATCH_ANY, FINALLY, g1_free, g1_get_gen, g1_new, g1_null, g2_free, g2_get_gen, g2_new, g2_null, gt_cmp, gt_copy, gt_exp, gt_free, gt_get_ord, gt_inv, gt_is_unity, gt_mul, gt_new, gt_null, pc_map, result, RLC_EQ, RLC_ERR, RLC_OK, TRY, _bgn_t::x, _bgn_t::y, and _bgn_t::z.