RELIC: src/fpx/relic_fp24_sqr.c File Reference
relic_fp24_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp24_sqr_basic (fp24_t c, fp24_t a)
void fp24_sqr_unr (dv24_t c, fp24_t a)
void fp24_sqr_lazyr (fp24_t c, fp24_t a)
Detailed Description
Implementation of squaring in a 24-degree extension of a prime field.
Definition in file relic_fp24_sqr.c.
Function Documentation
fp24_sqr_basic()
void fp24_sqr_basic (fp24_t c, fp24_t a)
Computes the square of a 24-degree extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to square.
Definition at line 42 of file relic_fp24_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), THROW, and TRY.
fp24_sqr_unr()
void fp24_sqr_unr (dv24_t c, fp24_t a)
Computes the square of a 24-degree extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to square.
Definition at line 119 of file relic_fp24_sqr.c.
References CATCH_ANY, dv8_free, dv8_new, dv8_null, dv_copy(), ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp8_add(), fp8_free, fp8_mul_unr(), fp8_new, fp8_null, fp8_sqr_unr(), fp8_sub(), fp_hlvd_low(), RLC_FP_DIGS, THROW, and TRY.
Referenced by fp24_sqr_lazyr().
fp24_sqr_lazyr()
void fp24_sqr_lazyr (fp24_t c, fp24_t a)
Computes the square of a 24-degree extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the 24-degree extension field element to square.
Definition at line 221 of file relic_fp24_sqr.c.
References CATCH_ANY, dv24_free, dv24_new, dv24_null, ERR_CAUGHT, FINALLY, fp24_sqr_unr(), fp2_rdcn_low(), THROW, and TRY.