RELIC: include/relic_err.h File Reference
relic_err.h File Reference
Core functions
#include <stdint.h>
#include <setjmp.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_util.h"
#include "relic_label.h"
Data Structures
struct _sts_t
Macros
#define ERR_FILE RLC_STR(__FILE__)
#define ERR_TRY
#define ERR_CATCH(ADDR)
#define ERR_THROW(E)
#define TRY ERR_TRY
#define CATCH(E) ERR_CATCH(&(E))
#define CATCH_ANY ERR_CATCH(NULL)
#define FINALLY else if (_z == 0)
#define THROW ERR_THROW
#define ERROR(LABEL) goto LABEL
#define ERR_PRINT(ERROR) err_full_msg(__func__, ERR_FILE, __LINE__, ERROR) \
Typedefs
typedef int err_t
typedef struct _sts_t sts_t
Enumerations
enum errors {
ERR_CAUGHT = 1, ERR_NO_MEMORY, ERR_NO_PRECI, ERR_NO_FILE,
ERR_NO_READ, ERR_NO_VALID, ERR_NO_BUFFER, ERR_NO_FIELD,
ERR_NO_CURVE, ERR_NO_CONFIG, ERR_MAX
}
Functions
void err_simple_msg (int error)
void err_full_msg (const char *function, const char *file, int line, int error)
void err_get_msg (err_t *e, char **msg)
int err_get_code (void)
Detailed Description
Interface of the error-handling functions.
Definition in file relic_err.h.
Macro Definition Documentation
ERR_FILE
#define ERR_FILE RLC_STR(__FILE__)
Truncate file name if verbosity is turned off.
Definition at line 80 of file relic_err.h.
ERR_TRY
#define ERR_TRY
Value:
    {                                                                   \
        sts_t *_last, _this;                                            \
        ctx_t *_ctx = core_get();                                       \
        _last = _ctx->last;                                             \
        _this.block = 1;                                                \
        _ctx->last = &_this;                                            \
        for (int _z = 0; ; _z = 1)                                      \
            if (_z) {                                                   \
                if (setjmp(_this.addr) == 0) {                          \
                    if (1)                                              \
Implements the TRY clause of the error-handling routines.
This macro copies the last error from the current library context to a temporary variable and handles the current error. The loop is used so the CATCH facility is called first to store the address of the error being caught. The setjmp() function is then called to store the current program location in the current error field. The program block can now be executed. If an error is thrown inside the program block, the setjmp() function is called again and the return value is non-zero.
Definition at line 123 of file relic_err.h.
ERR_CATCH
#define ERR_CATCH (ADDR)
Value:
                    else { }                                            \
                    _ctx->caught = 0;                                   \
                } else {                                                \
                    _ctx->caught = 1;                                   \
                }                                                       \
                _ctx->last = _last;                                     \
                break;                                                  \
            } else {                                                    \
                _this.error = ADDR;                                     \
            }                                                           \
    }                                                                   \
    for (int _z = 0; _z < 2; _z++)                                      \
        if (_z == 1 && core_get()->caught)                              \
Implements the CATCH clause of the error-handling routines.
First, the address of the error is stored and the execution resumes on the ERR_TRY macro. If an error is thrown inside the program block, the caught flag is updated and the last error is restored. If some error was caught, the execution is resumed inside the CATCH block.
Parameters
[in] ADDR - the address of the exception being caught
Definition at line 145 of file relic_err.h.
ERR_THROW
#define ERR_THROW (E)
Value:
    {                                                                   \
        ctx_t *_ctx = core_get();                                       \
        _ctx->code = RLC_ERR;                                           \
        if (_ctx->last != NULL && _ctx->last->block == 0) {             \
            exit(E);                                                    \
        }                                                               \
        if (_ctx->last == NULL) {                                       \
            _ctx->last = &(_ctx->error);                                \
            _ctx->error.error = &(_ctx->number);                        \
            _ctx->error.block = 0;                                      \
            _ctx->number = E;                                           \
            ERR_PRINT(E);                                               \
        } else {                                                        \
            for (; ; longjmp(_ctx->last->addr, 1)) {                    \
                ERR_PRINT(E);                                           \
                if (_ctx->last->error) {                                \
                    if (E != ERR_CAUGHT) {                              \
                        *(_ctx->last->error) = E;                       \
                    }                                                   \
                }                                                       \
            }                                                           \
        }                                                               \
    }                                                                   \
Implements the THROW clause of the error-handling routines.
If the error pointer is not NULL but there is no surrounding TRY-CATCH block, then the code threw an exception after an exception was thrown. In this case, we finish execution.
If the error pointer is NULL, the error was thrown outside of a TRY-CATCH block. An error message is printed and the function returns.
If the error pointer is valid, the longjmp() function is called to return to the program location where setjmp() was last called. An error message respective to the error is then printed and the current error pointer is updated to store the error.
Parameters
[in] E - the exception being caught.
Definition at line 177 of file relic_err.h.
TRY
#define TRY ERR_TRY
Implements a TRY clause.
Definition at line 206 of file relic_err.h.
CATCH
#define CATCH (E) ERR_CATCH(&(E))
Implements a CATCH clause.
Definition at line 218 of file relic_err.h.
CATCH_ANY
#define CATCH_ANY ERR_CATCH(NULL)
Implements a CATCH clause for any possible error.
If this macro is used the error type is not available inside the CATCH block.
Definition at line 233 of file relic_err.h.
FINALLY
#define FINALLY else if (_z == 0)
Implements a FINALLY clause.
Definition at line 245 of file relic_err.h.
THROW
#define THROW ERR_THROW
Implements a THROW clause.
Definition at line 254 of file relic_err.h.
ERROR
#define ERROR (LABEL) goto LABEL
Treats an error jumping to the argument.
Parameters
[in] LABEL - the label to jump
Definition at line 274 of file relic_err.h.
ERR_PRINT
#define ERR_PRINT (ERROR) err_full_msg(__func__, ERR_FILE, __LINE__, ERROR) \
Prints the current error message.
Parameters
[in] ERROR - the error code.
Definition at line 283 of file relic_err.h.
Typedef Documentation
err_t
typedef int err_t
Type that represents an error.
Definition at line 93 of file relic_err.h.
sts_t
typedef struct _sts_t sts_t
Type that describes an error status, including the error code and the program location where the error occurred.
Enumeration Type Documentation
errors
enum errors
List of possible errors generated by the library.
Enumerator
ERR_CAUGHT
Constant to indicate the first an error already catched.
ERR_NO_MEMORY
Occurs when memory-allocating functions fail.
ERR_NO_PRECI
Occcurs when the library precision is not sufficient.
ERR_NO_FILE
Occurs when a file is not found.
ERR_NO_READ
Occurs when the specified number of bytes cannot be read from source.
ERR_NO_VALID
Occurs when an invalid value is passed as input.
ERR_NO_BUFFER
Occurs when a buffer capacity is insufficient.
ERR_NO_FIELD
Occurs when there is not a supported field in the security level.
ERR_NO_CURVE
Occurs when there is not a supported curve in the security level.
ERR_NO_CONFIG
Occurs when the library configuration is incorrect.
ERR_MAX
Constant to indicate the number of errors.
Definition at line 53 of file relic_err.h.
Function Documentation
err_simple_msg()
void err_simple_msg (int error)
Prints the error message with little information.
Parameters
[in] error - the error code.
Definition at line 51 of file relic_err.c.
References core_get(), and ERR_CAUGHT.
err_full_msg()
void err_full_msg (const char * function, const char * file, int line, int error)
Prints the error message with detailed information.
Parameters
[in] function - the function where the error occurred.
[in] file - the source file where the error occurred.
[in] line - the line in the file where the error occurred.
[in] error - the error code.
Definition at line 59 of file relic_err.c.
References core_get(), ERR_CAUGHT, and _ctx_t::reason.
err_get_msg()
void err_get_msg (err_t * e, char ** msg)
Prints the error message respective to an error code.
Parameters
[out] e - the error occurred.
[out] msg - the error message.
Definition at line 92 of file relic_err.c.
References core_get(), _sts_t::error, _ctx_t::last, and _ctx_t::reason.
err_get_code()
int err_get_code (void)
Returns the code returned by the last function call and resets the current code.
Returns
ERR_OK if no errors occurred in the function, ERR_ERR otherwise.
Definition at line 101 of file relic_err.c.
References _ctx_t::code, core_get(), and RLC_OK.