RELIC: src/rand/relic_rand_core.c File Reference
relic_rand_core.c File Reference
Pseudo-random number generators.
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_label.h"
#include "relic_rand.h"
#include "relic_md.h"
#include "relic_err.h"
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
Macros
#define RAND_PATH "/dev/urandom"
Functions
void rand_init ()
void rand_clean ()
Detailed Description
Implementation of utilities for pseudo-random number generation.
Version
Id
relic_rand_core.c 1918 2014-06-18 22:06:00Z dfaranha
Definition in file relic_rand_core.c.
Macro Definition Documentation
#define RAND_PATH "/dev/urandom"
The path to the char device that supplies entropy.
Definition at line 75 of file relic_rand_core.c.
Referenced by rand_init().
Function Documentation
void rand_init (void)
Initializes the pseudo-random number generator.
Definition at line 82 of file relic_rand_core.c.
References core_get(), ERR_NO_FILE, ERR_NO_READ, _ctx_t::rand, RAND_PATH, rand_seed(), SEED_SIZE, _ctx_t::seeded, and THROW.
Referenced by core_init().
void rand_clean (void)
Finishes the pseudo-random number generator.
Definition at line 175 of file relic_rand_core.c.
References core_get(), _ctx_t::rand, and _ctx_t::seeded.
Referenced by core_clean().