RELIC: src/ep/relic_ep_param.c File Reference
relic_ep_param.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
#include "relic_epx.h"
Macros
#define ASSIGN(CURVE, FIELD)
#define ASSIGNK(CURVE, FIELD)
#define NIST_P256_A "FFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFC"
#define NIST_P256_B "5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B"
#define NIST_P256_X "6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296"
#define NIST_P256_Y "4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5"
#define NIST_P256_R "FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551"
#define NIST_P256_H "1"
#define BSI_P256_A "7D5A0975FC2C3057EEF67530417AFFE7FB8055C126DC5C6CE94A4B44F330B5D9"
#define BSI_P256_B "26DC5C6CE94A4B44F330B5D9BBD77CBF958416295CF7E1CE6BCCDC18FF8C07B6"
#define BSI_P256_X "8BD2AEB9CB7E57CB2C4B482FFC81B7AFB9DE27E1E3BD23C23A4453BD9ACE3262"
#define BSI_P256_Y "547EF835C3DAC4FD97F8461A14611DC9C27745132DED8E545C1D54C72F046997"
#define BSI_P256_R "A9FB57DBA1EEA9BC3E660A909D838D718C397AA3B561A6F7901E0E82974856A7"
#define BSI_P256_H "1"
#define SECG_K256_A "0"
#define SECG_K256_B "7"
#define SECG_K256_X "79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798"
#define SECG_K256_Y "483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8"
#define SECG_K256_R "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141"
#define SECG_K256_H "1"
#define SECG_K256_BETA "7AE96A2B657C07106E64479EAC3434E99CF0497512F58995C1396C28719501EE"
#define SECG_K256_LAMB "5363AD4CC05C30E0A5261C028812645A122E22EA20816678DF02967C1B23BD72"
#define BN_P256_A "0"
#define BN_P256_B "11"
#define BN_P256_X "B64000000000FF2F2200000085FD5480B0001F44B6B88BF142BC818F95E3E6AE"
#define BN_P256_Y "4"
#define BN_P256_R "B64000000000FF2F2200000085FD547FD8001F44B6B7F4B7C2BC818F7B6BEF99"
#define BN_P256_H "1"
#define BN_P256_BETA "B64000000000FF2E2F00000085FC555230001F445D656FB022BC77236CD54C89"
#define BN_P256_LAMB "B64000000000FF2D3C00000085FB562050001F44040FF68D82BC6CB6D9E8694E"
Functions
int ep_param_get (void)
void ep_param_set (int param)
int ep_param_set_any (void)
int ep_param_set_any_plain (void)
int ep_param_set_any_endom (void)
int ep_param_set_any_super (void)
int ep_param_set_any_pairf (void)
void ep_param_print (void)
int ep_param_level (void)
int ep_param_embed (void)
Detailed Description
Implementation of the prime elliptic curve parameters.
Definition in file relic_ep_param.c.
Macro Definition Documentation
NIST_P256_A
#define NIST_P256_A "FFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFC"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 190 of file relic_ep_param.c.
NIST_P256_B
#define NIST_P256_B "5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 191 of file relic_ep_param.c.
NIST_P256_X
#define NIST_P256_X "6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 192 of file relic_ep_param.c.
NIST_P256_Y
#define NIST_P256_Y "4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 193 of file relic_ep_param.c.
NIST_P256_R
#define NIST_P256_R "FFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 194 of file relic_ep_param.c.
NIST_P256_H
#define NIST_P256_H "1"
Parameters for the NIST P-256 prime elliptic curve.
Definition at line 195 of file relic_ep_param.c.
BSI_P256_A
#define BSI_P256_A "7D5A0975FC2C3057EEF67530417AFFE7FB8055C126DC5C6CE94A4B44F330B5D9"
Parameters for the Brainpool P256r1 prime elliptic curve.
Definition at line 204 of file relic_ep_param.c.
BSI_P256_B
#define BSI_P256_B "26DC5C6CE94A4B44F330B5D9BBD77CBF958416295CF7E1CE6BCCDC18FF8C07B6"
Parameters for the Brainpool P256r1 prime elliptic curve.
Definition at line 205 of file relic_ep_param.c.
BSI_P256_X
#define BSI_P256_X "8BD2AEB9CB7E57CB2C4B482FFC81B7AFB9DE27E1E3BD23C23A4453BD9ACE3262"
Parameters for the Brainpool P256r1 prime elliptic curve.
Definition at line 206 of file relic_ep_param.c.
BSI_P256_Y
#define BSI_P256_Y "547EF835C3DAC4FD97F8461A14611DC9C27745132DED8E545C1D54C72F046997"
Parameters for the Brainpool P256r1 prime elliptic curve.
Definition at line 207 of file relic_ep_param.c.
BSI_P256_R
#define BSI_P256_R "A9FB57DBA1EEA9BC3E660A909D838D718C397AA3B561A6F7901E0E82974856A7"
Parameters for the Brainpool P256r1 prime elliptic curve.
Definition at line 208 of file relic_ep_param.c.
BSI_P256_H
#define BSI_P256_H "1"
Parameters for the Brainpool P256r1 prime elliptic curve.
Definition at line 209 of file relic_ep_param.c.
SECG_K256_A
#define SECG_K256_A "0"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 218 of file relic_ep_param.c.
SECG_K256_B
#define SECG_K256_B "7"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 219 of file relic_ep_param.c.
SECG_K256_X
#define SECG_K256_X "79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 220 of file relic_ep_param.c.
SECG_K256_Y
#define SECG_K256_Y "483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 221 of file relic_ep_param.c.
SECG_K256_R
#define SECG_K256_R "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 222 of file relic_ep_param.c.
SECG_K256_H
#define SECG_K256_H "1"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 223 of file relic_ep_param.c.
SECG_K256_BETA
#define SECG_K256_BETA "7AE96A2B657C07106E64479EAC3434E99CF0497512F58995C1396C28719501EE"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 224 of file relic_ep_param.c.
SECG_K256_LAMB
#define SECG_K256_LAMB "5363AD4CC05C30E0A5261C028812645A122E22EA20816678DF02967C1B23BD72"
Parameters for the SECG K-256 prime elliptic curve.
Definition at line 225 of file relic_ep_param.c.
BN_P256_A
#define BN_P256_A "0"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 336 of file relic_ep_param.c.
BN_P256_B
#define BN_P256_B "11"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 337 of file relic_ep_param.c.
BN_P256_X
#define BN_P256_X "B64000000000FF2F2200000085FD5480B0001F44B6B88BF142BC818F95E3E6AE"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 338 of file relic_ep_param.c.
BN_P256_Y
#define BN_P256_Y "4"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 339 of file relic_ep_param.c.
BN_P256_R
#define BN_P256_R "B64000000000FF2F2200000085FD547FD8001F44B6B7F4B7C2BC818F7B6BEF99"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 340 of file relic_ep_param.c.
BN_P256_H
#define BN_P256_H "1"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 341 of file relic_ep_param.c.
BN_P256_BETA
#define BN_P256_BETA "B64000000000FF2E2F00000085FC555230001F445D656FB022BC77236CD54C89"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 342 of file relic_ep_param.c.
BN_P256_LAMB
#define BN_P256_LAMB "B64000000000FF2D3C00000085FB562050001F44040FF68D82BC6CB6D9E8694E"
Parameters for a 256-bit pairing-friendly prime curve.
Definition at line 343 of file relic_ep_param.c.
ASSIGN
#define ASSIGN (CURVE, FIELD)
Value:
    fp_param_set(FIELD);                                                    \
    RLC_GET(str, CURVE##_A, sizeof(CURVE##_A));                             \
    fp_read_str(a, str, strlen(str), 16);                                   \
    RLC_GET(str, CURVE##_B, sizeof(CURVE##_B));                             \
    fp_read_str(b, str, strlen(str), 16);                                   \
    RLC_GET(str, CURVE##_X, sizeof(CURVE##_X));                             \
    fp_read_str(g->x, str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_Y, sizeof(CURVE##_Y));                             \
    fp_read_str(g->y, str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_R, sizeof(CURVE##_R));                             \
    bn_read_str(r, str, strlen(str), 16);                                   \
    RLC_GET(str, CURVE##_H, sizeof(CURVE##_H));                             \
    bn_read_str(h, str, strlen(str), 16);                                   \
Assigns a set of ordinary elliptic curve parameters.
Parameters
[in] CURVE - the curve parameters to assign.
[in] FIELD - the finite field identifier.
Definition at line 572 of file relic_ep_param.c.
ASSIGNK
#define ASSIGNK (CURVE, FIELD)
Value:
    ASSIGN(CURVE, FIELD);                                                   \
    RLC_GET(str, CURVE##_BETA, sizeof(CURVE##_BETA));                       \
    fp_read_str(beta, str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_LAMB, sizeof(CURVE##_LAMB));                       \
    bn_read_str(lamb, str, strlen(str), 16);                                \
Assigns a set of parameters for an elliptic curve with endomorphisms.
Parameters
[in] CURVE - the curve parameters to assign.
[in] FIELD - the finite field identifier.
Definition at line 593 of file relic_ep_param.c.
Function Documentation
ep_param_get()
int ep_param_get (void)
Returns the parameter identifier of the currently configured prime elliptic curve.
Returns
the parameter identifier.
Definition at line 604 of file relic_ep_param.c.
References core_get(), and _ctx_t::ep_id.
Referenced by ep2_curve_set_twist(), ep_param_embed(), ep_param_level(), and ep_param_print().
ep_param_set()
void ep_param_set (int param)
Configures a prime elliptic curve by its parameter identifier.
Parameters
- the parameter identifier.
Definition at line 608 of file relic_ep_param.c.
References ASSIGN, ASSIGNK, B12_381, B12_446, B12_455, B12_638, B12_P381, B12_P446, B12_P455, B12_P638, B24_477, B24_P477, B48_575, B48_P575, BN_158, BN_254, BN_256, BN_382, BN_446, BN_638, bn_free(), bn_null, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, BSI_256, BSI_P256, CATCH_ANY, core_get(), CP8_544, CP8_P544, CURVE_1174, CURVE_22103, CURVE_25519, CURVE_383187, CURVE_4417, CURVE_511187, CURVE_67254, EP_B12, EP_B48, EP_BN, ep_curve_set_endom(), ep_curve_set_plain(), ep_curve_set_super(), _ctx_t::ep_id, _ctx_t::ep_is_pairf, EP_K54, ep_null, ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp_null, fp_set_dig(), K54_569, K54_P569, KSS_508, KSS_P508, NIST_192, NIST_224, NIST_256, NIST_384, NIST_521, NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, ep_st::norm, OT8_P511, OT_511, PRIME_22103, PRIME_22605, PRIME_25109, PRIME_25519, PRIME_382105, PRIME_383187, PRIME_511187, RLC_FP_BYTES, SECG_160, SECG_160D, SECG_192, SECG_224, SECG_256, SECG_K160, SECG_K192, SECG_K224, SECG_K256, SECG_P160, SS_1536, SS_P1536, THROW, TRY, and ep_st::z.
Referenced by ep_param_set_any_endom(), ep_param_set_any_pairf(), ep_param_set_any_plain(), and ep_param_set_any_super().
ep_param_set_any()
int ep_param_set_any (void)
Configures some set of curve parameters for the current security level.
Definition at line 901 of file relic_ep_param.c.
References ep_param_set_any_endom(), ep_param_set_any_pairf(), ep_param_set_any_plain(), RLC_ERR, and RLC_OK.
ep_param_set_any_plain()
int ep_param_set_any_plain (void)
Configures some set of ordinary curve parameters for the current security level.
Returns
RLC_OK if there is a curve at this security level, RLC_ERR otherwise.
Definition at line 917 of file relic_ep_param.c.
References CURVE_1174, CURVE_22103, CURVE_25519, CURVE_383187, CURVE_4417, CURVE_67254, ep_param_set(), NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, RLC_ERR, RLC_OK, and SECG_P160.
Referenced by ep_param_set_any().
ep_param_set_any_endom()
int ep_param_set_any_endom (void)
Configures some set of Koblitz curve parameters for the current security level.
Returns
RLC_OK if there is a curve at this security level, RLC_ERR otherwise.
Definition at line 953 of file relic_ep_param.c.
References B12_P381, B12_P446, B12_P455, B12_P638, B24_P477, BN_P158, BN_P254, BN_P382, BN_P446, BN_P638, CP8_P544, ep_param_set(), KSS_P508, OT8_P511, RLC_ERR, RLC_OK, SECG_K160, SECG_K192, SECG_K224, and SECG_K256.
Referenced by ep_param_set_any().
ep_param_set_any_super()
int ep_param_set_any_super (void)
Configures some set of supersingular curve parameters for the current security level.
Returns
RLC_OK if there is a curve at this security level, RLC_ERR otherwise.
Definition at line 1003 of file relic_ep_param.c.
References ep_param_set(), RLC_ERR, RLC_OK, and SS_P1536.
ep_param_set_any_pairf()
int ep_param_set_any_pairf (void)
Configures some set of pairing-friendly curve parameters for the current security level.
Returns
RLC_OK if there is a curve at this security level, RLC_ERR otherwise.
Definition at line 1017 of file relic_ep_param.c.
References B12_P381, B12_P446, B12_P455, B12_P638, B24_P477, B48_P575, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, CP8_P544, ep2_curve_set_twist(), EP_DTYPE, EP_MTYPE, ep_param_set(), K54_P569, KSS_P508, OT8_P511, RLC_ERR, RLC_OK, and SS_P1536.
Referenced by ep_param_set_any().
ep_param_print()
void ep_param_print (void)
Prints the current configured prime elliptic curve.
Definition at line 1115 of file relic_ep_param.c.
References B12_P381, B12_P446, B12_P455, B12_P638, B24_P477, B48_P575, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, BSI_P256, CP8_P544, CURVE_1174, CURVE_25519, CURVE_383187, CURVE_511187, ep_param_get(), K54_P569, KSS_P508, NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, OT8_P511, SECG_K160, SECG_K192, SECG_K224, SECG_K256, SECG_P160, SS_P1536, and util_banner.
ep_param_level()
int ep_param_level (void)
Returns the current security level.
Definition at line 1216 of file relic_ep_param.c.
References B12_P381, B12_P446, B12_P455, B12_P638, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, CP8_544, CURVE_25519, ep_param_get(), NIST_P192, NIST_P224, NIST_P256, NIST_P384, NIST_P521, SECG_K160, SECG_K192, SECG_K224, SECG_K256, SECG_P160, and SS_P1536.
ep_param_embed()
int ep_param_embed (void)
Returns the embedding degree of the currently configured elliptic curve.
Definition at line 1256 of file relic_ep_param.c.
References B12_P381, B12_P446, B12_P455, B12_P638, B48_P575, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, CP8_P544, ep_param_get(), K54_P569, OT8_P511, and SS_P1536.