RELIC: src/epx/relic_ep3_mul.c File Reference
relic_ep3_mul.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep3_psi (ep3_t r, const ep3_t p)
static void ep3_mul_gls_imp (ep3_t r, const ep3_t p, const bn_t k)
static void ep3_mul_reg_gls (ep3_t r, const ep3_t p, const bn_t k)
static void ep3_mul_naf_imp (ep3_t r, const ep3_t p, const bn_t k)
static void ep3_mul_reg_imp (ep3_t r, const ep3_t p, const bn_t k)
void ep3_mul_basic (ep3_t r, const ep3_t p, const bn_t k)
void ep3_mul_slide (ep3_t r, const ep3_t p, const bn_t k)
void ep3_mul_monty (ep3_t r, const ep3_t p, const bn_t k)
void ep3_mul_lwnaf (ep3_t r, const ep3_t p, const bn_t k)
void ep3_mul_lwreg (ep3_t r, const ep3_t p, const bn_t k)
void ep3_mul_gen (ep3_t r, const bn_t k)
void ep3_mul_dig (ep3_t r, const ep3_t p, const dig_t k)
Detailed Description
Implementation of point multiplication on prime elliptic curves over a cubic extensions.
Definition in file relic_ep3_mul.c.
Function Documentation
ep3_psi()
static void ep3_psi (ep3_t r, const ep3_t p) static
Definition at line 41 of file relic_ep3_mul.c.
References ep3_add, ep3_dbl, ep3_frb(), ep3_free, ep3_is_infty(), ep3_new, ep3_null, ep3_set_infty(), ep3_sub(), ep_curve_is_pairf(), EP_FM18, EP_K18, EP_SG18, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_gls_imp(), and ep3_mul_reg_gls().
ep3_mul_gls_imp()
static void ep3_mul_gls_imp (ep3_t r, const ep3_t p, const bn_t k) static
Definition at line 88 of file relic_ep3_mul.c.
References BASIC, bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_dbl(), bn_free, bn_is_even(), bn_mod, bn_neg(), bn_new, bn_null, bn_rec_frb(), bn_rec_sac(), bn_sign(), ep3_add, ep3_copy(), ep3_curve_get_ord(), ep3_dbl, ep3_free, ep3_neg(), ep3_new, ep3_norm(), ep3_norm_sim(), ep3_null, ep3_psi(), ep3_set_infty(), ep3_sub(), EP_ADD, EP_BN, ep_curve_is_pairf(), EP_SG18, ERR_CAUGHT, fp3_set_dig(), fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by ep3_mul_lwnaf().
ep3_mul_reg_gls()
static void ep3_mul_reg_gls (ep3_t r, const ep3_t p, const bn_t k) static
Definition at line 196 of file relic_ep3_mul.c.
References BASIC, bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_dbl(), bn_free, bn_is_even(), bn_mod, bn_neg(), bn_new, bn_null, bn_rec_frb(), bn_rec_sac(), bn_sign(), ep3_add, ep3_copy(), ep3_curve_get_ord(), ep3_dbl, ep3_free, ep3_neg(), ep3_new, ep3_norm(), ep3_norm_sim(), ep3_null, ep3_psi(), ep3_sub(), EP_ADD, EP_BN, ep_curve_is_pairf(), EP_SG18, ERR_CAUGHT, fp3_copy_sec(), fp3_set_dig(), fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by ep3_mul_lwreg().
ep3_mul_naf_imp()
static void ep3_mul_naf_imp (ep3_t r, const ep3_t p, const bn_t k) static
Definition at line 326 of file relic_ep3_mul.c.
References bn_rec_naf(), bn_sign(), ep3_add, ep3_dbl, ep3_free, ep3_neg(), ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ep3_sub(), ep3_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep3_mul_lwnaf().
ep3_mul_reg_imp()
static void ep3_mul_reg_imp (ep3_t r, const ep3_t p, const bn_t k) static
Definition at line 378 of file relic_ep3_mul.c.
References BASIC, bn_abs(), bn_bits(), bn_free, bn_is_even(), bn_new, bn_null, bn_rec_reg(), bn_sign(), ep3_add, ep3_curve_get_ord(), ep3_dbl, ep3_free, ep3_neg(), ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ep3_sub(), ep3_tab(), EP_ADD, ERR_CAUGHT, fp3_copy_sec(), fp3_set_dig(), fp_copy_sec(), RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep3_mul_lwreg().
ep3_mul_basic()
void ep3_mul_basic (ep3_t r, const ep3_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 467 of file relic_ep3_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ep3_add, ep3_dbl, ep3_free, ep3_is_infty(), ep3_mul_dig(), ep3_neg(), ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ep3_sub(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_cof_fm18(), ep3_mul_cof_k18(), and ep3_mul_cof_sg18().
ep3_mul_slide()
void ep3_mul_slide (ep3_t r, const ep3_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 525 of file relic_ep3_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ep3_add, ep3_copy(), ep3_dbl, ep3_free, ep3_is_infty(), ep3_neg(), ep3_new, ep3_norm(), ep3_norm_sim(), ep3_null, ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
ep3_mul_monty()
void ep3_mul_monty (ep3_t r, const ep3_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the constant-time Montgomery ladder point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 596 of file relic_ep3_mul.c.
References bn_abs(), bn_add(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, dv_swap_sec(), ep3_add, ep3_blind(), ep3_curve_get_ord(), ep3_dbl, ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_MAX, RLC_SEL, RLC_THROW, and RLC_TRY.
ep3_mul_lwnaf()
void ep3_mul_lwnaf (ep3_t r, const ep3_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 678 of file relic_ep3_mul.c.
References bn_is_zero(), ep3_is_infty(), ep3_mul_gls_imp(), ep3_mul_naf_imp(), ep3_set_infty(), and ep_curve_is_endom().
ep3_mul_lwreg()
void ep3_mul_lwreg (ep3_t r, const ep3_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 700 of file relic_ep3_mul.c.
References bn_is_zero(), ep3_is_infty(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_set_infty(), and ep_curve_is_endom().
ep3_mul_gen()
void ep3_mul_gen (ep3_t r, const bn_t k)
Multiplies the generator of an elliptic curve over a qaudratic extension.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 720 of file relic_ep3_mul.c.
References bn_is_zero(), ep3_curve_get_gen(), ep3_curve_get_tab(), ep3_free, ep3_mul, ep3_mul_fix, ep3_new, ep3_null, ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_sim_gen(), and ep3_rand().
ep3_mul_dig()
void ep3_mul_dig (ep3_t r, const ep3_t p, const dig_t k)
Multiplies a prime elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 747 of file relic_ep3_mul.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ep3_add, ep3_copy(), ep3_dbl, ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ep3_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_basic().