RELIC: src/ep/relic_ep_dbl.c File Reference
relic_ep_dbl.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
static void ep_dbl_basic_imp (ep_t r, fp_t s, const ep_t p)
static void ep_dbl_projc_imp (ep_t r, const ep_t p)
void ep_dbl_basic (ep_t r, const ep_t p)
void ep_dbl_slp_basic (ep_t r, fp_t s, const ep_t p)
void ep_dbl_projc (ep_t r, const ep_t p)
Detailed Description
Implementation of the point doubling on prime elliptic curves.
Version
Id
relic_ep_dbl.c 1898 2014-05-30 22:40:35Z dfaranha
Definition in file relic_ep_dbl.c.
Function Documentation
static void ep_dbl_basic_imp (ep_t r, fp_t s, const ep_t p) static
Doubles a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 48 of file relic_ep_dbl.c.
References CATCH_ANY, ep_curve_get_a(), ep_curve_opt_a(), ERR_CAUGHT, FINALLY, fp_add, fp_add_dig(), fp_copy(), fp_dbl, fp_free, fp_inv, fp_mul, fp_new, fp_null, fp_sqr, fp_sub, OPT_DIGIT, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by ep_dbl_basic(), and ep_dbl_slp_basic().
static void ep_dbl_projc_imp (ep_t r, const ep_t p) static
Doubles a point represented in projective coordinates on an ordinary prime elliptic curve.
Parameters
r - the result.
p - the point to double.
Definition at line 131 of file relic_ep_dbl.c.
References CATCH_ANY, ep_curve_get_a(), ep_curve_opt_a(), ERR_CAUGHT, FINALLY, fp_add, fp_add_dig(), fp_dbl, fp_free, fp_mul, fp_mul_dig(), fp_new, fp_null, fp_sqr, fp_sub, OPT_DIGIT, OPT_MINUS3, OPT_ONE, OPT_ZERO, THROW, and TRY.
Referenced by ep_dbl_projc().
void ep_dbl_basic (ep_t r, const ep_t p)
Doubles a prime elliptic curve point represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 339 of file relic_ep_dbl.c.
References ep_dbl_basic_imp(), ep_is_infty(), and ep_set_infty().
Referenced by ep_add_basic_imp().
void ep_dbl_slp_basic (ep_t r, fp_t s, const ep_t p)
Doubles a prime elliptic curve point represented in affine coordinates and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 347 of file relic_ep_dbl.c.
References ep_dbl_basic_imp(), ep_is_infty(), and ep_set_infty().
Referenced by pp_dbl_k2_basic().
void ep_dbl_projc (ep_t r, const ep_t p)
Doubles a prime elliptic curve point represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 360 of file relic_ep_dbl.c.
References ep_dbl_projc_imp(), ep_is_infty(), ep_set_infty(), and fp_is_zero().
Referenced by ep_add_projc_imp(), and ep_add_projc_mix().