RELIC: src/cp/relic_cp_decdsa.c File Reference
relic_cp_decdsa.c File Reference
Cryptographic protocols
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_rand.h"
#include "relic_bn.h"
#include "relic_util.h"
#include "relic_cp.h"
#include "relic_md.h"
Functions
void cp_decdsa_gen (bn_t d_1, bn_t d_2, ec_t q)
Detailed Description
Implementation of the distributed ECDSA cryptosystem.
Version
Id
relic_cp_rsa.c 1355 2013-01-27 02:28:52Z dfaranha
Definition in file relic_cp_decdsa.c.
Function Documentation
void cp_decdsa_gen (bn_t d_1, bn_t d_2, ec_t q)
Definition at line 46 of file relic_cp_decdsa.c.
References bn_add(), bn_bits(), bn_free, bn_gcd_ext, bn_is_zero(), bn_mod, bn_mul, BN_NEG, bn_new, bn_null, BN_POS, bn_rand(), bn_sign(), CATCH_ANY, ec_curve_get_ord, ec_mul_gen, ERR_CAUGHT, FINALLY, THROW, and TRY.