RELIC: src/bn/relic_bn_lcm.c File Reference
relic_bn_lcm.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
Functions
void bn_lcm (bn_t c, const bn_t a, const bn_t b)
Detailed Description
Implementation of least common multiple.
Definition in file relic_bn_lcm.c.
Function Documentation
bn_lcm()
void bn_lcm (bn_t c, const bn_t a, const bn_t b)
Computes the last common multiple of two multiple precision integers. Computes c = lcm(a, b).
Parameters
[out] c - the result.
[in] a - the first integer.
[in] b - the second integer.
Definition at line 38 of file relic_bn_lcm.c.
References bn_cmp_abs(), bn_div(), bn_free(), bn_null, CATCH_ANY, ERR_CAUGHT, FINALLY, RLC_LT, RLC_POS, bn_st::sign, THROW, and TRY.