RELIC: src/epx/relic_ep4_norm.c File Reference
relic_ep4_norm.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep4_norm_imp (ep4_t r, const ep4_t p, int inv)
void ep4_norm (ep4_t r, const ep4_t p)
void ep4_norm_sim (ep4_t *r, const ep4_t *t, int n)
Detailed Description
Implementation of point normalization on prime elliptic curves over a quartic extension field.
Definition in file relic_ep4_norm.c.
Function Documentation
ep4_norm_imp()
static void ep4_norm_imp (ep4_t r, const ep4_t p, int inv) static
Normalizes a point represented in projective coordinates.
Parameters
r - the result.
p - the point to normalize.
inv - the flag to indicate if z is already inverted.
Definition at line 48 of file relic_ep4_norm.c.
References BASIC, ep4_copy(), ERR_CAUGHT, fp4_copy(), fp4_free, fp4_inv(), fp4_mul, fp4_new, fp4_null, fp4_set_dig(), fp4_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_norm(), and ep4_norm_sim().
ep4_norm()
void ep4_norm (ep4_t r, const ep4_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 97 of file relic_ep4_norm.c.
References BASIC, ep4_copy(), ep4_is_infty(), ep4_norm_imp(), and ep4_set_infty().
Referenced by ep4_curve_set(), ep4_mul_basic(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_dig(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_naf_imp(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_pre_ordin(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_basic(), ep4_mul_sim_dig(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_on_curve(), ep4_size_bin(), ep4_tab(), ep4_write_bin(), pp_map_k24(), pp_map_oatep_k16(), pp_map_sim_k24(), pp_map_sim_oatep_k16(), pp_map_sim_tatep_k16(), pp_map_sim_weilp_k16(), pp_map_tatep_k16(), and pp_map_weilp_k16().
ep4_norm_sim()
void ep4_norm_sim (ep4_t * r, const ep4_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 113 of file relic_ep4_norm.c.
References ep4_is_infty(), ep4_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, fp4_copy(), fp4_free, fp4_inv_sim(), fp4_new, fp4_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_reg_gls(), ep4_mul_sim_joint(), ep4_mul_sim_trick(), ep4_mul_slide(), and ep4_tab().