RELIC: src/md/blake2s-ref.c File Reference
blake2s-ref.c File Reference
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "blake2.h"
#include "blake2-impl.h"
Macros
#define G(r, i, a, b, c, d)
#define ROUND(r)
Functions
static int blake2s_set_lastnode (blake2s_state *S)
static int blake2s_clear_lastnode (blake2s_state *S)
static int blake2s_set_lastblock (blake2s_state *S)
static int blake2s_clear_lastblock (blake2s_state *S)
static int blake2s_increment_counter (blake2s_state *S, const uint32_t inc)
static int blake2s_param_set_digest_length (blake2s_param *P, const uint8_t digest_length)
static int blake2s_param_set_fanout (blake2s_param *P, const uint8_t fanout)
static int blake2s_param_set_max_depth (blake2s_param *P, const uint8_t depth)
static int blake2s_param_set_leaf_length (blake2s_param *P, const uint32_t leaf_length)
static int blake2s_param_set_node_offset (blake2s_param *P, const uint64_t node_offset)
static int blake2s_param_set_node_depth (blake2s_param *P, const uint8_t node_depth)
static int blake2s_param_set_inner_length (blake2s_param *P, const uint8_t inner_length)
static int blake2s_param_set_salt (blake2s_param *P, const uint8_t salt[BLAKE2S_SALTBYTES])
static int blake2s_param_set_personal (blake2s_param *P, const uint8_t personal[BLAKE2S_PERSONALBYTES])
static int blake2s_init0 (blake2s_state *S)
int blake2s_init_param (blake2s_state *S, const blake2s_param *P)
int blake2s_init (blake2s_state *S, const uint8_t outlen)
int blake2s_init_key (blake2s_state *S, const uint8_t outlen, const void *key, const uint8_t keylen)
static int blake2s_compress (blake2s_state *S, const uint8_t block[BLAKE2S_BLOCKBYTES])
int blake2s_update (blake2s_state *S, const uint8_t *in, uint64_t inlen)
int blake2s_final (blake2s_state *S, uint8_t *out, uint8_t outlen)
int blake2s (uint8_t *out, const void *in, const void *key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen)
Variables
static const uint32_t blake2s_IV [8]
static const uint8_t blake2s_sigma [10][16]
Macro Definition Documentation
G
#define G (r, i, a, b, c, d)
Value:
  do { \
    a = a + b + m[blake2s_sigma[r][2*i+0]]; \
    d = rotr32(d ^ a, 16); \
    c = c + d; \
    b = rotr32(b ^ c, 12); \
    a = a + b + m[blake2s_sigma[r][2*i+1]]; \
    d = rotr32(d ^ a, 8); \
    c = c + d; \
    b = rotr32(b ^ c, 7); \
  } while(0)
ROUND
#define ROUND (r)
Value:
  do { \
    G(r,0,v[ 0],v[ 4],v[ 8],v[12]); \
    G(r,1,v[ 1],v[ 5],v[ 9],v[13]); \
    G(r,2,v[ 2],v[ 6],v[10],v[14]); \
    G(r,3,v[ 3],v[ 7],v[11],v[15]); \
    G(r,4,v[ 0],v[ 5],v[10],v[15]); \
    G(r,5,v[ 1],v[ 6],v[11],v[12]); \
    G(r,6,v[ 2],v[ 7],v[ 8],v[13]); \
    G(r,7,v[ 3],v[ 4],v[ 9],v[14]); \
  } while(0)
Function Documentation
blake2s_set_lastnode()
static int blake2s_set_lastnode (blake2s_state * S) inline static
Definition at line 41 of file blake2s-ref.c.
Referenced by blake2s_set_lastblock().
blake2s_clear_lastnode()
static int blake2s_clear_lastnode (blake2s_state * S) inline static
Definition at line 47 of file blake2s-ref.c.
Referenced by blake2s_clear_lastblock().
blake2s_set_lastblock()
static int blake2s_set_lastblock (blake2s_state * S) inline static
Definition at line 54 of file blake2s-ref.c.
References blake2s_set_lastnode().
Referenced by blake2s_final().
blake2s_clear_lastblock()
static int blake2s_clear_lastblock (blake2s_state * S) inline static
Definition at line 62 of file blake2s-ref.c.
References blake2s_clear_lastnode().
blake2s_increment_counter()
static int blake2s_increment_counter (blake2s_state * S, const uint32_t inc) inline static
Definition at line 70 of file blake2s-ref.c.
Referenced by blake2s_final(), and blake2s_update().
blake2s_param_set_digest_length()
static int blake2s_param_set_digest_length (blake2s_param * P, const uint8_t digest_length) inline static
Definition at line 78 of file blake2s-ref.c.
References __blake2s_param::digest_length.
blake2s_param_set_fanout()
static int blake2s_param_set_fanout (blake2s_param * P, const uint8_t fanout) inline static
Definition at line 84 of file blake2s-ref.c.
References __blake2s_param::fanout.
blake2s_param_set_max_depth()
static int blake2s_param_set_max_depth (blake2s_param * P, const uint8_t depth) inline static
Definition at line 90 of file blake2s-ref.c.
References __blake2s_param::depth.
blake2s_param_set_leaf_length()
static int blake2s_param_set_leaf_length (blake2s_param * P, const uint32_t leaf_length) inline static
Definition at line 96 of file blake2s-ref.c.
References __blake2s_param::leaf_length, and store32().
blake2s_param_set_node_offset()
static int blake2s_param_set_node_offset (blake2s_param * P, const uint64_t node_offset) inline static
Definition at line 102 of file blake2s-ref.c.
References __blake2s_param::node_offset, and store48().
blake2s_param_set_node_depth()
static int blake2s_param_set_node_depth (blake2s_param * P, const uint8_t node_depth) inline static
Definition at line 108 of file blake2s-ref.c.
References __blake2s_param::node_depth.
blake2s_param_set_inner_length()
static int blake2s_param_set_inner_length (blake2s_param * P, const uint8_t inner_length) inline static
Definition at line 114 of file blake2s-ref.c.
References __blake2s_param::inner_length.
blake2s_param_set_salt()
static int blake2s_param_set_salt (blake2s_param * P, const uint8_t salt[BLAKE2S_SALTBYTES]) inline static
Definition at line 120 of file blake2s-ref.c.
References BLAKE2S_SALTBYTES, and __blake2s_param::salt.
blake2s_param_set_personal()
static int blake2s_param_set_personal (blake2s_param * P, const uint8_t personal[BLAKE2S_PERSONALBYTES]) inline static
Definition at line 126 of file blake2s-ref.c.
References BLAKE2S_PERSONALBYTES, and __blake2s_param::personal.
blake2s_init0()
static int blake2s_init0 (blake2s_state * S) inline static
Definition at line 132 of file blake2s-ref.c.
References blake2s_IV, and blake2s_state.
Referenced by blake2s_init_param().
blake2s_init_param()
int blake2s_init_param (blake2s_state * S, const blake2s_param * P)
Definition at line 142 of file blake2s-ref.c.
References blake2s_init0(), and load32().
Referenced by blake2s_init(), and blake2s_init_key().
blake2s_init()
int blake2s_init (blake2s_state * S, const uint8_t outlen)
Definition at line 156 of file blake2s-ref.c.
References blake2s_init_param(), BLAKE2S_OUTBYTES, __blake2s_param::depth, __blake2s_param::digest_length, __blake2s_param::fanout, __blake2s_param::inner_length, __blake2s_param::key_length, __blake2s_param::leaf_length, __blake2s_param::node_depth, __blake2s_param::node_offset, __blake2s_param::personal, __blake2s_param::salt, store32(), and store48().
Referenced by blake2s().
blake2s_init_key()
int blake2s_init_key (blake2s_state * S, const uint8_t outlen, const void * key, const uint8_t keylen)
Definition at line 177 of file blake2s-ref.c.
References BLAKE2S_BLOCKBYTES, blake2s_init_param(), BLAKE2S_KEYBYTES, BLAKE2S_OUTBYTES, blake2s_update(), __blake2s_param::depth, __blake2s_param::digest_length, __blake2s_param::fanout, __blake2s_param::inner_length, __blake2s_param::key_length, __blake2s_param::leaf_length, __blake2s_param::node_depth, __blake2s_param::node_offset, __blake2s_param::personal, __blake2s_param::salt, secure_zero_memory(), store32(), and store48().
Referenced by blake2s().
blake2s_compress()
static int blake2s_compress (blake2s_state * S, const uint8_t block[BLAKE2S_BLOCKBYTES]) static
Definition at line 209 of file blake2s-ref.c.
References blake2s_IV, blake2s_sigma, G, load32(), rotr32(), and ROUND.
Referenced by blake2s_final(), and blake2s_update().
blake2s_update()
int blake2s_update (blake2s_state * S, const uint8_t * in, uint64_t inlen)
Definition at line 270 of file blake2s-ref.c.
References BLAKE2S_BLOCKBYTES, blake2s_compress(), and blake2s_increment_counter().
Referenced by blake2s(), and blake2s_init_key().
blake2s_final()
int blake2s_final (blake2s_state * S, uint8_t * out, uint8_t outlen)
Definition at line 300 of file blake2s-ref.c.
References BLAKE2S_BLOCKBYTES, blake2s_compress(), blake2s_increment_counter(), BLAKE2S_OUTBYTES, blake2s_set_lastblock(), and store32().
Referenced by blake2s().
blake2s()
int blake2s (uint8_t * out, const void * in, const void * key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen)
Definition at line 327 of file blake2s-ref.c.
References blake2s_final(), blake2s_init(), blake2s_init_key(), blake2s_state, and blake2s_update().
Referenced by md_map_b2s160(), and md_map_b2s256().
Variable Documentation
blake2s_IV
const uint32_t blake2s_IV[8] static
Initial value:
=
{
  0x6A09E667UL, 0xBB67AE85UL, 0x3C6EF372UL, 0xA54FF53AUL,
  0x510E527FUL, 0x9B05688CUL, 0x1F83D9ABUL, 0x5BE0CD19UL
}
Definition at line 21 of file blake2s-ref.c.
Referenced by blake2s_compress(), and blake2s_init0().
blake2s_sigma
const uint8_t blake2s_sigma[10][16] static
Initial value:
=
{
  {  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15 } ,
  { 14, 10,  4,  8,  9, 15, 13,  6,  1, 12,  0,  2, 11,  7,  5,  3 } ,
  { 11,  8, 12,  0,  5,  2, 15, 13, 10, 14,  3,  6,  7,  1,  9,  4 } ,
  {  7,  9,  3,  1, 13, 12, 11, 14,  2,  6,  5, 10,  4,  0, 15,  8 } ,
  {  9,  0,  5,  7,  2,  4, 10, 15, 14,  1, 11, 12,  6,  8,  3, 13 } ,
  {  2, 12,  6, 10,  0, 11,  8,  3,  4, 13,  7,  5, 15, 14,  1,  9 } ,
  { 12,  5,  1, 15, 14, 13,  4, 10,  0,  7,  6,  3,  9,  2,  8, 11 } ,
  { 13, 11,  7, 14, 12,  1,  3,  9,  5,  0, 15,  4,  8,  6,  2, 10 } ,
  {  6, 15, 14,  9, 11,  3,  0,  8, 12,  2, 13,  7,  1,  4, 10,  5 } ,
  { 10,  2,  8,  4,  7,  6,  1,  5, 15, 11,  9, 14,  3, 12, 13 , 0 } ,
}
Definition at line 27 of file blake2s-ref.c.
Referenced by blake2s_compress().