RELIC: src/cp/relic_cp_smlers.c File Reference
relic_cp_smlers.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_smlers_sig (bn_t td, smlers_t p, const uint8_t *msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
int cp_smlers_ver (bn_t td, smlers_t *s, size_t size, const uint8_t *msg, size_t len, const ec_t pp)
int cp_smlers_ext (bn_t td, smlers_t *p, size_t *size, const uint8_t *msg, size_t len, const ec_t pk, const ec_t pp)
Detailed Description
Implementation of extendable ring signatures.
Definition in file relic_cp_smlers.c.
Function Documentation
cp_smlers_sig()
int cp_smlers_sig (bn_t td, smlers_t p, const uint8_t * msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
Signs a message using the same-message linkable extendable ring signature scheme.
Parameters
[out] td - the signature trapdoor.
[out] p - the resulting signature.
[in] msg - the message to sign.
[in] len - the message length.
[in] sk - the signer's private key.
[in] pk - the singer's public key.
[in] pp - the public parameters.
Definition at line 38 of file relic_cp_smlers.c.
References cp_ers_sig(), cp_sokor_sig(), ec_copy, ec_curve_get_gen, ec_free, ec_map, ec_mul, ec_new, ec_null, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_smlers_ver()
int cp_smlers_ver (bn_t td, smlers_t * s, size_t size, const uint8_t * msg, size_t len, const ec_t pp)
Verifies a same-message linkable extendable ring signature.
Parameters
[in] td - the signature trapdoor.
[in] s - the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] pp - the public parameters.
Definition at line 76 of file relic_cp_smlers.c.
References bn_free, bn_new, bn_null, cp_sokor_ver(), ec_add, ec_cmp, ec_copy, ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_map, ec_mul_gen, ec_new, ec_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
cp_smlers_ext()
int cp_smlers_ext (bn_t td, smlers_t * p, size_t * size, const uint8_t * msg, size_t len, const ec_t pk, const ec_t pp)
Extends a same-message extendable ring signature with a new signature.
Parameters
[out] td - the signature trapdoor.
[in] p - the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] pk - the singer's public key.
[in] pp - the public parameters.
Definition at line 132 of file relic_cp_smlers.c.
References bn_free, bn_mod, bn_new, bn_null, bn_rand_mod(), bn_sub(), cp_sokor_sig(), ec_cmp, ec_copy, ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_map, ec_mul_gen, ec_new, ec_null, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.