RELIC: src/md/relic_md_sha256.c File Reference
relic_md_sha256.c File Reference
Hash functions
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_md.h"
#include "sha.h"
Functions
void md_map_sh256 (uint8_t *hash, const uint8_t *msg, int len)
Detailed Description
Implementation of the SHA-256 hash function.
Definition in file relic_md_sha256.c.
Function Documentation
md_map_sh256()
void md_map_sh256 (uint8_t * hash, const uint8_t * msg, int len)
Computes the SHA-256 hash function.
Parameters
[out] hash - the digest.
[in] msg - the message to hash.
[in] len - the message length in bytes.
Definition at line 43 of file relic_md_sha256.c.
References ERR_NO_VALID, SHA256Input(), SHA256Reset(), SHA256Result(), shaSuccess, and THROW.