RELIC: src/epx/relic_ep2_cmp.c File Reference
relic_ep2_cmp.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
int ep2_cmp (const ep2_t p, const ep2_t q)
Detailed Description
Implementation of utilities for prime elliptic curves over a quadratic extension field.
Definition in file relic_ep2_cmp.c.
Function Documentation
ep2_cmp()
int ep2_cmp (const ep2_t p, const ep2_t q)
Compares two elliptic curve points.
Parameters
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 39 of file relic_ep2_cmp.c.
References ep2_copy(), ep2_free, ep2_is_infty(), ep2_new, ep2_null, ERR_CAUGHT, fp2_cmp(), fp2_mul, fp2_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.