RELIC: src/epx/relic_ep8_add.c File Reference
relic_ep8_add.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_ep_add_tmpl.h"
Functions
TMPL_ADD_BASIC_IMP (ep8, fp8)
TMPL_ADD_PROJC_MIX (ep8, fp8)
TMPL_ADD_PROJC_IMP (ep8, fp8)
TMPL_ADD_JACOB_MIX (ep8, fp8)
TMPL_ADD_JACOB_IMP (ep8, fp8)
void ep8_add_basic (ep8_t r, const ep8_t p, const ep8_t q)
void ep8_add_slp_basic (ep8_t r, fp8_t s, const ep8_t p, const ep8_t q)
void ep8_add_projc (ep8_t r, const ep8_t p, const ep8_t q)
void ep8_add_jacob (ep8_t r, const ep8_t p, const ep8_t q)
void ep8_sub (ep8_t r, const ep8_t p, const ep8_t q)
Detailed Description
Implementation of addition on prime elliptic curves over an octic extension field.
Definition in file relic_ep8_add.c.
Function Documentation
TMPL_ADD_BASIC_IMP()
TMPL_ADD_BASIC_IMP (ep8 , fp8)
Adds two points represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
TMPL_ADD_PROJC_MIX()
TMPL_ADD_PROJC_MIX (ep8 , fp8)
Adds a point represented in homogeneous coordinates to a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the projective point.
[in] q - the affine point.
TMPL_ADD_PROJC_IMP()
TMPL_ADD_PROJC_IMP (ep8 , fp8)
Adds two points represented in homogeneous coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
TMPL_ADD_JACOB_MIX()
TMPL_ADD_JACOB_MIX (ep8 , fp8)
Adds a point represented in Jacobian coordinates to a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the projective point.
[in] q - the affine point.
TMPL_ADD_JACOB_IMP()
TMPL_ADD_JACOB_IMP (ep8 , fp8)
Adds two points represented in Jacobian coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
ep8_add_basic()
void ep8_add_basic (ep8_t r, const ep8_t p, const ep8_t q)
Adds to points represented in affine coordinates in an elliptic curve over a octic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 109 of file relic_ep8_add.c.
References ep8_copy(), and ep8_is_infty().
ep8_add_slp_basic()
void ep8_add_slp_basic (ep8_t r, fp8_t s, const ep8_t p, const ep8_t q)
Adds to points represented in affine coordinates in an elliptic curve over a octic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 123 of file relic_ep8_add.c.
References ep8_copy(), and ep8_is_infty().
Referenced by pp_add_k48_basic().
ep8_add_projc()
void ep8_add_projc (ep8_t r, const ep8_t p, const ep8_t q)
Adds two points represented in projective coordinates in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 141 of file relic_ep8_add.c.
References ep8_copy(), and ep8_is_infty().
ep8_add_jacob()
void ep8_add_jacob (ep8_t r, const ep8_t p, const ep8_t q)
Adds two points represented in Jacobian coordinates in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 159 of file relic_ep8_add.c.
References ep8_copy(), and ep8_is_infty().
ep8_sub()
void ep8_sub (ep8_t r, const ep8_t p, const ep8_t q)
Subtracts a point in an elliptic curve over an octic extension from another.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 175 of file relic_ep8_add.c.
References ep8_add, ep8_free, ep8_neg(), ep8_new, ep8_null, ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_mul_basic(), ep8_mul_cof(), ep8_mul_dig(), ep8_mul_fix_ordin(), ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), and ep8_mul_sim_plain().