RELIC: src/ep/relic_ep_mul_fix.c File Reference
relic_ep_mul_fix.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
static void ep_mul_fix_plain (ep_t r, const ep_t *t, const bn_t k)
static void ep_mul_combs_endom (ep_t r, const ep_t *t, const bn_t k)
static void ep_mul_combs_plain (ep_t r, const ep_t *t, const bn_t k)
void ep_mul_pre_basic (ep_t *t, const ep_t p)
void ep_mul_fix_basic (ep_t r, const ep_t *t, const bn_t k)
void ep_mul_pre_yaowi (ep_t *t, const ep_t p)
void ep_mul_fix_yaowi (ep_t r, const ep_t *t, const bn_t k)
void ep_mul_pre_nafwi (ep_t *t, const ep_t p)
void ep_mul_fix_nafwi (ep_t r, const ep_t *t, const bn_t k)
void ep_mul_pre_combs (ep_t *t, const ep_t p)
void ep_mul_fix_combs (ep_t r, const ep_t *t, const bn_t k)
void ep_mul_pre_combd (ep_t *t, const ep_t p)
void ep_mul_fix_combd (ep_t r, const ep_t *t, const bn_t k)
void ep_mul_pre_lwnaf (ep_t *t, const ep_t p)
void ep_mul_fix_lwnaf (ep_t r, const ep_t *t, const bn_t k)
Detailed Description
Implementation of fixed point multiplication on binary elliptic curves.
Version
Id
relic_ep_mul_fix.c 1838 2014-03-06 17:52:28Z dfaranha
Definition in file relic_ep_mul_fix.c.
Function Documentation
static void ep_mul_fix_plain (ep_t r, const ep_t * t, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] t - the precomputed table.
[in] k - the integer.
Definition at line 48 of file relic_ep_mul_fix.c.
References bn_rec_naf(), ep_add, ep_dbl, EP_DEPTH, ep_norm(), ep_set_infty(), ep_sub, and FP_BITS.
Referenced by ep_mul_fix_lwnaf().
static void ep_mul_combs_endom (ep_t r, const ep_t * t, const bn_t k) static
Multiplies a prime elliptic curve point by an integer using the COMBS method.
Parameters
[out] r - the result.
[in] t - the precomputed table.
[in] k - the integer.
Definition at line 87 of file relic_ep_mul_fix.c.
References bn_abs(), bn_bits(), bn_free, bn_get_bit(), BN_NEG, bn_new, bn_null, BN_POS, bn_rec_glv(), bn_sign(), CATCH_ANY, ep_add, ep_copy(), ep_curve_get_beta(), ep_curve_get_ord(), ep_curve_get_v1(), ep_curve_get_v2(), ep_dbl, EP_DEPTH, ep_free, ep_neg, ep_new, ep_norm(), ep_null, ep_set_infty(), ep_sub, ERR_CAUGHT, FINALLY, fp_mul, THROW, and TRY.
Referenced by ep_mul_fix_combs().
static void ep_mul_combs_plain (ep_t r, const ep_t * t, const bn_t k) static
Multiplies a prime elliptic curve point by an integer using the COMBS method.
Parameters
[out] r - the result.
[in] t - the precomputed table.
[in] k - the integer.
Definition at line 189 of file relic_ep_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_new, bn_null, CATCH_ANY, ep_add, ep_copy(), ep_curve_get_ord(), ep_dbl, EP_DEPTH, ep_norm(), ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by ep_mul_fix_combs().
void ep_mul_pre_basic (ep_t * t, const ep_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 251 of file relic_ep_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep_copy(), ep_curve_get_ord(), ep_dbl, ep_norm_sim(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep_mul_fix_basic (ep_t r, const ep_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 276 of file relic_ep_mul_fix.c.
References bn_bits(), bn_get_bit(), ep_add, ep_norm(), and ep_set_infty().
void ep_mul_pre_yaowi (ep_t * t, const ep_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 295 of file relic_ep_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep_copy(), ep_curve_get_ord(), ep_dbl, EP_DEPTH, ep_norm_sim(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep_mul_fix_yaowi (ep_t r, const ep_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 324 of file relic_ep_mul_fix.c.
References bn_rec_win(), CATCH_ANY, CEIL, ep_add, EP_DEPTH, ep_free, ep_new, ep_norm(), ep_null, ep_set_infty(), ERR_CAUGHT, FINALLY, FP_BITS, THROW, and TRY.
void ep_mul_pre_nafwi (ep_t * t, const ep_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 362 of file relic_ep_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep_copy(), ep_curve_get_ord(), ep_dbl, EP_DEPTH, ep_norm_sim(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep_mul_fix_nafwi (ep_t r, const ep_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 393 of file relic_ep_mul_fix.c.
References bn_rec_naf(), CATCH_ANY, ep_add, EP_DEPTH, ep_free, ep_new, ep_norm(), ep_null, ep_set_infty(), ep_sub, ERR_CAUGHT, FINALLY, FP_BITS, THROW, and TRY.
void ep_mul_pre_combs (ep_t * t, const ep_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 454 of file relic_ep_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep_add, ep_copy(), ep_curve_get_ord(), ep_curve_is_endom(), ep_dbl, EP_DEPTH, ep_norm(), ep_norm_sim(), ep_set_infty(), EP_TABLE_COMBS, ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep_mul_fix_combs (ep_t r, const ep_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 500 of file relic_ep_mul_fix.c.
References ep_curve_is_endom(), ep_mul_combs_endom(), and ep_mul_combs_plain().
void ep_mul_pre_combd (ep_t * t, const ep_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 516 of file relic_ep_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, CATCH_ANY, ep_add, ep_copy(), ep_curve_get_ord(), ep_dbl, EP_DEPTH, ep_norm(), ep_norm_sim(), ep_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep_mul_fix_combd (ep_t r, const ep_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 564 of file relic_ep_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_new, bn_null, CATCH_ANY, ep_add, ep_curve_get_ord(), ep_dbl, EP_DEPTH, ep_norm(), ep_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep_mul_pre_lwnaf (ep_t * t, const ep_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 620 of file relic_ep_mul_fix.c.
References EP_DEPTH, and ep_tab().
void ep_mul_fix_lwnaf (ep_t r, const ep_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 624 of file relic_ep_mul_fix.c.
References ep_mul_fix_plain().