RELIC: src/fpx/relic_fpx_srt.c File Reference
relic_fpx_srt.c File Reference
Extensions of prime fields
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
int fp2_srt (fp2_t c, fp2_t a)
int fp3_srt (fp3_t c, fp3_t a)
Detailed Description
Implementation of square root in extensions defined over prime fields.
Version
Id
relic_fpx_srt.c 1894 2014-05-18 03:08:36Z dfaranha
Definition in file relic_fpx_srt.c.
Function Documentation
int fp2_srt (fp2_t c, fp2_t a)
Extracts the square root of a quadratic extension field element. Computes c = sqrt(a). The other square root is the negation of c.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 39 of file relic_fpx_srt.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_add, fp_copy(), fp_dbl, fp_free, fp_inv, fp_mul, fp_new, fp_null, fp_prime_get_qnr(), fp_set_dig(), fp_sqr, fp_srt(), fp_sub, THROW, and TRY.
Referenced by ep2_map(), and ep2_upk().
int fp3_srt (fp3_t c, fp3_t a)
Extracts the square root of a cubic extension field element. Computes c = sqrt(a). The other square root is the negation of c.
Parameters
[out] c - the result.
[in] a - the extension field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 100 of file relic_fpx_srt.c.
References bn_div_dig(), bn_free, bn_new, bn_null, bn_sub_dig(), CATCH_ANY, CMP_EQ, dv_copy(), ERR_CAUGHT, FINALLY, fp3_cmp(), fp3_dbl, fp3_exp(), fp3_frb(), fp3_free, fp3_mul, fp3_new, fp3_null, fp3_sqr, FP_DIGS, fp_prime_get(), fp_sub_dig(), THROW, and TRY.