RELIC: src/fp/relic_fp_srt.c File Reference
relic_fp_srt.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
Functions
int fp_srt (fp_t c, const fp_t a)
Detailed Description
Implementation of the square root function.
Definition in file relic_fp_srt.c.
Function Documentation
fp_srt()
int fp_srt (fp_t c, const fp_t a)
Extracts the square root of a prime field element. Computes c = sqrt(a). The other square root is the negation of c.
Parameters
[out] c - the result.
[in] a - the prime field element.
Returns
- 1 if there is a square root, 0 otherwise.
Definition at line 38 of file relic_fp_srt.c.
References bn_add_dig(), bn_free(), bn_is_even(), bn_lsh(), bn_null, bn_rsh(), CATCH_ANY, bn_st::dp, dv_copy(), ERR_CAUGHT, FINALLY, fp_cmp(), fp_cmp_dig(), fp_copy(), fp_null, fp_prime_get(), fp_prime_get_mod8(), fp_rand(), RLC_EQ, RLC_FP_DIGS, THROW, TRY, and bn_st::used.
Referenced by ed_upk(), ep_map(), ep_sw_b12(), ep_sw_bn(), ep_upk(), fp2_srt(), fp2_upk(), fp_prime_calc(), and fp_prime_set().