RELIC: src/epx/relic_ep2_neg.c File Reference
relic_ep2_neg.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
void ep2_neg_basic (ep2_t r, ep2_t p)
void ep2_neg_projc (ep2_t r, ep2_t p)
Detailed Description
Implementation of point negation on elliptic prime curves over quadratic extensions.
Definition in file relic_ep2_neg.c.
Function Documentation
ep2_neg_basic()
void ep2_neg_basic (ep2_t r, ep2_t p)
Negates a point represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 41 of file relic_ep2_neg.c.
References ep2_is_infty(), ep2_set_infty(), fp2_copy(), fp2_neg(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_sub_basic().
ep2_neg_projc()
void ep2_neg_projc (ep2_t r, ep2_t p)
Negates a point represented in projective coordinates in an elliptic curve over a quadratic exyension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 61 of file relic_ep2_neg.c.
References ep2_is_infty(), ep2_set_infty(), fp2_copy(), fp2_neg(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_sub_projc().