RELIC: src/fpx/relic_fpx_exp.c File Reference
relic_fpx_exp.c File Reference
Extensions of prime fields
#include "relic_core.h"
Functions
void fp2_exp (fp2_t c, fp2_t a, bn_t b)
void fp2_conv_uni (fp2_t c, fp2_t a)
void fp2_exp_uni (fp2_t c, fp2_t a, bn_t b)
int fp2_test_uni (fp2_t a)
void fp3_exp (fp3_t c, fp3_t a, bn_t b)
void fp6_exp (fp6_t c, fp6_t a, bn_t b)
void fp12_exp (fp12_t c, fp12_t a, bn_t b)
void fp12_exp_cyc (fp12_t c, fp12_t a, bn_t b)
void fp12_exp_cyc_sps (fp12_t c, fp12_t a, int *b, int len)
void fp12_conv_uni (fp12_t c, fp12_t a)
void fp12_conv_cyc (fp12_t c, fp12_t a)
int fp12_test_cyc (fp12_t a)
void fp12_back_cyc (fp12_t c, fp12_t a)
void fp12_back_cyc_sim (fp12_t c[], fp12_t a[], int n)
void fp18_exp (fp18_t c, fp18_t a, bn_t b)
void fp18_exp_cyc (fp18_t c, fp18_t a, bn_t b)
void fp18_exp_cyc_sps (fp18_t c, fp18_t a, int *b, int len)
void fp18_conv_uni (fp18_t c, fp18_t a)
void fp18_conv_cyc (fp18_t c, fp18_t a)
int fp18_test_cyc (fp18_t a)
void fp18_back_cyc (fp18_t c, fp18_t a)
void fp18_back_cyc_sim (fp18_t c[], fp18_t a[], int n)
Detailed Description
Implementation of exponentiation in extensions defined over prime fields.
Version
Id
relic_fpx_exp.c 1953 2014-08-18 15:26:35Z dfaranha
Definition in file relic_fpx_exp.c.
Function Documentation
void fp2_exp (fp2_t c, fp2_t a, bn_t b)
Computes a power of a quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension element to exponentiate.
[in] b - the exponent.
Definition at line 38 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_mul, fp2_new, fp2_null, fp2_sqr, THROW, and TRY.
Referenced by fp2_calc().
void fp2_conv_uni (fp2_t c, fp2_t a)
Converts a quadratic extension field element to a unitary element. Computes c = a^(p - 1).
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
Definition at line 64 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_inv(), fp2_inv_uni(), fp2_mul, fp2_new, fp2_null, THROW, and TRY.
Referenced by pp_exp_k2().
void fp2_exp_uni (fp2_t c, fp2_t a, bn_t b)
Computes a power of a unitary quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the unitary element to exponentiate.
[in] b - the exponent.
Definition at line 88 of file relic_fpx_exp.c.
References bn_rec_naf(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_inv_uni(), fp2_mul, fp2_new, fp2_null, fp2_sqr, fp2_zero(), FP_BITS, fp_set_dig(), FP_WIDTH, THROW, and TRY.
Referenced by pp_exp_k2().
int fp2_test_uni (fp2_t a)
Tests if a quadratic extension field element is unitary.
Parameters
[in] a - the quadratic extension field element to test.
Returns
1 if the extension field element is unitary, 0 otherwise.
Definition at line 147 of file relic_fpx_exp.c.
References CATCH_ANY, CMP_EQ, ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, fp_add, fp_cmp_dig(), fp_sqr, THROW, and TRY.
Referenced by fp2_pck(), fp2_size_bin(), and fp2_write_bin().
void fp3_exp (fp3_t c, fp3_t a, bn_t b)
Computes a power of a cubic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the cubic extension element to exponentiate.
[in] b - the exponent.
Definition at line 172 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp3_copy(), fp3_free, fp3_mul, fp3_new, fp3_null, fp3_sqr, THROW, and TRY.
Referenced by fp3_calc(), and fp3_srt().
void fp6_exp (fp6_t c, fp6_t a, bn_t b)
Computes a power of a sextic extension field element. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the sextic extension element to exponentiate.
[in] b - the exponent.
Definition at line 198 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_copy(), fp6_free, fp6_mul, fp6_new, fp6_null, fp6_sqr, THROW, and TRY.
void fp12_exp (fp12_t c, fp12_t a, bn_t b)
Computes a power of a dodecic extension field element. Detects if the extension field element is in a cyclotomic subgroup and if this is the case, faster formulae are used.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 224 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_copy(), fp12_exp_cyc(), fp12_free, fp12_mul, fp12_new, fp12_null, fp12_sqr, fp12_test_cyc(), THROW, and TRY.
void fp12_exp_cyc (fp12_t c, fp12_t a, bn_t b)
Computes a power of a cyclotomic dodecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 254 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_back_cyc_sim(), fp12_copy(), fp12_free, fp12_mul, fp12_new, fp12_null, fp12_sqr_cyc, fp12_sqr_pck, THROW, and TRY.
Referenced by fp12_exp().
void fp12_exp_cyc_sps (fp12_t c, fp12_t a, int * b, int l)
Computes a power of a cyclotomic dodecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
Definition at line 331 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_back_cyc_sim(), fp12_copy(), fp12_free, fp12_inv_uni(), fp12_mul, fp12_new, fp12_null, fp12_sqr_pck, THROW, and TRY.
Referenced by pp_exp_b12(), and pp_exp_bn().
void fp12_conv_uni (fp12_t c, fp12_t a)
Converts a dodecic extension field element to a unitary element. Computes c = a^(p^6 - 1).
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
Definition at line 396 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_free, fp12_inv(), fp12_inv_uni(), fp12_mul, fp12_new, fp12_null, THROW, and TRY.
void fp12_conv_cyc (fp12_t c, fp12_t a)
Converts a dodecic extension field element to a cyclotomic element. Computes c = a^(p^6 - 1)*(p^2 + 1).
Parameters
[out] c - the result.
[in] a - a dodecic extension field element.
Definition at line 419 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_frb(), fp12_free, fp12_inv(), fp12_inv_uni(), fp12_mul, fp12_new, fp12_null, THROW, and TRY.
Referenced by pp_exp_b12(), and pp_exp_bn().
int fp12_test_cyc (fp12_t a)
Tests if a dodecic extension field element belongs to the cyclotomic subgroup.
Parameters
[in] a - the dodecic extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 449 of file relic_fpx_exp.c.
References CATCH_ANY, CMP_EQ, ERR_CAUGHT, FINALLY, fp12_back_cyc(), fp12_cmp(), fp12_free, fp12_new, fp12_null, THROW, and TRY.
Referenced by fp12_exp(), fp12_pck(), fp12_size_bin(), and fp12_upk().
void fp12_back_cyc (fp12_t c, fp12_t a)
Decompresses a compressed cyclotomic extension field element to its usual representation.
Parameters
[out] c - the result.
[in] a - a dodecic extension field element to decompress.
Definition at line 471 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_add, fp2_copy(), fp2_dbl, fp2_free, fp2_inv(), fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_add_dig(), THROW, and TRY.
Referenced by fp12_read_bin(), fp12_test_cyc(), and fp12_upk().
void fp12_back_cyc_sim (fp12_t c[], fp12_t a[], int n)
Definition at line 529 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_add, fp2_copy(), fp2_dbl, fp2_free, fp2_inv_sim(), fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sqr, fp2_sub, fp_add_dig(), THROW, and TRY.
Referenced by fp12_exp_cyc(), and fp12_exp_cyc_sps().
void fp18_exp (fp18_t c, fp18_t a, bn_t b)
Computes a power of a octodecic extension field element. Detects if the extension field element is in a cyclotomic subgroup and if this is the case, faster formulae are used.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 598 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_copy(), fp18_exp_cyc(), fp18_free, fp18_mul, fp18_new, fp18_null, fp18_sqr, fp18_test_cyc(), THROW, and TRY.
void fp18_exp_cyc (fp18_t c, fp18_t a, bn_t b)
Computes a power of a cyclotomic octodecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 628 of file relic_fpx_exp.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_back_cyc_sim(), fp18_copy(), fp18_free, fp18_mul, fp18_new, fp18_null, fp18_sqr_cyc(), fp18_sqr_pck(), THROW, and TRY.
Referenced by fp18_exp().
void fp18_exp_cyc_sps (fp18_t c, fp18_t a, int * b, int l)
Computes a power of a cyclotomic octodecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
Definition at line 705 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_back_cyc_sim(), fp18_copy(), fp18_free, fp18_inv_uni(), fp18_mul, fp18_new, fp18_null, fp18_sqr_pck(), THROW, and TRY.
void fp18_conv_uni (fp18_t c, fp18_t a)
Converts a octodecic extension field element to a unitary element. Computes c = a^(p^9 - 1).
Parameters
[out] c - the result.
[in] a - a octodecic extension field element.
Definition at line 770 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_free, fp18_inv(), fp18_inv_uni(), fp18_mul, fp18_new, fp18_null, THROW, and TRY.
void fp18_conv_cyc (fp18_t c, fp18_t a)
Converts a octodecic extension field element to a cyclotomic element. Computes c = a^(p^9 - 1)*(p^2 + 1).
Parameters
[out] c - the result.
[in] a - a octodecic extension field element.
Definition at line 793 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_frb(), fp18_free, fp18_inv(), fp18_inv_uni(), fp18_mul, fp18_new, fp18_null, THROW, and TRY.
int fp18_test_cyc (fp18_t a)
Tests if a octodecic extension field element belongs to the cyclotomic subgroup.
Parameters
[in] a - the octodecic extension field element to test.
Returns
1 if the extension field element is in the subgroup. 0 otherwise.
Definition at line 824 of file relic_fpx_exp.c.
References CATCH_ANY, CMP_EQ, ERR_CAUGHT, FINALLY, fp18_back_cyc(), fp18_cmp(), fp18_free, fp18_new, fp18_null, THROW, and TRY.
Referenced by fp18_exp().
void fp18_back_cyc (fp18_t c, fp18_t a)
Decompresses a compressed cyclotomic extension field element to its usual representation.
Parameters
[out] c - the result.
[in] a - a octodecic extension field element to decompress.
Definition at line 846 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_copy(), fp3_add, fp3_dbl, fp3_free, fp3_inv(), fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_sqr, fp3_sub, fp_add_dig(), fp_copy(), fp_dbl, THROW, and TRY.
Referenced by fp18_test_cyc().
void fp18_back_cyc_sim (fp18_t c[], fp18_t a[], int n)
Definition at line 935 of file relic_fpx_exp.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp18_copy(), fp3_add, fp3_dbl, fp3_free, fp3_inv_sim(), fp3_mul, fp3_mul_nor(), fp3_new, fp3_null, fp3_sqr, fp3_sub, fp_add_dig(), fp_copy(), fp_dbl, THROW, and TRY.
Referenced by fp18_exp_cyc(), and fp18_exp_cyc_sps().