RELIC: include/relic_rand.h File Reference
relic_rand.h File Reference
Pseudo-random number generators.
#include "relic_rand.h"
Macros
#define RAND_SIZE (1 + 2*440/8)
#define SEED_SIZE 64
Functions
void rand_init (void)
void rand_clean (void)
void rand_seed (void(*callback)(uint8_t *, int, void *), void *arg)
void rand_bytes (uint8_t *buf, int size)
Detailed Description
Interface of the module for pseudo-random number generation.
Version
Id
relic_rand.h 1920 2014-06-18 22:10:21Z dfaranha
Definition in file relic_rand.h.
Macro Definition Documentation
#define RAND_SIZE (1 + 2*440/8)
Size of the PRNG internal state in bytes.
Definition at line 51 of file relic_rand.h.
Referenced by rand_bytes(), rand_gen(), and rand_seed().
#define SEED_SIZE 64
Minimum size of the PRNG seed.
Definition at line 69 of file relic_rand.h.
Referenced by rand_init().
Function Documentation
void rand_init (void)
Initializes the pseudo-random number generator.
Definition at line 82 of file relic_rand_core.c.
References core_get(), ERR_NO_FILE, ERR_NO_READ, _ctx_t::rand, RAND_PATH, rand_seed(), SEED_SIZE, _ctx_t::seeded, and THROW.
Referenced by core_init().
void rand_clean (void)
Finishes the pseudo-random number generator.
Definition at line 175 of file relic_rand_core.c.
References core_get(), _ctx_t::rand, and _ctx_t::seeded.
Referenced by core_clean().
void rand_seed (void(*)(uint8_t *, int, void *) callback, void * arg)
Sets the initial state of the pseudo-random number generator as a function pointer.
Parameters
[in] callback - the callback to call.
[in] arg - the argument for the callback.
void rand_bytes (uint8_t * buf, int size)
Gathers pseudo-random bytes from the pseudo-random number generator.
Parameters
[out] buf - the buffer to write.
[in] size - the number of bytes to gather.
Exceptions
ERR_NO_VALID - if the required length is too large.
ERR_NO_READ - it the pseudo-random number generator cannot generate the specified number of bytes.
Definition at line 146 of file relic_rand_hash.c.
References core_get(), _ctx_t::counter, ERR_NO_VALID, MD_LEN, md_map, _ctx_t::rand, rand_add(), rand_gen(), rand_inc(), RAND_SIZE, and THROW.
Referenced by bn_rand(), fb_rand(), fp_rand(), and pad_pkcs1().