RELIC: src/mpc/relic_mpc_mt.c File Reference
relic_mpc_mt.c File Reference
Multi-party computation
#include "relic_core.h"
#include "relic_bn.h"
#include "relic_mpc.h"
#include "relic_util.h"
Functions
void mpc_mt_gen (mt_t tri[2], const bn_t order)
void mpc_mt_lcl (bn_t d, bn_t e, const bn_t x, const bn_t y, const bn_t n, const mt_t tri)
void mpc_mt_bct (bn_t d[2], bn_t e[2], bn_t n)
void mpc_mt_mul (bn_t r, const bn_t d, const bn_t e, const bn_t n, const mt_t tri, int party)
Detailed Description
Implementation of multiplication tri generation.
Definition in file relic_mpc_mt.c.
Function Documentation
mpc_mt_gen()
void mpc_mt_gen (mt_t tri[2], const bn_t order)
Generates a pair of multiplication triples for use in MPC protocols such that [a] * [b] = [c] modulo a certain order.
Parameters
[out] tri - the multiplication triples to generate.
[in] order - the order.
Definition at line 41 of file relic_mpc_mt.c.
References bn_add(), bn_mod, bn_mul, bn_rand_mod(), bn_sign(), and bn_sub().
Referenced by pc_map_tri().
mpc_mt_lcl()
void mpc_mt_lcl (bn_t d, bn_t e, const bn_t x, const bn_t y, const bn_t n, const mt_t tri)
Performs the local work for a MPC multiplication.
Parameters
[out] d - the masked first multiplication operand.
[out] e - the masked second multiplication operand.
[in] x - the first multiplication operand.
[in] y - the second multiplication operand.
[in] n - the order.
[in] tri - the multiplication triple.
Definition at line 61 of file relic_mpc_mt.c.
References bn_add(), bn_free, bn_mod, bn_new, bn_null, bn_sign(), bn_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by cp_mpss_sig().
mpc_mt_bct()
void mpc_mt_bct (bn_t d[2], bn_t e[2], bn_t n)
Opens the public values in an MPC multiplication.
Parameters
[out] d - the first public value.
[out] e - the second public value.
[in] n - the order.
Definition at line 92 of file relic_mpc_mt.c.
References bn_add(), bn_copy(), and bn_mod.
Referenced by cp_mpss_sig().
mpc_mt_mul()
void mpc_mt_mul (bn_t r, const bn_t d, const bn_t e, const bn_t n, const mt_t tri, int party)
Finishes an MPC multiplication by computing the multiplication result.
Parameters
[out] r - the share of the multiplication result.
[in] d - the first public value.
[in] e - the second public value.
[in] n - the order.
[in] tri - the multiplication triple.
[in] party - the party performing the computation.
Definition at line 102 of file relic_mpc_mt.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_sign(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by cp_mpss_sig().