RELIC: src/eb/relic_eb_cmp.c File Reference
relic_eb_cmp.c File Reference
Elliptic curves over binary fields
#include "relic_core.h"
#include "relic_eb.h"
#include "relic_conf.h"
Functions
int eb_cmp (const eb_t p, const eb_t q)
Detailed Description
Implementation of the binary elliptic curve point comparison.
Definition in file relic_eb_cmp.c.
Function Documentation
eb_cmp()
int eb_cmp (const eb_t p, const eb_t q)
Compares two binary elliptic curve points.
Parameters
[in] p - the first binary elliptic curve point.
[in] q - the second binary elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 40 of file relic_eb_cmp.c.
References BASIC, eb_copy(), eb_free, eb_is_infty(), eb_new, eb_norm(), eb_null, ERR_CAUGHT, fb_cmp(), fb_mul, fb_sqr, PROJC, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.