RELIC: src/epx/relic_ep3_map.c File Reference
relic_ep3_map.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_md.h"
Functions
void ep3_map (ep3_t p, const uint8_t *msg, size_t len)
Detailed Description
Implementation of hashing to a prime elliptic curve over a cubic extension field.
Definition in file relic_ep3_map.c.
Function Documentation
ep3_map()
void ep3_map (ep3_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in an elliptic curve over a cubic extension.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 40 of file relic_ep3_map.c.
References BASIC, bn_free, bn_get_bit(), bn_new, bn_null, bn_read_bin(), core_get(), _ctx_t::ep3_b, ep3_mul_cof(), ep3_rhs(), ep3_set_infty(), _ctx_t::ep_map_c, ep_param_level(), ERR_CAUGHT, ERR_NO_VALID, fp3_add, fp3_copy(), fp3_copy_sec(), fp3_dbl, fp3_free, fp3_inv(), fp3_is_sqr(), fp3_is_zero(), fp3_mul, fp3_neg(), fp3_new, fp3_null, fp3_set_dig(), fp3_sqr, fp3_srt(), fp3_sub, fp_is_zero(), fp_mul, FP_PRIME, fp_prime_back(), fp_prime_conv(), md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.