RELIC: src/bn/relic_bn_rec.c File Reference
relic_bn_rec.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
Macros
#define MOD_C 8
#define MOD_2TC (1 << MOD_C)
#define MOD_CMASK (MOD_2TC - 1)
Functions
static char get_bits (const bn_t a, int from, int to)
void bn_rec_win (uint8_t *win, int *len, const bn_t k, int w)
void bn_rec_slw (uint8_t *win, int *len, const bn_t k, int w)
void bn_rec_naf (int8_t *naf, int *len, const bn_t k, int w)
void bn_rec_tnaf_get (uint8_t *t, int8_t *beta, int8_t *gama, int8_t u, int w)
void bn_rec_tnaf_mod (bn_t r0, bn_t r1, const bn_t k, int u, int m)
void bn_rec_tnaf (int8_t *tnaf, int *len, const bn_t k, int8_t u, int m, int w)
void bn_rec_rtnaf (int8_t *tnaf, int *len, const bn_t k, int8_t u, int m, int w)
void bn_rec_reg (int8_t *naf, int *len, const bn_t k, int n, int w)
void bn_rec_jsf (int8_t *jsf, int *len, const bn_t k, const bn_t l)
void bn_rec_glv (bn_t k0, bn_t k1, const bn_t k, const bn_t n, const bn_t *v1, const bn_t *v2)
Detailed Description
Implementation of the multiple precision integer recoding functions.
Definition in file relic_bn_rec.c.
Macro Definition Documentation
MOD_C
#define MOD_C 8
Constant C for the partial reduction modulo (t^m - 1)/(t - 1).
Definition at line 78 of file relic_bn_rec.c.
MOD_2TC
#define MOD_2TC (1 << MOD_C)
Constant 2^C.
Definition at line 83 of file relic_bn_rec.c.
MOD_CMASK
#define MOD_CMASK (MOD_2TC - 1)
Mask to calculate reduction modulo 2^C.
Definition at line 88 of file relic_bn_rec.c.
Function Documentation
get_bits()
static char get_bits (const bn_t a, int from, int to) static
Returns a maximum of eight contiguous bits from a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
[in] from - the first bit position.
[in] to - the last bit position, inclusive.
Returns
the bits in the chosen positions.
Definition at line 46 of file relic_bn_rec.c.
References bn_st::dp, RLC_DIG, RLC_DMASK, RLC_MASK, and RLC_RIP.
Referenced by bn_rec_slw(), and bn_rec_win().
bn_rec_win()
void bn_rec_win (uint8_t * win, int * len, const bn_t k, int w)
Recodes a positive integer in window form. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] win - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 94 of file relic_bn_rec.c.
References bn_bits(), ERR_NO_BUFFER, get_bits(), RLC_CEIL, and THROW.
Referenced by eb_mul_sim_trick(), ed_mul_sim_trick(), ep2_mul_sim_trick(), and ep_mul_sim_trick().
bn_rec_slw()
void bn_rec_slw (uint8_t * win, int * len, const bn_t k, int w)
Recodes a positive integer in sliding window form. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] win - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 111 of file relic_bn_rec.c.
References bn_bits(), bn_get_bit(), ERR_NO_BUFFER, get_bits(), RLC_CEIL, RLC_MAX, and THROW.
Referenced by bn_mxp_slide(), ed_mul_slide(), ep2_mul_slide(), ep_mul_slide(), fb_exp_slide(), and fp_exp_slide().
bn_rec_naf()
void bn_rec_naf (int8_t * naf, int * len, const bn_t k, int w)
Recodes a positive integer in width-w Non-Adjacent Form. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] naf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 138 of file relic_bn_rec.c.
References bn_abs(), bn_add_dig(), bn_bits(), bn_free(), bn_get_dig(), bn_hlv(), bn_is_even(), bn_is_zero(), bn_null, bn_sub_dig(), CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, RLC_MASK, THROW, and TRY.
Referenced by eb_mul_fix_plain(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_rnaf_imp(), eb_mul_sim_plain(), ed_mul_fix_plain(), ed_mul_naf_imp(), ed_mul_sim_plain(), ep2_mul_fix_ordin(), ep2_mul_naf_imp(), ep2_mul_sim_plain(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_naf_imp(), ep_mul_sim_endom(), ep_mul_sim_plain(), fp2_exp_cyc(), fp8_exp_cyc(), fp_prime_set_pairf(), pp_mil_k12(), pp_mil_k48(), pp_mil_k54(), and pp_mil_k8().
bn_rec_tnaf_get()
void bn_rec_tnaf_get (uint8_t * t, int8_t * beta, int8_t * gama, int8_t u, int w)
Write the constants needed for \tau-NAF recoding as a set of \alpha_u = \beta_u + \gamma_u * \tau elements.
Parameters
[out] t - the integer corresponding to \tau.
[out] beta - the first coefficients of the constants.
[out] gama - the second coefficients of the constants.
[in] u - the u curve parameter.
[in] w - the window size in bits.
Definition at line 208 of file relic_bn_rec.c.
Referenced by bn_rec_rtnaf(), and bn_rec_tnaf().
bn_rec_tnaf_mod()
void bn_rec_tnaf_mod (bn_t r0, bn_t r1, const bn_t k, int u, int m)
Computes the partial reduction k partmod d = r0 + r1 * t, where d = (t^m - 1)/(t - 1).
Parameters
[out] r0 - the first half of the result.
[out] r1 - the second half of the result.
[in] k - the number to reduce.
[in] u - the u curve parameter.
[in] m - the extension degree of the binary field.
Definition at line 340 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_dbl(), bn_free(), bn_hlv(), bn_is_even(), bn_neg(), bn_null, bn_set_dig(), bn_sub(), bn_sub_dig(), bn_zero(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by bn_rec_rtnaf(), and bn_rec_tnaf().
bn_rec_tnaf()
void bn_rec_tnaf (int8_t * tnaf, int * len, const bn_t k, int8_t u, int m, int w)
Recodes a positive integer in width-w \tau-NAF. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] tnaf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] u - the u curve parameter.
[in] m - the extension degree of the binary field.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 412 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_free(), bn_hlv(), bn_is_zero(), bn_null, bn_rec_tnaf_get(), bn_rec_tnaf_mod(), bn_sign(), bn_sub(), bn_sub_dig(), CATCH_ANY, bn_st::dp, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, RLC_MASK, RLC_NEG, bn_st::sign, THROW, and TRY.
Referenced by eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), and eb_mul_sim_kbltz().
bn_rec_rtnaf()
void bn_rec_rtnaf (int8_t * tnaf, int * len, const bn_t k, int8_t u, int m, int w)
Recodes a positive integer in regular fixed-length width-w \tau-NAF. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] tnaf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] u - the u curve parameter.
[in] m - the extension degree of the binary field.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 538 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_free(), bn_hlv(), bn_null, bn_rec_tnaf_get(), bn_rec_tnaf_mod(), bn_sign(), bn_sub(), bn_sub_dig(), CATCH_ANY, bn_st::dp, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, RLC_CEIL, RLC_MASK, RLC_NEG, bn_st::sign, THROW, and TRY.
bn_rec_reg()
void bn_rec_reg (int8_t * naf, int * len, const bn_t k, int n, int w)
Recodes a positive integer in regular fixed-length width-w NAF. If a negative integer is given instead, its absolute value is taken.
Parameters
[out] naf - the recoded integer.
[out] len - the number of bytes written.
[in] k - the integer to recode.
[in] n - the length of the recoding.
[in] w - the window size in bits.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 677 of file relic_bn_rec.c.
References bn_abs(), bn_free(), bn_get_dig(), bn_hlv(), bn_null, bn_rsh(), CATCH_ANY, bn_st::dp, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, RLC_CEIL, RLC_MASK, THROW, and TRY.
Referenced by ed_mul_reg_imp(), ep_mul_reg_glv(), and ep_mul_reg_imp().
bn_rec_jsf()
void bn_rec_jsf (int8_t * jsf, int * len, const bn_t k, const bn_t l)
Recodes of a pair of positive integers in Joint Sparse Form. If negative integers are given instead, takes their absolute value.
Parameters
[out] jsf - the recoded pair of integers.
[out] len - the number of bytes written.
[in] k - the first integer to recode.
[in] l - the second integer to recode.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 726 of file relic_bn_rec.c.
References bn_abs(), bn_bits(), bn_free(), bn_get_dig(), bn_hlv(), bn_is_zero(), bn_null, CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, RLC_MASK, RLC_MAX, THROW, and TRY.
Referenced by eb_mul_sim_joint(), ed_mul_sim_joint(), ep2_mul_sim_joint(), and ep_mul_sim_joint().
bn_rec_glv()
void bn_rec_glv (bn_t k0, bn_t k1, const bn_t k, const bn_t n, const bn_t * v1, const bn_t * v2)
Definition at line 801 of file relic_bn_rec.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_free(), bn_get_bit(), bn_neg(), bn_null, bn_rsh(), bn_sub(), CATCH_ANY, ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by ep_mul_combs_endom(), ep_mul_glv_imp(), ep_mul_reg_glv(), and ep_mul_sim_endom().