RELIC: src/fpx/relic_fpx_add.c File Reference
relic_fpx_add.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
void fp2_add_basic (fp2_t c, fp2_t a, fp2_t b)
void fp2_sub_basic (fp2_t c, fp2_t a, fp2_t b)
void fp2_dbl_basic (fp2_t c, fp2_t a)
void fp2_add_integ (fp2_t c, fp2_t a, fp2_t b)
void fp2_sub_integ (fp2_t c, fp2_t a, fp2_t b)
void fp2_dbl_integ (fp2_t c, fp2_t a)
void fp2_neg (fp2_t c, fp2_t a)
void fp3_add_basic (fp2_t c, fp2_t a, fp2_t b)
void fp3_sub_basic (fp2_t c, fp2_t a, fp2_t b)
void fp3_dbl_basic (fp2_t c, fp2_t a)
void fp3_neg (fp3_t c, fp3_t a)
void fp3_add_integ (fp2_t c, fp2_t a, fp2_t b)
void fp3_sub_integ (fp2_t c, fp2_t a, fp2_t b)
void fp3_dbl_integ (fp2_t c, fp2_t a)
void fp4_add (fp4_t c, fp4_t a, fp4_t b)
void fp4_sub (fp4_t c, fp4_t a, fp4_t b)
void fp4_dbl (fp4_t c, fp4_t a)
void fp4_neg (fp4_t c, fp4_t a)
void fp6_add (fp6_t c, fp6_t a, fp6_t b)
void fp6_sub (fp6_t c, fp6_t a, fp6_t b)
void fp6_dbl (fp6_t c, fp6_t a)
void fp6_neg (fp6_t c, fp6_t a)
void fp8_add (fp8_t c, fp8_t a, fp8_t b)
void fp8_sub (fp8_t c, fp8_t a, fp8_t b)
void fp8_dbl (fp8_t c, fp8_t a)
void fp8_neg (fp8_t c, fp8_t a)
void fp9_add (fp9_t c, fp9_t a, fp9_t b)
void fp9_sub (fp9_t c, fp9_t a, fp9_t b)
void fp9_dbl (fp9_t c, fp9_t a)
void fp9_neg (fp9_t c, fp9_t a)
void fp12_add (fp12_t c, fp12_t a, fp12_t b)
void fp12_sub (fp12_t c, fp12_t a, fp12_t b)
void fp12_neg (fp12_t c, fp12_t a)
void fp12_dbl (fp12_t c, fp12_t a)
void fp18_add (fp18_t c, fp18_t a, fp18_t b)
void fp18_sub (fp18_t c, fp18_t a, fp18_t b)
void fp18_dbl (fp18_t c, fp18_t a)
void fp18_neg (fp18_t c, fp18_t a)
void fp24_add (fp24_t c, fp24_t a, fp24_t b)
void fp24_sub (fp24_t c, fp24_t a, fp24_t b)
void fp24_neg (fp24_t c, fp24_t a)
void fp24_dbl (fp24_t c, fp24_t a)
void fp48_add (fp48_t c, fp48_t a, fp48_t b)
void fp48_sub (fp48_t c, fp48_t a, fp48_t b)
void fp48_neg (fp48_t c, fp48_t a)
void fp48_dbl (fp48_t c, fp48_t a)
void fp54_add (fp54_t c, fp54_t a, fp54_t b)
void fp54_sub (fp54_t c, fp54_t a, fp54_t b)
void fp54_neg (fp54_t c, fp54_t a)
void fp54_dbl (fp54_t c, fp54_t a)
Detailed Description
Implementation of addition in extensions defined over prime fields.
Definition in file relic_fpx_add.c.
Function Documentation
fp2_add_basic()
void fp2_add_basic (fp2_t c, fp2_t a, fp2_t b)
Adds two quadratic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 41 of file relic_fpx_add.c.
fp2_sub_basic()
void fp2_sub_basic (fp2_t c, fp2_t a, fp2_t b)
Subtracts a quadratic extension field element from another using basic arithmetic.
Parameters
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Definition at line 46 of file relic_fpx_add.c.
fp2_dbl_basic()
void fp2_dbl_basic (fp2_t c, fp2_t a)
Doubles a quadratic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to double.
Definition at line 51 of file relic_fpx_add.c.
fp2_add_integ()
void fp2_add_integ (fp2_t c, fp2_t a, fp2_t b)
Adds two quadratic extension field elements using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the first quadratic extension field element.
[in] b - the second quadratic extension field element.
Definition at line 61 of file relic_fpx_add.c.
References fp2_addm_low().
fp2_sub_integ()
void fp2_sub_integ (fp2_t c, fp2_t a, fp2_t b)
Subtracts a quadratic extension field element from another using integrated modular reduction.
Parameters
[out] C - the result.
[in] A - the first quadratic extension field element.
[in] B - the second quadratic extension field element.
Definition at line 65 of file relic_fpx_add.c.
References fp2_subm_low().
fp2_dbl_integ()
void fp2_dbl_integ (fp2_t c, fp2_t a)
Doubles a quadratic extension field element using integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the quadratic extension field element to double.
Definition at line 69 of file relic_fpx_add.c.
References fp2_dblm_low().
fp2_neg()
void fp2_neg (fp2_t c, fp2_t a)
Negates a quadratic extension field element.
Parameters
[out] C - the result.
[out] A - the quadratic extension field element to negate.
Definition at line 75 of file relic_fpx_add.c.
Referenced by ep2_neg_basic(), ep2_neg_projc(), ep2_upk(), fp4_inv(), fp4_inv_cyc(), fp4_neg(), fp6_neg(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), and pp_add_lit_k12().
fp3_add_basic()
void fp3_add_basic (fp2_t c, fp2_t a, fp2_t b)
Definition at line 82 of file relic_fpx_add.c.
fp3_sub_basic()
void fp3_sub_basic (fp2_t c, fp2_t a, fp2_t b)
Definition at line 88 of file relic_fpx_add.c.
fp3_dbl_basic()
void fp3_dbl_basic (fp2_t c, fp2_t a)
Definition at line 94 of file relic_fpx_add.c.
fp3_neg()
void fp3_neg (fp3_t c, fp3_t a)
Negates a cubic extension field element. Computes c = -a.
Parameters
[out] C - the result.
[out] A - the cubic extension field element to negate.
Definition at line 103 of file relic_fpx_add.c.
Referenced by fp9_neg().
fp3_add_integ()
void fp3_add_integ (fp2_t c, fp2_t a, fp2_t b)
Definition at line 111 of file relic_fpx_add.c.
References fp3_addm_low().
fp3_sub_integ()
void fp3_sub_integ (fp2_t c, fp2_t a, fp2_t b)
Definition at line 115 of file relic_fpx_add.c.
References fp3_subm_low().
fp3_dbl_integ()
void fp3_dbl_integ (fp2_t c, fp2_t a)
Definition at line 119 of file relic_fpx_add.c.
References fp3_dblm_low().
fp4_add()
void fp4_add (fp4_t c, fp4_t a, fp4_t b)
Adds two quartic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first quartic extension field element.
[in] b - the second quartic extension field element.
Definition at line 125 of file relic_fpx_add.c.
Referenced by fp8_add(), fp8_mul_basic(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_basic(), fp8_sqr_cyc(), and fp8_sqr_unr().
fp4_sub()
void fp4_sub (fp4_t c, fp4_t a, fp4_t b)
Subtracts a quartic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the quartic extension field element.
[in] b - the quartic extension field element.
Definition at line 130 of file relic_fpx_add.c.
Referenced by fp8_inv(), fp8_mul_basic(), fp8_sqr_basic(), fp8_sqr_cyc(), and fp8_sub().
fp4_dbl()
void fp4_dbl (fp4_t c, fp4_t a)
Doubles a quartic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the quartic extension field element to double.
Definition at line 135 of file relic_fpx_add.c.
Referenced by fp8_dbl(), fp8_sqr_basic(), and fp8_sqr_cyc().
fp4_neg()
void fp4_neg (fp4_t c, fp4_t a)
Negates a quartic extension field element. Computes c = -a.
Parameters
[out] C - the result.
[out] A - the quartic extension field element to negate.
Definition at line 141 of file relic_fpx_add.c.
References fp2_neg().
Referenced by fp8_inv(), fp8_inv_cyc(), and fp8_neg().
fp6_add()
void fp6_add (fp6_t c, fp6_t a, fp6_t b)
Adds two sextic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first sextic extension field element.
[in] b - the second sextic extension field element.
Definition at line 146 of file relic_fpx_add.c.
Referenced by fp12_add(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_mul_unr(), and fp12_sqr_basic().
fp6_sub()
void fp6_sub (fp6_t c, fp6_t a, fp6_t b)
Subtracts a sextic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 152 of file relic_fpx_add.c.
Referenced by fp12_inv(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_sqr_basic(), and fp12_sub().
fp6_dbl()
void fp6_dbl (fp6_t c, fp6_t a)
Doubles a sextic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to double.
Definition at line 158 of file relic_fpx_add.c.
Referenced by fp12_dbl(), and fp12_sqr_basic().
fp6_neg()
void fp6_neg (fp6_t c, fp6_t a)
Negates a sextic extension field element. Computes c = -a.
Parameters
[out] C - the result.
[out] A - the sextic extension field element to negate.
Definition at line 164 of file relic_fpx_add.c.
References fp2_neg().
Referenced by fp12_inv(), fp12_inv_cyc(), and fp12_neg().
fp8_add()
void fp8_add (fp8_t c, fp8_t a, fp8_t b)
Adds two octic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first octic extension field element.
[in] b - the second octic extension field element.
Definition at line 170 of file relic_fpx_add.c.
References fp4_add().
Referenced by ep8_dbl_basic(), fp24_add(), fp24_inv(), fp24_mul_basic(), fp24_mul_dxs(), fp24_mul_unr(), fp24_sqr_basic(), fp24_sqr_unr(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_mul_dxs(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), pp_add_k48_projc(), and pp_dbl_k48_projc().
fp8_sub()
void fp8_sub (fp8_t c, fp8_t a, fp8_t b)
Subtracts an octic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the octic extension field element.
[in] b - the octic extension field element.
Definition at line 175 of file relic_fpx_add.c.
References fp4_sub().
Referenced by ep8_add_basic(), ep8_dbl_basic(), fp24_inv(), fp24_mul_basic(), fp24_mul_dxs(), fp24_sqr_basic(), fp24_sqr_unr(), fp24_sub(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), pp_add_k48_basic(), pp_add_k48_projc(), pp_dbl_k48_basic(), and pp_dbl_k48_projc().
fp8_dbl()
void fp8_dbl (fp8_t c, fp8_t a)
Doubles an octic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the octic extension field element to double.
Definition at line 180 of file relic_fpx_add.c.
References fp4_dbl().
Referenced by ep8_dbl_basic(), fp24_dbl(), fp24_sqr_basic(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_sqr_cyc_basic(), fp48_sqr_cyc_lazyr(), fp48_sqr_pck_basic(), fp48_sqr_pck_lazyr(), and pp_dbl_k48_projc().
fp8_neg()
void fp8_neg (fp8_t c, fp8_t a)
Negates an octic extension field element. Computes c = -a.
Parameters
[out] C - the result.
[out] A - the octic extension field element to negate.
Definition at line 185 of file relic_fpx_add.c.
References fp4_neg().
Referenced by fp24_neg(), pp_add_k48_projc(), and pp_mil_k48().
fp9_add()
void fp9_add (fp9_t c, fp9_t a, fp9_t b)
Adds two nonic extension field elements. Computes c = a + b.
Parameters
[out] c - the result.
[in] a - the first nonic extension field element.
[in] b - the second nonic extension field element.
Definition at line 190 of file relic_fpx_add.c.
Referenced by ep9_dbl_basic(), fp18_add(), fp18_mul_basic(), fp18_mul_dxs(), fp18_mul_unr(), fp18_sqr_basic(), fp18_sqr_unr(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_mul_dxs(), fp54_sqr_cyc_basic(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), pp_add_k54_projc(), and pp_dbl_k54_projc().
fp9_sub()
void fp9_sub (fp9_t c, fp9_t a, fp9_t b)
Subtracts a nonic extension field element from another. Computes c = a - b.
Parameters
[out] c - the result.
[in] a - the nonic extension field element.
[in] b - the nonic extension field element.
Definition at line 196 of file relic_fpx_add.c.
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_inv(), fp18_mul_basic(), fp18_mul_dxs(), fp18_sqr_basic(), fp18_sub(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_sqr_cyc_basic(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), pp_add_k54_basic(), pp_add_k54_projc(), pp_dbl_k54_basic(), and pp_dbl_k54_projc().
fp9_dbl()
void fp9_dbl (fp9_t c, fp9_t a)
Doubles a nonic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to double.
Definition at line 202 of file relic_fpx_add.c.
Referenced by ep9_dbl_basic(), fp18_dbl(), fp18_sqr_basic(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_sqr_cyc_basic(), fp54_sqr_pck_basic(), fp54_sqr_pck_lazyr(), and pp_dbl_k54_projc().
fp9_neg()
void fp9_neg (fp9_t c, fp9_t a)
Negates a nonic extension field element. Computes c = -a.
Parameters
[out] C - the result.
[out] A - the nonic extension field element to negate.
Definition at line 208 of file relic_fpx_add.c.
References fp3_neg().
Referenced by fp18_inv(), fp18_inv_cyc(), fp18_neg(), pp_add_k54_projc(), and pp_mil_k54().
fp12_add()
void fp12_add (fp12_t c, fp12_t a, fp12_t b)
Adds two dodecic extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first dodecic extension field element.
[in] B - the second dodecic extension field element.
Definition at line 214 of file relic_fpx_add.c.
References fp6_add().
fp12_sub()
void fp12_sub (fp12_t c, fp12_t a, fp12_t b)
Subtracts a dodecic extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first dodecic extension field element.
[in] B - the second dodecic extension field element.
Definition at line 219 of file relic_fpx_add.c.
References fp6_sub().
fp12_neg()
void fp12_neg (fp12_t c, fp12_t a)
Negates a dodecic extension field element.
Parameters
[out] C - the result.
[out] A - the dodecic extension field element to negate.
Definition at line 224 of file relic_fpx_add.c.
References fp6_neg().
fp12_dbl()
void fp12_dbl (fp12_t c, fp12_t a)
Doubles a dodecic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to double.
Definition at line 229 of file relic_fpx_add.c.
References fp6_dbl().
fp18_add()
void fp18_add (fp18_t c, fp18_t a, fp18_t b)
Adds two octdecic extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first octdecic extension field element.
[in] B - the second octdecic extension field element.
Definition at line 234 of file relic_fpx_add.c.
References fp9_add().
Referenced by fp54_add(), fp54_inv(), fp54_mul_basic(), fp54_mul_dxs(), and fp54_sqr_basic().
fp18_sub()
void fp18_sub (fp18_t c, fp18_t a, fp18_t b)
Subtracts an octdecic extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first octdecic extension field element.
[in] B - the second octdecic extension field element.
Definition at line 239 of file relic_fpx_add.c.
References fp9_sub().
Referenced by fp54_inv(), fp54_mul_basic(), fp54_mul_dxs(), fp54_sqr_basic(), and fp54_sub().
fp18_dbl()
void fp18_dbl (fp18_t c, fp18_t a)
Doubles an octdecic extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the octdecic extension field element to double.
Definition at line 244 of file relic_fpx_add.c.
References fp9_dbl().
Referenced by fp54_dbl(), and fp54_sqr_basic().
fp18_neg()
void fp18_neg (fp18_t c, fp18_t a)
Negates an octdecic extension field element.
Parameters
[out] C - the result.
[out] A - the octdecic extension field element to negate.
Definition at line 249 of file relic_fpx_add.c.
References fp9_neg().
Referenced by fp54_inv_cyc(), and fp54_neg().
fp24_add()
void fp24_add (fp24_t c, fp24_t a, fp24_t b)
Adds two 24-degree extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first 24-degree extension field element.
[in] B - the second 24-degree extension field element.
Definition at line 254 of file relic_fpx_add.c.
References fp8_add().
Referenced by fp48_add(), fp48_mul_basic(), fp48_mul_dxs(), and fp48_sqr_basic().
fp24_sub()
void fp24_sub (fp24_t c, fp24_t a, fp24_t b)
Subtracts a 24-degree extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first 24-degree extension field element.
[in] B - the second 24-degree extension field element.
Definition at line 260 of file relic_fpx_add.c.
References fp8_sub().
Referenced by fp48_inv(), fp48_mul_basic(), fp48_mul_dxs(), fp48_sqr_basic(), and fp48_sub().
fp24_neg()
void fp24_neg (fp24_t c, fp24_t a)
Negates a 24-degree extension field element.
Parameters
[out] C - the result.
[out] A - the 24-degree extension field element to negate.
Definition at line 266 of file relic_fpx_add.c.
References fp8_neg().
Referenced by fp48_inv(), fp48_inv_cyc(), and fp48_neg().
fp24_dbl()
void fp24_dbl (fp24_t c, fp24_t a)
Doubles a 24-degree extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the octic extension field element to double.
Definition at line 272 of file relic_fpx_add.c.
References fp8_dbl().
Referenced by fp48_dbl(), and fp48_sqr_basic().
fp48_add()
void fp48_add (fp48_t c, fp48_t a, fp48_t b)
Adds two 48-extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first 48-extension field element.
[in] B - the second 48-extension field element.
Definition at line 278 of file relic_fpx_add.c.
References fp24_add().
fp48_sub()
void fp48_sub (fp48_t c, fp48_t a, fp48_t b)
Subtracts a 48-extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first 48-extension field element.
[in] B - the second 48-extension field element.
Definition at line 283 of file relic_fpx_add.c.
References fp24_sub().
fp48_neg()
void fp48_neg (fp48_t c, fp48_t a)
Negates a 48-extension field element.
Parameters
[out] C - the result.
[out] A - the 48-extension field element to negate.
Definition at line 288 of file relic_fpx_add.c.
References fp24_neg().
fp48_dbl()
void fp48_dbl (fp48_t c, fp48_t a)
Doubles a 48-extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to double.
Definition at line 293 of file relic_fpx_add.c.
References fp24_dbl().
fp54_add()
void fp54_add (fp54_t c, fp54_t a, fp54_t b)
Adds two 54-extension field elements. Computes C = A + B.
Parameters
[out] C - the result.
[in] A - the first 54-extension field element.
[in] B - the second 54-extension field element.
Definition at line 298 of file relic_fpx_add.c.
References fp18_add().
fp54_sub()
void fp54_sub (fp54_t c, fp54_t a, fp54_t b)
Subtracts a 54-extension field element from another. Computes C = A - B.
Parameters
[out] C - the result.
[in] A - the first 54-extension field element.
[in] B - the second 54-extension field element.
Definition at line 304 of file relic_fpx_add.c.
References fp18_sub().
fp54_neg()
void fp54_neg (fp54_t c, fp54_t a)
Negates a 54-extension field element.
Parameters
[out] C - the result.
[out] A - the 54-extension field element to negate.
Definition at line 310 of file relic_fpx_add.c.
References fp18_neg().
fp54_dbl()
void fp54_dbl (fp54_t c, fp54_t a)
Doubles a 54-extension field element. Computes c = 2 * a.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to double.
Definition at line 316 of file relic_fpx_add.c.
References fp18_dbl().