RELIC: src/epx/relic_ep3_util.c File Reference
relic_ep3_util.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
int ep3_is_infty (const ep3_t p)
void ep3_set_infty (ep3_t p)
void ep3_copy (ep3_t r, const ep3_t p)
void ep3_rand (ep3_t p)
void ep3_blind (ep3_t r, const ep3_t p)
void ep3_rhs (fp3_t rhs, const fp3_t x)
int ep3_on_curve (const ep3_t p)
void ep3_tab (ep3_t *t, const ep3_t p, int w)
void ep3_print (const ep3_t p)
size_t ep3_size_bin (const ep3_t a, int pack)
void ep3_read_bin (ep3_t a, const uint8_t *bin, size_t len)
void ep3_write_bin (uint8_t *bin, size_t len, const ep3_t a, int pack)
Detailed Description
Implementation of comparison for points on prime elliptic curves over a cubic extension field.
Definition in file relic_ep3_util.c.
Function Documentation
ep3_is_infty()
int ep3_is_infty (const ep3_t p)
Tests if a point on an elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep3_util.c.
References fp3_is_zero().
Referenced by ep3_add_basic(), ep3_add_jacob(), ep3_add_projc(), ep3_add_slp_basic(), ep3_cmp(), ep3_dbl_basic(), ep3_dbl_jacob(), ep3_dbl_projc(), ep3_dbl_slp_basic(), ep3_mul_basic(), ep3_mul_dig(), ep3_mul_lwnaf(), ep3_mul_lwreg(), ep3_mul_monty(), ep3_mul_sim_gen(), ep3_mul_sim_inter(), ep3_mul_sim_joint(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_neg(), ep3_norm(), ep3_norm_sim(), ep3_on_curve(), ep3_psi(), ep3_size_bin(), ep3_write_bin(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), pp_map_weilp_k18(), and pp_norm_k18().
ep3_set_infty()
void ep3_set_infty (ep3_t p)
Assigns an elliptic curve point to the point at infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep3_util.c.
References BASIC, and fp3_zero().
Referenced by ep3_dbl_basic(), ep3_dbl_jacob(), ep3_dbl_projc(), ep3_dbl_slp_basic(), ep3_map(), ep3_mul_basic(), ep3_mul_dig(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_lwnaf(), ep3_mul_fix_plain(), ep3_mul_gen(), ep3_mul_gls_imp(), ep3_mul_lwnaf(), ep3_mul_lwreg(), ep3_mul_monty(), ep3_mul_naf_imp(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_imp(), ep3_mul_sim_dig(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_neg(), ep3_norm(), ep3_psi(), ep3_read_bin(), ep3_sub(), and pp_norm_k18().
ep3_copy()
void ep3_copy (ep3_t r, const ep3_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the elliptic curve point to copy.
Definition at line 50 of file relic_ep3_util.c.
References fp3_copy().
Referenced by ep3_add_basic(), ep3_add_jacob(), ep3_add_projc(), ep3_add_slp_basic(), ep3_blind(), ep3_cmp(), ep3_curve_get_gen(), ep3_curve_set_twist(), ep3_frb(), ep3_mul_dig(), ep3_mul_fix_combs(), ep3_mul_gls_imp(), ep3_mul_pre_basic(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_norm(), ep3_norm_imp(), ep3_tab(), pp_add_k18_basic(), pp_dbl_k18_basic(), pp_mil_k18(), and pp_norm_k18().
ep3_rand()
void ep3_rand (ep3_t p)
Assigns a random value to an elliptic curve point.
Parameters
[out] p - the elliptic curve point to assign.
Definition at line 57 of file relic_ep3_util.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ep3_curve_get_ord(), ep3_mul_gen(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_blind()
void ep3_blind (ep3_t r, const ep3_t p)
Randomizes coordinates of an elliptic curve point.
Parameters
[out] r - the blinded prime elliptic curve point.
[in] p - the prime elliptic curve point to blind.
Definition at line 81 of file relic_ep3_util.c.
References ep3_copy(), ERR_CAUGHT, fp3_free, fp3_mul, fp3_new, fp3_null, fp3_rand(), fp3_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_monty().
ep3_rhs()
void ep3_rhs (fp3_t rhs, const fp3_t x)
Computes the right-hand side of the elliptic curve equation at the x-coordinate of a certain prime elliptic curve point.
Parameters
[out] rhs - the result.
[in] x - the x-coordinate of the point.
Definition at line 112 of file relic_ep3_util.c.
References ep3_curve_get_a(), ep3_curve_get_b(), ep3_curve_opt_a(), ep3_curve_opt_b(), ERR_CAUGHT, fp3_add, fp3_add_dig(), fp3_copy(), fp3_free, fp3_mul, fp3_mul_dig(), fp3_new, fp3_null, fp3_sqr, fp3_sub_dig(), fp_add_dig(), fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep3_map(), and ep3_on_curve().
ep3_on_curve()
int ep3_on_curve (const ep3_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 176 of file relic_ep3_util.c.
References ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ep3_rhs(), ERR_CAUGHT, fp3_cmp(), fp3_sqr, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_read_bin().
ep3_tab()
void ep3_tab (ep3_t * t, const ep3_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 199 of file relic_ep3_util.c.
References ep3_add, ep3_copy(), ep3_dbl, ep3_norm(), and ep3_norm_sim().
Referenced by ep3_mul_naf_imp(), ep3_mul_pre_lwnaf(), ep3_mul_reg_imp(), and ep3_mul_sim_plain().
ep3_print()
void ep3_print (const ep3_t p)
Prints an elliptic curve point.
Parameters
[in] p - the elliptic curve point to print.
Definition at line 220 of file relic_ep3_util.c.
References fp3_print().
ep3_size_bin()
size_t ep3_size_bin (const ep3_t a, int pack)
Returns the number of bytes necessary to store a prime elliptic curve point over a cubic extension with optional point compression.
Parameters
[in] a - the prime field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 226 of file relic_ep3_util.c.
References ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep3_read_bin()
void ep3_read_bin (ep3_t a, const uint8_t * bin, size_t len)
Reads a prime elliptic curve point over a cubic extension from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 252 of file relic_ep3_util.c.
References BASIC, ep3_on_curve(), ep3_set_infty(), ERR_NO_BUFFER, ERR_NO_VALID, fp3_read_bin(), fp3_set_dig(), RLC_FP_BYTES, and RLC_THROW.
ep3_write_bin()
void ep3_write_bin (uint8_t * bin, size_t len, const ep3_t a, int pack)
Writes a prime elliptic curve pointer over a cubic extension to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime elliptic curve point to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 286 of file relic_ep3_util.c.
References ep3_free, ep3_is_infty(), ep3_new, ep3_norm(), ep3_null, ERR_CAUGHT, ERR_NO_BUFFER, fp3_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.