RELIC: include/relic_core.h File Reference
relic_core.h File Reference
Core functions
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "relic_err.h"
#include "relic_bn.h"
#include "relic_eb.h"
#include "relic_epx.h"
#include "relic_ed.h"
#include "relic_conf.h"
#include "relic_bench.h"
#include "relic_rand.h"
#include "relic_label.h"
#include "relic_alloc.h"
Data Structures
struct _ctx_t
Macros
#define RLC_OK 0
#define RLC_ERR 1
#define RLC_LT -1
#define RLC_EQ 0
#define RLC_GT 1
#define RLC_NE 2
#define RLC_ZERO 0
#define RLC_ONE 1
#define RLC_TWO 2
#define RLC_MIN3 3
#define RLC_TINY 4
#define RLC_HUGE 5
#define RLC_TERMS 16
Typedefs
typedef struct _ctx_t ctx_t
Functions
int core_init (void)
int core_clean (void)
ctx_t * core_get (void)
void core_set (ctx_t *ctx)
Detailed Description
Interface of the library core functions.
Definition in file relic_core.h.
Macro Definition Documentation
RLC_OK
#define RLC_OK 0
Indicates that the function executed correctly.
Definition at line 71 of file relic_core.h.
RLC_ERR
#define RLC_ERR 1
Indicates that an error occurred during the function execution.
Definition at line 76 of file relic_core.h.
RLC_LT
#define RLC_LT -1
Indicates that a comparison returned that the first argument was lesser than the second argument.
Definition at line 82 of file relic_core.h.
RLC_EQ
#define RLC_EQ 0
Indicates that a comparison returned that the first argument was equal to the second argument.
Definition at line 88 of file relic_core.h.
RLC_GT
#define RLC_GT 1
Indicates that a comparison returned that the first argument was greater than the second argument.
Definition at line 94 of file relic_core.h.
RLC_NE
#define RLC_NE 2
Indicates that two incomparable elements are not equal.
Definition at line 99 of file relic_core.h.
RLC_ZERO
#define RLC_ZERO 0
Optimization identifer for the case where a coefficient is 0.
Definition at line 104 of file relic_core.h.
RLC_ONE
#define RLC_ONE 1
Optimization identifer for the case where a coefficient is 1.
Definition at line 109 of file relic_core.h.
RLC_TWO
#define RLC_TWO 2
Optimization identifer for the case where a coefficient is 2.
Definition at line 114 of file relic_core.h.
RLC_MIN3
#define RLC_MIN3 3
Optimization identifier for the case where a coefficient is -3.
Definition at line 119 of file relic_core.h.
RLC_TINY
#define RLC_TINY 4
Optimization identifer for the case where a coefficient is small.
Definition at line 124 of file relic_core.h.
RLC_HUGE
#define RLC_HUGE 5
Optimization identifier for the case where the coefficient is arbitrary.
Definition at line 129 of file relic_core.h.
RLC_TERMS
#define RLC_TERMS 16
Maximum number of terms to describe a sparse object.
Definition at line 134 of file relic_core.h.
Typedef Documentation
ctx_t
typedef struct _ctx_t ctx_t
Library context.
Function Documentation
core_init()
int core_init (void)
Initializes the library.
Returns
RLC_OK if no error occurs, RLC_ERR otherwise.
Definition at line 98 of file relic_core.c.
References arch_init(), CATCH_ANY, _ctx_t::code, core_ctx, eb_curve_init(), ed_curve_init(), ep_curve_init(), ERR_NO_BUFFER, ERR_NO_CONFIG, ERR_NO_CURVE, ERR_NO_FIELD, ERR_NO_FILE, ERR_NO_MEMORY, ERR_NO_PRECI, ERR_NO_READ, ERR_NO_VALID, fb_poly_init(), first_ctx, fp_prime_init(), _ctx_t::last, MSG_NO_BUFFER, MSG_NO_CONFIG, MSG_NO_CURVE, MSG_NO_FIELD, MSG_NO_FILE, MSG_NO_MEMORY, MSG_NO_PRECI, MSG_NO_READ, MSG_NO_VALID, pp_map_init(), rand_init(), _ctx_t::reason, RLC_ERR, RLC_OK, and TRY.
core_clean()
int core_clean (void)
Finalizes the library.
Returns
RLC_OK if no error occurs, RLC_ERR otherwise.
Definition at line 154 of file relic_core.c.
References arch_clean(), core_ctx, eb_curve_clean(), ed_curve_clean(), ep_curve_clean(), fb_poly_clean(), fp_prime_clean(), pp_map_clean(), rand_clean(), and RLC_OK.
core_get()
ctx_t* core_get (void)
Returns a pointer to the current library context.
Returns
a pointer to the library context.
Definition at line 182 of file relic_core.c.
References core_ctx.
Referenced by bench_after(), bench_before(), bench_compute(), bench_print(), bench_reset(), bench_total(), eb_curve_clean(), eb_curve_get_a(), eb_curve_get_b(), eb_curve_get_cof(), eb_curve_get_gen(), eb_curve_get_ord(), eb_curve_get_tab(), eb_curve_init(), eb_curve_is_kbltz(), eb_curve_opt_a(), eb_curve_opt_b(), eb_curve_set(), eb_param_get(), eb_param_level(), eb_param_print(), eb_param_set(), ed_add_basic(), ed_add_extnd(), ed_add_projc(), ed_curve_clean(), ed_curve_get_cof(), ed_curve_get_gen(), ed_curve_get_ord(), ed_curve_get_tab(), ed_curve_init(), ed_dbl_basic(), ed_dbl_extnd(), ed_dbl_projc(), ed_map(), ed_param_get(), ed_param_set(), ed_rhs(), ed_upk(), ep2_curve_clean(), ep2_curve_get_a(), ep2_curve_get_b(), ep2_curve_get_cof(), ep2_curve_get_gen(), ep2_curve_get_ord(), ep2_curve_get_tab(), ep2_curve_init(), ep2_curve_is_twist(), ep2_curve_set(), ep2_curve_set_twist(), ep_curve_clean(), ep_curve_get_a(), ep_curve_get_b(), ep_curve_get_beta(), ep_curve_get_cof(), ep_curve_get_gen(), ep_curve_get_ord(), ep_curve_get_tab(), ep_curve_get_v1(), ep_curve_get_v2(), ep_curve_init(), ep_curve_is_endom(), ep_curve_is_pairf(), ep_curve_is_super(), ep_curve_opt_a(), ep_curve_opt_b(), ep_curve_set_endom(), ep_curve_set_plain(), ep_curve_set_super(), ep_param_get(), ep_param_set(), ep_sw_b12(), ep_sw_bn(), err_full_msg(), err_get_code(), err_get_msg(), err_simple_msg(), fb_param_get(), fb_param_set(), fb_poly_add(), fb_poly_get(), fb_poly_get_chain(), fb_poly_get_rdc(), fb_poly_get_slv(), fb_poly_get_srz(), fb_poly_get_trc(), fb_poly_init(), fb_poly_set(), fb_poly_set_dense(), fb_poly_set_penta(), fb_poly_set_trino(), fb_poly_tab_sqr(), fb_poly_tab_srz(), find_chain(), find_solve(), find_srz(), find_trace(), fp2_field_get_qnr(), fp2_field_init(), fp2_mul_frb(), fp3_field_init(), fp3_mul_frb(), fp_add_dig(), fp_param_get(), fp_param_set(), fp_prime_calc(), fp_prime_clean(), fp_prime_conv(), fp_prime_conv_dig(), fp_prime_get(), fp_prime_get_cnr(), fp_prime_get_conv(), fp_prime_get_mod8(), fp_prime_get_par(), fp_prime_get_par_sps(), fp_prime_get_qnr(), fp_prime_get_rdc(), fp_prime_get_sps(), fp_prime_init(), fp_prime_set(), fp_prime_set_pairf(), fp_prime_set_pmers(), fp_sub_dig(), pp_mil_k54(), rand_clean(), and rand_init().
core_set()
void core_set (ctx_t * ctx)
Switched the library context to a new context.
Parameters
[in] ctx - the new library context.
Definition at line 186 of file relic_core.c.
References core_ctx.