RELIC: src/cp/relic_cp_sokaka.c File Reference
relic_cp_sokaka.c File Reference
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include <stdint.h>
#include "relic.h"
#include "relic_test.h"
#include "relic_bench.h"
Functions
int cp_sokaka_gen (bn_t master)
int cp_sokaka_gen_prv (sokaka_t k, char *id, int len, bn_t master)
int cp_sokaka_key (uint8_t *key, unsigned int key_len, char *id1, int len1, sokaka_t k, char *id2, int len2)
Detailed Description
Implementation of the Sakai-Ohgishi-Kasahara Identity-Based Non-Interactive Authenticated Key Agreement scheme.
Definition in file relic_cp_sokaka.c.
Function Documentation
cp_sokaka_gen()
int cp_sokaka_gen (bn_t master)
Generates a master key for the SOKAKA identity-based non-interactive authenticated key agreement protocol.
Parameters
[out] master - the master key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 47 of file relic_cp_sokaka.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, FINALLY, g1_get_ord, result, RLC_ERR, RLC_OK, and TRY.
cp_sokaka_gen_prv()
int cp_sokaka_gen_prv (sokaka_t k, char * id, int len, bn_t master)
Generates a private key for the SOKAKA protocol.
Parameters
[out] k - the private key.
[in] id - the identity.
[in] len - the length of identity in bytes.
[in] master - the master key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 68 of file relic_cp_sokaka.c.
References g1_map, g1_mul, g2_map, g2_mul, pc_map_is_type1, RLC_OK, _sokaka::s1, and _sokaka::s2.
cp_sokaka_key()
int cp_sokaka_key (uint8_t * key, unsigned int key_len, char * id1, int len1, sokaka_t k, char * id2, int len2)
Computes a shared key between two entities.
Parameters
[out] key - the shared key.
[int] key_len - the intended shared key length in bytes.
[in] id1 - the first identity.
[in] len1 - the length of the first identity in bytes.
[in] k - the private key of the first identity.
[in] id2 - the second identity.
[in] len2 - the length of the second identity in bytes.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 81 of file relic_cp_sokaka.c.
References CATCH_ANY, ERR_NO_MEMORY, ERR_NO_VALID, FINALLY, g1_free, g1_map, g1_new, g1_null, g2_free, g2_map, g2_new, g2_null, gt_free, gt_new, gt_null, gt_size_bin, gt_write_bin, md_kdf(), pc_map, pc_map_is_type1, result, RLC_ALLOCA, RLC_ERR, RLC_FREE, RLC_OK, _sokaka::s1, _sokaka::s2, THROW, and TRY.