RELIC: src/bn/relic_bn_lag.c File Reference
relic_bn_lag.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
#include "relic_bn.h"
Functions
void bn_lag (bn_t *c, const bn_t *a, const bn_t b, size_t n)
void bn_evl (bn_t c, const bn_t *a, const bn_t x, const bn_t b, size_t n)
Detailed Description
Implementation of the modular Lagrante interpolation.
Definition in file relic_bn_lag.c.
Function Documentation
bn_lag()
void bn_lag (bn_t * c, const bn_t * a, const bn_t b, size_t n)
Computes the coefficients of the polynomial representing the Lagrange interpolation for a modulus and a given set of roots. Computes c(x) = \prod_{0 <= i < n}(x - ai) mod q.
Parameters
[out] c - the coefficients of the polynomial.
[in] a - the set of roots.
[in] b - the modulus.
[in] n - the number of roots to interpolate.
Definition at line 39 of file relic_bn_lag.c.
References bn_copy(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_set_dig(), bn_sub(), bn_zero(), ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by cp_pbpsi_ask().
bn_evl()
void bn_evl (bn_t c, const bn_t * a, const bn_t x, const bn_t b, size_t n)
Evaluates an interpolated n-degree polynomial over a value in a modular way, given the (n+1) coefficients of the polynomial and the modulus. Computes c = a(x) mod q.
Parameters
[out] c - the result of the evaluation.
[in] a - the coefficients of the polynomial.
[in] x - the value to evaluate.
[in] b - the modulus.
[in] n - the degree of the polynomial.
Definition at line 87 of file relic_bn_lag.c.
References bn_add(), bn_mod, bn_mul, and bn_zero().
Referenced by mpc_sss_gen().