RELIC: src/ed/relic_ed_curve.c File Reference
relic_ed_curve.c File Reference
Edwards curves over Edwards fields
#include "relic_core.h"
Functions
void ed_curve_init (void)
void ed_curve_clean (void)
void ed_curve_get_gen (ed_t g)
void ed_curve_get_ord (bn_t n)
void ed_curve_get_cof (bn_t h)
const ed_t * ed_curve_get_tab (void)
Detailed Description
Implementation of the point addition on prime elliptic twisted Edwards curves.
Version
$Id$
Definition in file relic_ed_curve.c.
Function Documentation
ed_curve_init()
void ed_curve_init (void)
Multiplies an Edwards elliptic curve point by an integer. Computes R = kP.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer. Builds a precomputation table for multiplying a fixed Edwards elliptic point.
[out] T - the precomputation table.
[in] P - the point to multiply. Multiplies a fixed Edwards elliptic point using a precomputation table. Computes R = kP.
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer. Multiplies and adds two Edwards elliptic curve points simultaneously. Computes R = kP + mQ.
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] M - the second integer, Initializes the Edwards elliptic curve arithmetic module.
Definition at line 35 of file relic_ed_curve.c.
References bn_init(), core_get(), _ctx_t::ed_g, _ctx_t::ed_h, _ctx_t::ed_pre, _ctx_t::ed_ptr, _ctx_t::ed_r, ed_set_infty(), and RLC_FP_DIGS.
Referenced by core_init().
ed_curve_clean()
void ed_curve_clean (void)
Finalizes the Edwards elliptic curve arithmetic module.
Definition at line 47 of file relic_ed_curve.c.
References bn_clean(), core_get(), _ctx_t::ed_h, and _ctx_t::ed_r.
Referenced by core_clean().
ed_curve_get_gen()
void ed_curve_get_gen (ed_t g)
Returns the generator of the group of points in the curve.
Parameters
[out] g - the returned generator.
Definition at line 53 of file relic_ed_curve.c.
References core_get(), and ed_copy().
Referenced by ed_mul_gen(), and ed_mul_sim_gen().
ed_curve_get_ord()
void ed_curve_get_ord (bn_t r)
Returns the order of the group of points in the Edwards curve.
Parameters
[out] r - the returned order.
Definition at line 57 of file relic_ed_curve.c.
References bn_copy(), and core_get().
Referenced by ed_mul_combs_plain(), ed_mul_fix_combd(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_trick(), and ed_rand().
ed_curve_get_cof()
void ed_curve_get_cof (bn_t h)
Returns the cofactor of the Edwards elliptic curve.
Parameters
[out] n - the returned cofactor.
Definition at line 61 of file relic_ed_curve.c.
References bn_copy(), and core_get().
ed_curve_get_tab()
const ed_t* ed_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 65 of file relic_ed_curve.c.
References core_get(), and _ctx_t::ed_ptr.
Referenced by ed_mul_gen(), ed_mul_sim_gen(), and ed_param_set().