RELIC: src/bn/relic_bn_inv.c File Reference
relic_bn_inv.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
#include "relic_bn.h"
Functions
void bn_mod_inv (bn_t c, const bn_t a, const bn_t b)
void bn_mod_inv_sim (bn_t *c, const bn_t *a, const bn_t b, int n)
Detailed Description
Implementation of the multiple precision integer modular inversion.
Definition in file relic_bn_inv.c.
Function Documentation
bn_mod_inv()
void bn_mod_inv (bn_t c, const bn_t a, const bn_t b)
Computes the modular inverse of a multiple precision integer. Computes c such that a*c mod b = 1.
Parameters
[out] c - the result.
[in] a - the element to invert. param[in] b - the modulus.
Definition at line 39 of file relic_bn_inv.c.
References bn_add(), bn_cmp_dig(), bn_copy(), bn_free, bn_gcd_ext, bn_new, bn_null, bn_sign(), ERR_CAUGHT, ERR_NO_VALID, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by bn_mod_inv_sim(), bn_mxp_basic(), bn_mxp_monty(), bn_mxp_slide(), cp_bbs_sig(), cp_cmlhs_sig(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ghpe_dec(), cp_lvprv_ask(), cp_lvprv_gen(), cp_lvpub_gen(), cp_pdprv_ask(), cp_pdprv_gen(), cp_pdpub_gen(), cp_phpe_dec(), cp_phpe_gen(), cp_rsa_gen(), cp_shipsi_ans(), cp_shipsi_gen(), cp_shpe_dec(), cp_shpe_gen(), and cp_zss_sig().
bn_mod_inv_sim()
void bn_mod_inv_sim (bn_t * c, const bn_t * a, const bn_t b, int n)
Computes the modular inverse of multiple precision integers simultaneously. Computes c_i such that a_i * c_i mod b = 1.
Parameters
[out] c - the results.
[in] a - the elements to invert. param[in] b - the modulus.
[in] n - the number of elements.
Definition at line 67 of file relic_bn_inv.c.
References bn_copy(), bn_free, bn_mod, bn_mod_inv(), bn_mul, bn_new, bn_null, ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by cp_etrs_sig(), cp_etrs_uni(), cp_etrs_ver(), and mpc_sss_key().