RELIC: src/epx/relic_ep2_frb.c File Reference
relic_ep2_frb.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
void ep2_frb (ep2_t r, ep2_t p, int i)
Detailed Description
Implementation of frobenius action on prime elliptic curves over quadratic extensions.
Definition in file relic_ep2_frb.c.
Function Documentation
ep2_frb()
void ep2_frb (ep2_t r, ep2_t p, int i)
Computes a power of the Gailbraith-Lin-Scott homomorphism of a point represented in affine coordinates on a twisted elliptic curve over a quadratic exension. That is, Psi^i(P) = Twist(P)(Frob^i(unTwist(P)). On the trace-zero group of a quadratic twist, consists of a power of the Frobenius map of a point represented in affine coordinates in an elliptic curve over a quadratic exension. Computes Frob^i(P) = (p^i)P.
Parameters
[out] r - the result in affine coordinates.
[in] p - a point in affine coordinates.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_ep2_frb.c.
References ep2_copy(), ep2_curve_is_twist(), EP_MTYPE, fp2_frb(), fp2_mul_art(), fp2_mul_frb(), ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_glv_imp(), g2_is_valid(), and pp_fin_k12_oatep().