RELIC: src/cp/relic_cp_bdpe.c File Reference
relic_cp_bdpe.c File Reference
Cryptographic protocols
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_rand.h"
#include "relic_bn.h"
#include "relic_util.h"
#include "relic_cp.h"
#include "relic_md.h"
Functions
int cp_bdpe_gen (bdpe_t pub, bdpe_t prv, dig_t block, int bits)
int cp_bdpe_enc (uint8_t *out, int *out_len, dig_t in, bdpe_t pub)
int cp_bdpe_dec (dig_t *out, uint8_t *in, int in_len, bdpe_t prv)
Detailed Description
Implementation of Benaloh's Dense Probabilistic Encryption cryptosystem.
Definition in file relic_cp_bdpe.c.
Function Documentation
cp_bdpe_gen()
int cp_bdpe_gen (bdpe_t pub, bdpe_t prv, dig_t block, int bits)
Generates a key pair for Benaloh's Dense Probabilistic Encryption.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] block - the block size.
[in] bits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 46 of file relic_cp_bdpe.c.
References bn_add_dig(), bn_cmp_dig(), bn_copy(), bn_div_dig(), bn_free(), bn_gcd_dig(), bn_is_prime(), bn_is_prime_basic(), bn_mul_dig(), bn_null, bn_rand(), bn_set_dig(), bn_sub_dig(), CATCH_ANY, bn_st::dp, ERR_NO_VALID, FINALLY, _bdpe_t::n, _bdpe_t::p, _bdpe_t::q, result, RLC_EQ, RLC_ERR, RLC_OK, RLC_POS, _bdpe_t::t, THROW, TRY, util_bits_dig(), and _bdpe_t::y.
cp_bdpe_enc()
int cp_bdpe_enc (uint8_t * out, int * out_len, dig_t in, bdpe_t pub)
Encrypts using Benaloh's cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the plaintext as a small integer.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 118 of file relic_cp_bdpe.c.
References bn_free(), bn_mod, bn_mxp_dig(), bn_null, bn_rand_mod(), bn_set_dig(), bn_size_bin(), bn_write_bin(), CATCH_ANY, FINALLY, _bdpe_t::n, result, RLC_ERR, RLC_OK, _bdpe_t::t, TRY, and _bdpe_t::y.
cp_bdpe_dec()
int cp_bdpe_dec (dig_t * out, uint8_t * in, int in_len, bdpe_t prv)
Decrypts using Benaloh's cryptosystem.
Parameters
[out] out - the decrypted small integer.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 162 of file relic_cp_bdpe.c.
References bn_add_dig(), bn_cmp(), bn_div_dig(), bn_free(), bn_mxp_dig(), bn_null, bn_read_bin(), bn_size_bin(), bn_sub(), CATCH_ANY, FINALLY, _bdpe_t::n, _bdpe_t::p, _bdpe_t::q, result, RLC_EQ, RLC_ERR, RLC_OK, _bdpe_t::t, TRY, and _bdpe_t::y.