RELIC: src/epx/relic_ep4_util.c File Reference
relic_ep4_util.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
int ep4_is_infty (const ep4_t p)
void ep4_set_infty (ep4_t p)
void ep4_copy (ep4_t r, const ep4_t p)
void ep4_rand (ep4_t p)
void ep4_blind (ep4_t r, const ep4_t p)
void ep4_rhs (fp4_t rhs, const fp4_t x)
int ep4_on_curve (const ep4_t p)
void ep4_tab (ep4_t *t, const ep4_t p, int w)
void ep4_print (const ep4_t p)
size_t ep4_size_bin (const ep4_t a, int pack)
void ep4_read_bin (ep4_t a, const uint8_t *bin, size_t len)
void ep4_write_bin (uint8_t *bin, size_t len, const ep4_t a, int pack)
Detailed Description
Implementation of comparison for points on prime elliptic curves over a quartic extension field.
Definition in file relic_ep4_util.c.
Function Documentation
ep4_is_infty()
int ep4_is_infty (const ep4_t p)
Tests if a point on an elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep4_util.c.
References fp4_is_zero().
Referenced by ep4_add_basic(), ep4_add_jacob(), ep4_add_projc(), ep4_add_slp_basic(), ep4_cmp(), ep4_dbl_basic(), ep4_dbl_jacob(), ep4_dbl_projc(), ep4_dbl_slp_basic(), ep4_mul_basic(), ep4_mul_dig(), ep4_mul_lwnaf(), ep4_mul_lwreg(), ep4_mul_monty(), ep4_mul_sim_gen(), ep4_mul_sim_inter(), ep4_mul_sim_joint(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_neg(), ep4_norm(), ep4_norm_sim(), ep4_on_curve(), ep4_psi(), ep4_size_bin(), ep4_write_bin(), pp_map_k24(), pp_map_oatep_k16(), pp_map_sim_k24(), pp_map_sim_oatep_k16(), pp_map_sim_tatep_k16(), pp_map_sim_weilp_k16(), pp_map_tatep_k16(), pp_map_weilp_k16(), pp_norm_k16(), and pp_norm_k24().
ep4_set_infty()
void ep4_set_infty (ep4_t p)
Assigns an elliptic curve point to the point at infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep4_util.c.
References BASIC, and fp4_zero().
Referenced by ep4_dbl_basic(), ep4_dbl_jacob(), ep4_dbl_projc(), ep4_dbl_slp_basic(), ep4_map(), ep4_mul_basic(), ep4_mul_dig(), ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_fix_ordin(), ep4_mul_gen(), ep4_mul_gls_imp(), ep4_mul_lwnaf(), ep4_mul_lwreg(), ep4_mul_monty(), ep4_mul_naf_imp(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_dig(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_neg(), ep4_norm(), ep4_psi(), ep4_read_bin(), ep4_sub(), pp_norm_k16(), and pp_norm_k24().
ep4_copy()
void ep4_copy (ep4_t r, const ep4_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the elliptic curve point to copy.
Definition at line 50 of file relic_ep4_util.c.
References fp4_copy().
Referenced by ep4_add_basic(), ep4_add_jacob(), ep4_add_projc(), ep4_add_slp_basic(), ep4_blind(), ep4_cmp(), ep4_curve_get_gen(), ep4_curve_set_twist(), ep4_frb(), ep4_mul_dig(), ep4_mul_fix_combs(), ep4_mul_pre_basic(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_pre_ordin(), ep4_mul_reg_gls(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_norm(), ep4_norm_imp(), ep4_psi(), ep4_tab(), pp_add_k16_basic(), pp_add_k24_basic(), pp_dbl_k16_basic(), pp_dbl_k24_basic(), pp_mil_k16(), pp_mil_k24(), pp_norm_k16(), and pp_norm_k24().
ep4_rand()
void ep4_rand (ep4_t p)
Assigns a random value to an elliptic curve point.
Parameters
[out] p - the elliptic curve point to assign.
Definition at line 57 of file relic_ep4_util.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ep4_curve_get_ord(), ep4_mul_gen(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_blind()
void ep4_blind (ep4_t r, const ep4_t p)
Randomizes coordinates of an elliptic curve point.
Parameters
[out] r - the blinded prime elliptic curve point.
[in] p - the prime elliptic curve point to blind.
Definition at line 81 of file relic_ep4_util.c.
References ep4_copy(), ERR_CAUGHT, fp4_free, fp4_mul, fp4_new, fp4_null, fp4_rand(), fp4_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_monty().
ep4_rhs()
void ep4_rhs (fp4_t rhs, const fp4_t x)
Computes the right-hand side of the elliptic curve equation at the x-coordinate of a certain prime elliptic curve point.
Parameters
[out] rhs - the result.
[in] x - the x-coordinate of the point.
Definition at line 112 of file relic_ep4_util.c.
References ep4_curve_get_a(), ep4_curve_get_b(), ep4_curve_opt_a(), ep4_curve_opt_b(), ERR_CAUGHT, fp4_add(), fp4_copy(), fp4_free, fp4_mul, fp4_mul_dig(), fp4_new, fp4_null, fp4_sqr, fp_add_dig(), fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep4_map(), and ep4_on_curve().
ep4_on_curve()
int ep4_on_curve (const ep4_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 176 of file relic_ep4_util.c.
References ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep4_rhs(), ERR_CAUGHT, fp4_cmp(), fp4_sqr, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_read_bin().
ep4_tab()
void ep4_tab (ep4_t * t, const ep4_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 199 of file relic_ep4_util.c.
References ep4_add, ep4_copy(), ep4_dbl, ep4_norm(), and ep4_norm_sim().
Referenced by ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_mul_reg_imp(), and ep4_mul_sim_plain().
ep4_print()
void ep4_print (const ep4_t p)
Prints an elliptic curve point.
Parameters
[in] p - the elliptic curve point to print.
Definition at line 220 of file relic_ep4_util.c.
References fp4_print().
ep4_size_bin()
size_t ep4_size_bin (const ep4_t a, int pack)
Returns the number of bytes necessary to store a prime elliptic curve point over a quartic extension with optional point compression.
Parameters
[in] a - the prime field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 226 of file relic_ep4_util.c.
References ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep4_read_bin()
void ep4_read_bin (ep4_t a, const uint8_t * bin, size_t len)
Reads a prime elliptic curve point over a quartic extension from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 252 of file relic_ep4_util.c.
References BASIC, ep4_on_curve(), ep4_set_infty(), ERR_NO_BUFFER, ERR_NO_VALID, fp4_read_bin(), fp4_set_dig(), RLC_FP_BYTES, and RLC_THROW.
ep4_write_bin()
void ep4_write_bin (uint8_t * bin, size_t len, const ep4_t a, int pack)
Writes a prime elliptic curve pointer over a quartic extension to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime elliptic curve point to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 286 of file relic_ep4_util.c.
References ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ERR_CAUGHT, ERR_NO_BUFFER, fp4_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.