RELIC: src/epx/relic_ep8_map.c File Reference
relic_ep8_map.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_md.h"
Functions
void ep8_map (ep8_t p, const uint8_t *msg, size_t len)
Detailed Description
Implementation of hashing to a prime elliptic curve over an octic extension field.
Definition in file relic_ep8_map.c.
Function Documentation
ep8_map()
void ep8_map (ep8_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in an elliptic curve over an octic extension.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 40 of file relic_ep8_map.c.
References BASIC, bn_free, bn_get_bit(), bn_new, bn_null, bn_read_bin(), core_get(), _ctx_t::ep8_b, ep8_mul_cof(), ep8_rhs(), ep8_set_infty(), _ctx_t::ep_map_c, ep_param_level(), ERR_CAUGHT, ERR_NO_VALID, fp4_is_zero(), fp8_add(), fp8_copy(), fp8_copy_sec(), fp8_dbl(), fp8_free, fp8_inv(), fp8_is_sqr(), fp8_is_zero(), fp8_mul, fp8_neg(), fp8_new, fp8_null, fp8_set_dig(), fp8_sqr, fp8_srt(), fp8_sub(), fp_is_zero(), fp_mul, FP_PRIME, fp_prime_back(), fp_prime_conv(), md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.