RELIC: include/relic_util.h File Reference
relic_util.h File Reference
Misc utilities
#include "relic_arch.h"
#include "relic_types.h"
#include "relic_label.h"
Macros
#define RLC_MIN(A, B) ((A) < (B) ? (A) : (B))
#define RLC_MAX(A, B) ((A) > (B) ? (A) : (B))
#define RLC_RIP(B, D, V) D = (V) >> (RLC_DIG_LOG); B = (V) - ((D) << (RLC_DIG_LOG));
#define RLC_CEIL(A, B) (((A) - 1) / (B) + 1)
#define RLC_MASK(B) (((dig_t)1 << (B)) - 1)
#define RLC_LMASK (RLC_MASK(RLC_DIG >> 1))
#define RLC_HMASK (RLC_LMASK << (RLC_DIG >> 1))
#define RLC_DMASK (RLC_HMASK | RLC_LMASK)
#define RLC_LOW(D) (D & RLC_LMASK)
#define RLC_HIGH(D) (D >> (RLC_DIG >> 1))
#define RLC_SEL(A, B, C) ((-(C) & ((A) ^ (B))) ^ (A))
#define RLC_SWAP(A, B) ((A) ^= (B), (B) ^= (A), (A) ^= (B))
#define RLC_UPP(C) ((C) - 0x20 * (((C) >= 'a') && ((C) <= 'z')))
#define RLC_ECHO(A) A
#define util_print(F, ...) util_printf(RLC_STR(F), ##__VA_ARGS__)
#define util_banner(L, I)
#define RLC_CAT(A, B) _RLC_CAT(A, B)
#define _RLC_CAT(A, B) A ## B
#define RLC_OPT(...) _OPT(__VA_ARGS__, _imp, _basic, _error)
#define _OPT(...) RLC_ECHO(__OPT(__VA_ARGS__))
#define __OPT(_1, _2, N, ...) N
Functions
uint32_t util_conv_endian (uint32_t i)
uint32_t util_conv_big (uint32_t i)
uint32_t util_conv_little (uint32_t i)
char util_conv_char (dig_t i)
int util_bits_dig (dig_t a)
int util_cmp_const (const void *a, const void *b, int n)
void util_printf (const char *format,...)
void util_print_dig (dig_t a, int pad)
Detailed Description
Interface of misc utilitles.
Definition in file relic_util.h.
Macro Definition Documentation
RLC_MIN
#define RLC_MIN (A, B) ((A) < (B) ? (A) : (B))
Returns the minimum between two numbers.
Parameters
[in] A - the first number.
[in] B - the second number.
Definition at line 53 of file relic_util.h.
RLC_MAX
#define RLC_MAX (A, B) ((A) > (B) ? (A) : (B))
Returns the maximum between two numbers.
Parameters
[in] A - the first number.
[in] B - the second number.
Definition at line 61 of file relic_util.h.
RLC_RIP
#define RLC_RIP (B, D, V) D = (V) >> (RLC_DIG_LOG); B = (V) - ((D) << (RLC_DIG_LOG));
Splits a bit count in a digit count and an updated bit count.
Parameters
[out] B - the resulting bit count.
[out] D - the resulting digit count.
[out] V - the bit count.
Definition at line 70 of file relic_util.h.
RLC_CEIL
#define RLC_CEIL (A, B) (((A) - 1) / (B) + 1)
Computes the ceiling function of an integer division.
Parameters
[in] A - the dividend.
[in] B - the divisor.
Definition at line 79 of file relic_util.h.
RLC_MASK
#define RLC_MASK (B) (((dig_t)1 << (B)) - 1)
Returns a bit mask to isolate the lowest part of a digit.
Parameters
[in] B - the number of bits to isolate.
Definition at line 86 of file relic_util.h.
RLC_LMASK
#define RLC_LMASK (RLC_MASK(RLC_DIG >> 1))
Returns a bit mask to isolate the lowest half of a digit.
Definition at line 91 of file relic_util.h.
RLC_HMASK
#define RLC_HMASK (RLC_LMASK << (RLC_DIG >> 1))
Returns a bit mask to isolate the highest half of a digit.
Definition at line 96 of file relic_util.h.
RLC_DMASK
#define RLC_DMASK (RLC_HMASK | RLC_LMASK)
Bit mask used to return an entire digit.
Definition at line 101 of file relic_util.h.
RLC_LOW
#define RLC_LOW (D) (D & RLC_LMASK)
Returns the lowest half of a digit.
Parameters
[in] D - the digit.
Definition at line 108 of file relic_util.h.
RLC_HIGH
#define RLC_HIGH (D) (D >> (RLC_DIG >> 1))
Returns the highest half of a digit.
Parameters
[in] D - the digit.
Definition at line 115 of file relic_util.h.
RLC_SEL
#define RLC_SEL (A, B, C) ((-(C) & ((A) ^ (B))) ^ (A))
Selects between two values based on the value of a given flag.
Parameters
[in] A - the first argument.
[in] B - the second argument.
[in] C - the selection flag.
Definition at line 124 of file relic_util.h.
RLC_SWAP
#define RLC_SWAP (A, B) ((A) ^= (B), (B) ^= (A), (A) ^= (B))
Swaps two values.
Parameters
[in] A - the first argument.
[in] B - the second argument.
Definition at line 132 of file relic_util.h.
RLC_UPP
#define RLC_UPP (C) ((C) - 0x20 * (((C) >= 'a') && ((C) <= 'z')))
Returns the given character in upper case.
Parameters
[in] C - the character.
Definition at line 139 of file relic_util.h.
RLC_ECHO
#define RLC_ECHO (A) A
Indirection to help some compilers expand symbols.
Definition at line 144 of file relic_util.h.
RLC_CAT
#define RLC_CAT (A, B) _RLC_CAT(A, B)
Concatenates two tokens.
Definition at line 150 of file relic_util.h.
_RLC_CAT
#define _RLC_CAT (A, B) A ## B
Concatenates two tokens.
Definition at line 151 of file relic_util.h.
RLC_OPT
#define RLC_OPT (...) _OPT(__VA_ARGS__, _imp, _basic, _error)
Selects a basic or advanced version of a function by checking if an additional argument was passed.
Definition at line 159 of file relic_util.h.
_OPT
#define _OPT (...) RLC_ECHO(__OPT(__VA_ARGS__))
Selects a basic or advanced version of a function by checking if an additional argument was passed.
Definition at line 160 of file relic_util.h.
__OPT
#define __OPT (_1, _2, N, ...) N
Selects a basic or advanced version of a function by checking if an additional argument was passed.
Definition at line 161 of file relic_util.h.
util_print
#define util_print (F, ...) util_printf(RLC_STR(F), ##__VA_ARGS__)
Selects a real or dummy printing function depending on library flags.
Parameters
[in] F - the format string.
Definition at line 170 of file relic_util.h.
util_banner
#define util_banner (L, I)
Value:
    if (!I) {                                                               \
        util_print("\n-- " L "\n");                                         \
    } else {                                                                \
        util_print("\n** " L "\n\n");                                       \
    }                                                                       \
Prints a standard label.
Parameters
[in] L - the label of the banner.
[in] I - if the banner is inside an hierarchy.
Definition at line 181 of file relic_util.h.
Function Documentation
util_conv_endian()
uint32_t util_conv_endian (uint32_t i)
Toggle endianess of a digit.
Buffer to hold printed messages.
Definition at line 89 of file relic_util.c.
Referenced by util_conv_big(), and util_conv_little().
util_conv_big()
uint32_t util_conv_big (uint32_t i)
Convert a digit to big-endian.
Definition at line 100 of file relic_util.c.
References util_conv_endian().
Referenced by md_kdf(), and md_mgf().
util_conv_little()
uint32_t util_conv_little (uint32_t i)
Convert a digit to little-endian.
Definition at line 108 of file relic_util.c.
References util_conv_endian().
util_conv_char()
char util_conv_char (dig_t i)
Converts a small digit to a character.
Definition at line 116 of file relic_util.c.
Referenced by bn_read_str(), bn_write_str(), fb_read_str(), and fb_write_str().
util_bits_dig()
int util_bits_dig (dig_t a)
Returns the highest bit set on a digit.
Parameters
[in] a - the digit.
Returns
the position of the highest bit set.
Definition at line 141 of file relic_util.c.
References RLC_DIG.
Referenced by bn_bits(), bn_mxp_dig(), bn_mxp_slide(), cp_bdpe_gen(), eb_mul_dig(), ed_mul_dig(), ed_mul_slide(), ep2_mul_dig(), ep2_mul_sim_dig(), ep2_mul_slide(), ep_mul_dig(), ep_mul_sim_dig(), ep_mul_slide(), fb_bits(), fb_exp_slide(), fb_inv_exgcd(), fp12_exp_dig(), fp2_exp_dig(), fp48_exp_dig(), fp54_exp_dig(), fp_bits(), and fp_exp_slide().
util_cmp_const()
int util_cmp_const (const void * a, const void * b, int n)
Compares two buffers in constant time.
Parameters
[in] a - the first buffer.
[in] b - the second buffer.
[in] n - the length in bytes of the buffers.
Returns
RLC_EQ if they are equal and RLC_NE otherwise.
Definition at line 184 of file relic_util.c.
References result, RLC_EQ, and RLC_NE.
Referenced by cp_ecies_dec(), and cp_rsa_ver().
util_printf()
void util_printf (const char * format, ...)
Formats and prints data following a printf-like syntax.
Parameters
[in] format - the format.
[in] ... - the list of arguments matching the format.
util_print_dig()
void util_print_dig (dig_t a, int pad)
Prints a digit.
Parameters
[in] a - the digit to print.
[in] pad - the flag to indicate if the digit must be padded with zeroes.
Definition at line 233 of file relic_util.c.
References util_print().
Referenced by bn_print(), dv_print(), fb_print(), and fp_print().