RELIC: src/epx/relic_ep4_map.c File Reference
relic_ep4_map.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_md.h"
Functions
void ep4_map (ep4_t p, const uint8_t *msg, size_t len)
Detailed Description
Implementation of hashing to a prime elliptic curve over a quartic extension field.
Definition in file relic_ep4_map.c.
Function Documentation
ep4_map()
void ep4_map (ep4_t p, const uint8_t * msg, size_t len)
Maps a byte array to a point in an elliptic curve over a quartic extension.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 40 of file relic_ep4_map.c.
References BASIC, bn_free, bn_get_bit(), bn_new, bn_null, bn_read_bin(), core_get(), _ctx_t::ep4_b, ep4_curve_get_a(), ep4_mul_cof(), ep4_rhs(), ep4_set_infty(), ep_curve_opt_a(), ep_curve_opt_b(), _ctx_t::ep_map_c, ep_param_level(), ERR_CAUGHT, ERR_NO_VALID, fp2_is_zero(), fp4_add(), fp4_copy(), fp4_copy_sec(), fp4_dbl(), fp4_free, fp4_inv(), fp4_inv_sim(), fp4_is_sqr(), fp4_is_zero(), fp4_mul, fp4_mul_dig(), fp4_neg(), fp4_new, fp4_null, fp4_set_dig(), fp4_sqr, fp4_srt(), fp4_sub(), fp4_zero(), fp_hlv, fp_is_even(), fp_is_zero(), fp_mul, FP_PRIME, fp_prime_back(), fp_prime_conv(), fp_sub_dig(), md_xmd, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, RLC_TRY, and RLC_ZERO.