RELIC: src/ep/relic_ep_norm.c File Reference
relic_ep_norm.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
static void ep_norm_imp (ep_t r, const ep_t p, int inverted)
void ep_norm (ep_t r, const ep_t p)
void ep_norm_sim (ep_t *r, const ep_t *t, int n)
Detailed Description
Implementation of point normalization on prime elliptic curves.
Definition in file relic_ep_norm.c.
Function Documentation
ep_norm_imp()
static void ep_norm_imp (ep_t r, const ep_t p, int inverted) static
Normalizes a point represented in projective coordinates.
Parameters
r - the result.
p - the point to normalize.
Definition at line 46 of file relic_ep_norm.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_copy(), fp_null, fp_set_dig(), ep_st::norm, THROW, TRY, ep_st::x, ep_st::y, and ep_st::z.
Referenced by ep_norm(), and ep_norm_sim().
ep_norm()
void ep_norm (ep_t r, const ep_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 84 of file relic_ep_norm.c.
References ep_copy(), ep_is_infty(), ep_norm_imp(), ep_set_infty(), and ep_st::norm.
Referenced by ep_cmp(), ep_curve_set_endom(), ep_curve_set_plain(), ep_curve_set_super(), ep_is_valid(), ep_map(), ep_mul_basic(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_dig(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_basic(), ep_mul_sim_dig(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_plain(), ep_mul_sim_trick(), ep_mul_slide(), ep_tab(), ep_write_bin(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_tatep_k12(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k12(), pp_map_sim_weilp_k2(), pp_map_tatep_k12(), pp_map_tatep_k2(), pp_map_weilp_k12(), pp_map_weilp_k2(), and pp_norm_k2().
ep_norm_sim()
void ep_norm_sim (ep_t * r, const ep_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 100 of file relic_ep_norm.c.
References CATCH_ANY, ep_is_infty(), ep_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp_copy(), fp_inv_sim(), fp_null, RLC_ALLOCA, RLC_FREE, THROW, and TRY.
Referenced by ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_sim_joint(), ep_mul_sim_trick(), ep_mul_slide(), and ep_tab().