RELIC: include/relic_pc.h File Reference
relic_pc.h File Reference
Pairing-based cryptography
#include "relic_fbx.h"
#include "relic_ep.h"
#include "relic_eb.h"
#include "relic_pp.h"
#include "relic_bn.h"
#include "relic_util.h"
#include "relic_conf.h"
#include "relic_types.h"
Macros
#define RLC_PC_BYTES RLC_FP_BYTES
#define RLC_G1_TABLE RLC_CAT(RLC_CAT(RLC_, G1_UPPER), _TABLE)
#define RLC_G2_TABLE RLC_CAT(RLC_CAT(RLC_, G2_UPPER), _TABLE)
#define g1_null(A) RLC_CAT(G1_LOWER, null)(A)
#define g2_null(A) RLC_CAT(G2_LOWER, null)(A)
#define gt_null(A) RLC_CAT(GT_LOWER, null)(A)
#define g1_new(A) RLC_CAT(G1_LOWER, new)(A)
#define g2_new(A) RLC_CAT(G2_LOWER, new)(A)
#define gt_new(A) RLC_CAT(GT_LOWER, new)(A)
#define g1_free(A) RLC_CAT(G1_LOWER, free)(A)
#define g2_free(A) RLC_CAT(G2_LOWER, free)(A)
#define gt_free(A) RLC_CAT(GT_LOWER, free)(A)
#define g1_get_gen(G) RLC_CAT(G1_LOWER, curve_get_gen)(G)
#define g2_get_gen(G) RLC_CAT(G2_LOWER, curve_get_gen)(G)
#define g1_get_ord(N) RLC_CAT(G1_LOWER, curve_get_ord)(N)
#define g2_get_ord(N) RLC_CAT(G2_LOWER, curve_get_ord)(N)
#define gt_get_ord(N) RLC_CAT(G1_LOWER, curve_get_ord)(N)
#define pc_param_set_any() ep_param_set_any_pairf()
#define pc_param_print() RLC_CAT(G1_LOWER, param_print)()
#define pc_param_level() RLC_CAT(G1_LOWER, param_level)()
#define g1_is_infty(P) RLC_CAT(G1_LOWER, is_infty)(P)
#define g2_is_infty(P) RLC_CAT(G2_LOWER, is_infty)(P)
#define gt_is_unity(A) (RLC_CAT(GT_LOWER, cmp_dig)(A, 1) == RLC_EQ)
#define g1_set_infty(P) RLC_CAT(G1_LOWER, set_infty)(P)
#define g2_set_infty(P) RLC_CAT(G2_LOWER, set_infty)(P)
#define gt_zero(A) RLC_CAT(GT_LOWER, zero)(A)
#define gt_set_unity(A) RLC_CAT(GT_LOWER, set_dig)(A, 1)
#define g1_copy(R, P) RLC_CAT(G1_LOWER, copy)(R, P)
#define g2_copy(R, P) RLC_CAT(G2_LOWER, copy)(R, P)
#define gt_copy(C, A) RLC_CAT(GT_LOWER, copy)(C, A)
#define g1_cmp(P, Q) RLC_CAT(G1_LOWER, cmp)(P, Q)
#define g2_cmp(P, Q) RLC_CAT(G2_LOWER, cmp)(P, Q)
#define gt_cmp(A, B) RLC_CAT(GT_LOWER, cmp)(A, B)
#define gt_cmp_dig(A, D) RLC_CAT(GT_LOWER, cmp_dig)(A, D)
#define g1_rand(P) RLC_CAT(G1_LOWER, rand)(P)
#define g2_rand(P) RLC_CAT(G2_LOWER, rand)(P)
#define g1_print(P) RLC_CAT(G1_LOWER, print)(P)
#define g2_print(P) RLC_CAT(G2_LOWER, print)(P)
#define gt_print(A) RLC_CAT(GT_LOWER, print)(A)
#define g1_size_bin(P, C) RLC_CAT(G1_LOWER, size_bin)(P, C)
#define g2_size_bin(P, C) RLC_CAT(G2_LOWER, size_bin)(P, C)
#define gt_size_bin(A, C) RLC_CAT(GT_LOWER, size_bin)(A, C)
#define g1_read_bin(P, B, L) RLC_CAT(G1_LOWER, read_bin)(P, B, L)
#define g2_read_bin(P, B, L) RLC_CAT(G2_LOWER, read_bin)(P, B, L)
#define gt_read_bin(A, B, L) RLC_CAT(GT_LOWER, read_bin)(A, B, L)
#define g1_write_bin(B, L, P, C) RLC_CAT(G1_LOWER, write_bin)(B, L, P, C)
#define g2_write_bin(B, L, P, C) RLC_CAT(G2_LOWER, write_bin)(B, L, P, C)
#define gt_write_bin(B, L, A, C) RLC_CAT(GT_LOWER, write_bin)(B, L, A, C)
#define g1_neg(R, P) RLC_CAT(G1_LOWER, neg)(R, P)
#define g2_neg(R, P) RLC_CAT(G2_LOWER, neg)(R, P)
#define gt_inv(C, A) RLC_CAT(GT_LOWER, inv_cyc)(C, A)
#define g1_add(R, P, Q) RLC_CAT(G1_LOWER, add)(R, P, Q)
#define g2_add(R, P, Q) RLC_CAT(G2_LOWER, add)(R, P, Q)
#define gt_mul(C, A, B) RLC_CAT(GT_LOWER, mul)(C, A, B)
#define g1_sub(R, P, Q) RLC_CAT(G1_LOWER, sub)(R, P, Q)
#define g2_sub(R, P, Q) RLC_CAT(G2_LOWER, sub)(R, P, Q)
#define g1_dbl(R, P) RLC_CAT(G1_LOWER, dbl)(R, P)
#define g2_dbl(R, P) RLC_CAT(G2_LOWER, dbl)(R, P)
#define gt_sqr(C, A) RLC_CAT(GT_LOWER, sqr)(C, A)
#define g1_norm(R, P) RLC_CAT(G1_LOWER, norm)(R, P)
#define g1_norm_sim(R, P, N) RLC_CAT(G1_LOWER, norm_sim)(R, P, N)
#define g2_norm(R, P) RLC_CAT(G2_LOWER, norm)(R, P)
#define g2_norm_sim(R, P, N) RLC_CAT(G2_LOWER, norm_sim)(R, P, N)
#define g1_mul(R, P, K) RLC_CAT(G1_LOWER, mul)(R, P, K)
#define g1_mul_key(R, P, K) RLC_CAT(G1_LOWER, mul_lwreg)(R, P, K)
#define g1_mul_dig(R, P, K) RLC_CAT(G1_LOWER, mul_dig)(R, P, K)
#define g2_mul(R, P, K) RLC_CAT(G2_LOWER, mul)(R, P, K)
#define g2_mul_dig(R, P, K) RLC_CAT(G2_LOWER, mul_dig)(R, P, K)
#define gt_exp(C, A, B) RLC_CAT(GT_LOWER, exp_cyc)(C, A, B);
#define gt_exp_dig(C, A, B) RLC_CAT(GT_LOWER, exp_dig)(C, A, B)
#define g1_mul_gen(R, K) RLC_CAT(G1_LOWER, mul_gen)(R, K)
#define g2_mul_gen(R, K) RLC_CAT(G2_LOWER, mul_gen)(R, K)
#define g1_mul_pre(T, P) RLC_CAT(G1_LOWER, mul_pre)(T, P)
#define g2_mul_pre(T, P) RLC_CAT(G2_LOWER, mul_pre)(T, P)
#define g1_mul_fix(R, T, K) RLC_CAT(G1_LOWER, mul_fix)(R, T, K)
#define g2_mul_fix(R, T, K) RLC_CAT(G2_LOWER, mul_fix)(R, T, K)
#define g1_mul_sim(R, P, K, Q, L) RLC_CAT(G1_LOWER, mul_sim)(R, P, K, Q, L)
#define g1_mul_sim_dig(R, P, K, L) RLC_CAT(G1_LOWER, mul_sim_dig)(R, P, K, L)
#define g2_mul_sim(R, P, K, Q, L) RLC_CAT(G2_LOWER, mul_sim)(R, P, K, Q, L)
#define g2_mul_sim_dig(R, P, K, L) RLC_CAT(G2_LOWER, mul_sim_dig)(R, P, K, L)
#define g1_mul_sim_gen(R, K, Q, L) RLC_CAT(G1_LOWER, mul_sim_gen)(R, K, Q, L)
#define g2_mul_sim_gen(R, K, Q, L) RLC_CAT(G2_LOWER, mul_sim_gen)(R, K, Q, L)
#define g1_map(P, M, L) ; RLC_CAT(G1_LOWER, map)(P, M, L)
#define g2_map(P, M, L) ; RLC_CAT(G2_LOWER, map)(P, M, L)
#define pc_map(R, P, Q) ; RLC_CAT(PC_LOWER, map_k12)(R, P, Q)
#define pc_map_sim(R, P, Q, M) ; RLC_CAT(PC_LOWER, map_sim_k12)(R, P, Q, M)
#define pc_exp(C, A) ; RLC_CAT(PC_LOWER, exp_k12)(C, A)
#define G1_LOWER ep_
#define G1_UPPER EP
#define G2_LOWER ep2_
#define G2_UPPER EP
#define GT_LOWER fp12_
#define PC_LOWER pp_
#define pc_map_is_type1() (0)
#define pc_map_is_type3() (1)
Functions
typedef RLC_CAT (G1_LOWER, t) g1_t
typedef RLC_CAT (G1_LOWER, st) g1_st
typedef RLC_CAT (G2_LOWER, t) g2_t
typedef RLC_CAT (G2_LOWER, st) g2_st
typedef RLC_CAT (GT_LOWER, t) gt_t
void gt_rand (gt_t a)
void gt_get_gen (gt_t g)
int g1_is_valid (g1_t a)
int g2_is_valid (g2_t a)
int gt_is_valid (gt_t a)
Detailed Description
Abstractions of pairing computation useful to protocol implementors.
Definition in file relic_pc.h.
Macro Definition Documentation
G1_LOWER
#define G1_LOWER ep_
Prefix for function mappings.
Definition at line 57 of file relic_pc.h.
G1_UPPER
#define G1_UPPER EP
Prefix for function mappings.
Definition at line 58 of file relic_pc.h.
G2_LOWER
#define G2_LOWER ep2_
Prefix for function mappings.
Definition at line 59 of file relic_pc.h.
G2_UPPER
#define G2_UPPER EP
Prefix for function mappings.
Definition at line 60 of file relic_pc.h.
GT_LOWER
#define GT_LOWER fp12_
Prefix for function mappings.
Definition at line 61 of file relic_pc.h.
PC_LOWER
#define PC_LOWER pp_
Prefix for function mappings.
Definition at line 62 of file relic_pc.h.
RLC_PC_BYTES
#define RLC_PC_BYTES RLC_FP_BYTES
Represents the size in bytes of the order of G_1 and G_2.
Definition at line 76 of file relic_pc.h.
RLC_G1_TABLE
#define RLC_G1_TABLE RLC_CAT(RLC_CAT(RLC_, G1_UPPER), _TABLE)
Represents a G_1 precomputed table.
Definition at line 81 of file relic_pc.h.
RLC_G2_TABLE
#define RLC_G2_TABLE RLC_CAT(RLC_CAT(RLC_, G2_UPPER), _TABLE)
Represents a G_2 precomputed table.
Definition at line 86 of file relic_pc.h.
g1_null
#define g1_null (A) RLC_CAT(G1_LOWER, null)(A)
Initializes a G_1 element with a null value.
Parameters
[out] A - the element to initialize.
Definition at line 126 of file relic_pc.h.
g2_null
#define g2_null (A) RLC_CAT(G2_LOWER, null)(A)
Initializes a G_2 element with a null value.
Parameters
[out] A - the element to initialize.
Definition at line 133 of file relic_pc.h.
gt_null
#define gt_null (A) RLC_CAT(GT_LOWER, null)(A)
Initializes a G_T element with a null value.
Parameters
[out] A - the element to initialize.
Definition at line 140 of file relic_pc.h.
g1_new
#define g1_new (A) RLC_CAT(G1_LOWER, new)(A)
Calls a function to allocate a G_1 element.
Parameters
[out] A - the new element.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 148 of file relic_pc.h.
g2_new
#define g2_new (A) RLC_CAT(G2_LOWER, new)(A)
Calls a function to allocate a G_2 element.
Parameters
[out] A - the new element.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 156 of file relic_pc.h.
gt_new
#define gt_new (A) RLC_CAT(GT_LOWER, new)(A)
Calls a function to allocate a G_T element.
Parameters
[out] A - the new element.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
Definition at line 164 of file relic_pc.h.
g1_free
#define g1_free (A) RLC_CAT(G1_LOWER, free)(A)
Calls a function to clean and free a G_1 element.
Parameters
[out] A - the element to clean and free.
Definition at line 171 of file relic_pc.h.
g2_free
#define g2_free (A) RLC_CAT(G2_LOWER, free)(A)
Calls a function to clean and free a G_2 element.
Parameters
[out] A - the element to clean and free.
Definition at line 178 of file relic_pc.h.
gt_free
#define gt_free (A) RLC_CAT(GT_LOWER, free)(A)
Calls a function to clean and free a G_T element.
Parameters
[out] A - the element to clean and free.
Definition at line 185 of file relic_pc.h.
g1_get_gen
#define g1_get_gen (G) RLC_CAT(G1_LOWER, curve_get_gen)(G)
Returns the generator of the group G_1.
Parameters
[out] G - the returned generator.
Definition at line 192 of file relic_pc.h.
g2_get_gen
#define g2_get_gen (G) RLC_CAT(G2_LOWER, curve_get_gen)(G)
Returns the generator of the group G_2.
Parameters
[out] G - the returned generator.
Definition at line 199 of file relic_pc.h.
g1_get_ord
#define g1_get_ord (N) RLC_CAT(G1_LOWER, curve_get_ord)(N)
Returns the order of the group G_1.
Parameters
[out] N 0 the returned order.
Definition at line 206 of file relic_pc.h.
g2_get_ord
#define g2_get_ord (N) RLC_CAT(G2_LOWER, curve_get_ord)(N)
Returns the order of the group G_2.
Parameters
[out] N 0 the returned order.
Definition at line 213 of file relic_pc.h.
gt_get_ord
#define gt_get_ord (N) RLC_CAT(G1_LOWER, curve_get_ord)(N)
Returns the order of the group G_T.
Parameters
[out] N 0 the returned order.
Definition at line 220 of file relic_pc.h.
pc_param_set_any
#define pc_param_set_any () ep_param_set_any_pairf()
Configures some set of curve parameters for the current security level.
Definition at line 225 of file relic_pc.h.
pc_map_is_type1
#define pc_map_is_type1 () (0)
Returns the type of the configured pairing.
Definition at line 233 of file relic_pc.h.
pc_map_is_type3
#define pc_map_is_type3 () (1)
Returns the type of the configured pairing.
Definition at line 234 of file relic_pc.h.
pc_param_print
#define pc_param_print () RLC_CAT(G1_LOWER, param_print)()
Prints the current configured binary elliptic curve.
Definition at line 246 of file relic_pc.h.
pc_param_level
#define pc_param_level () RLC_CAT(G1_LOWER, param_level)()
Returns the current security level.
Definition at line 251 of file relic_pc.h.
g1_is_infty
#define g1_is_infty (P) RLC_CAT(G1_LOWER, is_infty)(P)
Tests if a G_1 element is the unity.
Parameters
[in] P - the element to test.
Returns
1 if the element it the unity, 0 otherwise.
Definition at line 259 of file relic_pc.h.
g2_is_infty
#define g2_is_infty (P) RLC_CAT(G2_LOWER, is_infty)(P)
Tests if a G_2 element is the unity.
Parameters
[in] P - the element to test.
Returns
1 if the element it the unity, 0 otherwise.
Definition at line 267 of file relic_pc.h.
gt_is_unity
#define gt_is_unity (A) (RLC_CAT(GT_LOWER, cmp_dig)(A, 1) == RLC_EQ)
Tests if a G_T element is the unity.
Parameters
[in] A - the element to test.
Returns
1 if the element it the unity, 0 otherwise.
Definition at line 275 of file relic_pc.h.
g1_set_infty
#define g1_set_infty (P) RLC_CAT(G1_LOWER, set_infty)(P)
Assigns a G_1 element to the unity.
Parameters
[out] P - the element to assign.
Definition at line 282 of file relic_pc.h.
g2_set_infty
#define g2_set_infty (P) RLC_CAT(G2_LOWER, set_infty)(P)
Assigns a G_2 element to the unity.
Parameters
[out] P - the element to assign.
Definition at line 289 of file relic_pc.h.
gt_zero
#define gt_zero (A) RLC_CAT(GT_LOWER, zero)(A)
Assigns a G_T element to zero.
Parameters
[out] A - the element to assign.
Definition at line 296 of file relic_pc.h.
gt_set_unity
#define gt_set_unity (A) RLC_CAT(GT_LOWER, set_dig)(A, 1)
Assigns a G_T element to the unity.
Parameters
[out] A - the element to assign.
Definition at line 303 of file relic_pc.h.
g1_copy
#define g1_copy (R, P) RLC_CAT(G1_LOWER, copy)(R, P)
Copies the second argument to the first argument.
Parameters
[out] R - the result.
[in] P - the element to copy.
Definition at line 311 of file relic_pc.h.
g2_copy
#define g2_copy (R, P) RLC_CAT(G2_LOWER, copy)(R, P)
Copies the second argument to the first argument.
Parameters
[out] R - the result.
[in] P - the element to copy.
Definition at line 319 of file relic_pc.h.
gt_copy
#define gt_copy (C, A) RLC_CAT(GT_LOWER, copy)(C, A)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the element to copy.
Definition at line 327 of file relic_pc.h.
g1_cmp
#define g1_cmp (P, Q) RLC_CAT(G1_LOWER, cmp)(P, Q)
Compares two elements from G_1.
Parameters
[in] P - the first element.
[in] Q - the second element.
Returns
RLC_EQ if P == Q and RLC_NE if P != Q.
Definition at line 336 of file relic_pc.h.
g2_cmp
#define g2_cmp (P, Q) RLC_CAT(G2_LOWER, cmp)(P, Q)
Compares two elements from G_2.
Parameters
[in] P - the first element.
[in] Q - the second element.
Returns
RLC_EQ if P == Q and RLC_NE if P != Q.
Definition at line 345 of file relic_pc.h.
gt_cmp
#define gt_cmp (A, B) RLC_CAT(GT_LOWER, cmp)(A, B)
Compares two elements from G_T.
Parameters
[in] A - the first element.
[in] B - the second element.
Returns
RLC_EQ if A == B and RLC_NE if P != Q.
Definition at line 354 of file relic_pc.h.
gt_cmp_dig
#define gt_cmp_dig (A, D) RLC_CAT(GT_LOWER, cmp_dig)(A, D)
Compares a G_T element with a digit.
Parameters
[in] A - the G_T element.
[in] D - the digit.
Returns
RLC_EQ if A == D and RLC_NE if A != D.
Definition at line 363 of file relic_pc.h.
g1_rand
#define g1_rand (P) RLC_CAT(G1_LOWER, rand)(P)
Assigns a random value to a G_1 element.
Parameters
[out] P - the element to assign.
Definition at line 370 of file relic_pc.h.
g2_rand
#define g2_rand (P) RLC_CAT(G2_LOWER, rand)(P)
Assigns a random value to a G_2 element.
Parameters
[out] P - the element to assign.
Definition at line 377 of file relic_pc.h.
g1_print
#define g1_print (P) RLC_CAT(G1_LOWER, print)(P)
Prints a G_1 element.
Parameters
[in] P - the element to print.
Definition at line 384 of file relic_pc.h.
g2_print
#define g2_print (P) RLC_CAT(G2_LOWER, print)(P)
Prints a G_2 element.
Parameters
[in] P - the element to print.
Definition at line 391 of file relic_pc.h.
gt_print
#define gt_print (A) RLC_CAT(GT_LOWER, print)(A)
Prints a G_T element.
Parameters
[in] A - the element to print.
Definition at line 398 of file relic_pc.h.
g1_size_bin
#define g1_size_bin (P, C) RLC_CAT(G1_LOWER, size_bin)(P, C)
Returns the number of bytes necessary to store a G_1 element.
Parameters
[in] P - the element of G_1.
[in] C - the flag to indicate point compression.
Definition at line 406 of file relic_pc.h.
g2_size_bin
#define g2_size_bin (P, C) RLC_CAT(G2_LOWER, size_bin)(P, C)
Returns the number of bytes necessary to store a G_2 element.
Parameters
[in] P - the element of G_2.
[in] C - the flag to indicate point compression.
Definition at line 414 of file relic_pc.h.
gt_size_bin
#define gt_size_bin (A, C) RLC_CAT(GT_LOWER, size_bin)(A, C)
Returns the number of bytes necessary to store a G_T element.
Parameters
[in] A - the element of G_T.
[in] C - the flag to indicate compression.
Definition at line 422 of file relic_pc.h.
g1_read_bin
#define g1_read_bin (P, B, L) RLC_CAT(G1_LOWER, read_bin)(P, B, L)
Reads a G_1 element from a byte vector in big-endian format.
Parameters
[out] P - the result.
[in] B - the byte vector.
[in] L - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not sufficient.
Definition at line 432 of file relic_pc.h.
g2_read_bin
#define g2_read_bin (P, B, L) RLC_CAT(G2_LOWER, read_bin)(P, B, L)
Reads a G_2 element from a byte vector in big-endian format.
Parameters
[out] P - the result.
[in] B - the byte vector.
[in] L - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not sufficient.
Definition at line 442 of file relic_pc.h.
gt_read_bin
#define gt_read_bin (A, B, L) RLC_CAT(GT_LOWER, read_bin)(A, B, L)
Reads a G_T element from a byte vector in big-endian format.
Parameters
[out] A - the result.
[in] B - the byte vector.
[in] L - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not sufficient.
Definition at line 452 of file relic_pc.h.
g1_write_bin
#define g1_write_bin (B, L, P, C) RLC_CAT(G1_LOWER, write_bin)(B, L, P, C)
Writes an optionally compressed G_1 element to a byte vector in big-endian format.
Parameters
[out] B - the byte vector.
[in] L - the buffer capacity.
[in] P - the G_1 element to write.
[in] C - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not enough.
Definition at line 464 of file relic_pc.h.
g2_write_bin
#define g2_write_bin (B, L, P, C) RLC_CAT(G2_LOWER, write_bin)(B, L, P, C)
Writes an optionally compressed G_2 element to a byte vector in big-endian format.
Parameters
[out] B - the byte vector.
[in] L - the buffer capacity.
[in] P - the G_2 element to write.
[in] C - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not enough.
Definition at line 476 of file relic_pc.h.
gt_write_bin
#define gt_write_bin (B, L, A, C) RLC_CAT(GT_LOWER, write_bin)(B, L, A, C)
Writes an optionally compresseds G_T element to a byte vector in big-endian format.
Parameters
[out] B - the byte vector.
[in] L - the buffer capacity.
[in] A - the G_T element to write.
[in] C - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not sufficient.
Definition at line 488 of file relic_pc.h.
g1_neg
#define g1_neg (R, P) RLC_CAT(G1_LOWER, neg)(R, P)
Negates a element from G_1. Computes R = -P.
Parameters
[out] R - the result.
[in] P - the element to negate.
Definition at line 496 of file relic_pc.h.
g2_neg
#define g2_neg (R, P) RLC_CAT(G2_LOWER, neg)(R, P)
Negates a element from G_2. Computes R = -P.
Parameters
[out] R - the result.
[in] P - the element to negate.
Definition at line 504 of file relic_pc.h.
gt_inv
#define gt_inv (C, A) RLC_CAT(GT_LOWER, inv_cyc)(C, A)
Inverts a element from G_T. Computes C = 1/A.
Parameters
[out] C - the result.
[in] A - the element to invert.
Definition at line 512 of file relic_pc.h.
g1_add
#define g1_add (R, P, Q) RLC_CAT(G1_LOWER, add)(R, P, Q)
Adds two elliptic elements from G_1. Computes R = P + Q.
Parameters
[out] R - the result.
[in] P - the first element to add.
[in] Q - the second element to add.
Definition at line 521 of file relic_pc.h.
g2_add
#define g2_add (R, P, Q) RLC_CAT(G2_LOWER, add)(R, P, Q)
Adds two elliptic elements from G_2. Computes R = P + Q.
Parameters
[out] R - the result.
[in] P - the first element to add.
[in] Q - the second element to add.
Definition at line 530 of file relic_pc.h.
gt_mul
#define gt_mul (C, A, B) RLC_CAT(GT_LOWER, mul)(C, A, B)
Multiplies two elliptic elements from G_T. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first element to multiply.
[in] B - the second element to multiply.
Definition at line 539 of file relic_pc.h.
g1_sub
#define g1_sub (R, P, Q) RLC_CAT(G1_LOWER, sub)(R, P, Q)
Subtracts a G_1 element from another. Computes R = P - Q.
Parameters
[out] R - the result.
[in] P - the first element.
[in] Q - the second element.
Definition at line 548 of file relic_pc.h.
g2_sub
#define g2_sub (R, P, Q) RLC_CAT(G2_LOWER, sub)(R, P, Q)
Subtracts a G_2 element from another. Computes R = P - Q.
Parameters
[out] R - the result.
[in] P - the first element.
[in] Q - the second element.
Definition at line 557 of file relic_pc.h.
g1_dbl
#define g1_dbl (R, P) RLC_CAT(G1_LOWER, dbl)(R, P)
Doubles a G_1 element. Computes R = 2P.
Parameters
[out] R - the result.
[in] P - the element to double.
Definition at line 565 of file relic_pc.h.
g2_dbl
#define g2_dbl (R, P) RLC_CAT(G2_LOWER, dbl)(R, P)
Doubles a G_2 element. Computes R = 2P.
Parameters
[out] R - the result.
[in] P - the element to double.
Definition at line 573 of file relic_pc.h.
gt_sqr
#define gt_sqr (C, A) RLC_CAT(GT_LOWER, sqr)(C, A)
Squares a G_T element. Computes C = A^2.
Parameters
[out] C - the result.
[in] A - the element to square.
Definition at line 581 of file relic_pc.h.
g1_norm
#define g1_norm (R, P) RLC_CAT(G1_LOWER, norm)(R, P)
Normalizes an element of G_1.
Parameters
[out] R - the result.
[in] P - the element to normalize.
Definition at line 589 of file relic_pc.h.
g1_norm_sim
#define g1_norm_sim (R, P, N) RLC_CAT(G1_LOWER, norm_sim)(R, P, N)
Normalizes a vector of G_1 elements.
Parameters
[out] R - the result.
[in] P - the elements to normalize.
[in] N - the number of elements to normalize.
Definition at line 598 of file relic_pc.h.
g2_norm
#define g2_norm (R, P) RLC_CAT(G2_LOWER, norm)(R, P)
Normalizes an element of G_2.
Parameters
[out] R - the result.
[in] P - the element to normalize.
Definition at line 606 of file relic_pc.h.
g2_norm_sim
#define g2_norm_sim (R, P, N) RLC_CAT(G2_LOWER, norm_sim)(R, P, N)
Normalizes a vector of G_2 elements.
Parameters
[out] R - the result.
[in] P - the elements to normalize.
[in] N - the number of elements to normalize.
Definition at line 615 of file relic_pc.h.
g1_mul
#define g1_mul (R, P, K) RLC_CAT(G1_LOWER, mul)(R, P, K)
Multiplies an element from G_1 by an integer. Computes R = kP.
Parameters
[out] R - the result.
[in] P - the element to multiply.
[in] K - the integer.
Definition at line 624 of file relic_pc.h.
g1_mul_key
#define g1_mul_key (R, P, K) RLC_CAT(G1_LOWER, mul_lwreg)(R, P, K)
Multiplies an element from G_1 by a secret scalar. Computes R = kP.
Parameters
[out] R - the result.
[in] P - the element to multiply.
[in] K - the secret scalar.
Definition at line 633 of file relic_pc.h.
g1_mul_dig
#define g1_mul_dig (R, P, K) RLC_CAT(G1_LOWER, mul_dig)(R, P, K)
Multiplies an element from G_1 by a small integer. Computes R = kP.
Parameters
[out] R - the result.
[in] P - the element to multiply.
[in] K - the small integer.
Definition at line 642 of file relic_pc.h.
g2_mul
#define g2_mul (R, P, K) RLC_CAT(G2_LOWER, mul)(R, P, K)
Multiplies an element from G_2 by an integer. Computes R = kP.
Parameters
[out] R - the result.
[in] P - the element to multiply.
[in] K - the integer.
Definition at line 651 of file relic_pc.h.
g2_mul_dig
#define g2_mul_dig (R, P, K) RLC_CAT(G2_LOWER, mul_dig)(R, P, K)
Multiplies an element from G_2 by a small integer. Computes R = kP.
Parameters
[out] R - the result.
[in] P - the element to multiply.
[in] K - the small integer.
Definition at line 660 of file relic_pc.h.
gt_exp
#define gt_exp (C, A, B) RLC_CAT(GT_LOWER, exp_cyc)(C, A, B);
Exponentiates an element from G_T by an integer. Computes C = A^B.
Parameters
[out] C - the result.
[in] A - the element to exponentiate.
[in] B - the integer exponent.
Definition at line 669 of file relic_pc.h.
gt_exp_dig
#define gt_exp_dig (C, A, B) RLC_CAT(GT_LOWER, exp_dig)(C, A, B)
Exponentiates an element from G_T by a small integer. Computes c = a^b.
Parameters
[out] R - the result.
[in] P - the element to multiply.
[in] K - the small integer.
Definition at line 678 of file relic_pc.h.
g1_mul_gen
#define g1_mul_gen (R, K) RLC_CAT(G1_LOWER, mul_gen)(R, K)
Multiplies the generator of G_1 by an integer.
Parameters
[out] R - the result.
[in] K - the integer.
Definition at line 686 of file relic_pc.h.
g2_mul_gen
#define g2_mul_gen (R, K) RLC_CAT(G2_LOWER, mul_gen)(R, K)
Multiplies the generator of G_2 by an integer.
Parameters
[out] R - the result.
[in] K - the integer.
Definition at line 694 of file relic_pc.h.
g1_mul_pre
#define g1_mul_pre (T, P) RLC_CAT(G1_LOWER, mul_pre)(T, P)
Builds a precomputation table for multiplying an element from G_1.
Parameters
[out] T - the precomputation table.
[in] P - the element to multiply.
Definition at line 702 of file relic_pc.h.
g2_mul_pre
#define g2_mul_pre (T, P) RLC_CAT(G2_LOWER, mul_pre)(T, P)
Builds a precomputation table for multiplying an element from G_2.
Parameters
[out] T - the precomputation table.
[in] P - the element to multiply.
Definition at line 710 of file relic_pc.h.
g1_mul_fix
#define g1_mul_fix (R, T, K) RLC_CAT(G1_LOWER, mul_fix)(R, T, K)
Multiplies an element from G_1 using a precomputation table. Computes R = kP.
Parameters
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer.
Definition at line 720 of file relic_pc.h.
g2_mul_fix
#define g2_mul_fix (R, T, K) RLC_CAT(G2_LOWER, mul_fix)(R, T, K)
Multiplies an element from G_2 using a precomputation table. Computes R = kP.
Parameters
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer.
Definition at line 730 of file relic_pc.h.
g1_mul_sim
#define g1_mul_sim (R, P, K, Q, L) RLC_CAT(G1_LOWER, mul_sim)(R, P, K, Q, L)
Multiplies simultaneously two elements from G_1. Computes R = kP + lQ.
Parameters
[out] R - the result.
[out] P - the first G_1 element to multiply.
[out] K - the first integer scalar.
[out] L - the second G_1 element to multiply.
[out] Q - the second integer scalar.
Definition at line 741 of file relic_pc.h.
g1_mul_sim_dig
#define g1_mul_sim_dig (R, P, K, L) RLC_CAT(G1_LOWER, mul_sim_dig)(R, P, K, L)
Multiplies elements from G_1 by small scalars. Computes R = \sum k_iP_i.
Parameters
[out] R - the result.
[in] P - the elements to multiply.
[in] K - the small scalars.
[in] L - the number of points to multiply.
Definition at line 751 of file relic_pc.h.
g2_mul_sim
#define g2_mul_sim (R, P, K, Q, L) RLC_CAT(G2_LOWER, mul_sim)(R, P, K, Q, L)
Multiplies simultaneously two elements from G_2. Computes R = kP + lQ.
Parameters
[out] R - the result.
[out] P - the first G_2 element to multiply.
[out] K - the first integer scalar.
[out] L - the second G_2 element to multiply.
[out] Q - the second integer scalar.
Definition at line 762 of file relic_pc.h.
g2_mul_sim_dig
#define g2_mul_sim_dig (R, P, K, L) RLC_CAT(G2_LOWER, mul_sim_dig)(R, P, K, L)
Multiplies elements from G_2 by small scalars. Computes R = \sum k_iP_i.
Parameters
[out] R - the result.
[in] P - the elements to multiply.
[in] K - the small scalars.
[in] L - the number of points to multiply.
Definition at line 772 of file relic_pc.h.
g1_mul_sim_gen
#define g1_mul_sim_gen (R, K, Q, L) RLC_CAT(G1_LOWER, mul_sim_gen)(R, K, Q, L)
Multiplies simultaneously two elements from G_1, where one of the is the generator. Computes R = kG + lQ.
Parameters
[out] R - the result.
[out] K - the first integer scalar.
[out] L - the second G_1 element to multiply.
[out] Q - the second integer scalar.
Definition at line 783 of file relic_pc.h.
g2_mul_sim_gen
#define g2_mul_sim_gen (R, K, Q, L) RLC_CAT(G2_LOWER, mul_sim_gen)(R, K, Q, L)
Multiplies simultaneously two elements from G_1, where one of the is the generator. Computes R = kG + lQ.
Parameters
[out] R - the result.
[out] K - the first integer scalar.
[out] L - the second G_1 element to multiply.
[out] Q - the second integer scalar.
Definition at line 794 of file relic_pc.h.
g1_map
#define g1_map (P, M, L) ; RLC_CAT(G1_LOWER, map)(P, M, L)
Maps a byte array to an element in G_1.
Parameters
[out] P - the result.
[in] M - the byte array to map.
[in] L - the array length in bytes.
Definition at line 803 of file relic_pc.h.
g2_map
#define g2_map (P, M, L) ; RLC_CAT(G2_LOWER, map)(P, M, L)
Maps a byte array to an element in G_2.
Parameters
[out] P - the result.
[in] M - the byte array to map.
[in] L - the array length in bytes.
Definition at line 812 of file relic_pc.h.
pc_map
#define pc_map (R, P, Q) ; RLC_CAT(PC_LOWER, map_k12)(R, P, Q)
Computes the bilinear pairing of a G_1 element and a G_2 element. Computes R = e(P, Q).
Parameters
[out] R - the result.
[in] P - the first element.
[in] Q - the second element.
Definition at line 823 of file relic_pc.h.
pc_map_sim
#define pc_map_sim (R, P, Q, M) ; RLC_CAT(PC_LOWER, map_sim_k12)(R, P, Q, M)
Computes the multi-pairing of G_1 elements and G_2 elements. Computes R = \prod e(P_i, Q_i).
Parameters
[out] R - the result.
[in] P - the first pairing arguments.
[in] Q - the second pairing arguments.
[in] M - the number of pairing arguments.
Definition at line 838 of file relic_pc.h.
pc_exp
#define pc_exp (C, A) ; RLC_CAT(PC_LOWER, exp_k12)(C, A)
Computes the final exponentiation of the pairing.
Parameters
[out] C - the result.
[in] A - the field element to exponentiate.
Definition at line 850 of file relic_pc.h.
Function Documentation
RLC_CAT() [1/5]
typedef RLC_CAT (G1_LOWER , t)
Represents a G_1 element.
RLC_CAT() [2/5]
typedef RLC_CAT (G1_LOWER , st)
Represents a G_1 element with automatic allocation.
RLC_CAT() [3/5]
typedef RLC_CAT (G2_LOWER , t)
Represents a G_2 element.
RLC_CAT() [4/5]
typedef RLC_CAT (G2_LOWER , st)
Represents a G_2 element with automatic allocation.
RLC_CAT() [5/5]
typedef RLC_CAT (GT_LOWER , t)
Represents a G_T element.
gt_rand()
void gt_rand (gt_t a)
Assigns a random value to an element from G_T.
Parameters
[out] a - the element to assign.
Definition at line 50 of file relic_pc_util.c.
References gt_rand_imp, pp_exp_k12(), and pp_exp_k2().
gt_get_gen()
void gt_get_gen (gt_t g)
Returns the generator for the group G_T.
Parameters
[out] g - the returned generator.
Definition at line 59 of file relic_pc_util.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, g1_free, g1_get_gen, g1_new, g1_null, g2_free, g2_get_gen, g2_new, g2_null, pc_map, THROW, and TRY.
g1_is_valid()
int g1_is_valid (g1_t a)
Checks if an element from G_1 is valid (has the right order).
Parameters
[in] a - the element to check.
Definition at line 82 of file relic_pc_util.c.
References bn_add_dig(), bn_cmp_dig(), bn_free(), bn_hlv(), bn_null, CATCH_ANY, ep_curve_get_cof(), ep_is_valid(), ERR_CAUGHT, FINALLY, g1_cmp, g1_dbl, g1_free, g1_get_ord, g1_mul, g1_new, g1_null, RLC_EQ, THROW, and TRY.
Referenced by cp_bbs_ver().
g2_is_valid()
int g2_is_valid (g2_t a)
Checks if an element form G_2 is valid (has the right order).
Parameters
[in] a - the element to check.
Definition at line 118 of file relic_pc_util.c.
References bn_add_dig(), bn_cmp_dig(), bn_free(), bn_hlv(), bn_null, bn_sub(), bn_sub_dig(), CATCH_ANY, bn_st::dp, dv_copy(), ep2_frb(), ep_curve_get_cof(), ERR_CAUGHT, FINALLY, fp_prime_get(), g2_add, g2_cmp, g2_dbl, g2_free, g2_get_ord, g2_mul, g2_neg, g2_new, g2_null, RLC_EQ, RLC_FP_DIGS, RLC_POS, bn_st::sign, THROW, TRY, and bn_st::used.
gt_is_valid()
int gt_is_valid (gt_t a)
Checks if an element form G_T is valid (has the right order).
Parameters
[in] a - the element to check.
Definition at line 174 of file relic_pc_util.c.
References bn_add_dig(), bn_cmp_dig(), bn_free(), bn_hlv(), bn_null, bn_sub(), bn_sub_dig(), CATCH_ANY, bn_st::dp, dv_copy(), ep_curve_get_cof(), ERR_CAUGHT, FINALLY, fp12_frb(), fp_prime_get(), gt_cmp, gt_exp, gt_free, gt_get_ord, gt_inv, gt_mul, gt_new, gt_null, gt_sqr, RLC_EQ, RLC_FP_DIGS, RLC_POS, bn_st::sign, THROW, TRY, and bn_st::used.