RELIC: src/fpx/relic_fpx_frb.c File Reference
relic_fpx_frb.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
void fp2_frb (fp2_t c, fp2_t a, int i)
void fp3_frb (fp3_t c, fp3_t a, int i)
void fp4_frb (fp4_t c, fp4_t a, int i)
void fp6_frb (fp6_t c, fp6_t a, int i)
void fp8_frb (fp8_t c, fp8_t a, int i)
void fp9_frb (fp9_t c, fp9_t a, int i)
void fp12_frb (fp12_t c, fp12_t a, int i)
void fp18_frb (fp18_t c, fp18_t a, int i)
void fp24_frb (fp24_t c, fp24_t a, int i)
void fp48_frb (fp48_t c, fp48_t a, int i)
void fp54_frb (fp54_t c, fp54_t a, int i)
Detailed Description
Implementation of frobenius action in extensions defined over prime fields.
Definition in file relic_fpx_frb.c.
Function Documentation
fp2_frb()
void fp2_frb (fp2_t c, fp2_t a, int i)
Computes a power of the Frobenius map of a quadratic extension field element. When i is odd, this is the same as computing the conjugate of the extension field element.
Parameters
[out] c - the result.
[in] a - the quadratic extension element to conjugate.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_fpx_frb.c.
References fp2_copy(), and fp_copy().
Referenced by ep2_frb(), fp12_frb(), fp2_test_cyc(), fp4_frb(), and fp6_frb().
fp3_frb()
void fp3_frb (fp3_t c, fp3_t a, int i)
Computes a power of the Frobenius map of a cubic extension field element.
Parameters
[out] c - the result.
[in] a - the cubic extension element to exponentiate.
[in] i - the power of the Frobenius map.
Definition at line 52 of file relic_fpx_frb.c.
References fp3_copy(), and fp3_mul_frb().
Referenced by fp18_frb(), fp3_srt(), and fp9_frb().
fp4_frb()
void fp4_frb (fp4_t c, fp4_t a, int i)
Computes a power of the Frobenius endomorphism of a quartic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a quartic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 64 of file relic_fpx_frb.c.
References fp2_frb(), fp2_mul_frb(), and fp4_copy().
Referenced by fp8_frb().
fp6_frb()
void fp6_frb (fp6_t c, fp6_t a, int i)
Computes a power of the Frobenius endomorphism of a sextic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a sextic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 74 of file relic_fpx_frb.c.
References fp2_frb(), fp2_mul_frb(), and fp6_copy().
Referenced by fp12_frb().
fp8_frb()
void fp8_frb (fp8_t c, fp8_t a, int i)
Computes a power of the Frobenius endomorphism of an octic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - an octic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 86 of file relic_fpx_frb.c.
References fp2_mul_frb(), fp4_frb(), fp4_mul_art(), fp8_copy(), and fp_prime_get_mod8().
Referenced by fp24_frb(), and pp_exp_k8().
fp9_frb()
void fp9_frb (fp9_t c, fp9_t a, int i)
Computes a power of the Frobenius endomorphism of a nonic extension field element. Computes c = a^p^i.
Parameters
[out] c - the result.
[in] a - a nonic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 100 of file relic_fpx_frb.c.
References fp3_frb(), fp3_mul_frb(), and fp9_copy().
Referenced by fp18_frb(), and pp_mil_k54().
fp12_frb()
void fp12_frb (fp12_t c, fp12_t a, int i)
Computes the Frobenius endomorphism of a dodecic extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a dodecic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 112 of file relic_fpx_frb.c.
References fp12_copy(), fp2_frb(), fp2_mul_frb(), and fp6_frb().
Referenced by fp12_conv_cyc(), fp12_exp_cyc(), gt_is_valid(), pp_exp_b12(), and pp_exp_bn().
fp18_frb()
void fp18_frb (fp18_t c, fp18_t a, int i)
Computes the Frobenius endomorphism of an octdecic extension element. Computes c = a^(p^i).
Parameters
[out] c - the result.
[in] a - an octdecic extension field element.
[in] i - the power of the Frobenius map.
Definition at line 126 of file relic_fpx_frb.c.
References fp18_copy(), fp3_frb(), fp3_mul_frb(), and fp9_frb().
Referenced by fp54_frb().
fp24_frb()
void fp24_frb (fp24_t c, fp24_t a, int i)
Computes the Frobenius endomorphism of a 24-degree extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a 24-degree extension field element.
[in] i - the power of the Frobenius map.
Definition at line 140 of file relic_fpx_frb.c.
References fp24_copy(), fp2_mul_frb(), fp4_mul_art(), fp8_frb(), and fp_prime_get_mod8().
Referenced by fp48_frb().
fp48_frb()
void fp48_frb (fp48_t c, fp48_t a, int i)
Computes the Frobenius endomorphism of a 48-extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a 48-extension field element.
[in] i - the power of the Frobenius map.
Definition at line 159 of file relic_fpx_frb.c.
References fp24_frb(), fp2_mul_frb(), fp48_copy(), fp4_mul_art(), fp8_mul_art(), and fp_prime_get_mod8().
Referenced by fp48_conv_cyc(), and pp_exp_k48().
fp54_frb()
void fp54_frb (fp54_t c, fp54_t a, int i)
Computes the Frobenius endomorphism of a 54-extension element. Computes c = a^p.
Parameters
[out] c - the result.
[in] a - a 54-extension field element.
[in] i - the power of the Frobenius map.
Definition at line 181 of file relic_fpx_frb.c.
References fp18_frb(), fp3_mul_frb(), fp54_copy(), and fp9_mul_art().
Referenced by fp54_conv_cyc(), and pp_exp_k54().