RELIC: src/epx/relic_ep2_curve.c File Reference
relic_ep2_curve.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Macros
#define ASSIGN(CURVE)
#define BN_P256_A0 "0"
#define BN_P256_A1 "0"
#define BN_P256_B0 "4"
#define BN_P256_B1 "B64000000000FF2F2200000085FD5480B0001F44B6B88BF142BC818F95E3E6AE"
#define BN_P256_X0 "0C77AE4A1D6E145166739CF23DAFACA9DD396E9046424FC5479BD57692904538"
#define BN_P256_X1 "8D1705B45D9EAAD78A9198FD8D76E2013D1BC119B4D95721A8D32F819A544F51"
#define BN_P256_Y0 "A906E963E4988478E458A4959EF7D61B570358814E28A04EF9B8C794064D73A7"
#define BN_P256_Y1 "A033144CA161E3E3271624B3F0CC1CE607ACD2CBCE9E9253C732CF3E1016DEE7"
#define BN_P256_R "B64000000000FF2F2200000085FD547FD8001F44B6B7F4B7C2BC818F7B6BEF99"
#define BN_P256_H "B64000000000FF2F2200000085FD548188001F44B6B9232AC2BC818FB05BDDC5"
Functions
void ep2_curve_init (void)
void ep2_curve_clean (void)
int ep2_curve_is_twist (void)
void ep2_curve_get_gen (ep2_t g)
void ep2_curve_get_a (fp2_t a)
void ep2_curve_get_b (fp2_t b)
void ep2_curve_get_vs (bn_t *v)
void ep2_curve_get_ord (bn_t n)
void ep2_curve_get_cof (bn_t h)
ep2_t * ep2_curve_get_tab (void)
void ep2_curve_set_twist (int type)
void ep2_curve_set (fp2_t a, fp2_t b, ep2_t g, bn_t r, bn_t h)
Detailed Description
Implementation of configuration of prime elliptic curves over quadratic extensions.
Definition in file relic_ep2_curve.c.
Macro Definition Documentation
BN_P256_A0
#define BN_P256_A0 "0"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 74 of file relic_ep2_curve.c.
BN_P256_A1
#define BN_P256_A1 "0"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 75 of file relic_ep2_curve.c.
BN_P256_B0
#define BN_P256_B0 "4"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 76 of file relic_ep2_curve.c.
BN_P256_B1
#define BN_P256_B1 "B64000000000FF2F2200000085FD5480B0001F44B6B88BF142BC818F95E3E6AE"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 77 of file relic_ep2_curve.c.
BN_P256_X0
#define BN_P256_X0 "0C77AE4A1D6E145166739CF23DAFACA9DD396E9046424FC5479BD57692904538"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 78 of file relic_ep2_curve.c.
BN_P256_X1
#define BN_P256_X1 "8D1705B45D9EAAD78A9198FD8D76E2013D1BC119B4D95721A8D32F819A544F51"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 79 of file relic_ep2_curve.c.
BN_P256_Y0
#define BN_P256_Y0 "A906E963E4988478E458A4959EF7D61B570358814E28A04EF9B8C794064D73A7"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 80 of file relic_ep2_curve.c.
BN_P256_Y1
#define BN_P256_Y1 "A033144CA161E3E3271624B3F0CC1CE607ACD2CBCE9E9253C732CF3E1016DEE7"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 81 of file relic_ep2_curve.c.
BN_P256_R
#define BN_P256_R "B64000000000FF2F2200000085FD547FD8001F44B6B7F4B7C2BC818F7B6BEF99"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 82 of file relic_ep2_curve.c.
BN_P256_H
#define BN_P256_H "B64000000000FF2F2200000085FD548188001F44B6B9232AC2BC818FB05BDDC5"
Parameters for a pairing-friendly prime curve over a quadratic extension.
Definition at line 83 of file relic_ep2_curve.c.
ASSIGN
#define ASSIGN (CURVE)
Value:
    RLC_GET(str, CURVE##_A0, sizeof(CURVE##_A0));                           \
    fp_read_str(a[0], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_A1, sizeof(CURVE##_A1));                           \
    fp_read_str(a[1], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_B0, sizeof(CURVE##_B0));                           \
    fp_read_str(b[0], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_B1, sizeof(CURVE##_B1));                           \
    fp_read_str(b[1], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_X0, sizeof(CURVE##_X0));                           \
    fp_read_str(g->x[0], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_X1, sizeof(CURVE##_X1));                           \
    fp_read_str(g->x[1], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_Y0, sizeof(CURVE##_Y0));                           \
    fp_read_str(g->y[0], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_Y1, sizeof(CURVE##_Y1));                           \
    fp_read_str(g->y[1], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_R, sizeof(CURVE##_R));                             \
    bn_read_str(r, str, strlen(str), 16);                                   \
    RLC_GET(str, CURVE##_H, sizeof(CURVE##_H));                             \
    bn_read_str(h, str, strlen(str), 16);                                   \
Assigns a set of ordinary elliptic curve parameters.
Parameters
[in] CURVE - the curve parameters to assign.
Definition at line 229 of file relic_ep2_curve.c.
Function Documentation
ep2_curve_init()
void ep2_curve_init (void)
Calls a function to allocate a point on a elliptic curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory. Calls a function to clean and free a point on a elliptic curve.
Parameters
[out] A - the point to free. Negates a point in an elliptic curve over a quadratic extension field. Computes R = -P.
[out] R - the result.
[in] P - the point to negate. Adds two points in an elliptic curve over a quadratic extension field. Computes R = P + Q.
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add. Subtracts a point in an elliptic curve over a quadratic extension field from another point in this curve. Computes R = P - Q.
[out] R - the result.
[in] P - the first point.
[in] Q - the second point. Doubles a point in an elliptic curve over a quadratic extension field. Computes R = 2P.
[out] R - the result.
[in] P - the point to double. Multiplies a point in an elliptic curve over a quadratic extension field. Computes R = kP.
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer. Builds a precomputation table for multiplying a fixed prime elliptic point over a quadratic extension.
[out] T - the precomputation table.
[in] P - the point to multiply. Multiplies a fixed prime elliptic point over a quadratic extension using a precomputation table. Computes R = kP.
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer. Multiplies and adds two prime elliptic curve points simultaneously. Computes R = kP + lQ.
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] M - the second integer, Initializes the elliptic curve over quadratic extension.
Definition at line 255 of file relic_ep2_curve.c.
References bn_init(), core_get(), _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_pre, _ctx_t::ep2_ptr, _ctx_t::ep2_r, ep2_set_infty(), fp2_new, RLC_FP_DIGS, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by pp_map_init().
ep2_curve_clean()
void ep2_curve_clean (void)
Finalizes the elliptic curve over quadratic extension.
Definition at line 296 of file relic_ep2_curve.c.
References bn_clean(), core_get(), _ctx_t::ep2_h, _ctx_t::ep2_pre, _ctx_t::ep2_r, fp2_free, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by pp_map_clean().
ep2_curve_is_twist()
int ep2_curve_is_twist (void)
Tests if the configured elliptic curve is a twist.
Returns
the type of the elliptic curve twist, 0 if non-twisted curve.
Definition at line 309 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_is_twist.
Referenced by ep2_frb(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k8_basic(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_add_lit_k12(), pp_dbl_k12_basic(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k8_basic(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_lazyr_new(), pp_dbl_k8_projc_new(), and pp_dbl_lit_k12().
ep2_curve_get_gen()
void ep2_curve_get_gen (ep2_t g)
Returns the generator of the group of points in the elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 313 of file relic_ep2_curve.c.
References core_get(), and ep2_copy().
Referenced by ep2_mul_gen(), and ep2_mul_sim_gen().
ep2_curve_get_a()
void ep2_curve_get_a (fp2_t a)
Returns the 'a' coefficient of the currently configured elliptic curve.
Parameters
[out] a - the 'a' coefficient of the elliptic curve.
Definition at line 317 of file relic_ep2_curve.c.
References core_get(), _ctx_t::ep2_a, and fp_copy().
Referenced by ep2_dbl_basic_imp(), ep2_dbl_projc_imp(), and ep2_rhs().
ep2_curve_get_b()
void ep2_curve_get_b (fp2_t b)
Returns the 'b' coefficient of the currently configured elliptic curve.
Parameters
[out] b - the 'b' coefficient of the elliptic curve.
Definition at line 323 of file relic_ep2_curve.c.
References core_get(), _ctx_t::ep2_b, and fp_copy().
Referenced by ep2_rhs(), pp_dbl_k12_projc_basic(), and pp_dbl_k12_projc_lazyr().
ep2_curve_get_vs()
void ep2_curve_get_vs (bn_t * v)
Returns the vector of coefficients required to perform GLV method.
Parameters
[out] b - the vector of coefficients.
Definition at line 329 of file relic_ep2_curve.c.
References bn_add(), bn_add_dig(), bn_copy(), bn_dbl(), bn_free(), bn_mul_dig(), bn_neg(), bn_null, bn_rsh(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp_prime_get_par(), THROW, and TRY.
Referenced by ep2_mul_glv_imp(), and fp12_exp_cyc().
ep2_curve_get_ord()
void ep2_curve_get_ord (bn_t n)
Returns the order of the group of points in the elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 376 of file relic_ep2_curve.c.
References bn_copy(), core_get(), _ctx_t::ep2_is_twist, _ctx_t::ep2_r, and ep_curve_get_ord().
Referenced by ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_glv_imp(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_sim_trick(), ep2_rand(), and fp12_exp_cyc().
ep2_curve_get_cof()
void ep2_curve_get_cof (bn_t h)
Returns the cofactor of the group order in the elliptic curve.
Parameters
[out] h - the returned cofactor.
Definition at line 385 of file relic_ep2_curve.c.
References bn_copy(), and core_get().
Referenced by ep2_map().
ep2_curve_get_tab()
ep2_t* ep2_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 391 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_ptr.
Referenced by ep2_curve_set(), ep2_curve_set_twist(), ep2_mul_gen(), and ep2_mul_sim_gen().
ep2_curve_set_twist()
void ep2_curve_set_twist (int type)
Configures an elliptic curve by twisting the curve over the base prime field.
Parameters
- the type of twist (multiplicative or divisive)
Definition at line 401 of file relic_ep2_curve.c.
References ASSIGN, B12_P381, B12_P446, B12_P455, B12_P638, bn_copy(), bn_free(), bn_null, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, CATCH_ANY, core_get(), CP8_P544, _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_copy(), ep2_curve_get_tab(), _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_is_twist, ep2_null, _ctx_t::ep2_r, EP_DTYPE, EP_MTYPE, ep_param_get(), ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp2_free, fp2_new, fp2_null, fp2_zero(), fp_copy(), fp_prime_calc(), fp_set_dig(), ep2_st::norm, OT8_P511, RLC_FP_BYTES, THROW, TRY, and ep2_st::z.
Referenced by ep_param_set_any_pairf().
ep2_curve_set()
void ep2_curve_set (fp2_t a, fp2_t b, ep2_t g, bn_t r, bn_t h)
Configures an elliptic curve over a quadratic extension by its coefficients.
Parameters
[in] a - the 'a' coefficient of the curve.
[in] b - the 'b' coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
Definition at line 513 of file relic_ep2_curve.c.
References bn_copy(), core_get(), _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_curve_get_tab(), _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_is_twist, ep2_norm(), _ctx_t::ep2_r, and fp_copy().