RELIC: src/fpx/relic_fpx_cyc.c File Reference
relic_fpx_cyc.c File Reference
Prime field extensions.
#include "relic_core.h"
Functions
void fp2_conv_cyc (fp2_t c, fp2_t a)
int fp2_test_cyc (fp2_t a)
void fp2_exp_cyc (fp2_t c, fp2_t a, bn_t b)
void fp8_conv_cyc (fp8_t c, fp8_t a)
int fp8_test_cyc (fp8_t a)
void fp8_exp_cyc (fp8_t c, fp8_t a, bn_t b)
void fp12_conv_cyc (fp12_t c, fp12_t a)
int fp12_test_cyc (fp12_t a)
void fp12_back_cyc (fp12_t c, fp12_t a)
void fp12_back_cyc_sim (fp12_t c[], fp12_t a[], int n)
void fp12_exp_cyc (fp12_t c, fp12_t a, bn_t b)
void fp12_exp_cyc_sps (fp12_t c, fp12_t a, const int *b, int len, int sign)
void fp48_conv_cyc (fp48_t c, fp48_t a)
int fp48_test_cyc (fp48_t a)
void fp48_back_cyc (fp48_t c, fp48_t a)
void fp48_back_cyc_sim (fp48_t c[], fp48_t a[], int n)
void fp48_exp_cyc (fp48_t c, fp48_t a, bn_t b)
void fp48_exp_cyc_sps (fp48_t c, fp48_t a, const int *b, int len, int sign)
void fp54_conv_cyc (fp54_t c, fp54_t a)
int fp54_test_cyc (fp54_t a)
void fp54_back_cyc (fp54_t c, fp54_t a)
void fp54_back_cyc_sim (fp54_t c[], fp54_t a[], int n)
void fp54_exp_cyc (fp54_t c, fp54_t a, bn_t b)
void fp54_exp_cyc_sps (fp54_t c, fp54_t a, const int *b, int len, int sign)
Detailed Description
Implementation of exponentiation in cyclotomic subgroups of extensions defined over prime fields.
Definition in file relic_fpx_cyc.c.
Function Documentation
fp2_conv_cyc()
void fp2_conv_cyc (fp2_t c, fp2_t a)
Converts a quadratic extension field element to a cyclotomic element. Computes c = a^(p - 1).
Parameters
[out] c - the result.
[in] a - the quadratic extension field element.
Definition at line 39 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_free, fp2_inv(), fp2_inv_cyc(), fp2_new, fp2_null, THROW, and TRY.
Referenced by pp_exp_k2().
fp2_test_cyc()
int fp2_test_cyc (fp2_t a)
Tests if a quadratic extension field element is cyclotomic.
Parameters
[in] a - the quadratic extension field element to test.
Returns
1 if the extension field element is cyclotomic, 0 otherwise.
Definition at line 62 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_cmp_dig(), fp2_frb(), fp2_free, fp2_new, fp2_null, result, RLC_EQ, THROW, and TRY.
Referenced by fp2_pck(), fp2_size_bin(), and fp2_write_bin().
fp2_exp_cyc()
void fp2_exp_cyc (fp2_t c, fp2_t a, bn_t b)
Computes a power of a cyclotomic quadratic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic element to exponentiate.
[in] b - the exponent.
Definition at line 84 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_inv_cyc(), fp2_new, fp2_null, fp2_set_dig(), FP_WIDTH, RLC_FP_BITS, RLC_NEG, THROW, and TRY.
Referenced by pp_exp_k2().
fp8_conv_cyc()
void fp8_conv_cyc (fp8_t c, fp8_t a)
Converts an octic extension field element to a cyclotomic element. Computes c = a^(p^4 - 1).
Parameters
[out] c - the result.
[in] a - the octic extension field element.
Definition at line 150 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_free, fp8_inv(), fp8_inv_cyc(), fp8_new, fp8_null, THROW, and TRY.
Referenced by pp_exp_k8().
fp8_test_cyc()
int fp8_test_cyc (fp8_t a)
Tests if an octic extension field element is cyclotomic.
Parameters
[in] a - the octic extension field element to test.
Returns
1 if the extension field element is cyclotomic, 0 otherwise.
Definition at line 173 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_cmp_dig(), fp8_free, fp8_inv_cyc(), fp8_new, fp8_null, result, RLC_EQ, THROW, and TRY.
Referenced by fp8_exp(), and fp8_size_bin().
fp8_exp_cyc()
void fp8_exp_cyc (fp8_t c, fp8_t a, bn_t b)
Computes a power of a cyclotomic octic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 195 of file relic_fpx_cyc.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_copy(), fp8_free, fp8_inv_cyc(), fp8_new, fp8_null, fp8_set_dig(), fp8_sqr_cyc(), FP_WIDTH, RLC_FP_BITS, RLC_NEG, THROW, and TRY.
Referenced by fp8_exp(), and pp_exp_k8().
fp12_conv_cyc()
void fp12_conv_cyc (fp12_t c, fp12_t a)
Converts a dodecic extension field element to a cyclotomic element. Computes c = a^(p^6 - 1)*(p^2 + 1).
Parameters
[out] c - the result.
[in] a - a dodecic extension field element.
Definition at line 261 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_frb(), fp12_free, fp12_inv(), fp12_inv_cyc(), fp12_new, fp12_null, THROW, and TRY.
Referenced by pp_exp_b12(), and pp_exp_bn().
fp12_test_cyc()
int fp12_test_cyc (fp12_t a)
Tests if a dodecic extension field element belongs to the cyclotomic subgroup.
Parameters
[in] a - the dodecic extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 292 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_back_cyc(), fp12_cmp(), fp12_free, fp12_new, fp12_null, result, RLC_EQ, THROW, and TRY.
Referenced by fp12_exp(), fp12_exp_dig(), fp12_pck(), fp12_size_bin(), and fp12_upk().
fp12_back_cyc()
void fp12_back_cyc (fp12_t c, fp12_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to decompress.
Definition at line 315 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_inv(), fp2_new, fp2_null, fp_add_dig(), THROW, and TRY.
Referenced by fp12_read_bin(), fp12_test_cyc(), and fp12_upk().
fp12_back_cyc_sim()
void fp12_back_cyc_sim (fp12_t c[], fp12_t a[], int n)
Definition at line 373 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp2_copy(), fp2_free, fp2_inv_sim(), fp2_new, fp2_null, fp_add_dig(), RLC_ALLOCA, RLC_FREE, THROW, and TRY.
Referenced by fp12_exp_cyc(), and fp12_exp_cyc_sps().
fp12_exp_cyc()
void fp12_exp_cyc (fp12_t c, fp12_t a, bn_t b)
Computes a power of a cyclotomic dodecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 451 of file relic_fpx_cyc.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_dbl(), bn_div(), bn_free(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_mod, bn_neg(), bn_null, bn_sign(), bn_sub(), bn_sub_dig(), bn_zero(), CATCH_ANY, ep2_curve_get_ord(), ep2_curve_get_vs(), EP_B12, EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp12_back_cyc_sim(), fp12_copy(), fp12_frb(), fp12_free, fp12_inv_cyc(), fp12_new, fp12_null, fp12_set_dig(), fp_prime_get_par(), RLC_ALLOCA, RLC_DIG, RLC_FREE, RLC_MAX, RLC_NEG, RLC_POS, bn_st::sign, THROW, and TRY.
Referenced by fp12_exp().
fp12_exp_cyc_sps()
void fp12_exp_cyc_sps (fp12_t c, fp12_t a, const int * b, int l, int s)
Computes a power of a cyclotomic dodecic extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 691 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp12_back_cyc_sim(), fp12_copy(), fp12_free, fp12_inv_cyc(), fp12_new, fp12_null, fp12_set_dig(), RLC_ALLOCA, RLC_FREE, RLC_NEG, THROW, and TRY.
Referenced by pp_exp_b12(), and pp_exp_bn().
fp48_conv_cyc()
void fp48_conv_cyc (fp48_t c, fp48_t a)
Converts a 48-extension field element to a cyclotomic element. Computes c = a^(p^6 - 1).
Parameters
[out] c - the result.
[in] a - the 48-extension field element.
Definition at line 769 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp48_frb(), fp48_free, fp48_inv(), fp48_inv_cyc(), fp48_new, fp48_null, THROW, and TRY.
Referenced by pp_exp_k48().
fp48_test_cyc()
int fp48_test_cyc (fp48_t a)
Tests if a 48-extension field element belongs to the cyclotomic subgroup.
Parameters
[in] a - the 48-extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 800 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp48_back_cyc(), fp48_cmp(), fp48_free, fp48_new, fp48_null, result, RLC_EQ, THROW, and TRY.
Referenced by fp48_exp(), fp48_exp_dig(), fp48_pck(), fp48_size_bin(), and fp48_upk().
fp48_back_cyc()
void fp48_back_cyc (fp48_t c, fp48_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the 48-extension field element to decompress.
Definition at line 822 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp8_add(), fp8_copy(), fp8_dbl(), fp8_free, fp8_inv(), fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), fp_add_dig(), THROW, and TRY.
Referenced by fp48_read_bin(), fp48_test_cyc(), and fp48_upk().
fp48_back_cyc_sim()
void fp48_back_cyc_sim (fp48_t c[], fp48_t a[], int n)
Definition at line 880 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp8_add(), fp8_copy(), fp8_dbl(), fp8_free, fp8_inv_sim(), fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), fp_add_dig(), RLC_ALLOCA, RLC_FREE, THROW, and TRY.
Referenced by fp48_exp_cyc(), and fp48_exp_cyc_sps().
fp48_exp_cyc()
void fp48_exp_cyc (fp48_t c, fp48_t a, bn_t b)
Computes a power of a cyclotomic 48-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 958 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp48_back_cyc_sim(), fp48_copy(), fp48_free, fp48_inv_cyc(), fp48_new, fp48_null, fp48_set_dig(), RLC_ALLOCA, RLC_DIG, RLC_FREE, RLC_NEG, THROW, and TRY.
Referenced by fp48_exp().
fp48_exp_cyc_sps()
void fp48_exp_cyc_sps (fp48_t c, fp48_t a, const int * b, int l, int s)
Computes a power of a cyclotomic 48-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 1051 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp48_back_cyc_sim(), fp48_copy(), fp48_free, fp48_inv_cyc(), fp48_new, fp48_null, fp48_set_dig(), RLC_ALLOCA, RLC_FREE, RLC_NEG, THROW, and TRY.
Referenced by pp_exp_k48().
fp54_conv_cyc()
void fp54_conv_cyc (fp54_t c, fp54_t a)
Converts a 54-extension field element to a cyclotomic element. Computes c = a^(p^6 - 1).
Parameters
[out] c - the result.
[in] a - the 54-extension field element.
Definition at line 1129 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp54_frb(), fp54_free, fp54_inv(), fp54_inv_cyc(), fp54_new, fp54_null, THROW, and TRY.
Referenced by pp_exp_k54().
fp54_test_cyc()
int fp54_test_cyc (fp54_t a)
Tests if a 54-extension field element belongs to the cyclotomic subgroup.
Parameters
[in] a - the 54-extension field element to test.
Returns
1 if the extension field element is in the subgroup, 0 otherwise.
Definition at line 1160 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp54_back_cyc(), fp54_cmp(), fp54_free, fp54_new, fp54_null, result, RLC_EQ, THROW, and TRY.
Referenced by fp54_exp_dig(), fp54_pck(), fp54_size_bin(), and fp54_upk().
fp54_back_cyc()
void fp54_back_cyc (fp54_t c, fp54_t a)
Decompresses a compressed cyclotomic extension field element.
Parameters
[out] c - the result.
[in] a - the 54-extension field element to decompress.
Definition at line 1182 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp9_add(), fp9_copy(), fp9_dbl(), fp9_free, fp9_inv(), fp9_mul_art(), fp9_new, fp9_null, fp9_sub(), fp_add_dig(), THROW, and TRY.
Referenced by fp54_read_bin(), fp54_test_cyc(), and fp54_upk().
fp54_back_cyc_sim()
void fp54_back_cyc_sim (fp54_t c[], fp54_t a[], int n)
Definition at line 1240 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp9_add(), fp9_copy(), fp9_dbl(), fp9_free, fp9_inv_sim(), fp9_mul_art(), fp9_new, fp9_null, fp9_sub(), fp_add_dig(), RLC_ALLOCA, RLC_FREE, THROW, and TRY.
Referenced by fp54_exp_cyc(), and fp54_exp_cyc_sps().
fp54_exp_cyc()
void fp54_exp_cyc (fp54_t c, fp54_t a, bn_t b)
Computes a power of a cyclotomic 54-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent.
Definition at line 1318 of file relic_fpx_cyc.c.
References bn_bits(), bn_get_bit(), bn_ham(), bn_is_even(), bn_is_zero(), bn_sign(), CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp54_back_cyc_sim(), fp54_copy(), fp54_free, fp54_inv_cyc(), fp54_new, fp54_null, fp54_set_dig(), RLC_ALLOCA, RLC_DIG, RLC_FREE, RLC_NEG, THROW, and TRY.
fp54_exp_cyc_sps()
void fp54_exp_cyc_sps (fp54_t c, fp54_t a, const int * b, int l, int s)
Computes a power of a cyclotomic 54-extension field element.
Parameters
[out] c - the result.
[in] a - the basis.
[in] b - the exponent in sparse form.
[in] l - the length of the exponent in sparse form.
[in] s - the sign of the exponent.
Definition at line 1411 of file relic_fpx_cyc.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp54_back_cyc_sim(), fp54_copy(), fp54_free, fp54_inv_cyc(), fp54_new, fp54_null, fp54_set_dig(), RLC_ALLOCA, RLC_FREE, RLC_NEG, THROW, and TRY.
Referenced by pp_exp_k54().