RELIC: src/fpx/relic_fp16_mul.c File Reference
relic_fp16_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp16_mul_basic (fp16_t c, const fp16_t a, const fp16_t b)
void fp16_mul_dxs_basic (fp16_t c, const fp16_t a, const fp16_t b)
void fp16_mul_unr (dv16_t c, const fp16_t a, const fp16_t b)
void fp16_mul_lazyr (fp16_t c, const fp16_t a, const fp16_t b)
void fp16_mul_dxs_lazyr (fp16_t c, const fp16_t a, const fp16_t b)
void fp16_mul_art (fp16_t c, const fp16_t a)
Detailed Description
Implementation of multiplication in an sextadecic extension of a prime field.
Definition in file relic_fp16_mul.c.
Function Documentation
fp16_mul_basic()
void fp16_mul_basic (fp16_t c, const fp16_t a, const fp16_t b)
Multiples two sextadecic extension field elements.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element.
[in] b - the sextadecic extension field element.
Definition at line 42 of file relic_fp16_mul.c.
References ERR_CAUGHT, fp8_add(), fp8_free, fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_mul_dxs_basic()
void fp16_mul_dxs_basic (fp16_t c, const fp16_t a, const fp16_t b)
Definition at line 83 of file relic_fp16_mul.c.
References ERR_CAUGHT, fp4_add(), fp4_is_zero(), fp4_mul, fp4_mul_art(), fp4_sub(), fp8_add(), fp8_free, fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), fp_mul, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_mul_unr()
void fp16_mul_unr (dv16_t c, const fp16_t a, const fp16_t b)
Multiples two sextadecic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element.
[in] b - the sextadecic extension field element.
Definition at line 153 of file relic_fp16_mul.c.
References dv8_free, dv8_new, dv8_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp8_add(), fp8_free, fp8_mul_unr(), fp8_new, fp8_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp16_mul_lazyr().
fp16_mul_lazyr()
void fp16_mul_lazyr (fp16_t c, const fp16_t a, const fp16_t b)
Multiples two sextadecic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element.
[in] b - the sextadecic extension field element.
Definition at line 216 of file relic_fp16_mul.c.
References dv16_free, dv16_new, dv16_null, ERR_CAUGHT, fp16_mul_unr(), fp2_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_mul_dxs_lazyr()
void fp16_mul_dxs_lazyr (fp16_t c, const fp16_t a, const fp16_t b)
Definition at line 238 of file relic_fp16_mul.c.
References dv16_free, dv16_new, dv16_null, dv8_free, dv8_new, dv8_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp4_add(), fp4_is_zero(), fp4_mul_unr(), fp8_add(), fp8_free, fp8_mul_unr(), fp8_new, fp8_null, fp_muln_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
fp16_mul_art()
void fp16_mul_art (fp16_t c, const fp16_t a)
Multiplies an sextadecic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to multiply.
Definition at line 343 of file relic_fp16_mul.c.
References ERR_CAUGHT, fp8_copy(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.