RELIC: src/fpx/relic_fp16_sqr.c File Reference
relic_fp16_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp16_sqr_basic (fp16_t c, const fp16_t a)
void fp16_sqr_unr (dv16_t c, const fp16_t a)
void fp16_sqr_lazyr (fp16_t c, const fp16_t a)
void fp16_sqr_cyc (fp16_t c, const fp16_t a)
Detailed Description
Implementation of squaring in an sextadecic extension of a prime field.
Definition in file relic_fp16_sqr.c.
Function Documentation
fp16_sqr_basic()
void fp16_sqr_basic (fp16_t c, const fp16_t a)
Computes the squares of an sextadecic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to square.
Definition at line 42 of file relic_fp16_sqr.c.
References ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul, fp8_mul_art(), fp8_new, fp8_null, fp8_sub(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_sqr_unr()
void fp16_sqr_unr (dv16_t c, const fp16_t a)
Computes the square of an sextadecic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to square.
Definition at line 73 of file relic_fp16_sqr.c.
References dv8_free, dv8_new, dv8_null, dv_copy(), ERR_CAUGHT, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp8_add(), fp8_free, fp8_new, fp8_null, fp8_sqr_unr(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_THROW, and RLC_TRY.
Referenced by fp16_sqr_lazyr().
fp16_sqr_lazyr()
void fp16_sqr_lazyr (fp16_t c, const fp16_t a)
Computes the square of an sextadecic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the sextadecic extension field element to square.
Definition at line 129 of file relic_fp16_sqr.c.
References dv16_free, dv16_new, dv16_null, ERR_CAUGHT, fp16_sqr_unr(), fp2_rdcn_low(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
fp16_sqr_cyc()
void fp16_sqr_cyc (fp16_t c, const fp16_t a)
Computes the square of a cyclotomic sextadecic extension field element.
Parameters
[out] c - the result.
[in] a - the cyclotomic extension element to square.
Definition at line 153 of file relic_fp16_sqr.c.
References ERR_CAUGHT, fp8_add(), fp8_dbl(), fp8_free, fp8_mul_art(), fp8_new, fp8_null, fp8_sqr, fp8_sub(), fp_add_dig(), fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by fp16_exp_cyc(), fp16_exp_cyc_sim(), fp16_exp_dig(), pp_exp_afg16(), and pp_exp_kss().