RELIC: src/epx/relic_ep3_mul_cof.c File Reference
relic_ep3_mul_cof.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_md.h"
Functions
static void ep3_mul_cof_k18 (ep3_t r, const ep3_t p)
static void ep3_mul_cof_sg18 (ep3_t r, const ep3_t p)
static void ep3_mul_cof_fm18 (ep3_t r, const ep3_t p)
void ep3_mul_cof (ep3_t r, const ep3_t p)
Detailed Description
Implementation of point multiplication of a prime elliptic curve over a cubic extension field by the curve cofactor.
Definition in file relic_ep3_mul_cof.c.
Function Documentation
ep3_mul_cof_k18()
static void ep3_mul_cof_k18 (ep3_t r, const ep3_t p) static
Multiplies a point by the cofactor in a KSS18 curve.
Parameters
[out] r - the result.
[in] p - the point to multiply.
Definition at line 46 of file relic_ep3_mul_cof.c.
References bn_free, bn_new, bn_null, ep3_add, ep3_dbl, ep3_frb(), ep3_free, ep3_mul_basic(), ep3_neg(), ep3_new, ep3_norm(), ep3_null, ep3_sub(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_cof().
ep3_mul_cof_sg18()
static void ep3_mul_cof_sg18 (ep3_t r, const ep3_t p) static
Multiplies a point by the cofactor in a Scott-Guillevic curve.
Parameters
[out] r - the result.
[in] p - the point to multiply.
Definition at line 156 of file relic_ep3_mul_cof.c.
References bn_div_dig(), bn_free, bn_mul_dig(), bn_new, bn_null, ep3_add, ep3_dbl, ep3_frb(), ep3_free, ep3_mul_basic(), ep3_new, ep3_norm(), ep3_null, ep3_sub(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_cof().
ep3_mul_cof_fm18()
static void ep3_mul_cof_fm18 (ep3_t r, const ep3_t p) static
Multiplies a point by the cofactor in a Fotiadis-Mardindale curve.
Parameters
[out] r - the result.
[in] p - the point to multiply.
Definition at line 224 of file relic_ep3_mul_cof.c.
References bn_add_dig(), bn_div_dig(), bn_free, bn_new, bn_null, ep3_add, ep3_dbl, ep3_frb(), ep3_free, ep3_mul_basic(), ep3_new, ep3_norm(), ep3_null, ep3_sub(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_cof().
ep3_mul_cof()
void ep3_mul_cof (ep3_t r, const ep3_t p)
Multiplies a point in an elliptic curve over a cubic extension field by the curve cofactor or a small multiple for which a short vector exists. In short, it takes a point in the curve to the large prime-order subgroup.
Parameters
[out] R - the result.
[in] P - the point to multiply.
Definition at line 301 of file relic_ep3_mul_cof.c.
References bn_free, bn_null, ep3_curve_get_cof(), ep3_mul_big, ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep_curve_is_pairf(), EP_FM18, EP_K18, EP_SG18, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_map().