RELIC: src/md/blake2.h File Reference
blake2.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct __blake2s_param
struct __blake2b_param
struct __blake2sp_state
struct __blake2bp_state
Macros
#define __BLAKE2_H__
#define ALIGNME(x) __attribute__((aligned(x)))
Typedefs
typedef struct __blake2s_param blake2s_param
typedef struct __blake2b_param blake2b_param
typedef struct __blake2sp_state blake2sp_state
typedef struct __blake2bp_state blake2bp_state
Enumerations
enum blake2s_constant {
BLAKE2S_BLOCKBYTES = 64, BLAKE2S_OUTBYTES = 32, BLAKE2S_KEYBYTES = 32, BLAKE2S_SALTBYTES = 8,
BLAKE2S_PERSONALBYTES = 8
}
enum blake2b_constant {
BLAKE2B_BLOCKBYTES = 128, BLAKE2B_OUTBYTES = 64, BLAKE2B_KEYBYTES = 64, BLAKE2B_SALTBYTES = 16,
BLAKE2B_PERSONALBYTES = 16
}
Functions
ALIGNME (64) typedef struct __blake2s_state
int blake2s_init (blake2s_state *S, const uint8_t outlen)
int blake2s_init_key (blake2s_state *S, const uint8_t outlen, const void *key, const uint8_t keylen)
int blake2s_init_param (blake2s_state *S, const blake2s_param *P)
int blake2s_update (blake2s_state *S, const uint8_t *in, uint64_t inlen)
int blake2s_final (blake2s_state *S, uint8_t *out, uint8_t outlen)
int blake2b_init (blake2b_state *S, const uint8_t outlen)
int blake2b_init_key (blake2b_state *S, const uint8_t outlen, const void *key, const uint8_t keylen)
int blake2b_init_param (blake2b_state *S, const blake2b_param *P)
int blake2b_update (blake2b_state *S, const uint8_t *in, uint64_t inlen)
int blake2b_final (blake2b_state *S, uint8_t *out, uint8_t outlen)
int blake2sp_init (blake2sp_state *S, const uint8_t outlen)
int blake2sp_init_key (blake2sp_state *S, const uint8_t outlen, const void *key, const uint8_t keylen)
int blake2sp_update (blake2sp_state *S, const uint8_t *in, uint64_t inlen)
int blake2sp_final (blake2sp_state *S, uint8_t *out, uint8_t outlen)
int blake2bp_init (blake2bp_state *S, const uint8_t outlen)
int blake2bp_init_key (blake2bp_state *S, const uint8_t outlen, const void *key, const uint8_t keylen)
int blake2bp_update (blake2bp_state *S, const uint8_t *in, uint64_t inlen)
int blake2bp_final (blake2bp_state *S, uint8_t *out, uint8_t outlen)
int blake2s (uint8_t *out, const void *in, const void *key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen)
int blake2b (uint8_t *out, const void *in, const void *key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen)
int blake2sp (uint8_t *out, const void *in, const void *key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen)
int blake2bp (uint8_t *out, const void *in, const void *key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen)
static int blake2 (uint8_t *out, const void *in, const void *key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen)
Variables
blake2s_state
blake2b_state
Macro Definition Documentation
__BLAKE2_H__
#define __BLAKE2_H__
Definition at line 15 of file blake2.h.
ALIGNME
#define ALIGNME (x) __attribute__((aligned(x)))
Definition at line 23 of file blake2.h.
Typedef Documentation
blake2s_param
typedef struct __blake2s_param blake2s_param
blake2b_param
typedef struct __blake2b_param blake2b_param
blake2sp_state
typedef struct __blake2sp_state blake2sp_state
blake2bp_state
typedef struct __blake2bp_state blake2bp_state
Enumeration Type Documentation
blake2s_constant
enum blake2s_constant
Enumerator
BLAKE2S_BLOCKBYTES
BLAKE2S_OUTBYTES
BLAKE2S_KEYBYTES
BLAKE2S_SALTBYTES
BLAKE2S_PERSONALBYTES
Definition at line 30 of file blake2.h.
blake2b_constant
enum blake2b_constant
Enumerator
BLAKE2B_BLOCKBYTES
BLAKE2B_OUTBYTES
BLAKE2B_KEYBYTES
BLAKE2B_SALTBYTES
BLAKE2B_PERSONALBYTES
Definition at line 39 of file blake2.h.
Function Documentation
ALIGNME()
ALIGNME (64)
Definition at line 64 of file blake2.h.
References BLAKE2S_BLOCKBYTES.
blake2s_init()
int blake2s_init (blake2s_state * S, const uint8_t outlen)
Definition at line 156 of file blake2s-ref.c.
References blake2s_init_param(), BLAKE2S_OUTBYTES, __blake2s_param::depth, __blake2s_param::digest_length, __blake2s_param::fanout, __blake2s_param::inner_length, __blake2s_param::key_length, __blake2s_param::leaf_length, __blake2s_param::node_depth, __blake2s_param::node_offset, __blake2s_param::personal, __blake2s_param::salt, store32(), and store48().
Referenced by blake2s().
blake2s_init_key()
int blake2s_init_key (blake2s_state * S, const uint8_t outlen, const void * key, const uint8_t keylen)
Definition at line 177 of file blake2s-ref.c.
References BLAKE2S_BLOCKBYTES, blake2s_init_param(), BLAKE2S_KEYBYTES, BLAKE2S_OUTBYTES, blake2s_update(), __blake2s_param::depth, __blake2s_param::digest_length, __blake2s_param::fanout, __blake2s_param::inner_length, __blake2s_param::key_length, __blake2s_param::leaf_length, __blake2s_param::node_depth, __blake2s_param::node_offset, __blake2s_param::personal, __blake2s_param::salt, secure_zero_memory(), store32(), and store48().
Referenced by blake2s().
blake2s_init_param()
int blake2s_init_param (blake2s_state * S, const blake2s_param * P)
Definition at line 142 of file blake2s-ref.c.
References blake2s_init0(), and load32().
Referenced by blake2s_init(), and blake2s_init_key().
blake2s_update()
int blake2s_update (blake2s_state * S, const uint8_t * in, uint64_t inlen)
Definition at line 270 of file blake2s-ref.c.
References BLAKE2S_BLOCKBYTES, blake2s_compress(), and blake2s_increment_counter().
Referenced by blake2s(), and blake2s_init_key().
blake2s_final()
int blake2s_final (blake2s_state * S, uint8_t * out, uint8_t outlen)
Definition at line 300 of file blake2s-ref.c.
References BLAKE2S_BLOCKBYTES, blake2s_compress(), blake2s_increment_counter(), BLAKE2S_OUTBYTES, blake2s_set_lastblock(), and store32().
Referenced by blake2s().
blake2b_init()
int blake2b_init (blake2b_state * S, const uint8_t outlen)
blake2b_init_key()
int blake2b_init_key (blake2b_state * S, const uint8_t outlen, const void * key, const uint8_t keylen)
blake2b_init_param()
int blake2b_init_param (blake2b_state * S, const blake2b_param * P)
blake2b_update()
int blake2b_update (blake2b_state * S, const uint8_t * in, uint64_t inlen)
blake2b_final()
int blake2b_final (blake2b_state * S, uint8_t * out, uint8_t outlen)
blake2sp_init()
int blake2sp_init (blake2sp_state * S, const uint8_t outlen)
blake2sp_init_key()
int blake2sp_init_key (blake2sp_state * S, const uint8_t outlen, const void * key, const uint8_t keylen)
blake2sp_update()
int blake2sp_update (blake2sp_state * S, const uint8_t * in, uint64_t inlen)
blake2sp_final()
int blake2sp_final (blake2sp_state * S, uint8_t * out, uint8_t outlen)
blake2bp_init()
int blake2bp_init (blake2bp_state * S, const uint8_t outlen)
blake2bp_init_key()
int blake2bp_init_key (blake2bp_state * S, const uint8_t outlen, const void * key, const uint8_t keylen)
blake2bp_update()
int blake2bp_update (blake2bp_state * S, const uint8_t * in, uint64_t inlen)
blake2bp_final()
int blake2bp_final (blake2bp_state * S, uint8_t * out, uint8_t outlen)
blake2s()
int blake2s (uint8_t * out, const void * in, const void * key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen)
Definition at line 327 of file blake2s-ref.c.
References blake2s_final(), blake2s_init(), blake2s_init_key(), blake2s_state, and blake2s_update().
Referenced by md_map_b2s160(), and md_map_b2s256().
blake2b()
int blake2b (uint8_t * out, const void * in, const void * key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen)
Referenced by blake2().
blake2sp()
int blake2sp (uint8_t * out, const void * in, const void * key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen)
blake2bp()
int blake2bp (uint8_t * out, const void * in, const void * key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen)
blake2()
static int blake2 (uint8_t * out, const void * in, const void * key, const uint8_t outlen, const uint64_t inlen, uint8_t keylen) inline static
Definition at line 146 of file blake2.h.
References blake2b().
Variable Documentation
blake2s_state
blake2s_state
Definition at line 72 of file blake2.h.
Referenced by blake2s(), and blake2s_init0().
blake2b_state
blake2b_state
Definition at line 97 of file blake2.h.