RELIC: src/ep/relic_ep_psi.c File Reference
relic_ep_psi.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
#include "relic_ep.h"
Functions
void ep_psi (ep_t r, const ep_t p)
Detailed Description
Implementation of the endomorphism map on prime elliptic curves.
Definition in file relic_ep_psi.c.
Function Documentation
ep_psi()
void ep_psi (ep_t r, const ep_t p)
Computes the endomorphism map of a prime elliptic curve point. Computes R = \psi(P).
Parameters
[out] r - the result.
[in] p - the point.
Definition at line 39 of file relic_ep_psi.c.
References ep_copy(), ep_curve_get_beta(), ep_curve_opt_a(), ep_is_infty(), ep_set_infty(), fp_mul, fp_neg, and RLC_ZERO.
Referenced by ep_curve_set_endom(), ep_mul_cof(), ep_mul_combs_endom(), ep_mul_glv_imp(), ep_mul_reg_glv(), ep_mul_sim_endom(), ep_mul_sim_lot_endom(), and g1_is_valid().