RELIC: src/epx/relic_ep3_mul_sim.c File Reference
relic_ep3_mul_sim.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep3_mul_sim_plain (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m, ep3_t *t)
void ep3_mul_sim_basic (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t l)
void ep3_mul_sim_trick (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
void ep3_mul_sim_inter (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
void ep3_mul_sim_joint (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
void ep3_mul_sim_gen (ep3_t r, const bn_t k, const ep3_t q, const bn_t m)
void ep3_mul_sim_dig (ep3_t r, const ep3_t p[], const dig_t k[], size_t len)
void ep3_mul_sim_lot (ep3_t r, const ep3_t p[], const bn_t k[], int n)
Detailed Description
Implementation of simultaneous point multiplication on a prime elliptic curve over a cubic extension field.
Definition in file relic_ep3_mul_sim.c.
Function Documentation
ep3_mul_sim_plain()
static void ep3_mul_sim_plain (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m, ep3_t * t) static
Multiplies and adds two prime elliptic curve points simultaneously, optionally choosing the first point as the generator depending on an optional table of precomputed points.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
[in] t - the pointer to the precomputed table.
Definition at line 53 of file relic_ep3_mul_sim.c.
References bn_rec_naf(), bn_sign(), ep3_add, ep3_dbl, ep3_free, ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ep3_sub(), ep3_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep3_mul_sim_gen(), and ep3_mul_sim_inter().
ep3_mul_sim_basic()
void ep3_mul_sim_basic (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 149 of file relic_ep3_mul_sim.c.
References ep3_add, ep3_free, ep3_mul, ep3_new, ep3_norm(), ep3_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_sim_trick()
void ep3_mul_sim_trick (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 174 of file relic_ep3_mul_sim.c.
References bn_free, bn_is_zero(), bn_new, bn_null, bn_rec_win(), bn_sign(), ep3_add, ep3_copy(), ep3_curve_get_ord(), ep3_dbl, ep3_free, ep3_is_infty(), ep3_mul, ep3_neg(), ep3_new, ep3_norm(), ep3_norm_sim(), ep3_null, ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
ep3_mul_sim_inter()
void ep3_mul_sim_inter (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 267 of file relic_ep3_mul_sim.c.
References bn_is_zero(), ep3_is_infty(), ep3_mul, and ep3_mul_sim_plain().
ep3_mul_sim_joint()
void ep3_mul_sim_joint (ep3_t r, const ep3_t p, const bn_t k, const ep3_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 285 of file relic_ep3_mul_sim.c.
References bn_bits(), bn_is_zero(), bn_rec_jsf(), bn_sign(), ep3_add, ep3_copy(), ep3_dbl, ep3_free, ep3_is_infty(), ep3_mul, ep3_neg(), ep3_new, ep3_norm(), ep3_norm_sim(), ep3_null, ep3_set_infty(), ep3_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
ep3_mul_sim_gen()
void ep3_mul_sim_gen (ep3_t r, const bn_t k, const ep3_t q, const bn_t m)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = [k]G + [l]Q.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 360 of file relic_ep3_mul_sim.c.
References bn_is_zero(), ep3_curve_get_gen(), ep3_curve_get_tab(), ep3_free, ep3_is_infty(), ep3_mul, ep3_mul_gen(), ep3_mul_sim, ep3_mul_sim_plain(), ep3_new, ep3_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_sim_dig()
void ep3_mul_sim_dig (ep3_t r, const ep3_t p[], const dig_t k[], size_t len)
Multiplies prime elliptic curve points by small scalars. Computes R = \sum k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the small scalars.
[in] len - the number of points to multiply.
Definition at line 392 of file relic_ep3_mul_sim.c.
References ep3_add, ep3_dbl, ep3_free, ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_MAX, RLC_THROW, RLC_TRY, and util_bits_dig().
ep3_mul_sim_lot()
void ep3_mul_sim_lot (ep3_t r, const ep3_t p[], const bn_t k[], int n)
Multiplies simultaneously elements from a prime elliptic curve. Computes R = \Sum_i=0..n k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the integer scalars.
[in] n - the number of elements to multiply.
Definition at line 426 of file relic_ep3_mul_sim.c.
References bn_free, bn_new, bn_null, bn_rec_frb(), bn_rec_naf(), bn_sign(), ep3_add, ep3_copy(), ep3_dbl, ep3_frb(), ep3_free, ep3_neg(), ep3_new, ep3_norm(), ep3_null, ep3_set_infty(), ep3_sub(), EP_BN, ep_curve_get_ord(), ep_curve_is_pairf(), ERR_CAUGHT, fp_prime_get_par(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().