RELIC: src/bc/rijndael-api-fst.h File Reference
rijndael-api-fst.h File Reference
#include <stdio.h>
#include "rijndael-alg-fst.h"
Data Structures
struct keyInstance
struct cipherInstance
Macros
#define DIR_ENCRYPT 0 /* Are we encrpyting? */
#define DIR_DECRYPT 1 /* Are we decrpyting? */
#define MODE_ECB 1 /* Are we ciphering in ECB mode? */
#define MODE_CBC 2 /* Are we ciphering in CBC mode? */
#define MODE_CFB1 3 /* Are we ciphering in 1-bit CFB mode? */
#define TRUE 1
#define FALSE 0
#define BITSPERBLOCK 128 /* Default number of bits in a cipher block */
#define BAD_KEY_DIR -1 /* Key direction is invalid, e.g., unknown value */
#define BAD_KEY_MAT -2 /* Key material not of correct length */
#define BAD_KEY_INSTANCE -3 /* Key passed is not valid */
#define BAD_CIPHER_MODE -4 /* Params struct passed to cipherInit invalid */
#define BAD_CIPHER_STATE -5 /* Cipher in wrong state (e.g., not initialized) */
#define BAD_BLOCK_LENGTH -6
#define BAD_CIPHER_INSTANCE -7
#define BAD_DATA -8 /* Data contents are invalid, e.g., invalid padding */
#define BAD_OTHER -9 /* Unknown error */
#define MAX_KEY_SIZE 64 /* # of ASCII char's needed to represent a key */
#define MAX_IV_SIZE 16 /* # bytes needed to represent an IV */
Typedefs
typedef unsigned char BYTE
Functions
int makeKey (keyInstance *key, BYTE direction, int keyLen, char *keyMaterial)
int makeKey2 (keyInstance *key, BYTE direction, int keyLen, char *keyMaterial)
int cipherInit (cipherInstance *cipher, BYTE mode, char *IV)
int blockEncrypt (cipherInstance *cipher, keyInstance *key, BYTE *input, int inputLen, BYTE *outBuffer)
int padEncrypt (cipherInstance *cipher, keyInstance *key, BYTE *input, int inputOctets, BYTE *outBuffer)
int blockDecrypt (cipherInstance *cipher, keyInstance *key, BYTE *input, int inputLen, BYTE *outBuffer)
int padDecrypt (cipherInstance *cipher, keyInstance *key, BYTE *input, int inputOctets, BYTE *outBuffer)
Macro Definition Documentation
DIR_ENCRYPT
#define DIR_ENCRYPT 0 /* Are we encrpyting? */
rijndael-api-fst.h
Version
2.9 (December 2000)
Optimised ANSI C code for the Rijndael cipher (now AES)
Author
Vincent Rijmen vince.nosp@m.nt.r.nosp@m.ijmen.nosp@m.@esa.nosp@m.t.kul.nosp@m.euve.nosp@m.n.ac..nosp@m.be
Antoon Bosselaers antoo.nosp@m.n.bo.nosp@m.ssela.nosp@m.ers@.nosp@m.esat..nosp@m.kule.nosp@m.uven..nosp@m.ac.b.nosp@m.e
Paulo Barreto paulo.nosp@m..bar.nosp@m.reto@.nosp@m.terr.nosp@m.a.com.nosp@m..br
This code is hereby placed in the public domain.
THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Acknowledgements:
We are deeply indebted to the following people for their bug reports, fixes, and improvement suggestions to this implementation. Though we tried to list all contributions, we apologise in advance for any missing reference.
Andrew Bales Andre.nosp@m.w.Ba.nosp@m.les@H.nosp@m.oney.nosp@m.well..nosp@m.com Markus Friedl marku.nosp@m.s.fr.nosp@m.iedl@.nosp@m.info.nosp@m.rmati.nosp@m.k.un.nosp@m.i-erl.nosp@m.ange.nosp@m.n.de John Skodon skodo.nosp@m.nj@w.nosp@m.ebqui.nosp@m.ll.c.nosp@m.om
Definition at line 45 of file rijndael-api-fst.h.
DIR_DECRYPT
#define DIR_DECRYPT 1 /* Are we decrpyting? */
Definition at line 46 of file rijndael-api-fst.h.
MODE_ECB
#define MODE_ECB 1 /* Are we ciphering in ECB mode? */
Definition at line 47 of file rijndael-api-fst.h.
MODE_CBC
#define MODE_CBC 2 /* Are we ciphering in CBC mode? */
Definition at line 48 of file rijndael-api-fst.h.
MODE_CFB1
#define MODE_CFB1 3 /* Are we ciphering in 1-bit CFB mode? */
Definition at line 49 of file rijndael-api-fst.h.
TRUE
#define TRUE 1
Definition at line 50 of file rijndael-api-fst.h.
FALSE
#define FALSE 0
Definition at line 51 of file rijndael-api-fst.h.
BITSPERBLOCK
#define BITSPERBLOCK 128 /* Default number of bits in a cipher block */
Definition at line 52 of file rijndael-api-fst.h.
BAD_KEY_DIR
#define BAD_KEY_DIR -1 /* Key direction is invalid, e.g., unknown value */
Definition at line 55 of file rijndael-api-fst.h.
BAD_KEY_MAT
#define BAD_KEY_MAT -2 /* Key material not of correct length */
Definition at line 56 of file rijndael-api-fst.h.
BAD_KEY_INSTANCE
#define BAD_KEY_INSTANCE -3 /* Key passed is not valid */
Definition at line 57 of file rijndael-api-fst.h.
BAD_CIPHER_MODE
#define BAD_CIPHER_MODE -4 /* Params struct passed to cipherInit invalid */
Definition at line 58 of file rijndael-api-fst.h.
BAD_CIPHER_STATE
#define BAD_CIPHER_STATE -5 /* Cipher in wrong state (e.g., not initialized) */
Definition at line 59 of file rijndael-api-fst.h.
BAD_BLOCK_LENGTH
#define BAD_BLOCK_LENGTH -6
Definition at line 60 of file rijndael-api-fst.h.
BAD_CIPHER_INSTANCE
#define BAD_CIPHER_INSTANCE -7
Definition at line 61 of file rijndael-api-fst.h.
BAD_DATA
#define BAD_DATA -8 /* Data contents are invalid, e.g., invalid padding */
Definition at line 62 of file rijndael-api-fst.h.
BAD_OTHER
#define BAD_OTHER -9 /* Unknown error */
Definition at line 63 of file rijndael-api-fst.h.
MAX_KEY_SIZE
#define MAX_KEY_SIZE 64 /* # of ASCII char's needed to represent a key */
Definition at line 66 of file rijndael-api-fst.h.
MAX_IV_SIZE
#define MAX_IV_SIZE 16 /* # bytes needed to represent an IV */
Definition at line 67 of file rijndael-api-fst.h.
Typedef Documentation
BYTE
typedef unsigned char BYTE
Definition at line 71 of file rijndael-api-fst.h.
Function Documentation
makeKey()
int makeKey (keyInstance * key, BYTE direction, int keyLen, char * keyMaterial)
rijndael-api-fst.c
Version
2.9 (December 2000)
Optimised ANSI C code for the Rijndael cipher (now AES)
Author
Vincent Rijmen vince.nosp@m.nt.r.nosp@m.ijmen.nosp@m.@esa.nosp@m.t.kul.nosp@m.euve.nosp@m.n.ac..nosp@m.be
Antoon Bosselaers antoo.nosp@m.n.bo.nosp@m.ssela.nosp@m.ers@.nosp@m.esat..nosp@m.kule.nosp@m.uven..nosp@m.ac.b.nosp@m.e
Paulo Barreto paulo.nosp@m..bar.nosp@m.reto@.nosp@m.terr.nosp@m.a.com.nosp@m..br
This code is hereby placed in the public domain.
THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Acknowledgements:
We are deeply indebted to the following people for their bug reports, fixes, and improvement suggestions to this implementation. Though we tried to list all contributions, we apologise in advance for any missing reference.
Andrew Bales Andre.nosp@m.w.Ba.nosp@m.les@H.nosp@m.oney.nosp@m.well..nosp@m.com Markus Friedl marku.nosp@m.s.fr.nosp@m.iedl@.nosp@m.info.nosp@m.rmati.nosp@m.k.un.nosp@m.i-erl.nosp@m.ange.nosp@m.n.de John Skodon skodo.nosp@m.nj@w.nosp@m.ebqui.nosp@m.ll.c.nosp@m.om
Definition at line 46 of file rijndael-api-fst.c.
References BAD_KEY_DIR, BAD_KEY_INSTANCE, BAD_KEY_MAT, DIR_DECRYPT, DIR_ENCRYPT, keyInstance::direction, keyInstance::ek, keyInstance::keyLen, keyInstance::keyMaterial, MAXKB, keyInstance::Nr, rijndaelKeySetupDec(), rijndaelKeySetupEnc(), keyInstance::rk, and TRUE.
makeKey2()
int makeKey2 (keyInstance * key, BYTE direction, int keyLen, char * keyMaterial)
Definition at line 108 of file rijndael-api-fst.c.
References BAD_KEY_DIR, BAD_KEY_INSTANCE, BAD_KEY_MAT, DIR_DECRYPT, DIR_ENCRYPT, keyInstance::direction, keyInstance::ek, keyInstance::keyLen, keyInstance::keyMaterial, MAXKB, keyInstance::Nr, rijndaelKeySetupDec(), rijndaelKeySetupEnc(), keyInstance::rk, and TRUE.
Referenced by bc_aes_cbc_dec(), and bc_aes_cbc_enc().
cipherInit()
int cipherInit (cipherInstance * cipher, BYTE mode, char * IV)
Definition at line 148 of file rijndael-api-fst.c.
References BAD_CIPHER_INSTANCE, BAD_CIPHER_MODE, cipherInstance::IV, MAX_IV_SIZE, cipherInstance::mode, MODE_CBC, MODE_CFB1, MODE_ECB, and TRUE.
Referenced by bc_aes_cbc_dec(), and bc_aes_cbc_enc().
blockEncrypt()
int blockEncrypt (cipherInstance * cipher, keyInstance * key, BYTE * input, int inputLen, BYTE * outBuffer)
Definition at line 187 of file rijndael-api-fst.c.
References BAD_CIPHER_STATE, DIR_DECRYPT, keyInstance::direction, keyInstance::ek, cipherInstance::IV, cipherInstance::mode, MODE_CBC, MODE_CFB1, MODE_ECB, keyInstance::Nr, rijndaelEncrypt(), and keyInstance::rk.
padEncrypt()
int padEncrypt (cipherInstance * cipher, keyInstance * key, BYTE * input, int inputOctets, BYTE * outBuffer)
Encrypt data partitioned in octets, using RFC 2040-like padding.
Parameters
input data to be encrypted (octet sequence)
inputOctets input length in octets (not bits)
outBuffer encrypted output data
Returns
length in octets (not bits) of the encrypted output buffer.
Definition at line 270 of file rijndael-api-fst.c.
References BAD_CIPHER_STATE, DIR_DECRYPT, keyInstance::direction, cipherInstance::IV, cipherInstance::mode, MODE_CBC, MODE_ECB, keyInstance::Nr, rijndaelEncrypt(), and keyInstance::rk.
Referenced by bc_aes_cbc_enc().
blockDecrypt()
int blockDecrypt (cipherInstance * cipher, keyInstance * key, BYTE * input, int inputLen, BYTE * outBuffer)
Definition at line 340 of file rijndael-api-fst.c.
References BAD_CIPHER_STATE, DIR_ENCRYPT, keyInstance::direction, keyInstance::ek, cipherInstance::IV, cipherInstance::mode, MODE_CBC, MODE_CFB1, MODE_ECB, keyInstance::Nr, rijndaelDecrypt(), rijndaelEncrypt(), and keyInstance::rk.
padDecrypt()
int padDecrypt (cipherInstance * cipher, keyInstance * key, BYTE * input, int inputOctets, BYTE * outBuffer)
Definition at line 416 of file rijndael-api-fst.c.
References BAD_CIPHER_STATE, BAD_DATA, DIR_ENCRYPT, keyInstance::direction, cipherInstance::IV, cipherInstance::mode, MODE_CBC, MODE_ECB, keyInstance::Nr, rijndaelDecrypt(), and keyInstance::rk.
Referenced by bc_aes_cbc_dec().