RELIC: src/bn/relic_bn_util.c File Reference
relic_bn_util.c File Reference
Multiple precision integer arithmetic
#include <inttypes.h>
#include "relic_core.h"
Macros
#define RAND_DIST 40
Functions
void bn_copy (bn_t c, const bn_t a)
void bn_abs (bn_t c, const bn_t a)
void bn_neg (bn_t c, const bn_t a)
int bn_sign (const bn_t a)
void bn_zero (bn_t a)
int bn_is_zero (const bn_t a)
int bn_is_even (const bn_t a)
int bn_bits (const bn_t a)
int bn_get_bit (const bn_t a, int bit)
void bn_set_bit (bn_t a, int bit, int value)
int bn_ham (const bn_t a)
void bn_get_dig (dig_t *c, const bn_t a)
void bn_set_dig (bn_t a, dig_t digit)
void bn_set_2b (bn_t a, int b)
void bn_rand (bn_t a, int sign, int bits)
void bn_rand_mod (bn_t a, bn_t b)
void bn_print (const bn_t a)
int bn_size_str (const bn_t a, int radix)
void bn_read_str (bn_t a, const char *str, int len, int radix)
void bn_write_str (char *str, int len, const bn_t a, int radix)
int bn_size_bin (const bn_t a)
void bn_read_bin (bn_t a, const uint8_t *bin, int len)
void bn_write_bin (uint8_t *bin, int len, const bn_t a)
int bn_size_raw (const bn_t a)
void bn_read_raw (bn_t a, const dig_t *raw, int len)
void bn_write_raw (dig_t *raw, int len, const bn_t a)
Detailed Description
Implementation of the multiple precision utilities.
Definition in file relic_bn_util.c.
Macro Definition Documentation
RAND_DIST
#define RAND_DIST 40
Statistical distance 1/2^\lambda between sampling and uniform distribution.
Definition at line 43 of file relic_bn_util.c.
Function Documentation
bn_copy()
void bn_copy (bn_t c, const bn_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to copy.
Definition at line 49 of file relic_bn_util.c.
References bn_grow(), bn_st::dp, dv_copy(), bn_st::sign, and bn_st::used.
Referenced by bn_abs(), bn_add_imp(), bn_div_dig(), bn_div_imp(), bn_div_rem_dig(), bn_factor(), bn_gcd_basic(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_lehme(), bn_gcd_stein(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lsh(), bn_mod_2b(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mod_monty_conv(), bn_mod_pmers(), bn_mul_basic(), bn_mul_comba(), bn_mul_karat_imp(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_slide(), bn_neg(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_rsh(), bn_size_str(), bn_smb_jac(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_srt(), bn_sub_imp(), bn_write_str(), cp_bdpe_gen(), cp_psb_sig(), cp_rabin_gen(), cp_rsa_dec_quick(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_sig_quick(), eb_curve_get_cof(), eb_curve_get_ord(), eb_curve_set(), ed_curve_get_cof(), ed_curve_get_ord(), ed_param_set(), ep2_curve_get_cof(), ep2_curve_get_ord(), ep2_curve_get_vs(), ep2_curve_set(), ep2_curve_set_twist(), ep2_mul_glv_imp(), ep_curve_get_cof(), ep_curve_get_ord(), ep_curve_get_v1(), ep_curve_get_v2(), ep_curve_set_endom(), ep_curve_set_plain(), ep_curve_set_super(), fp12_exp_cyc(), fp_inv_binar(), fp_inv_exgcd(), fp_prime_get_par(), fp_prime_set(), and fp_prime_set_pairf().
bn_abs()
void bn_abs (bn_t c, const bn_t a)
Returns the absolute value of a multiple precision integer.
Parameters
[out] c - the result.
[in] a - the argument of the absolute function.
Definition at line 61 of file relic_bn_util.c.
References bn_copy(), bn_st::dp, RLC_POS, and bn_st::sign.
Referenced by bn_div_imp(), bn_gcd_basic(), bn_gcd_dig(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_lehme(), bn_gcd_stein(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_rec_tnaf_mod(), eb_mul_lodah(), ed_mul_reg_imp(), ep2_mul_glv_imp(), ep_mul_combs_endom(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), and fp12_exp_cyc().
bn_neg()
void bn_neg (bn_t c, const bn_t a)
Inverts the sign of a multiple precision integer.
Parameters
[out] c - the result.
[out] a - the multiple precision integer to negate.
Definition at line 68 of file relic_bn_util.c.
References bn_copy(), bn_is_zero(), bn_st::dp, and bn_st::sign.
Referenced by bn_div_imp(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_lehme(), bn_rec_glv(), bn_rec_tnaf_mod(), bn_smb_jac(), bn_smb_leg(), ep2_curve_get_vs(), ep2_mul_glv_imp(), ep_curve_set_endom(), ep_map(), fp12_exp_cyc(), and fp_param_set().
bn_sign()
int bn_sign (const bn_t a)
Returns the sign of a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
RLC_POS if the argument is positive and RLC_NEG otherwise.
Definition at line 77 of file relic_bn_util.c.
References bn_st::sign.
Referenced by bn_div_imp(), bn_is_prime_solov(), bn_mod_barrt(), bn_mod_monty_conv(), bn_mxp_basic(), bn_mxp_monty(), bn_mxp_slide(), bn_rand_mod(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_smb_jac(), bn_smb_leg(), bn_srt(), cp_bbs_sig(), cp_cmlhs_sig(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_ver(), cp_phpe_dec(), cp_rabin_dec(), cp_rsa_dec_quick(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), cp_rsa_sig_quick(), cp_zss_sig(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_fix_plain(), eb_mul_lnaf_imp(), eb_mul_lodah(), eb_mul_ltnaf_imp(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_plain(), eb_mul_sim_trick(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_reg_imp(), ed_mul_sim_joint(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ep2_mul_basic(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_ordin(), ep2_mul_glv_imp(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_sim_joint(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep_curve_set_endom(), ep_mul_basic(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_plain(), ep_mul_glv_imp(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_endom(), ep_mul_sim_joint(), ep_mul_sim_plain(), ep_mul_sim_trick(), ep_mul_slide(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fp12_exp(), fp12_exp_cyc(), fp18_exp(), fp24_exp(), fp2_exp(), fp2_exp_cyc(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp6_exp(), fp8_exp(), fp8_exp_cyc(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), fp_exp_slide(), fp_inv_binar(), fp_inv_exgcd(), pp_exp_b12(), pp_exp_bn(), pp_exp_k48(), pp_exp_k54(), pp_map_k48(), pp_map_k54(), pp_map_oatep_k12(), pp_map_oatep_k8(), and pp_map_sim_oatep_k12().
bn_zero()
void bn_zero (bn_t a)
Assigns zero to a multiple precision integer.
Parameters
[out] a - the multiple precision integer to assign.
Definition at line 81 of file relic_bn_util.c.
References bn_st::alloc, bn_st::dp, dv_zero(), RLC_POS, bn_st::sign, and bn_st::used.
Referenced by bn_div_imp(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_mod_2b(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mul_basic(), bn_mxp_basic(), bn_mxp_monty(), bn_mxp_slide(), bn_read_bin(), bn_read_str(), bn_rec_tnaf_mod(), bn_set_dig(), bn_smb_jac(), bn_smb_leg(), bn_sqr_basic(), cp_mklhs_fun(), cp_mklhs_onv(), cp_mklhs_ver(), cp_rabin_enc(), cp_rsa_enc(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), ep2_mul_glv_imp(), fp12_exp_cyc(), fp_inv_binar(), fp_inv_exgcd(), and fp_inv_monty().
bn_is_zero()
int bn_is_zero (const bn_t a)
Tests if a multiple precision integer is zero or not.
Parameters
[in] a - the multiple precision integer to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 87 of file relic_bn_util.c.
References bn_st::dp, and bn_st::used.
Referenced by bn_bits(), bn_div(), bn_div_dig(), bn_div_imp(), bn_div_rem(), bn_div_rem_dig(), bn_gcd_basic(), bn_gcd_dig(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_gcd_lehme(), bn_gcd_stein(), bn_is_even(), bn_is_factor(), bn_mod_pmers(), bn_mxp_basic(), bn_mxp_monty(), bn_mxp_slide(), bn_neg(), bn_rand_mod(), bn_rec_jsf(), bn_rec_naf(), bn_rec_tnaf(), bn_size_str(), bn_smb_jac(), bn_write_str(), cp_bbs_gen(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_fix_plain(), eb_mul_halve(), eb_mul_lodah(), eb_mul_lwnaf(), eb_mul_rwnaf(), eb_mul_sim_gen(), eb_mul_sim_inter(), eb_mul_sim_joint(), eb_mul_sim_trick(), ed_mul_basic(), ed_mul_fix_basic(), ed_mul_gen(), ed_mul_lwnaf(), ed_mul_lwreg(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_reg_imp(), ed_mul_sim_gen(), ed_mul_sim_inter(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), ep2_mul_basic(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_ordin(), ep2_mul_gen(), ep2_mul_lwnaf(), ep2_mul_monty(), ep2_mul_sim_gen(), ep2_mul_sim_inter(), ep2_mul_sim_joint(), ep2_mul_sim_trick(), ep2_mul_slide(), ep_mul_basic(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_fix_plain(), ep_mul_gen(), ep_mul_glv_imp(), ep_mul_lwnaf(), ep_mul_lwreg(), ep_mul_monty(), ep_mul_naf_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_gen(), ep_mul_sim_inter(), ep_mul_sim_joint(), ep_mul_sim_trick(), ep_mul_slide(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fp12_exp(), fp12_exp_cyc(), fp18_exp(), fp24_exp(), fp2_exp(), fp2_exp_cyc(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp6_exp(), fp8_exp(), fp8_exp_cyc(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), fp_exp_slide(), fp_inv_monty(), fp_prime_conv(), fp_read_bin(), and fp_read_str().
bn_is_even()
int bn_is_even (const bn_t a)
Tests if a multiple precision integer is even or odd.
Parameters
[in] a - the multiple precision integer to test.
Returns
1 if the argument is even, 0 otherwise.
Definition at line 97 of file relic_bn_util.c.
References bn_is_zero(), and bn_st::dp.
Referenced by bn_factor(), bn_gcd_ext_stein(), bn_gcd_stein(), bn_is_prime_rabin(), bn_rec_naf(), bn_rec_tnaf_mod(), bn_smb_jac(), ed_mul_reg_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), fp12_exp_cyc(), fp48_exp_cyc(), fp54_exp_cyc(), and fp_srt().
bn_bits()
int bn_bits (const bn_t a)
Returns the number of bits of a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
number of bits.
Definition at line 107 of file relic_bn_util.c.
References bn_is_zero(), bn_st::dp, RLC_DIG, bn_st::used, and util_bits_dig().
Referenced by bn_gcd_ext_lehme(), bn_gcd_lehme(), bn_gen_prime_basic(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_ham(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_lsh(), bn_mod_pmers(), bn_mod_pre_pmers(), bn_mxp_basic(), bn_mxp_monty(), bn_mxp_slide(), bn_rand_mod(), bn_rec_glv(), bn_rec_jsf(), bn_rec_naf(), bn_rec_rtnaf(), bn_rec_slw(), bn_rec_tnaf(), bn_rec_win(), bn_size_str(), bn_srt(), cp_ecdh_key(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecies_dec(), cp_ecies_enc(), cp_ecmqv_key(), cp_ecss_sig(), cp_ecss_ver(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), cp_rsa_ver(), eb_map(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_halve(), eb_mul_lodah(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_sim_joint(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_monty(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_joint(), ep2_map(), ep2_mul_basic(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_glv_imp(), ep2_mul_monty(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_sim_joint(), ep_curve_set_endom(), ep_map(), ep_mul_basic(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_monty(), ep_mul_pre_basic(), ep_mul_pre_combd(), ep_mul_pre_combs(), ep_mul_reg_glv(), ep_mul_reg_imp(), ep_mul_sim_joint(), fb_exp_basic(), fb_exp_monty(), fp12_exp(), fp12_exp_cyc(), fp18_exp(), fp24_exp(), fp2_exp(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp6_exp(), fp8_exp(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), fp_prime_set_pairf(), pp_mil_k12(), pp_mil_k2(), pp_mil_k48(), pp_mil_k54(), pp_mil_k8(), pp_mil_lit_k12(), and pp_mil_lit_k2().
bn_get_bit()
int bn_get_bit (const bn_t a, int bit)
Returns the bit stored in the given position on a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
[in] bit - the bit position to read.
Returns
the bit value.
Definition at line 120 of file relic_bn_util.c.
References bn_st::dp, RLC_RIP, and bn_st::used.
Referenced by bn_ham(), bn_mxp_basic(), bn_mxp_monty(), bn_rec_glv(), bn_rec_slw(), eb_mul_basic(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_lodah(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_monty(), ep2_mul_basic(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_glv_imp(), ep2_mul_monty(), ep_mul_basic(), ep_mul_combs_endom(), ep_mul_combs_plain(), ep_mul_fix_basic(), ep_mul_fix_combd(), ep_mul_monty(), fb_exp_basic(), fb_exp_monty(), fp12_exp(), fp12_exp_cyc(), fp18_exp(), fp24_exp(), fp2_exp(), fp3_exp(), fp48_exp(), fp48_exp_cyc(), fp4_exp(), fp54_exp(), fp54_exp_cyc(), fp6_exp(), fp8_exp(), fp9_exp(), fp_exp_basic(), fp_exp_monty(), pp_mil_k2(), pp_mil_lit_k12(), and pp_mil_lit_k2().
bn_set_bit()
void bn_set_bit (bn_t a, int bit, int value)
Stores a bit in a given position on a multiple precision integer.
Parameters
[out] a - the multiple precision integer.
[in] bit - the bit position to store.
[in] value - the bit value.
Definition at line 132 of file relic_bn_util.c.
References bn_trim(), bn_st::dp, RLC_RIP, and bn_st::used.
Referenced by cp_ecmqv_key(), and fp_param_set().
bn_ham()
int bn_ham (const bn_t a)
Returns the Hamming weight of a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
the number of non-zero bits.
Definition at line 148 of file relic_bn_util.c.
References bn_bits(), and bn_get_bit().
Referenced by fp12_exp_cyc(), fp48_exp_cyc(), and fp54_exp_cyc().
bn_get_dig()
void bn_get_dig (dig_t * digit, const bn_t a)
Reads the first digit in a multiple precision integer.
Parameters
[out] digit - the result.
[in] a - the multiple precision integer.
Definition at line 158 of file relic_bn_util.c.
References bn_st::dp.
Referenced by bn_rec_jsf(), bn_rec_naf(), and bn_rec_reg().
bn_set_dig()
void bn_set_dig (bn_t a, dig_t digit)
Assigns a small positive constant to a multiple precision integer.
The constant must fit on a multiple precision digit, or dig_t type using only the number of bits specified on RLC_DIG.
Parameters
[out] a - the result.
[in] digit - the constant to assign.
Definition at line 162 of file relic_bn_util.c.
References bn_zero(), bn_st::dp, RLC_POS, bn_st::sign, and bn_st::used.
Referenced by bn_div_imp(), bn_factor(), bn_gcd_dig(), bn_gcd_ext_basic(), bn_gcd_ext_dig(), bn_gcd_ext_lehme(), bn_gcd_ext_mid(), bn_gcd_ext_stein(), bn_is_prime_rabin(), bn_mod_barrt(), bn_mod_pre_monty(), bn_mxp_basic(), bn_mxp_dig(), bn_mxp_monty(), bn_mxp_slide(), bn_rec_tnaf_mod(), bn_smb_jac(), bn_smb_leg(), cp_bdpe_enc(), cp_bdpe_gen(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_monty(), fp_param_set(), fp_prime_set(), fp_prime_set_pairf(), and pp_exp_k8().
bn_set_2b()
void bn_set_2b (bn_t a, int b)
Assigns a multiple precision integer to 2^b.
Parameters
[out] a - the result.
[in] b - the power of 2 to assign.
Definition at line 169 of file relic_bn_util.c.
References bn_grow(), bn_st::dp, RLC_POS, RLC_RIP, bn_st::sign, and bn_st::used.
Referenced by bn_mod_pre_barrt(), bn_mod_pre_pmers(), bn_srt(), cp_rsa_gen_basic(), cp_rsa_gen_quick(), fp_inv_monty(), fp_param_set(), and fp_prime_set_pmers().
bn_rand()
void bn_rand (bn_t a, int sign, int bits)
Assigns a random value to a multiple precision integer.
Parameters
[out] a - the multiple precision integer to assign.
[in] sign - the sign to be assigned (RLC_NEG or RLC_POS).
[in] bits - the number of bits.
Definition at line 182 of file relic_bn_util.c.
References bn_grow(), bn_trim(), bn_st::dp, rand_bytes(), RLC_RIP, bn_st::sign, and bn_st::used.
Referenced by bn_gen_prime_basic(), bn_gen_prime_safep(), bn_gen_prime_stron(), bn_is_prime_solov(), bn_rand_mod(), cp_bbs_gen(), cp_bdpe_gen(), and eb_mul_halve().
bn_rand_mod()
void bn_rand_mod (bn_t a, bn_t b)
Assigns a non-zero random value to a multiple precision integer with absolute value smaller than a given modulus.
Parameters
[out] a - the multiple precision integer to assign.
[in] b - the modulus.
Definition at line 201 of file relic_bn_util.c.
References bn_bits(), bn_cmp_abs(), bn_is_zero(), bn_mod, bn_rand(), bn_sign(), RAND_DIST, and RLC_LT.
Referenced by cp_bdpe_enc(), cp_bgn_enc1(), cp_bgn_enc2(), cp_bgn_gen(), cp_bls_gen(), cp_clb_gen(), cp_cli_gen(), cp_cls_gen(), cp_cmlhs_gen(), cp_cmlhs_sig(), cp_ecdh_gen(), cp_ecdsa_gen(), cp_ecdsa_sig(), cp_ecies_enc(), cp_ecies_gen(), cp_ecmqv_gen(), cp_ecss_gen(), cp_ecss_sig(), cp_ibe_enc(), cp_ibe_gen(), cp_mklhs_gen(), cp_phpe_enc(), cp_psb_gen(), cp_pss_gen(), cp_sokaka_gen(), cp_vbnn_gen(), cp_vbnn_gen_prv(), cp_vbnn_sig(), cp_zss_gen(), eb_rand(), ed_rand(), ep2_rand(), and ep_rand().
bn_print()
void bn_print (const bn_t a)
Prints a multiple precision integer to standard output.
Parameters
[in] a - the multiple precision integer to print.
Definition at line 208 of file relic_bn_util.c.
References bn_st::dp, RLC_NEG, bn_st::sign, bn_st::used, util_print(), and util_print_dig().
bn_size_str()
int bn_size_str (const bn_t a, int radix)
Returns the number of digits in radix necessary to store a multiple precision integer. The radix must be included in the interval [2, 64].
Parameters
[in] a - the multiple precision integer.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Returns
the number of digits in the given radix.
Definition at line 232 of file relic_bn_util.c.
References bn_bits(), bn_copy(), bn_div_dig(), bn_free(), bn_is_zero(), bn_null, CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, FINALLY, RLC_NEG, RLC_POS, bn_st::sign, THROW, and TRY.
Referenced by bn_write_str(), fb_size_str(), and fp_size_str().
bn_read_str()
void bn_read_str (bn_t a, const char * str, int len, int radix)
Reads a multiple precision integer from a string in a given radix. The radix must be included in the interval [2, 64].
Parameters
[out] a - the result.
[in] str - the string.
[in] len - the size of the string.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Definition at line 275 of file relic_bn_util.c.
References bn_add_dig(), bn_mul_dig(), bn_zero(), ERR_NO_VALID, RLC_NEG, RLC_POS, RLC_UPP, bn_st::sign, THROW, and util_conv_char().
Referenced by fp_param_set(), and fp_read_str().
bn_write_str()
void bn_write_str (char * str, int len, const bn_t a, int radix)
Writes a multiple precision integer to a string in a given radix. The radix must be included in the interval [2, 64].
Parameters
[out] str - the string.
[in] len - the buffer capacity.
[in] a - the multiple integer to write.
[in] radix - the radix.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
ERR_NO_VALID - if the radix is invalid.
Definition at line 316 of file relic_bn_util.c.
References bn_copy(), bn_div_rem_dig(), bn_free(), bn_is_zero(), bn_null, bn_size_str(), CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_VALID, FINALLY, RLC_NEG, RLC_POS, bn_st::sign, THROW, TRY, and util_conv_char().
Referenced by fp_write_str().
bn_size_bin()
int bn_size_bin (const bn_t a)
Returns the number of bytes necessary to store a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
the number of bytes.
Definition at line 383 of file relic_bn_util.c.
References bn_st::dp, RLC_DIG, and bn_st::used.
Referenced by bn_write_bin(), cp_bdpe_dec(), cp_bdpe_enc(), cp_ecdh_key(), cp_ecies_dec(), cp_ecies_enc(), cp_ecmqv_key(), cp_phpe_dec(), cp_phpe_enc(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), and cp_rsa_ver().
bn_read_bin()
void bn_read_bin (bn_t a, const uint8_t * bin, int len)
Reads a positive multiple precision integer from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Definition at line 397 of file relic_bn_util.c.
References bn_grow(), bn_trim(), bn_zero(), bn_st::dp, RLC_DIG, RLC_POS, bn_st::sign, and bn_st::used.
Referenced by cp_bbs_sig(), cp_bbs_ver(), cp_bdpe_dec(), cp_clb_sig(), cp_clb_ver(), cp_cli_sig(), cp_cli_ver(), cp_cls_sig(), cp_cls_ver(), cp_cmlhs_sig(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_sig(), cp_ecss_ver(), cp_phpe_dec(), cp_phpe_enc(), cp_psb_sig(), cp_psb_ver(), cp_pss_sig(), cp_pss_ver(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), cp_rsa_ver(), cp_vbnn_gen_prv(), cp_vbnn_sig(), cp_vbnn_ver(), cp_zss_sig(), cp_zss_ver(), eb_map(), ed_map(), ep2_map(), ep_map(), fb_read_bin(), and fp_read_bin().
bn_write_bin()
void bn_write_bin (uint8_t * bin, int len, const bn_t a)
Writes a positive multiple precision integer to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the multiple integer to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 427 of file relic_bn_util.c.
References bn_size_bin(), bn_st::dp, ERR_NO_BUFFER, RLC_DIG, THROW, and bn_st::used.
Referenced by cp_bdpe_enc(), cp_ecdh_key(), cp_ecies_dec(), cp_ecies_enc(), cp_ecmqv_key(), cp_ecss_sig(), cp_ecss_ver(), cp_phpe_dec(), cp_phpe_enc(), cp_rabin_dec(), cp_rabin_enc(), cp_rsa_dec_basic(), cp_rsa_dec_quick(), cp_rsa_enc(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), cp_rsa_ver(), fb_write_bin(), and fp_write_bin().
bn_size_raw()
int bn_size_raw (const bn_t a)
Returns the number of digits necessary to store a multiple precision integer.
Parameters
[in] a - the multiple precision integer.
Returns
the number of digits.
Definition at line 457 of file relic_bn_util.c.
References bn_st::used.
bn_read_raw()
void bn_read_raw (bn_t a, const dig_t * raw, int len)
Reads a positive multiple precision integer from a digit vector.
Parameters
[out] a - the result.
[in] raw - the digit vector.
[in] len - the size of the string.
Definition at line 461 of file relic_bn_util.c.
References bn_grow(), bn_trim(), CATCH_ANY, bn_st::dp, dv_copy(), ERR_CAUGHT, RLC_POS, bn_st::sign, THROW, TRY, and bn_st::used.
Referenced by fb_size_str(), fb_write_bin(), fp_inv_monty(), and fp_print().
bn_write_raw()
void bn_write_raw (dig_t * raw, int len, const bn_t a)
Writes a positive multiple precision integer to a byte vector.
Parameters
[out] raw - the digit vector.
[in] len - the buffer capacity.
[in] a - the multiple integer to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 473 of file relic_bn_util.c.
References bn_st::dp, ERR_NO_BUFFER, THROW, and bn_st::used.