RELIC: src/epx/relic_ep3_norm.c File Reference
relic_ep3_norm.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep3_norm_imp (ep3_t r, const ep3_t p, int inv)
void ep3_norm (ep3_t r, const ep3_t p)
void ep3_norm_sim (ep3_t *r, const ep3_t *t, int n)
Detailed Description
Implementation of point normalization on prime elliptic curves over a cubic extension field.
Definition in file relic_ep3_norm.c.
Function Documentation
ep3_norm_imp()
static void ep3_norm_imp (ep3_t r, const ep3_t p, int inv) static
Normalizes a point represented in projective coordinates.
Parameters
r - the result.
p - the point to normalize.
inv - the flag to indicate if z is already inverted.
Definition at line 48 of file relic_ep3_norm.c.
References BASIC, ep3_copy(), ERR_CAUGHT, fp3_copy(), fp3_free, fp3_inv(), fp3_mul, fp3_new, fp3_null, fp3_set_dig(), fp3_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_norm(), and ep3_norm_sim().
ep3_norm()
void ep3_norm (ep3_t r, const ep3_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 97 of file relic_ep3_norm.c.
References BASIC, ep3_copy(), ep3_is_infty(), ep3_norm_imp(), and ep3_set_infty().
Referenced by ep3_curve_set(), ep3_mul_basic(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_dig(), ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_plain(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_naf_imp(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_basic(), ep3_mul_sim_dig(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), ep3_mul_sim_trick(), ep3_mul_slide(), ep3_on_curve(), ep3_size_bin(), ep3_tab(), ep3_write_bin(), pp_map_oatep_k18(), pp_map_sim_oatep_k18(), pp_map_sim_tatep_k18(), pp_map_sim_weilp_k18(), pp_map_tatep_k18(), and pp_map_weilp_k18().
ep3_norm_sim()
void ep3_norm_sim (ep3_t * r, const ep3_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 113 of file relic_ep3_norm.c.
References ep3_is_infty(), ep3_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, fp3_copy(), fp3_free, fp3_inv_sim(), fp3_new, fp3_null, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_gls_imp(), ep3_mul_reg_gls(), ep3_mul_sim_joint(), ep3_mul_sim_trick(), ep3_mul_slide(), and ep3_tab().