RELIC: src/dv/relic_dv_util.c File Reference
relic_dv_util.c File Reference
Digit vector handling
#include <inttypes.h>
#include "relic_core.h"
Functions
void dv_print (dig_t *a, int digits)
void dv_zero (dig_t *a, int digits)
void dv_copy (dig_t *c, const dig_t *a, int digits)
void dv_copy_cond (dig_t *c, const dig_t *a, int digits, dig_t cond)
void dv_swap_cond (dig_t *c, dig_t *a, int digits, dig_t cond)
int dv_cmp (const dig_t *a, const dig_t *b, int size)
int dv_cmp_const (const dig_t *a, const dig_t *b, int size)
Detailed Description
Implementation of the basic functions to temporary double precision digit vectors.
Definition in file relic_dv_util.c.
Function Documentation
dv_print()
void dv_print (dig_t * a, int digits)
Calls a function to allocate a temporary double-precision digit vector.
Parameters
[out] A - the double-precision result. Calls a function to clean and free a temporary double-precision digit vector.
[out] A - the temporary digit vector to clean and free. Prints a temporary digit vector.
[in] a - the temporary digit vector to print.
[in] digits - the number of digits to print.
Definition at line 41 of file relic_dv_util.c.
References util_print(), and util_print_dig().
dv_zero()
void dv_zero (dig_t * a, int digits)
Assigns zero to a temporary double-precision digit vector.
Parameters
[out] a - the temporary digit vector to assign.
[in] digits - the number of words to initialize with zero.
Definition at line 54 of file relic_dv_util.c.
References ERR_NO_PRECI, RLC_DV_DIGS, and THROW.
Referenced by bn_zero(), eb_mul_lodah(), fb_inv_almos(), fb_inv_binar(), fb_inv_exgcd(), fb_mul_basic(), fb_mul_karat(), fb_zero(), fp_inv_divst(), fp_inv_monty(), fp_mul_basic(), fp_mul_karat(), fp_mul_karat_imp(), fp_prime_back(), fp_prime_conv_dig(), fp_prime_set(), fp_sqr_basic(), fp_sqr_karat(), fp_sqr_karat_imp(), and fp_zero().
dv_copy()
void dv_copy (dig_t * c, const dig_t * a, int digits)
Copies some digits from a digit vector to another digit vector.
Parameters
[out] c - the destination.
[in] a - the source.
[in] digits - the number of digits to copy.
Definition at line 68 of file relic_dv_util.c.
Referenced by bn_copy(), bn_read_raw(), eb_map(), ed_map(), ep_map(), fb_copy(), fp18_sqr_unr(), fp24_mul_unr(), fp24_sqr_unr(), fp2_field_init(), fp3_field_init(), fp3_srt(), fp8_mul_dxs(), fp8_mul_unr(), fp8_sqr_unr(), fp_copy(), fp_inv_basic(), fp_inv_binar(), fp_inv_divst(), fp_inv_exgcd(), fp_inv_monty(), fp_prime_back(), fp_prime_conv(), fp_prime_conv_dig(), fp_prime_set(), fp_rdc_basic(), fp_srt(), g2_is_valid(), gt_is_valid(), and pp_exp_k2().
dv_copy_cond()
void dv_copy_cond (dig_t * c, const dig_t * a, int digits, dig_t cond)
Conditionally copies some digits from a digit vector to another digit vector.
Parameters
[out] c - the destination. @paraim[in] a - the source.
[in] digits - the number of digits to copy.
[in] cond - the condition to evaluate.
Definition at line 72 of file relic_dv_util.c.
Referenced by ed_mul_reg_imp(), ep_mul_reg_glv(), ep_mul_reg_imp(), and fp_inv_divst().
dv_swap_cond()
void dv_swap_cond (dig_t * c, dig_t * a, int digits, dig_t cond)
Conditionally swap two digit vectors.
Parameters
[in,out] c - the destination. @paraim[in,out] a - the source.
[in] digits - the number of digits to copy.
[in] cond - the condition to evaluate.
Definition at line 82 of file relic_dv_util.c.
Referenced by bn_mxp_monty(), eb_mul_lodah(), ed_mul_monty(), ep2_mul_monty(), ep_mul_monty(), fb_exp_monty(), fp_exp_monty(), and fp_inv_divst().
dv_cmp()
int dv_cmp (const dig_t * a, const dig_t * b, int size)
Returns the result of a comparison between two digit vectors.
Parameters
[in] a - the first digit vector.
[in] b - the second digit vector.
[in] size - the length in digits of the vectors.
Returns
RLC_LT if a < b, RLC_EQ if a == b and RLC_GT if a > b.
Definition at line 93 of file relic_dv_util.c.
References RLC_EQ, RLC_GT, and RLC_LT.
Referenced by bn_cmp_abs(), fp_add_basic(), fp_add_dig(), fp_dbl_basic(), fp_inv_monty(), and fp_rand().
dv_cmp_const()
int dv_cmp_const (const dig_t * a, const dig_t * b, int size)
Compares two digit vectors in constant time.
Parameters
[in] a - the first digit vector.
[in] b - the second digit vector.
[in] size - the length in digits of the vectors.
Returns
RLC_EQ if they are equal and RLC_NE otherwise.
Definition at line 108 of file relic_dv_util.c.
References RLC_EQ, and RLC_NE.
Referenced by cp_ecdsa_ver(), cp_ecss_ver(), fb_cmp(), and fp_cmp().