RELIC: src/epx/relic_ep2_mul_cof.c File Reference
relic_ep2_mul_cof.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_md.h"
Functions
static void ep2_mul_cof_bn (ep2_t r, const ep2_t p)
static void ep2_mul_cof_b12 (ep2_t r, const ep2_t p)
void ep2_mul_cof (ep2_t r, const ep2_t p)
Detailed Description
Implementation of point multiplication of a prime elliptic curve over a quadratic extension field by the curve cofactor.
Definition in file relic_ep2_mul_cof.c.
Function Documentation
ep2_mul_cof_bn()
static void ep2_mul_cof_bn (ep2_t r, const ep2_t p) static
Multiplies a point by the cofactor in a Barreto-Naehrig curve.
Parameters
[out] r - the result.
[in] p - the point to multiply.
Definition at line 46 of file relic_ep2_mul_cof.c.
References bn_free, bn_new, bn_null, ep2_add, ep2_dbl, ep2_frb(), ep2_free, ep2_mul_basic(), ep2_new, ep2_norm(), ep2_null, ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_cof().
ep2_mul_cof_b12()
static void ep2_mul_cof_b12 (ep2_t r, const ep2_t p) static
Multiplies a point by the cofactor in a Barreto-Lynn-Scott curve.
Parameters
[out] r - the result.
[in] p - the point to multiply.
Definition at line 99 of file relic_ep2_mul_cof.c.
References bn_free, bn_new, bn_null, ep2_add, ep2_dbl, ep2_frb(), ep2_free, ep2_mul_basic(), ep2_new, ep2_norm(), ep2_null, ep2_sub(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_mul_cof().
ep2_mul_cof()
void ep2_mul_cof (ep2_t r, const ep2_t p)
Multiplies a point in an elliptic curve over a quadratic extension field by the curve cofactor or a small multiple for which a short vector exists. In short, it takes a point in the curve to the large prime-order subgroup.
Parameters
[out] R - the result.
[in] P - the point to multiply.
Definition at line 152 of file relic_ep2_mul_cof.c.
References bn_free, bn_null, ep2_curve_get_cof(), ep2_mul_big, ep2_mul_cof_b12(), ep2_mul_cof_bn(), EP_B12, EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep2_map_basic(), ep2_map_from_field(), and ep2_map_swift().