RELIC: src/pp/relic_pp_exp.c File Reference
relic_pp_exp.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_exp_bn (fp12_t c, fp12_t a)
static void pp_exp_b12 (fp12_t c, fp12_t a)
void pp_exp_k2 (fp2_t c, fp2_t a)
void pp_exp_k12 (fp12_t c, fp12_t a)
Detailed Description
Implementation of the final exponentiation for pairings over prime curves.
Version
Id
relic_pp_exp.c 1665 2013-12-28 03:06:13Z dfaranha
Definition in file relic_pp_exp.c.
Function Documentation
static void pp_exp_bn (fp12_t c, fp12_t a) static
Computes the final exponentiation of a pairing defined over a Barreto-Naehrig curve.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 47 of file relic_pp_exp.c.
References bn_free, BN_NEG, bn_new, bn_null, bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_conv_cyc(), fp12_exp_cyc_sps(), fp12_frb(), fp12_free, fp12_inv_uni(), fp12_mul, fp12_new, fp12_null, fp12_sqr_cyc, fp_param_get_sps(), fp_param_get_var(), MAX_TERMS, THROW, and TRY.
Referenced by pp_exp_k12().
static void pp_exp_b12 (fp12_t c, fp12_t a) static
Computes the final exponentiation of a pairing defined over a Barreto-Lynn-Scott curve.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 133 of file relic_pp_exp.c.
References bn_free, BN_NEG, bn_new, bn_null, bn_sign(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp12_conv_cyc(), fp12_exp_cyc_sps(), fp12_frb(), fp12_free, fp12_inv_uni(), fp12_mul, fp12_new, fp12_null, fp12_sqr_cyc, fp_param_get_sps(), fp_param_get_var(), MAX_TERMS, THROW, and TRY.
Referenced by pp_exp_k12().
void pp_exp_k2 (fp2_t c, fp2_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 2. Computes c = a^(p^2 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 237 of file relic_pp_exp.c.
References bn_add_dig(), bn_div(), bn_free, bn_new, bn_null, BN_POS, CATCH_ANY, dv_copy(), ep_curve_get_ord(), ERR_CAUGHT, FINALLY, fp2_conv_uni(), fp2_exp_uni(), FP_DIGS, fp_prime_get(), THROW, and TRY.
Referenced by gt_rand(), and pp_map_tatep_k2().
void pp_exp_k12 (fp12_t c, fp12_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 12. Computes c = a^(p^12 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 264 of file relic_pp_exp.c.
References B12_P638, BN_P158, BN_P254, BN_P256, BN_P638, ep_param_get(), pp_exp_b12(), and pp_exp_bn().
Referenced by gt_rand(), pp_map_oatep_k12(), and pp_map_tatep_k12().