RELIC: src/cp/relic_cp_pcdel.c File Reference
relic_cp_pcdel.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_pdpub_gen (bn_t c, bn_t r, g1_t u1, g2_t u2, g2_t v2, gt_t e)
int cp_pdpub_ask (g1_t v1, g2_t w2, const g1_t p, const g2_t q, const bn_t c, const bn_t r, const g1_t u1, const g2_t u2, const g2_t v2)
int cp_pdpub_ans (gt_t g[3], const g1_t p, const g2_t q, const g1_t v1, const g2_t v2, const g2_t w2)
int cp_pdpub_ver (gt_t r, const gt_t g[3], const bn_t c, const gt_t e)
int cp_pdprv_gen (bn_t c, bn_t r[3], g1_t u1[2], g2_t u2[2], g2_t v2[4], gt_t e[2])
int cp_pdprv_ask (g1_t v1[3], g2_t w2[4], const g1_t p, const g2_t q, const bn_t c, const bn_t r[3], const g1_t u1[2], const g2_t u2[2], const g2_t v2[4])
int cp_pdprv_ans (gt_t g[4], const g1_t v1[3], const g2_t w2[4])
int cp_pdprv_ver (gt_t r, const gt_t g[4], const bn_t c, const gt_t e[2])
int cp_lvpub_gen (bn_t r, g1_t u1, g2_t u2, g2_t v2, gt_t e)
int cp_lvpub_ask (bn_t c, g1_t v1, g2_t w2, const g1_t p, const g2_t q, const bn_t r, const g1_t u1, const g2_t u2, const g2_t v2)
int cp_lvpub_ans (gt_t g[2], const g1_t p, const g2_t q, const g1_t v1, const g2_t v2, const g2_t w2)
int cp_lvpub_ver (gt_t r, const gt_t g[2], const bn_t c, const gt_t e)
int cp_lvprv_gen (bn_t c, bn_t r[3], g1_t u1[2], g2_t u2[2], g2_t v2[4], gt_t e[2])
int cp_lvprv_ask (g1_t v1[3], g2_t w2[4], const g1_t p, const g2_t q, const bn_t c, const bn_t r[3], const g1_t u1[2], const g2_t u2[2], const g2_t v2[4])
int cp_lvprv_ans (gt_t g[4], const g1_t v1[3], const g2_t w2[4])
int cp_lvprv_ver (gt_t r, const gt_t g[4], const bn_t c, const gt_t e[2])
Detailed Description
Implementation of pairing delegation protocols.
Definition in file relic_cp_pcdel.c.
Function Documentation
cp_pdpub_gen()
int cp_pdpub_gen (bn_t c, bn_t r, g1_t u1, g2_t u2, g2_t v2, gt_t e)
Generate parameters for the DCKKS pairing delegation protocol described at "Secure and Efficient Delegationof Pairings with Online Inputs" (CARDIS 2020)
Parameters
[out] c - the challenge.
[out] r - the randomness.
[out] u1 - the U1 precomputed value in G_1.
[out] u2 - the U2 precomputed value in G_2.
[out] v2 - the image of the randomness in G_2.
[out] e - the precomputed values e(U1, U2).
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_pcdel.c.
References bn_free, bn_mod_inv(), bn_new, bn_null, bn_rand(), bn_rand_mod(), g1_rand, g2_mul(), g2_rand, pc_get_ord, pc_map, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_POS, and RLC_TRY.
cp_pdpub_ask()
int cp_pdpub_ask (g1_t v1, g2_t w2, const g1_t p, const g2_t q, const bn_t c, const bn_t r, const g1_t u1, const g2_t u2, const g2_t v2)
Execute the client-side request for the DCKKS pairing delegation protocol.
Parameters
[out] v1 - the blinded element in G_1.
[out] w2 - the blinded element in G_2.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] c - the challenge.
[in] r - the randomness.
[in] u1 - the U1 precomputed value in G_1.
[in] u2 - the U2 precomputed value in G_2.
[in] v2 - the image of the randomness in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 67 of file relic_cp_pcdel.c.
References g1_mul(), g1_sub, g2_add, g2_mul(), and RLC_OK.
cp_pdpub_ans()
int cp_pdpub_ans (gt_t g[3], const g1_t p, const g2_t q, const g1_t v1, const g2_t v2, const g2_t w2)
Execute the server-side response for the DCKKS pairing delegation protocol.
Parameters
[out] g - the group elements computed by the server.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] v1 - the blinded element in G_1.
[in] v2 - the image of the randomness in G_2.
[in] w2 - the blinded element in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 81 of file relic_cp_pcdel.c.
References pc_map, and RLC_OK.
cp_pdpub_ver()
int cp_pdpub_ver (gt_t r, const gt_t g[3], const bn_t c, const gt_t e)
Verifies the result of the DCKKS pairing delegation protocol.
Parameters
[out] r - the result of the computation.
[in] g - the group elements returned by the server.
[in] c - the challenge.
[in] e - the precomputed values e(U1, U2).
Returns
a boolean value indicating if the computation is correct.
Definition at line 90 of file relic_cp_pcdel.c.
References gt_cmp, gt_copy, gt_exp(), gt_free, gt_is_valid(), gt_mul, gt_new, gt_null, gt_set_unity, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, and RLC_TRY.
cp_pdprv_gen()
int cp_pdprv_gen (bn_t c, bn_t r[3], g1_t u1[2], g2_t u2[2], g2_t v2[4], gt_t e[2])
Generate parameters for the DCKKS pairing delegation protocol described at "Secure and Efficient Delegationof Pairings with Online Inputs" (CARDIS 2020)
Parameters
[out] c - the challenge.
[out] r - the randomness.
[out] u1 - the U1 precomputed value in G_1.
[out] u2 - the U2 precomputed value in G_2.
[out] v2 - the image of the randomness in G_2.
[out] e - the precomputed values e(U1, U2).
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 120 of file relic_cp_pcdel.c.
References bn_free, bn_mod_inv(), bn_new, bn_null, bn_rand(), bn_rand_mod(), g1_rand, g2_mul(), g2_neg, g2_rand, pc_get_ord, pc_map, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_POS, and RLC_TRY.
cp_pdprv_ask()
int cp_pdprv_ask (g1_t v1[3], g2_t w2[4], const g1_t p, const g2_t q, const bn_t c, const bn_t r[3], const g1_t u1[2], const g2_t u2[2], const g2_t v2[4])
Execute the client-side request for the DCKKS pairing delegation protocol.
Parameters
[out] v1 - the blinded element in G_1.
[out] w2 - the blinded element in G_2.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] c - the challenge.
[in] r - the randomness.
[in] u1 - the U1 precomputed value in G_1.
[in] u2 - the U2 precomputed value in G_2.
[in] v2 - the image of the randomness in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 157 of file relic_cp_pcdel.c.
References bn_free, bn_mod_inv(), bn_new, bn_null, ERR_CAUGHT, g1_mul(), g1_sub, g2_add, g2_copy, g2_mul(), pc_get_ord, RLC_CATCH_ANY, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.
cp_pdprv_ans()
int cp_pdprv_ans (gt_t g[4], const g1_t v1[3], const g2_t w2[4])
Execute the server-side response for the DCKKS pairing delegation protocol.
Parameters
[out] g - the group elements computed by the server.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] v1 - the blinded element in G_1.
[in] v2 - the image of the randomness in G_2.
[in] w2 - the blinded element in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 191 of file relic_cp_pcdel.c.
References pc_map, and RLC_OK.
cp_pdprv_ver()
int cp_pdprv_ver (gt_t r, const gt_t g[4], const bn_t c, const gt_t e[2])
Verifies the result of the DCKKS pairing delegation protocol.
Parameters
[out] r - the result of the computation.
[in] g - the group elements returned by the server.
[in] c - the challenge.
[in] e - the precomputed values e(U1, U2).
Returns
a boolean value indicating if the computation is correct.
Definition at line 200 of file relic_cp_pcdel.c.
References gt_cmp, gt_exp(), gt_free, gt_is_valid(), gt_mul, gt_new, gt_null, gt_set_unity, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, and RLC_TRY.
cp_lvpub_gen()
int cp_lvpub_gen (bn_t r, g1_t u1, g2_t u2, g2_t v2, gt_t e)
Generate parameters for the LOVE pairing delegation protocol with public inputs.
Parameters
[out] r - the randomness.
[out] u1 - the U1 precomputed value in G_1.
[out] u2 - the U2 precomputed value in G_2.
[out] v2 - the image of the randomness in G_2.
[out] e - the precomputed values e(U1, U2).
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 231 of file relic_cp_pcdel.c.
References bn_free, bn_mod_inv(), bn_new, bn_null, bn_rand_mod(), g1_rand, g2_mul(), g2_rand, pc_get_ord, pc_map, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_lvpub_ask()
int cp_lvpub_ask (bn_t c, g1_t v1, g2_t w2, const g1_t p, const g2_t q, const bn_t r, const g1_t u1, const g2_t u2, const g2_t v2)
Execute the client-side request for the LOVE pairing delegation protocol.
Parameters
[out] c - the challenge.
[out] v1 - the blinded element in G_1.
[out] w2 - the blinded element in G_2.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] c - the challenge.
[in] r - the randomness.
[in] u1 - the U1 precomputed value in G_1.
[in] u2 - the U2 precomputed value in G_2.
[in] v2 - the image of the randomness in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 259 of file relic_cp_pcdel.c.
References bn_rand(), g1_mul(), g1_sub, g2_add, g2_mul(), RLC_OK, and RLC_POS.
cp_lvpub_ans()
int cp_lvpub_ans (gt_t g[2], const g1_t p, const g2_t q, const g1_t v1, const g2_t v2, const g2_t w2)
Execute the server-side response for the LOVE pairing delegation protocol.
Parameters
[out] g - the group elements computed by the server.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] v1 - the blinded element in G_1.
[in] v2 - the image of the randomness in G_2.
[in] w2 - the blinded element in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 275 of file relic_cp_pcdel.c.
References ERR_CAUGHT, g1_copy, g1_free, g1_new, g1_null, g2_copy, g2_free, g2_neg, g2_new, g2_null, pc_map, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.
cp_lvpub_ver()
int cp_lvpub_ver (gt_t r, const gt_t g[2], const bn_t c, const gt_t e)
Verifies the result of the LOVE pairing delegation protocol.
Parameters
[out] r - the result of the computation.
[in] g - the group elements returned by the server.
[in] c - the challenge.
[in] e - the precomputed values e(U1, U2).
Returns
a boolean value indicating if the computation is correct.
Definition at line 310 of file relic_cp_pcdel.c.
References gt_cmp, gt_copy, gt_exp(), gt_free, gt_inv, gt_is_valid(), gt_mul, gt_new, gt_null, gt_set_unity, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, and RLC_TRY.
cp_lvprv_gen()
int cp_lvprv_gen (bn_t c, bn_t r[3], g1_t u1[2], g2_t u2[2], g2_t v2[4], gt_t e[2])
Generate parameters for the LOVE pairing delegation protocol with private inputs.
Parameters
[out] c - the challenge.
[out] r - the randomness.
[out] u1 - the U1 precomputed value in G_1.
[out] u2 - the U2 precomputed value in G_2.
[out] v2 - the image of the randomness in G_2.
[out] e - the precomputed values e(U1, U2).
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 339 of file relic_cp_pcdel.c.
References bn_free, bn_mod_inv(), bn_new, bn_null, bn_rand(), bn_rand_mod(), g1_rand, g2_mul(), g2_neg, g2_rand, pc_get_ord, pc_map, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, RLC_POS, and RLC_TRY.
cp_lvprv_ask()
int cp_lvprv_ask (g1_t v1[3], g2_t w2[4], const g1_t p, const g2_t q, const bn_t c, const bn_t r[3], const g1_t u1[2], const g2_t u2[2], const g2_t v2[4])
Execute the client-side request for the LOVE pairing delegation protocol.
Parameters
[out] v1 - the blinded element in G_1.
[out] w2 - the blinded element in G_2.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] c - the challenge.
[in] r - the randomness.
[in] u1 - the U1 precomputed value in G_1.
[in] u2 - the U2 precomputed value in G_2.
[in] v2 - the image of the randomness in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 376 of file relic_cp_pcdel.c.
References bn_free, bn_mod_inv(), bn_new, bn_null, ERR_CAUGHT, g1_mul(), g1_sub, g2_add, g2_copy, g2_mul(), pc_get_ord, RLC_CATCH_ANY, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.
cp_lvprv_ans()
int cp_lvprv_ans (gt_t g[4], const g1_t v1[3], const g2_t w2[4])
Execute the server-side response for the LOVE pairing delegation protocol.
Parameters
[out] g - the group elements computed by the server.
[in] p - the first argument of the pairing.
[in] q - the second argument of the pairing.
[in] v1 - the blinded element in G_1.
[in] v2 - the image of the randomness in G_2.
[in] w2 - the blinded element in G_2.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 410 of file relic_cp_pcdel.c.
References ERR_CAUGHT, g1_copy, g1_free, g1_new, g1_null, g2_copy, g2_free, g2_new, g2_null, pc_map, pc_map_sim, RLC_CATCH_ANY, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.
cp_lvprv_ver()
int cp_lvprv_ver (gt_t r, const gt_t g[4], const bn_t c, const gt_t e[2])
Verifies the result of the LOVE pairing delegation protocol.
Parameters
[out] r - the result of the computation.
[in] g - the group elements returned by the server.
[in] c - the challenge.
[in] e - the precomputed values e(U1, U2).
Returns
a boolean value indicating if the computation is correct.
Definition at line 444 of file relic_cp_pcdel.c.
References gt_cmp, gt_exp(), gt_free, gt_is_valid(), gt_mul, gt_new, gt_null, gt_set_unity, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, and RLC_TRY.