RELIC: src/cp/relic_cp_mpss.c File Reference
relic_cp_mpss.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_mpss_gen (bn_t r[2], bn_t s[2], g2_t h, g2_t x[2], g2_t y[2])
int cp_mpss_bct (g2_t x[2], g2_t y[2])
int cp_mpss_sig (g1_t a, g1_t b[2], const bn_t m[2], const bn_t r[2], const bn_t s[2], const mt_t mul_tri[2], const mt_t sm_tri[2])
int cp_mpss_ver (gt_t e, const g1_t a, const g1_t b[2], const bn_t m[2], const g2_t h, const g2_t x, const g2_t y, const mt_t sm_tri[2], const pt_t pc_tri[2])
int cp_mpsb_gen (bn_t r[2], bn_t s[][2], g2_t h, g2_t x[2], g2_t y[][2], size_t l)
int cp_mpsb_bct (g2_t x[2], g2_t y[][2], size_t l)
int cp_mpsb_sig (g1_t a, g1_t b[2], const bn_t m[][2], const bn_t r[2], const bn_t s[][2], const mt_t mul_tri[2], const mt_t sm_tri[2], size_t l)
int cp_mpsb_ver (gt_t e, const g1_t a, const g1_t b[2], const bn_t m[][2], const g2_t h, const g2_t x, const g2_t y[][2], const bn_t v[][2], const mt_t sm_tri[2], const pt_t pc_tri[2], size_t l)
Detailed Description
Implementation of the multi-party Pointcheval-Sanders signature protocols.
Definition in file relic_cp_mpss.c.
Function Documentation
cp_mpss_gen()
int cp_mpss_gen (bn_t r[2], bn_t s[2], g2_t g, g2_t x[2], g2_t y[2])
Generates a key pair for the multi-part version of the Pointcheval-Sanders simple signature (MPSS) protocol.
Parameters
[out] r - the first part of the private key.
[out] s - the second part of the private key.
[out] g - the first part of the public key.
[out] x - the second part of the public key.
[out] y - the third part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_mpss.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_get_ord, g2_mul(), g2_rand, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_mpss_bct()
int cp_mpss_bct (g2_t x[2], g2_t y[2])
Opens public values in the MPSS protocols, in this case public keys.
Parameters
[in,out] x - the shares of the second part of the public key.
[in,out] y - the shares of the third part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 68 of file relic_cp_mpss.c.
References g2_add, g2_copy, g2_norm, and RLC_OK.
cp_mpss_sig()
int cp_mpss_sig (g1_t a, g1_t b[2], const bn_t m[2], const bn_t r[2], const bn_t s[2], const mt_t mul_tri[2], const mt_t sm_tri[2])
Signs a message using the MPSS protocol operating over shares using triples.
Parameters
[out] a - the first part of the signature.
[out] b - the second part of the signature.
[in] m - the message to sign.
[in] r - the first part of the private key.
[in] s - the second part of the private key.
[in] mul_tri - the triple for the multiplication.
[in] sm_tri - the triple for the scalar multiplication.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 79 of file relic_cp_mpss.c.
References bn_add(), bn_free, bn_mod, bn_new, bn_null, g1_add, g1_get_ord, g1_mul(), g1_norm, g1_rand, mpc_mt_bct(), mpc_mt_lcl(), mpc_mt_mul(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_mpss_ver()
int cp_mpss_ver (gt_t e, const g1_t a, const g1_t b[2], const bn_t m[2], const g2_t h, const g2_t x, const g2_t y, const mt_t sm_tri[2], const pt_t pc_tri[2])
Verifies a signature using the MPSS protocol operating over shares using triples.
Parameters
[out] e - the result of the verification.
[in] a - the first part of the signature.
[in] b - the second part of the signature.
[in] m - the message to sign.
[in] g - the first part of the public key.
[in] x - the second part of the public key.
[in] y - the third part of the public key.
[in] sm_tri - the triple for the scalar multiplication.
[in] pc_tri - the triple for the pairing computation.
Returns
a boolean value indicating the verification result.
Definition at line 124 of file relic_cp_mpss.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g1_copy, g1_free, g1_get_ord, g1_is_infty, g1_neg, g1_new, g1_null, g2_add, g2_copy, g2_free, g2_mul(), g2_new, g2_norm, g2_null, gt_exp_bct(), gt_exp_lcl(), gt_exp_mpc(), gt_free, gt_mul, gt_new, gt_null, gt_rand(), pc_map_sim, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, and RLC_TRY.
cp_mpsb_gen()
int cp_mpsb_gen (bn_t r[2], bn_t s[][2], g2_t h, g2_t x[2], g2_t y[][2], size_t l)
Generates a key pair for the multi-part version of the Pointcheval-Sanders simple signature (MPSS) protocol.
Parameters
[out] r - the first part of the private key.
[out] s - the second part of the private key.
[out] g - the first part of the public key.
[out] x - the second part of the public key.
[out] y - the third part of the public key.
[in] l - the number of messages to sign.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 213 of file relic_cp_mpss.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g2_get_ord, g2_mul(), g2_rand, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_mpsb_bct()
int cp_mpsb_bct (g2_t x[2], g2_t y[][2], size_t l)
Opens public values in the MPSS protocols, in this case public keys.
Parameters
[in,out] x - the shares of the second part of the public key.
[in,out] y - the shares of the third part of the public key.
[in] l - the number of messages to sign.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 246 of file relic_cp_mpss.c.
References g2_add, g2_copy, g2_norm, and RLC_OK.
cp_mpsb_sig()
int cp_mpsb_sig (g1_t a, g1_t b[2], const bn_t m[][2], const bn_t r[2], const bn_t s[][2], const mt_t mul_tri[2], const mt_t sm_tri[2], size_t l)
Signs a message using the MPSS protocol operating over shares using triples.
Parameters
[out] a - the first part of the signature.
[out] b - the second part of the signature.
[in] m - the messages to sign.
[in] r - the first part of the private key.
[in] s - the second parts of the private key.
[in] mul_tri - the triple for the multiplication.
[in] sm_tri - the triple for the scalar multiplication.
[in] l - the number of messages to sign.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 259 of file relic_cp_mpss.c.
References bn_add(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_sign(), bn_sub(), bn_zero(), g1_add, g1_get_ord, g1_mul(), g1_norm, g1_rand, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_NEG, RLC_OK, and RLC_TRY.
cp_mpsb_ver()
int cp_mpsb_ver (gt_t e, const g1_t a, const g1_t b[2], const bn_t m[][2], const g2_t h, const g2_t x, const g2_t y[][2], const bn_t v[][2], const mt_t sm_tri[2], const pt_t pc_tri[2], size_t l)
Verifies a signature using the MPSS protocol operating over shares using triples.
Parameters
[out] e - the result of the verification.
[in] a - the first part of the signature.
[in] b - the second part of the signature.
[in] m - the messages to sign.
[in] g - the first part of the public key.
[in] x - the second part of the public key.
[in] y - the third parts of the public key.
[in] sm_tri - the triple for the scalar multiplication.
[in] pc_tri - the triple for the pairing computation.
[in] v - the private keys, can be NULL.
[in] l - the number of messages to sign.
Returns
a boolean value indicating the verification result.
Definition at line 319 of file relic_cp_mpss.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_sign(), bn_sub(), bn_zero(), ERR_NO_MEMORY, g1_copy, g1_free, g1_get_ord, g1_is_infty, g1_neg, g1_new, g1_null, g2_add, g2_copy, g2_free, g2_mul(), g2_mul_sim_lot, g2_new, g2_norm, g2_null, gt_exp_bct(), gt_exp_lcl(), gt_exp_mpc(), gt_free, gt_mul, gt_new, gt_null, gt_rand(), pc_map_sim, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.