RELIC: src/ep/relic_ep_map.c File Reference
relic_ep_map.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
#include "relic_md.h"
Functions
static void ep_sw_b12 (ep_t p, const fp_t t, int u, int negate)
static void ep_sw_bn (ep_t p, const fp_t t, int u, int negate)
void ep_map (ep_t p, const uint8_t *msg, int len)
Detailed Description
Implementation of hashing to a prime elliptic curve.
Definition in file relic_ep_map.c.
Function Documentation
ep_sw_b12()
static void ep_sw_b12 (ep_t p, const fp_t t, int u, int negate) static
Optimized Shallue–van de Woestijne encoding from Section 3 of "Fast and simple constant-time hashing to the BLS12-381 elliptic curve".
Definition at line 43 of file relic_ep_map.c.
References CATCH_ANY, core_get(), ep_rhs(), ERR_CAUGHT, FINALLY, fp_add_dig(), fp_copy(), fp_is_zero(), fp_null, fp_set_dig(), fp_srt(), fp_sub_dig(), ep_st::norm, THROW, TRY, ep_st::x, ep_st::y, and ep_st::z.
Referenced by ep_map().
ep_sw_bn()
static void ep_sw_bn (ep_t p, const fp_t t, int u, int negate) static
Based on the rust implementation of pairings, zkcrypto/pairing. The algorithm is Shallue–van de Woestijne encoding from Section 3 of "Indifferentiable Hashing to Barreto–Naehrig Curves" from Fouque-Tibouchi: https://www.di.ens.fr/~fouque/pub/latincrypt12.pdf
Definition at line 129 of file relic_ep_map.c.
References CATCH_ANY, core_get(), ep_curve_get_b(), ep_curve_get_gen(), ep_rhs(), ep_set_infty(), ERR_CAUGHT, FINALLY, fp_add_dig(), fp_copy(), fp_is_zero(), fp_null, fp_set_dig(), fp_srt(), fp_sub_dig(), ep_st::norm, THROW, TRY, ep_st::x, ep_st::y, and ep_st::z.
Referenced by ep_map().
ep_map()
void ep_map (ep_t p, const uint8_t * msg, int len)
Maps a byte array to a point in a prime elliptic curve.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 203 of file relic_ep_map.c.
References bn_add_dig(), bn_bits(), bn_cmp(), bn_free(), bn_hlv(), bn_neg(), bn_null, bn_read_bin(), CATCH_ANY, bn_st::dp, dv_copy(), EP_B12, EP_BN, ep_curve_get_cof(), ep_curve_is_pairf(), ep_mul_basic(), ep_mul_dig(), ep_norm(), ep_null, ep_rhs(), ep_sw_b12(), ep_sw_bn(), ERR_CAUGHT, FINALLY, fp_add_dig(), fp_null, fp_prime_back(), fp_prime_conv(), fp_prime_get(), fp_prime_get_par(), fp_set_dig(), fp_srt(), fp_zero(), ep_st::norm, RLC_DIG, RLC_FP_BYTES, RLC_FP_DIGS, RLC_LT, RLC_MIN, RLC_POS, bn_st::sign, THROW, TRY, bn_st::used, ep_st::x, ep_st::y, and ep_st::z.