RELIC: src/fpx/relic_fpx_util.c File Reference
relic_fpx_util.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
void fp2_copy (fp2_t c, fp2_t a)
void fp2_zero (fp2_t a)
int fp2_is_zero (fp2_t a)
void fp2_rand (fp2_t a)
void fp2_print (fp2_t a)
int fp2_size_bin (fp2_t a, int pack)
void fp2_read_bin (fp2_t a, const uint8_t *bin, int len)
void fp2_write_bin (uint8_t *bin, int len, fp2_t a, int pack)
void fp2_set_dig (fp2_t a, dig_t b)
void fp3_copy (fp3_t c, fp3_t a)
void fp3_zero (fp3_t a)
int fp3_is_zero (fp3_t a)
void fp3_rand (fp3_t a)
void fp3_print (fp3_t a)
int fp3_size_bin (fp3_t a)
void fp3_read_bin (fp3_t a, const uint8_t *bin, int len)
void fp3_write_bin (uint8_t *bin, int len, fp3_t a)
void fp3_set_dig (fp3_t a, dig_t b)
void fp4_copy (fp4_t c, fp4_t a)
void fp4_zero (fp4_t a)
int fp4_is_zero (fp4_t a)
void fp4_rand (fp4_t a)
void fp4_print (fp4_t a)
int fp4_size_bin (fp4_t a)
void fp4_read_bin (fp4_t a, const uint8_t *bin, int len)
void fp4_write_bin (uint8_t *bin, int len, fp4_t a)
void fp4_set_dig (fp4_t a, dig_t b)
void fp6_copy (fp6_t c, fp6_t a)
void fp6_zero (fp6_t a)
int fp6_is_zero (fp6_t a)
void fp6_rand (fp6_t a)
void fp6_print (fp6_t a)
int fp6_size_bin (fp6_t a)
void fp6_read_bin (fp6_t a, const uint8_t *bin, int len)
void fp6_write_bin (uint8_t *bin, int len, fp6_t a)
void fp6_set_dig (fp6_t a, dig_t b)
void fp8_copy (fp8_t c, fp8_t a)
void fp8_zero (fp8_t a)
int fp8_is_zero (fp8_t a)
void fp8_rand (fp8_t a)
void fp8_print (fp8_t a)
int fp8_size_bin (fp8_t a, int pack)
void fp8_read_bin (fp8_t a, const uint8_t *bin, int len)
void fp8_write_bin (uint8_t *bin, int len, fp8_t a)
void fp8_set_dig (fp8_t a, dig_t b)
void fp9_copy (fp9_t c, fp9_t a)
void fp9_zero (fp9_t a)
int fp9_is_zero (fp9_t a)
void fp9_rand (fp9_t a)
void fp9_print (fp9_t a)
int fp9_size_bin (fp9_t a)
void fp9_read_bin (fp9_t a, const uint8_t *bin, int len)
void fp9_write_bin (uint8_t *bin, int len, fp9_t a)
void fp9_set_dig (fp9_t a, dig_t b)
void fp12_copy (fp12_t c, fp12_t a)
void fp12_zero (fp12_t a)
int fp12_is_zero (fp12_t a)
void fp12_rand (fp12_t a)
void fp12_print (fp12_t a)
int fp12_size_bin (fp12_t a, int pack)
void fp12_read_bin (fp12_t a, const uint8_t *bin, int len)
void fp12_write_bin (uint8_t *bin, int len, fp12_t a, int pack)
void fp12_set_dig (fp12_t a, dig_t b)
void fp18_copy (fp18_t c, fp18_t a)
void fp18_zero (fp18_t a)
int fp18_is_zero (fp18_t a)
void fp18_rand (fp18_t a)
void fp18_print (fp18_t a)
int fp18_size_bin (fp18_t a)
void fp18_read_bin (fp18_t a, const uint8_t *bin, int len)
void fp18_write_bin (uint8_t *bin, int len, fp18_t a)
void fp18_set_dig (fp18_t a, dig_t b)
void fp24_copy (fp24_t c, fp24_t a)
void fp24_zero (fp24_t a)
int fp24_is_zero (fp24_t a)
void fp24_rand (fp24_t a)
void fp24_print (fp24_t a)
int fp24_size_bin (fp24_t a)
void fp24_read_bin (fp24_t a, const uint8_t *bin, int len)
void fp24_write_bin (uint8_t *bin, int len, fp24_t a)
void fp24_set_dig (fp24_t a, dig_t b)
void fp48_copy (fp48_t c, fp48_t a)
void fp48_zero (fp48_t a)
int fp48_is_zero (fp48_t a)
void fp48_rand (fp48_t a)
void fp48_print (fp48_t a)
int fp48_size_bin (fp48_t a, int pack)
void fp48_read_bin (fp48_t a, const uint8_t *bin, int len)
void fp48_write_bin (uint8_t *bin, int len, fp48_t a, int pack)
void fp48_set_dig (fp48_t a, dig_t b)
void fp54_copy (fp54_t c, fp54_t a)
void fp54_zero (fp54_t a)
int fp54_is_zero (fp54_t a)
void fp54_rand (fp54_t a)
void fp54_print (fp54_t a)
int fp54_size_bin (fp54_t a, int pack)
void fp54_read_bin (fp54_t a, const uint8_t *bin, int len)
void fp54_write_bin (uint8_t *bin, int len, fp54_t a, int pack)
void fp54_set_dig (fp54_t a, dig_t b)
Detailed Description
Implementation of utilities in extensions defined over prime fields.
Definition in file relic_fpx_util.c.
Function Documentation
fp2_copy()
void fp2_copy (fp2_t c, fp2_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the quadratic extension field element to copy.
Definition at line 39 of file relic_fpx_util.c.
References fp_copy().
Referenced by ep2_add_basic_imp(), ep2_add_projc_mix(), ep2_copy(), ep2_dbl_basic_imp(), ep2_neg_basic(), ep2_neg_projc(), ep2_norm_imp(), ep2_norm_sim(), ep2_pck(), ep2_rhs(), ep2_upk(), fp12_back_cyc(), fp12_back_cyc_sim(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), fp12_sqr_unr(), fp2_exp(), fp2_exp_cyc(), fp2_exp_dig(), fp2_frb(), fp2_inv_sim(), fp2_mul_nor_basic(), fp2_pck(), fp2_upk(), fp4_copy(), fp4_inv_cyc(), fp4_mul_art(), fp6_copy(), fp6_mul_art(), fp6_mul_basic(), fp6_mul_dxs(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_dbl_k8_projc_basic(), and pp_dbl_k8_projc_lazyr().
fp2_zero()
void fp2_zero (fp2_t a)
Assigns zero to a quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to zero.
Definition at line 44 of file relic_fpx_util.c.
References fp_zero().
Referenced by ep2_curve_set_twist(), ep2_pck(), ep2_read_bin(), ep2_set_infty(), fp12_pck(), fp12_read_bin(), fp4_set_dig(), fp4_zero(), fp6_set_dig(), fp6_zero(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), and pp_mil_k2().
fp2_is_zero()
int fp2_is_zero (fp2_t a)
Tests if a quadratic extension field element is zero or not.
Parameters
[in] A - the quadratic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 49 of file relic_fpx_util.c.
References fp_is_zero().
Referenced by ep2_add_basic_imp(), ep2_add_projc_imp(), ep2_add_projc_mix(), ep2_is_infty(), fp12_upk(), fp4_cmp_dig(), fp4_is_zero(), fp6_cmp_dig(), and fp6_is_zero().
fp2_rand()
void fp2_rand (fp2_t a)
Assigns a random value to a quadratic extension field element.
Parameters
[out] A - the quadratic extension field element to assign.
Definition at line 53 of file relic_fpx_util.c.
References fp_rand().
Referenced by fp4_rand(), and fp6_rand().
fp2_print()
void fp2_print (fp2_t a)
Prints a quadratic extension field element to standard output.
Parameters
[in] A - the quadratic extension field element to print.
Definition at line 58 of file relic_fpx_util.c.
References fp_print().
Referenced by ep2_print(), fp4_print(), and fp6_print().
fp2_size_bin()
int fp2_size_bin (fp2_t a, int pack)
Returns the number of bytes necessary to store a quadratic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 63 of file relic_fpx_util.c.
References fp2_test_cyc(), and RLC_FP_BYTES.
fp2_read_bin()
void fp2_read_bin (fp2_t a, const uint8_t * bin, int len)
Reads a quadratic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 75 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_upk(), fp_read_bin(), fp_set_bit(), fp_zero(), RLC_FP_BYTES, and THROW.
Referenced by ep2_read_bin(), fp12_read_bin(), fp4_read_bin(), and fp6_read_bin().
fp2_write_bin()
void fp2_write_bin (uint8_t * bin, int len, fp2_t a, int pack)
Writes a quadratic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 91 of file relic_fpx_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, fp2_free, fp2_new, fp2_null, fp2_pck(), fp2_test_cyc(), fp_get_bit(), fp_write_bin(), RLC_FP_BYTES, THROW, and TRY.
Referenced by ep2_write_bin(), fp12_write_bin(), fp4_write_bin(), and fp6_write_bin().
fp2_set_dig()
void fp2_set_dig (fp2_t a, dig_t b)
Assigns a quadratic extension field element to a digit.
Parameters
[in] a - the quadratic extension field element.
[in] b - the digit.
Definition at line 123 of file relic_fpx_util.c.
References fp_set_dig(), and fp_zero().
Referenced by ep2_norm_imp(), fp2_exp(), fp2_exp_cyc(), fp2_exp_dig(), fp2_field_init(), fp4_set_dig(), fp6_set_dig(), pp_fin_k12_oatep(), pp_map_sim_tatep_k2(), pp_map_sim_weilp_k2(), pp_map_tatep_k2(), pp_map_weilp_k2(), and pp_norm_k8().
fp3_copy()
void fp3_copy (fp3_t c, fp3_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the cubic extension field element to copy.
Definition at line 128 of file relic_fpx_util.c.
References fp_copy().
Referenced by fp3_exp(), fp3_frb(), fp3_inv_sim(), fp3_mul_frb(), fp9_copy(), fp9_mul_art(), fp9_mul_basic(), and fp9_mul_dxs().
fp3_zero()
void fp3_zero (fp3_t a)
Assigns zero to a cubic extension field element.
Parameters
[out] A - the cubic extension field element to zero.
Definition at line 134 of file relic_fpx_util.c.
References fp_zero().
Referenced by fp3_field_init(), fp3_srt(), fp9_set_dig(), and fp9_zero().
fp3_is_zero()
int fp3_is_zero (fp3_t a)
Tests if a cubic extension field element is zero or not.
Parameters
[in] A - the cubic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 140 of file relic_fpx_util.c.
References fp_is_zero().
Referenced by fp9_cmp_dig(), and fp9_is_zero().
fp3_rand()
void fp3_rand (fp3_t a)
Assigns a random value to a cubic extension field element.
Parameters
[out] A - the cubic extension field element to assign.
Definition at line 144 of file relic_fpx_util.c.
References fp_rand().
Referenced by fp9_rand().
fp3_print()
void fp3_print (fp3_t a)
Prints a cubic extension field element to standard output.
Parameters
[in] A - the cubic extension field element to print.
Definition at line 150 of file relic_fpx_util.c.
References fp_print().
Referenced by fp9_print().
fp3_size_bin()
int fp3_size_bin (fp3_t a)
Returns the number of bytes necessary to store a cubic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 156 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp3_read_bin()
void fp3_read_bin (fp3_t a, const uint8_t * bin, int len)
Reads a cubic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 160 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp9_read_bin().
fp3_write_bin()
void fp3_write_bin (uint8_t * bin, int len, fp3_t a)
Writes a cubic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 169 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp9_write_bin().
fp3_set_dig()
void fp3_set_dig (fp3_t a, dig_t b)
Assigns a cubic extension field element to a digit.
Parameters
[in] a - the cubic extension field element.
[in] b - the digit.
Definition at line 178 of file relic_fpx_util.c.
References fp_set_dig(), and fp_zero().
Referenced by fp3_exp(), fp9_set_dig(), and pp_mil_k54().
fp4_copy()
void fp4_copy (fp4_t c, fp4_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the sextic extension field element to copy.
Definition at line 184 of file relic_fpx_util.c.
References fp2_copy().
Referenced by fp4_exp(), fp4_frb(), fp8_copy(), fp8_inv_cyc(), and fp8_mul_art().
fp4_zero()
void fp4_zero (fp4_t a)
Assigns zero to a quartic extension field element.
Parameters
[out] A - the quartic extension field element to zero.
Definition at line 189 of file relic_fpx_util.c.
References fp2_zero().
Referenced by fp8_set_dig(), and fp8_zero().
fp4_is_zero()
int fp4_is_zero (fp4_t a)
Tests if a quartic extension field element is zero or not.
Parameters
[in] A - the quartic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 194 of file relic_fpx_util.c.
References fp2_is_zero().
Referenced by fp8_cmp_dig(), and fp8_is_zero().
fp4_rand()
void fp4_rand (fp4_t a)
Assigns a random value to a quartic extension field element.
Parameters
[out] A - the quartic extension field element to assign.
Definition at line 198 of file relic_fpx_util.c.
References fp2_rand().
Referenced by fp8_rand().
fp4_print()
void fp4_print (fp4_t a)
Prints a quartic extension field element to standard output.
Parameters
[in] A - the quartic extension field element to print.
Definition at line 203 of file relic_fpx_util.c.
References fp2_print().
Referenced by fp8_print().
fp4_size_bin()
int fp4_size_bin (fp4_t a)
Returns the number of bytes necessary to store a quartic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 208 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp4_read_bin()
void fp4_read_bin (fp4_t a, const uint8_t * bin, int len)
Reads a quartic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 212 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp8_read_bin().
fp4_write_bin()
void fp4_write_bin (uint8_t * bin, int len, fp4_t a)
Writes a quartic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 220 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp8_write_bin().
fp4_set_dig()
void fp4_set_dig (fp4_t a, dig_t b)
Assigns a quartic extension field element to a digit.
Parameters
[in] a - the quartic extension field element.
[in] b - the digit.
Definition at line 228 of file relic_fpx_util.c.
References fp2_set_dig(), and fp2_zero().
Referenced by fp4_exp(), and fp8_set_dig().
fp6_copy()
void fp6_copy (fp6_t c, fp6_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the sextic extension field element to copy.
Definition at line 233 of file relic_fpx_util.c.
References fp2_copy().
Referenced by fp12_copy(), fp12_inv_cyc(), fp12_mul_art(), fp6_exp(), and fp6_frb().
fp6_zero()
void fp6_zero (fp6_t a)
Assigns zero to a sextic extension field element.
Parameters
[out] A - the sextic extension field element to zero.
Definition at line 239 of file relic_fpx_util.c.
References fp2_zero().
Referenced by fp12_set_dig(), and fp12_zero().
fp6_is_zero()
int fp6_is_zero (fp6_t a)
Tests if a sextic extension field element is zero or not.
Parameters
[in] A - the sextic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 245 of file relic_fpx_util.c.
References fp2_is_zero().
Referenced by fp12_cmp_dig(), and fp12_is_zero().
fp6_rand()
void fp6_rand (fp6_t a)
Assigns a random value to a sextic extension field element.
Parameters
[out] A - the sextic extension field element to assign.
Definition at line 249 of file relic_fpx_util.c.
References fp2_rand().
Referenced by fp12_rand().
fp6_print()
void fp6_print (fp6_t a)
Prints a sextic extension field element to standard output.
Parameters
[in] A - the sextic extension field element to print.
Definition at line 255 of file relic_fpx_util.c.
References fp2_print().
Referenced by fp12_print().
fp6_size_bin()
int fp6_size_bin (fp6_t a)
Returns the number of bytes necessary to store a quadratic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 261 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp6_read_bin()
void fp6_read_bin (fp6_t a, const uint8_t * bin, int len)
Reads a quadratic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 265 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp12_read_bin().
fp6_write_bin()
void fp6_write_bin (uint8_t * bin, int len, fp6_t a)
Writes a sextic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 274 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp2_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp12_write_bin().
fp6_set_dig()
void fp6_set_dig (fp6_t a, dig_t b)
Assigns a sextic extension field element to a digit.
Parameters
[in] a - the sextic extension field element.
[in] b - the digit.
Definition at line 283 of file relic_fpx_util.c.
References fp2_set_dig(), and fp2_zero().
Referenced by fp12_set_dig(), and fp6_exp().
fp8_copy()
void fp8_copy (fp8_t c, fp8_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the octic extension field element to copy.
Definition at line 289 of file relic_fpx_util.c.
References fp4_copy().
Referenced by ep8_add_basic(), ep8_dbl_basic(), fp24_copy(), fp24_mul_art(), fp24_mul_basic(), fp24_mul_dxs(), fp48_back_cyc(), fp48_back_cyc_sim(), fp48_mul_dxs(), fp8_exp(), fp8_exp_cyc(), fp8_frb(), fp8_inv_sim(), pp_add_k48_basic(), pp_dbl_k48_basic(), pp_exp_k8(), and pp_mil_k48().
fp8_zero()
void fp8_zero (fp8_t a)
Assigns zero to an octic extension field element.
Parameters
[out] A - the octic extension field element to zero.
Definition at line 294 of file relic_fpx_util.c.
References fp4_zero().
Referenced by ep8_add_basic(), fp24_set_dig(), fp24_zero(), fp48_pck(), fp48_read_bin(), pp_dbl_k48_projc(), and pp_mil_k8().
fp8_is_zero()
int fp8_is_zero (fp8_t a)
Tests if an octic extension field element is zero or not.
Parameters
[in] A - the octic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 299 of file relic_fpx_util.c.
References fp4_is_zero().
Referenced by ep8_add_basic(), fp24_cmp_dig(), fp24_is_zero(), fp48_upk(), and pp_map_k48().
fp8_rand()
void fp8_rand (fp8_t a)
Assigns a random value to an octic extension field element.
Parameters
[out] A - the octic extension field element to assign.
Definition at line 303 of file relic_fpx_util.c.
References fp4_rand().
Referenced by fp24_rand().
fp8_print()
void fp8_print (fp8_t a)
Prints an octic extension field element to standard output.
Parameters
[in] A - the octic extension field element to print.
Definition at line 308 of file relic_fpx_util.c.
References fp4_print().
Referenced by fp24_print().
fp8_size_bin()
int fp8_size_bin (fp8_t a, int pack)
Returns the number of bytes necessary to store an octic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 313 of file relic_fpx_util.c.
References fp8_test_cyc(), and RLC_FP_BYTES.
fp8_read_bin()
void fp8_read_bin (fp8_t a, const uint8_t * bin, int len)
Reads an octic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 325 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp4_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp24_read_bin(), and fp48_read_bin().
fp8_write_bin()
void fp8_write_bin (uint8_t * bin, int len, fp8_t a)
Writes an octic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 333 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp4_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp24_write_bin(), and fp48_write_bin().
fp8_set_dig()
void fp8_set_dig (fp8_t a, dig_t b)
Assigns an octic extension field element to a digit.
Parameters
[in] a - the octic extension field element.
[in] b - the digit.
Definition at line 341 of file relic_fpx_util.c.
References fp4_set_dig(), and fp4_zero().
Referenced by fp24_set_dig(), fp8_exp(), fp8_exp_cyc(), pp_map_oatep_k8(), and pp_mil_k48().
fp9_copy()
void fp9_copy (fp9_t c, fp9_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the nonic extension field element to copy.
Definition at line 346 of file relic_fpx_util.c.
References fp3_copy().
Referenced by ep9_add_basic(), ep9_dbl_basic(), fp18_copy(), fp18_inv_cyc(), fp18_mul_art(), fp18_mul_dxs(), fp54_back_cyc(), fp54_back_cyc_sim(), fp54_mul_dxs(), fp9_exp(), fp9_frb(), fp9_inv_sim(), pp_add_k54_basic(), pp_dbl_k54_basic(), and pp_mil_k54().
fp9_zero()
void fp9_zero (fp9_t a)
Assigns zero to a nonic extension field element.
Parameters
[out] A - the nonic extension field element to zero.
Definition at line 352 of file relic_fpx_util.c.
References fp3_zero().
Referenced by ep9_add_basic(), fp18_set_dig(), fp18_zero(), fp54_pck(), fp54_read_bin(), pp_dbl_k54_projc(), and pp_mil_k54().
fp9_is_zero()
int fp9_is_zero (fp9_t a)
Tests if a nonic extension field element is zero or not.
Parameters
[in] A - the nonic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 358 of file relic_fpx_util.c.
References fp3_is_zero().
Referenced by ep9_add_basic(), fp18_cmp_dig(), fp18_is_zero(), fp54_upk(), and pp_map_k54().
fp9_rand()
void fp9_rand (fp9_t a)
Assigns a random value to a nonic extension field element.
Parameters
[out] A - the nonic extension field element to assign.
Definition at line 362 of file relic_fpx_util.c.
References fp3_rand().
Referenced by fp18_rand().
fp9_print()
void fp9_print (fp9_t a)
Prints a nonic extension field element to standard output.
Parameters
[in] A - the nonic extension field element to print.
Definition at line 368 of file relic_fpx_util.c.
References fp3_print().
Referenced by fp18_print().
fp9_size_bin()
int fp9_size_bin (fp9_t a)
Returns the number of bytes necessary to store a quadratic extension field element.
Parameters
[out] size - the result.
[in] a - the extension field element.
Definition at line 374 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp9_read_bin()
void fp9_read_bin (fp9_t a, const uint8_t * bin, int len)
Reads a quadratic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 378 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp3_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp18_read_bin(), and fp54_read_bin().
fp9_write_bin()
void fp9_write_bin (uint8_t * bin, int len, fp9_t a)
Writes a nonic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 387 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp3_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp18_write_bin(), and fp54_write_bin().
fp9_set_dig()
void fp9_set_dig (fp9_t a, dig_t b)
Assigns a nonic extension field element to a digit.
Parameters
[in] a - the nonic extension field element.
[in] b - the digit.
Definition at line 396 of file relic_fpx_util.c.
References fp3_set_dig(), and fp3_zero().
Referenced by fp18_set_dig(), fp9_exp(), and pp_mil_k54().
fp12_copy()
void fp12_copy (fp12_t c, fp12_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the dodecic extension field element to copy.
Definition at line 402 of file relic_fpx_util.c.
References fp6_copy().
Referenced by fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sps(), fp12_exp_dig(), fp12_frb(), fp12_pck(), and fp12_upk().
fp12_zero()
void fp12_zero (fp12_t a)
Assigns zero to a dodecic extension field element.
Parameters
[out] A - the dodecic extension field element to zero.
Definition at line 407 of file relic_fpx_util.c.
References fp6_zero().
Referenced by pp_dbl_k12_basic(), pp_fin_k12_oatep(), pp_mil_k12(), and pp_mil_lit_k12().
fp12_is_zero()
int fp12_is_zero (fp12_t a)
Tests if a dodecic extension field element is zero or not.
Parameters
[in] A - the dodecic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 412 of file relic_fpx_util.c.
References fp6_is_zero().
fp12_rand()
void fp12_rand (fp12_t a)
Assigns a random value to a dodecic extension field element.
Parameters
[out] A - the dodecic extension field element to assign.
Definition at line 416 of file relic_fpx_util.c.
References fp6_rand().
fp12_print()
void fp12_print (fp12_t a)
Prints a dodecic extension field element to standard output.
Parameters
[in] A - the dodecic extension field element to print.
Definition at line 421 of file relic_fpx_util.c.
References fp6_print().
fp12_size_bin()
int fp12_size_bin (fp12_t a, int pack)
Returns the number of bytes necessary to store a dodecic extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 426 of file relic_fpx_util.c.
References fp12_test_cyc(), and RLC_FP_BYTES.
fp12_read_bin()
void fp12_read_bin (fp12_t a, const uint8_t * bin, int len)
Reads a dodecic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 438 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp12_back_cyc(), fp2_read_bin(), fp2_zero(), fp6_read_bin(), RLC_FP_BYTES, and THROW.
fp12_write_bin()
void fp12_write_bin (uint8_t * bin, int len, fp12_t a, int pack)
Writes a dodecic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 457 of file relic_fpx_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, fp12_free, fp12_new, fp12_null, fp12_pck(), fp2_write_bin(), fp6_write_bin(), RLC_FP_BYTES, THROW, and TRY.
fp12_set_dig()
void fp12_set_dig (fp12_t a, dig_t b)
Assigns a dodecic extension field element to a digit.
Parameters
[in] a - the dodecic extension field element.
[in] b - the digit.
Definition at line 488 of file relic_fpx_util.c.
References fp6_set_dig(), and fp6_zero().
Referenced by fp12_exp(), fp12_exp_cyc(), fp12_exp_cyc_sps(), fp12_exp_dig(), pp_map_oatep_k12(), pp_map_sim_oatep_k12(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), and pp_map_weilp_k12().
fp18_copy()
void fp18_copy (fp18_t c, fp18_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the octdecic extension field element to copy.
Definition at line 493 of file relic_fpx_util.c.
References fp9_copy().
Referenced by fp18_exp(), fp18_frb(), fp54_copy(), fp54_mul_art(), fp54_mul_basic(), and fp54_mul_dxs().
fp18_zero()
void fp18_zero (fp18_t a)
Assigns zero to an octdecic extension field element.
Parameters
[out] A - the octdecic extension field element to zero.
Definition at line 498 of file relic_fpx_util.c.
References fp9_zero().
Referenced by fp54_set_dig(), and fp54_zero().
fp18_is_zero()
int fp18_is_zero (fp18_t a)
Tests if an octdecic extension field element is zero or not.
Parameters
[in] A - the octdecic extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 503 of file relic_fpx_util.c.
References fp9_is_zero().
Referenced by fp54_cmp_dig(), and fp54_is_zero().
fp18_rand()
void fp18_rand (fp18_t a)
Assigns a random value to an octdecic extension field element.
Parameters
[out] A - the octdecic extension field element to assign.
Definition at line 507 of file relic_fpx_util.c.
References fp9_rand().
Referenced by fp54_rand().
fp18_print()
void fp18_print (fp18_t a)
Prints an octdecic extension field element to standard output.
Parameters
[in] A - the octdecic extension field element to print.
Definition at line 512 of file relic_fpx_util.c.
References fp9_print().
Referenced by fp54_print().
fp18_size_bin()
int fp18_size_bin (fp18_t a)
Returns the number of bytes necessary to store an octdecic extension field element.
Parameters
[in] a - the extension field element.
Returns
the number of bytes.
Definition at line 517 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp18_read_bin()
void fp18_read_bin (fp18_t a, const uint8_t * bin, int len)
Reads an octdecic extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 521 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp9_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp54_read_bin().
fp18_write_bin()
void fp18_write_bin (uint8_t * bin, int len, fp18_t a)
Writes an octdecic extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 529 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp9_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp54_write_bin().
fp18_set_dig()
void fp18_set_dig (fp18_t a, dig_t b)
Assigns an octdecic extension field element to a digit.
Parameters
[in] a - the octdecic extension field element.
[in] b - the digit.
Definition at line 537 of file relic_fpx_util.c.
References fp9_set_dig(), and fp9_zero().
Referenced by fp18_exp(), and fp54_set_dig().
fp24_copy()
void fp24_copy (fp24_t c, fp24_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the 24-degree extension field element to copy.
Definition at line 542 of file relic_fpx_util.c.
References fp8_copy().
Referenced by fp24_exp(), fp24_frb(), fp48_copy(), fp48_inv_cyc(), and fp48_mul_art().
fp24_zero()
void fp24_zero (fp24_t a)
Assigns zero to a 24-degree extension field element.
Parameters
[out] A - the 24-degree extension field element to zero.
Definition at line 548 of file relic_fpx_util.c.
References fp8_zero().
Referenced by fp48_set_dig(), and fp48_zero().
fp24_is_zero()
int fp24_is_zero (fp24_t a)
Tests if a 24-degree extension field element is zero or not.
Parameters
[in] A - the 24-degree extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 554 of file relic_fpx_util.c.
References fp8_is_zero().
Referenced by fp48_cmp_dig(), and fp48_is_zero().
fp24_rand()
void fp24_rand (fp24_t a)
Assigns a random value to a 24-degree extension field element.
Parameters
[out] A - the 24-degree extension field element to assign.
Definition at line 558 of file relic_fpx_util.c.
References fp8_rand().
Referenced by fp48_rand().
fp24_print()
void fp24_print (fp24_t a)
Prints a 24-degree extension field element to standard output.
Parameters
[in] A - the 24-degree extension field element to print.
Definition at line 564 of file relic_fpx_util.c.
References fp8_print().
Referenced by fp48_print().
fp24_size_bin()
int fp24_size_bin (fp24_t a)
Returns the number of bytes necessary to store a 24-degree extension field element.
Parameters
[in] a - the extension field element.
Returns
the number of bytes.
Definition at line 570 of file relic_fpx_util.c.
References RLC_FP_BYTES.
fp24_read_bin()
void fp24_read_bin (fp24_t a, const uint8_t * bin, int len)
Reads a 24-degree extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 574 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp8_read_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp48_read_bin().
fp24_write_bin()
void fp24_write_bin (uint8_t * bin, int len, fp24_t a)
Writes a 24-degree extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 583 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp8_write_bin(), RLC_FP_BYTES, and THROW.
Referenced by fp48_write_bin().
fp24_set_dig()
void fp24_set_dig (fp24_t a, dig_t b)
Assigns a 24-degree extension field element to a digit.
Parameters
[in] a - the 24-degree extension field element.
[in] b - the digit.
Definition at line 592 of file relic_fpx_util.c.
References fp8_set_dig(), and fp8_zero().
Referenced by fp24_exp(), and fp48_set_dig().
fp48_copy()
void fp48_copy (fp48_t c, fp48_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the 48-extension field element to copy.
Definition at line 598 of file relic_fpx_util.c.
References fp24_copy().
Referenced by fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sps(), fp48_exp_dig(), fp48_frb(), fp48_pck(), and fp48_upk().
fp48_zero()
void fp48_zero (fp48_t a)
Assigns zero to a 48-extension field element.
Parameters
[out] A - the 48-extension field element to zero.
Definition at line 603 of file relic_fpx_util.c.
References fp24_zero().
Referenced by pp_add_k48_basic(), pp_dbl_k48_basic(), and pp_mil_k48().
fp48_is_zero()
int fp48_is_zero (fp48_t a)
Tests if a 48-extension field element is zero or not.
Parameters
[in] A - the 48-extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 608 of file relic_fpx_util.c.
References fp24_is_zero().
fp48_rand()
void fp48_rand (fp48_t a)
Assigns a random value to a 48-extension field element.
Parameters
[out] A - the 48-extension field element to assign.
Definition at line 612 of file relic_fpx_util.c.
References fp24_rand().
fp48_print()
void fp48_print (fp48_t a)
Prints a 48-extension field element to standard output.
Parameters
[in] A - the 48-extension field element to print.
Definition at line 617 of file relic_fpx_util.c.
References fp24_print().
fp48_size_bin()
int fp48_size_bin (fp48_t a, int pack)
Returns the number of bytes necessary to store a 48-extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 622 of file relic_fpx_util.c.
References fp48_test_cyc(), and RLC_FP_BYTES.
fp48_read_bin()
void fp48_read_bin (fp48_t a, const uint8_t * bin, int len)
Reads a 48-extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 634 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp24_read_bin(), fp48_back_cyc(), fp8_read_bin(), fp8_zero(), RLC_FP_BYTES, and THROW.
fp48_write_bin()
void fp48_write_bin (uint8_t * bin, int len, fp48_t a, int pack)
Writes a 48-extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 653 of file relic_fpx_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, fp24_write_bin(), fp48_free, fp48_new, fp48_null, fp48_pck(), fp8_write_bin(), RLC_FP_BYTES, THROW, and TRY.
fp48_set_dig()
void fp48_set_dig (fp48_t a, dig_t b)
Assigns a 48-extension field element to a digit.
Parameters
[in] a - the 48-extension field element.
[in] b - the digit.
Definition at line 684 of file relic_fpx_util.c.
References fp24_set_dig(), and fp24_zero().
Referenced by fp48_exp(), fp48_exp_cyc(), fp48_exp_cyc_sps(), fp48_exp_dig(), and pp_map_k48().
fp54_copy()
void fp54_copy (fp54_t c, fp54_t a)
Copies the second argument to the first argument.
Parameters
[out] C - the result.
[in] A - the 54-extension field element to copy.
Definition at line 689 of file relic_fpx_util.c.
References fp18_copy().
Referenced by fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), fp54_frb(), fp54_pck(), fp54_upk(), and pp_exp_k54().
fp54_zero()
void fp54_zero (fp54_t a)
Assigns zero to a 54-extension field element.
Parameters
[out] A - the 54-extension field element to zero.
Definition at line 695 of file relic_fpx_util.c.
References fp18_zero().
Referenced by pp_add_k54_basic(), pp_dbl_k54_basic(), and pp_mil_k54().
fp54_is_zero()
int fp54_is_zero (fp54_t a)
Tests if a 54-extension field element is zero or not.
Parameters
[in] A - the 54-extension field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 701 of file relic_fpx_util.c.
References fp18_is_zero().
fp54_rand()
void fp54_rand (fp54_t a)
Assigns a random value to a 54-extension field element.
Parameters
[out] A - the 54-extension field element to assign.
Definition at line 705 of file relic_fpx_util.c.
References fp18_rand().
fp54_print()
void fp54_print (fp54_t a)
Prints a 54-extension field element to standard output.
Parameters
[in] A - the 54-extension field element to print.
Definition at line 711 of file relic_fpx_util.c.
References fp18_print().
fp54_size_bin()
int fp54_size_bin (fp54_t a, int pack)
Returns the number of bytes necessary to store a 54-extension field element.
Parameters
[in] a - the extension field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 717 of file relic_fpx_util.c.
References fp54_test_cyc(), and RLC_FP_BYTES.
fp54_read_bin()
void fp54_read_bin (fp54_t a, const uint8_t * bin, int len)
Reads a 54-extension field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 729 of file relic_fpx_util.c.
References ERR_NO_BUFFER, fp18_read_bin(), fp54_back_cyc(), fp9_read_bin(), fp9_zero(), RLC_FP_BYTES, and THROW.
fp54_write_bin()
void fp54_write_bin (uint8_t * bin, int len, fp54_t a, int pack)
Writes a 54-extension field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the extension field element to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not correct.
Definition at line 749 of file relic_fpx_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, fp18_write_bin(), fp54_free, fp54_new, fp54_null, fp54_pck(), fp9_write_bin(), RLC_FP_BYTES, THROW, and TRY.
fp54_set_dig()
void fp54_set_dig (fp54_t a, dig_t b)
Assigns a 54-extension field element to a digit.
Parameters
[in] a - the 54-extension field element.
[in] b - the digit.
Definition at line 781 of file relic_fpx_util.c.
References fp18_set_dig(), and fp18_zero().
Referenced by fp54_exp(), fp54_exp_cyc(), fp54_exp_cyc_sps(), fp54_exp_dig(), and pp_map_k54().