RELIC: src/pc/relic_pc_exp.c File Reference
relic_pc_exp.c File Reference
Pairing-based cryptography
#include "relic_pc.h"
#include "relic_core.h"
Macros
#define RLC_GT_TABLE (1 << (RLC_WIDTH - 2))
Functions
static void gt_psi (gt_t c, const gt_t a)
void gt_exp_gls_naf (gt_t c, const gt_t a, const bn_t b, size_t f)
static void gt_exp_gls_sac (gt_t c, const gt_t a, const bn_t b, size_t d, size_t f)
static void gt_exp_reg_sac (gt_t c, const gt_t a, const bn_t b, size_t d, size_t f)
void gt_exp_reg_gls (gt_t c, const gt_t a, const bn_t b, size_t f)
void g1_mul (g1_t c, const g1_t a, const bn_t b)
void g1_mul_gen (g1_t c, const bn_t b)
void g2_mul (g2_t c, const g2_t a, const bn_t b)
void g2_mul_gen (g2_t c, const bn_t b)
void gt_exp (gt_t c, const gt_t a, const bn_t b)
void gt_exp_sec (gt_t c, const gt_t a, const bn_t b)
void gt_exp_dig (gt_t c, const gt_t a, dig_t b)
void gt_exp_sim (gt_t e, const gt_t a, const bn_t b, const gt_t c, const bn_t d)
void gt_exp_gen (gt_t c, const bn_t b)
Detailed Description
Implementation of exponentiation in pairing groups.
Definition in file relic_pc_exp.c.
Macro Definition Documentation
RLC_GT_TABLE
#define RLC_GT_TABLE (1 << (RLC_WIDTH - 2))
Size of a precomputation table using the double-table comb method.
Definition at line 107 of file relic_pc_exp.c.
Referenced by gt_exp_gls_naf(), and gt_exp_reg_gls().
Function Documentation
gt_psi()
static void gt_psi (gt_t c, const gt_t a) static
Apply Frobenius endomorphism in different pairing-friendly curve families.
Parameters
[in] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 44 of file relic_pc_exp.c.
References EP_AFG16, ep_curve_is_pairf(), EP_FM18, EP_K16, EP_K18, EP_SG18, ERR_CAUGHT, gt_frb, gt_free, gt_inv, gt_mul, gt_new, gt_null, gt_sqr, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by gt_exp_gls_naf(), gt_exp_gls_sac(), gt_exp_reg_gls(), and gt_exp_reg_sac().
gt_exp_gls_naf()
void gt_exp_gls_naf (gt_t c, const gt_t a, const bn_t b, size_t f)
Exponentiates an element from G_T using the w-NAF method.
Parameters
[out] c - the result.
[in] a - the element to exponentiate.
[in] b - the exponent.
[in] f - the maximum Frobenius power.
Definition at line 117 of file relic_pc_exp.c.
References bn_abs(), bn_add(), bn_dbl(), bn_free, bn_is_zero(), bn_mod, bn_neg(), bn_new, bn_null, bn_rec_frb(), bn_rec_naf(), bn_sign(), EP_AFG16, EP_BN, ep_curve_embed(), ep_curve_is_pairf(), EP_K16, EP_SG18, ERR_CAUGHT, ERR_NO_MEMORY, fp_prime_get_par(), gt_copy, gt_free, gt_get_ord, gt_inv, gt_mul, gt_new, gt_null, gt_psi(), gt_set_unity, gt_sqr, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_GT_TABLE, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by gt_exp().
gt_exp_gls_sac()
static void gt_exp_gls_sac (gt_t c, const gt_t a, const bn_t b, size_t d, size_t f) static
Exponentiates an element from G_T using the variable-time GLS-SAC method.
Parameters
[out] c - the result.
[in] a - the element to exponentiate.
[in] b - the exponent.
[in] f - the maximum Frobenius power.
Definition at line 267 of file relic_pc_exp.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_dbl(), bn_free, bn_is_even(), bn_mod, bn_neg(), bn_new, bn_null, bn_rec_frb(), bn_rec_sac(), bn_sign(), EP_BN, ep_curve_is_pairf(), EP_SG18, ERR_CAUGHT, ERR_NO_MEMORY, fp_prime_get_par(), gt_copy, gt_free, gt_get_ord, gt_inv, gt_mul, gt_new, gt_null, gt_psi(), gt_set_unity, gt_sqr, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by gt_exp().
gt_exp_reg_sac()
static void gt_exp_reg_sac (gt_t c, const gt_t a, const bn_t b, size_t d, size_t f) static
Exponentiates an element from G_T in constant time using the GLS-SAC method.
Parameters
[out] c - the result.
[in] a - the element to exponentiate.
[in] b - the exponent.
[in] f - the maximum Frobenius power.
Definition at line 393 of file relic_pc_exp.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_dbl(), bn_free, bn_is_even(), bn_mod, bn_neg(), bn_new, bn_null, bn_rec_frb(), bn_rec_sac(), bn_sign(), EP_BN, ep_curve_is_pairf(), EP_SG18, ERR_CAUGHT, ERR_NO_MEMORY, fp_prime_get_par(), gt_copy, gt_copy_sec, gt_free, gt_get_ord, gt_inv, gt_mul, gt_new, gt_null, gt_psi(), gt_set_unity, gt_sqr, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by gt_exp_sec().
gt_exp_reg_gls()
void gt_exp_reg_gls (gt_t c, const gt_t a, const bn_t b, size_t f)
Exponentiates an element from G_T in constant time.
Parameters
[out] c - the result.
[in] a - the element to exponentiate.
[in] b - the exponent.
[in] f - the maximum Frobenius power.
Definition at line 516 of file relic_pc_exp.c.
References bn_abs(), bn_add(), bn_bits(), bn_dbl(), bn_free, bn_is_even(), bn_is_zero(), bn_mod, bn_neg(), bn_new, bn_null, bn_rec_frb(), bn_rec_reg(), bn_sign(), EP_BN, ep_curve_is_pairf(), EP_SG18, ERR_CAUGHT, ERR_NO_MEMORY, fp_prime_get_par(), gt_copy, gt_copy_sec, gt_free, gt_get_ord, gt_inv, gt_mul, gt_new, gt_null, gt_psi(), gt_set_unity, gt_sqr, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_GT_TABLE, RLC_MAX, RLC_NEG, RLC_POS, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by gt_exp_sec().
g1_mul()
void g1_mul (g1_t r, const g1_t p, const bn_t k)
Multiplies an element from G_1 by an integer. Computes R = [k]P.
Parameters
[out] r - the result.
[in] p - the element to multiply.
[in] k - the integer.
Definition at line 660 of file relic_pc_exp.c.
References bn_bits(), bn_free, bn_mod, bn_new, bn_null, bn_sign(), ERR_CAUGHT, g1_mul_dig, g1_neg, pc_get_ord, RLC_CAT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_G1_LOWER, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by cp_bgn_dec1(), cp_bgn_enc1(), cp_clb_sig(), cp_clb_ver(), cp_cli_sig(), cp_cls_sig(), cp_cls_ver(), cp_cmlhs_onv(), cp_cmlhs_sig(), cp_cmlhs_ver(), cp_lvprv_ask(), cp_lvpub_ask(), cp_mpsb_sig(), cp_mpss_sig(), cp_pbpsi_ans(), cp_pdprv_ask(), cp_pdpub_ask(), cp_psb_sig(), cp_pss_sig(), and cp_sokaka_gen_prv().
g1_mul_gen()
void g1_mul_gen (g1_t r, const bn_t k)
Multiplies the generator of G_1 by an integer.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 690 of file relic_pc_exp.c.
References bn_free, bn_mod, bn_new, bn_null, ERR_CAUGHT, pc_get_ord, RLC_CAT, RLC_CATCH_ANY, RLC_FINALLY, RLC_G1_LOWER, RLC_THROW, and RLC_TRY.
Referenced by cp_bbs_sig(), cp_bgn_dec1(), cp_bgn_enc1(), cp_bgn_gen(), cp_cmlhs_sig(), cp_ibe_enc(), cp_ibe_gen(), cp_mklhs_onv(), cp_mklhs_sig(), cp_mklhs_ver(), cp_pbpsi_ans(), cp_pbpsi_gen(), cp_zss_gen(), cp_zss_ver(), and pc_map_tri().
g2_mul()
void g2_mul (g2_t r, const g2_t p, const bn_t k)
Multiplies an element from G_2 by an integer. Computes R = [k]P.
Parameters
[out] r - the result.
[in] p - the element to multiply.
[in] k - the integer.
Definition at line 712 of file relic_pc_exp.c.
References bn_bits(), bn_free, bn_mod, bn_new, bn_null, bn_sign(), ERR_CAUGHT, g2_mul_dig, g2_neg, pc_get_ord, RLC_CAT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_G2_LOWER, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by cp_bgn_dec2(), cp_bgn_enc2(), cp_ibe_gen_prv(), cp_lvprv_ask(), cp_lvprv_gen(), cp_lvpub_ask(), cp_lvpub_gen(), cp_mpsb_gen(), cp_mpsb_ver(), cp_mpss_gen(), cp_mpss_ver(), cp_pbpsi_ask(), cp_pbpsi_gen(), cp_pdprv_ask(), cp_pdprv_gen(), cp_pdpub_ask(), cp_pdpub_gen(), cp_psb_gen(), cp_pss_gen(), cp_pss_ver(), and cp_sokaka_gen_prv().
g2_mul_gen()
void g2_mul_gen (g2_t r, const bn_t k)
Multiplies the generator of G_2 by an integer.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 742 of file relic_pc_exp.c.
References bn_free, bn_mod, bn_new, bn_null, ERR_CAUGHT, pc_get_ord, RLC_CAT, RLC_CATCH_ANY, RLC_FINALLY, RLC_G2_LOWER, RLC_THROW, and RLC_TRY.
Referenced by cp_bbs_gen(), cp_bbs_ver(), cp_bgn_dec2(), cp_bgn_enc2(), cp_bgn_gen(), cp_bls_gen(), cp_clb_gen(), cp_cli_gen(), cp_cls_gen(), cp_cmlhs_gen(), cp_cmlhs_sig(), cp_mklhs_gen(), cp_pbpsi_ask(), cp_zss_sig(), and pc_map_tri().
gt_exp()
void gt_exp (gt_t c, const gt_t a, const bn_t b)
Exponentiates an element from G_T by an integer. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the element to exponentiate.
[in] b - the integer exponent.
Definition at line 764 of file relic_pc_exp.c.
References bn_bits(), bn_sign(), ep_curve_embed(), ep_curve_frdim(), gt_exp_dig(), gt_exp_gls_naf(), gt_exp_gls_sac(), gt_inv, RLC_CAT, RLC_DIG, RLC_GT_LOWER, and RLC_NEG.
Referenced by cp_bgn_dec(), cp_cmlhs_gen(), cp_ibe_enc(), cp_lvprv_ver(), cp_lvpub_ver(), cp_pdprv_ver(), cp_pdpub_ver(), gt_exp_gen(), gt_exp_sim(), and gt_is_valid().
gt_exp_sec()
void gt_exp_sec (gt_t c, const gt_t a, const bn_t b)
Exponentiates an element from G_T by a secret integer. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the element to exponentiate.
[in] b - the integer exponent.
Definition at line 787 of file relic_pc_exp.c.
References bn_bits(), bn_sign(), ep_curve_frdim(), gt_exp_dig(), gt_exp_reg_gls(), gt_exp_reg_sac(), gt_inv, RLC_CAT, RLC_DIG, RLC_GT_LOWER, and RLC_NEG.
gt_exp_dig()
void gt_exp_dig (gt_t c, const gt_t a, const dig_t b)
Exponentiates an element from G_T by a small integer. Computes c = a^b.
Parameters
[out] c - the result.
[in] a - the element to exponentiate.
[in] b - the integer exponent.
Definition at line 807 of file relic_pc_exp.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ERR_CAUGHT, gt_copy, gt_free, gt_inv, gt_mul, gt_new, gt_null, gt_set_unity, gt_sqr, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by cp_cmlhs_off(), cp_cmlhs_ver(), gt_exp(), and gt_exp_sec().
gt_exp_sim()
void gt_exp_sim (gt_t e, const gt_t a, const bn_t b, const gt_t c, const bn_t d)
Exponentiates two elements from G_T by integers simultaneously. Computes e = a^b * c^d.
Parameters
[out] e - the result.
[in] a - the first element to exponentiate.
[in] b - the first integer exponent.
[in] a - the second element to exponentiate.
[in] b - the second integer exponent.
Definition at line 856 of file relic_pc_exp.c.
References bn_free, bn_mod, bn_new, bn_null, ERR_CAUGHT, gt_exp(), gt_free, gt_get_ord, gt_mul, gt_new, gt_null, RLC_CAT, RLC_CATCH_ANY, RLC_FINALLY, RLC_GT_LOWER, RLC_THROW, and RLC_TRY.
Referenced by gt_exp_mpc().
gt_exp_gen()
void gt_exp_gen (gt_t c, const bn_t b)
Exponentiates a generator from G_T by an integer. Computes c = a^b.
Parameters
[out] c - the result.
[in] b - the integer exponent.
Definition at line 893 of file relic_pc_exp.c.
References ERR_CAUGHT, gt_exp(), gt_free, gt_get_gen(), gt_new, gt_null, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pc_map_tri().