RELIC: src/fb/relic_fb_util.c File Reference
relic_fb_util.c File Reference
Binary field arithmetic
#include "relic_core.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
#include "relic_rand.h"
#include "relic_util.h"
Functions
static int valid_radix (int radix)
static int log_radix (int radix)
void fb_copy (fb_t c, const fb_t a)
void fb_neg (fb_t c, const fb_t a)
void fb_zero (fb_t a)
int fb_is_zero (const fb_t a)
int fb_get_bit (const fb_t a, int bit)
void fb_set_bit (fb_t a, int bit, int value)
int fb_bits (const fb_t a)
void fb_set_dig (fb_t c, dig_t a)
void fb_rand (fb_t a)
void fb_print (const fb_t a)
int fb_size_str (const fb_t a, int radix)
void fb_read_str (fb_t a, const char *str, int len, int radix)
void fb_write_str (char *str, int len, const fb_t a, int radix)
int fb_size_bin (const fb_t a)
void fb_read_bin (fb_t a, const uint8_t *bin, int len)
void fb_write_bin (uint8_t *bin, int len, const fb_t a)
Detailed Description
Implementation of the basic functions to manipulate binary field elements.
Version
Id
relic_fb_util.c 1927 2014-06-20 14:21:12Z dfaranha
Definition in file relic_fb_util.c.
Function Documentation
static int valid_radix (int radix) static
Checks if a radix is a power of two.
Parameters
[in] radix - the radix to check.
Returns
if radix is a valid radix.
Definition at line 48 of file relic_fb_util.c.
Referenced by fb_read_str(), fb_size_str(), and fb_write_str().
static int log_radix (int radix) static
Computes the logarithm of a valid radix in basis two.
Parameters
[in] radix - the valid radix.
Returns
the logarithm of the radix in basis two.
Definition at line 63 of file relic_fb_util.c.
Referenced by fb_read_str(), and fb_write_str().
void fb_copy (fb_t c, const fb_t a)
Copies the second argument to the first argument.
Parameters
[out] c - the result.
[in] a - the binary field element to copy.
Definition at line 77 of file relic_fb_util.c.
References FB_DIGS.
Referenced by eb_add_basic_imp(), eb_add_projc_mix(), eb_copy(), eb_curve_set(), eb_dbl_basic_imp(), eb_dbl_projc_imp(), eb_hlv(), eb_mul_halve(), eb_mul_lodah(), eb_neg_basic(), eb_neg_projc(), eb_norm_hlv(), eb_norm_imp(), eb_norm_sim(), eb_pck(), eb_rhs(), eb_upk(), fb2_mul_nor(), fb2_slv(), fb4_frb(), fb4_inv(), fb4_mul_dxd(), fb4_mul_dxs(), fb_exp_basic(), fb_exp_monty(), fb_exp_slide(), fb_inv_almos(), fb_inv_basic(), fb_inv_binar(), fb_inv_bruch(), fb_inv_exgcd(), fb_inv_itoht(), fb_inv_sim(), fb_itr_basic(), fb_itr_pre_quick(), fb_lsh(), fb_mul_basic(), fb_mul_rcomb(), fb_poly_add(), fb_poly_set(), fb_rdc_basic(), fb_read_bin(), fb_rsh(), fb_slv_basic(), fb_srt_basic(), fb_trc_basic(), fb_write_str(), find_solve(), and find_trace().
void fb_neg (fb_t c, const fb_t a)
Negates a binary field element.
Parameters
[out] c - the result.
[out] a - the binary field element to negate.
Definition at line 83 of file relic_fb_util.c.
References FB_DIGS.
void fb_zero (fb_t a)
Assigns zero to a binary field element.
Parameters
[out] a - the binary field element to assign.
Definition at line 89 of file relic_fb_util.c.
References FB_DIGS.
Referenced by eb_curve_init(), eb_frb_basic(), eb_mul_halve(), eb_mul_lodah(), eb_param_set(), eb_read_bin(), eb_set_infty(), fb_inv_bruch(), fb_itr_pre_quick(), fb_mul_basic(), fb_poly_init(), fb_poly_set_penta(), fb_poly_set_trino(), fb_read_str(), fb_set_dig(), find_solve(), and find_trace().
int fb_is_zero (const fb_t a)
Tests if a binary field element is zero or not.
Parameters
[in] a - the binary field element to test.
Returns
1 if the argument is zero, 0 otherwise.
Definition at line 97 of file relic_fb_util.c.
References FB_DIGS.
Referenced by detect_opt(), eb_add_basic_imp(), eb_add_projc_imp(), eb_add_projc_mix(), eb_is_infty(), eb_mul_lodah(), fb_write_str(), and find_trace().
int fb_get_bit (const fb_t a, int bit)
Reads the bit stored in the given position on a binary field element.
Parameters
[in] a - the binary field element.
[in] bit - the bit position.
Returns
the bit value.
Definition at line 108 of file relic_fb_util.c.
References FB_DIG_LOG, and SPLIT.
Referenced by eb_pck(), eb_upk(), eb_write_bin(), fb_mul_basic(), and fb_rdc_basic().
void fb_set_bit (fb_t a, int bit, int value)
Stores a bit in a given position on a binary field element.
Parameters
[out] a - the binary field element.
[in] bit - the bit position.
[in] value - the bit value.
Definition at line 116 of file relic_fb_util.c.
References FB_DIG_LOG, and SPLIT.
Referenced by eb_frb_basic(), eb_mul_lodah(), eb_mul_sim_kbltz(), eb_param_set(), eb_read_bin(), fb_poly_set_penta(), fb_poly_set_trino(), find_solve(), and find_trace().
int fb_bits (const fb_t a)
Returns the number of bits of a binary field element.
Parameters
[in] a - the binary field element.
Returns
the number of bits.
Definition at line 131 of file relic_fb_util.c.
References FB_DIG_LOG, FB_DIGS, and util_bits_dig().
Referenced by detect_opt(), fb_inv_exgcd(), fb_mul_basic(), and fb_rdc_basic().
void fb_set_dig (fb_t c, dig_t a)
Assigns a small positive polynomial to a binary field element.
The degree of the polynomial must be smaller than FB_DIGIT.
Parameters
[out] c - the result.
[in] a - the small polynomial to assign.
Definition at line 145 of file relic_fb_util.c.
References fb_zero().
Referenced by eb_frb_projc(), eb_hlv(), eb_map(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_norm_imp(), eb_norm_sim(), eb_pck(), eb_read_bin(), eb_tab(), eb_upk(), fb_exp_monty(), fb_exp_slide(), fb_inv_almos(), fb_inv_basic(), fb_inv_bruch(), fb_itr_pre_quick(), and find_srz().
void fb_rand (fb_t a)
Assigns a random value to a binary field element.
Parameters
[out] a - the binary field element to assign.
Definition at line 150 of file relic_fb_util.c.
References FB_BITS, FB_DIG_LOG, FB_DIGS, MASK, rand_bytes(), and SPLIT.
void fb_print (const fb_t a)
Prints a binary field element to standard output.
Parameters
[in] a - the binary field element to print.
Definition at line 162 of file relic_fb_util.c.
References FB_DIGS, util_print, and util_print_dig().
Referenced by eb_print().
int fb_size_str (const fb_t a, int radix)
Returns the number of digits in radix necessary to store a binary field element. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[in] a - the binary field element.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
Returns
the number of digits in the given radix.
Definition at line 175 of file relic_fb_util.c.
References bn_free, bn_new, bn_null, bn_read_raw(), bn_size_str(), CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, FB_DIGS, FINALLY, THROW, TRY, and valid_radix().
Referenced by fb_write_str().
void fb_read_str (fb_t a, const char * str, int len, int radix)
Reads a binary field element from a string in a given radix. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[out] a - the result.
[in] str - the string.
[in] len - the size of the string.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
ERR_NO_BUFFER - if the string is too long.
Definition at line 202 of file relic_fb_util.c.
References ERR_NO_BUFFER, ERR_NO_VALID, fb_add_dig(), fb_lshb_low(), fb_zero(), log_radix(), THROW, TOUPPER, util_conv_char(), and valid_radix().
void fb_write_str (char * str, int len, const fb_t a, int radix)
Writes a binary field element to a string in a given radix. The radix must be a power of 2 included in the interval [2, 64].
Parameters
[out] str - the string.
[in] len - the buffer capacity.
[in] a - the binary field element to write.
[in] radix - the radix.
Exceptions
ERR_NO_VALID - if the radix is invalid.
ERR_NO_BUFFER - if the buffer capacity is insufficient.
Definition at line 236 of file relic_fb_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, ERR_NO_VALID, fb_copy(), fb_free, fb_is_zero(), fb_new, fb_null, fb_rshb_low(), fb_size_str(), FINALLY, log_radix(), THROW, TRY, util_conv_char(), and valid_radix().
int fb_size_bin (const fb_t a)
Returns the number of bytes necessary to store a binary field element.
Parameters
[in] a - the binary field element.
Returns
the number of bytes.
Definition at line 293 of file relic_fb_util.c.
References FB_BYTES.
void fb_read_bin (fb_t a, const uint8_t * bin, int len)
Reads a binary field element from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not FP_BYTES.
Definition at line 297 of file relic_fb_util.c.
References bn_free, bn_new, bn_null, bn_read_bin(), CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FB_BYTES, fb_copy(), FINALLY, THROW, and TRY.
Referenced by eb_read_bin().
void fb_write_bin (uint8_t * bin, int len, const fb_t a)
Writes a binary field element to a byte vector in big-endian format.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the binary field element to write.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is not FP_BYTES.
Definition at line 321 of file relic_fb_util.c.
References bn_free, bn_new, bn_null, bn_read_raw(), bn_write_bin(), CATCH_ANY, ERR_CAUGHT, ERR_NO_BUFFER, FB_BYTES, FB_DIGS, FINALLY, THROW, and TRY.
Referenced by eb_write_bin().