RELIC: include/relic_test.h File Reference
relic_test.h File Reference
#include <string.h>
#include "relic_conf.h"
#include "relic_label.h"
#include "relic_util.h"
Macros
#define TEST_ONCE(P) util_print("Testing if " P "...%*c", (64 - strlen(P)), ' '); \
#define TEST_BEGIN(P)
#define TEST_ASSERT(C, LABEL)
#define TEST_END test_pass() \
Functions
void test_fail (void)
void test_pass (void)
Detailed Description
Interface of useful routines for testing.
Definition in file relic_test.h.
Macro Definition Documentation
TEST_ONCE
#define TEST_ONCE (P) util_print("Testing if " P "...%*c", (64 - strlen(P)), ' '); \
Runs a new benchmark once.
Parameters
[in] P - the property description.
Definition at line 54 of file relic_test.h.
TEST_BEGIN
#define TEST_BEGIN (P)
Value:
    util_print("Testing if " P "...%*c", (64 - strlen(P)), ' ');            \
    for (int i = 0; i < TESTS; i++)                                         \
Tests a sequence of commands to see if they respect some property.
Parameters
[in] P - the property description.
Definition at line 62 of file relic_test.h.
TEST_ASSERT
#define TEST_ASSERT (C, LABEL)
Value:
    if (!(C)) {                                                             \
        test_fail();                                                        \
        util_print("(at ");                                                 \
        util_print(__FILE__);                                               \
        util_print(":%d)\n", __LINE__);                                     \
        ERROR(LABEL);                                                       \
    }                                                                       \
Asserts a condition.
If the condition is not satisfied, a unconditional jump is made to the passed label.
Parameters
[in] C - the condition to assert.
[in] LABEL - the label to jump if the condition is no satisfied.
Definition at line 75 of file relic_test.h.
TEST_END
#define TEST_END test_pass() \
Finalizes a test printing the test result.
Definition at line 87 of file relic_test.h.
Function Documentation
test_fail()
void test_fail (void)
Prints a string indicating that the test failed.
Definition at line 142 of file relic_test.c.
References fail_font(), reset_font(), and util_print().
test_pass()
void test_pass (void)
Prints a string indicating that the test passed.
Definition at line 148 of file relic_test.c.
References pass_font(), reset_font(), and util_print().