RELIC: src/pc/relic_pc_util.c File Reference
relic_pc_util.c File Reference
Pairing-based cryptography
#include "relic_pc.h"
#include "relic_core.h"
Macros
#define gt_rand_imp(A) RLC_CAT(GT_LOWER, rand)(A)
Functions
void gt_rand (gt_t a)
void gt_get_gen (gt_t g)
int g1_is_valid (g1_t a)
int g2_is_valid (g2_t a)
int gt_is_valid (gt_t a)
Detailed Description
Implementation of pairing computation utilities.
Definition in file relic_pc_util.c.
Macro Definition Documentation
gt_rand_imp
#define gt_rand_imp (A) RLC_CAT(GT_LOWER, rand)(A)
Internal macro to map GT_T function to basic FPX implementation. The final exponentiation from the pairing is used to move element to subgroup.
Parameters
[out] A - the element to assign.
Definition at line 44 of file relic_pc_util.c.
Function Documentation
gt_rand()
void gt_rand (gt_t a)
Assigns a random value to an element from G_T.
Parameters
[out] a - the element to assign.
Definition at line 50 of file relic_pc_util.c.
References gt_rand_imp, pp_exp_k12(), and pp_exp_k2().
gt_get_gen()
void gt_get_gen (gt_t g)
Returns the generator for the group G_T.
Parameters
[out] g - the returned generator.
Definition at line 59 of file relic_pc_util.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, g1_free, g1_get_gen, g1_new, g1_null, g2_free, g2_get_gen, g2_new, g2_null, pc_map, THROW, and TRY.
g1_is_valid()
int g1_is_valid (g1_t a)
Checks if an element from G_1 is valid (has the right order).
Parameters
[in] a - the element to check.
Definition at line 82 of file relic_pc_util.c.
References bn_add_dig(), bn_cmp_dig(), bn_free(), bn_hlv(), bn_null, CATCH_ANY, ep_curve_get_cof(), ep_is_valid(), ERR_CAUGHT, FINALLY, g1_cmp, g1_dbl, g1_free, g1_get_ord, g1_mul, g1_new, g1_null, RLC_EQ, THROW, and TRY.
Referenced by cp_bbs_ver().
g2_is_valid()
int g2_is_valid (g2_t a)
Checks if an element form G_2 is valid (has the right order).
Parameters
[in] a - the element to check.
Definition at line 118 of file relic_pc_util.c.
References bn_add_dig(), bn_cmp_dig(), bn_free(), bn_hlv(), bn_null, bn_sub(), bn_sub_dig(), CATCH_ANY, bn_st::dp, dv_copy(), ep2_frb(), ep_curve_get_cof(), ERR_CAUGHT, FINALLY, fp_prime_get(), g2_add, g2_cmp, g2_dbl, g2_free, g2_get_ord, g2_mul, g2_neg, g2_new, g2_null, RLC_EQ, RLC_FP_DIGS, RLC_POS, bn_st::sign, THROW, TRY, and bn_st::used.
gt_is_valid()
int gt_is_valid (gt_t a)
Checks if an element form G_T is valid (has the right order).
Parameters
[in] a - the element to check.
Definition at line 174 of file relic_pc_util.c.
References bn_add_dig(), bn_cmp_dig(), bn_free(), bn_hlv(), bn_null, bn_sub(), bn_sub_dig(), CATCH_ANY, bn_st::dp, dv_copy(), ep_curve_get_cof(), ERR_CAUGHT, FINALLY, fp12_frb(), fp_prime_get(), gt_cmp, gt_exp, gt_free, gt_get_ord, gt_inv, gt_mul, gt_new, gt_null, gt_sqr, RLC_EQ, RLC_FP_DIGS, RLC_POS, bn_st::sign, THROW, TRY, and bn_st::used.