RELIC: src/epx/relic_ep2_mul.c File Reference
relic_ep2_mul.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep2_mul_glv_imp (ep2_t r, ep2_t p, const bn_t k)
static void ep2_mul_naf_imp (ep2_t r, ep2_t p, const bn_t k)
void ep2_mul_basic (ep2_t r, ep2_t p, const bn_t k)
void ep2_mul_slide (ep2_t r, ep2_t p, const bn_t k)
void ep2_mul_monty (ep2_t r, ep2_t p, const bn_t k)
void ep2_mul_lwnaf (ep2_t r, ep2_t p, const bn_t k)
void ep2_mul_gen (ep2_t r, bn_t k)
void ep2_mul_dig (ep2_t r, ep2_t p, dig_t k)
Detailed Description
Implementation of point multiplication on prime elliptic curves over quadratic extensions.
Definition in file relic_ep2_mul.c.
Function Documentation
ep2_mul_glv_imp()
static void ep2_mul_glv_imp (ep2_t r, ep2_t p, const bn_t k) static
Definition at line 43 of file relic_ep2_mul.c.
References bn_abs(), bn_add(), bn_add_dig(), bn_bits(), bn_copy(), bn_dbl(), bn_div(), bn_free(), bn_get_bit(), bn_mod, bn_neg(), bn_null, bn_sign(), bn_sub(), bn_sub_dig(), bn_zero(), CATCH_ANY, ep2_curve_get_ord(), ep2_curve_get_vs(), ep2_frb(), ep2_norm(), ep2_null, ep2_set_infty(), EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, FINALLY, fp_prime_get_par(), RLC_MAX, RLC_NEG, RLC_POS, bn_st::sign, THROW, and TRY.
Referenced by ep2_mul_lwnaf().
ep2_mul_naf_imp()
static void ep2_mul_naf_imp (ep2_t r, ep2_t p, const bn_t k) static
Definition at line 217 of file relic_ep2_mul.c.
References bn_rec_naf(), bn_sign(), CATCH_ANY, ep2_norm(), ep2_null, ep2_set_infty(), ep2_tab(), EP_WIDTH, ERR_CAUGHT, FINALLY, RLC_FP_BITS, RLC_NEG, THROW, and TRY.
Referenced by ep2_mul_lwnaf().
ep2_mul_basic()
void ep2_mul_basic (ep2_t r, ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 273 of file relic_ep2_mul.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ep2_copy(), ep2_is_infty(), ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, RLC_NEG, THROW, and TRY.
Referenced by ep2_map(), ep2_mul_cof_b12(), and ep2_mul_cof_bn().
ep2_mul_slide()
void ep2_mul_slide (ep2_t r, ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 319 of file relic_ep2_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), CATCH_ANY, ep2_copy(), ep2_is_infty(), ep2_norm(), ep2_norm_sim(), ep2_null, ep2_set_infty(), EP_WIDTH, ERR_CAUGHT, FINALLY, RLC_FP_BITS, RLC_NEG, THROW, TRY, and util_bits_dig().
ep2_mul_monty()
void ep2_mul_monty (ep2_t r, ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the constant-time Montgomery laddering point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 389 of file relic_ep2_mul.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, dv_swap_cond(), ep2_copy(), ep2_is_infty(), ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, RLC_FP_DIGS, RLC_NEG, THROW, and TRY.
ep2_mul_lwnaf()
void ep2_mul_lwnaf (ep2_t r, ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 442 of file relic_ep2_mul.c.
References bn_is_zero(), ep2_is_infty(), ep2_mul_glv_imp(), ep2_mul_naf_imp(), ep2_set_infty(), and ep_curve_is_endom().
ep2_mul_gen()
void ep2_mul_gen (ep2_t r, bn_t k)
Multiplies the generator of an elliptic curve over a qaudratic extension.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 462 of file relic_ep2_mul.c.
References bn_is_zero(), CATCH_ANY, ep2_curve_get_gen(), ep2_curve_get_tab(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by ep2_mul_sim_gen(), and ep2_rand().
ep2_mul_dig()
void ep2_mul_dig (ep2_t r, ep2_t p, dig_t k)
Multiplies a prime elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 489 of file relic_ep2_mul.c.
References CATCH_ANY, ep2_copy(), ep2_is_infty(), ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, THROW, TRY, and util_bits_dig().
Referenced by ep2_map().