RELIC: src/epx/relic_ep8_mul_cof.c File Reference
relic_ep8_mul_cof.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_md.h"
Functions
void ep8_mul_cof (ep8_t r, const ep8_t p)
Detailed Description
Implementation of point multiplication of a prime elliptic curve over an octic extension field by the curve cofactor.
Definition in file relic_ep8_mul_cof.c.
Function Documentation
ep8_mul_cof()
void ep8_mul_cof (ep8_t r, const ep8_t p)
Multiplies a point in an elliptic curve over an octic extension field by the curve cofactor or a small multiple for which a short vector exists. In short, it takes a point in the curve to the large prime-order subgroup.
Parameters
[out] R - the result.
[in] P - the point to multiply.
Definition at line 40 of file relic_ep8_mul_cof.c.
References bn_free, bn_new, bn_null, ep8_add, ep8_dbl, ep8_frb(), ep8_free, ep8_mul_basic(), ep8_new, ep8_norm(), ep8_null, ep8_sub(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_map().