RELIC: src/epx/relic_ep4_curve.c File Reference
relic_ep4_curve.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Macros
#define ASSIGN(CURVE)
Functions
static void detect_opt (int *opt, fp4_t a)
void ep4_curve_init (void)
void ep4_curve_clean (void)
int ep4_curve_opt_a (void)
int ep4_curve_opt_b (void)
void ep4_curve_mul_a (fp4_t c, const fp4_t a)
void ep4_curve_mul_b (fp4_t c, const fp4_t a)
int ep4_curve_is_twist (void)
void ep4_curve_get_gen (ep4_t g)
fp2_t * ep4_curve_get_a (void)
fp2_t * ep4_curve_get_b (void)
void ep4_curve_get_ord (bn_t n)
void ep4_curve_get_cof (bn_t h)
ep4_t * ep4_curve_get_tab (void)
void ep4_curve_set_twist (int type)
void ep4_curve_set (const fp4_t a, const fp4_t b, const ep4_t g, const bn_t r, const bn_t h)
Detailed Description
Implementation of configuration of prime elliptic curves over a quartic extension field.
Definition in file relic_ep4_curve.c.
Macro Definition Documentation
ASSIGN
#define ASSIGN (CURVE)
Assigns a set of ordinary elliptic curve parameters.
Parameters
[in] CURVE - the curve parameters to assign.
Definition at line 230 of file relic_ep4_curve.c.
Referenced by ep4_curve_set_twist().
Function Documentation
detect_opt()
static void detect_opt (int * opt, fp4_t a) static
Detects an optimization based on the curve coefficients.
Definition at line 271 of file relic_ep4_curve.c.
References ERR_CAUGHT, fp2_is_zero(), fp4_cmp(), fp4_cmp_dig(), fp4_free, fp4_is_zero(), fp4_neg(), fp4_new, fp4_null, fp4_set_dig(), fp_bits(), fp_is_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_EQ, RLC_FINALLY, RLC_HUGE, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep4_curve_set_twist().
ep4_curve_init()
void ep4_curve_init (void)
Initializes the elliptic curve over quartic extension.
Definition at line 307 of file relic_ep4_curve.c.
References bn_make(), core_get(), _ctx_t::ep4_a, _ctx_t::ep4_b, _ctx_t::ep4_g, _ctx_t::ep4_h, ep4_new, _ctx_t::ep4_pre, _ctx_t::ep4_ptr, _ctx_t::ep4_r, fp4_new, RLC_EP_TABLE, RLC_FP_DIGS, ep4_st::x, ep4_st::y, and ep4_st::z.
Referenced by pp_map_init().
ep4_curve_clean()
void ep4_curve_clean (void)
Finalizes the elliptic curve over quartic extension.
Definition at line 335 of file relic_ep4_curve.c.
References bn_clean(), core_get(), _ctx_t::ep4_a, _ctx_t::ep4_b, ep4_free, _ctx_t::ep4_g, _ctx_t::ep4_h, _ctx_t::ep4_pre, _ctx_t::ep4_r, fp4_free, RLC_EP_TABLE, ep4_st::x, ep4_st::y, and ep4_st::z.
Referenced by pp_map_clean().
ep4_curve_opt_a()
int ep4_curve_opt_a (void)
Returns a optimization identifier based on the 'a' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 353 of file relic_ep4_curve.c.
References core_get(), and _ctx_t::ep4_opt_a.
Referenced by ep4_rhs().
ep4_curve_opt_b()
int ep4_curve_opt_b (void)
Returns b optimization identifier based on the 'b' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 357 of file relic_ep4_curve.c.
References core_get(), and _ctx_t::ep4_opt_b.
Referenced by ep4_curve_set_twist(), and ep4_rhs().
ep4_curve_mul_a()
void ep4_curve_mul_a (fp4_t c, const fp4_t a)
Multiplies a field element by the a-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 361 of file relic_ep4_curve.c.
References core_get(), _ctx_t::ep4_a, ep4_curve_is_twist(), _ctx_t::ep4_opt_a, _ctx_t::ep_opt_a, fp4_copy(), fp4_dbl(), fp4_mul, fp4_mul_art(), fp4_mul_dig(), fp4_zero(), RLC_EP_MTYPE, RLC_ONE, RLC_TINY, RLC_TWO, and RLC_ZERO.
Referenced by pp_dbl_k16_projc_basic(), and pp_dbl_k16_projc_lazyr().
ep4_curve_mul_b()
void ep4_curve_mul_b (fp4_t c, const fp4_t a)
Multiplies a field element by the b-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 402 of file relic_ep4_curve.c.
References core_get(), _ctx_t::ep4_b, _ctx_t::ep4_opt_b, fp4_copy(), fp4_mul, fp4_mul_dig(), fp4_zero(), RLC_ONE, RLC_TINY, and RLC_ZERO.
ep4_curve_is_twist()
int ep4_curve_is_twist (void)
Tests if the configured elliptic curve is a twist.
Returns
the type of the elliptic curve twist, 0 if non-twisted curve.
Definition at line 422 of file relic_ep4_curve.c.
References core_get(), and _ctx_t::ep4_is_twist.
Referenced by ep4_curve_mul_a(), pp_add_k16_basic(), pp_add_k16_projc_basic(), pp_add_k16_projc_lazyr(), pp_add_k24_basic(), pp_add_k24_projc(), pp_add_lit_k16(), pp_dbl_k16_basic(), pp_dbl_k16_projc_basic(), pp_dbl_k16_projc_lazyr(), pp_dbl_k24_basic(), pp_dbl_k24_projc(), and pp_dbl_lit_k16().
ep4_curve_get_gen()
void ep4_curve_get_gen (ep4_t g)
Returns the generator of the group of points in the elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 426 of file relic_ep4_curve.c.
References core_get(), and ep4_copy().
Referenced by ep4_mul_gen(), and ep4_mul_sim_gen().
ep4_curve_get_a()
fp2_t * ep4_curve_get_a (void)
Returns the 'a' coefficient of the currently configured elliptic curve.
Returns
the 'a' coefficient of the elliptic curve.
Definition at line 430 of file relic_ep4_curve.c.
References core_get(), and _ctx_t::ep4_a.
Referenced by ep4_map(), and ep4_rhs().
ep4_curve_get_b()
fp2_t * ep4_curve_get_b (void)
Returns the 'b' coefficient of the currently configured elliptic curve.
Parameters
[out] b - the 'b' coefficient of the elliptic curve.
Definition at line 434 of file relic_ep4_curve.c.
References core_get(), and _ctx_t::ep4_b.
Referenced by ep4_rhs(), and pp_dbl_k24_projc().
ep4_curve_get_ord()
void ep4_curve_get_ord (bn_t n)
Returns the order of the group of points in the elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 438 of file relic_ep4_curve.c.
References bn_copy(), core_get(), _ctx_t::ep4_is_twist, _ctx_t::ep4_r, and ep_curve_get_ord().
Referenced by ep4_mul_fix_basic(), ep4_mul_fix_combd(), ep4_mul_fix_combs(), ep4_mul_gls_imp(), ep4_mul_monty(), ep4_mul_pre_basic(), ep4_mul_pre_combd(), ep4_mul_pre_combs(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_trick(), and ep4_rand().
ep4_curve_get_cof()
void ep4_curve_get_cof (bn_t h)
Returns the cofactor of the group order in the elliptic curve.
Parameters
[out] h - the returned cofactor.
Definition at line 447 of file relic_ep4_curve.c.
References bn_copy(), and core_get().
Referenced by ep4_mul_cof().
ep4_curve_get_tab()
ep4_t * ep4_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 453 of file relic_ep4_curve.c.
References core_get(), and _ctx_t::ep4_ptr.
Referenced by ep4_curve_set(), ep4_curve_set_twist(), ep4_mul_gen(), and ep4_mul_sim_gen().
ep4_curve_set_twist()
void ep4_curve_set_twist (int type)
Configures an elliptic curve by twisting the curve over the base prime field.
Parameters
- the type of twist (multiplicative or divisive)
Definition at line 463 of file relic_ep4_curve.c.
References AFG16_P510, AFG16_P766, ASSIGN, B24_P315, B24_P317, B24_P509, BASIC, bn_copy(), bn_free, bn_new, bn_null, core_get(), detect_opt(), _ctx_t::ep4_a, _ctx_t::ep4_b, ep4_copy(), ep4_curve_get_tab(), ep4_curve_opt_b(), ep4_free, _ctx_t::ep4_g, _ctx_t::ep4_h, _ctx_t::ep4_is_twist, ep4_mul_pre, ep4_new, ep4_null, _ctx_t::ep4_opt_a, _ctx_t::ep4_opt_b, _ctx_t::ep4_r, ep_param_get(), ERR_CAUGHT, ERR_NO_VALID, FM16_P765, fp2_is_zero(), _ctx_t::fp2_p2, fp2_zero(), fp4_copy(), fp4_free, fp4_inv(), fp4_new, fp4_null, _ctx_t::fp4_p1, fp4_set_dig(), fp4_zero(), fp_copy(), _ctx_t::frb4, K16_P330, K16_P766, pc_core_calc(), RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_EP_MTYPE, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, RLC_TRY, and RLC_ZERO.
Referenced by ep_param_set_any_pairf().
ep4_curve_set()
void ep4_curve_set (const fp4_t a, const fp4_t b, const ep4_t g, const bn_t r, const bn_t h)
Configures an elliptic curve over a quartic extension by its coefficients.
Parameters
[in] a - the 'a' coefficient of the curve.
[in] b - the 'b' coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
Definition at line 592 of file relic_ep4_curve.c.
References bn_copy(), core_get(), _ctx_t::ep4_a, _ctx_t::ep4_b, ep4_curve_get_tab(), _ctx_t::ep4_g, _ctx_t::ep4_h, _ctx_t::ep4_is_twist, ep4_mul_pre, ep4_norm(), _ctx_t::ep4_r, and fp4_copy().