RELIC: src/epx/relic_ep4_dbl.c File Reference
relic_ep4_dbl.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_ep_dbl_tmpl.h"
Functions
TMPL_DBL_BASIC_IMP (ep4, fp4)
TMPL_DBL_PROJC_IMP (ep4, fp4)
TMPL_DBL_JACOB_IMP (ep4, fp4)
void ep4_dbl_basic (ep4_t r, const ep4_t p)
void ep4_dbl_slp_basic (ep4_t r, fp4_t s, const ep4_t p)
void ep4_dbl_projc (ep4_t r, const ep4_t p)
void ep4_dbl_jacob (ep4_t r, const ep4_t p)
Detailed Description
Implementation of doubling on elliptic prime curves over a quartic extension field.
Definition in file relic_ep4_dbl.c.
Function Documentation
TMPL_DBL_BASIC_IMP()
TMPL_DBL_BASIC_IMP (ep4 , fp4)
Doubles a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
TMPL_DBL_PROJC_IMP()
TMPL_DBL_PROJC_IMP (ep4 , fp4)
Doubles a point represented in projective coordinates on an ordinary prime elliptic curve.
Parameters
r - the result.
p - the point to double.
TMPL_DBL_JACOB_IMP()
TMPL_DBL_JACOB_IMP (ep4 , fp4)
Doubles a point represented in Jacobian coordinates on an ordinary prime elliptic curve.
Parameters
r - the result.
p - the point to double.
ep4_dbl_basic()
void ep4_dbl_basic (ep4_t r, const ep4_t p)
Doubles a point represented in affine coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[int] p - the point to double.
Definition at line 86 of file relic_ep4_dbl.c.
References ep4_is_infty(), and ep4_set_infty().
ep4_dbl_slp_basic()
void ep4_dbl_slp_basic (ep4_t r, fp4_t s, const ep4_t p)
Doubles a point represented in affine coordinates in an elliptic curve over a quartic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 94 of file relic_ep4_dbl.c.
References ep4_is_infty(), and ep4_set_infty().
Referenced by pp_dbl_k16_basic(), and pp_dbl_k24_basic().
ep4_dbl_projc()
void ep4_dbl_projc (ep4_t r, const ep4_t p)
Doubles a point represented in projective coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 107 of file relic_ep4_dbl.c.
References ep4_is_infty(), and ep4_set_infty().
ep4_dbl_jacob()
void ep4_dbl_jacob (ep4_t r, const ep4_t p)
Doubles a point represented in Jacobian coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 120 of file relic_ep4_dbl.c.
References ep4_is_infty(), and ep4_set_infty().