RELIC: src/epx/relic_ep2_util.c File Reference
relic_ep2_util.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
int ep2_is_infty (ep2_t p)
void ep2_set_infty (ep2_t p)
void ep2_copy (ep2_t r, ep2_t p)
int ep2_cmp (ep2_t p, ep2_t q)
void ep2_rand (ep2_t p)
void ep2_rhs (fp2_t rhs, ep2_t p)
int ep2_is_valid (ep2_t p)
void ep2_tab (ep2_t *t, ep2_t p, int w)
void ep2_print (ep2_t p)
int ep2_size_bin (ep2_t a, int pack)
void ep2_read_bin (ep2_t a, const uint8_t *bin, int len)
void ep2_write_bin (uint8_t *bin, int len, ep2_t a, int pack)
Detailed Description
Implementation of utilities for prime elliptic curves over quadratic extensions.
Definition in file relic_ep2_util.c.
Function Documentation
ep2_is_infty()
int ep2_is_infty (ep2_t p)
Tests if a point on a elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep2_util.c.
References fp2_is_zero(), and ep2_st::z.
Referenced by ep2_add_basic(), ep2_add_projc(), ep2_add_slp_basic(), ep2_dbl_basic(), ep2_dbl_projc(), ep2_dbl_slp_basic(), ep2_is_valid(), ep2_mul_basic(), ep2_mul_dig(), ep2_mul_lwnaf(), ep2_mul_monty(), ep2_mul_sim_gen(), ep2_mul_sim_inter(), ep2_mul_sim_joint(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_neg_basic(), ep2_neg_projc(), ep2_norm(), ep2_size_bin(), ep2_write_bin(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), pp_map_weilp_k12(), pp_norm_k12(), and pp_norm_k8().
ep2_set_infty()
void ep2_set_infty (ep2_t p)
Assigns a elliptic curve point to a point at the infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep2_util.c.
References fp2_zero(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_add_basic_imp(), ep2_add_projc_imp(), ep2_add_projc_mix(), ep2_curve_init(), ep2_dbl_basic(), ep2_dbl_projc(), ep2_dbl_slp_basic(), ep2_mul_basic(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_ordin(), ep2_mul_gen(), ep2_mul_glv_imp(), ep2_mul_lwnaf(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_sim_dig(), ep2_mul_sim_joint(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_neg_basic(), ep2_neg_projc(), ep2_norm(), ep2_read_bin(), ep2_sub_basic(), ep2_sub_projc(), pp_norm_k12(), and pp_norm_k8().
ep2_copy()
void ep2_copy (ep2_t r, ep2_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the elliptic curve point to copy.
Definition at line 50 of file relic_ep2_util.c.
References fp2_copy(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_add_basic(), ep2_add_projc(), ep2_add_slp_basic(), ep2_cmp(), ep2_curve_get_gen(), ep2_curve_set_twist(), ep2_frb(), ep2_mul_basic(), ep2_mul_dig(), ep2_mul_fix_combs(), ep2_mul_monty(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_ordin(), ep2_mul_sim_joint(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_norm(), ep2_tab(), pp_add_k12_basic(), pp_add_k8_basic(), pp_dbl_k12_basic(), pp_dbl_k8_basic(), pp_mil_k12(), pp_mil_k8(), pp_norm_k12(), and pp_norm_k8().
ep2_cmp()
int ep2_cmp (ep2_t p, ep2_t q)
Compares two elliptic curve points.
Parameters
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 57 of file relic_ep2_util.c.
References CATCH_ANY, ep2_copy(), ep2_norm(), ep2_null, ERR_CAUGHT, FINALLY, fp2_cmp(), ep2_st::norm, result, RLC_EQ, RLC_NE, THROW, TRY, ep2_st::x, ep2_st::y, and ep2_st::z.
ep2_rand()
void ep2_rand (ep2_t p)
Assigns a random value to an elliptic curve point.
Parameters
[out] p - the elliptic curve point to assign.
Definition at line 110 of file relic_ep2_util.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, ep2_curve_get_ord(), ep2_mul_gen(), ERR_CAUGHT, FINALLY, THROW, and TRY.
ep2_rhs()
void ep2_rhs (fp2_t rhs, ep2_t p)
Computes the right-hand side of the elliptic curve equation at a certain elliptic curve point.
Parameters
[out] rhs - the result.
[in] p - the point.
Definition at line 134 of file relic_ep2_util.c.
References CATCH_ANY, ep2_curve_get_a(), ep2_curve_get_b(), ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_new, fp2_null, THROW, TRY, and ep2_st::x.
Referenced by ep2_is_valid(), ep2_map(), and ep2_upk().
ep2_is_valid()
int ep2_is_valid (ep2_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 168 of file relic_ep2_util.c.
References CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, ep2_rhs(), ERR_CAUGHT, FINALLY, fp2_cmp(), RLC_EQ, THROW, TRY, ep2_st::x, and ep2_st::y.
ep2_tab()
void ep2_tab (ep2_t * t, ep2_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 191 of file relic_ep2_util.c.
References ep2_copy(), ep2_norm(), and ep2_norm_sim().
Referenced by ep2_mul_naf_imp(), and ep2_mul_sim_plain().
ep2_print()
void ep2_print (ep2_t p)
Prints a elliptic curve point.
Parameters
[in] p - the elliptic curve point to print.
Definition at line 208 of file relic_ep2_util.c.
References fp2_print(), ep2_st::x, ep2_st::y, and ep2_st::z.
ep2_size_bin()
int ep2_size_bin (ep2_t a, int pack)
Returns the number of bytes necessary to store a prime elliptic curve point over a quadratic extension with optional point compression.
Parameters
[in] a - the prime field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 214 of file relic_ep2_util.c.
References CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, ERR_CAUGHT, FINALLY, RLC_FP_BYTES, THROW, and TRY.
ep2_read_bin()
void ep2_read_bin (ep2_t a, const uint8_t * bin, int len)
Reads a prime elliptic curve point over a quadratic extension from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 242 of file relic_ep2_util.c.
References ep2_set_infty(), ep2_upk(), ERR_NO_BUFFER, ERR_NO_VALID, fp2_read_bin(), fp2_zero(), fp_set_bit(), fp_set_dig(), fp_zero(), ep2_st::norm, RLC_FP_BYTES, THROW, ep2_st::x, ep2_st::y, and ep2_st::z.
ep2_write_bin()
void ep2_write_bin (uint8_t * bin, int len, ep2_t a, int pack)
Writes a prime elliptic curve pointer over a quadratic extension to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime elliptic curve point to write.
[in] pack - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 288 of file relic_ep2_util.c.
References CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, ep2_pck(), ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, fp2_write_bin(), fp_get_bit(), RLC_FP_BYTES, THROW, TRY, ep2_st::x, and ep2_st::y.