RELIC: src/cp/relic_cp_pss.c File Reference
relic_cp_pss.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_pss_gen (bn_t r, bn_t s, g2_t g, g2_t x, g2_t y)
int cp_pss_sig (g1_t a, g1_t b, uint8_t *msg, int len, bn_t r, bn_t s)
int cp_pss_ver (g1_t a, g1_t b, uint8_t *msg, int len, g2_t g, g2_t x, g2_t y)
int cp_psb_gen (bn_t r, bn_t s[], g2_t g, g2_t x, g2_t y[], int l)
int cp_psb_sig (g1_t a, g1_t b, uint8_t *msgs[], int lens[], bn_t r, bn_t s[], int l)
int cp_psb_ver (g1_t a, g1_t b, uint8_t *msgs[], int lens[], g2_t g, g2_t x, g2_t y[], int l)
Detailed Description
Implementation of the Pointcheval-Sanders signature protocols.
Definition in file relic_cp_pss.c.
Function Documentation
cp_pss_gen()
int cp_pss_gen (bn_t u, bn_t v, g2_t g, g2_t x, g2_t y)
Generates a key pair for the Pointcheval-Sanders simple signature (PSS) protocol.
Parameters
[out] u - the first part of the private key.
[out] v - the second part of the private key.
[out] g - the first part of the public key.
[out] x - the secpmd part of the public key.
[out] y - the third part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_pss.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, FINALLY, g2_get_ord, g2_mul, g2_rand, result, RLC_ERR, RLC_OK, and TRY.
cp_pss_sig()
int cp_pss_sig (g1_t a, g1_t b, uint8_t * msg, int len, bn_t u, bn_t v)
Signs a message using the PSS protocol.
Parameters
[out] a - the first part of the signature.
[out] b - the second part of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] u - the first part of the private key.
[in] v - the second part of the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 63 of file relic_cp_pss.c.
References bn_add(), bn_free(), bn_mod, bn_null, bn_read_bin(), CATCH_ANY, FINALLY, g1_get_ord, g1_mul, g1_rand, result, RLC_ERR, RLC_OK, and TRY.
cp_pss_ver()
int cp_pss_ver (g1_t a, g1_t b, uint8_t * msg, int len, g2_t g, g2_t x, g2_t y)
Verifies a signature using the PSS protocol.
Parameters
[in] a - the first part of the signature.
[in] b - the second part of the signature.
[in] msg - the message to sign.
[in] len - the message length in bytes.
[in] g - the first part of the public key.
[in] u - the second part of the public key.
[in] v - the third part of the public key.
Returns
a boolean value indicating the verification result.
Definition at line 93 of file relic_cp_pss.c.
References bn_free(), bn_mod, bn_null, bn_read_bin(), CATCH_ANY, ERR_CAUGHT, FINALLY, g1_copy, g1_free, g1_get_ord, g1_is_infty, g1_new, g1_null, g2_add, g2_copy, g2_free, g2_mul, g2_neg, g2_new, g2_norm, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_map_sim, result, THROW, and TRY.
cp_psb_gen()
int cp_psb_gen (bn_t r, bn_t s[], g2_t g, g2_t x, g2_t y[], int l)
Generates a key pair for the Pointcheval-Sanders block signature (PSB) protocol.
Parameters
[out] r - the first part of the private key.
[out] s - the second part of the private key.
[out] g - the first part of the public key.
[out] x - the secpmd part of the public key.
[out] y - the third part of the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 152 of file relic_cp_pss.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, FINALLY, g2_get_ord, g2_mul, g2_rand, result, RLC_ERR, RLC_OK, and TRY.
cp_psb_sig()
int cp_psb_sig (g1_t a, g1_t b, uint8_t * msgs[], int lens[], bn_t r, bn_t s[], int l)
Signs a block of messages using the PSB protocol.
Parameters
[out] a - the first component of the signature.
[out] b - the second component of the signature.
[in] msgs - the l messages to sign.
[in] lens - the l message lengths in bytes.
[in] r - the first part of the private key.
[in] s - the remaining l part of the private key.
[in] l - the number of messages to sign.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 179 of file relic_cp_pss.c.
References bn_add(), bn_copy(), bn_free(), bn_mod, bn_null, bn_read_bin(), CATCH_ANY, FINALLY, g1_get_ord, g1_mul, g1_rand, result, RLC_ERR, RLC_OK, and TRY.
cp_psb_ver()
int cp_psb_ver (g1_t a, g1_t b, uint8_t * msgs[], int lens[], g2_t g, g2_t x, g2_t y[], int l)
Verifies a block of messages signed using the PSB protocol.
Parameters
[out] a - the first component of the signature.
[out] b - the seconed component of the signature.
[in] msgs - the l messages to sign.
[in] lens - the l message lengths in bytes.
[in] g - the first part of the public key.
[in] x - the second part of the public key.
[in] y - the remaining l parts of the public key.
[in] l - the number of messages to sign.
Returns
a boolean value indicating the verification result.
Definition at line 219 of file relic_cp_pss.c.
References bn_free(), bn_mod, bn_null, bn_read_bin(), CATCH_ANY, ERR_CAUGHT, FINALLY, g1_copy, g1_free, g1_get_ord, g1_is_infty, g1_new, g1_null, g2_add, g2_copy, g2_free, g2_mul, g2_neg, g2_new, g2_norm, g2_null, gt_free, gt_is_unity, gt_new, gt_null, pc_map_sim, result, THROW, and TRY.