RELIC: include/relic_epx.h File Reference
relic_epx.h File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_fpx.h"
#include "relic_ep.h"
#include "relic_types.h"
Data Structures
struct ep2_st
struct ep3_st
Macros
#define RLC_EPX_TABLE_BASIC (2 * RLC_FP_BITS + 1)
#define RLC_EPX_TABLE_COMBS (1 << EP_DEPTH)
#define RLC_EPX_TABLE_COMBD (1 << (EP_DEPTH + 1))
#define RLC_EPX_TABLE_LWNAF (1 << (EP_DEPTH - 2))
#define RLC_EPX_TABLE_MAX RLC_MAX(RLC_EPX_TABLE_BASIC, RLC_EPX_TABLE_COMBD)
#define ep2_null(A) A = NULL
Typedefs
typedef ep2_st * ep2_t
typedef ep3_st * ep3_t
Functions
void ep2_curve_init (void)
void ep2_curve_clean (void)
void ep2_curve_get_a (fp2_t a)
void ep2_curve_get_b (fp2_t b)
void ep2_curve_get_vs (bn_t *v)
int ep2_curve_opt_a (void)
int ep2_curve_is_twist (void)
void ep2_curve_get_gen (ep2_t g)
ep2_t * ep2_curve_get_tab (void)
void ep2_curve_get_ord (bn_t n)
void ep2_curve_get_cof (bn_t h)
void ep2_curve_set (fp2_t a, fp2_t b, ep2_t g, bn_t r, bn_t h)
void ep2_curve_set_twist (int type)
int ep2_is_infty (ep2_t p)
void ep2_set_infty (ep2_t p)
void ep2_copy (ep2_t r, ep2_t p)
int ep2_cmp (ep2_t p, ep2_t q)
void ep2_rand (ep2_t p)
void ep2_rhs (fp2_t rhs, ep2_t p)
int ep2_is_valid (ep2_t p)
void ep2_tab (ep2_t *t, ep2_t p, int w)
void ep2_print (ep2_t p)
int ep2_size_bin (ep2_t a, int pack)
void ep2_read_bin (ep2_t a, const uint8_t *bin, int len)
void ep2_write_bin (uint8_t *bin, int len, ep2_t a, int pack)
void ep2_neg_basic (ep2_t r, ep2_t p)
void ep2_neg_projc (ep2_t r, ep2_t p)
void ep2_add_basic (ep2_t r, ep2_t p, ep2_t q)
void ep2_add_slp_basic (ep2_t r, fp2_t s, ep2_t p, ep2_t q)
void ep2_sub_basic (ep2_t r, ep2_t p, ep2_t q)
void ep2_add_projc (ep2_t r, ep2_t p, ep2_t q)
void ep2_sub_projc (ep2_t r, ep2_t p, ep2_t q)
void ep2_dbl_basic (ep2_t r, ep2_t p)
void ep2_dbl_slp_basic (ep2_t r, fp2_t s, ep2_t p)
void ep2_dbl_projc (ep2_t r, ep2_t p)
void ep2_mul_basic (ep2_t r, ep2_t p, const bn_t k)
void ep2_mul_slide (ep2_t r, ep2_t p, const bn_t k)
void ep2_mul_monty (ep2_t r, ep2_t p, const bn_t k)
void ep2_mul_lwnaf (ep2_t r, ep2_t p, const bn_t k)
void ep2_mul_lwreg (ep2_t r, ep2_t p, const bn_t k)
void ep2_mul_gen (ep2_t r, bn_t k)
void ep2_mul_dig (ep2_t r, ep2_t p, dig_t k)
void ep2_mul_pre_basic (ep2_t *t, ep2_t p)
void ep2_mul_pre_yaowi (ep2_t *t, ep2_t p)
void ep2_mul_pre_nafwi (ep2_t *t, ep2_t p)
void ep2_mul_pre_combs (ep2_t *t, ep2_t p)
void ep2_mul_pre_combd (ep2_t *t, ep2_t p)
void ep2_mul_pre_lwnaf (ep2_t *t, ep2_t p)
void ep2_mul_fix_basic (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_fix_yaowi (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_fix_nafwi (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_fix_combs (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_fix_combd (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_fix_lwnaf (ep2_t r, ep2_t *t, bn_t k)
void ep2_mul_sim_basic (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
void ep2_mul_sim_trick (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
void ep2_mul_sim_inter (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
void ep2_mul_sim_joint (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
void ep2_mul_sim_gen (ep2_t r, bn_t k, ep2_t q, bn_t m)
void ep2_mul_sim_dig (ep2_t r, ep2_t p[], dig_t k[], int len)
void ep2_norm (ep2_t r, ep2_t p)
void ep2_norm_sim (ep2_t *r, ep2_t *t, int n)
void ep2_map (ep2_t p, const uint8_t *msg, int len)
void ep2_frb (ep2_t r, ep2_t p, int i)
void ep2_pck (ep2_t r, ep2_t p)
int ep2_upk (ep2_t r, ep2_t p)
Detailed Description
Interface of the module for arithmetic on prime elliptic curves defined over extension fields.
Definition in file relic_epx.h.
Macro Definition Documentation
RLC_EPX_TABLE_BASIC
#define RLC_EPX_TABLE_BASIC (2 * RLC_FP_BITS + 1)
Size of a precomputation table using the binary method.
Definition at line 51 of file relic_epx.h.
RLC_EPX_TABLE_COMBS
#define RLC_EPX_TABLE_COMBS (1 << EP_DEPTH)
Size of a precomputation table using the single-table comb method.
Definition at line 56 of file relic_epx.h.
RLC_EPX_TABLE_COMBD
#define RLC_EPX_TABLE_COMBD (1 << (EP_DEPTH + 1))
Size of a precomputation table using the double-table comb method.
Definition at line 61 of file relic_epx.h.
RLC_EPX_TABLE_LWNAF
#define RLC_EPX_TABLE_LWNAF (1 << (EP_DEPTH - 2))
Size of a precomputation table using the w-(T)NAF method.
Definition at line 66 of file relic_epx.h.
RLC_EPX_TABLE_MAX
#define RLC_EPX_TABLE_MAX RLC_MAX(RLC_EPX_TABLE_BASIC, RLC_EPX_TABLE_COMBD)
Size of a precomputation table using the chosen algorithm. Maximum size of a precomputation table.
Definition at line 87 of file relic_epx.h.
ep2_null
#define ep2_null (A) A = NULL
Initializes a point on a elliptic curve with a null value.
Parameters
[out] A - the point to initialize.
Definition at line 155 of file relic_epx.h.
Typedef Documentation
ep2_t
typedef ep2_st* ep2_t
Pointer to an elliptic curve point.
Definition at line 116 of file relic_epx.h.
ep3_t
typedef ep3_st* ep3_t
Pointer to an elliptic curve point.
Definition at line 140 of file relic_epx.h.
Function Documentation
ep2_curve_init()
void ep2_curve_init (void)
Calls a function to allocate a point on a elliptic curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory. Calls a function to clean and free a point on a elliptic curve.
Parameters
[out] A - the point to free. Negates a point in an elliptic curve over a quadratic extension field. Computes R = -P.
[out] R - the result.
[in] P - the point to negate. Adds two points in an elliptic curve over a quadratic extension field. Computes R = P + Q.
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add. Subtracts a point in an elliptic curve over a quadratic extension field from another point in this curve. Computes R = P - Q.
[out] R - the result.
[in] P - the first point.
[in] Q - the second point. Doubles a point in an elliptic curve over a quadratic extension field. Computes R = 2P.
[out] R - the result.
[in] P - the point to double. Multiplies a point in an elliptic curve over a quadratic extension field. Computes R = kP.
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer. Builds a precomputation table for multiplying a fixed prime elliptic point over a quadratic extension.
[out] T - the precomputation table.
[in] P - the point to multiply. Multiplies a fixed prime elliptic point over a quadratic extension using a precomputation table. Computes R = kP.
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer. Multiplies and adds two prime elliptic curve points simultaneously. Computes R = kP + lQ.
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] M - the second integer, Initializes the elliptic curve over quadratic extension.
Definition at line 255 of file relic_ep2_curve.c.
References bn_init(), core_get(), _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_pre, _ctx_t::ep2_ptr, _ctx_t::ep2_r, ep2_set_infty(), fp2_new, RLC_FP_DIGS, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by pp_map_init().
ep2_curve_clean()
void ep2_curve_clean (void)
Finalizes the elliptic curve over quadratic extension.
Definition at line 296 of file relic_ep2_curve.c.
References bn_clean(), core_get(), _ctx_t::ep2_h, _ctx_t::ep2_pre, _ctx_t::ep2_r, fp2_free, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by pp_map_clean().
ep2_curve_get_a()
void ep2_curve_get_a (fp2_t a)
Returns the 'a' coefficient of the currently configured elliptic curve.
Parameters
[out] a - the 'a' coefficient of the elliptic curve.
Definition at line 317 of file relic_ep2_curve.c.
References core_get(), _ctx_t::ep2_a, and fp_copy().
Referenced by ep2_dbl_basic_imp(), ep2_dbl_projc_imp(), and ep2_rhs().
ep2_curve_get_b()
void ep2_curve_get_b (fp2_t b)
Returns the 'b' coefficient of the currently configured elliptic curve.
Parameters
[out] b - the 'b' coefficient of the elliptic curve.
Definition at line 323 of file relic_ep2_curve.c.
References core_get(), _ctx_t::ep2_b, and fp_copy().
Referenced by ep2_rhs(), pp_dbl_k12_projc_basic(), and pp_dbl_k12_projc_lazyr().
ep2_curve_get_vs()
void ep2_curve_get_vs (bn_t * v)
Returns the vector of coefficients required to perform GLV method.
Parameters
[out] b - the vector of coefficients.
Definition at line 329 of file relic_ep2_curve.c.
References bn_add(), bn_add_dig(), bn_copy(), bn_dbl(), bn_free(), bn_mul_dig(), bn_neg(), bn_null, bn_rsh(), CATCH_ANY, ERR_CAUGHT, FINALLY, fp_prime_get_par(), THROW, and TRY.
Referenced by ep2_mul_glv_imp(), and fp12_exp_cyc().
ep2_curve_opt_a()
int ep2_curve_opt_a (void)
Returns a optimization identifier based on the 'a' coefficient of the curve.
Returns
the optimization identifier.
ep2_curve_is_twist()
int ep2_curve_is_twist (void)
Tests if the configured elliptic curve is a twist.
Returns
the type of the elliptic curve twist, 0 if non-twisted curve.
Definition at line 309 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_is_twist.
Referenced by ep2_frb(), fp12_mul_dxs_basic(), fp12_mul_dxs_lazyr(), pp_add_k12_basic(), pp_add_k12_projc_basic(), pp_add_k12_projc_lazyr(), pp_add_k8_basic(), pp_add_k8_projc_basic(), pp_add_k8_projc_lazyr(), pp_add_lit_k12(), pp_dbl_k12_basic(), pp_dbl_k12_projc_basic(), pp_dbl_k12_projc_lazyr(), pp_dbl_k8_basic(), pp_dbl_k8_projc_basic(), pp_dbl_k8_projc_lazyr(), pp_dbl_k8_projc_lazyr_new(), pp_dbl_k8_projc_new(), and pp_dbl_lit_k12().
ep2_curve_get_gen()
void ep2_curve_get_gen (ep2_t g)
Returns the generator of the group of points in the elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 313 of file relic_ep2_curve.c.
References core_get(), and ep2_copy().
Referenced by ep2_mul_gen(), and ep2_mul_sim_gen().
ep2_curve_get_tab()
ep2_t* ep2_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 391 of file relic_ep2_curve.c.
References core_get(), and _ctx_t::ep2_ptr.
Referenced by ep2_curve_set(), ep2_curve_set_twist(), ep2_mul_gen(), and ep2_mul_sim_gen().
ep2_curve_get_ord()
void ep2_curve_get_ord (bn_t n)
Returns the order of the group of points in the elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 376 of file relic_ep2_curve.c.
References bn_copy(), core_get(), _ctx_t::ep2_is_twist, _ctx_t::ep2_r, and ep_curve_get_ord().
Referenced by ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_glv_imp(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_sim_trick(), ep2_rand(), and fp12_exp_cyc().
ep2_curve_get_cof()
void ep2_curve_get_cof (bn_t h)
Returns the cofactor of the group order in the elliptic curve.
Parameters
[out] h - the returned cofactor.
Definition at line 385 of file relic_ep2_curve.c.
References bn_copy(), and core_get().
Referenced by ep2_map().
ep2_curve_set()
void ep2_curve_set (fp2_t a, fp2_t b, ep2_t g, bn_t r, bn_t h)
Configures an elliptic curve over a quadratic extension by its coefficients.
Parameters
[in] a - the 'a' coefficient of the curve.
[in] b - the 'b' coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
Definition at line 513 of file relic_ep2_curve.c.
References bn_copy(), core_get(), _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_curve_get_tab(), _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_is_twist, ep2_norm(), _ctx_t::ep2_r, and fp_copy().
ep2_curve_set_twist()
void ep2_curve_set_twist (int type)
Configures an elliptic curve by twisting the curve over the base prime field.
Parameters
- the type of twist (multiplicative or divisive)
Definition at line 401 of file relic_ep2_curve.c.
References ASSIGN, B12_P381, B12_P446, B12_P455, B12_P638, bn_copy(), bn_free(), bn_null, BN_P158, BN_P254, BN_P256, BN_P382, BN_P446, BN_P638, CATCH_ANY, core_get(), CP8_P544, _ctx_t::ep2_a, _ctx_t::ep2_b, ep2_copy(), ep2_curve_get_tab(), _ctx_t::ep2_g, _ctx_t::ep2_h, _ctx_t::ep2_is_twist, ep2_null, _ctx_t::ep2_r, EP_DTYPE, EP_MTYPE, ep_param_get(), ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp2_free, fp2_new, fp2_null, fp2_zero(), fp_copy(), fp_prime_calc(), fp_set_dig(), ep2_st::norm, OT8_P511, RLC_FP_BYTES, THROW, TRY, and ep2_st::z.
Referenced by ep_param_set_any_pairf().
ep2_is_infty()
int ep2_is_infty (ep2_t p)
Tests if a point on a elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep2_util.c.
References fp2_is_zero(), and ep2_st::z.
Referenced by ep2_add_basic(), ep2_add_projc(), ep2_add_slp_basic(), ep2_dbl_basic(), ep2_dbl_projc(), ep2_dbl_slp_basic(), ep2_is_valid(), ep2_mul_basic(), ep2_mul_dig(), ep2_mul_lwnaf(), ep2_mul_monty(), ep2_mul_sim_gen(), ep2_mul_sim_inter(), ep2_mul_sim_joint(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_neg_basic(), ep2_neg_projc(), ep2_norm(), ep2_size_bin(), ep2_write_bin(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), pp_map_weilp_k12(), pp_norm_k12(), and pp_norm_k8().
ep2_set_infty()
void ep2_set_infty (ep2_t p)
Assigns a elliptic curve point to a point at the infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep2_util.c.
References fp2_zero(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_add_basic_imp(), ep2_add_projc_imp(), ep2_add_projc_mix(), ep2_curve_init(), ep2_dbl_basic(), ep2_dbl_projc(), ep2_dbl_slp_basic(), ep2_mul_basic(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_ordin(), ep2_mul_gen(), ep2_mul_glv_imp(), ep2_mul_lwnaf(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_sim_dig(), ep2_mul_sim_joint(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_neg_basic(), ep2_neg_projc(), ep2_norm(), ep2_read_bin(), ep2_sub_basic(), ep2_sub_projc(), pp_norm_k12(), and pp_norm_k8().
ep2_copy()
void ep2_copy (ep2_t r, ep2_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the elliptic curve point to copy.
Definition at line 50 of file relic_ep2_util.c.
References fp2_copy(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_add_basic(), ep2_add_projc(), ep2_add_slp_basic(), ep2_cmp(), ep2_curve_get_gen(), ep2_curve_set_twist(), ep2_frb(), ep2_mul_basic(), ep2_mul_dig(), ep2_mul_fix_combs(), ep2_mul_monty(), ep2_mul_pre_basic(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_ordin(), ep2_mul_sim_joint(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_norm(), ep2_tab(), pp_add_k12_basic(), pp_add_k8_basic(), pp_dbl_k12_basic(), pp_dbl_k8_basic(), pp_mil_k12(), pp_mil_k8(), pp_norm_k12(), and pp_norm_k8().
ep2_cmp()
int ep2_cmp (ep2_t p, ep2_t q)
Compares two elliptic curve points.
Parameters
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 57 of file relic_ep2_util.c.
References CATCH_ANY, ep2_copy(), ep2_norm(), ep2_null, ERR_CAUGHT, FINALLY, fp2_cmp(), ep2_st::norm, result, RLC_EQ, RLC_NE, THROW, TRY, ep2_st::x, ep2_st::y, and ep2_st::z.
ep2_rand()
void ep2_rand (ep2_t p)
Assigns a random value to an elliptic curve point.
Parameters
[out] p - the elliptic curve point to assign.
Definition at line 110 of file relic_ep2_util.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, ep2_curve_get_ord(), ep2_mul_gen(), ERR_CAUGHT, FINALLY, THROW, and TRY.
ep2_rhs()
void ep2_rhs (fp2_t rhs, ep2_t p)
Computes the right-hand side of the elliptic curve equation at a certain elliptic curve point.
Parameters
[out] rhs - the result.
[in] p - the point.
Definition at line 134 of file relic_ep2_util.c.
References CATCH_ANY, ep2_curve_get_a(), ep2_curve_get_b(), ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_new, fp2_null, THROW, TRY, and ep2_st::x.
Referenced by ep2_is_valid(), ep2_map(), and ep2_upk().
ep2_is_valid()
int ep2_is_valid (ep2_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 168 of file relic_ep2_util.c.
References CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, ep2_rhs(), ERR_CAUGHT, FINALLY, fp2_cmp(), RLC_EQ, THROW, TRY, ep2_st::x, and ep2_st::y.
ep2_tab()
void ep2_tab (ep2_t * t, ep2_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 191 of file relic_ep2_util.c.
References ep2_copy(), ep2_norm(), and ep2_norm_sim().
Referenced by ep2_mul_naf_imp(), and ep2_mul_sim_plain().
ep2_print()
void ep2_print (ep2_t p)
Prints a elliptic curve point.
Parameters
[in] p - the elliptic curve point to print.
Definition at line 208 of file relic_ep2_util.c.
References fp2_print(), ep2_st::x, ep2_st::y, and ep2_st::z.
ep2_size_bin()
int ep2_size_bin (ep2_t a, int pack)
Returns the number of bytes necessary to store a prime elliptic curve point over a quadratic extension with optional point compression.
Parameters
[in] a - the prime field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 214 of file relic_ep2_util.c.
References CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, ERR_CAUGHT, FINALLY, RLC_FP_BYTES, THROW, and TRY.
ep2_read_bin()
void ep2_read_bin (ep2_t a, const uint8_t * bin, int len)
Reads a prime elliptic curve point over a quadratic extension from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 242 of file relic_ep2_util.c.
References ep2_set_infty(), ep2_upk(), ERR_NO_BUFFER, ERR_NO_VALID, fp2_read_bin(), fp2_zero(), fp_set_bit(), fp_set_dig(), fp_zero(), ep2_st::norm, RLC_FP_BYTES, THROW, ep2_st::x, ep2_st::y, and ep2_st::z.
ep2_write_bin()
void ep2_write_bin (uint8_t * bin, int len, ep2_t a, int pack)
Writes a prime elliptic curve pointer over a quadratic extension to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime elliptic curve point to write.
[in] pack - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 288 of file relic_ep2_util.c.
References CATCH_ANY, ep2_is_infty(), ep2_norm(), ep2_null, ep2_pck(), ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, fp2_write_bin(), fp_get_bit(), RLC_FP_BYTES, THROW, TRY, ep2_st::x, and ep2_st::y.
ep2_neg_basic()
void ep2_neg_basic (ep2_t r, ep2_t p)
Negates a point represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 41 of file relic_ep2_neg.c.
References ep2_is_infty(), ep2_set_infty(), fp2_copy(), fp2_neg(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_sub_basic().
ep2_neg_projc()
void ep2_neg_projc (ep2_t r, ep2_t p)
Negates a point represented in projective coordinates in an elliptic curve over a quadratic exyension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 61 of file relic_ep2_neg.c.
References ep2_is_infty(), ep2_set_infty(), fp2_copy(), fp2_neg(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_sub_projc().
ep2_add_basic()
void ep2_add_basic (ep2_t r, ep2_t p, ep2_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 358 of file relic_ep2_add.c.
References ep2_add_basic_imp(), ep2_copy(), and ep2_is_infty().
Referenced by ep2_sub_basic().
ep2_add_slp_basic()
void ep2_add_slp_basic (ep2_t r, fp2_t s, ep2_t p, ep2_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quadratic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 372 of file relic_ep2_add.c.
References ep2_add_basic_imp(), ep2_copy(), and ep2_is_infty().
Referenced by pp_add_k12_basic(), and pp_add_k8_basic().
ep2_sub_basic()
void ep2_sub_basic (ep2_t r, ep2_t p, ep2_t q)
Subtracts a points represented in affine coordinates in an elliptic curve over a quadratic extension from another point.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 386 of file relic_ep2_add.c.
References CATCH_ANY, ep2_add_basic(), ep2_neg_basic(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, ep2_st::norm, THROW, and TRY.
ep2_add_projc()
void ep2_add_projc (ep2_t r, ep2_t p, ep2_t q)
Adds two points represented in projective coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 416 of file relic_ep2_add.c.
References ep2_add_projc_imp(), ep2_copy(), and ep2_is_infty().
Referenced by ep2_sub_projc().
ep2_sub_projc()
void ep2_sub_projc (ep2_t r, ep2_t p, ep2_t q)
Subtracts a points represented in projective coordinates in an elliptic curve over a quadratic extension from another point.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 436 of file relic_ep2_add.c.
References CATCH_ANY, ep2_add_projc(), ep2_neg_projc(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
ep2_dbl_basic()
void ep2_dbl_basic (ep2_t r, ep2_t p)
Doubles a points represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[int] p - the point to double.
Definition at line 247 of file relic_ep2_dbl.c.
References ep2_dbl_basic_imp(), ep2_is_infty(), and ep2_set_infty().
ep2_dbl_slp_basic()
void ep2_dbl_slp_basic (ep2_t r, fp2_t s, ep2_t p)
Doubles a points represented in affine coordinates in an elliptic curve over a quadratic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 256 of file relic_ep2_dbl.c.
References ep2_dbl_basic_imp(), ep2_is_infty(), and ep2_set_infty().
Referenced by ep2_add_basic_imp(), pp_dbl_k12_basic(), and pp_dbl_k8_basic().
ep2_dbl_projc()
void ep2_dbl_projc (ep2_t r, ep2_t p)
Doubles a points represented in projective coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 269 of file relic_ep2_dbl.c.
References ep2_dbl_projc_imp(), ep2_is_infty(), and ep2_set_infty().
Referenced by ep2_add_projc_imp(), and ep2_add_projc_mix().
ep2_mul_basic()
void ep2_mul_basic (ep2_t r, ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 273 of file relic_ep2_mul.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ep2_copy(), ep2_is_infty(), ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, RLC_NEG, THROW, and TRY.
Referenced by ep2_map(), ep2_mul_cof_b12(), and ep2_mul_cof_bn().
ep2_mul_slide()
void ep2_mul_slide (ep2_t r, ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 319 of file relic_ep2_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), CATCH_ANY, ep2_copy(), ep2_is_infty(), ep2_norm(), ep2_norm_sim(), ep2_null, ep2_set_infty(), EP_WIDTH, ERR_CAUGHT, FINALLY, RLC_FP_BITS, RLC_NEG, THROW, TRY, and util_bits_dig().
ep2_mul_monty()
void ep2_mul_monty (ep2_t r, ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the constant-time Montgomery laddering point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 389 of file relic_ep2_mul.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, dv_swap_cond(), ep2_copy(), ep2_is_infty(), ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, RLC_FP_DIGS, RLC_NEG, THROW, and TRY.
ep2_mul_lwnaf()
void ep2_mul_lwnaf (ep2_t r, ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 442 of file relic_ep2_mul.c.
References bn_is_zero(), ep2_is_infty(), ep2_mul_glv_imp(), ep2_mul_naf_imp(), ep2_set_infty(), and ep_curve_is_endom().
ep2_mul_lwreg()
void ep2_mul_lwreg (ep2_t r, ep2_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
ep2_mul_gen()
void ep2_mul_gen (ep2_t r, bn_t k)
Multiplies the generator of an elliptic curve over a qaudratic extension.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 462 of file relic_ep2_mul.c.
References bn_is_zero(), CATCH_ANY, ep2_curve_get_gen(), ep2_curve_get_tab(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by ep2_mul_sim_gen(), and ep2_rand().
ep2_mul_dig()
void ep2_mul_dig (ep2_t r, ep2_t p, dig_t k)
Multiplies a prime elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 489 of file relic_ep2_mul.c.
References CATCH_ANY, ep2_copy(), ep2_is_infty(), ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, THROW, TRY, and util_bits_dig().
Referenced by ep2_map().
ep2_mul_pre_basic()
void ep2_mul_pre_basic (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 120 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free(), bn_null, CATCH_ANY, ep2_copy(), ep2_curve_get_ord(), ERR_CAUGHT, FINALLY, THROW, and TRY.
ep2_mul_pre_yaowi()
void ep2_mul_pre_yaowi (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ep2_mul_pre_nafwi()
void ep2_mul_pre_nafwi (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ep2_mul_pre_combs()
void ep2_mul_pre_combs (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 166 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free(), bn_null, CATCH_ANY, ep2_copy(), ep2_curve_get_ord(), ep2_norm(), ep2_set_infty(), EP_DEPTH, ERR_CAUGHT, FINALLY, RLC_EP_TABLE_COMBS, THROW, and TRY.
ep2_mul_pre_combd()
void ep2_mul_pre_combd (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 272 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free(), bn_null, CATCH_ANY, ep2_copy(), ep2_curve_get_ord(), ep2_norm(), ep2_set_infty(), EP_DEPTH, ERR_CAUGHT, FINALLY, RLC_EP_TABLE_COMBD, THROW, and TRY.
ep2_mul_pre_lwnaf()
void ep2_mul_pre_lwnaf (ep2_t * t, ep2_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 385 of file relic_ep2_mul_fix.c.
References ep2_mul_pre_ordin().
ep2_mul_fix_basic()
void ep2_mul_fix_basic (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 143 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ep2_norm(), ep2_set_infty(), and RLC_NEG.
ep2_mul_fix_yaowi()
void ep2_mul_fix_yaowi (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ep2_mul_fix_nafwi()
void ep2_mul_fix_nafwi (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ep2_mul_fix_combs()
void ep2_mul_fix_combs (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 208 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free(), bn_get_bit(), bn_is_zero(), bn_null, bn_sign(), CATCH_ANY, ep2_copy(), ep2_curve_get_ord(), ep2_norm(), ep2_set_infty(), EP_DEPTH, ERR_CAUGHT, FINALLY, RLC_NEG, THROW, and TRY.
ep2_mul_fix_combd()
void ep2_mul_fix_combd (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 321 of file relic_ep2_mul_fix.c.
References bn_bits(), bn_free(), bn_get_bit(), bn_is_zero(), bn_null, bn_sign(), CATCH_ANY, ep2_curve_get_ord(), ep2_norm(), ep2_set_infty(), EP_DEPTH, ERR_CAUGHT, FINALLY, RLC_NEG, THROW, and TRY.
ep2_mul_fix_lwnaf()
void ep2_mul_fix_lwnaf (ep2_t r, ep2_t * t, bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 389 of file relic_ep2_mul_fix.c.
References ep2_mul_fix_ordin().
ep2_mul_sim_basic()
void ep2_mul_sim_basic (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 144 of file relic_ep2_mul_sim.c.
References CATCH_ANY, ep2_norm(), ep2_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
ep2_mul_sim_trick()
void ep2_mul_sim_trick (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 168 of file relic_ep2_mul_sim.c.
References bn_free(), bn_is_zero(), bn_null, bn_rec_win(), bn_sign(), CATCH_ANY, ep2_copy(), ep2_curve_get_ord(), ep2_is_infty(), ep2_norm(), ep2_norm_sim(), ep2_null, ep2_set_infty(), EP_WIDTH, ERR_CAUGHT, FINALLY, RLC_CEIL, RLC_FP_BITS, RLC_MAX, RLC_NEG, THROW, and TRY.
ep2_mul_sim_inter()
void ep2_mul_sim_inter (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 268 of file relic_ep2_mul_sim.c.
References bn_is_zero(), ep2_is_infty(), and ep2_mul_sim_plain().
ep2_mul_sim_joint()
void ep2_mul_sim_joint (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 295 of file relic_ep2_mul_sim.c.
References bn_bits(), bn_is_zero(), bn_rec_jsf(), bn_sign(), CATCH_ANY, ep2_copy(), ep2_is_infty(), ep2_norm(), ep2_norm_sim(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, THROW, and TRY.
ep2_mul_sim_gen()
void ep2_mul_sim_gen (ep2_t r, bn_t k, ep2_t q, bn_t m)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = kG + lQ.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 368 of file relic_ep2_mul_sim.c.
References bn_is_zero(), CATCH_ANY, ep2_curve_get_gen(), ep2_curve_get_tab(), ep2_is_infty(), ep2_mul_gen(), ep2_mul_sim_plain(), ep2_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
ep2_mul_sim_dig()
void ep2_mul_sim_dig (ep2_t r, ep2_t p[], dig_t k[], int len)
Multiplies prime elliptic curve points by small scalars. Computes R = \sum k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the small scalars.
[in] len - the number of points to multiply.
Definition at line 400 of file relic_ep2_mul_sim.c.
References CATCH_ANY, ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, RLC_MAX, THROW, TRY, and util_bits_dig().
ep2_norm()
void ep2_norm (ep2_t r, ep2_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 88 of file relic_ep2_norm.c.
References ep2_copy(), ep2_is_infty(), ep2_norm_imp(), ep2_set_infty(), and ep2_st::norm.
Referenced by ep2_cmp(), ep2_curve_set(), ep2_is_valid(), ep2_mul_basic(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_mul_fix_basic(), ep2_mul_fix_combd(), ep2_mul_fix_combs(), ep2_mul_fix_ordin(), ep2_mul_glv_imp(), ep2_mul_monty(), ep2_mul_naf_imp(), ep2_mul_pre_combd(), ep2_mul_pre_combs(), ep2_mul_pre_ordin(), ep2_mul_sim_basic(), ep2_mul_sim_dig(), ep2_mul_sim_joint(), ep2_mul_sim_plain(), ep2_mul_sim_trick(), ep2_mul_slide(), ep2_size_bin(), ep2_tab(), ep2_write_bin(), pp_map_oatep_k12(), pp_map_oatep_k8(), pp_map_sim_oatep_k12(), pp_map_sim_tatep_k12(), pp_map_sim_weilp_k12(), pp_map_tatep_k12(), and pp_map_weilp_k12().
ep2_norm_sim()
void ep2_norm_sim (ep2_t * r, ep2_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 103 of file relic_ep2_norm.c.
References CATCH_ANY, ep2_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp2_copy(), fp2_free, fp2_inv_sim(), fp2_new, fp2_null, RLC_ALLOCA, RLC_FREE, THROW, and TRY.
Referenced by ep2_mul_sim_joint(), ep2_mul_sim_trick(), ep2_mul_slide(), and ep2_tab().
ep2_map()
void ep2_map (ep2_t p, const uint8_t * msg, int len)
Maps a byte array to a point in an elliptic curve over a quadratic extension.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 152 of file relic_ep2_map.c.
References bn_bits(), bn_free(), bn_null, bn_read_bin(), CATCH_ANY, bn_st::dp, ep2_curve_get_cof(), ep2_mul_basic(), ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_dig(), ep2_rhs(), EP_B12, EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, fp2_srt(), fp_add_dig(), fp_prime_conv(), fp_set_dig(), fp_zero(), ep2_st::norm, RLC_DIG, RLC_FP_BYTES, RLC_MIN, THROW, TRY, ep2_st::x, ep2_st::y, and ep2_st::z.
ep2_frb()
void ep2_frb (ep2_t r, ep2_t p, int i)
Computes a power of the Gailbraith-Lin-Scott homomorphism of a point represented in affine coordinates on a twisted elliptic curve over a quadratic exension. That is, Psi^i(P) = Twist(P)(Frob^i(unTwist(P)). On the trace-zero group of a quadratic twist, consists of a power of the Frobenius map of a point represented in affine coordinates in an elliptic curve over a quadratic exension. Computes Frob^i(P) = (p^i)P.
Parameters
[out] r - the result in affine coordinates.
[in] p - a point in affine coordinates.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_ep2_frb.c.
References ep2_copy(), ep2_curve_is_twist(), EP_MTYPE, fp2_frb(), fp2_mul_art(), fp2_mul_frb(), ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_mul_cof_b12(), ep2_mul_cof_bn(), ep2_mul_glv_imp(), g2_is_valid(), and pp_fin_k12_oatep().
ep2_pck()
void ep2_pck (ep2_t r, ep2_t p)
Compresses a point in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to compress.
Definition at line 39 of file relic_ep2_pck.c.
References fp2_copy(), fp2_zero(), fp_get_bit(), fp_set_bit(), fp_set_dig(), fp_zero(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_write_bin().
ep2_upk()
int ep2_upk (ep2_t r, ep2_t p)
Decompresses a point in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
if the decompression was successful
Definition at line 50 of file relic_ep2_pck.c.
References CATCH_ANY, ep2_rhs(), ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_neg(), fp2_new, fp2_null, fp2_srt(), fp_get_bit(), fp_set_dig(), fp_zero(), ep2_st::norm, result, THROW, TRY, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_read_bin().