RELIC: src/fb/relic_fb_poly.c File Reference
relic_fb_poly.c File Reference
Binary field arithmetic
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_dv.h"
#include "relic_fb.h"
#include "relic_fb_low.h"
Functions
static void find_trace (void)
static void find_solve (void)
static void find_srz (void)
static void find_chain (void)
static void fb_poly_set (const fb_t f)
void fb_poly_init (void)
void fb_poly_clean (void)
dig_t * fb_poly_get (void)
void fb_poly_add (fb_t c, const fb_t a)
void fb_poly_set_dense (const fb_t f)
void fb_poly_set_trino (int a)
void fb_poly_set_penta (int a, int b, int c)
dig_t * fb_poly_get_srz (void)
const fb_t * fb_poly_tab_sqr (int i)
const dig_t * fb_poly_tab_srz (int i)
void fb_poly_get_trc (int *a, int *b, int *c)
void fb_poly_get_rdc (int *a, int *b, int *c)
const dig_t * fb_poly_get_slv (void)
const int * fb_poly_get_chain (int *len)
Detailed Description
Implementation of the binary field modulus manipulation.
Definition in file relic_fb_poly.c.
Function Documentation
find_trace()
static void find_trace (void) static
Find non-zero bits for fast trace computation.
Exceptions
ERR_NO_MEMORY if there is no available memory.
ERR_NO_VALID if the polynomial is invalid.
Definition at line 54 of file relic_fb_poly.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, ERR_NO_VALID, fb_add(), fb_copy(), fb_is_zero(), fb_null, fb_set_bit(), _ctx_t::fb_ta, _ctx_t::fb_tb, _ctx_t::fb_tc, fb_zero(), FINALLY, RLC_FB_BITS, THROW, and TRY.
Referenced by fb_poly_set().
find_solve()
static void find_solve (void) static
Precomputes half-traces for z^i with odd i.
Exceptions
ERR_NO_MEMORY if there is no available memory.
Definition at line 116 of file relic_fb_poly.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, fb_add(), fb_copy(), _ctx_t::fb_half, fb_null, fb_rsh(), fb_set_bit(), fb_zero(), FINALLY, RLC_FB_BITS, THROW, and TRY.
Referenced by fb_poly_set().
find_srz()
static void find_srz (void) static
Precomputes the square root of z.
Definition at line 160 of file relic_fb_poly.c.
References core_get(), fb_mul_dig(), fb_set_dig(), _ctx_t::fb_srz, _ctx_t::fb_tab_srz, and RLC_FB_BITS.
Referenced by fb_poly_set().
find_chain()
static void find_chain (void) static
Finds an addition chain for (RLC_FB_BITS - 1).
Definition at line 183 of file relic_fb_poly.c.
References _ctx_t::chain, _ctx_t::chain_len, core_get(), fb_poly_tab_sqr(), _ctx_t::fb_tab_ptr, _ctx_t::fb_tab_sqr, RLC_FB_BITS, RLC_FB_TABLE, and RLC_TERMS.
Referenced by fb_poly_set().
fb_poly_set()
static void fb_poly_set (const fb_t f) static
Configures the irreducible polynomial of the binary field.
Parameters
[in] f - the new irreducible polynomial.
Definition at line 300 of file relic_fb_poly.c.
References core_get(), fb_copy(), find_chain(), find_solve(), find_srz(), and find_trace().
Referenced by fb_poly_set_dense(), fb_poly_set_penta(), and fb_poly_set_trino().
fb_poly_init()
void fb_poly_init (void)
Reduces a multiple precision integer modulo another integer. This macro should not be called directly. Use bn_mod() with 4 arguments instead.
Parameters
[out] C - the result.
[in] A - the binary field element to exponentiate.
[in] B - the exponent.
[in] T - the precomputed table for the exponent. Initializes the binary field arithmetic layer.
Definition at line 320 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, _ctx_t::fb_poly, and fb_zero().
Referenced by core_init().
fb_poly_clean()
void fb_poly_clean (void)
Finalizes the binary field arithmetic layer.
Definition at line 328 of file relic_fb_poly.c.
Referenced by core_clean().
fb_poly_get()
dig_t* fb_poly_get (void)
Returns the irreducible polynomial f(z) configured for the binary field.
Returns
the irreducible polynomial.
Definition at line 331 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_poly.
Referenced by fb_inv_almos(), fb_inv_binar(), fb_inv_bruch(), fb_inv_ctaia(), fb_inv_exgcd(), and fb_rdc_basic().
fb_poly_add()
void fb_poly_add (fb_t c, const fb_t a)
Adds a binary field element and the irreducible polynomial. Computes c = a + f(z).
Parameters
[out] c - the destination.
[in] a - the binary field element.
Definition at line 335 of file relic_fb_poly.c.
References core_get(), fb_add(), fb_copy(), _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, _ctx_t::fb_poly, and RLC_FB_DIGS.
Referenced by fb_inv_almos(), fb_inv_binar(), fb_inv_ctaia(), and fb_mul_basic().
fb_poly_set_dense()
void fb_poly_set_dense (const fb_t f)
Configures the irreducible polynomial of the binary field as a dense polynomial.
Parameters
[in] f - the new irreducible polynomial.
Definition at line 363 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, and fb_poly_set().
fb_poly_set_trino()
void fb_poly_set_trino (int a)
Configures a trinomial as the irreducible polynomial by its non-zero coefficients. The other coefficients are RLC_FB_BITS and 0.
Parameters
[in] a - the second coefficient.
Definition at line 370 of file relic_fb_poly.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, fb_null, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, fb_poly_set(), fb_set_bit(), fb_zero(), FINALLY, RLC_DIG_LOG, RLC_FB_BITS, THROW, and TRY.
Referenced by fb_param_set().
fb_poly_set_penta()
void fb_poly_set_penta (int a, int b, int c)
Configures a pentanomial as the binary field modulo by its non-zero coefficients. The other coefficients are RLC_FB_BITS and 0.
Parameters
[in] a - the second coefficient.
[in] b - the third coefficient.
[in] c - the fourth coefficient.
Definition at line 398 of file relic_fb_poly.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, _ctx_t::fb_na, _ctx_t::fb_nb, _ctx_t::fb_nc, fb_null, _ctx_t::fb_pa, _ctx_t::fb_pb, _ctx_t::fb_pc, fb_poly_set(), fb_set_bit(), fb_zero(), FINALLY, RLC_DIG_LOG, RLC_FB_BITS, THROW, and TRY.
Referenced by fb_param_set().
fb_poly_get_srz()
dig_t* fb_poly_get_srz (void)
Returns the square root of z.
Returns
the square root of z.
Definition at line 431 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_srz.
fb_poly_tab_sqr()
const fb_t* fb_poly_tab_sqr (int i)
Returns a table for accelerating repeated squarings.
Parameters
the number of the table.
Returns
the precomputed result.
Definition at line 439 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_tab_ptr.
Referenced by fb_inv_itoht(), and find_chain().
fb_poly_tab_srz()
const dig_t* fb_poly_tab_srz (int i)
Returns sqrt(z) * (i represented as a polynomial).
Returns
the precomputed result.
Definition at line 453 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_tab_srz.
fb_poly_get_trc()
void fb_poly_get_trc (int * a, int * b, int * c)
Returns the non-zero bits used to compute the trace function. The -1 coefficient is the last coefficient.
Parameters
[out] a - the first coefficient.
[out] b - the second coefficient.
[out] c - the third coefficient.
Definition at line 467 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_ta, _ctx_t::fb_tb, and _ctx_t::fb_tc.
fb_poly_get_rdc()
void fb_poly_get_rdc (int * a, int * b, int * c)
Returns the non-zero coefficients of the configured trinomial or pentanomial. If b is -1, the irreducible polynomial configured is a trinomial. The other coefficients are RLC_FB_BITS and 0.
Parameters
[out] a - the second coefficient.
[out] b - the third coefficient.
[out] c - the fourth coefficient.
Definition at line 478 of file relic_fb_poly.c.
References core_get(), _ctx_t::fb_pa, _ctx_t::fb_pb, and _ctx_t::fb_pc.
Referenced by fb_param_print().
fb_poly_get_slv()
const dig_t* fb_poly_get_slv (void)
Returns the table of precomputed half-traces.
Returns
the table of half-traces.
Definition at line 485 of file relic_fb_poly.c.
References core_get(), and _ctx_t::fb_half.
fb_poly_get_chain()
const int* fb_poly_get_chain (int * len)
Returns an addition chain for (RLC_FB_BITS - 1).
Parameters
[out] len - the number of elements in the addition chain.
Returns
a pointer to the addition chain.
Definition at line 493 of file relic_fb_poly.c.
References _ctx_t::chain, _ctx_t::chain_len, core_get(), and RLC_TERMS.
Referenced by fb_inv_itoht().