RELIC: src/pp/relic_pp_map_k16.c File Reference
relic_pp_map_k16.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_mil_k16 (fp16_t r, ep4_t *t, ep4_t *q, ep_t *p, int m, bn_t a)
static void pp_mil_lit_k16 (fp16_t r, ep_t *t, ep_t *p, ep4_t *q, int m, bn_t a)
static void pp_fin_k16_oatep (fp16_t r, ep4_t t, const ep4_t q, const ep_t p)
void pp_map_tatep_k16 (fp16_t r, const ep_t p, const ep4_t q)
void pp_map_sim_tatep_k16 (fp16_t r, const ep_t *p, const ep4_t *q, int m)
void pp_map_weilp_k16 (fp16_t r, const ep_t p, const ep4_t q)
void pp_map_sim_weilp_k16 (fp16_t r, const ep_t *p, const ep4_t *q, int m)
void pp_map_oatep_k16 (fp16_t r, const ep_t p, const ep4_t q)
void pp_map_sim_oatep_k16 (fp16_t r, const ep_t *p, const ep4_t *q, int m)
Detailed Description
Implementation of pairing computation for curves with embedding degree 16.
Definition in file relic_pp_map_k16.c.
Function Documentation
pp_mil_k16()
static void pp_mil_k16 (fp16_t r, ep4_t * t, ep4_t * q, ep_t * p, int m, bn_t a) static
Compute the Miller loop for pairings of type G_2 x G_1 over the bits of a given parameter represented in sparse form.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] q - the vector of first arguments in affine coordinates.
[in] p - the vector of second arguments in affine coordinates.
[in] n - the number of pairings to evaluate.
[in] a - the loop parameter.
Definition at line 51 of file relic_pp_map_k16.c.
References bn_bits(), bn_rec_naf(), ep4_copy(), ep4_free, ep4_neg(), ep4_new, ep4_null, ep_free, ep_neg(), ep_new, ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp16_free, fp16_mul_dxs, fp16_new, fp16_null, fp16_sqr, fp16_zero(), fp_copy(), fp_neg, pp_add_k16, pp_dbl_k16, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by pp_map_oatep_k16(), pp_map_sim_oatep_k16(), pp_map_sim_weilp_k16(), and pp_map_weilp_k16().
pp_mil_lit_k16()
static void pp_mil_lit_k16 (fp16_t r, ep_t * t, ep_t * p, ep4_t * q, int m, bn_t a) static
Compute the Miller loop for pairings of type G_1 x G_2 over the bits of a given parameter.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] p - the first pairing argument in affine coordinates.
[in] q - the second pairing argument in affine coordinates.
[in] n - the number of pairings to evaluate.
[in] a - the loop parameter.
Definition at line 147 of file relic_pp_map_k16.c.
References bn_bits(), bn_get_bit(), ep4_free, ep4_neg(), ep4_new, ep4_null, ep_copy(), ERR_CAUGHT, ERR_NO_MEMORY, fp16_free, fp16_mul, fp16_new, fp16_null, fp16_sqr, fp16_zero(), pp_add_lit_k16(), pp_dbl_lit_k16(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
Referenced by pp_map_sim_tatep_k16(), pp_map_sim_weilp_k16(), pp_map_tatep_k16(), and pp_map_weilp_k16().
pp_fin_k16_oatep()
static void pp_fin_k16_oatep (fp16_t r, ep4_t t, const ep4_t q, const ep_t p) static
Compute the final lines for optimal ate pairings.
Parameters
[out] r - the result.
[out] t - the resulting point.
[in] q - the first point of the pairing, in G_2.
[in] p - the second point of the pairing, in G_1.
[in] a - the loop parameter.
Definition at line 201 of file relic_pp_map_k16.c.
References ep4_frb(), ep4_free, ep4_new, ep4_null, ep_free, ep_neg(), ep_new, ep_null, ERR_CAUGHT, fp16_frb(), fp16_free, fp16_mul_dxs, fp16_new, fp16_null, fp16_zero(), fp_copy(), fp_neg, pp_add_k16, pp_dbl_k16, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by pp_map_oatep_k16(), and pp_map_sim_oatep_k16().
pp_map_tatep_k16()
void pp_map_tatep_k16 (fp16_t r, const ep_t p, const ep4_t q)
Computes the Tate pairing of two points in a parameterized elliptic curve with embedding degree 16.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 249 of file relic_pp_map_k16.c.
References bn_free, bn_new, bn_null, ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp16_set_dig(), pp_exp_k16(), pp_mil_lit_k16(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_tatep_k16()
void pp_map_sim_tatep_k16 (fp16_t r, const ep_t * p, const ep4_t * q, int m)
Computes the Tate multi-pairing in a parameterized elliptic curve with embedding degree 16.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 286 of file relic_pp_map_k16.c.
References bn_free, bn_new, bn_null, ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp16_set_dig(), pp_exp_k16(), pp_mil_lit_k16(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_weilp_k16()
void pp_map_weilp_k16 (fp16_t r, const ep_t p, const ep4_t q)
Computes the Weil pairing of two points in a parameterized elliptic curve with embedding degree 16.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 344 of file relic_pp_map_k16.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp16_free, fp16_inv(), fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, fp16_set_dig(), fp16_sqr, pp_mil_k16(), pp_mil_lit_k16(), RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_map_sim_weilp_k16()
void pp_map_sim_weilp_k16 (fp16_t r, const ep_t * p, const ep4_t * q, int m)
Computes the Weil multi-pairing in a parameterized elliptic curve with embedding degree 16.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 400 of file relic_pp_map_k16.c.
References bn_free, bn_new, bn_null, bn_sub_dig(), ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep_curve_get_ord(), ep_free, ep_is_infty(), ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp16_free, fp16_inv(), fp16_inv_cyc(), fp16_mul, fp16_new, fp16_null, fp16_set_dig(), fp16_sqr, pp_mil_k16(), pp_mil_lit_k16(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
pp_map_oatep_k16()
void pp_map_oatep_k16 (fp16_t r, const ep_t p, const ep4_t q)
Computes the optimal ate pairing of two points in a parameterized elliptic curve with embedding degree 16.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 477 of file relic_pp_map_k16.c.
References bn_free, bn_new, bn_null, bn_sign(), ep4_free, ep4_is_infty(), ep4_neg(), ep4_new, ep4_norm(), ep4_null, EP_AFG16, ep_curve_is_pairf(), EP_FM16, ep_free, ep_is_infty(), EP_K16, ep_new, ep_norm(), ep_null, ERR_CAUGHT, fp16_frb(), fp16_inv_cyc(), fp16_set_dig(), fp_prime_get_par(), pp_exp_k16(), pp_fin_k16_oatep(), pp_mil_k16(), RLC_CATCH_ANY, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
pp_map_sim_oatep_k16()
void pp_map_sim_oatep_k16 (fp16_t r, const ep_t * p, const ep4_t * q, int m)
Computes the optimal ate multi-pairing in a parameterized elliptic curve with embedding degree 16.
Parameters
[out] r - the result.
[in] q - the first pairing arguments.
[in] p - the second pairing arguments.
[in] m - the number of pairings to evaluate.
Definition at line 538 of file relic_pp_map_k16.c.
References bn_free, bn_new, bn_null, bn_sign(), ep4_free, ep4_is_infty(), ep4_neg(), ep4_new, ep4_norm(), ep4_null, EP_AFG16, ep_curve_is_pairf(), EP_FM16, ep_free, ep_is_infty(), EP_K16, ep_new, ep_norm(), ep_null, ERR_CAUGHT, ERR_NO_MEMORY, fp16_frb(), fp16_inv_cyc(), fp16_set_dig(), fp_prime_get_par(), pp_exp_k16(), pp_fin_k16_oatep(), pp_mil_k16(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.