RELIC: include/relic_ed.h File Reference
relic_ed.h File Reference
Edwards curves over Edwards fields
#include "relic_fp.h"
#include "relic_bn.h"
#include "relic_types.h"
#include "relic_label.h"
Data Structures
struct ed_st
Macros
#define RLC_ED_TABLE_BASIC (RLC_FP_BITS + 1)
#define RLC_ED_TABLE_COMBS (1 << ED_DEPTH)
#define RLC_ED_TABLE_COMBD (1 << (ED_DEPTH + 1))
#define RLC_ED_TABLE_LWNAF (1 << (ED_DEPTH - 2))
#define RLC_ED_TABLE_MAX RLC_MAX(RLC_ED_TABLE_BASIC, RLC_ED_TABLE_COMBD)
#define ed_null(A) A = NULL;
Typedefs
typedef ed_st * ed_t
Enumerations
enum { CURVE_ED25519 = 1 }
Functions
void ed_param_set (int param)
int ed_param_set_any (void)
int ed_param_get (void)
void ed_curve_get_ord (bn_t r)
void ed_curve_get_gen (ed_t g)
const ed_t * ed_curve_get_tab (void)
void ed_curve_get_cof (bn_t h)
void ed_param_print (void)
int ed_param_level (void)
void ed_rand (ed_t p)
void ed_rhs (fp_t rhs, const ed_t p)
void ed_copy (ed_t r, const ed_t p)
int ed_cmp (const ed_t p, const ed_t q)
void ed_set_infty (ed_t p)
int ed_is_infty (const ed_t p)
void ed_neg_basic (ed_t r, const ed_t p)
void ed_neg_projc (ed_t r, const ed_t p)
void ed_add_basic (ed_t r, const ed_t p, const ed_t q)
void ed_add_projc (ed_t r, const ed_t p, const ed_t q)
void ed_add_extnd (ed_t r, const ed_t p, const ed_t q)
void ed_sub_basic (ed_t r, const ed_t p, const ed_t q)
void ed_sub_projc (ed_t r, const ed_t p, const ed_t q)
void ed_sub_extnd (ed_t r, const ed_t p, const ed_t q)
void ed_dbl_basic (ed_t r, const ed_t p)
void ed_dbl_projc (ed_t r, const ed_t p)
void ed_dbl_extnd (ed_t r, const ed_t p)
void ed_norm (ed_t r, const ed_t p)
void ed_norm_sim (ed_t *r, const ed_t *t, int n)
void ed_map (ed_t p, const uint8_t *msg, int len)
void ed_curve_init (void)
void ed_curve_clean (void)
void ed_mul_pre_basic (ed_t *t, const ed_t p)
void ed_mul_pre_yaowi (ed_t *t, const ed_t p)
void ed_mul_pre_nafwi (ed_t *t, const ed_t p)
void ed_mul_pre_combs (ed_t *t, const ed_t p)
void ed_mul_pre_combd (ed_t *t, const ed_t p)
void ed_mul_pre_lwnaf (ed_t *t, const ed_t p)
void ed_mul_fix_basic (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_fix_yaowi (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_fix_nafwi (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_fix_combs (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_fix_combd (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_fix_lwnaf (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_fix_lwnaf_mixed (ed_t r, const ed_t *t, const bn_t k)
void ed_mul_gen (ed_t r, const bn_t k)
void ed_mul_dig (ed_t r, const ed_t p, dig_t k)
void ed_mul_sim_basic (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_trick (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_inter (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_joint (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
void ed_mul_sim_gen (ed_t r, const bn_t k, const ed_t q, const bn_t m)
void ed_tab (ed_t *t, const ed_t p, int w)
void ed_print (const ed_t p)
int ed_is_valid (const ed_t p)
int ed_size_bin (const ed_t a, int pack)
void ed_read_bin (ed_t a, const uint8_t *bin, int len)
void ed_write_bin (uint8_t *bin, int len, const ed_t a, int pack)
void ed_mul_basic (ed_t r, const ed_t p, const bn_t k)
void ed_mul_slide (ed_t r, const ed_t p, const bn_t k)
void ed_mul_monty (ed_t r, const ed_t p, const bn_t k)
void ed_mul_lwnaf (ed_t r, const ed_t p, const bn_t k)
void ed_mul_lwreg (ed_t r, const ed_t p, const bn_t k)
void ed_pck (ed_t r, const ed_t p)
int ed_upk (ed_t r, const ed_t p)
Detailed Description
Interface of the module for arithmetic on elliptic curves.
Definition in file relic_ed.h.
Macro Definition Documentation
RLC_ED_TABLE_BASIC
#define RLC_ED_TABLE_BASIC (RLC_FP_BITS + 1)
Size of a precomputation table using the binary method.
Definition at line 62 of file relic_ed.h.
RLC_ED_TABLE_COMBS
#define RLC_ED_TABLE_COMBS (1 << ED_DEPTH)
Size of a precomputation table using the single-table comb method.
Definition at line 67 of file relic_ed.h.
RLC_ED_TABLE_COMBD
#define RLC_ED_TABLE_COMBD (1 << (ED_DEPTH + 1))
Size of a precomputation table using the double-table comb method.
Definition at line 72 of file relic_ed.h.
RLC_ED_TABLE_LWNAF
#define RLC_ED_TABLE_LWNAF (1 << (ED_DEPTH - 2))
Size of a precomputation table using the w-(T)NAF method.
Definition at line 77 of file relic_ed.h.
RLC_ED_TABLE_MAX
#define RLC_ED_TABLE_MAX RLC_MAX(RLC_ED_TABLE_BASIC, RLC_ED_TABLE_COMBD)
Size of a precomputation table using the chosen algorithm. Maximum size of a precomputation table.
Definition at line 98 of file relic_ed.h.
ed_null
#define ed_null (A) A = NULL;
Initializes a point on an Edwards curve with a null value.
Parameters
[out] A - the point to initialize.
Definition at line 144 of file relic_ed.h.
Typedef Documentation
ed_t
typedef ed_st* ed_t
Pointer to an elliptic curve point.
Definition at line 129 of file relic_ed.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Prime elliptic curve identifiers.
Enumerator
CURVE_ED25519
ED25519 Edwards curve.
Definition at line 51 of file relic_ed.h.
Function Documentation
ed_param_set()
void ed_param_set (int param)
Calls a function to allocate a point on an Edwards curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory. Calls a function to clean and free a point on an Edwards curve.
Parameters
[out] A - the point to free. Negates an Edwards elliptic curve point. Computes R = -P.
[out] R - the result.
[in] P - the point to negate. Adds two Edwards elliptic curve points. Computes R = P + Q.
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add. Subtracts an Edwards elliptic curve point from another. Computes R = P - Q.
[out] R - the result.
[in] P - the first point.
[in] Q - the second point. Doubles an Edwards elliptic curve point. Computes R = 2P.
[out] R - the result.
[in] P - the point to double. Configures an Edwards curve by its parameter identifier.
- the parameter identifier.
Definition at line 71 of file relic_ed_param.c.
References ASSIGN_ED, bn_copy(), bn_free(), bn_null, CATCH_ANY, core_get(), CURVE_ED25519, ed_copy(), ed_curve_get_tab(), _ctx_t::ed_g, _ctx_t::ed_h, _ctx_t::ed_id, ed_null, _ctx_t::ed_pre, _ctx_t::ed_ptr, _ctx_t::ed_r, ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp_set_dig(), ed_st::norm, PRIME_25519, RLC_FP_BYTES, ed_st::t, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_param_set_any().
ed_param_set_any()
int ed_param_set_any (void)
Configures some set of curve parameters for the current security level.
Definition at line 134 of file relic_ed_param.c.
References CURVE_ED25519, ed_param_set(), RLC_ERR, and RLC_OK.
ed_param_get()
int ed_param_get (void)
Returns the parameter identifier of the currently configured Edwards elliptic curve.
Returns
the parameter identifier.
Definition at line 144 of file relic_ed_param.c.
References core_get(), and _ctx_t::ed_id.
Referenced by ed_param_level(), and ed_param_print().
ed_curve_get_ord()
void ed_curve_get_ord (bn_t r)
Returns the order of the group of points in the Edwards curve.
Parameters
[out] r - the returned order.
Definition at line 57 of file relic_ed_curve.c.
References bn_copy(), and core_get().
Referenced by ed_mul_combs_plain(), ed_mul_fix_combd(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_trick(), and ed_rand().
ed_curve_get_gen()
void ed_curve_get_gen (ed_t g)
Returns the generator of the group of points in the curve.
Parameters
[out] g - the returned generator.
Definition at line 53 of file relic_ed_curve.c.
References core_get(), and ed_copy().
Referenced by ed_mul_gen(), and ed_mul_sim_gen().
ed_curve_get_tab()
const ed_t* ed_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 65 of file relic_ed_curve.c.
References core_get(), and _ctx_t::ed_ptr.
Referenced by ed_mul_gen(), ed_mul_sim_gen(), and ed_param_set().
ed_curve_get_cof()
void ed_curve_get_cof (bn_t h)
Returns the cofactor of the Edwards elliptic curve.
Parameters
[out] n - the returned cofactor.
Definition at line 61 of file relic_ed_curve.c.
References bn_copy(), and core_get().
ed_param_print()
void ed_param_print (void)
Prints the current configured Edwards elliptic curve.
Definition at line 156 of file relic_ed_param.c.
References CURVE_ED25519, ed_param_get(), and util_banner.
ed_param_level()
int ed_param_level (void)
Returns the current security level.
Definition at line 148 of file relic_ed_param.c.
References CURVE_ED25519, and ed_param_get().
ed_rand()
void ed_rand (ed_t p)
Assigns a random value to an Edwards elliptic curve point.
Parameters
[out] p - the Edwards elliptic curve point to assign.
Definition at line 147 of file relic_ed_util.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, ed_curve_get_ord(), ed_mul_gen(), ERR_CAUGHT, FINALLY, THROW, and TRY.
ed_rhs()
void ed_rhs (fp_t rhs, const ed_t p)
Computes the right-hand side of the elliptic curve equation at a certain Edwards elliptic curve point.
Parameters
[out] rhs - the result.
[in] p - the point.
Definition at line 169 of file relic_ed_util.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, fp_null, THROW, TRY, ed_st::x, and ed_st::y.
Referenced by ed_is_valid().
ed_copy()
void ed_copy (ed_t r, const ed_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the Edwards elliptic curve point to copy.
Definition at line 84 of file relic_ed_util.c.
References fp_copy(), ed_st::norm, ed_st::t, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_cmp(), ed_curve_get_gen(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_dig(), ed_mul_monty(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), ed_norm(), ed_param_set(), and ed_tab().
ed_cmp()
int ed_cmp (const ed_t p, const ed_t q)
Compares two Edwards elliptic curve points.
Parameters
[in] p - the first Edwards elliptic curve point.
[in] q - the second Edwards elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 95 of file relic_ed_util.c.
References CATCH_ANY, ed_copy(), ed_norm(), ed_null, ERR_CAUGHT, FINALLY, fp_cmp(), ed_st::norm, result, RLC_EQ, RLC_NE, ed_st::t, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
ed_set_infty()
void ed_set_infty (ed_t p)
Assigns an Edwards elliptic curve point to a point at the infinity.
Parameters
[out] p - the point to assign.
Definition at line 74 of file relic_ed_util.c.
References fp_set_dig(), fp_zero(), ed_st::norm, ed_st::t, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_curve_init(), ed_mul_basic(), ed_mul_dig(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_gen(), ed_mul_lwnaf(), ed_mul_lwreg(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_reg_imp(), ed_mul_sim_joint(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ed_neg_basic(), ed_neg_projc(), ed_norm(), ed_read_bin(), ed_sub_basic(), ed_sub_extnd(), and ed_sub_projc().
ed_is_infty()
int ed_is_infty (const ed_t p)
Tests if a point on an Edwards elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 44 of file relic_ed_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp_cmp_dig(), fp_is_zero(), fp_null, ed_st::norm, RLC_EQ, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_is_valid(), ed_mul_basic(), ed_mul_lwnaf(), ed_mul_lwreg(), ed_mul_monty(), ed_mul_sim_gen(), ed_mul_sim_inter(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), ed_neg_basic(), ed_neg_projc(), ed_norm(), ed_norm_sim(), ed_size_bin(), and ed_write_bin().
ed_neg_basic()
void ed_neg_basic (ed_t r, const ed_t p)
Negates an Edwards elliptic curve point represented by affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to negate.
Definition at line 40 of file relic_ed_neg.c.
References ed_is_infty(), ed_set_infty(), fp_copy(), ed_st::norm, ed_st::x, and ed_st::y.
Referenced by ed_sub_basic().
ed_neg_projc()
void ed_neg_projc (ed_t r, const ed_t p)
Negates an Edwards elliptic curve point represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to negate.
Definition at line 56 of file relic_ed_neg.c.
References ed_is_infty(), ed_set_infty(), fp_copy(), ed_st::norm, ed_st::t, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_sub_extnd(), and ed_sub_projc().
ed_add_basic()
void ed_add_basic (ed_t r, const ed_t p, const ed_t q)
Adds two Edwards elliptic curve points represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 44 of file relic_ed_add.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, fp_add_dig(), fp_copy(), fp_null, fp_sub_dig(), ed_st::norm, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_sub_basic().
ed_add_projc()
void ed_add_projc (ed_t r, const ed_t p, const ed_t q)
Adds two Edwards elliptic curve points represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 125 of file relic_ed_add.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, fp_null, ed_st::norm, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_sub_projc().
ed_add_extnd()
void ed_add_extnd (ed_t r, const ed_t p, const ed_t q)
Adds two Edwards elliptic curve points represented in exteded coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 230 of file relic_ed_add.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, fp_null, ed_st::norm, ed_st::t, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_sub_extnd().
ed_sub_basic()
void ed_sub_basic (ed_t r, const ed_t p, const ed_t q)
Subtracts an Edwards elliptic curve point from another, both points represented by affine coordinates..
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 96 of file relic_ed_add.c.
References CATCH_ANY, ed_add_basic(), ed_neg_basic(), ed_null, ed_set_infty(), ERR_CAUGHT, FINALLY, ed_st::norm, THROW, and TRY.
ed_sub_projc()
void ed_sub_projc (ed_t r, const ed_t p, const ed_t q)
Subtracts an Edwards elliptic curve point from another, both represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 202 of file relic_ed_add.c.
References CATCH_ANY, ed_add_projc(), ed_neg_projc(), ed_null, ed_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
ed_sub_extnd()
void ed_sub_extnd (ed_t r, const ed_t p, const ed_t q)
Subtracts an Edwards elliptic curve point from another, both represented by extended coordinates.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 296 of file relic_ed_add.c.
References CATCH_ANY, ed_add_extnd(), ed_neg_projc(), ed_null, ed_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
ed_dbl_basic()
void ed_dbl_basic (ed_t r, const ed_t p)
Doubles an Edwards elliptic curve point represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 42 of file relic_ed_dbl.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, fp_add_dig(), fp_copy(), fp_null, fp_sub_dig(), ed_st::norm, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
ed_dbl_projc()
void ed_dbl_projc (ed_t r, const ed_t p)
Doubles an Edwards elliptic curve point represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 95 of file relic_ed_dbl.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, fp_null, ed_st::norm, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
ed_dbl_extnd()
void ed_dbl_extnd (ed_t r, const ed_t p)
Doubles an Edwards elliptic curve point represented in extended coordinates.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 168 of file relic_ed_dbl.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, fp_null, ed_st::norm, ed_st::t, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
ed_norm()
void ed_norm (ed_t r, const ed_t p)
Converts a point to affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to convert.
Definition at line 73 of file relic_ed_norm.c.
References ed_copy(), ed_is_infty(), ed_norm_imp(), ed_set_infty(), and ed_st::norm.
Referenced by ed_cmp(), ed_is_valid(), ed_map(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_dig(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_reg_imp(), ed_mul_sim_basic(), ed_mul_sim_joint(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ed_tab(), and ed_write_bin().
ed_norm_sim()
void ed_norm_sim (ed_t * r, const ed_t * t, int n)
Converts multiple points to affine coordinates.
Parameters
[out] r - the result.
[in] t - the points to convert.
[in] n - the number of points.
Definition at line 89 of file relic_ed_norm.c.
References CATCH_ANY, ed_is_infty(), ed_norm_imp(), ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, fp_copy(), fp_inv_sim(), fp_null, RLC_ALLOCA, RLC_FREE, THROW, and TRY.
Referenced by ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), and ed_tab().
ed_map()
void ed_map (ed_t p, const uint8_t * msg, int len)
Maps a byte array to a point in an Edwards elliptic curve.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 40 of file relic_ed_map.c.
References bn_free(), bn_null, bn_read_bin(), bn_rsh(), bn_sub_dig(), CATCH_ANY, core_get(), bn_st::dp, dv_copy(), ed_norm(), ERR_CAUGHT, FINALLY, fp_add_dig(), fp_cmp(), fp_null, fp_prime_conv(), fp_prime_get(), fp_set_dig(), fp_sub_dig(), ed_st::norm, RLC_DIG, RLC_EQ, RLC_FP_BYTES, RLC_FP_DIGS, RLC_MIN, ed_st::t, THROW, TRY, bn_st::used, ed_st::x, ed_st::y, and ed_st::z.
ed_curve_init()
void ed_curve_init (void)
Multiplies an Edwards elliptic curve point by an integer. Computes R = kP.
Parameters
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer. Builds a precomputation table for multiplying a fixed Edwards elliptic point.
[out] T - the precomputation table.
[in] P - the point to multiply. Multiplies a fixed Edwards elliptic point using a precomputation table. Computes R = kP.
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer. Multiplies and adds two Edwards elliptic curve points simultaneously. Computes R = kP + mQ.
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] M - the second integer, Initializes the Edwards elliptic curve arithmetic module.
Definition at line 35 of file relic_ed_curve.c.
References bn_init(), core_get(), _ctx_t::ed_g, _ctx_t::ed_h, _ctx_t::ed_pre, _ctx_t::ed_ptr, _ctx_t::ed_r, ed_set_infty(), and RLC_FP_DIGS.
Referenced by core_init().
ed_curve_clean()
void ed_curve_clean (void)
Finalizes the Edwards elliptic curve arithmetic module.
Definition at line 47 of file relic_ed_curve.c.
References bn_clean(), core_get(), _ctx_t::ed_h, and _ctx_t::ed_r.
Referenced by core_clean().
ed_mul_pre_basic()
void ed_mul_pre_basic (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 161 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free(), bn_null, CATCH_ANY, ed_copy(), ed_curve_get_ord(), ed_norm_sim(), ERR_CAUGHT, FINALLY, THROW, and TRY.
ed_mul_pre_yaowi()
void ed_mul_pre_yaowi (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using Yao's windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ed_mul_pre_nafwi()
void ed_mul_pre_nafwi (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the NAF windowing method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
ed_mul_pre_combs()
void ed_mul_pre_combs (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 209 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free(), bn_null, CATCH_ANY, ed_copy(), ed_curve_get_ord(), ED_DEPTH, ed_norm(), ed_norm_sim(), ed_set_infty(), ERR_CAUGHT, FINALLY, RLC_ED_TABLE_COMBS, THROW, and TRY.
ed_mul_pre_combd()
void ed_mul_pre_combd (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 255 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free(), bn_null, CATCH_ANY, ed_copy(), ed_curve_get_ord(), ED_DEPTH, ed_norm(), ed_norm_sim(), ed_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
ed_mul_pre_lwnaf()
void ed_mul_pre_lwnaf (ed_t * t, const ed_t p)
Builds a precomputation table for multiplying a fixed Edwards elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 362 of file relic_ed_mul_fix.c.
References ED_DEPTH, and ed_tab().
ed_mul_fix_basic()
void ed_mul_fix_basic (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 186 of file relic_ed_mul_fix.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), ed_norm(), ed_set_infty(), and RLC_NEG.
ed_mul_fix_yaowi()
void ed_mul_fix_yaowi (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and Yao's windowing method
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ed_mul_fix_nafwi()
void ed_mul_fix_nafwi (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ed_mul_fix_combs()
void ed_mul_fix_combs (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 248 of file relic_ed_mul_fix.c.
References ed_mul_combs_plain().
ed_mul_fix_combd()
void ed_mul_fix_combd (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 303 of file relic_ed_mul_fix.c.
References bn_bits(), bn_free(), bn_get_bit(), bn_null, bn_sign(), CATCH_ANY, ed_curve_get_ord(), ED_DEPTH, ed_norm(), ed_set_infty(), ERR_CAUGHT, FINALLY, RLC_NEG, THROW, and TRY.
ed_mul_fix_lwnaf()
void ed_mul_fix_lwnaf (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 366 of file relic_ed_mul_fix.c.
References ed_mul_fix_plain().
ed_mul_fix_lwnaf_mixed()
void ed_mul_fix_lwnaf_mixed (ed_t r, const ed_t * t, const bn_t k)
Multiplies a fixed Edwards elliptic point using a precomputation table and the w-(T)NAF mixed coordinate method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
ed_mul_gen()
void ed_mul_gen (ed_t r, const bn_t k)
Multiplies the generator of an Edwards elliptic curve by an integer.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 382 of file relic_ed_mul.c.
References bn_is_zero(), CATCH_ANY, ed_curve_get_gen(), ed_curve_get_tab(), ed_null, ed_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
Referenced by ed_mul_sim_gen(), and ed_rand().
ed_mul_dig()
void ed_mul_dig (ed_t r, const ed_t p, dig_t k)
Multiplies an Edwards elliptic curve point by a small positive integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 408 of file relic_ed_mul.c.
References CATCH_ANY, ed_copy(), ed_norm(), ed_null, ed_set_infty(), ERR_CAUGHT, FINALLY, THROW, TRY, and util_bits_dig().
ed_mul_sim_basic()
void ed_mul_sim_basic (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds two Edwards elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 157 of file relic_ed_mul_sim.c.
References CATCH_ANY, ed_norm(), ed_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
ed_mul_sim_trick()
void ed_mul_sim_trick (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds two Edwards elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 182 of file relic_ed_mul_sim.c.
References bn_free(), bn_is_zero(), bn_null, bn_rec_win(), bn_sign(), CATCH_ANY, ed_copy(), ed_curve_get_ord(), ed_is_infty(), ed_norm(), ed_norm_sim(), ed_null, ed_set_infty(), ED_WIDTH, ERR_CAUGHT, FINALLY, RLC_CEIL, RLC_FP_BITS, RLC_MAX, RLC_NEG, THROW, and TRY.
ed_mul_sim_inter()
void ed_mul_sim_inter (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds two Edwards elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 281 of file relic_ed_mul_sim.c.
References bn_is_zero(), ed_is_infty(), and ed_mul_sim_plain().
ed_mul_sim_joint()
void ed_mul_sim_joint (ed_t r, const ed_t p, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds two Edwards elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 300 of file relic_ed_mul_sim.c.
References bn_bits(), bn_is_zero(), bn_rec_jsf(), bn_sign(), CATCH_ANY, ed_copy(), ed_is_infty(), ed_norm(), ed_norm_sim(), ed_null, ed_set_infty(), ERR_CAUGHT, FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, THROW, and TRY.
ed_mul_sim_gen()
void ed_mul_sim_gen (ed_t r, const bn_t k, const ed_t q, const bn_t m)
Multiplies and adds the generator and an Edwards elliptic curve point simultaneously. Computes R = kG + mQ.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
Definition at line 374 of file relic_ed_mul_sim.c.
References bn_is_zero(), CATCH_ANY, ed_curve_get_gen(), ed_curve_get_tab(), ed_is_infty(), ed_mul_gen(), ed_mul_sim_plain(), ed_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
ed_tab()
void ed_tab (ed_t * t, const ed_t p, int w)
Builds a precomputation table for multiplying a random Edwards elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 228 of file relic_ed_util.c.
References ed_copy(), ed_norm(), and ed_norm_sim().
Referenced by ed_mul_naf_imp(), ed_mul_pre_lwnaf(), ed_mul_reg_imp(), and ed_mul_sim_plain().
ed_print()
void ed_print (const ed_t p)
Prints an Edwards elliptic curve point.
Parameters
[in] p - the Edwards elliptic curve point to print.
Definition at line 245 of file relic_ed_util.c.
References fp_print(), ed_st::t, ed_st::x, ed_st::y, and ed_st::z.
ed_is_valid()
int ed_is_valid (const ed_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 196 of file relic_ed_util.c.
References CATCH_ANY, ed_is_infty(), ed_norm(), ed_null, ed_rhs(), ERR_CAUGHT, FINALLY, fp_cmp(), fp_cmp_dig(), fp_is_zero(), RLC_EQ, ed_st::t, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
ed_size_bin()
int ed_size_bin (const ed_t a, int pack)
Returns the number of bytes necessary to store an Edwards elliptic curve point with optional point compression.
Parameters
[in] a - the Edwards field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 254 of file relic_ed_util.c.
References ed_is_infty(), and RLC_FP_BYTES.
ed_read_bin()
void ed_read_bin (ed_t a, const uint8_t * bin, int len)
Reads an Edwards elliptic curve point from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 269 of file relic_ed_util.c.
References ed_set_infty(), ed_upk(), ERR_NO_BUFFER, ERR_NO_VALID, fp_read_bin(), fp_set_bit(), fp_set_dig(), fp_zero(), ed_st::norm, RLC_FP_BYTES, ed_st::t, THROW, ed_st::x, ed_st::y, and ed_st::z.
ed_write_bin()
void ed_write_bin (uint8_t * bin, int len, const ed_t a, int pack)
Writes an Edwards elliptic curve point to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the Edwards elliptic curve point to write.
[in] pack - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 319 of file relic_ed_util.c.
References CATCH_ANY, ed_is_infty(), ed_norm(), ed_null, ed_pck(), ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, fp_get_bit(), fp_write_bin(), RLC_FP_BYTES, THROW, TRY, ed_st::x, and ed_st::y.
ed_mul_basic()
void ed_mul_basic (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 196 of file relic_ed_mul.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, ed_copy(), ed_is_infty(), ed_norm(), ed_null, ed_set_infty(), ERR_CAUGHT, FINALLY, RLC_NEG, THROW, and TRY.
ed_mul_slide()
void ed_mul_slide (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 234 of file relic_ed_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), CATCH_ANY, ed_copy(), ed_is_infty(), ed_norm(), ed_norm_sim(), ed_null, ed_set_infty(), EP_WIDTH, ERR_CAUGHT, FINALLY, RLC_FP_BITS, RLC_NEG, THROW, TRY, and util_bits_dig().
ed_mul_monty()
void ed_mul_monty (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using the constant-time Montgomery laddering point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 304 of file relic_ed_mul.c.
References bn_bits(), bn_get_bit(), bn_is_zero(), bn_sign(), CATCH_ANY, dv_swap_cond(), ed_copy(), ed_is_infty(), ed_norm(), ed_null, ed_set_infty(), ERR_CAUGHT, FINALLY, RLC_FP_DIGS, RLC_NEG, THROW, and TRY.
ed_mul_lwnaf()
void ed_mul_lwnaf (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 358 of file relic_ed_mul.c.
References bn_is_zero(), ed_is_infty(), ed_mul_naf_imp(), and ed_set_infty().
ed_mul_lwreg()
void ed_mul_lwreg (ed_t r, const ed_t p, const bn_t k)
Multiplies an Edwards elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 371 of file relic_ed_mul.c.
References bn_is_zero(), ed_is_infty(), ed_mul_reg_imp(), and ed_set_infty().
ed_pck()
void ed_pck (ed_t r, const ed_t p)
Compresses a point.
Parameters
[out] r - the result.
[in] p - the point to compress.
Definition at line 38 of file relic_ed_pck.c.
References fp_copy(), fp_get_bit(), fp_set_bit(), fp_set_dig(), fp_zero(), ed_st::norm, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_write_bin().
ed_upk()
int ed_upk (ed_t r, const ed_t p)
Decompresses a point.
Parameters
[out] r - the result.
[in] p - the point to decompress.
Returns
if the decompression was successful
Definition at line 47 of file relic_ed_pck.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, fp_copy(), fp_get_bit(), fp_null, fp_set_dig(), fp_srt(), fp_sub_dig(), ed_st::norm, result, ed_st::t, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_read_bin().