RELIC: src/eb/relic_eb_curve.c File Reference
relic_eb_curve.c File Reference
Elliptic curves over binary fields
#include "relic_core.h"
#include "relic_eb.h"
#include "relic_conf.h"
Functions
static void detect_opt (int *opt, fb_t a)
void eb_curve_init (void)
void eb_curve_clean (void)
dig_t * eb_curve_get_a (void)
int eb_curve_opt_a (void)
dig_t * eb_curve_get_b (void)
int eb_curve_opt_b (void)
int eb_curve_is_kbltz (void)
void eb_curve_get_gen (eb_t g)
void eb_curve_get_ord (bn_t n)
void eb_curve_get_cof (bn_t h)
const eb_t * eb_curve_get_tab (void)
void eb_curve_set (const fb_t a, const fb_t b, const eb_t g, const bn_t r, const bn_t h)
Detailed Description
Implementation of the binary elliptic curve utilities.
Definition in file relic_eb_curve.c.
Function Documentation
detect_opt()
static void detect_opt (int * opt, fb_t a) static
Detects an optimization based on the curve coefficients.
Parameters
opt - the resulting optimization.
a - the curve coefficient.
Definition at line 46 of file relic_eb_curve.c.
References fb_bits(), fb_cmp_dig(), fb_is_zero(), RLC_DIG, RLC_EQ, RLC_HUGE, RLC_ONE, RLC_TINY, and RLC_ZERO.
Referenced by eb_curve_set().
eb_curve_init()
void eb_curve_init (void)
Calls a function to allocate a point on a binary elliptic curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory. Calls a function to clean and free a point on a binary elliptic curve.
Parameters
[out] A - the point to clean and free. Negates a binary elliptic curve point. Computes R = -P.
[out] R - the result.
[in] P - the point to negate. Adds two binary elliptic curve points. Computes R = P + Q.
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add. Subtracts a binary elliptic curve point from another. Computes R = P - Q.
[out] R - the result.
[in] P - the first point.
[in] Q - the second point. Doubles a binary elliptic curve point. Computes R = 2P.
[out] R - the result.
[in] P - the point to double. Computes the Frobenius map of a binary elliptic curve point on a Koblitz curve. Computes R = t(P).
[out] R - the result.
[in] P - the point. Multiplies a binary elliptic curve point by an integer. Computes R = kP.
[out] R - the result.
[in] P - the point to multiply.
[in] K - the integer. Builds a precomputation table for multiplying a fixed binary elliptic point point.
[out] T - the precomputation table.
[in] P - the point to multiply. Multiplies a fixed binary elliptic point using a precomputation table. Computes R = kP.
[out] R - the result.
[in] T - the precomputation table.
[in] K - the integer. Multiplies and adds two binary elliptic curve points simultaneously. Computes R = kP + mQ.
[out] R - the result.
[in] P - the first point to multiply.
[in] K - the first integer.
[in] Q - the second point to multiply.
[in] M - the second integer, Initializes the binary elliptic curve arithmetic module.
Definition at line 66 of file relic_eb_curve.c.
References bn_init(), core_get(), _ctx_t::eb_g, _ctx_t::eb_h, _ctx_t::eb_pre, _ctx_t::eb_ptr, _ctx_t::eb_r, fb_zero(), RLC_FB_DIGS, eb_st::x, eb_st::y, and eb_st::z.
Referenced by core_init().
eb_curve_clean()
void eb_curve_clean (void)
Finalizes the binary elliptic curve arithmetic module.
Definition at line 80 of file relic_eb_curve.c.
References bn_clean(), core_get(), _ctx_t::eb_h, and _ctx_t::eb_r.
Referenced by core_clean().
eb_curve_get_a()
dig_t* eb_curve_get_a (void)
Returns the 'a' coefficient of the currently configured binary elliptic curve.
Returns
the 'a' coefficient of the elliptic curve.
Definition at line 86 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_a.
Referenced by eb_add_basic_imp(), eb_add_projc_mix(), eb_dbl_basic_imp(), eb_dbl_projc_imp(), eb_hlv(), eb_mul_halve(), and eb_rhs().
eb_curve_opt_a()
int eb_curve_opt_a (void)
Returns a optimization identifier based on the 'a' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 90 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_opt_a.
Referenced by eb_add_basic_imp(), eb_add_projc_mix(), eb_dbl_basic_imp(), eb_dbl_projc_imp(), eb_hlv(), eb_mul_fix_kbltz(), eb_mul_ltnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_kbltz(), eb_rhs(), and eb_tab().
eb_curve_get_b()
dig_t* eb_curve_get_b (void)
Returns the 'b' coefficient of the currently configured binary elliptic curve.
Returns
the 'b' coefficient of the elliptic curve.
Definition at line 94 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_b.
Referenced by eb_mul_halve(), eb_mul_lodah(), and eb_rhs().
eb_curve_opt_b()
int eb_curve_opt_b (void)
Returns a optimization identifier based on the 'b' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 98 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_opt_b.
Referenced by eb_mul_lodah(), and eb_rhs().
eb_curve_is_kbltz()
int eb_curve_is_kbltz (void)
Tests if the configured binary elliptic curve is a Koblitz curve.
Returns
1 if the binary elliptic curve is a Koblitz curve, 0 otherwise.
Definition at line 102 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_is_kbltz.
Referenced by eb_mul_fix_lwnaf(), eb_mul_lwnaf(), eb_mul_rwnaf(), eb_mul_sim_gen(), eb_mul_sim_inter(), and eb_tab().
eb_curve_get_gen()
void eb_curve_get_gen (eb_t g)
Returns the generator of the group of points in the binary elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 106 of file relic_eb_curve.c.
References core_get(), and eb_copy().
Referenced by eb_mul_gen(), and eb_mul_sim_gen().
eb_curve_get_ord()
void eb_curve_get_ord (bn_t n)
Returns the order of the group of points in the binary elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 110 of file relic_eb_curve.c.
References bn_copy(), and core_get().
Referenced by eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_halve(), eb_mul_lodah(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_sim_trick(), and eb_rand().
eb_curve_get_cof()
void eb_curve_get_cof (bn_t h)
Returns the cofactor of the binary elliptic curve.
Parameters
[out] n - the returned cofactor.
Definition at line 114 of file relic_eb_curve.c.
References bn_copy(), and core_get().
Referenced by eb_map(), and eb_mul_halve().
eb_curve_get_tab()
const eb_t* eb_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 118 of file relic_eb_curve.c.
References core_get(), and _ctx_t::eb_ptr.
Referenced by eb_curve_set(), eb_mul_gen(), and eb_mul_sim_gen().
eb_curve_set()
void eb_curve_set (const fb_t a, const fb_t b, const eb_t g, const bn_t n, const bn_t h)
Configures an ordinary binary elliptic curve by its coefficients and generator.
Parameters
[in] a - the 'a' coefficient of the curve.
[in] b - the 'b' coefficient of the curve.
[in] g - the generator.
[in] n - the order of the generator.
[in] h - the cofactor of the group order.
Definition at line 134 of file relic_eb_curve.c.
References bn_copy(), core_get(), detect_opt(), _ctx_t::eb_a, _ctx_t::eb_b, eb_curve_get_tab(), _ctx_t::eb_g, _ctx_t::eb_h, _ctx_t::eb_is_kbltz, eb_norm(), _ctx_t::eb_opt_a, _ctx_t::eb_opt_b, _ctx_t::eb_r, fb_cmp_dig(), fb_copy(), and RLC_EQ.
Referenced by eb_param_set().