RELIC: src/bn/relic_bn_prime.c File Reference
relic_bn_prime.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
Macros
#define BASIC_TESTS ((int)(sizeof(primes)/sizeof(dig_t)))
Functions
dig_t bn_get_prime (int pos)
int bn_is_prime (const bn_t a)
int bn_is_prime_basic (const bn_t a)
int bn_is_prime_rabin (const bn_t a)
int bn_is_prime_solov (const bn_t a)
void bn_gen_prime_basic (bn_t a, int bits)
void bn_gen_prime_safep (bn_t a, int bits)
void bn_gen_prime_stron (bn_t a, int bits)
Variables
static const dig_t primes []
Detailed Description
Implementation of the prime number generation and testing functions.
Strong prime generation is based on Gordon's Algorithm, taken from Handbook of Applied Cryptography.
Definition in file relic_bn_prime.c.
Macro Definition Documentation
BASIC_TESTS
#define BASIC_TESTS ((int)(sizeof(primes)/sizeof(dig_t)))
Number of trial division tests.
Definition at line 44 of file relic_bn_prime.c.
Function Documentation
bn_get_prime()
dig_t bn_get_prime (int pos)
Returns a small precomputed prime from a given position in the list of prime numbers.
Parameters
[in] pos - the position in the prime sequence.
Returns
a prime if the position is lower than 512, 0 otherwise.
Definition at line 173 of file relic_bn_prime.c.
References BASIC_TESTS, and primes.
bn_is_prime()
int bn_is_prime (const bn_t a)
Tests if a number is a probable prime.
Parameters
[in] a - the multiple precision integer to test.
Returns
1 if a is prime, 0 otherwise.
Definition at line 180 of file relic_bn_prime.c.
References bn_is_prime_basic(), bn_is_prime_rabin(), and result.
Referenced by bn_gen_prime_basic(), bn_gen_prime_safep(), bn_gen_prime_stron(), cp_bdpe_gen(), and fp_param_set_any_dense().
bn_is_prime_basic()
int bn_is_prime_basic (const bn_t a)
Tests if a number is prime using a series of trial divisions.
Parameters
[in] a - the number to test.
Returns
1 if a is a probable prime, 0 otherwise.
Definition at line 197 of file relic_bn_prime.c.
References BASIC_TESTS, bn_cmp_dig(), bn_mod_dig(), primes, result, and RLC_EQ.
Referenced by bn_is_prime(), and cp_bdpe_gen().
bn_is_prime_rabin()
int bn_is_prime_rabin (const bn_t a)
Tests if a number a > 2 is prime using the Miller-Rabin test with probability 2^(-80) of error.
Parameters
[in] a - the number to test.
Returns
1 if a is a probable prime, 0 otherwise.
Definition at line 218 of file relic_bn_prime.c.
References bn_bits(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free(), bn_is_even(), bn_mod, bn_null, bn_rsh(), bn_set_dig(), bn_sub_dig(), CATCH_ANY, ERR_CAUGHT, FINALLY, primes, result, RLC_EQ, RLC_LT, THROW, and TRY.
Referenced by bn_is_prime().
bn_is_prime_solov()
int bn_is_prime_solov (const bn_t a)
Tests if a number a > 2 is prime using the Solovay-Strassen test with probability 2^(-80) of error.
Parameters
[in] a - the number to test.
Returns
1 if a is a probable prime, 0 otherwise.
Definition at line 343 of file relic_bn_prime.c.
References bn_add(), bn_bits(), bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free(), bn_mod, bn_null, bn_rand(), bn_rsh(), bn_sign(), bn_smb_jac(), bn_sub_dig(), CATCH_ANY, ERR_CAUGHT, FINALLY, result, RLC_EQ, RLC_LT, RLC_NEG, RLC_POS, THROW, and TRY.
bn_gen_prime_basic()
void bn_gen_prime_basic (bn_t a, int bits)
Generates a probable prime number.
Parameters
[out] a - the result.
[in] bits - the length of the number in bits.
Definition at line 409 of file relic_bn_prime.c.
References bn_bits(), bn_is_prime(), bn_rand(), and RLC_POS.
bn_gen_prime_safep()
void bn_gen_prime_safep (bn_t a, int bits)
Generates a probable prime number a with (a - 1)/2 also prime.
Parameters
[out] a - the result.
[in] bits - the length of the number in bits.
Definition at line 424 of file relic_bn_prime.c.
References bn_add_dig(), bn_bits(), bn_is_prime(), bn_lsh(), bn_rand(), bn_rsh(), bn_sub_dig(), and RLC_POS.
bn_gen_prime_stron()
void bn_gen_prime_stron (bn_t a, int bits)
Generates a probable prime number with (a - 1)/2, (a + 1)/2 and ((a - 1)/2 - 1)/2 also prime.
Parameters
[out] a - the result.
[in] bits - the length of the number in bits.
Definition at line 448 of file relic_bn_prime.c.
References bn_add(), bn_add_dig(), bn_bits(), bn_dbl(), bn_free(), bn_is_prime(), bn_mul_dig(), bn_null, bn_rand(), bn_sub_dig(), CATCH_ANY, bn_st::dp, ERR_CAUGHT, FINALLY, RLC_DIG, RLC_POS, THROW, and TRY.
Variable Documentation
primes
const dig_t primes[] static
Small prime numbers table.
Definition at line 49 of file relic_bn_prime.c.
Referenced by bn_get_prime(), bn_is_prime_basic(), and bn_is_prime_rabin().