RELIC: src/cp/relic_cp_rabin.c File Reference
relic_cp_rabin.c File Reference
Cryptographic protocols
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_rand.h"
#include "relic_bn.h"
#include "relic_util.h"
#include "relic_cp.h"
#include "relic_md.h"
Macros
#define RABIN_PAD_LEN 8
#define RABIN_PAD (0xFF)
Functions
int cp_rabin_gen (rabin_t pub, rabin_t prv, int bits)
int cp_rabin_enc (uint8_t *out, int *out_len, uint8_t *in, int in_len, rabin_t pub)
int cp_rabin_dec (uint8_t *out, int *out_len, uint8_t *in, int in_len, rabin_t prv)
Detailed Description
Implementation of the Rabin cryptosystem.
Definition in file relic_cp_rabin.c.
Macro Definition Documentation
RABIN_PAD_LEN
#define RABIN_PAD_LEN 8
Length in bytes of added redundancy.
Definition at line 49 of file relic_cp_rabin.c.
RABIN_PAD
#define RABIN_PAD (0xFF)
Byte used as padding unit in ciphertext.
Definition at line 54 of file relic_cp_rabin.c.
Function Documentation
cp_rabin_gen()
int cp_rabin_gen (rabin_t pub, rabin_t prv, int bits)
Generates a key pair for the Rabin cryptosystem.
Parameters
[out] pub - the public key.
[out] prv - the private key,
[in] bits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 60 of file relic_cp_rabin.c.
References bn_cmp(), bn_cmp_dig(), bn_copy(), bn_free(), bn_mod_2b(), bn_null, CATCH_ANY, _rabin_t::dp, _rabin_t::dq, FINALLY, _rabin_t::n, _rabin_t::p, _rabin_t::q, result, RLC_EQ, RLC_ERR, RLC_LT, RLC_OK, and TRY.
cp_rabin_enc()
int cp_rabin_enc (uint8_t * out, int * out_len, uint8_t * in, int in_len, rabin_t pub)
Encrypts using the Rabin cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 106 of file relic_cp_rabin.c.
References bn_add(), bn_add_dig(), bn_free(), bn_lsh(), bn_mod, bn_mod_2b(), bn_null, bn_read_bin(), bn_size_bin(), bn_write_bin(), bn_zero(), CATCH_ANY, FINALLY, _rabin_t::n, RABIN_PAD, RABIN_PAD_LEN, result, RLC_ERR, RLC_OK, and TRY.
cp_rabin_dec()
int cp_rabin_dec (uint8_t * out, int * out_len, uint8_t * in, int in_len, rabin_t prv)
Decrypts using the Rabin cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to decrypt.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 157 of file relic_cp_rabin.c.
References bn_add(), bn_add_dig(), bn_cmp(), bn_free(), bn_is_zero(), bn_mod, bn_mod_2b(), bn_null, bn_read_bin(), bn_rsh(), bn_sign(), bn_size_bin(), bn_sub(), bn_write_bin(), CATCH_ANY, _rabin_t::dp, bn_st::dp, _rabin_t::dq, FINALLY, _rabin_t::n, _rabin_t::p, _rabin_t::q, RABIN_PAD, RABIN_PAD_LEN, result, RLC_EQ, RLC_ERR, RLC_NEG, RLC_OK, and TRY.