RELIC: src/cp/relic_cp_ecdh.c File Reference
relic_cp_ecdh.c File Reference
Cryptographic protocols
#include "relic.h"
#include "relic_test.h"
#include "relic_bench.h"
Functions
int cp_ecdh_gen (bn_t d, ec_t q)
int cp_ecdh_key (uint8_t *key, int key_len, bn_t d, ec_t q)
Detailed Description
Implementation of the ECDH protocol.
Version
Id
relic_cp_ecdh.c 1928 2014-06-20 14:22:00Z dfaranha
Definition in file relic_cp_ecdh.c.
Function Documentation
int cp_ecdh_gen (bn_t d, ec_t q)
Generates an ECDH key pair.
Parameters
[out] d - the private key.
[in] q - the public key.
Definition at line 40 of file relic_cp_ecdh.c.
References bn_bits(), bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, BN_POS, bn_rand(), CATCH_ANY, ec_curve_get_ord, ec_mul_gen, FINALLY, STS_ERR, STS_OK, and TRY.
int cp_ecdh_key (uint8_t * key, int key_len, bn_t d, ec_t q)
Derives a shared secret using ECDH.
Parameters
[out] key - the shared key.
int] key_len - the intended shared key length in bytes.
[in] d - the private key.
[in] q - the point received from the other party.
Returns
STS_OK if no errors occurred, STS_ERR otherwise.
Definition at line 68 of file relic_cp_ecdh.c.
References bn_bits(), BN_DIGIT, bn_free, bn_new, bn_null, bn_size_bin(), bn_write_bin(), CATCH_ANY, ec_curve_get_cof, ec_free, ec_get_x, ec_is_infty, ec_mul, ec_mul_dig, ec_new, ec_null, ERR_CAUGHT, FC_BYTES, FINALLY, md_kdf2(), STS_ERR, STS_OK, THROW, and TRY.