RELIC: src/epx/relic_ep2_add.c File Reference
relic_ep2_add.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep2_add_basic_imp (ep2_t r, fp2_t s, ep2_t p, ep2_t q)
static void ep2_add_projc_mix (ep2_t r, ep2_t p, ep2_t q)
static void ep2_add_projc_imp (ep2_t r, ep2_t p, ep2_t q)
void ep2_add_basic (ep2_t r, ep2_t p, ep2_t q)
void ep2_add_slp_basic (ep2_t r, fp2_t s, ep2_t p, ep2_t q)
void ep2_sub_basic (ep2_t r, ep2_t p, ep2_t q)
void ep2_add_projc (ep2_t r, ep2_t p, ep2_t q)
void ep2_sub_projc (ep2_t r, ep2_t p, ep2_t q)
Detailed Description
Implementation of addition on prime elliptic curves over quadratic extensions.
Definition in file relic_ep2_add.c.
Function Documentation
ep2_add_basic_imp()
static void ep2_add_basic_imp (ep2_t r, fp2_t s, ep2_t p, ep2_t q) static
Adds two points represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
r - the result.
s - the resulting slope.
p - the first point to add.
q - the second point to add.
Definition at line 50 of file relic_ep2_add.c.
References CATCH_ANY, ep2_dbl_slp_basic(), ep2_set_infty(), ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_inv(), fp2_is_zero(), fp2_new, fp2_null, ep2_st::norm, THROW, TRY, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_add_basic(), and ep2_add_slp_basic().
ep2_add_projc_mix()
static void ep2_add_projc_mix (ep2_t r, ep2_t p, ep2_t q) static
Adds a point represented in affine coordinates to a point represented in projective coordinates.
Parameters
r - the result.
s - the slope.
p - the affine point.
q - the projective point.
Definition at line 127 of file relic_ep2_add.c.
References CATCH_ANY, ep2_dbl_projc(), ep2_set_infty(), ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_is_zero(), fp2_new, fp2_null, ep2_st::norm, THROW, TRY, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_add_projc_imp().
ep2_add_projc_imp()
static void ep2_add_projc_imp (ep2_t r, ep2_t p, ep2_t q) static
Adds two points represented in projective coordinates on an ordinary prime elliptic curve.
Parameters
r - the result.
p - the first point to add.
q - the second point to add.
Definition at line 236 of file relic_ep2_add.c.
References CATCH_ANY, ep2_add_projc_mix(), ep2_dbl_projc(), ep2_set_infty(), ERR_CAUGHT, FINALLY, fp2_free, fp2_is_zero(), fp2_new, fp2_null, ep2_st::norm, THROW, TRY, ep2_st::x, ep2_st::y, and ep2_st::z.
Referenced by ep2_add_projc().
ep2_add_basic()
void ep2_add_basic (ep2_t r, ep2_t p, ep2_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 358 of file relic_ep2_add.c.
References ep2_add_basic_imp(), ep2_copy(), and ep2_is_infty().
Referenced by ep2_sub_basic().
ep2_add_slp_basic()
void ep2_add_slp_basic (ep2_t r, fp2_t s, ep2_t p, ep2_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quadratic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 372 of file relic_ep2_add.c.
References ep2_add_basic_imp(), ep2_copy(), and ep2_is_infty().
Referenced by pp_add_k12_basic(), and pp_add_k8_basic().
ep2_sub_basic()
void ep2_sub_basic (ep2_t r, ep2_t p, ep2_t q)
Subtracts a points represented in affine coordinates in an elliptic curve over a quadratic extension from another point.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 386 of file relic_ep2_add.c.
References CATCH_ANY, ep2_add_basic(), ep2_neg_basic(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, ep2_st::norm, THROW, and TRY.
ep2_add_projc()
void ep2_add_projc (ep2_t r, ep2_t p, ep2_t q)
Adds two points represented in projective coordinates in an elliptic curve over a quadratic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 416 of file relic_ep2_add.c.
References ep2_add_projc_imp(), ep2_copy(), and ep2_is_infty().
Referenced by ep2_sub_projc().
ep2_sub_projc()
void ep2_sub_projc (ep2_t r, ep2_t p, ep2_t q)
Subtracts a points represented in projective coordinates in an elliptic curve over a quadratic extension from another point.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 436 of file relic_ep2_add.c.
References CATCH_ANY, ep2_add_projc(), ep2_neg_projc(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.