RELIC: src/epx/relic_ep4_mul.c File Reference
relic_ep4_mul.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep4_psi (ep4_t r, const ep4_t p)
static void ep4_mul_gls_imp (ep4_t r, const ep4_t p, const bn_t k)
static void ep4_mul_reg_gls (ep4_t r, const ep4_t p, const bn_t k)
static void ep4_mul_naf_imp (ep4_t r, const ep4_t p, const bn_t k)
static void ep4_mul_reg_imp (ep4_t r, const ep4_t p, const bn_t k)
void ep4_mul_basic (ep4_t r, const ep4_t p, const bn_t k)
void ep4_mul_slide (ep4_t r, const ep4_t p, const bn_t k)
void ep4_mul_monty (ep4_t r, const ep4_t p, const bn_t k)
void ep4_mul_lwnaf (ep4_t r, const ep4_t p, const bn_t k)
void ep4_mul_lwreg (ep4_t r, const ep4_t p, const bn_t k)
void ep4_mul_gen (ep4_t r, const bn_t k)
void ep4_mul_dig (ep4_t r, const ep4_t p, const dig_t k)
Detailed Description
Implementation of point multiplication on prime elliptic curves over a quartic extension field.
Definition in file relic_ep4_mul.c.
Function Documentation
ep4_psi()
static void ep4_psi (ep4_t r, const ep4_t p) static
Definition at line 40 of file relic_ep4_mul.c.
References ep4_copy(), ep4_dbl, ep4_frb(), ep4_free, ep4_is_infty(), ep4_neg(), ep4_new, ep4_null, ep4_set_infty(), ep4_sub(), EP_AFG16, ep_curve_is_pairf(), EP_FM16, EP_K16, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_gls_imp(), and ep4_mul_reg_gls().
ep4_mul_gls_imp()
static void ep4_mul_gls_imp (ep4_t r, const ep4_t p, const bn_t k) static
Definition at line 85 of file relic_ep4_mul.c.
References bn_free, bn_mod, bn_new, bn_null, bn_rec_frb(), bn_rec_naf(), bn_sign(), ep4_add, ep4_curve_get_ord(), ep4_dbl, ep4_free, ep4_neg(), ep4_new, ep4_norm(), ep4_null, ep4_psi(), ep4_set_infty(), ep4_sub(), ep4_tab(), EP_AFG16, EP_BN, ep_curve_is_pairf(), EP_K16, ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep4_mul_lwnaf().
ep4_mul_reg_gls()
static void ep4_mul_reg_gls (ep4_t r, const ep4_t p, const bn_t k) static
Definition at line 182 of file relic_ep4_mul.c.
References BASIC, bn_abs(), bn_add_dig(), bn_bits(), bn_free, bn_is_even(), bn_mod, bn_new, bn_null, bn_rec_frb(), bn_rec_sac(), bn_sign(), ep4_add, ep4_copy(), ep4_curve_get_ord(), ep4_dbl, ep4_free, ep4_neg(), ep4_new, ep4_norm(), ep4_norm_sim(), ep4_null, ep4_psi(), ep4_set_infty(), ep4_sub(), EP_ADD, EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, fp4_copy_sec(), fp4_set_dig(), fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by ep4_mul_lwreg().
ep4_mul_naf_imp()
static void ep4_mul_naf_imp (ep4_t r, const ep4_t p, const bn_t k) static
Definition at line 324 of file relic_ep4_mul.c.
References bn_rec_naf(), bn_sign(), ep4_add, ep4_dbl, ep4_free, ep4_neg(), ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ep4_sub(), ep4_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep4_mul_lwnaf().
ep4_mul_reg_imp()
static void ep4_mul_reg_imp (ep4_t r, const ep4_t p, const bn_t k) static
Definition at line 376 of file relic_ep4_mul.c.
References BASIC, bn_abs(), bn_bits(), bn_free, bn_is_even(), bn_new, bn_null, bn_rec_reg(), bn_sign(), ep4_add, ep4_curve_get_ord(), ep4_dbl, ep4_free, ep4_neg(), ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ep4_sub(), ep4_tab(), EP_ADD, ERR_CAUGHT, fp4_copy_sec(), fp4_set_dig(), fp_copy_sec(), RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep4_mul_lwreg().
ep4_mul_basic()
void ep4_mul_basic (ep4_t r, const ep4_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 465 of file relic_ep4_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ep4_add, ep4_dbl, ep4_free, ep4_is_infty(), ep4_mul_dig(), ep4_neg(), ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ep4_sub(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), and ep4_mul_cof_k16().
ep4_mul_slide()
void ep4_mul_slide (ep4_t r, const ep4_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 523 of file relic_ep4_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ep4_add, ep4_copy(), ep4_dbl, ep4_free, ep4_is_infty(), ep4_neg(), ep4_new, ep4_norm(), ep4_norm_sim(), ep4_null, ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
ep4_mul_monty()
void ep4_mul_monty (ep4_t r, const ep4_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the constant-time Montgomery ladder point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 593 of file relic_ep4_mul.c.
References bn_abs(), bn_add(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, dv_swap_sec(), ep4_add, ep4_blind(), ep4_curve_get_ord(), ep4_dbl, ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_MAX, RLC_SEL, RLC_THROW, and RLC_TRY.
ep4_mul_lwnaf()
void ep4_mul_lwnaf (ep4_t r, const ep4_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 681 of file relic_ep4_mul.c.
References bn_is_zero(), ep4_is_infty(), ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_set_infty(), and ep_curve_is_endom().
ep4_mul_lwreg()
void ep4_mul_lwreg (ep4_t r, const ep4_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 703 of file relic_ep4_mul.c.
References bn_is_zero(), ep4_is_infty(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_set_infty(), and ep_curve_is_endom().
ep4_mul_gen()
void ep4_mul_gen (ep4_t r, const bn_t k)
Multiplies the generator of an elliptic curve over a qaudratic extension.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 723 of file relic_ep4_mul.c.
References bn_is_zero(), ep4_curve_get_gen(), ep4_curve_get_tab(), ep4_free, ep4_mul, ep4_mul_fix, ep4_new, ep4_null, ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_sim_gen(), and ep4_rand().
ep4_mul_dig()
void ep4_mul_dig (ep4_t r, const ep4_t p, const dig_t k)
Multiplies a prime elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 750 of file relic_ep4_mul.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ep4_add, ep4_copy(), ep4_dbl, ep4_free, ep4_is_infty(), ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ep4_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_basic(), and ep4_mul_cof_k16().