RELIC: src/fp/relic_fp_div.c File Reference
relic_fp_div.c File Reference
Prime field arithmetic
#include "relic_core.h"
#include "relic_fp_low.h"
Functions
void fp_hlv_basic (fp_t c, const fp_t a)
void fp_hlv_integ (fp_t c, const fp_t a)
void fp_trs (fp_t c, const fp_t a)
Detailed Description
Implementation of the prime functions to divide by small constants.
Definition in file relic_fp_div.c.
Function Documentation
fp_hlv_basic()
void fp_hlv_basic (fp_t c, const fp_t a)
Halves a prime field element.
Parameters
[out] c - the result.
[in] a - the prime field element to halve.
Definition at line 41 of file relic_fp_div.c.
References fp_addn_low(), fp_copy(), fp_prime_get(), fp_rsh1_low(), RLC_DIG, and RLC_FP_DIGS.
fp_hlv_integ()
void fp_hlv_integ (fp_t c, const fp_t a)
Halves a prime field element with integrated modular reduction.
Parameters
[out] c - the result.
[in] a - the prime field element to halve.
Definition at line 59 of file relic_fp_div.c.
References fp_hlvm_low().
fp_trs()
void fp_trs (fp_t c, const fp_t a)
Divides a prime field element by 3 (trisecting). Computes C = A/3.
Parameters
[out] C - the result.
[in] A - the first prime field element.
Definition at line 65 of file relic_fp_div.c.
References core_get(), ERR_CAUGHT, fp_copy(), fp_copy_sec(), fp_free, fp_new, fp_null, fp_sub, RLC_3MASK, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_MUL_DIG, RLC_THROW, and RLC_TRY.