RELIC: src/pp/relic_pp_norm.c File Reference
relic_pp_norm.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_md.h"
#include "relic_pp.h"
#include "relic_conf.h"
#include "relic_fp_low.h"
Functions
void pp_norm_k2 (ep_t r, ep_t p)
void pp_norm_k8 (ep2_t r, ep2_t p)
void pp_norm_k12 (ep2_t r, ep2_t p)
Detailed Description
Implementation of point normalization for points used in pairing computation.
Definition in file relic_pp_norm.c.
Function Documentation
pp_norm_k2()
void pp_norm_k2 (ep_t c, ep_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 2.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 42 of file relic_pp_norm.c.
References ep_norm().
pp_norm_k8()
void pp_norm_k8 (ep2_t c, ep2_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 8.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 46 of file relic_pp_norm.c.
References ep2_copy(), ep2_is_infty(), ep2_set_infty(), fp2_inv(), fp2_set_dig(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.
pp_norm_k12()
void pp_norm_k12 (ep2_t c, ep2_t a)
Normalizes the accumulator point used inside pairing computation defined over curves of embedding degree 12.
Parameters
[out] r - the resulting point.
[in] p - the point to normalize.
Definition at line 66 of file relic_pp_norm.c.
References ep2_copy(), ep2_is_infty(), ep2_set_infty(), fp2_inv(), fp_set_dig(), fp_zero(), ep2_st::norm, ep2_st::x, ep2_st::y, and ep2_st::z.