RELIC: src/epx/relic_ep8_dbl.c File Reference
relic_ep8_dbl.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_ep_dbl_tmpl.h"
Functions
TMPL_DBL_BASIC_IMP (ep8, fp8)
TMPL_DBL_PROJC_IMP (ep8, fp8)
TMPL_DBL_JACOB_IMP (ep8, fp8)
void ep8_dbl_basic (ep8_t r, const ep8_t p)
void ep8_dbl_slp_basic (ep8_t r, fp8_t s, const ep8_t p)
void ep8_dbl_projc (ep8_t r, const ep8_t p)
void ep8_dbl_jacob (ep8_t r, const ep8_t p)
Detailed Description
Implementation of doubling on elliptic prime curves over an octic extension field.
Definition in file relic_ep8_dbl.c.
Function Documentation
TMPL_DBL_BASIC_IMP()
TMPL_DBL_BASIC_IMP (ep8 , fp8)
Doubles a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
TMPL_DBL_PROJC_IMP()
TMPL_DBL_PROJC_IMP (ep8 , fp8)
Doubles a point represented in projective coordinates on an ordinary prime elliptic curve.
Parameters
r - the result.
p - the point to double.
TMPL_DBL_JACOB_IMP()
TMPL_DBL_JACOB_IMP (ep8 , fp8)
Doubles a point represented in Jacobian coordinates on an ordinary prime elliptic curve.
Parameters
r - the result.
p - the point to double.
ep8_dbl_basic()
void ep8_dbl_basic (ep8_t r, const ep8_t p)
Doubles a point represented in affine coordinates in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[int] p - the point to double.
Definition at line 86 of file relic_ep8_dbl.c.
References ep8_is_infty(), and ep8_set_infty().
ep8_dbl_slp_basic()
void ep8_dbl_slp_basic (ep8_t r, fp8_t s, const ep8_t p)
Doubles a point represented in affine coordinates in an elliptic curve over an octic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 94 of file relic_ep8_dbl.c.
References ep8_is_infty(), and ep8_set_infty().
Referenced by pp_dbl_k48_basic().
ep8_dbl_projc()
void ep8_dbl_projc (ep8_t r, const ep8_t p)
Doubles a point represented in projective coordinates in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 107 of file relic_ep8_dbl.c.
References ep8_is_infty(), and ep8_set_infty().
ep8_dbl_jacob()
void ep8_dbl_jacob (ep8_t r, const ep8_t p)
Doubles a point represented in Jacobian coordinates in an elliptic curve over an octic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 120 of file relic_ep8_dbl.c.
References ep8_is_infty(), and ep8_set_infty().