RELIC: src/pp/relic_pp_dbl_k1.c File Reference
relic_pp_dbl_k1.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
#include "relic_util.h"
Functions
void pp_dbl_k1_basic (fp_t l, fp_t m, ep_t r, const ep_t p, const ep_t q)
void pp_dbl_k1_projc (fp_t l, fp_t m, ep_t r, const ep_t p, const ep_t q)
Detailed Description
Implementation of Miller doubling for curves of embedding degree 1.
Definition in file relic_pp_dbl_k1.c.
Function Documentation
pp_dbl_k1_basic()
void pp_dbl_k1_basic (fp_t l, fp_t m, ep_t r, const ep_t p, const ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 1 using affine coordinates.
Parameters
[out] l - the numerator of the result of the evaluation.
[out] m - the denominator of the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 47 of file relic_pp_dbl_k1.c.
References ep_dbl_slp_basic(), ERR_CAUGHT, fp_add, fp_free, fp_is_zero(), fp_mul, fp_new, fp_null, fp_set_dig(), fp_sub, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
pp_dbl_k1_projc()
void pp_dbl_k1_projc (fp_t l, fp_t m, ep_t r, const ep_t p, const ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 1 using projective coordinates.
Parameters
[out] l - the numerator of the result of the evaluation.
[out] m - the denominator of the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 74 of file relic_pp_dbl_k1.c.
References ep_curve_get_a(), ERR_CAUGHT, fp_add, fp_dbl, fp_free, fp_is_zero(), fp_mul, fp_new, fp_null, fp_set_dig(), fp_sqr, fp_sub, JACOB, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.