RELIC: src/md/blake2-impl.h File Reference
blake2-impl.h File Reference
#include <stdint.h>
Macros
#define __BLAKE2_IMPL_H__
Functions
static uint32_t load32 (const void *src)
static uint64_t load64 (const void *src)
static void store32 (void *dst, uint32_t w)
static void store64 (void *dst, uint64_t w)
static uint64_t load48 (const void *src)
static void store48 (void *dst, uint64_t w)
static uint32_t rotl32 (const uint32_t w, const unsigned c)
static uint64_t rotl64 (const uint64_t w, const unsigned c)
static uint32_t rotr32 (const uint32_t w, const unsigned c)
static uint64_t rotr64 (const uint64_t w, const unsigned c)
static void secure_zero_memory (void *v, size_t n)
Macro Definition Documentation
__BLAKE2_IMPL_H__
#define __BLAKE2_IMPL_H__
Definition at line 15 of file blake2-impl.h.
Function Documentation
load32()
static uint32_t load32 (const void * src) inline static
Definition at line 19 of file blake2-impl.h.
Referenced by blake2s_compress(), and blake2s_init_param().
load64()
static uint64_t load64 (const void * src) inline static
Definition at line 35 of file blake2-impl.h.
store32()
static void store32 (void * dst, uint32_t w) inline static
Definition at line 55 of file blake2-impl.h.
Referenced by blake2s_final(), blake2s_init(), blake2s_init_key(), and blake2s_param_set_leaf_length().
store64()
static void store64 (void * dst, uint64_t w) inline static
Definition at line 68 of file blake2-impl.h.
load48()
static uint64_t load48 (const void * src) inline static
Definition at line 85 of file blake2-impl.h.
store48()
static void store48 (void * dst, uint64_t w) inline static
Definition at line 97 of file blake2-impl.h.
Referenced by blake2s_init(), blake2s_init_key(), and blake2s_param_set_node_offset().
rotl32()
static uint32_t rotl32 (const uint32_t w, const unsigned c) inline static
Definition at line 108 of file blake2-impl.h.
rotl64()
static uint64_t rotl64 (const uint64_t w, const unsigned c) inline static
Definition at line 113 of file blake2-impl.h.
rotr32()
static uint32_t rotr32 (const uint32_t w, const unsigned c) inline static
Definition at line 118 of file blake2-impl.h.
Referenced by blake2s_compress().
rotr64()
static uint64_t rotr64 (const uint64_t w, const unsigned c) inline static
Definition at line 123 of file blake2-impl.h.
secure_zero_memory()
static void secure_zero_memory (void * v, size_t n) inline static
Definition at line 129 of file blake2-impl.h.
Referenced by blake2s_init_key().