RELIC: src/ed/relic_ed_cmp.c File Reference
relic_ed_cmp.c File Reference
Edwards curves over prime fields.
#include <assert.h>
#include "relic_core.h"
#include "relic_label.h"
#include "relic_md.h"
Functions
int ed_cmp (const ed_t p, const ed_t q)
Detailed Description
Implementation of the Edwards elliptic curve point comparison.
Version
$Id$
Definition in file relic_ed_cmp.c.
Function Documentation
ed_cmp()
int ed_cmp (const ed_t p, const ed_t q)
Compares two Edwards elliptic curve points.
Parameters
[in] p - the first Edwards elliptic curve point.
[in] q - the second Edwards elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 44 of file relic_ed_cmp.c.
References BASIC, ed_copy(), ed_new, ed_norm(), ed_null, ep_free, ERR_CAUGHT, fp_cmp(), fp_mul, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.