RELIC: src/cp/relic_cp_cmlhs.c File Reference
relic_cp_cmlhs.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_cmlhs_init (g1_t h)
int cp_cmlhs_gen (bn_t x[], gt_t hs[], int len, uint8_t prf[], int plen, bn_t sk, g2_t pk, bn_t d, g2_t y)
int cp_cmlhs_sig (g1_t sig, g2_t z, g1_t a, g1_t c, g1_t r, g2_t s, bn_t msg, char *data, int dlen, int label, bn_t x, g1_t h, uint8_t prf[], int plen, bn_t d, bn_t sk)
int cp_cmlhs_fun (g1_t a, g1_t c, g1_t as[], g1_t cs[], dig_t f[], int len)
int cp_cmlhs_evl (g1_t r, g2_t s, g1_t rs[], g2_t ss[], dig_t f[], int len)
int cp_cmlhs_ver (g1_t r, g2_t s, g1_t sig[], g2_t z[], g1_t a[], g1_t c[], bn_t msg, char *data, int dlen, int label[], g1_t h, gt_t hs[][RLC_TERMS], dig_t f[][RLC_TERMS], int flen[], g2_t y[], g2_t pk[], int slen)
Detailed Description
Implementation of context-hiding linearly homomophic signature protocol.
Definition in file relic_cp_cmlhs.c.
Function Documentation
cp_cmlhs_init()
int cp_cmlhs_init (g1_t h)
Initialize the Context-hiding Multi-key Homomorphic Signature scheme (CMLHS). The scheme due to Schabhuser et al. signs a vector of messages.
Parameters
[out] h - the random element (message as one component).
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_cmlhs.c.
References g1_rand, and RLC_OK.
cp_cmlhs_gen()
int cp_cmlhs_gen (bn_t x[], gt_t hs[], int len, uint8_t prf[], int plen, bn_t sk, g2_t pk, bn_t d, g2_t y)
Generates a key pair for the CMLHS scheme using BLS as underlying signature.
Parameters
[out] x - the exponent values, one per label.
[out] hs - the hash values, one per label.
[in] len - the number of possible labels.
[out] prf - the key for the pseudo-random function (PRF).
[out] plen - the PRF key length.
[out] sk - the private key for the BLS signature scheme.
[out] pk - the public key for the BLS signature scheme.
[out] d - the secret exponent.
[out] y - the corresponding public element.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 43 of file relic_cp_cmlhs.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, cp_bls_gen(), FINALLY, g1_free, g1_get_gen, g1_get_ord, g1_new, g1_null, g2_free, g2_get_gen, g2_mul_gen, g2_new, g2_null, gt_exp, gt_free, gt_new, gt_null, pc_map, rand_bytes(), result, RLC_ERR, RLC_OK, and TRY.
cp_cmlhs_sig()
int cp_cmlhs_sig (g1_t sig, g2_t z, g1_t a, g1_t c, g1_t r, g2_t s, bn_t msg, char * data, int dlen, int label, bn_t x, g1_t h, uint8_t prf[], int plen, bn_t sk, bn_t d)
Signs a message vector using the CMLHS.
Parameters
[out] sig - the resulting BLS signature.
[out] z - the power of the output of the PRF.
[out] a - the first component of the signature.
[out] c - the second component of the signature.
[out] r - the third component of the signature.
[out] s - the fourth component of the signature.
[in] msg - the message vector to sign (one component).
[in] data - the dataset identifier.
[in] dlen - the length of the dataset identifier.
[in] label - the integer label.
[in] x - the exponent value for the label.
[in] h - the random value (message has one component).
[in] prf - the key for the pseudo-random function (PRF).
[in] plen - the PRF key length.
[in] sk - the private key for the BLS signature scheme.
[out] d - the secret exponent.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 92 of file relic_cp_cmlhs.c.
References bn_add(), bn_free(), bn_mod, bn_null, bn_rand_mod(), bn_read_bin(), bn_sign(), bn_sub(), CATCH_ANY, cp_bls_sig(), ERR_NO_MEMORY, FINALLY, g1_add, g1_free, g1_get_ord, g1_mul, g1_mul_gen, g1_new, g1_norm, g1_null, g2_mul_gen, g2_neg, g2_write_bin, md_hmac(), result, RLC_ALLOCA, RLC_ERR, RLC_FP_BYTES, RLC_FREE, RLC_NEG, RLC_OK, THROW, and TRY.
cp_cmlhs_fun()
int cp_cmlhs_fun (g1_t a, g1_t c, g1_t as[], g1_t cs[], dig_t f[], int len)
Applies a function over a set of CMLHS signatures from the same user.
Parameters
[out] a - the resulting first component of the signature.
[out] c - the resulting second component of the signature.
[in] as - the vector of first components of the signatures.
[in] cs - the vector of second components of the signatures.
[in] f - the linear coefficients in the function.
[in] len - the number of coefficients.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 174 of file relic_cp_cmlhs.c.
References g1_mul_sim_dig, result, and RLC_OK.
cp_cmlhs_evl()
int cp_cmlhs_evl (g1_t r, g2_t s, g1_t rs[], g2_t ss[], dig_t f[], int len)
Evaluates a function over a set of CMLHS signatures.
Parameters
[out] r - the resulting third component of the signature.
[out] s - the resulting fourth component of the signature.
[in] rs - the vector of third components of the signatures.
[in] ss - the vector of fourth components of the signatures.
[in] f - the linear coefficients in the function.
[in] len - the number of coefficients.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 183 of file relic_cp_cmlhs.c.
References g1_mul_sim_dig, g2_mul_sim_dig, result, and RLC_OK.
cp_cmlhs_ver()
int cp_cmlhs_ver (g1_t r, g2_t s, g1_t sig[], g2_t z[], g1_t a[], g1_t c[], bn_t m, char * data, int dlen, int label[], g1_t h, gt_t hs[][RLC_TERMS], dig_t f[][RLC_TERMS], int flen[], g2_t y[], g2_t pk[], int slen)
Verifies a CMLHS signature over a set of messages.
Parameters
[in] r - the first component of the homomorphic signature.
[in] s - the second component of the homomorphic signature.
[in] sig - the BLS signatures.
[in] z - the powers of the outputs of the PRF.
[in] a - the vector of first components of the signatures.
[in] c - the vector of second components of the signatures.
[in] msg - the combined message.
[in] data - the dataset identifier.
[in] dlen - the length of the dataset identifier.
[in] label - the integer labels.
[in] h - the random element (message has one component).
[in] hs - the hash values, one per label.
[in] f - the linear coefficients in the function.
[in] flen - the number of coefficients.
[in] y - the public elements of the users.
[in] pk - the public keys of the users.
[in] slen - the number of signatures.
Returns
a boolean value indicating the verification result.
Definition at line 192 of file relic_cp_cmlhs.c.
References bn_free(), bn_null, CATCH_ANY, cp_bls_ver(), ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, g1_add, g1_free, g1_get_gen, g1_get_ord, g1_mul, g1_new, g1_norm, g1_null, g1_set_infty, g2_free, g2_get_gen, g2_new, g2_null, g2_write_bin, gt_cmp, gt_exp_dig, gt_free, gt_mul, gt_new, gt_null, pc_map, pc_map_sim, result, RLC_ALLOCA, RLC_EQ, RLC_FP_BYTES, RLC_FREE, THROW, and TRY.