RELIC: src/pp/relic_pp_map_k54.c File Reference
relic_pp_map_k54.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_mil_k54 (fp54_t r, fp9_t qx, fp9_t qy, ep_t p, bn_t a)
void pp_map_k54 (fp54_t r, ep_t p, fp9_t qx, fp9_t qy)
Detailed Description
Implementation of pairing computation for curves with embedding degree 54.
Definition in file relic_pp_map_k54.c.
Function Documentation
pp_mil_k54()
static void pp_mil_k54 (fp54_t r, fp9_t qx, fp9_t qy, ep_t p, bn_t a) static
Definition at line 40 of file relic_pp_map_k54.c.
References bn_bits(), bn_rec_naf(), CATCH_ANY, core_get(), ep_null, ERR_CAUGHT, FINALLY, fp3_mul_nor(), fp3_set_dig(), fp54_free, fp54_mul_dxs(), fp54_new, fp54_null, fp54_zero(), fp9_copy(), fp9_frb(), fp9_free, fp9_inv(), fp9_neg(), fp9_new, fp9_null, fp9_set_dig(), fp9_zero(), fp_copy(), RLC_FP_BITS, THROW, TRY, ep_st::x, and ep_st::y.
Referenced by pp_map_k54().
pp_map_k54()
void pp_map_k54 (fp54_t r, ep_t p, fp9_t qx, fp9_t qy)
Computes the Optimal Ate pairing of two points in a parameterized elliptic curve with embedding degree 54.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 162 of file relic_pp_map_k54.c.
References bn_free(), bn_null, bn_sign(), CATCH_ANY, ep_curve_is_pairf(), ep_is_infty(), EP_K54, ERR_CAUGHT, FINALLY, fp54_inv_cyc(), fp54_set_dig(), fp9_is_zero(), fp_prime_get_par(), pp_exp_k54(), pp_mil_k54(), RLC_NEG, THROW, and TRY.