RELIC: src/epx/relic_ep4_add.c File Reference
relic_ep4_add.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_ep_add_tmpl.h"
Functions
TMPL_ADD_BASIC_IMP (ep4, fp4)
TMPL_ADD_PROJC_MIX (ep4, fp4)
TMPL_ADD_PROJC_IMP (ep4, fp4)
TMPL_ADD_JACOB_MIX (ep4, fp4)
TMPL_ADD_JACOB_IMP (ep4, fp4)
void ep4_add_basic (ep4_t r, const ep4_t p, const ep4_t q)
void ep4_add_slp_basic (ep4_t r, fp4_t s, const ep4_t p, const ep4_t q)
void ep4_add_projc (ep4_t r, const ep4_t p, const ep4_t q)
void ep4_add_jacob (ep4_t r, const ep4_t p, const ep4_t q)
void ep4_sub (ep4_t r, const ep4_t p, const ep4_t q)
Detailed Description
Implementation of addition on prime elliptic curves over a quartic extension field.
Definition in file relic_ep4_add.c.
Function Documentation
TMPL_ADD_BASIC_IMP()
TMPL_ADD_BASIC_IMP (ep4 , fp4)
Adds two points represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
TMPL_ADD_PROJC_MIX()
TMPL_ADD_PROJC_MIX (ep4 , fp4)
Adds a point represented in homogeneous coordinates to a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the projective point.
[in] q - the affine point.
TMPL_ADD_PROJC_IMP()
TMPL_ADD_PROJC_IMP (ep4 , fp4)
Adds two points represented in homogeneous coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
TMPL_ADD_JACOB_MIX()
TMPL_ADD_JACOB_MIX (ep4 , fp4)
Adds a point represented in Jacobian coordinates to a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the projective point.
[in] q - the affine point.
TMPL_ADD_JACOB_IMP()
TMPL_ADD_JACOB_IMP (ep4 , fp4)
Adds two points represented in Jacobian coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
ep4_add_basic()
void ep4_add_basic (ep4_t r, const ep4_t p, const ep4_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 109 of file relic_ep4_add.c.
References ep4_copy(), and ep4_is_infty().
ep4_add_slp_basic()
void ep4_add_slp_basic (ep4_t r, fp4_t s, const ep4_t p, const ep4_t q)
Adds to points represented in affine coordinates in an elliptic curve over a quartic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 123 of file relic_ep4_add.c.
References ep4_copy(), and ep4_is_infty().
Referenced by pp_add_k16_basic(), and pp_add_k24_basic().
ep4_add_projc()
void ep4_add_projc (ep4_t r, const ep4_t p, const ep4_t q)
Adds two points represented in projective coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 141 of file relic_ep4_add.c.
References ep4_copy(), and ep4_is_infty().
ep4_add_jacob()
void ep4_add_jacob (ep4_t r, const ep4_t p, const ep4_t q)
Adds two points represented in Jacobian coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 159 of file relic_ep4_add.c.
References ep4_copy(), and ep4_is_infty().
ep4_sub()
void ep4_sub (ep4_t r, const ep4_t p, const ep4_t q)
Subtracts a point in an elliptic curve over a quartic extension from another.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 175 of file relic_ep4_add.c.
References ep4_add, ep4_free, ep4_neg(), ep4_new, ep4_null, ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep4_mul_basic(), ep4_mul_cof_afg16(), ep4_mul_cof_b24(), ep4_mul_cof_fm16(), ep4_mul_cof_k16(), ep4_mul_dig(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_plain(), and ep4_psi().