RELIC: src/fpx/relic_fp12_mul.c File Reference
relic_fp12_mul.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
static void fp6_mul_dxs_unr_lazyr (dv6_t c, fp6_t a, fp6_t b)
void fp12_mul_basic (fp12_t c, fp12_t a, fp12_t b)
void fp12_mul_dxs_basic (fp12_t c, fp12_t a, fp12_t b)
void fp12_mul_unr (dv12_t c, fp12_t a, fp12_t b)
void fp12_mul_lazyr (fp12_t c, fp12_t a, fp12_t b)
void fp12_mul_dxs_lazyr (fp12_t c, fp12_t a, fp12_t b)
void fp12_mul_art (fp12_t c, fp12_t a)
Detailed Description
Implementation of multiplication in a dodecic extension of a prime field.
Definition in file relic_fp12_mul.c.
Function Documentation
fp6_mul_dxs_unr_lazyr()
static void fp6_mul_dxs_unr_lazyr (dv6_t c, fp6_t a, fp6_t b) inline static
Definition at line 42 of file relic_fp12_mul.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_addm_low(), fp2_addn_low(), fp2_free, fp2_mulc_low(), fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_norh_low(), fp2_null, fp2_subc_low(), THROW, and TRY.
Referenced by fp12_mul_dxs_lazyr().
fp12_mul_basic()
void fp12_mul_basic (fp12_t c, fp12_t a, fp12_t b)
Multiples two dodecic extension field elements using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
[in] b - the dodecic extension field element.
Definition at line 120 of file relic_fp12_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_add(), fp6_free, fp6_mul_art(), fp6_new, fp6_null, fp6_sub(), THROW, and TRY.
fp12_mul_dxs_basic()
void fp12_mul_dxs_basic (fp12_t c, fp12_t a, fp12_t b)
Multiples a dense dodecic extension field element by a sparse element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the dense dodecic extension field element.
[in] b - the sparse dodecic extension field element.
Definition at line 161 of file relic_fp12_mul.c.
References CATCH_ANY, ep2_curve_is_twist(), EP_DTYPE, ERR_CAUGHT, FINALLY, fp2_copy(), fp6_add(), fp6_free, fp6_mul_art(), fp6_mul_dxs(), fp6_new, fp6_null, fp6_sub(), fp_copy(), THROW, and TRY.
fp12_mul_unr()
void fp12_mul_unr (dv12_t c, fp12_t a, fp12_t b)
Multiples two dodecic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
[in] b - the dodecic extension field element.
Definition at line 248 of file relic_fp12_mul.c.
References CATCH_ANY, dv6_free, dv6_new, dv6_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_nord_low(), fp2_subc_low(), fp6_add(), fp6_free, fp6_mul_unr(), fp6_new, fp6_null, THROW, and TRY.
Referenced by fp12_mul_lazyr().
fp12_mul_lazyr()
void fp12_mul_lazyr (fp12_t c, fp12_t a, fp12_t b)
Multiples two dodecic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element.
[in] b - the dodecic extension field element.
Definition at line 301 of file relic_fp12_mul.c.
References CATCH_ANY, dv12_free, dv12_new, dv12_null, ERR_CAUGHT, FINALLY, fp12_mul_unr(), fp2_rdcn_low(), THROW, and TRY.
fp12_mul_dxs_lazyr()
void fp12_mul_dxs_lazyr (fp12_t c, fp12_t a, fp12_t b)
Multiples a dense dodecic extension field element by a sparse element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the dense dodecic extension field element.
[in] b - the sparse dodecic extension field element.
Definition at line 320 of file relic_fp12_mul.c.
References CATCH_ANY, dv6_free, dv6_new, dv6_null, ep2_curve_is_twist(), EP_DTYPE, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_copy(), fp2_mulc_low(), fp2_muln_low(), fp2_nord_low(), fp2_rdcn_low(), fp2_subc_low(), fp6_add(), fp6_free, fp6_mul_dxs_unr_lazyr(), fp6_new, fp6_null, fp_copy(), fp_muln_low(), THROW, and TRY.
fp12_mul_art()
void fp12_mul_art (fp12_t c, fp12_t a)
Multiplies a dodecic extension field element by the adjoined root.
Parameters
[out] c - the result.
[in] a - the dodecic extension field element to multiply.
Definition at line 424 of file relic_fp12_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp6_copy(), fp6_free, fp6_mul_art(), fp6_new, fp6_null, THROW, and TRY.