RELIC: src/epx/relic_ep2_mul_sim.c File Reference
relic_ep2_mul_sim.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep2_mul_sim_plain (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m, ep2_t *t)
void ep2_mul_sim_basic (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t l)
void ep2_mul_sim_trick (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
void ep2_mul_sim_inter (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
void ep2_mul_sim_joint (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
void ep2_mul_sim_gen (ep2_t r, bn_t k, ep2_t q, bn_t m)
void ep2_mul_sim_dig (ep2_t r, ep2_t p[], dig_t k[], int len)
Detailed Description
Implementation of simultaneous point multiplication on a prime elliptic curve over a quadratic extension.
Definition in file relic_ep2_mul_sim.c.
Function Documentation
ep2_mul_sim_plain()
static void ep2_mul_sim_plain (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m, ep2_t * t) static
Definition at line 41 of file relic_ep2_mul_sim.c.
References bn_rec_naf(), bn_sign(), CATCH_ANY, ep2_norm(), ep2_null, ep2_set_infty(), ep2_tab(), EP_DEPTH, EP_WIDTH, ERR_CAUGHT, FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, THROW, and TRY.
Referenced by ep2_mul_sim_gen(), and ep2_mul_sim_inter().
ep2_mul_sim_basic()
void ep2_mul_sim_basic (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 144 of file relic_ep2_mul_sim.c.
References CATCH_ANY, ep2_norm(), ep2_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
ep2_mul_sim_trick()
void ep2_mul_sim_trick (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 168 of file relic_ep2_mul_sim.c.
References bn_free(), bn_is_zero(), bn_null, bn_rec_win(), bn_sign(), CATCH_ANY, ep2_copy(), ep2_curve_get_ord(), ep2_is_infty(), ep2_norm(), ep2_norm_sim(), ep2_null, ep2_set_infty(), EP_WIDTH, ERR_CAUGHT, FINALLY, RLC_CEIL, RLC_FP_BITS, RLC_MAX, RLC_NEG, THROW, and TRY.
ep2_mul_sim_inter()
void ep2_mul_sim_inter (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 268 of file relic_ep2_mul_sim.c.
References bn_is_zero(), ep2_is_infty(), and ep2_mul_sim_plain().
ep2_mul_sim_joint()
void ep2_mul_sim_joint (ep2_t r, ep2_t p, bn_t k, ep2_t q, bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 295 of file relic_ep2_mul_sim.c.
References bn_bits(), bn_is_zero(), bn_rec_jsf(), bn_sign(), CATCH_ANY, ep2_copy(), ep2_is_infty(), ep2_norm(), ep2_norm_sim(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, THROW, and TRY.
ep2_mul_sim_gen()
void ep2_mul_sim_gen (ep2_t r, bn_t k, ep2_t q, bn_t m)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = kG + lQ.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 368 of file relic_ep2_mul_sim.c.
References bn_is_zero(), CATCH_ANY, ep2_curve_get_gen(), ep2_curve_get_tab(), ep2_is_infty(), ep2_mul_gen(), ep2_mul_sim_plain(), ep2_null, ERR_CAUGHT, FINALLY, THROW, and TRY.
ep2_mul_sim_dig()
void ep2_mul_sim_dig (ep2_t r, ep2_t p[], dig_t k[], int len)
Multiplies prime elliptic curve points by small scalars. Computes R = \sum k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the small scalars.
[in] len - the number of points to multiply.
Definition at line 400 of file relic_ep2_mul_sim.c.
References CATCH_ANY, ep2_norm(), ep2_null, ep2_set_infty(), ERR_CAUGHT, FINALLY, RLC_MAX, THROW, TRY, and util_bits_dig().