RELIC: src/epx/relic_ep3_curve.c File Reference
relic_ep3_curve.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Macros
#define ASSIGN(CURVE)
Functions
static void detect_opt (int *opt, fp3_t a)
void ep3_curve_init (void)
void ep3_curve_clean (void)
int ep3_curve_opt_a (void)
int ep3_curve_opt_b (void)
void ep3_curve_mul_a (fp3_t c, const fp3_t a)
void ep3_curve_mul_b (fp3_t c, const fp3_t a)
int ep3_curve_is_twist (void)
void ep3_curve_get_gen (ep3_t g)
fp_t * ep3_curve_get_a (void)
fp_t * ep3_curve_get_b (void)
void ep3_curve_get_ord (bn_t n)
void ep3_curve_get_cof (bn_t h)
ep3_t * ep3_curve_get_tab (void)
void ep3_curve_set_twist (int type)
void ep3_curve_set (const fp3_t a, const fp3_t b, const ep3_t g, const bn_t r, const bn_t h)
Detailed Description
Implementation of configuration of prime elliptic curves over a cubic extension field.
Definition in file relic_ep3_curve.c.
Macro Definition Documentation
ASSIGN
#define ASSIGN (CURVE)
Value:
    RLC_GET(str, CURVE##_A0, sizeof(CURVE##_A0));                           \
    fp_read_str(a[0], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_A1, sizeof(CURVE##_A1));                           \
    fp_read_str(a[1], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_A2, sizeof(CURVE##_A2));                           \
    fp_read_str(a[2], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_B0, sizeof(CURVE##_B0));                           \
    fp_read_str(b[0], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_B1, sizeof(CURVE##_B1));                           \
    fp_read_str(b[1], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_B2, sizeof(CURVE##_B2));                           \
    fp_read_str(b[2], str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_X0, sizeof(CURVE##_X0));                           \
    fp_read_str(g->x[0], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_X1, sizeof(CURVE##_X1));                           \
    fp_read_str(g->x[1], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_X2, sizeof(CURVE##_X2));                           \
    fp_read_str(g->x[2], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_Y0, sizeof(CURVE##_Y0));                           \
    fp_read_str(g->y[0], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_Y1, sizeof(CURVE##_Y1));                           \
    fp_read_str(g->y[1], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_Y2, sizeof(CURVE##_Y2));                           \
    fp_read_str(g->y[2], str, strlen(str), 16);                             \
    RLC_GET(str, CURVE##_R, sizeof(CURVE##_R));                             \
    bn_read_str(r, str, strlen(str), 16);                                   \
    RLC_GET(str, CURVE##_H, sizeof(CURVE##_H));                             \
    bn_read_str(h, str, strlen(str), 16);                                   \
Assigns a set of ordinary elliptic curve parameters.
Parameters
[in] CURVE - the curve parameters to assign.
Definition at line 143 of file relic_ep3_curve.c.
Referenced by ep3_curve_set_twist().
Function Documentation
detect_opt()
static void detect_opt (int * opt, fp3_t a) static
Detects an optimization based on the curve coefficients.
Definition at line 176 of file relic_ep3_curve.c.
References ERR_CAUGHT, fp3_cmp(), fp3_cmp_dig(), fp3_free, fp3_is_zero(), fp3_neg(), fp3_new, fp3_null, fp3_set_dig(), fp_bits(), fp_is_zero(), RLC_CATCH_ANY, RLC_DIG, RLC_EQ, RLC_FINALLY, RLC_HUGE, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep3_curve_set_twist().
ep3_curve_init()
void ep3_curve_init (void)
Initializes the elliptic curve over cubic extension.
Definition at line 212 of file relic_ep3_curve.c.
References bn_make(), core_get(), _ctx_t::ep3_a, _ctx_t::ep3_b, _ctx_t::ep3_frb, _ctx_t::ep3_g, _ctx_t::ep3_h, ep3_new, _ctx_t::ep3_pre, _ctx_t::ep3_ptr, _ctx_t::ep3_r, fp3_new, RLC_EP_TABLE, RLC_FP_DIGS, ep3_st::x, ep3_st::y, and ep3_st::z.
Referenced by pp_map_init().
ep3_curve_clean()
void ep3_curve_clean (void)
Finalizes the elliptic curve over cubic extension.
Definition at line 243 of file relic_ep3_curve.c.
References bn_clean(), core_get(), _ctx_t::ep3_a, _ctx_t::ep3_b, _ctx_t::ep3_frb, ep3_free, _ctx_t::ep3_g, _ctx_t::ep3_h, _ctx_t::ep3_pre, _ctx_t::ep3_r, fp3_free, RLC_EP_TABLE, ep3_st::x, ep3_st::y, and ep3_st::z.
Referenced by pp_map_clean().
ep3_curve_opt_a()
int ep3_curve_opt_a (void)
Returns a optimization identifier based on the 'a' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 264 of file relic_ep3_curve.c.
References core_get(), and _ctx_t::ep3_opt_a.
Referenced by ep3_rhs().
ep3_curve_opt_b()
int ep3_curve_opt_b (void)
Returns b optimization identifier based on the 'b' coefficient of the curve.
Returns
the optimization identifier.
Definition at line 268 of file relic_ep3_curve.c.
References core_get(), and _ctx_t::ep3_opt_b.
Referenced by ep3_rhs().
ep3_curve_mul_a()
void ep3_curve_mul_a (fp3_t c, const fp3_t a)
Multiplies a field element by the a-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 272 of file relic_ep3_curve.c.
References core_get(), _ctx_t::ep3_a, _ctx_t::ep3_opt_a, fp3_copy(), fp3_dbl, fp3_mul, fp3_mul_dig(), fp3_zero(), RLC_ONE, RLC_TINY, RLC_TWO, and RLC_ZERO.
ep3_curve_mul_b()
void ep3_curve_mul_b (fp3_t c, const fp3_t a)
Multiplies a field element by the b-coefficient of the curve.
Parameters
[out] c - the result.
[in] a - the field element to multiply.
Definition at line 295 of file relic_ep3_curve.c.
References core_get(), _ctx_t::ep3_b, _ctx_t::ep3_opt_b, fp3_copy(), fp3_mul, fp3_mul_dig(), fp3_zero(), RLC_ONE, RLC_TINY, and RLC_ZERO.
ep3_curve_is_twist()
int ep3_curve_is_twist (void)
Tests if the configured elliptic curve is a twist.
Returns
the type of the elliptic curve twist, 0 if non-twisted curve.
Definition at line 315 of file relic_ep3_curve.c.
References core_get(), and _ctx_t::ep3_is_twist.
Referenced by fp18_mul_dxs_lazyr(), pp_add_k18_basic(), pp_add_k18_projc_basic(), pp_add_k18_projc_lazyr(), pp_dbl_k18_basic(), pp_dbl_k18_projc_basic(), and pp_dbl_k18_projc_lazyr().
ep3_curve_get_gen()
void ep3_curve_get_gen (ep3_t g)
Returns the generator of the group of points in the elliptic curve.
Parameters
[out] g - the returned generator.
Definition at line 319 of file relic_ep3_curve.c.
References core_get(), and ep3_copy().
Referenced by ep3_mul_gen(), and ep3_mul_sim_gen().
ep3_curve_get_a()
fp_t * ep3_curve_get_a (void)
Returns the 'a' coefficient of the currently configured elliptic curve.
Returns
the 'a' coefficient of the elliptic curve.
Definition at line 323 of file relic_ep3_curve.c.
References core_get(), and _ctx_t::ep3_a.
Referenced by ep3_rhs().
ep3_curve_get_b()
fp_t * ep3_curve_get_b (void)
Returns the 'b' coefficient of the currently configured elliptic curve.
Parameters
[out] b - the 'b' coefficient of the elliptic curve.
Definition at line 327 of file relic_ep3_curve.c.
References core_get(), and _ctx_t::ep3_b.
Referenced by ep3_rhs(), pp_dbl_k18_projc_basic(), and pp_dbl_k18_projc_lazyr().
ep3_curve_get_ord()
void ep3_curve_get_ord (bn_t n)
Returns the order of the group of points in the elliptic curve.
Parameters
[out] n - the returned order.
Definition at line 331 of file relic_ep3_curve.c.
References bn_copy(), core_get(), _ctx_t::ep3_is_twist, _ctx_t::ep3_r, and ep_curve_get_ord().
Referenced by ep3_mul_fix_basic(), ep3_mul_fix_combd(), ep3_mul_fix_combs(), ep3_mul_fix_lwnaf(), ep3_mul_gls_imp(), ep3_mul_monty(), ep3_mul_pre_basic(), ep3_mul_pre_combd(), ep3_mul_pre_combs(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_trick(), and ep3_rand().
ep3_curve_get_cof()
void ep3_curve_get_cof (bn_t h)
Returns the cofactor of the group order in the elliptic curve.
Parameters
[out] h - the returned cofactor.
Definition at line 340 of file relic_ep3_curve.c.
References bn_copy(), and core_get().
Referenced by ep3_mul_cof().
ep3_curve_get_tab()
ep3_t * ep3_curve_get_tab (void)
Returns the precomputation table for the generator.
Returns
the table.
Definition at line 346 of file relic_ep3_curve.c.
References core_get(), and _ctx_t::ep3_ptr.
Referenced by ep3_curve_set(), ep3_curve_set_twist(), ep3_mul_gen(), and ep3_mul_sim_gen().
ep3_curve_set_twist()
void ep3_curve_set_twist (int type)
Configures an elliptic curve by twisting the curve over the base prime field.
Parameters
- the type of twist (multiplicative or divisive)
Definition at line 356 of file relic_ep3_curve.c.
References ASSIGN, BASIC, bn_copy(), bn_free, bn_new, bn_null, core_get(), detect_opt(), _ctx_t::ep3_a, _ctx_t::ep3_b, ep3_copy(), ep3_curve_get_tab(), _ctx_t::ep3_frb, ep3_free, _ctx_t::ep3_g, _ctx_t::ep3_h, _ctx_t::ep3_is_twist, ep3_mul_pre, ep3_new, ep3_null, _ctx_t::ep3_opt_a, _ctx_t::ep3_opt_b, _ctx_t::ep3_r, ep_param_get(), ERR_CAUGHT, ERR_NO_VALID, FM18_P768, fp18_free, fp18_inv(), fp18_new, fp18_null, fp18_zero(), fp3_copy(), fp3_free, fp3_inv(), fp3_mul_art(), fp3_new, fp3_null, _ctx_t::fp3_p1, fp3_set_dig(), fp3_zero(), fp9_set_dig(), fp_copy(), K18_P354, K18_P508, K18_P638, pc_core_calc(), RLC_CATCH_ANY, RLC_EP_DTYPE, RLC_EP_MTYPE, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, RLC_TRY, and SG18_P638.
Referenced by ep_param_set_any_pairf().
ep3_curve_set()
void ep3_curve_set (const fp3_t a, const fp3_t b, const ep3_t g, const bn_t r, const bn_t h)
Configures an elliptic curve over a cubic extension by its coefficients.
Parameters
[in] a - the 'a' coefficient of the curve.
[in] b - the 'b' coefficient of the curve.
[in] g - the generator.
[in] r - the order of the group of points.
[in] h - the cofactor of the group order.
Definition at line 467 of file relic_ep3_curve.c.
References bn_copy(), core_get(), _ctx_t::ep3_a, _ctx_t::ep3_b, ep3_curve_get_tab(), _ctx_t::ep3_g, _ctx_t::ep3_h, _ctx_t::ep3_is_twist, ep3_mul_pre, ep3_norm(), _ctx_t::ep3_r, and fp3_copy().