RELIC: src/pp/relic_pp_dbl_k2.c File Reference
relic_pp_dbl_k2.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
#include "relic_util.h"
Functions
void pp_dbl_k2_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
void pp_dbl_k2_projc_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
void pp_dbl_k2_projc_lazyr (fp2_t l, ep_t r, ep_t p, ep_t q)
Detailed Description
Implementation of Miller doubling for curves of embedding degree 2.
Definition in file relic_pp_dbl_k2.c.
Function Documentation
pp_dbl_k2_basic()
void pp_dbl_k2_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 2 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k2.c.
References CATCH_ANY, ep_copy(), ep_dbl_slp_basic(), ep_null, ERR_CAUGHT, FINALLY, fp_copy(), fp_null, THROW, TRY, ep_st::x, and ep_st::y.
pp_dbl_k2_projc_basic()
void pp_dbl_k2_projc_basic (fp2_t l, ep_t r, ep_t p, ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 75 of file relic_pp_dbl_k2.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp_null, ep_st::norm, THROW, TRY, ep_st::x, ep_st::y, and ep_st::z.
pp_dbl_k2_projc_lazyr()
void pp_dbl_k2_projc_lazyr (fp2_t l, ep_t r, ep_t p, ep_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 164 of file relic_pp_dbl_k2.c.
References CATCH_ANY, dv_null, ERR_CAUGHT, FINALLY, fp_addc_low(), fp_muln_low(), fp_null, fp_rdcn_low(), fp_sqrn_low(), fp_subc_low(), fp_subm_low(), ep_st::norm, THROW, TRY, ep_st::x, ep_st::y, and ep_st::z.