RELIC: src/eb/relic_eb_frb.c File Reference
relic_eb_frb.c File Reference
Elliptic curves over binary fields
#include "string.h"
#include "relic_core.h"
#include "relic_eb.h"
Functions
void eb_frb_basic (eb_t r, const eb_t p)
void eb_frb_projc (eb_t r, const eb_t p)
Detailed Description
Implementation of the Frobenius map on binary elliptic curves.
Definition in file relic_eb_frb.c.
Function Documentation
eb_frb_basic()
void eb_frb_basic (eb_t r, const eb_t p)
Computes the Frobenius map of a binary elliptic curve point represented by affine coordinates.
Parameters
[out] r - the result.
[in] p - the point.
Definition at line 45 of file relic_eb_frb.c.
References eb_is_infty(), eb_set_infty(), fb_set_bit(), fb_zero(), eb_st::norm, eb_st::x, eb_st::y, and eb_st::z.
eb_frb_projc()
void eb_frb_projc (eb_t r, const eb_t p)
Computes the Frobenius map of a binary elliptic curve point represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the point.
Definition at line 63 of file relic_eb_frb.c.
References eb_is_infty(), eb_set_infty(), fb_set_dig(), eb_st::norm, eb_st::x, eb_st::y, and eb_st::z.