RELIC: src/ed/relic_ed_map.c File Reference
relic_ed_map.c File Reference
Edwards curves over Edwards fields
#include "relic_core.h"
#include "relic_md.h"
Functions
void ed_map (ed_t p, const uint8_t *msg, int len)
Detailed Description
Implementation of hashing to a prime elliptic curve.
Version
$Id$
Definition in file relic_ed_map.c.
Function Documentation
ed_map()
void ed_map (ed_t p, const uint8_t * msg, int len)
Maps a byte array to a point in an Edwards elliptic curve.
Parameters
[out] p - the result.
[in] msg - the byte array to map.
[in] len - the array length in bytes.
Definition at line 40 of file relic_ed_map.c.
References bn_free(), bn_null, bn_read_bin(), bn_rsh(), bn_sub_dig(), CATCH_ANY, core_get(), bn_st::dp, dv_copy(), ed_norm(), ERR_CAUGHT, FINALLY, fp_add_dig(), fp_cmp(), fp_null, fp_prime_conv(), fp_prime_get(), fp_set_dig(), fp_sub_dig(), ed_st::norm, RLC_DIG, RLC_EQ, RLC_FP_BYTES, RLC_FP_DIGS, RLC_MIN, ed_st::t, THROW, TRY, bn_st::used, ed_st::x, ed_st::y, and ed_st::z.