RELIC: src/pp/relic_pp_dbl_k12.c File Reference
relic_pp_dbl_k12.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
#include "relic_util.h"
Functions
void pp_dbl_k12_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k12_projc_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k12_projc_lazyr (fp12_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_lit_k12 (fp12_t l, ep_t r, ep_t p, ep2_t q)
Detailed Description
Implementation of Miller doubling for curves of embedding degree 12.
Definition in file relic_pp_dbl_k12.c.
Function Documentation
pp_dbl_k12_basic()
void pp_dbl_k12_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k12.c.
References CATCH_ANY, ep2_copy(), ep2_curve_is_twist(), ep2_dbl_slp_basic(), ep2_null, EP_MTYPE, ERR_CAUGHT, FINALLY, fp12_zero(), fp2_free, fp2_new, fp2_null, fp_copy(), THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, and ep_st::y.
pp_dbl_k12_projc_basic()
void pp_dbl_k12_projc_basic (fp12_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 85 of file relic_pp_dbl_k12.c.
References CATCH_ANY, ep2_curve_get_b(), ep2_curve_is_twist(), ep_curve_opt_b(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, ep2_st::norm, RLC_TWO, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_dbl_k12_projc_lazyr()
void pp_dbl_k12_projc_lazyr (fp12_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 12 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 239 of file relic_pp_dbl_k12.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ep2_curve_get_b(), ep2_curve_is_twist(), ep_curve_opt_b(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_addd_low(), fp2_free, fp2_new, fp2_null, fp2_rdcn_low(), fp2_sqrn_low(), fp2_subc_low(), ep2_st::norm, RLC_TWO, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_dbl_lit_k12()
void pp_dbl_lit_k12 (fp12_t l, ep_t r, ep_t p, ep2_t q)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve twist with embedding degree 12 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] p - the point to double.
[in] q - the affine point to evaluate the line function.
Definition at line 408 of file relic_pp_dbl_k12.c.
References CATCH_ANY, ep2_curve_is_twist(), ep_curve_get_b(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp_null, fp_zero(), ep_st::norm, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep_st::z.
Referenced by pp_mil_lit_k12().