RELIC: include/relic_md.h File Reference
relic_md.h File Reference
Hash functions
#include "relic_conf.h"
#include "relic_types.h"
#include "relic_label.h"
Macros
#define MD_LEN MD_LEN_SH256
#define md_map(H, M, L) md_map_sh256(H, M, L)
Enumerations
enum {
MD_LEN_SHONE = 20, MD_LEN_SH224 = 28, MD_LEN_SH256 = 32, MD_LEN_SH384 = 48,
MD_LEN_SH512 = 64
}
Functions
void md_map_shone (uint8_t *hash, const uint8_t *msg, int len)
void md_map_shone_mid (uint8_t *state, uint8_t *msg, int len)
void md_map_sh224 (uint8_t *hash, const uint8_t *msg, int len)
void md_map_sh256 (uint8_t *hash, const uint8_t *msg, int len)
void md_map_sh384 (uint8_t *hash, const uint8_t *msg, int len)
void md_map_sh512 (uint8_t *hash, const uint8_t *msg, int len)
void md_kdf1 (uint8_t *key, int key_len, const uint8_t *in, int in_len)
void md_kdf2 (uint8_t *key, int key_len, const uint8_t *in, int in_len)
void md_mgf1 (uint8_t *mask, int mask_len, const uint8_t *in, int in_len)
void md_hmac (uint8_t *mac, const uint8_t *in, int in_len, const uint8_t *key, int key_len)
Detailed Description
Interface of the module for computing hash functions.
Version
Id
relic_md.h 1776 2014-02-07 11:12:28Z dfaranha
Definition in file relic_md.h.
Macro Definition Documentation
#define MD_LEN MD_LEN_SH256
Length in bytes of default hash function output.
Definition at line 68 of file relic_md.h.
Referenced by cp_bbs_sig(), cp_bbs_ver(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecies_dec(), cp_ecies_enc(), cp_ecss_sig(), cp_ecss_ver(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), eb_map(), ep2_map(), ep_map(), md_hmac(), md_kdf1(), md_kdf2(), rand_bytes(), rand_gen(), and rand_hash().
#define md_map (H, M, L) md_map_sh256(H, M, L)
Maps a byte vector to a fixed-length byte vector using the chosen hash function.
Parameters
[out] H - the digest.
[in] M - the message to hash.
[in] L - the message length in bytes.
Definition at line 92 of file relic_md.h.
Referenced by cp_bbs_sig(), cp_bbs_ver(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_sig(), cp_ecss_ver(), cp_rsa_sig_basic(), cp_rsa_sig_quick(), cp_rsa_ver(), eb_map(), ep2_map(), ep_map(), md_hmac(), md_kdf1(), md_kdf2(), rand_bytes(), rand_gen(), and rand_hash().
Enumeration Type Documentation
anonymous enum
Enumerator
MD_LEN_SHONE
Hash length for SHA-1 function.
MD_LEN_SH224
Hash kength for SHA-224 function.
MD_LEN_SH256
Hash kength for SHA-256 function.
MD_LEN_SH384
Hash kength for SHA-384 function.
MD_LEN_SH512
Hash kength for SHA-512 function.
Definition at line 47 of file relic_md.h.
Function Documentation
void md_map_shone (uint8_t * hash, const uint8_t * msg, int len)
Computes the SHA-1 hash function.
Parameters
[out] hash - the digest.
[in] msg - the message to hash.
[in] len - the message length in bytes.
Definition at line 46 of file relic_md_sha1.c.
References ERR_NO_VALID, SHA1Input(), SHA1Reset(), SHA1Result(), shaSuccess, and THROW.
void md_map_shone_mid (uint8_t * state, uint8_t * msg, int len)
Returns the internal state of the hash function.
Parameters
[out] state - the internal state.
[in] msg - the message to hash.
[in] len - the message length in bytes.
void md_map_sh224 (uint8_t * hash, const uint8_t * msg, int len)
Computes the SHA-224 hash function.
Parameters
[out] hash - the digest.
[in] msg - the message to hash.
[in] len - the message length in bytes.
Definition at line 43 of file relic_md_sha224.c.
References ERR_NO_VALID, SHA224Input(), SHA224Reset(), SHA224Result(), shaSuccess, and THROW.
void md_map_sh256 (uint8_t * hash, const uint8_t * msg, int len)
Computes the SHA-256 hash function.
Parameters
[out] hash - the digest.
[in] msg - the message to hash.
[in] len - the message length in bytes.
Definition at line 43 of file relic_md_sha256.c.
References ERR_NO_VALID, SHA256Input(), SHA256Reset(), SHA256Result(), shaSuccess, and THROW.
void md_map_sh384 (uint8_t * hash, const uint8_t * msg, int len)
Computes the SHA-384 hash function.
Parameters
[out] hash - the digest.
[in] msg - the message to hash.
[in] len - the message length in bytes.
Definition at line 43 of file relic_md_sha384.c.
References ERR_NO_VALID, SHA384Input(), SHA384Reset(), SHA384Result(), shaSuccess, and THROW.
void md_map_sh512 (uint8_t * hash, const uint8_t * msg, int len)
Computes the SHA-512 hash function.
Parameters
[out] hash - the digest.
[in] msg - the message to hash.
[in] len - the message length in bytes.
Definition at line 43 of file relic_md_sha512.c.
References ERR_NO_VALID, SHA512Input(), SHA512Reset(), SHA512Result(), shaSuccess, and THROW.
void md_kdf1 (uint8_t * key, int key_len, const uint8_t * in, int in_len)
Derives a key from shared secret material through the standardized KDF1 function.
Parameters
[out] key - the resulting key.
[in] key_len - the intended key length in bytes.
[in] in - the shared secret.
[in] in_len - the length of the shared secret in bytes.
Definition at line 43 of file relic_md_kdf.c.
References CEIL, MD_LEN, md_map, and util_conv_big().
Referenced by cp_sokaka_key(), and md_mgf1().
void md_kdf2 (uint8_t * key, int key_len, const uint8_t * in, int in_len)
Derives a key from shared secret material through the standardized KDF2 function.
Parameters
[out] key - the resulting key.
[in] key_len - the intended key length in bytes.
[in] in - the shared secret.
[in] in_len - the length of the shared secret in bytes.
Definition at line 62 of file relic_md_kdf.c.
References CEIL, MD_LEN, md_map, and util_conv_big().
Referenced by cp_ecdh_key(), cp_ecies_dec(), cp_ecies_enc(), and cp_ecmqv_key().
void md_mgf1 (uint8_t * mask, int mask_len, const uint8_t * in, int in_len)
Derives a mask from shared secret material through the PKCS#1 2.0 MGF1 function .
Parameters
[out] key - the resulting mask.
[in] key_len - the intended mask length in bytes.
[in] in - the shared secret.
[in] in_len - the length of the shared secret in bytes.
Definition at line 43 of file relic_md_mgf.c.
References md_kdf1().
void md_hmac (uint8_t * mac, const uint8_t * in, int in_len, const uint8_t * key, int key_len)
Computes a Message Authentication Code through HMAC.
Parameters
[out] mac - the authentication.
[in] in - the date to authenticate.
[in] in_len - the number of bytes to authenticate.
[in] key - the cryptographic key.
[in] key_len - the size of the key in bytes.
Definition at line 43 of file relic_md_hmac.c.
References MD_LEN, and md_map.
Referenced by cp_ecies_dec(), and cp_ecies_enc().