RELIC: src/cp/relic_cp_pbpsi.c File Reference
relic_cp_pbpsi.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_pbpsi_gen (bn_t sk, g1_t ss, g2_t *s, size_t m)
int cp_pbpsi_ask (g2_t *d, bn_t r, const bn_t *x, const g2_t *s, size_t m)
int cp_pbpsi_ans (gt_t *t, g1_t *u, const g1_t ss, const g2_t d, const bn_t *y, size_t n)
int cp_pbpsi_int (bn_t *z, size_t *len, const g2_t *d, const bn_t *x, size_t m, const gt_t *t, const g1_t *u, size_t n)
Detailed Description
Implementation of pairing-based laconic private set intersection protocols.
Definition in file relic_cp_pbpsi.c.
Function Documentation
cp_pbpsi_gen()
int cp_pbpsi_gen (bn_t sk, g1_t ss, g2_t * s, size_t m)
Generates the secrets and consecutive powers for the pairing-based laconic Private Set Intersection (PB-PSI) protocol, given the maximum set size.
Parameters
[out] sk - the sender's secret key.
[out] ss - the secret power in G_2.
[out] s - the consecutive powers in G_1.
[in] m - the maximum set size.
Definition at line 38 of file relic_cp_pbpsi.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), g1_mul_gen(), g2_get_gen, g2_mul(), pc_get_ord, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_pbpsi_ask()
int cp_pbpsi_ask (g2_t * d, bn_t r, const bn_t * x, const g2_t * s, size_t m)
Computes the receiver part of the PB-PSI protocol, given its input set.
Parameters
[out] d - the polynomial interpolations in the exponent.
[out] r - the random nonce.
[in] x - the receiver's input set.
[in] s - the consecutive powers.
[in] m - the receiver's input set size.
Definition at line 65 of file relic_cp_pbpsi.c.
References bn_copy(), bn_free, bn_lag(), bn_new, bn_null, bn_rand_mod(), ERR_NO_MEMORY, g2_mul(), g2_mul_gen(), g2_mul_sim_lot, pc_get_ord, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, and RLC_TRY.
cp_pbpsi_ans()
int cp_pbpsi_ans (gt_t * t, g1_t * u, const g1_t ss, const g2_t d, const bn_t * y, size_t n)
Computes the sender part of the PB-PSI protocol, given its input set.
Parameters
[out] t - the pairing results.
[out] u - the missing elements in the exponent.
[in] ss - the secret power.
[in] d - the polynomial interpolations in the exponent.
[in] y - the server's input set.
[in] n - the sender's input set size.
Definition at line 122 of file relic_cp_pbpsi.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ERR_NO_MEMORY, g1_free, g1_mul(), g1_mul_gen(), g1_new, g1_null, g1_sub, g2_free, g2_get_gen, g2_new, g2_null, pc_get_ord, pc_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, RLC_TRY, and util_perm().
cp_pbpsi_int()
int cp_pbpsi_int (bn_t * z, size_t * len, const g2_t * d, const bn_t * x, size_t m, const gt_t * t, const g1_t * u, size_t n)
Computes the intersection as the final part of the PB-PSI protocol.
Parameters
[out] z - the elements in the intersection.
[out] len - the cardinality of the resulting intersection.
[in] d - the polynomial interpolations in the exponent.
[in] x - the receiver's input set.
[in] s - the consecutive powers.
[in] m - the receiver's input set size.
[in] t - the pairing results.
[in] u - the missing elements in the exponent.
[in] n - the sender's input set size.
Definition at line 170 of file relic_cp_pbpsi.c.
References bn_copy(), gt_cmp, gt_free, gt_is_unity, gt_new, gt_null, pc_map, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.