RELIC: src/bn/relic_bn_shift.c File Reference
relic_bn_shift.c File Reference
Multiple precision integer arithmetic
#include "relic_core.h"
#include "relic_bn_low.h"
Functions
void bn_dbl (bn_t c, const bn_t a)
void bn_hlv (bn_t c, const bn_t a)
void bn_lsh (bn_t c, const bn_t a, int bits)
void bn_rsh (bn_t c, const bn_t a, int bits)
Detailed Description
Implementation of the multiple precision arithmetic shift functions.
Definition in file relic_bn_shift.c.
Function Documentation
bn_dbl()
void bn_dbl (bn_t c, const bn_t a)
Doubles a multiple precision. Computes c = a + a.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to double.
Definition at line 39 of file relic_bn_shift.c.
References bn_grow(), bn_lsh1_low(), bn_st::dp, bn_st::sign, and bn_st::used.
Referenced by bn_gen_prime_stron(), bn_rec_tnaf_mod(), ep2_curve_get_vs(), ep2_mul_glv_imp(), ep_curve_set_endom(), fp12_exp_cyc(), fp_inv_monty(), and fp_param_set().
bn_hlv()
void bn_hlv (bn_t c, const bn_t a)
Halves a multiple precision. Computes c = floor(a / 2)
Parameters
[out] c - the result.
[in] a - the multiple precision integer to halve.
Definition at line 56 of file relic_bn_shift.c.
References bn_grow(), bn_rsh1_low(), bn_trim(), bn_st::dp, bn_st::sign, and bn_st::used.
Referenced by bn_gcd_ext_stein(), bn_gcd_stein(), bn_rec_jsf(), bn_rec_naf(), bn_rec_reg(), bn_rec_rtnaf(), bn_rec_tnaf(), bn_rec_tnaf_mod(), bn_srt(), ep_curve_set_endom(), ep_map(), fp_inv_binar(), g1_is_valid(), g2_is_valid(), and gt_is_valid().
bn_lsh()
void bn_lsh (bn_t c, const bn_t a, int bits)
Shifts a multiple precision number to the left. Computes c = a * 2^bits. c = a * 2^bits.
Parameters
[out] c - the result.
[in] a - the multiple precision integer to shift.
[in] bits - the number of bits to shift.
Definition at line 66 of file relic_bn_shift.c.
References bn_bits(), bn_copy(), bn_grow(), bn_lshb_low(), bn_lshd_low(), bn_trim(), bn_st::dp, RLC_DIG, RLC_RIP, bn_st::sign, and bn_st::used.
Referenced by bn_gcd_ext_stein(), bn_gcd_stein(), bn_gen_prime_safep(), bn_mod_barrt(), bn_mod_monty_conv(), bn_mul_karat_imp(), bn_sqr_karat_imp(), cp_rabin_enc(), eb_mul_halve(), ep_curve_set_endom(), fp_param_set(), fp_prime_conv(), fp_prime_set(), fp_srt(), and pp_exp_k8().
bn_rsh()
void bn_rsh (bn_t c, const bn_t a, int bits)
Shifts a multiple precision number to the right. Computes c = floor(a / 2^bits).
Parameters
[out] c - the result.
[in] a - the multiple precision integer to shift.
[in] bits - the number of bits to shift.
Definition at line 105 of file relic_bn_shift.c.
References bn_copy(), bn_rshb_low(), bn_rshd_low(), bn_trim(), bn_st::dp, RLC_RIP, bn_st::sign, and bn_st::used.
Referenced by bn_gcd_ext_lehme(), bn_gcd_lehme(), bn_gen_prime_safep(), bn_is_prime_rabin(), bn_is_prime_solov(), bn_mod_barrt(), bn_mod_pmers(), bn_rec_glv(), bn_rec_reg(), bn_smb_jac(), bn_smb_leg(), cp_ecdsa_sig(), cp_ecdsa_ver(), cp_ecss_sig(), cp_ecss_ver(), cp_rabin_dec(), ed_map(), ep2_curve_get_vs(), fp_srt(), and pp_exp_k8().