RELIC: src/eb/relic_eb_util.c File Reference
relic_eb_util.c File Reference
Elliptic curves over binary fields
#include "relic_core.h"
#include "relic_eb.h"
#include "relic_conf.h"
Functions
int eb_is_infty (const eb_t p)
void eb_set_infty (eb_t p)
void eb_copy (eb_t r, const eb_t p)
int eb_cmp (const eb_t p, const eb_t q)
void eb_rand (eb_t p)
void eb_rhs (fb_t rhs, const eb_t p)
int eb_is_valid (const eb_t p)
void eb_tab (eb_t *t, const eb_t p, int w)
void eb_print (const eb_t p)
int eb_size_bin (const eb_t a, int pack)
void eb_read_bin (eb_t a, const uint8_t *bin, int len)
void eb_write_bin (uint8_t *bin, int len, const eb_t a, int pack)
Detailed Description
Implementation of the binary elliptic curve utilities.
Definition in file relic_eb_util.c.
Function Documentation
eb_is_infty()
int eb_is_infty (const eb_t p)
Tests if a point on a binary elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 40 of file relic_eb_util.c.
References fb_is_zero(), and eb_st::z.
Referenced by eb_add_basic(), eb_add_projc(), eb_dbl_basic(), eb_dbl_projc(), eb_frb_basic(), eb_frb_projc(), eb_is_valid(), eb_mul_basic(), eb_mul_dig(), eb_mul_halve(), eb_mul_lwnaf(), eb_mul_rwnaf(), eb_mul_sim_gen(), eb_mul_sim_inter(), eb_mul_sim_joint(), eb_mul_sim_trick(), eb_neg_basic(), eb_neg_projc(), eb_norm(), eb_norm_sim(), eb_size_bin(), and eb_write_bin().
eb_set_infty()
void eb_set_infty (eb_t p)
Assigns a binary elliptic curve point to a point at the infinity.
Parameters
[out] p - the point to assign.
Definition at line 44 of file relic_eb_util.c.
References fb_zero(), eb_st::norm, eb_st::x, eb_st::y, and eb_st::z.
Referenced by eb_add_basic_imp(), eb_add_projc_imp(), eb_add_projc_mix(), eb_dbl_basic(), eb_dbl_projc(), eb_frb_basic(), eb_frb_projc(), eb_mul_basic(), eb_mul_dig(), eb_mul_fix_basic(), eb_mul_fix_combd(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_fix_plain(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_lodah(), eb_mul_lwnaf(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_rwnaf(), eb_mul_sim_joint(), eb_mul_sim_kbltz(), eb_mul_sim_plain(), eb_mul_sim_trick(), eb_neg_basic(), eb_neg_projc(), eb_norm(), eb_read_bin(), eb_sub_basic(), eb_sub_projc(), and eb_tab().
eb_copy()
void eb_copy (eb_t r, const eb_t p)
Copies the second argument to the first argument.
Parameters
[out] r - the result.
[in] p - the binary elliptic curve point to copy.
Definition at line 51 of file relic_eb_util.c.
References fb_copy(), eb_st::norm, eb_st::x, eb_st::y, and eb_st::z.
Referenced by eb_add_basic(), eb_add_projc(), eb_cmp(), eb_curve_get_gen(), eb_mul_basic(), eb_mul_dig(), eb_mul_fix_combs(), eb_mul_fix_kbltz(), eb_mul_fix_plain(), eb_mul_halve(), eb_mul_lnaf_imp(), eb_mul_ltnaf_imp(), eb_mul_pre_basic(), eb_mul_pre_combd(), eb_mul_pre_combs(), eb_mul_rnaf_imp(), eb_mul_rtnaf_imp(), eb_mul_sim_joint(), eb_mul_sim_trick(), eb_norm(), and eb_tab().
eb_cmp()
int eb_cmp (const eb_t p, const eb_t q)
Compares two binary elliptic curve points.
Parameters
[in] p - the first binary elliptic curve point.
[in] q - the second binary elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 58 of file relic_eb_util.c.
References CATCH_ANY, eb_copy(), eb_norm(), eb_null, ERR_CAUGHT, fb_cmp(), FINALLY, eb_st::norm, result, RLC_EQ, RLC_NE, THROW, TRY, eb_st::x, eb_st::y, and eb_st::z.
eb_rand()
void eb_rand (eb_t p)
Assigns a random value to a binary elliptic curve point.
Parameters
[out] p - the binary elliptic curve point to assign.
Definition at line 109 of file relic_eb_util.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, eb_curve_get_ord(), eb_mul_gen(), ERR_CAUGHT, FINALLY, THROW, and TRY.
eb_rhs()
void eb_rhs (fb_t rhs, const eb_t p)
Computes the right-hand side of the elliptic curve equation at a certain elliptic curve point.
Parameters
[out] rhs - the result.
[in] p - the point.
Definition at line 132 of file relic_eb_util.c.
References CATCH_ANY, eb_curve_get_a(), eb_curve_get_b(), eb_curve_opt_a(), eb_curve_opt_b(), ERR_CAUGHT, fb_add(), fb_add_dig(), fb_copy(), fb_mul_dig(), fb_null, FINALLY, RLC_ONE, RLC_TINY, RLC_ZERO, THROW, TRY, and eb_st::x.
Referenced by eb_is_valid(), eb_map(), and eb_upk().
eb_is_valid()
int eb_is_valid (const eb_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 189 of file relic_eb_util.c.
References CATCH_ANY, eb_is_infty(), eb_norm(), eb_null, eb_rhs(), ERR_CAUGHT, fb_add(), fb_cmp(), fb_null, FINALLY, RLC_EQ, THROW, TRY, eb_st::x, and eb_st::y.
eb_tab()
void eb_tab (eb_t * t, const eb_t p, int w)
Builds a precomputation table for multiplying a random binary elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 219 of file relic_eb_util.c.
References eb_copy(), eb_curve_is_kbltz(), eb_curve_opt_a(), eb_norm(), eb_norm_sim(), eb_set_infty(), fb_set_dig(), eb_st::norm, and RLC_ZERO.
Referenced by eb_mul_lnaf_imp(), eb_mul_ltnaf_imp(), eb_mul_pre_lwnaf(), eb_mul_sim_kbltz(), and eb_mul_sim_plain().
eb_print()
void eb_print (const eb_t p)
Prints a binary elliptic curve point.
Parameters
[in] p - the binary elliptic curve point to print.
Definition at line 512 of file relic_eb_util.c.
References fb_print(), eb_st::x, eb_st::y, and eb_st::z.
eb_size_bin()
int eb_size_bin (const eb_t a, int pack)
Returns the number of bytes necessary to store a binary elliptic curve point with optional point compression.
Parameters
[in] a - the binary field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 518 of file relic_eb_util.c.
References eb_is_infty(), and RLC_FB_BYTES.
eb_read_bin()
void eb_read_bin (eb_t a, const uint8_t * bin, int len)
Reads a binary elliptic curve point from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 533 of file relic_eb_util.c.
References eb_set_infty(), eb_upk(), ERR_NO_BUFFER, ERR_NO_VALID, fb_read_bin(), fb_set_bit(), fb_set_dig(), fb_zero(), eb_st::norm, RLC_FB_BYTES, THROW, eb_st::x, eb_st::y, and eb_st::z.
eb_write_bin()
void eb_write_bin (uint8_t * bin, int len, const eb_t a, int pack)
Writes a binary field element to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the binary elliptic curve point to write.
[in] pack - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 577 of file relic_eb_util.c.
References CATCH_ANY, eb_is_infty(), eb_norm(), eb_null, eb_pck(), ERR_CAUGHT, ERR_NO_BUFFER, fb_get_bit(), fb_write_bin(), FINALLY, RLC_FB_BYTES, THROW, TRY, eb_st::x, and eb_st::y.