RELIC: src/bc/rijndael-alg-fst.c File Reference
rijndael-alg-fst.c File Reference
#include <stdlib.h>
#include "rijndael-alg-fst.h"
Macros
#define SWAP(x) (_lrotl(x, 8) & 0x00ff00ff | _lrotr(x, 8) & 0xff00ff00)
#define GETU32(pt) (((u32)(pt)[0] << 24) ^ ((u32)(pt)[1] << 16) ^ ((u32)(pt)[2] << 8) ^ ((u32)(pt)[3]))
#define PUTU32(ct, st) { (ct)[0] = (u8)((st) >> 24); (ct)[1] = (u8)((st) >> 16); (ct)[2] = (u8)((st) >> 8); (ct)[3] = (u8)(st); }
Functions
int rijndaelKeySetupEnc (u32 rk[], const u8 cipherKey[], int keyBits)
int rijndaelKeySetupDec (u32 rk[], const u8 cipherKey[], int keyBits)
void rijndaelEncrypt (const u32 rk[], int Nr, const u8 pt[16], u8 ct[16])
void rijndaelDecrypt (const u32 rk[], int Nr, const u8 ct[16], u8 pt[16])
Variables
static const u32 Te0 [256]
static const u32 Te1 [256]
static const u32 Te2 [256]
static const u32 Te3 [256]
static const u32 Te4 [256]
static const u32 Td0 [256]
static const u32 Td1 [256]
static const u32 Td2 [256]
static const u32 Td3 [256]
static const u32 Td4 [256]
static const u32 rcon []
Macro Definition Documentation
#define SWAP (x) (_lrotl(x, 8) & 0x00ff00ff | _lrotr(x, 8) & 0xff00ff00)
Definition at line 713 of file rijndael-alg-fst.c.
#define GETU32 (pt) (((u32)(pt)[0] << 24) ^ ((u32)(pt)[1] << 16) ^ ((u32)(pt)[2] << 8) ^ ((u32)(pt)[3]))
Definition at line 719 of file rijndael-alg-fst.c.
Referenced by rijndaelDecrypt(), rijndaelEncrypt(), and rijndaelKeySetupEnc().
#define PUTU32 (ct, st) { (ct)[0] = (u8)((st) >> 24); (ct)[1] = (u8)((st) >> 16); (ct)[2] = (u8)((st) >> 8); (ct)[3] = (u8)(st); }
Definition at line 720 of file rijndael-alg-fst.c.
Referenced by rijndaelDecrypt(), and rijndaelEncrypt().
Function Documentation
int rijndaelKeySetupEnc (u32 rk[], const u8 cipherKey[], int keyBits)
Expand the cipher key into the encryption key schedule.
Returns
the number of rounds for the given cipher key size.
Definition at line 728 of file rijndael-alg-fst.c.
References GETU32, rcon, and Te4.
Referenced by makeKey(), makeKey2(), and rijndaelKeySetupDec().
int rijndaelKeySetupDec (u32 rk[], const u8 cipherKey[], int keyBits)
Expand the cipher key into the decryption key schedule.
Returns
the number of rounds for the given cipher key size.
Definition at line 814 of file rijndael-alg-fst.c.
References rijndaelKeySetupEnc(), Td0, Td1, Td2, Td3, and Te4.
Referenced by makeKey(), and makeKey2().
void rijndaelEncrypt (const u32 rk[], int Nr, const u8 pt[16], u8 ct[16])
Definition at line 854 of file rijndael-alg-fst.c.
References GETU32, PUTU32, Te0, Te1, Te2, Te3, and Te4.
Referenced by blockDecrypt(), blockEncrypt(), and padEncrypt().
void rijndaelDecrypt (const u32 rk[], int Nr, const u8 ct[16], u8 pt[16])
Definition at line 1035 of file rijndael-alg-fst.c.
References GETU32, PUTU32, Td0, Td1, Td2, Td3, and Td4.
Referenced by blockDecrypt(), and padDecrypt().
Variable Documentation
const u32 Te0[256] static
rijndael-alg-fst.c
Version
3.0 (December 2000)
Optimised ANSI C code for the Rijndael cipher (now AES)
Author
Vincent Rijmen vince.nosp@m.nt.r.nosp@m.ijmen.nosp@m.@esa.nosp@m.t.kul.nosp@m.euve.nosp@m.n.ac..nosp@m.be
Antoon Bosselaers antoo.nosp@m.n.bo.nosp@m.ssela.nosp@m.ers@.nosp@m.esat..nosp@m.kule.nosp@m.uven..nosp@m.ac.b.nosp@m.e
Paulo Barreto paulo.nosp@m..bar.nosp@m.reto@.nosp@m.terr.nosp@m.a.com.nosp@m..br
This code is hereby placed in the public domain.
THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 45 of file rijndael-alg-fst.c.
Referenced by rijndaelEncrypt().
const u32 Te1[256] static
Definition at line 111 of file rijndael-alg-fst.c.
Referenced by rijndaelEncrypt().
const u32 Te2[256] static
Definition at line 177 of file rijndael-alg-fst.c.
Referenced by rijndaelEncrypt().
const u32 Te3[256] static
Definition at line 243 of file rijndael-alg-fst.c.
Referenced by rijndaelEncrypt().
const u32 Te4[256] static
Definition at line 310 of file rijndael-alg-fst.c.
Referenced by rijndaelEncrypt(), rijndaelKeySetupDec(), and rijndaelKeySetupEnc().
const u32 Td0[256] static
Definition at line 376 of file rijndael-alg-fst.c.
Referenced by rijndaelDecrypt(), and rijndaelKeySetupDec().
const u32 Td1[256] static
Definition at line 442 of file rijndael-alg-fst.c.
Referenced by rijndaelDecrypt(), and rijndaelKeySetupDec().
const u32 Td2[256] static
Definition at line 508 of file rijndael-alg-fst.c.
Referenced by rijndaelDecrypt(), and rijndaelKeySetupDec().
const u32 Td3[256] static
Definition at line 575 of file rijndael-alg-fst.c.
Referenced by rijndaelDecrypt(), and rijndaelKeySetupDec().
const u32 Td4[256] static
Definition at line 641 of file rijndael-alg-fst.c.
Referenced by rijndaelDecrypt().
const u32 rcon[] static
Initial value:
= {
    0x01000000, 0x02000000, 0x04000000, 0x08000000,
    0x10000000, 0x20000000, 0x40000000, 0x80000000,
    0x1B000000, 0x36000000,
}
Definition at line 707 of file rijndael-alg-fst.c.
Referenced by rijndaelKeySetupEnc().