RELIC: src/ed/relic_ed_util.c File Reference
relic_ed_util.c File Reference
Edwards curves over Edwards fields
#include <assert.h>
#include "relic_core.h"
#include "relic_label.h"
#include "relic_md.h"
Functions
int ed_is_infty (const ed_t p)
void ed_set_infty (ed_t p)
void ed_copy (ed_t r, const ed_t p)
int ed_cmp (const ed_t p, const ed_t q)
void ed_rand (ed_t p)
void ed_rhs (fp_t rhs, const ed_t p)
int ed_is_valid (const ed_t p)
void ed_tab (ed_t *t, const ed_t p, int w)
void ed_print (const ed_t p)
int ed_size_bin (const ed_t a, int pack)
void ed_read_bin (ed_t a, const uint8_t *bin, int len)
void ed_write_bin (uint8_t *bin, int len, const ed_t a, int pack)
Detailed Description
Implementation of the Edwards elliptic curve utilities.
Version
$Id$
Definition in file relic_ed_util.c.
Function Documentation
ed_is_infty()
int ed_is_infty (const ed_t p)
Tests if a point on an Edwards elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 44 of file relic_ed_util.c.
References CATCH_ANY, ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp_cmp_dig(), fp_is_zero(), fp_null, ed_st::norm, RLC_EQ, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_is_valid(), ed_mul_basic(), ed_mul_lwnaf(), ed_mul_lwreg(), ed_mul_monty(), ed_mul_sim_gen(), ed_mul_sim_inter(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), ed_neg_basic(), ed_neg_projc(), ed_norm(), ed_norm_sim(), ed_size_bin(), and ed_write_bin().
ed_set_infty()
void ed_set_infty (ed_t p)
Assigns an Edwards elliptic curve point to a point at the infinity.
Parameters
[out] p - the point to assign.
Definition at line 74 of file relic_ed_util.c.
References fp_set_dig(), fp_zero(), ed_st::norm, ed_st::t, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_curve_init(), ed_mul_basic(), ed_mul_dig(), ed_mul_fix_basic(), ed_mul_fix_combd(), ed_mul_fix_plain(), ed_mul_gen(), ed_mul_lwnaf(), ed_mul_lwreg(), ed_mul_monty(), ed_mul_naf_imp(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_reg_imp(), ed_mul_sim_joint(), ed_mul_sim_plain(), ed_mul_sim_trick(), ed_mul_slide(), ed_neg_basic(), ed_neg_projc(), ed_norm(), ed_read_bin(), ed_sub_basic(), ed_sub_extnd(), and ed_sub_projc().
ed_copy()
void ed_copy (ed_t r, const ed_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the Edwards elliptic curve point to copy.
Definition at line 84 of file relic_ed_util.c.
References fp_copy(), ed_st::norm, ed_st::t, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_cmp(), ed_curve_get_gen(), ed_mul_basic(), ed_mul_combs_plain(), ed_mul_dig(), ed_mul_monty(), ed_mul_pre_basic(), ed_mul_pre_combd(), ed_mul_pre_combs(), ed_mul_sim_joint(), ed_mul_sim_trick(), ed_mul_slide(), ed_norm(), ed_param_set(), and ed_tab().
ed_cmp()
int ed_cmp (const ed_t p, const ed_t q)
Compares two Edwards elliptic curve points.
Parameters
[in] p - the first Edwards elliptic curve point.
[in] q - the second Edwards elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 95 of file relic_ed_util.c.
References CATCH_ANY, ed_copy(), ed_norm(), ed_null, ERR_CAUGHT, FINALLY, fp_cmp(), ed_st::norm, result, RLC_EQ, RLC_NE, ed_st::t, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
ed_rand()
void ed_rand (ed_t p)
Assigns a random value to an Edwards elliptic curve point.
Parameters
[out] p - the Edwards elliptic curve point to assign.
Definition at line 147 of file relic_ed_util.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, ed_curve_get_ord(), ed_mul_gen(), ERR_CAUGHT, FINALLY, THROW, and TRY.
ed_rhs()
void ed_rhs (fp_t rhs, const ed_t p)
Computes the right-hand side of the elliptic curve equation at a certain Edwards elliptic curve point.
Parameters
[out] rhs - the result.
[in] p - the point.
Definition at line 169 of file relic_ed_util.c.
References CATCH_ANY, core_get(), ERR_CAUGHT, FINALLY, fp_null, THROW, TRY, ed_st::x, and ed_st::y.
Referenced by ed_is_valid().
ed_is_valid()
int ed_is_valid (const ed_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 196 of file relic_ed_util.c.
References CATCH_ANY, ed_is_infty(), ed_norm(), ed_null, ed_rhs(), ERR_CAUGHT, FINALLY, fp_cmp(), fp_cmp_dig(), fp_is_zero(), RLC_EQ, ed_st::t, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
ed_tab()
void ed_tab (ed_t * t, const ed_t p, int w)
Builds a precomputation table for multiplying a random Edwards elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 228 of file relic_ed_util.c.
References ed_copy(), ed_norm(), and ed_norm_sim().
Referenced by ed_mul_naf_imp(), ed_mul_pre_lwnaf(), ed_mul_reg_imp(), and ed_mul_sim_plain().
ed_print()
void ed_print (const ed_t p)
Prints an Edwards elliptic curve point.
Parameters
[in] p - the Edwards elliptic curve point to print.
Definition at line 245 of file relic_ed_util.c.
References fp_print(), ed_st::t, ed_st::x, ed_st::y, and ed_st::z.
ed_size_bin()
int ed_size_bin (const ed_t a, int pack)
Returns the number of bytes necessary to store an Edwards elliptic curve point with optional point compression.
Parameters
[in] a - the Edwards field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 254 of file relic_ed_util.c.
References ed_is_infty(), and RLC_FP_BYTES.
ed_read_bin()
void ed_read_bin (ed_t a, const uint8_t * bin, int len)
Reads an Edwards elliptic curve point from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 269 of file relic_ed_util.c.
References ed_set_infty(), ed_upk(), ERR_NO_BUFFER, ERR_NO_VALID, fp_read_bin(), fp_set_bit(), fp_set_dig(), fp_zero(), ed_st::norm, RLC_FP_BYTES, ed_st::t, THROW, ed_st::x, ed_st::y, and ed_st::z.
ed_write_bin()
void ed_write_bin (uint8_t * bin, int len, const ed_t a, int pack)
Writes an Edwards elliptic curve point to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the Edwards elliptic curve point to write.
[in] pack - the flag to indicate point compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 319 of file relic_ed_util.c.
References CATCH_ANY, ed_is_infty(), ed_norm(), ed_null, ed_pck(), ERR_CAUGHT, ERR_NO_BUFFER, FINALLY, fp_get_bit(), fp_write_bin(), RLC_FP_BYTES, THROW, TRY, ed_st::x, and ed_st::y.