RELIC: src/ed/relic_ed_neg.c File Reference
relic_ed_neg.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
void ed_neg_basic (ed_t r, const ed_t p)
void ed_neg_projc (ed_t r, const ed_t p)
Detailed Description
Implementation of the point negation on Edwards elliptic curves.
Definition in file relic_ed_neg.c.
Function Documentation
ed_neg_basic()
void ed_neg_basic (ed_t r, const ed_t p)
Negates an Edwards elliptic curve point represented by affine coordinates.
Parameters
[out] r - the result.
[in] p - the point to negate.
Definition at line 40 of file relic_ed_neg.c.
References ed_is_infty(), ed_set_infty(), fp_copy(), ed_st::norm, ed_st::x, and ed_st::y.
Referenced by ed_sub_basic().
ed_neg_projc()
void ed_neg_projc (ed_t r, const ed_t p)
Negates an Edwards elliptic curve point represented by projective coordinates.
Parameters
[out] r - the result.
[in] p - the point to negate.
Definition at line 56 of file relic_ed_neg.c.
References ed_is_infty(), ed_set_infty(), fp_copy(), ed_st::norm, ed_st::t, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_sub_extnd(), and ed_sub_projc().