RELIC: src/epx/relic_ep8_mul_fix.c File Reference
relic_ep8_mul_fix.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep8_mul_pre_ordin (ep8_t *t, const ep8_t p)
static void ep8_mul_fix_ordin (ep8_t r, const ep8_t *table, const bn_t k)
void ep8_mul_pre_basic (ep8_t *t, const ep8_t p)
void ep8_mul_fix_basic (ep8_t r, const ep8_t *t, const bn_t k)
void ep8_mul_pre_combs (ep8_t *t, const ep8_t p)
void ep8_mul_fix_combs (ep8_t r, const ep8_t *t, const bn_t k)
void ep8_mul_pre_combd (ep8_t *t, const ep8_t p)
void ep8_mul_fix_combd (ep8_t r, const ep8_t *t, const bn_t k)
void ep8_mul_pre_lwnaf (ep8_t *t, const ep8_t p)
void ep8_mul_fix_lwnaf (ep8_t r, const ep8_t *t, const bn_t k)
Detailed Description
Implementation of fixed point multiplication on a prime elliptic curve over an octic extension field.
Definition in file relic_ep8_mul_fix.c.
Function Documentation
ep8_mul_pre_ordin()
static void ep8_mul_pre_ordin (ep8_t * t, const ep8_t p) static
Precomputes a table for a point multiplication on an ordinary curve.
Parameters
[out] t - the destination table.
[in] p - the point to multiply.
Definition at line 47 of file relic_ep8_mul_fix.c.
References ep8_add, ep8_copy(), ep8_dbl, ep8_norm(), and RLC_DEPTH.
Referenced by ep8_mul_pre_lwnaf().
ep8_mul_fix_ordin()
static void ep8_mul_fix_ordin (ep8_t r, const ep8_t * table, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 77 of file relic_ep8_mul_fix.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ep8_add, ep8_dbl, ep8_neg(), ep8_norm(), ep8_set_infty(), ep8_sub(), RLC_DEPTH, RLC_FP_BITS, and RLC_NEG.
Referenced by ep8_mul_fix_lwnaf().
ep8_mul_pre_basic()
void ep8_mul_pre_basic (ep8_t * t, const ep8_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 119 of file relic_ep8_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep8_copy(), ep8_curve_get_ord(), ep8_dbl, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_mul_fix_basic()
void ep8_mul_fix_basic (ep8_t r, const ep8_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 142 of file relic_ep8_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep8_add, ep8_curve_get_ord(), ep8_norm(), ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_mul_pre_combs()
void ep8_mul_pre_combs (ep8_t * t, const ep8_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 179 of file relic_ep8_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep8_add, ep8_copy(), ep8_curve_get_ord(), ep8_dbl, ep8_norm(), ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_mul_fix_combs()
void ep8_mul_fix_combs (ep8_t r, const ep8_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 221 of file relic_ep8_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep8_add, ep8_copy(), ep8_curve_get_ord(), ep8_dbl, ep8_norm(), ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_mul_pre_combd()
void ep8_mul_pre_combd (ep8_t * t, const ep8_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 286 of file relic_ep8_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep8_add, ep8_copy(), ep8_curve_get_ord(), ep8_dbl, ep8_norm(), ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBD, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_mul_fix_combd()
void ep8_mul_fix_combd (ep8_t r, const ep8_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 335 of file relic_ep8_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_new, bn_null, bn_sign(), ep8_add, ep8_curve_get_ord(), ep8_dbl, ep8_neg(), ep8_norm(), ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
ep8_mul_pre_lwnaf()
void ep8_mul_pre_lwnaf (ep8_t * t, const ep8_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 399 of file relic_ep8_mul_fix.c.
References ep8_mul_pre_ordin().
ep8_mul_fix_lwnaf()
void ep8_mul_fix_lwnaf (ep8_t r, const ep8_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 403 of file relic_ep8_mul_fix.c.
References ep8_mul_fix_ordin().