RELIC: src/cp/relic_cp_sok.c File Reference
relic_cp_sok.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_sokdl_sig (bn_t c, bn_t s, const uint8_t *msg, size_t len, const ec_t y, const bn_t x)
int cp_sokdl_ver (const bn_t c, const bn_t s, const uint8_t *msg, size_t len, const ec_t y)
int cp_sokor_sig (bn_t c[2], bn_t s[2], const uint8_t *msg, size_t len, const ec_t y[2], const ec_t g[2], const bn_t x, int first)
int cp_sokor_ver (const bn_t c[2], const bn_t s[2], const uint8_t *msg, size_t len, const ec_t y[2], const ec_t g[2])
Detailed Description
Implementation of protocols for proof of knowledge of discrete logarithms.
Definition in file relic_cp_sok.c.
Function Documentation
cp_sokdl_sig()
int cp_sokdl_sig (bn_t c, bn_t r, const uint8_t * msg, size_t len, const ec_t y, const bn_t x)
Computes the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Proves that y = [x]G.
Parameters
[out] c - the challenge.
[out] r - the response.
[in] msg - the message to sign.
[in] len - the length of the message.
[in] y - the elliptic curve point
[in] x - the discrete logarithm to prove.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 43 of file relic_cp_sok.c.
References bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_sub(), ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_THROW, and RLC_TRY.
cp_sokdl_ver()
int cp_sokdl_ver (const bn_t c, const bn_t r, const uint8_t * msg, size_t len, const ec_t y)
Verifies the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Verifies that y = [x]G.
Parameters
[in] c - the challenge.
[in] r - the response.
[in] msg - the message to sign.
[in] len - the length of the message.
[in] y - the elliptic curve point.
Returns
a boolean value indicating the verification result.
Definition at line 101 of file relic_cp_sok.c.
References bn_cmp(), bn_free, bn_mod, bn_new, bn_null, bn_read_bin(), ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_sim_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_THROW, and RLC_TRY.
cp_sokor_sig()
int cp_sokor_sig (bn_t c[2], bn_t r[2], const uint8_t * msg, size_t len, const ec_t y[2], const ec_t g[2], const bn_t x, int first)
Computes the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Proves that y0 = [x]G or y1 = [x]G.
Parameters
[out] c - the challenges.
[out] r - the responses.
[in] msg - the message to sign.
[in] len - the length of the message.
[in] y - the elliptic curve points.
[in] g - the elliptic curve generators.
[in] x - the discrete logarithm to prove.
[in] first - the flag to indicate the point for which the discrete logarithm is known.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 158 of file relic_cp_sok.c.
References bn_copy(), bn_free, bn_mod, bn_mul, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_sub(), ec_copy, ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul, ec_mul_gen, ec_mul_sim, ec_mul_sim_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_THROW, and RLC_TRY.
Referenced by cp_ers_ext(), cp_ers_sig(), cp_etrs_ext(), cp_etrs_sig(), cp_etrs_uni(), cp_smlers_ext(), and cp_smlers_sig().
cp_sokor_ver()
int cp_sokor_ver (const bn_t c[2], const bn_t r[2], const uint8_t * msg, size_t len, const ec_t y[2], const ec_t g[2])
Verifies the proof of knowledge of a discrete logarithm of an elliptic curve point to a generator. Verifies that y = [x]G.
Parameters
[in] c - the challenges.
[in] r - the responses.
[in] msg - the message to sign.
[in] len - the length of the message.
[in] y - the elliptic curve points.
[in] g - the elliptic curve generators.
Returns
a boolean value indicating the verification result.
Definition at line 261 of file relic_cp_sok.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, bn_read_bin(), bn_sub(), ec_copy, ec_curve_get_gen, ec_curve_get_ord, ec_free, ec_mul_sim, ec_mul_sim_gen, ec_new, ec_null, ec_size_bin, ec_write_bin, ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FC_BYTES, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_THROW, and RLC_TRY.
Referenced by cp_ers_ver(), cp_etrs_ver(), and cp_smlers_ver().