RELIC: src/md/relic_md_sha512.c File Reference
relic_md_sha512.c File Reference
Hash functions
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_md.h"
#include "sha.h"
Functions
void md_map_sh512 (uint8_t *hash, const uint8_t *msg, int len)
Detailed Description
Implementation of the SHA-512 hash function.
Version
Id
relic_md_sha512.c 1811 2014-03-03 15:08:29Z dfaranha
Definition in file relic_md_sha512.c.
Function Documentation
void md_map_sh512 (uint8_t * hash, const uint8_t * msg, int len)
Computes the SHA-512 hash function.
Parameters
[out] hash - the digest.
[in] msg - the message to hash.
[in] len - the message length in bytes.
Definition at line 43 of file relic_md_sha512.c.
References ERR_NO_VALID, SHA512Input(), SHA512Reset(), SHA512Result(), shaSuccess, and THROW.