RELIC: src/cp/relic_cp_rsapsi.c File Reference
relic_cp_rsapsi.c File Reference
Cryptographic protocols
#include "relic.h"
Macros
#define STAT_SEC 40
Functions
int cp_rsapsi_gen (bn_t g, bn_t n, size_t bits)
int cp_rsapsi_ask (bn_t d, bn_t r, bn_t *p, const bn_t g, const bn_t n, const bn_t *x, size_t m)
int cp_rsapsi_ans (bn_t *t, bn_t *u, const bn_t d, const bn_t g, const bn_t n, const bn_t y[], size_t l)
int cp_rsapsi_int (bn_t *z, size_t *len, const bn_t r, const bn_t *p, const bn_t n, const bn_t *x, size_t m, const bn_t *t, const bn_t *u, size_t l)
Detailed Description
Implementation of protocols for laconic private set intersection.
Definition in file relic_cp_rsapsi.c.
Macro Definition Documentation
STAT_SEC
#define STAT_SEC 40
Statistical security determining collision probability.
Definition at line 41 of file relic_cp_rsapsi.c.
Referenced by cp_rsapsi_ans(), and cp_rsapsi_ask().
Function Documentation
cp_rsapsi_gen()
int cp_rsapsi_gen (bn_t g, bn_t n, size_t bits)
Generates the trusted setup parameters for the factoring-based laconic Private Set Intersection (RSA-PSI) protocol.
Parameters
[out] g - the generator.
[out] n - the modulus.
[in] bits - the precision in bits.
Definition at line 47 of file relic_cp_rsapsi.c.
References bn_cmp(), bn_cmp_dig(), bn_free, bn_gcd, bn_gen_prime, bn_mul, bn_new, bn_null, bn_rand_mod(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_OK, RLC_THROW, and RLC_TRY.
cp_rsapsi_ask()
int cp_rsapsi_ask (bn_t d, bn_t r, bn_t * p, const bn_t g, const bn_t n, const bn_t * x, size_t m)
Computes the receiver part of the RSA-PSI protocol, given its input set.
Parameters
[out] d - the resulting accumulator.
[out] r - the random nonce.
[out] p - the mapping of elements to prime numbers.
[in] g - the generator given by the trusted setup.
[in] n - the modulus given by the trusted setup.
[in] x - the receiver's input set.
[in] m - the receiver's input set size.
Definition at line 80 of file relic_cp_rsapsi.c.
References bn_add_dig(), bn_is_even(), bn_is_prime(), bn_mxp, bn_rand_mod(), bn_read_bin(), bn_write_bin(), md_map, RLC_BN_BITS, RLC_CEIL, RLC_MD_LEN, RLC_OK, and STAT_SEC.
cp_rsapsi_ans()
int cp_rsapsi_ans (bn_t * t, bn_t * u, const bn_t d, const bn_t g, const bn_t n, const bn_t y[], size_t l)
Definition at line 106 of file relic_cp_rsapsi.c.
References bn_add_dig(), bn_free, bn_is_even(), bn_is_prime(), bn_mxp, bn_new, bn_null, bn_rand_mod(), bn_read_bin(), bn_write_bin(), ERR_NO_MEMORY, md_map, RLC_ALLOCA, RLC_BN_BITS, RLC_CATCH_ANY, RLC_CEIL, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_MD_LEN, RLC_OK, RLC_THROW, RLC_TRY, STAT_SEC, and util_perm().
cp_rsapsi_int()
int cp_rsapsi_int (bn_t * z, size_t * len, const bn_t r, const bn_t * p, const bn_t n, const bn_t * x, const size_t m, const bn_t * t, const bn_t * u, size_t l)
Computes the intersection as the final part of the RSA-PSI protocol.
Parameters
[out] z - the elements in the intersection.
[out] len - the cardinality of the resulting intersection.
[in] r - the random nonce.
[in] p - the mapping of elements to prime numbers.
[in] n - the modulus given by the trusted setup.
[in] x - the receiver's input set.
[in] m - the receiver's input set size.
[in] t - the accumulator results.
[in] u - the missing elements in the exponent.
[in] l - the sender's input set size.
Definition at line 149 of file relic_cp_rsapsi.c.
References bn_cmp(), bn_copy(), bn_free, bn_mxp, bn_new, bn_null, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.