RELIC: src/epx/relic_ep4_mul_fix.c File Reference
relic_ep4_mul_fix.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep4_mul_pre_ordin (ep4_t *t, const ep4_t p)
static void ep4_mul_fix_ordin (ep4_t r, const ep4_t *table, const bn_t k)
void ep4_mul_pre_basic (ep4_t *t, const ep4_t p)
void ep4_mul_fix_basic (ep4_t r, const ep4_t *t, const bn_t k)
void ep4_mul_pre_combs (ep4_t *t, const ep4_t p)
void ep4_mul_fix_combs (ep4_t r, const ep4_t *t, const bn_t k)
void ep4_mul_pre_combd (ep4_t *t, const ep4_t p)
void ep4_mul_fix_combd (ep4_t r, const ep4_t *t, const bn_t k)
void ep4_mul_pre_lwnaf (ep4_t *t, const ep4_t p)
void ep4_mul_fix_lwnaf (ep4_t r, const ep4_t *t, const bn_t k)
Detailed Description
Implementation of fixed point multiplication on a prime elliptic curve over a quartic extension field.
Definition in file relic_ep4_mul_fix.c.
Function Documentation
ep4_mul_pre_ordin()
static void ep4_mul_pre_ordin (ep4_t * t, const ep4_t p) static
Precomputes a table for a point multiplication on an ordinary curve.
Parameters
[out] t - the destination table.
[in] p - the point to multiply.
Definition at line 47 of file relic_ep4_mul_fix.c.
References ep4_add, ep4_copy(), ep4_dbl, ep4_norm(), and RLC_DEPTH.
Referenced by ep4_mul_pre_lwnaf().
ep4_mul_fix_ordin()
static void ep4_mul_fix_ordin (ep4_t r, const ep4_t * table, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 77 of file relic_ep4_mul_fix.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ep4_add, ep4_dbl, ep4_neg(), ep4_norm(), ep4_set_infty(), ep4_sub(), RLC_DEPTH, RLC_FP_BITS, and RLC_NEG.
Referenced by ep4_mul_fix_lwnaf().
ep4_mul_pre_basic()
void ep4_mul_pre_basic (ep4_t * t, const ep4_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 119 of file relic_ep4_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep4_copy(), ep4_curve_get_ord(), ep4_dbl, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_fix_basic()
void ep4_mul_fix_basic (ep4_t r, const ep4_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 142 of file relic_ep4_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep4_add, ep4_curve_get_ord(), ep4_norm(), ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_pre_combs()
void ep4_mul_pre_combs (ep4_t * t, const ep4_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 179 of file relic_ep4_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep4_add, ep4_copy(), ep4_curve_get_ord(), ep4_dbl, ep4_norm(), ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_fix_combs()
void ep4_mul_fix_combs (ep4_t r, const ep4_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 221 of file relic_ep4_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep4_add, ep4_copy(), ep4_curve_get_ord(), ep4_dbl, ep4_norm(), ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_pre_combd()
void ep4_mul_pre_combd (ep4_t * t, const ep4_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 286 of file relic_ep4_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep4_add, ep4_copy(), ep4_curve_get_ord(), ep4_dbl, ep4_norm(), ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBD, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_fix_combd()
void ep4_mul_fix_combd (ep4_t r, const ep4_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 335 of file relic_ep4_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_new, bn_null, bn_sign(), ep4_add, ep4_curve_get_ord(), ep4_dbl, ep4_neg(), ep4_norm(), ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_NEG, RLC_THROW, and RLC_TRY.
ep4_mul_pre_lwnaf()
void ep4_mul_pre_lwnaf (ep4_t * t, const ep4_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 399 of file relic_ep4_mul_fix.c.
References ep4_mul_pre_ordin().
ep4_mul_fix_lwnaf()
void ep4_mul_fix_lwnaf (ep4_t r, const ep4_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 403 of file relic_ep4_mul_fix.c.
References ep4_mul_fix_ordin().