RELIC: src/epx/relic_ep4_neg.c File Reference
relic_ep4_neg.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
void ep4_neg (ep4_t r, const ep4_t p)
Detailed Description
Implementation of point negation on elliptic prime curves over a quartic extension field.
Definition in file relic_ep4_neg.c.
Function Documentation
ep4_neg()
void ep4_neg (ep4_t r, const ep4_t p)
Negates a point represented in affine coordinates in an elliptic curve over a quartic extension.
Parameters
[out] r - the result.
[out] p - the point to negate.
Definition at line 39 of file relic_ep4_neg.c.
References ep4_is_infty(), ep4_set_infty(), fp4_copy(), and fp4_neg().
Referenced by ep4_mul_basic(), ep4_mul_fix_combd(), ep4_mul_fix_ordin(), ep4_mul_gls_imp(), ep4_mul_naf_imp(), ep4_mul_reg_gls(), ep4_mul_reg_imp(), ep4_mul_sim_joint(), ep4_mul_sim_lot(), ep4_mul_sim_trick(), ep4_mul_slide(), ep4_psi(), ep4_sub(), pp_map_oatep_k16(), pp_map_sim_oatep_k16(), pp_mil_k16(), pp_mil_k24(), and pp_mil_lit_k16().