RELIC: src/cp/relic_cp_phpe.c File Reference
relic_cp_phpe.c File Reference
Cryptographic protocols
#include <string.h>
#include "relic_core.h"
#include "relic_conf.h"
#include "relic_rand.h"
#include "relic_bn.h"
#include "relic_util.h"
#include "relic_cp.h"
#include "relic_md.h"
Functions
int cp_phpe_gen (bn_t n, bn_t l, int bits)
int cp_phpe_enc (uint8_t *out, int *out_len, uint8_t *in, int in_len, bn_t n)
int cp_phpe_dec (uint8_t *out, int out_len, uint8_t *in, int in_len, bn_t n, bn_t l)
Detailed Description
Implementation of Paillier's Homomorphic Probabilistic Encryption.
Definition in file relic_cp_phpe.c.
Function Documentation
cp_phpe_gen()
int cp_phpe_gen (bn_t n, bn_t l, int bits)
Generates a key pair for Paillier's Homomorphic Probabilistic Encryption.
Parameters
[out] n - the public key.
[out] l - the private key.
[in] bits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 46 of file relic_cp_phpe.c.
References bn_cmp(), bn_free(), bn_null, bn_sub_dig(), CATCH_ANY, FINALLY, result, RLC_EQ, RLC_ERR, RLC_OK, and TRY.
cp_phpe_enc()
int cp_phpe_enc (uint8_t * out, int * out_len, uint8_t * in, int in_len, bn_t n)
Encrypts using the Paillier cryptosystem.
Parameters
[out] out - the output buffer.
[in,out] out_len - the buffer capacity and number of bytes written.
[in] in - the input buffer.
[in] in_len - the number of bytes to encrypt.
[in] n - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 80 of file relic_cp_phpe.c.
References bn_add_dig(), bn_free(), bn_mod, bn_null, bn_rand_mod(), bn_read_bin(), bn_size_bin(), bn_write_bin(), CATCH_ANY, FINALLY, result, RLC_ERR, RLC_OK, and TRY.
cp_phpe_dec()
int cp_phpe_dec (uint8_t * out, int out_len, uint8_t * in, int in_len, bn_t n, bn_t l)
Decrypts using the Paillier cryptosystem. Since this system is homomorphic, no padding can be applied and the user is responsible for specifying the resulting plaintext size.
Parameters
[out] out - the output buffer.
[out] out_len - the number of bytes to write in the output buffer.
[in] in_len - the number of bytes to decrypt.
[in] n - the public key.
[in] l - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 135 of file relic_cp_phpe.c.
References bn_add(), bn_div(), bn_free(), bn_mod, bn_null, bn_read_bin(), bn_sign(), bn_size_bin(), bn_sub_dig(), bn_write_bin(), CATCH_ANY, FINALLY, result, RLC_ERR, RLC_NEG, RLC_OK, and TRY.