RELIC: src/pp/relic_pp_map.c File Reference
relic_pp_map.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
void pp_map_init (void)
void pp_map_clean (void)
Detailed Description
Implementation of pairings over prime curves.
Definition in file relic_pp_map.c.
Function Documentation
pp_map_init()
void pp_map_init (void)
Computes a multi-pairing of elliptic curve points defined on an elliptic curve of embedding degree 12. Computes \prod e(P_i, Q_i).
Parameters
[out] R - the result.
[in] P - the first pairing arguments.
[in] Q - the second pairing arguments.
[in] M - the number of pairings to evaluate. Initializes the pairing over prime fields.
Definition at line 40 of file relic_pp_map.c.
References ep2_curve_init().
Referenced by core_init().
pp_map_clean()
void pp_map_clean (void)
Finalizes the pairing over prime fields.
Definition at line 44 of file relic_pp_map.c.
References ep2_curve_clean().
Referenced by core_clean().