RELIC: src/rand/relic_rand_hash.c File Reference
relic_rand_hash.c File Reference
Pseudo-random number generators.
#include <stdlib.h>
#include <stdint.h>
#include "relic_conf.h"
#include "relic_core.h"
#include "relic_label.h"
#include "relic_rand.h"
#include "relic_md.h"
#include "relic_err.h"
Functions
static void rand_hash (uint8_t *out, int out_len, uint8_t *in, int in_len)
static int rand_inc (uint8_t *data, int size, int digit)
static int rand_add (uint8_t *state, uint8_t *hash, int size)
static void rand_gen (uint8_t *out, int out_len)
void rand_bytes (uint8_t *buf, int size)
void rand_seed (uint8_t *buf, int size)
Detailed Description
Implementation of the hash-drbg pseudo-random number generator.
Version
Id
relic_rand.c 1522 2013-08-27 15:55:54Z dfaranha
Definition in file relic_rand_hash.c.
Function Documentation
static void rand_hash (uint8_t * out, int out_len, uint8_t * in, int in_len) static
Definition at line 56 of file relic_rand_hash.c.
References CEIL, MD_LEN, md_map, MIN, and util_conv_big().
Referenced by rand_seed().
static int rand_inc (uint8_t * data, int size, int digit) static
Accumulates a small integer in the internal state.
Parameters
[in,out] state - the internal state.
[in] digit - the small integer.
Definition at line 84 of file relic_rand_hash.c.
Referenced by rand_bytes(), and rand_gen().
static int rand_add (uint8_t * state, uint8_t * hash, int size) static
Accumulates the hash value in the internal state.
Parameters
[in,out] state - the internal state.
[in] hash - the hash value.
Definition at line 101 of file relic_rand_hash.c.
Referenced by rand_bytes().
static void rand_gen (uint8_t * out, int out_len) static
Generates pseudo-random bytes by iterating the hash function.
Parameters
[out] out - the buffer to write.
[in] out_len - the number of bytes to write.
Definition at line 119 of file relic_rand_hash.c.
References CEIL, core_get(), MD_LEN, md_map, MIN, rand_inc(), and RAND_SIZE.
Referenced by rand_bytes().
void rand_bytes (uint8_t * buf, int size)
Gathers pseudo-random bytes from the pseudo-random number generator.
Parameters
[out] buf - the buffer to write.
[in] size - the number of bytes to gather.
Exceptions
ERR_NO_VALID - if the required length is too large.
ERR_NO_READ - it the pseudo-random number generator cannot generate the specified number of bytes.
Definition at line 146 of file relic_rand_hash.c.
References core_get(), _ctx_t::counter, ERR_NO_VALID, MD_LEN, md_map, _ctx_t::rand, rand_add(), rand_gen(), rand_inc(), RAND_SIZE, and THROW.
Referenced by bn_rand(), fb_rand(), fp_rand(), and pad_pkcs1().
void rand_seed (uint8_t * buf, int size)
Definition at line 168 of file relic_rand_hash.c.
References core_get(), _ctx_t::counter, ERR_NO_VALID, _ctx_t::rand, rand_hash(), RAND_SIZE, _ctx_t::seeded, and THROW.
Referenced by rand_init().