RELIC: src/cp/relic_cp_shpe.c File Reference
relic_cp_shpe.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_shpe_gen (shpe_t pub, shpe_t prv, size_t sbits, size_t nbits)
int cp_shpe_enc_prv (bn_t c, const bn_t m, const shpe_t prv)
int cp_shpe_enc (bn_t c, const bn_t m, const shpe_t pub)
int cp_shpe_dec (bn_t m, const bn_t c, const shpe_t prv)
Detailed Description
Implementation of Paillier's Subgroup-variant Homomorphic Probabilistic Encryption.
Definition in file relic_cp_shpe.c.
Function Documentation
cp_shpe_gen()
int cp_shpe_gen (shpe_t pub, shpe_t prv, size_t sbits, size_t nbits)
Generates a key pair for Paillier's Subgroup Homomorphic Probabilistic Encryption.
Parameters
[out] pub - the public key.
[out] prv - the private key.
[in] sbits - the subgroup order in bits.
[in] nbits - the key length in bits.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 39 of file relic_cp_shpe.c.
References bn_add_dig(), bn_cmp(), bn_copy(), bn_div(), bn_gen_prime, bn_gen_prime_factor(), bn_mod, bn_mod_inv(), bn_mul, bn_mxp, bn_sqr, bn_sub_dig(), RLC_EQ, RLC_ERR, and RLC_OK.
cp_shpe_enc_prv()
int cp_shpe_enc_prv (bn_t c, const bn_t m, const shpe_t prv)
Encrypts faster using the Subgroup Paillier cryptosystem if the private key is known.
Parameters
[out] c - the ciphertext represented as an integer.
[in] m - the plaintext as an integer.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 101 of file relic_cp_shpe.c.
References bn_add_dig(), bn_bits(), bn_free, bn_mod, bn_mul, bn_mxp, bn_new, bn_null, bn_rand_mod(), bn_sqr, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_shpe_enc()
int cp_shpe_enc (bn_t c, const bn_t m, const shpe_t pub)
Encrypts using the Subgroup Paillier cryptosystem.
Parameters
[out] c - the ciphertext, represented as an integer.
[in] m - the plaintext as an integer.
[in] pub - the public key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 149 of file relic_cp_shpe.c.
References bn_add(), bn_bits(), bn_free, bn_mul, bn_mxp, bn_new, bn_null, bn_rand_mod(), bn_sqr, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_shpe_dec()
int cp_shpe_dec (bn_t m, const bn_t c, const shpe_t prv)
Decrypts using the Subgroup Paillier cryptosystem.
Parameters
[out] m - the plaintext, represented as an integer.
[in] c - the ciphertex as an integer.
[in] prv - the private key.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 191 of file relic_cp_shpe.c.
References bn_bits(), bn_div(), bn_free, bn_mod, bn_mod_inv(), bn_mul, bn_mxp, bn_mxp_crt(), bn_new, bn_null, bn_sqr, bn_sub_dig(), RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.