RELIC: src/fpx/relic_fpx_field.c File Reference
relic_fpx_field.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
int fp2_field_get_qnr ()
void fp2_field_init (void)
void fp3_field_init (void)
Detailed Description
Implementation of configuration for prime field extensions.
Definition in file relic_fpx_field.c.
Function Documentation
fp2_field_get_qnr()
int fp2_field_get_qnr (void)
Return the integer part (u) of the quadratic non-residue (i + u).
Definition at line 39 of file relic_fpx_field.c.
References core_get(), and _ctx_t::qnr2.
Referenced by fp2_mul_nor_basic().
fp2_field_init()
void fp2_field_init (void)
Multiplies two 54-degree extension field elements. Computes C = A * B.
Parameters
[out] C - the result.
[in] A - the first 54-degree extension field element.
[in] B - the second 54-degree extension field element. Squares a 54-degree extension field element. Computes C = A * A.
[out] C - the result.
[in] A - the 54-degree extension field element to square. Squares a 54-degree extension field element in the cyclotomic subgroup. Computes C = A * A.
[out] C - the result.
[in] A - the 54-degree extension field element to square. Squares a 54-degree extension field element in the cyclotomic subgroup in compressed form. Computes C = A * A.
[out] C - the result.
[in] A - the 54-degree extension field element to square. Initializes the quadratic extension field arithmetic module.
Definition at line 50 of file relic_fpx_field.c.
References bn_div_dig(), bn_free(), bn_null, bn_sub_dig(), CATCH_ANY, core_get(), bn_st::dp, dv_copy(), ERR_CAUGHT, FINALLY, fp2_exp(), fp2_free, fp2_new, fp2_null, _ctx_t::fp2_p1, _ctx_t::fp2_p2, fp2_set_dig(), fp2_srt(), fp_copy(), fp_prime_get(), fp_set_dig(), fp_zero(), _ctx_t::qnr2, RLC_FP_DIGS, THROW, TRY, and bn_st::used.
Referenced by fp_prime_calc().
fp3_field_init()
void fp3_field_init (void)
Initializes the cubic extension field arithmetic module.
Definition at line 146 of file relic_fpx_field.c.
References bn_div_dig(), bn_free(), bn_null, CATCH_ANY, core_get(), bn_st::dp, dv_copy(), ERR_CAUGHT, FINALLY, fp3_exp(), fp3_free, fp3_new, fp3_null, _ctx_t::fp3_p0, _ctx_t::fp3_p1, _ctx_t::fp3_p2, fp3_zero(), fp_copy(), fp_is_zero(), fp_prime_get(), fp_prime_get_cnr(), fp_set_dig(), _ctx_t::frb3, RLC_FP_DIGS, THROW, TRY, and bn_st::used.
Referenced by fp_prime_calc().