RELIC: src/cp/relic_cp_ers.c File Reference
relic_cp_ers.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_ers_gen (ec_t pp)
int cp_ers_gen_key (bn_t sk, ec_t pk)
int cp_ers_sig (bn_t td, ers_t p, const uint8_t *msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
int cp_ers_ver (const bn_t td, const ers_t *s, size_t size, const uint8_t *msg, size_t len, const ec_t pp)
int cp_ers_ext (bn_t td, ers_t *p, size_t *size, const uint8_t *msg, size_t len, const ec_t pk, const ec_t pp)
Detailed Description
Implementation of extendable ring signatures.
Definition in file relic_cp_ers.c.
Function Documentation
cp_ers_gen()
int cp_ers_gen (ec_t pp)
Generates the public parameters of the extendable ring signature.
@åaram[out] pp - the public parameters.
Definition at line 38 of file relic_cp_ers.c.
References ec_rand, and RLC_OK.
cp_ers_gen_key()
int cp_ers_gen_key (bn_t sk, ec_t pk)
Generates a key pair for the extendable ring signature.
@åaram[out] sk - the private key.
Parameters
[out] pk - the public key.
Definition at line 43 of file relic_cp_ers.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ec_curve_get_ord, ec_mul_gen, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_ers_sig()
int cp_ers_sig (bn_t td, ers_t p, const uint8_t * msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
Signs a message using the extendable ring signature scheme.
Parameters
[out] td - the signature trapdoor.
[out] p - the resulting signature.
[in] msg - the message to sign.
[in] len - the message length.
[in] sk - the signer's private key.
[in] pk - the singer's public key.
[in] pp - the public parameters.
Definition at line 65 of file relic_cp_ers.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), cp_sokor_sig(), ec_copy, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_norm, ec_null, ec_sub, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
Referenced by cp_smlers_sig().
cp_ers_ver()
int cp_ers_ver (const bn_t td, const ers_t * s, size_t size, const uint8_t * msg, size_t len, const ec_t pp)
Verifies an extendable ring signature scheme over some messages.
Parameters
[in] td - the signature trapdoor.
[in] s
the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] pp - the public parameters.
Definition at line 105 of file relic_cp_ers.c.
References bn_free, bn_new, bn_null, cp_sokor_ver(), ec_add, ec_cmp, ec_copy, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
cp_ers_ext()
int cp_ers_ext (bn_t td, ers_t * p, size_t * size, const uint8_t * msg, size_t len, const ec_t pk, const ec_t pp)
Extends an extendable ring signature with a new signature.
Parameters
[out] td - the signature trapdoor.
[in] p - the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] pk - the singer's public key.
[in] pp - the public parameters.
Definition at line 150 of file relic_cp_ers.c.
References bn_free, bn_mod, bn_new, bn_null, bn_rand_mod(), bn_sub(), cp_sokor_sig(), ec_cmp, ec_copy, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_null, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.