RELIC: src/cp/relic_cp_mklhs.c File Reference
relic_cp_mklhs.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_mklhs_gen (bn_t sk, g2_t pk)
int cp_mklhs_sig (g1_t s, bn_t m, char *data, int dlen, char *label, int llen, bn_t sk)
int cp_mklhs_fun (bn_t mu, bn_t m[], dig_t f[], int len)
int cp_mklhs_evl (g1_t sig, g1_t s[], dig_t f[], int len)
int cp_mklhs_ver (g1_t sig, bn_t m, bn_t mu[], char *data, int dlen, char *label[], int llen[], dig_t f[][RLC_TERMS], int flen[], g2_t pk[], int slen)
int cp_mklhs_off (g1_t h[], dig_t ft[], char *label[], int llen[], dig_t f[][RLC_TERMS], int flen[], int slen)
int cp_mklhs_onv (g1_t sig, bn_t m, bn_t mu[], char *data, int dlen, g1_t h[], dig_t ft[], g2_t pk[], int slen)
Detailed Description
Implementation of the multi-key linearly homomophic signature protocol.
Definition in file relic_cp_mklhs.c.
Function Documentation
cp_mklhs_gen()
int cp_mklhs_gen (bn_t sk, g2_t pk)
Generates a key pair for the Multi-Key Homomorphic Signature (MKLHS) scheme.
Parameters
[out] sk - the private key for the signature scheme.
[out] pk - the public key for the signature scheme.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 38 of file relic_cp_mklhs.c.
References bn_free(), bn_null, bn_rand_mod(), CATCH_ANY, FINALLY, g2_get_ord, g2_mul_gen, result, RLC_ERR, RLC_OK, and TRY.
cp_mklhs_sig()
int cp_mklhs_sig (g1_t s, bn_t m, char * data, int dlen, char * label, int llen, bn_t sk)
Signs a message using the MKLHS.
Parameters
[out] s - the resulting signature.
[in] m - the message to sign.
[in] data - the dataset identifier.
[in] dlen - the length of the dataset identifier.
[in] label - the label.
[in] llen - the length of the label.
[in] sk - the private key for the signature scheme.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 60 of file relic_cp_mklhs.c.
References bn_free(), bn_null, CATCH_ANY, FINALLY, g1_add, g1_free, g1_get_ord, g1_map, g1_mul_gen, g1_mul_key, g1_new, g1_norm, result, RLC_ERR, RLC_OK, and TRY.
cp_mklhs_fun()
int cp_mklhs_fun (bn_t mu, bn_t m[], dig_t f[], int len)
Applies a function over a set of messages from the same user.
Parameters
[out] mu - the combined message.
[in] m - the vector of individual messages.
[in] f - the linear coefficients in the function.
[in] len - the number of coefficients.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 93 of file relic_cp_mklhs.c.
References bn_add(), bn_free(), bn_mod, bn_mul_dig(), bn_null, bn_zero(), CATCH_ANY, FINALLY, g1_get_ord, result, RLC_ERR, RLC_OK, and TRY.
cp_mklhs_evl()
int cp_mklhs_evl (g1_t sig, g1_t s[], dig_t f[], int len)
Evaluates a function over a set of MKLHS signatures.
Parameters
[out] sig - the resulting signature
[in] s - the set of signatures.
[in] f - the linear coefficients in the function.
[in] len - the number of coefficients.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 122 of file relic_cp_mklhs.c.
References g1_mul_sim_dig, result, and RLC_OK.
cp_mklhs_ver()
int cp_mklhs_ver (g1_t sig, bn_t m, bn_t mu[], char * data, int dlen, char * label[], int llen[], dig_t f[][RLC_TERMS], int flen[], g2_t pk[], int slen)
Verifies a MKLHS signature over a set of messages.
Parameters
[in] sig - the homomorphic signature to verify.
[in] m - the signed message.
[in] mu - the vector of signed messages per user.
[in] data - the dataset identifier.
[in] dlen - the length of the dataset identifier.
[in] label - the vector of labels.
[in] llen - the vector of label lengths.
[in] f - the linear coefficients in the function.
[in] flen - the number of coefficients.
[in] pk - the public keys of the users.
[in] slen - the number of signatures.
Returns
a boolean value indicating the verification result.
Definition at line 130 of file relic_cp_mklhs.c.
References bn_add(), bn_cmp(), bn_mod, bn_null, bn_zero(), CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, g1_add, g1_free, g1_get_ord, g1_map, g1_mul_gen, g1_mul_sim_dig, g1_new, g1_norm_sim, g1_null, g2_free, g2_get_gen, g2_new, g2_null, gt_cmp, gt_free, gt_new, gt_null, pc_map, pc_map_sim, RLC_ALLOCA, RLC_EQ, RLC_FREE, RLC_MAX, THROW, and TRY.
cp_mklhs_off()
int cp_mklhs_off (g1_t h[], dig_t ft[], char * label[], int llen[], dig_t f[][RLC_TERMS], int flen[], int slen)
Computes the offline part of veryfying a MKLHS signature over a set of messages.
Parameters
[out] h - the hashes of labels
[out] ft - the precomputed linear coefficients.
[in] label - the vector of labels.
[in] llen - the vector of label lengths.
[in] f - the linear coefficients in the function.
[in] flen - the number of coefficients.
[in] slen - the number of signatures.
Returns
RLC_OK if no errors occurred, RLC_ERR otherwise.
Definition at line 222 of file relic_cp_mklhs.c.
References CATCH_ANY, ERR_NO_MEMORY, FINALLY, g1_free, g1_map, g1_mul_sim_dig, g1_new, g1_null, result, RLC_ALLOCA, RLC_ERR, RLC_FREE, RLC_MAX, RLC_OK, THROW, and TRY.
cp_mklhs_onv()
int cp_mklhs_onv (g1_t sig, bn_t m, bn_t mu[], char * data, int dlen, g1_t h[], dig_t ft[], g2_t pk[], int slen)
Computes the online part of veryfying a MKLHS signature over a set of messages.
Parameters
[in] sig - the homomorphic signature to verify.
[in] m - the signed message.
[in] mu - the vector of signed messages per user.
[in] data - the dataset identifier.
[in] dlen - the length of the dataset identifier.
[in] d - the hashes of labels.
[in] ft - the precomputed linear coefficients.
[in] pk - the public keys of the users.
[in] slen - the number of signatures.
Returns
a boolean value indicating the verification result.
Definition at line 262 of file relic_cp_mklhs.c.
References bn_add(), bn_cmp(), bn_mod, bn_null, bn_zero(), CATCH_ANY, ERR_CAUGHT, ERR_NO_MEMORY, FINALLY, g1_add, g1_free, g1_get_ord, g1_map, g1_mul_dig, g1_mul_gen, g1_new, g1_norm_sim, g1_null, g2_free, g2_get_gen, g2_new, g2_null, gt_cmp, gt_free, gt_new, gt_null, pc_map, pc_map_sim, RLC_ALLOCA, RLC_EQ, RLC_FREE, THROW, and TRY.