RELIC: src/epx/relic_ep3_add.c File Reference
relic_ep3_add.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_ep_add_tmpl.h"
Functions
TMPL_ADD_BASIC_IMP (ep3, fp3)
TMPL_ADD_PROJC_MIX (ep3, fp3)
TMPL_ADD_PROJC_IMP (ep3, fp3)
TMPL_ADD_JACOB_MIX (ep3, fp3)
TMPL_ADD_JACOB_IMP (ep3, fp3)
void ep3_add_basic (ep3_t r, const ep3_t p, const ep3_t q)
void ep3_add_slp_basic (ep3_t r, fp3_t s, const ep3_t p, const ep3_t q)
void ep3_add_projc (ep3_t r, const ep3_t p, const ep3_t q)
void ep3_add_jacob (ep3_t r, const ep3_t p, const ep3_t q)
void ep3_sub (ep3_t r, const ep3_t p, const ep3_t q)
Detailed Description
Implementation of addition on prime elliptic curves over a cubic extension field.
Definition in file relic_ep3_add.c.
Function Documentation
TMPL_ADD_BASIC_IMP()
TMPL_ADD_BASIC_IMP (ep3 , fp3)
Adds two points represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
TMPL_ADD_PROJC_MIX()
TMPL_ADD_PROJC_MIX (ep3 , fp3)
Adds a point represented in homogeneous coordinates to a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the projective point.
[in] q - the affine point.
TMPL_ADD_PROJC_IMP()
TMPL_ADD_PROJC_IMP (ep3 , fp3)
Adds two points represented in homogeneous coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
TMPL_ADD_JACOB_MIX()
TMPL_ADD_JACOB_MIX (ep3 , fp3)
Adds a point represented in Jacobian coordinates to a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the projective point.
[in] q - the affine point.
TMPL_ADD_JACOB_IMP()
TMPL_ADD_JACOB_IMP (ep3 , fp3)
Adds two points represented in Jacobian coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
ep3_add_basic()
void ep3_add_basic (ep3_t r, const ep3_t p, const ep3_t q)
Adds to points represented in affine coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 109 of file relic_ep3_add.c.
References ep3_copy(), and ep3_is_infty().
ep3_add_slp_basic()
void ep3_add_slp_basic (ep3_t r, fp3_t s, const ep3_t p, const ep3_t q)
Adds to points represented in affine coordinates in an elliptic curve over a cubic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 123 of file relic_ep3_add.c.
References ep3_copy(), and ep3_is_infty().
Referenced by pp_add_k18_basic().
ep3_add_projc()
void ep3_add_projc (ep3_t r, const ep3_t p, const ep3_t q)
Adds two points represented in projective coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 141 of file relic_ep3_add.c.
References ep3_copy(), and ep3_is_infty().
ep3_add_jacob()
void ep3_add_jacob (ep3_t r, const ep3_t p, const ep3_t q)
Adds two points represented in Jacobian coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 159 of file relic_ep3_add.c.
References ep3_copy(), and ep3_is_infty().
ep3_sub()
void ep3_sub (ep3_t r, const ep3_t p, const ep3_t q)
Subtracts a point in an elliptic curve over a cubic extension from another.
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the point to subtract.
Definition at line 175 of file relic_ep3_add.c.
References ep3_add, ep3_free, ep3_neg(), ep3_new, ep3_null, ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep3_mul_basic(), ep3_mul_cof_fm18(), ep3_mul_cof_k18(), ep3_mul_cof_sg18(), ep3_mul_dig(), ep3_mul_fix_plain(), ep3_mul_gls_imp(), ep3_mul_naf_imp(), ep3_mul_reg_gls(), ep3_mul_reg_imp(), ep3_mul_sim_joint(), ep3_mul_sim_lot(), ep3_mul_sim_plain(), and ep3_psi().