RELIC: src/epx/relic_ep4_mul_sim.c File Reference
relic_ep4_mul_sim.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep4_mul_sim_plain (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m, ep4_t *t)
void ep4_mul_sim_basic (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t l)
void ep4_mul_sim_trick (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
void ep4_mul_sim_inter (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
void ep4_mul_sim_joint (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
void ep4_mul_sim_gen (ep4_t r, const bn_t k, const ep4_t q, const bn_t m)
void ep4_mul_sim_dig (ep4_t r, const ep4_t p[], const dig_t k[], size_t len)
void ep4_mul_sim_lot (ep4_t r, const ep4_t p[], const bn_t k[], size_t n)
Detailed Description
Implementation of simultaneous point multiplication on a prime elliptic curve over a quartic extension field.
Definition in file relic_ep4_mul_sim.c.
Function Documentation
ep4_mul_sim_plain()
static void ep4_mul_sim_plain (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m, ep4_t * t) static
Multiplies and adds two prime elliptic curve points simultaneously, optionally choosing the first point as the generator depending on an optional table of precomputed points.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer.
[in] t - the pointer to the precomputed table.
Definition at line 53 of file relic_ep4_mul_sim.c.
References bn_rec_naf(), bn_sign(), ep4_add, ep4_dbl, ep4_free, ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ep4_sub(), ep4_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep4_mul_sim_gen(), and ep4_mul_sim_inter().
ep4_mul_sim_basic()
void ep4_mul_sim_basic (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using scalar multiplication and point addition.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 150 of file relic_ep4_mul_sim.c.
References ep4_add, ep4_free, ep4_mul, ep4_new, ep4_norm(), ep4_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_sim_trick()
void ep4_mul_sim_trick (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using shamir's trick.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 175 of file relic_ep4_mul_sim.c.
References bn_free, bn_is_zero(), bn_new, bn_null, bn_rec_win(), bn_sign(), ep4_add, ep4_copy(), ep4_curve_get_ord(), ep4_dbl, ep4_free, ep4_is_infty(), ep4_mul, ep4_neg(), ep4_new, ep4_norm(), ep4_norm_sim(), ep4_null, ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
ep4_mul_sim_inter()
void ep4_mul_sim_inter (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using interleaving of NAFs.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 269 of file relic_ep4_mul_sim.c.
References bn_is_zero(), ep4_is_infty(), ep4_mul, and ep4_mul_sim_plain().
ep4_mul_sim_joint()
void ep4_mul_sim_joint (ep4_t r, const ep4_t p, const bn_t k, const ep4_t q, const bn_t m)
Multiplies and adds two prime elliptic curve points simultaneously using Solinas' Joint Sparse Form.
Parameters
[out] r - the result.
[in] p - the first point to multiply.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 287 of file relic_ep4_mul_sim.c.
References bn_bits(), bn_is_zero(), bn_rec_jsf(), bn_sign(), ep4_add, ep4_copy(), ep4_dbl, ep4_free, ep4_is_infty(), ep4_mul, ep4_neg(), ep4_new, ep4_norm(), ep4_norm_sim(), ep4_null, ep4_set_infty(), ep4_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, and RLC_TRY.
ep4_mul_sim_gen()
void ep4_mul_sim_gen (ep4_t r, const bn_t k, const ep4_t q, const bn_t m)
Multiplies and adds the generator and a prime elliptic curve point simultaneously. Computes R = [k]G + [l]Q.
Parameters
[out] r - the result.
[in] k - the first integer.
[in] q - the second point to multiply.
[in] m - the second integer,
Definition at line 362 of file relic_ep4_mul_sim.c.
References bn_is_zero(), ep4_curve_get_gen(), ep4_curve_get_tab(), ep4_free, ep4_is_infty(), ep4_mul, ep4_mul_gen(), ep4_mul_sim, ep4_mul_sim_plain(), ep4_new, ep4_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep4_mul_sim_dig()
void ep4_mul_sim_dig (ep4_t r, const ep4_t p[], const dig_t k[], size_t len)
Multiplies prime elliptic curve points by small scalars. Computes R = \sum k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the small scalars.
[in] len - the number of points to multiply.
Definition at line 394 of file relic_ep4_mul_sim.c.
References ep4_add, ep4_dbl, ep4_free, ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_MAX, RLC_THROW, RLC_TRY, and util_bits_dig().
ep4_mul_sim_lot()
void ep4_mul_sim_lot (ep4_t r, const ep4_t p[], const bn_t k[], size_t n)
Multiplies simultaneously elements from a prime elliptic curve. Computes R = \Sum_i=0..n k_iP_i.
Parameters
[out] r - the result.
[in] p - the points to multiply.
[in] k - the integer scalars.
[in] n - the number of elements to multiply.
Definition at line 428 of file relic_ep4_mul_sim.c.
References bn_free, bn_new, bn_null, bn_rec_frb(), bn_rec_naf(), bn_sign(), ep4_add, ep4_copy(), ep4_dbl, ep4_frb(), ep4_free, ep4_neg(), ep4_new, ep4_norm(), ep4_null, ep4_set_infty(), ep4_sub(), EP_BN, ep_curve_get_ord(), ep_curve_is_pairf(), ERR_CAUGHT, fp_prime_get_par(), RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_FREE, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().