RELIC: src/epx/relic_ep8_frb.c File Reference
relic_ep8_frb.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
void ep8_frb (ep8_t r, const ep8_t p, int i)
Detailed Description
Implementation of frobenius action on prime elliptic curves over an octic extension field.
Definition in file relic_ep8_frb.c.
Function Documentation
ep8_frb()
void ep8_frb (ep8_t r, const ep8_t p, int i)
Computes a power of the Gailbraith-Lin-Scott homomorphism of a point represented in affine coordinates on a twisted elliptic curve over a octic exension. That is, Psi^i(P) = Twist(P)(Frob^i(unTwist(P)). On the trace-zero group of an octic twist, consists of a power of the Frobenius map of a point represented in affine coordinates in an elliptic curve over an octic exension. Computes Frob^i(P) = (p^i)P.
Parameters
[out] r - the result in affine coordinates.
[in] p - a point in affine coordinates.
[in] i - the power of the Frobenius map.
Definition at line 39 of file relic_ep8_frb.c.
References ep8_copy(), fp8_frb(), and fp8_mul_frb().
Referenced by ep8_mul_cof(), ep8_mul_gls_imp(), ep8_mul_reg_gls(), and ep8_mul_sim_lot().