RELIC: src/epx/relic_ep4_cmp.c File Reference
relic_ep4_cmp.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
int ep4_cmp (const ep4_t p, const ep4_t q)
Detailed Description
Implementation of utilities for prime elliptic curves over a quartic extension field.
Definition in file relic_ep4_cmp.c.
Function Documentation
ep4_cmp()
int ep4_cmp (const ep4_t p, const ep4_t q)
Compares two elliptic curve points.
Parameters
[in] p - the first elliptic curve point.
[in] q - the second elliptic curve point.
Returns
RLC_EQ if p == q and RLC_NE if p != q.
Definition at line 39 of file relic_ep4_cmp.c.
References ep4_copy(), ep4_free, ep4_is_infty(), ep4_new, ep4_null, ERR_CAUGHT, fp4_cmp(), fp4_mul, fp4_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_NE, RLC_THROW, and RLC_TRY.