RELIC: src/ep/relic_ep_add.c File Reference
relic_ep_add.c File Reference
Elliptic curves over prime fields
#include "relic_core.h"
Functions
static void ep_add_basic_imp (ep_t r, fp_t s, const ep_t p, const ep_t q)
static void ep_add_projc_mix (ep_t r, const ep_t p, const ep_t q)
static void ep_add_projc_imp (ep_t r, const ep_t p, const ep_t q)
void ep_add_basic (ep_t r, const ep_t p, const ep_t q)
void ep_add_slp_basic (ep_t r, fp_t s, const ep_t p, const ep_t q)
void ep_sub_basic (ep_t r, const ep_t p, const ep_t q)
void ep_add_projc (ep_t r, const ep_t p, const ep_t q)
void ep_sub_projc (ep_t r, const ep_t p, const ep_t q)
Detailed Description
Implementation of the point addition on prime elliptic curves.
Version
Id
relic_ep_add.c 1669 2013-12-28 03:20:53Z dfaranha
Definition in file relic_ep_add.c.
Function Documentation
static void ep_add_basic_imp (ep_t r, fp_t s, const ep_t p, const ep_t q) static
Adds two points represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 49 of file relic_ep_add.c.
References CATCH_ANY, ep_dbl_basic(), ep_set_infty(), ERR_CAUGHT, FINALLY, fp_copy(), fp_free, fp_inv, fp_is_zero(), fp_mul, fp_new, fp_null, fp_sqr, fp_sub, THROW, and TRY.
Referenced by ep_add_basic(), and ep_add_slp_basic().
static void ep_add_projc_mix (ep_t r, const ep_t p, const ep_t q) static
Adds a point represented in affine coordinates to a point represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the projective point.
[in] q - the affine point.
Definition at line 126 of file relic_ep_add.c.
References CATCH_ANY, ep_dbl_projc(), ep_set_infty(), ERR_CAUGHT, FINALLY, fp_add, fp_dbl, fp_free, fp_is_zero(), fp_mul, fp_new, fp_null, fp_sqr, fp_sub, THROW, and TRY.
Referenced by ep_add_projc_imp().
static void ep_add_projc_imp (ep_t r, const ep_t p, const ep_t q) static
Adds two points represented in projective coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 246 of file relic_ep_add.c.
References CATCH_ANY, ep_add_projc_mix(), ep_dbl_projc(), ep_set_infty(), ERR_CAUGHT, FINALLY, fp_add, fp_dbl, fp_free, fp_is_zero(), fp_mul, fp_new, fp_null, fp_sqr, fp_sub, THROW, and TRY.
Referenced by ep_add_projc().
void ep_add_basic (ep_t r, const ep_t p, const ep_t q)
Adds two prime elliptic curve points represented in affine coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 376 of file relic_ep_add.c.
References ep_add_basic_imp(), ep_copy(), and ep_is_infty().
Referenced by ep_sub_basic().
void ep_add_slp_basic (ep_t r, fp_t s, const ep_t p, const ep_t q)
Adds two prime elliptic curve points represented in affine coordinates and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 390 of file relic_ep_add.c.
References ep_add_basic_imp(), ep_copy(), and ep_is_infty().
Referenced by pp_add_k2_basic().
void ep_sub_basic (ep_t r, const ep_t p, const ep_t q)
Subtracts a prime elliptic curve point from another, both points represented by affine coordinates..
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 404 of file relic_ep_add.c.
References CATCH_ANY, ep_add_basic(), ep_free, ep_neg_basic(), ep_new, ep_null, ep_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.
void ep_add_projc (ep_t r, const ep_t p, const ep_t q)
Adds two prime elliptic curve points represented in projective coordinates.
Parameters
[out] r - the result.
[in] p - the first point to add.
[in] q - the second point to add.
Definition at line 434 of file relic_ep_add.c.
References ep_add_projc_imp(), ep_copy(), and ep_is_infty().
Referenced by ep_sub_projc().
void ep_sub_projc (ep_t r, const ep_t p, const ep_t q)
Subtracts a prime elliptic curve point from another, both points represented by projective coordinates..
Parameters
[out] r - the result.
[in] p - the first point.
[in] q - the second point.
Definition at line 448 of file relic_ep_add.c.
References CATCH_ANY, ep_add_projc(), ep_free, ep_neg_projc(), ep_new, ep_null, ep_set_infty(), ERR_CAUGHT, FINALLY, THROW, and TRY.