RELIC: src/pp/relic_pp_map_k48.c File Reference
relic_pp_map_k48.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
static void pp_mil_k48 (fp48_t r, fp8_t qx, fp8_t qy, ep_t p, bn_t a)
void pp_map_k48 (fp48_t r, ep_t p, fp8_t qx, fp8_t qy)
Detailed Description
Implementation of pairing computation for curves with embedding degree 48.
Definition in file relic_pp_map_k48.c.
Function Documentation
pp_mil_k48()
static void pp_mil_k48 (fp48_t r, fp8_t qx, fp8_t qy, ep_t p, bn_t a) static
Definition at line 40 of file relic_pp_map_k48.c.
References bn_bits(), bn_rec_naf(), CATCH_ANY, ep_null, ERR_CAUGHT, FINALLY, fp48_free, fp48_mul_dxs(), fp48_new, fp48_null, fp48_zero(), fp8_copy(), fp8_free, fp8_neg(), fp8_new, fp8_null, fp8_set_dig(), RLC_FP_BITS, THROW, TRY, ep_st::x, and ep_st::y.
Referenced by pp_map_k48().
pp_map_k48()
void pp_map_k48 (fp48_t r, ep_t p, fp8_t qx, fp8_t qy)
Computes the Optimal Ate pairing of two points in a parameterized elliptic curve with embedding degree 48.
Parameters
[out] r - the result.
[in] q - the first elliptic curve point.
[in] p - the second elliptic curve point.
Definition at line 105 of file relic_pp_map_k48.c.
References bn_free(), bn_null, bn_sign(), CATCH_ANY, EP_B48, ep_curve_is_pairf(), ep_is_infty(), ERR_CAUGHT, FINALLY, fp48_inv_cyc(), fp48_set_dig(), fp8_is_zero(), fp_prime_get_par(), pp_exp_k48(), pp_mil_k48(), RLC_NEG, THROW, and TRY.