RELIC: src/epx/relic_ep3_dbl.c File Reference
relic_ep3_dbl.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
#include "relic_ep_dbl_tmpl.h"
Functions
TMPL_DBL_BASIC_IMP (ep3, fp3)
TMPL_DBL_PROJC_IMP (ep3, fp3)
TMPL_DBL_JACOB_IMP (ep3, fp3)
void ep3_dbl_basic (ep3_t r, const ep3_t p)
void ep3_dbl_slp_basic (ep3_t r, fp3_t s, const ep3_t p)
void ep3_dbl_projc (ep3_t r, const ep3_t p)
void ep3_dbl_jacob (ep3_t r, const ep3_t p)
Detailed Description
Implementation of doubling on elliptic prime curves over a cubic extension field.
Definition in file relic_ep3_dbl.c.
Function Documentation
TMPL_DBL_BASIC_IMP()
TMPL_DBL_BASIC_IMP (ep3 , fp3)
Doubles a point represented in affine coordinates on an ordinary prime elliptic curve.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
TMPL_DBL_PROJC_IMP()
TMPL_DBL_PROJC_IMP (ep3 , fp3)
Doubles a point represented in projective coordinates on an ordinary prime elliptic curve.
Parameters
r - the result.
p - the point to double.
TMPL_DBL_JACOB_IMP()
TMPL_DBL_JACOB_IMP (ep3 , fp3)
Doubles a point represented in Jacobian coordinates on an ordinary prime elliptic curve.
Parameters
r - the result.
p - the point to double.
ep3_dbl_basic()
void ep3_dbl_basic (ep3_t r, const ep3_t p)
Doubles a point represented in affine coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[int] p - the point to double.
Definition at line 86 of file relic_ep3_dbl.c.
References ep3_is_infty(), and ep3_set_infty().
ep3_dbl_slp_basic()
void ep3_dbl_slp_basic (ep3_t r, fp3_t s, const ep3_t p)
Doubles a point represented in affine coordinates in an elliptic curve over a cubic extension and returns the computed slope.
Parameters
[out] r - the result.
[out] s - the slope.
[in] p - the point to double.
Definition at line 94 of file relic_ep3_dbl.c.
References ep3_is_infty(), and ep3_set_infty().
Referenced by pp_dbl_k18_basic().
ep3_dbl_projc()
void ep3_dbl_projc (ep3_t r, const ep3_t p)
Doubles a point represented in projective coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 107 of file relic_ep3_dbl.c.
References ep3_is_infty(), and ep3_set_infty().
ep3_dbl_jacob()
void ep3_dbl_jacob (ep3_t r, const ep3_t p)
Doubles a point represented in Jacobian coordinates in an elliptic curve over a cubic extension.
Parameters
[out] r - the result.
[in] p - the point to double.
Definition at line 120 of file relic_ep3_dbl.c.
References ep3_is_infty(), and ep3_set_infty().