RELIC: src/fpx/relic_fpx_pck.c File Reference
relic_fpx_pck.c File Reference
Prime field extensions.
#include "relic_core.h"
Functions
void fp2_pck (fp2_t c, fp2_t a)
int fp2_upk (fp2_t c, fp2_t a)
void fp12_pck (fp12_t c, fp12_t a)
int fp12_upk (fp12_t c, fp12_t a)
void fp48_pck (fp48_t c, fp48_t a)
int fp48_upk (fp48_t c, fp48_t a)
void fp54_pck (fp54_t c, fp54_t a)
int fp54_upk (fp54_t c, fp54_t a)
Detailed Description
Implementation of finite field compression in extension fields.
Definition in file relic_fpx_pck.c.
Function Documentation
fp2_pck()
void fp2_pck (fp2_t c, fp2_t a)
Compresses an extension field element.
Parameters
[out] r - the result.
[in] p - the extension field element to compress.
Definition at line 38 of file relic_fpx_pck.c.
References fp2_copy(), fp2_test_cyc(), fp_copy(), fp_get_bit(), fp_set_bit(), and fp_zero().
Referenced by fp2_write_bin().
fp2_upk()
int fp2_upk (fp2_t c, fp2_t a)
Decompresses a quadratic extension field element.
Parameters
[out] r - the result.
[in] p - the quadratic extension field element.
Returns
if the decompression was successful
Definition at line 48 of file relic_fpx_pck.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp_bits(), fp_copy(), fp_get_bit(), fp_null, fp_srt(), fp_sub_dig(), result, THROW, and TRY.
Referenced by fp2_read_bin().
fp12_pck()
void fp12_pck (fp12_t c, fp12_t a)
Compresses a dodecic extension field element.
Parameters
[out] r - the result.
[in] p - the dodecic extension field element to compress.
Definition at line 87 of file relic_fpx_pck.c.
References fp12_copy(), fp12_test_cyc(), and fp2_zero().
Referenced by fp12_write_bin().
fp12_upk()
int fp12_upk (fp12_t c, fp12_t a)
Decompresses a dodecic extension field element.
Parameters
[out] r - the result.
[in] p - the dodecic extension field element to decompress.
Returns
if the decompression was successful
Definition at line 95 of file relic_fpx_pck.c.
References fp12_back_cyc(), fp12_copy(), fp12_test_cyc(), and fp2_is_zero().
fp48_pck()
void fp48_pck (fp48_t c, fp48_t a)
Compresses a 48-extension field element.
Parameters
[out] r - the result.
[in] p - the 48-extension field element to compress.
Definition at line 109 of file relic_fpx_pck.c.
References fp48_copy(), fp48_test_cyc(), and fp8_zero().
Referenced by fp48_write_bin().
fp48_upk()
int fp48_upk (fp48_t c, fp48_t a)
Decompresses a 48-extension field element.
Parameters
[out] r - the result.
[in] p - the 48-extension field element to decompress.
Returns
if the decompression was successful
Definition at line 117 of file relic_fpx_pck.c.
References fp48_back_cyc(), fp48_copy(), fp48_test_cyc(), and fp8_is_zero().
fp54_pck()
void fp54_pck (fp54_t c, fp54_t a)
Compresses a 54-extension field element.
Parameters
[out] r - the result.
[in] p - the 54-extension field element to compress.
Definition at line 131 of file relic_fpx_pck.c.
References fp54_copy(), fp54_test_cyc(), and fp9_zero().
Referenced by fp54_write_bin().
fp54_upk()
int fp54_upk (fp54_t c, fp54_t a)
Decompresses a 54-extension field element.
Parameters
[out] r - the result.
[in] p - the 54-extension field element to decompress.
Returns
if the decompression was successful
Definition at line 139 of file relic_fpx_pck.c.
References fp54_back_cyc(), fp54_copy(), fp54_test_cyc(), and fp9_is_zero().