RELIC: src/bn/relic_bn_mem.c File Reference
relic_bn_mem.c File Reference
Multiple precision integer arithmetic
#include <errno.h>
#include "relic_core.h"
Functions
void bn_init (bn_t a, int digits)
void bn_clean (bn_t a)
void bn_grow (bn_t a, int digits)
void bn_trim (bn_t a)
Detailed Description
Implementation of the multiple precision integer memory management routines.
Definition in file relic_bn_mem.c.
Function Documentation
bn_init()
void bn_init (bn_t a, int digits)
Reduces a multiple precision integer modulo another integer. This macro should not be called directly. Use bn_mod with 4 arguments instead.
Parameters
[out] C - the result.
[in] A - the the multiple precision integer to reduce.
[in] M - the modulus.
[in] U - the auxiliar value derived from the modulus. Reduces a multiple precision integer modulo a positive integer using Montgomery reduction. Computes c = a * u^(-1) (mod m).
[out] C - the result.
[in] A - the multiple precision integer to reduce.
[in] M - the modulus.
[in] U - the reciprocal of the modulus. Exponentiates a multiple precision integer modulo another multiple precision integer. Computes c = a^b mod m. If Montgomery reduction is used, the basis must not be in Montgomery form.
[out] C - the result.
[in] A - the basis.
[in] B - the exponent.
[in] M - the modulus. Computes the greatest common divisor of two multiple precision integers. Computes c = gcd(a, b).
[out] C - the result;
[in] A - the first multiple precision integer.
[in] B - the second multiple precision integer. Computes the extended greatest common divisor of two multiple precision integers. This function can be used to compute multiplicative inverses. Computes c = gcd(a, b) and c = a * d + b * e.
[out] C - the result;
[out] D - the cofactor of the first operand, cannot be NULL.
[out] E - the cofactor of the second operand, can be NULL.
[in] A - the first multiple precision integer.
[in] B - the second multiple precision integer. Generates a probable prime number.
[out] A - the result.
[in] B - the length of the number in bits. Initializes a previously allocated multiple precision integer.
[out] a - the multiple precision integer to initialize.
[in] digits - the required precision in digits.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
ERR_PRECISION - if the required precision cannot be represented by the library.
Definition at line 44 of file relic_bn_mem.c.
References ALIGN, bn_st::alloc, bn_st::dp, ERR_NO_MEMORY, ERR_NO_PRECI, ERR_NO_VALID, RLC_POS, bn_st::sign, THROW, and bn_st::used.
Referenced by eb_curve_init(), ed_curve_init(), ep2_curve_init(), ep_curve_init(), and fp_prime_init().
bn_clean()
void bn_clean (bn_t a)
Cleans a multiple precision integer.
Parameters
[out] a - the multiple precision integer to free.
Definition at line 87 of file relic_bn_mem.c.
References bn_st::alloc, bn_st::dp, RLC_POS, bn_st::sign, and bn_st::used.
Referenced by eb_curve_clean(), ed_curve_clean(), ep2_curve_clean(), ep_curve_clean(), and fp_prime_clean().
bn_grow()
void bn_grow (bn_t a, int digits)
Checks the current precision of a multiple precision integer and optionally expands its precision to a given size in digits.
Parameters
[out] a - the multiple precision integer to expand.
[in] digits - the number of digits to expand.
Exceptions
ERR_NO_MEMORY - if there is no available memory.
ERR_PRECISION - if the required precision cannot be represented by the library.
Definition at line 107 of file relic_bn_mem.c.
References bn_st::alloc, bn_st::dp, ERR_NO_MEMORY, ERR_NO_PRECI, RLC_DIG, and THROW.
Referenced by bn_add_dig(), bn_add_imp(), bn_copy(), bn_dbl(), bn_hlv(), bn_lsh(), bn_mul_dig(), bn_rand(), bn_read_bin(), bn_read_raw(), bn_set_2b(), bn_sub_dig(), bn_sub_imp(), and fp_prime_back().
bn_trim()
void bn_trim (bn_t a)
Adjust the number of valid digits of a multiple precision integer.
Parameters
[out] a - the multiple precision integer to adjust.
Definition at line 130 of file relic_bn_mem.c.
References bn_st::dp, RLC_POS, bn_st::sign, and bn_st::used.
Referenced by bn_add_dig(), bn_add_imp(), bn_div_dig(), bn_div_imp(), bn_div_rem_dig(), bn_hlv(), bn_lsh(), bn_mod_2b(), bn_mod_barrt(), bn_mod_monty_basic(), bn_mod_monty_comba(), bn_mul_basic(), bn_mul_comba(), bn_mul_dig(), bn_mul_karat_imp(), bn_mxp_slide(), bn_rand(), bn_read_bin(), bn_read_raw(), bn_rsh(), bn_set_bit(), bn_sqr_basic(), bn_sqr_comba(), bn_sqr_karat_imp(), bn_sub_dig(), bn_sub_imp(), fp_inv_monty(), fp_prime_back(), and fp_prime_set().