RELIC: src/mpc/relic_mpc_sss.c File Reference
relic_mpc_sss.c File Reference
Multi-party computation
#include "relic_core.h"
#include "relic_bn.h"
#include "relic_mpc.h"
#include "relic_util.h"
Functions
int mpc_sss_gen (bn_t *x, bn_t *y, const bn_t secret, const bn_t order, size_t k, size_t n)
int mpc_sss_key (bn_t key, const bn_t *x, const bn_t *y, const bn_t order, size_t k)
Detailed Description
Implementation of Shamir Secret Sharing.
Definition in file relic_mpc_sss.c.
Function Documentation
mpc_sss_gen()
int mpc_sss_gen (bn_t * x, bn_t * y, const bn_t key, const bn_t order, size_t k, size_t n)
Generates shares (x, y) of a secret key using a (k, n)-threshold Shamir's Secret Sharing over a given finite field.
Parameters
[out] x - the indexes of the parties receiving shares.
[out] y - the evaluation points.
[in] key - the secret to share.
[in] order - the order of the finite field.
[in] k - the threshold.
[in] n - the number of parties.
Definition at line 40 of file relic_mpc_sss.c.
References bn_copy(), bn_evl(), bn_free, bn_new, bn_null, bn_rand_mod(), bn_set_dig(), ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, and RLC_TRY.
mpc_sss_key()
int mpc_sss_key (bn_t key, const bn_t * x, const bn_t * y, const bn_t order, size_t k)
Recovers a secret key using a k shares (x, y) of over a given finite field.
Parameters
[in] key - the recovered secret.
[in] x - the indexes of the parties contributing shares.
[in] y - the evaluation points.
[in] order - the order of the finite field.
[in] k - the threshold.
Definition at line 81 of file relic_mpc_sss.c.
References bn_add(), bn_free, bn_mod, bn_mod_inv_sim(), bn_mul, bn_new, bn_null, bn_set_dig(), bn_sub(), ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, and RLC_TRY.