RELIC: src/pp/relic_pp_exp_k2.c File Reference
relic_pp_exp_k2.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_util.h"
Functions
void pp_exp_k2 (fp2_t c, fp2_t a)
Detailed Description
Implementation of the final exponentiation for curves of embedding degree 2.
Definition in file relic_pp_exp_k2.c.
Function Documentation
pp_exp_k2()
void pp_exp_k2 (fp2_t c, fp2_t a)
Computes the final exponentiation for a pairing defined over curves of embedding degree 2. Computes c = a^(p^2 - 1)/r.
Parameters
[out] c - the result.
[in] a - the extension field element to exponentiate.
Definition at line 40 of file relic_pp_exp_k2.c.
References bn_add_dig(), bn_div(), bn_free(), bn_null, CATCH_ANY, bn_st::dp, dv_copy(), ep_curve_get_ord(), ERR_CAUGHT, FINALLY, fp2_conv_cyc(), fp2_exp_cyc(), fp_prime_get(), RLC_FP_DIGS, RLC_POS, bn_st::sign, THROW, TRY, and bn_st::used.
Referenced by gt_rand(), pp_map_sim_tatep_k2(), and pp_map_tatep_k2().