RELIC: src/cp/relic_cp_etrs.c File Reference
relic_cp_etrs.c File Reference
Cryptographic protocols
#include "relic.h"
Functions
int cp_etrs_sig (bn_t *td, bn_t *y, size_t max, etrs_t p, const uint8_t *msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
int cp_etrs_ver (size_t thres, const bn_t *td, const bn_t *y, size_t max, const etrs_t *s, size_t size, const uint8_t *msg, size_t len, const ec_t pp)
int cp_etrs_ext (bn_t *td, bn_t *y, size_t max, etrs_t *p, size_t *size, const uint8_t *msg, size_t len, const ec_t pk, const ec_t pp)
int cp_etrs_uni (int thres, bn_t *td, bn_t *y, int max, etrs_t *p, size_t *size, const uint8_t *msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
Detailed Description
Implementation of extendable ring signatures.
Definition in file relic_cp_etrs.c.
Function Documentation
cp_etrs_sig()
int cp_etrs_sig (bn_t * td, bn_t * y, size_t max, etrs_t p, const uint8_t * msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
Signs a message using the extendable threshold ring signature scheme.
Parameters
[out] td - the signature trapdoors.
[out] y - the signature randomness.
[out] max - the maximum number of extensions.
[out] p - the resulting signature.
[in] msg - the message to sign.
[in] len - the message length.
[in] sk - the signer's private key.
[in] pk - the singer's public key.
[in] pp - the public parametetrs.
Definition at line 38 of file relic_cp_etrs.c.
References bn_add(), bn_copy(), bn_free, bn_mod, bn_mod_inv_sim(), bn_mul, bn_new, bn_null, bn_rand_mod(), bn_set_dig(), bn_sub(), bn_zero(), cp_sokor_sig(), ec_copy, ec_curve_get_ord, ec_free, ec_mul, ec_mul_sim_gen, ec_new, ec_null, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_ERR, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, and RLC_TRY.
cp_etrs_ver()
int cp_etrs_ver (size_t thres, const bn_t * td, const bn_t * y, size_t max, const etrs_t * s, size_t size, const uint8_t * msg, size_t len, const ec_t pp)
Verifies an extendable threshold ring signature scheme over some messages.
Parameters
[in] thres - the specified threshold.
[in] td - the signature trapdoors.
[in] y - the signature randomness.
[in] max - the maximum number of extensions.
[in] s - the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] pp - the public parametetrs.
Definition at line 143 of file relic_cp_etrs.c.
References bn_copy(), bn_free, bn_mod, bn_mod_inv_sim(), bn_mul, bn_new, bn_null, bn_set_dig(), bn_sub(), cp_sokor_ver(), ec_cmp, ec_copy, ec_curve_get_ord, ec_free, ec_mul_gen, ec_mul_sim_lot, ec_new, ec_null, ec_set_infty, ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_FREE, RLC_THROW, and RLC_TRY.
cp_etrs_ext()
int cp_etrs_ext (bn_t * td, bn_t * y, size_t max, etrs_t * p, size_t * size, const uint8_t * msg, size_t len, const ec_t pk, const ec_t pp)
Extends an extendable threshold ring signature with a new signature.
Parameters
[out] td - the signature trapdoors.
[in] y - the signature randomness.
[in] max - the maximum number of extensions.
[in] p - the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] pk - the singer's public key.
[in] pp - the public parametetrs.
Definition at line 245 of file relic_cp_etrs.c.
References bn_copy(), bn_free, bn_is_zero(), bn_new, bn_null, bn_zero(), cp_sokor_sig(), ec_cmp, ec_copy, ec_curve_get_ord, ec_free, ec_mul_gen, ec_new, ec_null, RLC_CATCH_ANY, RLC_EQ, RLC_ERR, RLC_FINALLY, RLC_OK, and RLC_TRY.
cp_etrs_uni()
int cp_etrs_uni (int thres, bn_t * td, bn_t * y, int max, etrs_t * p, size_t * size, const uint8_t * msg, size_t len, const bn_t sk, const ec_t pk, const ec_t pp)
Joins an extendable threshold ring signature with a new signature.
Parameters
[in] thres - the specified threshold.
[in] td - the signature trapdoors.
[in] y - the signature randomness.
[in] max - the maximum number of extensions.
[in] p - the ring of signatures.
[in] size - the number of signatures in the ring.
[in] msg - the message to sign.
[in] len - the message length.
[in] sk - the signer's private key.
[in] pk - the singer's public key.
[in] pp - the public parametetrs.
Definition at line 301 of file relic_cp_etrs.c.
References bn_copy(), bn_free, bn_mod, bn_mod_inv_sim(), bn_mul, bn_new, bn_null, bn_rand_mod(), bn_set_dig(), bn_sub(), cp_sokor_sig(), ec_add, ec_copy, ec_curve_get_ord, ec_free, ec_mul, ec_mul_gen, ec_new, ec_norm, ec_null, ec_set_infty, ERR_CAUGHT, ERR_NO_MEMORY, RLC_ALLOCA, RLC_CATCH_ANY, RLC_FINALLY, RLC_FREE, RLC_OK, RLC_THROW, and RLC_TRY.