RELIC: src/epx/relic_ep3_mul_fix.c File Reference
relic_ep3_mul_fix.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep3_mul_fix_plain (ep3_t r, const ep3_t *table, const bn_t k)
void ep3_mul_pre_basic (ep3_t *t, const ep3_t p)
void ep3_mul_fix_basic (ep3_t r, const ep3_t *t, const bn_t k)
void ep3_mul_pre_combs (ep3_t *t, const ep3_t p)
void ep3_mul_fix_combs (ep3_t r, const ep3_t *t, const bn_t k)
void ep3_mul_pre_combd (ep3_t *t, const ep3_t p)
void ep3_mul_fix_combd (ep3_t r, const ep3_t *t, const bn_t k)
void ep3_mul_pre_lwnaf (ep3_t *t, const ep3_t p)
void ep3_mul_fix_lwnaf (ep3_t r, const ep3_t *t, const bn_t k)
Detailed Description
Implementation of fixed point multiplication on a prime elliptic curve over a cubic extension field.
Definition in file relic_ep3_mul_fix.c.
Function Documentation
ep3_mul_fix_plain()
static void ep3_mul_fix_plain (ep3_t r, const ep3_t * table, const bn_t k) static
Multiplies a binary elliptic curve point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 49 of file relic_ep3_mul_fix.c.
References bn_is_zero(), bn_rec_naf(), bn_sign(), ep3_add, ep3_dbl, ep3_neg(), ep3_norm(), ep3_set_infty(), ep3_sub(), RLC_DEPTH, RLC_FP_BITS, and RLC_NEG.
Referenced by ep3_mul_fix_lwnaf().
ep3_mul_pre_basic()
void ep3_mul_pre_basic (ep3_t * t, const ep3_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the binary method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 91 of file relic_ep3_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep3_copy(), ep3_curve_get_ord(), ep3_dbl, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_fix_basic()
void ep3_mul_fix_basic (ep3_t r, const ep3_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the binary method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 114 of file relic_ep3_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep3_add, ep3_curve_get_ord(), ep3_norm(), ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_pre_combs()
void ep3_mul_pre_combs (ep3_t * t, const ep3_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the single-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 151 of file relic_ep3_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep3_add, ep3_copy(), ep3_curve_get_ord(), ep3_dbl, ep3_norm(), ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBS, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_fix_combs()
void ep3_mul_fix_combs (ep3_t r, const ep3_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the single-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 193 of file relic_ep3_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep3_add, ep3_copy(), ep3_curve_get_ord(), ep3_dbl, ep3_norm(), ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_pre_combd()
void ep3_mul_pre_combd (ep3_t * t, const ep3_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the double-table comb method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 258 of file relic_ep3_mul_fix.c.
References bn_bits(), bn_free, bn_new, bn_null, ep3_add, ep3_copy(), ep3_curve_get_ord(), ep3_dbl, ep3_norm(), ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_EP_TABLE_COMBD, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_fix_combd()
void ep3_mul_fix_combd (ep3_t r, const ep3_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the double-table comb method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 307 of file relic_ep3_mul_fix.c.
References bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, ep3_add, ep3_curve_get_ord(), ep3_dbl, ep3_norm(), ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DEPTH, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep3_mul_pre_lwnaf()
void ep3_mul_pre_lwnaf (ep3_t * t, const ep3_t p)
Builds a precomputation table for multiplying a fixed prime elliptic point using the w-(T)NAF method.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
Definition at line 372 of file relic_ep3_mul_fix.c.
References ep3_tab(), and RLC_DEPTH.
ep3_mul_fix_lwnaf()
void ep3_mul_fix_lwnaf (ep3_t r, const ep3_t * t, const bn_t k)
Multiplies a fixed prime elliptic point using a precomputation table and the w-(T)NAF method.
Parameters
[out] r - the result.
[in] t - the precomputation table.
[in] k - the integer.
Definition at line 376 of file relic_ep3_mul_fix.c.
References bn_free, bn_is_zero(), bn_mod, bn_new, bn_null, ep3_curve_get_ord(), ep3_mul_fix_plain(), ep3_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.