RELIC: src/ed/relic_ed_param.c File Reference
relic_ed_param.c File Reference
Edwards curves over Edwards fields
#include "relic_core.h"
Macros
#define ASSIGN_ED(CURVE, FIELD)
Functions
void ed_param_set (int param)
int ed_param_set_any (void)
int ed_param_get (void)
int ed_param_level (void)
void ed_param_print (void)
Detailed Description
Implementation of the Edwards elliptic curve parameters.
Version
$Id$
Definition in file relic_ed_param.c.
Macro Definition Documentation
ASSIGN_ED
#define ASSIGN_ED (CURVE, FIELD)
Value:
    fp_param_set(FIELD);                                                    \
    RLC_GET(str, CURVE##_A, sizeof(CURVE##_A));                             \
    fp_read_str(core_get()->ed_a, str, strlen(str), 16);                    \
    RLC_GET(str, CURVE##_D, sizeof(CURVE##_D));                             \
    fp_read_str(core_get()->ed_d, str, strlen(str), 16);                    \
    RLC_GET(str, CURVE##_X, sizeof(CURVE##_X));                             \
    fp_read_str(g->x, str, strlen(str), 16);                                \
    RLC_GET(str, CURVE##_Y, sizeof(CURVE##_Y));                             \
    fp_read_str(g->y, str, strlen(str), 16);                                \
    fp_set_dig(g->z, 1);                                                    \
    RLC_GET(str, CURVE##_R, sizeof(CURVE##_R));                             \
    bn_read_str(r, str, strlen(str), 16);                                   \
    RLC_GET(str, CURVE##_H, sizeof(CURVE##_H));                             \
    bn_read_str(h, str, strlen(str), 16);
Assigns a set of ordinary elliptic curve parameters.
Parameters
[in] CURVE - the curve parameters to assign.
[in] FIELD - the finite field identifier.
Definition at line 55 of file relic_ed_param.c.
Function Documentation
ed_param_set()
void ed_param_set (int param)
Calls a function to allocate a point on an Edwards curve.
Parameters
[out] A - the new point.
Exceptions
ERR_NO_MEMORY - if there is no available memory. Calls a function to clean and free a point on an Edwards curve.
Parameters
[out] A - the point to free. Negates an Edwards elliptic curve point. Computes R = -P.
[out] R - the result.
[in] P - the point to negate. Adds two Edwards elliptic curve points. Computes R = P + Q.
[out] R - the result.
[in] P - the first point to add.
[in] Q - the second point to add. Subtracts an Edwards elliptic curve point from another. Computes R = P - Q.
[out] R - the result.
[in] P - the first point.
[in] Q - the second point. Doubles an Edwards elliptic curve point. Computes R = 2P.
[out] R - the result.
[in] P - the point to double. Configures an Edwards curve by its parameter identifier.
- the parameter identifier.
Definition at line 71 of file relic_ed_param.c.
References ASSIGN_ED, bn_copy(), bn_free(), bn_null, CATCH_ANY, core_get(), CURVE_ED25519, ed_copy(), ed_curve_get_tab(), _ctx_t::ed_g, _ctx_t::ed_h, _ctx_t::ed_id, ed_null, _ctx_t::ed_pre, _ctx_t::ed_ptr, _ctx_t::ed_r, ERR_CAUGHT, ERR_NO_VALID, FINALLY, fp_set_dig(), ed_st::norm, PRIME_25519, RLC_FP_BYTES, ed_st::t, THROW, TRY, ed_st::x, ed_st::y, and ed_st::z.
Referenced by ed_param_set_any().
ed_param_set_any()
int ed_param_set_any (void)
Configures some set of curve parameters for the current security level.
Definition at line 134 of file relic_ed_param.c.
References CURVE_ED25519, ed_param_set(), RLC_ERR, and RLC_OK.
ed_param_get()
int ed_param_get (void)
Returns the parameter identifier of the currently configured Edwards elliptic curve.
Returns
the parameter identifier.
Definition at line 144 of file relic_ed_param.c.
References core_get(), and _ctx_t::ed_id.
Referenced by ed_param_level(), and ed_param_print().
ed_param_level()
int ed_param_level (void)
Returns the current security level.
Definition at line 148 of file relic_ed_param.c.
References CURVE_ED25519, and ed_param_get().
ed_param_print()
void ed_param_print (void)
Prints the current configured Edwards elliptic curve.
Definition at line 156 of file relic_ed_param.c.
References CURVE_ED25519, ed_param_get(), and util_banner.