RELIC: src/fpx/relic_fp9_sqr.c File Reference
relic_fp9_sqr.c File Reference
Prime field extensions.
#include "relic_core.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
Functions
void fp9_sqr_basic (fp9_t c, fp9_t a)
void fp9_sqr_unr (dv9_t c, fp9_t a)
void fp9_sqr_lazyr (fp9_t c, fp9_t a)
Detailed Description
Implementation of squaring in a nonic extension of a prime field.
Definition in file relic_fp9_sqr.c.
Function Documentation
fp9_sqr_basic()
void fp9_sqr_basic (fp9_t c, fp9_t a)
Computes the squares of a nonic extension field element using basic arithmetic.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to square.
Definition at line 42 of file relic_fp9_sqr.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp3_free, fp3_mul_nor(), fp3_new, fp3_null, THROW, and TRY.
fp9_sqr_unr()
void fp9_sqr_unr (dv9_t c, fp9_t a)
Computes the square of a nonic extension field element without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to square.
Definition at line 115 of file relic_fp9_sqr.c.
References CATCH_ANY, dv3_free, dv3_new, dv3_null, ERR_CAUGHT, FINALLY, fp3_addc_low(), fp3_addm_low(), fp3_dblm_low(), fp3_free, fp3_muln_low(), fp3_new, fp3_nord_low(), fp3_null, fp3_sqrn_low(), fp3_subc_low(), fp3_subm_low(), fp_hlvd_low(), THROW, and TRY.
Referenced by fp18_sqr_unr(), fp54_sqr_pck_lazyr(), and fp9_sqr_lazyr().
fp9_sqr_lazyr()
void fp9_sqr_lazyr (fp9_t c, fp9_t a)
Computes the square of a nonic extension field element using lazy reduction.
Parameters
[out] c - the result.
[in] a - the nonic extension field element to square.
Definition at line 204 of file relic_fp9_sqr.c.
References CATCH_ANY, dv9_free, dv9_new, dv9_null, ERR_CAUGHT, FINALLY, fp3_rdcn_low(), fp9_sqr_unr(), THROW, and TRY.