RELIC: src/epx/relic_ep8_util.c File Reference
relic_ep8_util.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
int ep8_is_infty (const ep8_t p)
void ep8_set_infty (ep8_t p)
void ep8_copy (ep8_t r, const ep8_t p)
void ep8_rand (ep8_t p)
void ep8_blind (ep8_t r, const ep8_t p)
void ep8_rhs (fp8_t rhs, const fp8_t x)
int ep8_on_curve (const ep8_t p)
void ep8_tab (ep8_t *t, const ep8_t p, int w)
void ep8_print (const ep8_t p)
size_t ep8_size_bin (const ep8_t a, int pack)
void ep8_read_bin (ep8_t a, const uint8_t *bin, size_t len)
void ep8_write_bin (uint8_t *bin, size_t len, const ep8_t a, int pack)
Detailed Description
Implementation of comparison for points on prime elliptic curves over an octic extensions.
Definition in file relic_ep8_util.c.
Function Documentation
ep8_is_infty()
int ep8_is_infty (const ep8_t p)
Tests if a point on an elliptic curve is at the infinity.
Parameters
[in] p - the point to test.
Returns
1 if the point is at infinity, 0 otherise.
Definition at line 39 of file relic_ep8_util.c.
References fp8_is_zero().
Referenced by ep8_add_basic(), ep8_add_jacob(), ep8_add_projc(), ep8_add_slp_basic(), ep8_cmp(), ep8_dbl_basic(), ep8_dbl_jacob(), ep8_dbl_projc(), ep8_dbl_slp_basic(), ep8_mul_basic(), ep8_mul_dig(), ep8_mul_lwnaf(), ep8_mul_lwreg(), ep8_mul_monty(), ep8_mul_sim_gen(), ep8_mul_sim_inter(), ep8_mul_sim_joint(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_neg(), ep8_norm(), ep8_norm_sim(), ep8_on_curve(), ep8_size_bin(), ep8_write_bin(), pp_map_k48(), pp_map_sim_k48(), and pp_norm_k48().
ep8_set_infty()
void ep8_set_infty (ep8_t p)
Assigns an elliptic curve point to the point at infinity.
Parameters
[out] p - the point to assign.
Definition at line 43 of file relic_ep8_util.c.
References BASIC, and fp8_zero().
Referenced by ep8_dbl_basic(), ep8_dbl_jacob(), ep8_dbl_projc(), ep8_dbl_slp_basic(), ep8_map(), ep8_mul_basic(), ep8_mul_dig(), ep8_mul_fix_basic(), ep8_mul_fix_combd(), ep8_mul_fix_combs(), ep8_mul_fix_ordin(), ep8_mul_gen(), ep8_mul_gls_imp(), ep8_mul_lwnaf(), ep8_mul_lwreg(), ep8_mul_monty(), ep8_mul_naf_imp(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_mul_sim_dig(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_plain(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_neg(), ep8_norm(), ep8_read_bin(), ep8_sub(), and pp_norm_k48().
ep8_copy()
void ep8_copy (ep8_t r, const ep8_t p)
Copies the second argument to the first argument.
Parameters
[out] q - the result.
[in] p - the elliptic curve point to copy.
Definition at line 50 of file relic_ep8_util.c.
References fp8_copy().
Referenced by ep8_add_basic(), ep8_add_jacob(), ep8_add_projc(), ep8_add_slp_basic(), ep8_blind(), ep8_cmp(), ep8_curve_get_gen(), ep8_curve_set_twist(), ep8_frb(), ep8_mul_dig(), ep8_mul_fix_combs(), ep8_mul_pre_basic(), ep8_mul_pre_combd(), ep8_mul_pre_combs(), ep8_mul_pre_ordin(), ep8_mul_reg_gls(), ep8_mul_sim_joint(), ep8_mul_sim_lot(), ep8_mul_sim_trick(), ep8_mul_slide(), ep8_norm(), ep8_norm_imp(), ep8_tab(), pp_add_k48_basic(), pp_dbl_k48_basic(), pp_mil_k48(), and pp_norm_k48().
ep8_rand()
void ep8_rand (ep8_t p)
Assigns a random value to an elliptic curve point.
Parameters
[out] p - the elliptic curve point to assign.
Definition at line 57 of file relic_ep8_util.c.
References bn_free, bn_new, bn_null, bn_rand_mod(), ep8_curve_get_ord(), ep8_mul_gen(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
ep8_blind()
void ep8_blind (ep8_t r, const ep8_t p)
Randomizes coordinates of an elliptic curve point.
Parameters
[out] r - the blinded prime elliptic curve point.
[in] p - the prime elliptic curve point to blind.
Definition at line 81 of file relic_ep8_util.c.
References ep8_copy(), ERR_CAUGHT, fp8_free, fp8_mul, fp8_new, fp8_null, fp8_rand(), fp8_sqr, JACOB, PROJC, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_mul_monty().
ep8_rhs()
void ep8_rhs (fp8_t rhs, const fp8_t x)
Computes the right-hand side of the elliptic curve equation at the x-coordinate of a certain prime elliptic curve point.
Parameters
[out] rhs - the result.
[in] x - the x-coordinate of the point.
Definition at line 112 of file relic_ep8_util.c.
References ep8_curve_get_a(), ep8_curve_get_b(), ep8_curve_opt_a(), ep8_curve_opt_b(), ERR_CAUGHT, fp8_add(), fp8_copy(), fp8_free, fp8_mul, fp8_new, fp8_null, fp8_sqr, fp_add_dig(), fp_sub_dig(), RLC_CATCH_ANY, RLC_FINALLY, RLC_MIN3, RLC_ONE, RLC_THROW, RLC_TINY, RLC_TRY, RLC_TWO, and RLC_ZERO.
Referenced by ep8_map(), and ep8_on_curve().
ep8_on_curve()
int ep8_on_curve (const ep8_t p)
Tests if a point is in the curve.
Parameters
[in] p - the point to test.
Definition at line 178 of file relic_ep8_util.c.
References ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, ep8_rhs(), ERR_CAUGHT, fp8_cmp(), fp8_sqr, RLC_CATCH_ANY, RLC_EQ, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_read_bin().
ep8_tab()
void ep8_tab (ep8_t * t, const ep8_t p, int w)
Builds a precomputation table for multiplying a random prime elliptic point.
Parameters
[out] t - the precomputation table.
[in] p - the point to multiply.
[in] w - the window width.
Definition at line 201 of file relic_ep8_util.c.
References ep8_add, ep8_copy(), ep8_dbl, ep8_norm(), and ep8_norm_sim().
Referenced by ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_mul_reg_imp(), and ep8_mul_sim_plain().
ep8_print()
void ep8_print (const ep8_t p)
Prints an elliptic curve point.
Parameters
[in] p - the elliptic curve point to print.
Definition at line 222 of file relic_ep8_util.c.
References fp8_print().
ep8_size_bin()
size_t ep8_size_bin (const ep8_t a, int pack)
Returns the number of bytes necessary to store a prime elliptic curve point over an octic extension with optional point compression.
Parameters
[in] a - the prime field element.
[in] pack - the flag to indicate compression.
Returns
the number of bytes.
Definition at line 228 of file relic_ep8_util.c.
References ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.
ep8_read_bin()
void ep8_read_bin (ep8_t a, const uint8_t * bin, size_t len)
Reads a prime elliptic curve point over an octic extension from a byte vector in big-endian format.
Parameters
[out] a - the result.
[in] bin - the byte vector.
[in] len - the buffer capacity.
Exceptions
ERR_NO_VALID - if the encoded point is invalid.
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 254 of file relic_ep8_util.c.
References BASIC, ep8_on_curve(), ep8_set_infty(), ERR_NO_BUFFER, ERR_NO_VALID, fp8_read_bin(), fp8_set_dig(), RLC_FP_BYTES, and RLC_THROW.
ep8_write_bin()
void ep8_write_bin (uint8_t * bin, size_t len, const ep8_t a, int pack)
Writes a prime elliptic curve pointer over an octic extension to a byte vector in big-endian format with optional point compression.
Parameters
[out] bin - the byte vector.
[in] len - the buffer capacity.
[in] a - the prime elliptic curve point to write.
[in] pack - the flag to indicate compression.
Exceptions
ERR_NO_BUFFER - if the buffer capacity is invalid.
Definition at line 288 of file relic_ep8_util.c.
References ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, ERR_CAUGHT, ERR_NO_BUFFER, fp8_write_bin(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BYTES, RLC_THROW, and RLC_TRY.