RELIC: src/epx/relic_ep8_mul.c File Reference
relic_ep8_mul.c File Reference
Elliptic curves defined over extensions of prime fields.
#include "relic_core.h"
Functions
static void ep8_mul_gls_imp (ep8_t r, const ep8_t p, const bn_t k)
static void ep8_mul_reg_gls (ep8_t r, const ep8_t p, const bn_t k)
static void ep8_mul_naf_imp (ep8_t r, const ep8_t p, const bn_t k)
static void ep8_mul_reg_imp (ep8_t r, const ep8_t p, const bn_t k)
void ep8_mul_basic (ep8_t r, const ep8_t p, const bn_t k)
void ep8_mul_slide (ep8_t r, const ep8_t p, const bn_t k)
void ep8_mul_monty (ep8_t r, const ep8_t p, const bn_t k)
void ep8_mul_lwnaf (ep8_t r, const ep8_t p, const bn_t k)
void ep8_mul_lwreg (ep8_t r, const ep8_t p, const bn_t k)
void ep8_mul_gen (ep8_t r, const bn_t k)
void ep8_mul_dig (ep8_t r, const ep8_t p, const dig_t k)
Detailed Description
Implementation of point multiplication on prime elliptic curves over an octic extension field.
Definition in file relic_ep8_mul.c.
Function Documentation
ep8_mul_gls_imp()
static void ep8_mul_gls_imp (ep8_t r, const ep8_t p, const bn_t k) static
Definition at line 43 of file relic_ep8_mul.c.
References bn_free, bn_mod, bn_new, bn_null, bn_rec_frb(), bn_rec_naf(), bn_sign(), ep8_add, ep8_curve_get_ord(), ep8_dbl, ep8_frb(), ep8_free, ep8_neg(), ep8_new, ep8_norm(), ep8_null, ep8_set_infty(), ep8_sub(), ep8_tab(), EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_MAX, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep8_mul_lwnaf().
ep8_mul_reg_gls()
static void ep8_mul_reg_gls (ep8_t r, const ep8_t p, const bn_t k) static
Definition at line 129 of file relic_ep8_mul.c.
References BASIC, bn_abs(), bn_add_dig(), bn_bits(), bn_free, bn_is_even(), bn_mod, bn_new, bn_null, bn_rec_frb(), bn_rec_sac(), bn_sign(), ep8_add, ep8_copy(), ep8_curve_get_ord(), ep8_dbl, ep8_frb(), ep8_free, ep8_neg(), ep8_new, ep8_norm(), ep8_norm_sim(), ep8_null, ep8_set_infty(), ep8_sub(), EP_ADD, EP_BN, ep_curve_is_pairf(), ERR_CAUGHT, fp8_copy_sec(), fp8_set_dig(), fp_prime_get_par(), RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and util_bits_dig().
Referenced by ep8_mul_lwreg().
ep8_mul_naf_imp()
static void ep8_mul_naf_imp (ep8_t r, const ep8_t p, const bn_t k) static
Definition at line 271 of file relic_ep8_mul.c.
References bn_rec_naf(), bn_sign(), ep8_add, ep8_dbl, ep8_free, ep8_neg(), ep8_new, ep8_norm(), ep8_null, ep8_set_infty(), ep8_sub(), ep8_tab(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep8_mul_lwnaf().
ep8_mul_reg_imp()
static void ep8_mul_reg_imp (ep8_t r, const ep8_t p, const bn_t k) static
Definition at line 323 of file relic_ep8_mul.c.
References BASIC, bn_abs(), bn_bits(), bn_free, bn_is_even(), bn_new, bn_null, bn_rec_reg(), bn_sign(), ep8_add, ep8_curve_get_ord(), ep8_dbl, ep8_free, ep8_neg(), ep8_new, ep8_norm(), ep8_null, ep8_set_infty(), ep8_sub(), ep8_tab(), EP_ADD, ERR_CAUGHT, fp8_copy_sec(), fp8_set_dig(), fp_copy_sec(), RLC_CATCH_ANY, RLC_CEIL, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, and RLC_WIDTH.
Referenced by ep8_mul_lwreg().
ep8_mul_basic()
void ep8_mul_basic (ep8_t r, const ep8_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the binary method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 412 of file relic_ep8_mul.c.
References bn_bits(), bn_is_zero(), bn_rec_naf(), bn_sign(), ep8_add, ep8_dbl, ep8_free, ep8_is_infty(), ep8_mul_dig(), ep8_neg(), ep8_new, ep8_norm(), ep8_null, ep8_set_infty(), ep8_sub(), ERR_CAUGHT, ERR_NO_BUFFER, RLC_ALLOCA, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_FREE, RLC_NEG, RLC_THROW, and RLC_TRY.
Referenced by ep8_mul_cof().
ep8_mul_slide()
void ep8_mul_slide (ep8_t r, const ep8_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the sliding window method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 470 of file relic_ep8_mul.c.
References bn_is_zero(), bn_rec_slw(), bn_sign(), ep8_add, ep8_copy(), ep8_dbl, ep8_free, ep8_is_infty(), ep8_neg(), ep8_new, ep8_norm(), ep8_norm_sim(), ep8_null, ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_BITS, RLC_NEG, RLC_THROW, RLC_TRY, RLC_WIDTH, and util_bits_dig().
ep8_mul_monty()
void ep8_mul_monty (ep8_t r, const ep8_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the constant-time Montgomery ladder point multiplication method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 540 of file relic_ep8_mul.c.
References bn_abs(), bn_add(), bn_bits(), bn_free, bn_get_bit(), bn_is_zero(), bn_mod, bn_new, bn_null, dv_swap_sec(), ep8_add, ep8_blind(), ep8_curve_get_ord(), ep8_dbl, ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_FP_DIGS, RLC_MAX, RLC_SEL, RLC_THROW, and RLC_TRY.
ep8_mul_lwnaf()
void ep8_mul_lwnaf (ep8_t r, const ep8_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using the w-NAF method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 622 of file relic_ep8_mul.c.
References bn_is_zero(), ep8_is_infty(), ep8_mul_gls_imp(), ep8_mul_naf_imp(), ep8_set_infty(), and ep_curve_is_endom().
ep8_mul_lwreg()
void ep8_mul_lwreg (ep8_t r, const ep8_t p, const bn_t k)
Multiplies a prime elliptic point by an integer using a regular method.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 644 of file relic_ep8_mul.c.
References bn_is_zero(), ep8_is_infty(), ep8_mul_reg_gls(), ep8_mul_reg_imp(), ep8_set_infty(), and ep_curve_is_endom().
ep8_mul_gen()
void ep8_mul_gen (ep8_t r, const bn_t k)
Multiplies the generator of an elliptic curve over a qaudratic extension.
Parameters
[out] r - the result.
[in] k - the integer.
Definition at line 664 of file relic_ep8_mul.c.
References bn_is_zero(), ep8_curve_get_gen(), ep8_curve_get_tab(), ep8_free, ep8_mul, ep8_mul_fix, ep8_new, ep8_null, ep8_set_infty(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_mul_sim_gen(), and ep8_rand().
ep8_mul_dig()
void ep8_mul_dig (ep8_t r, const ep8_t p, const dig_t k)
Multiplies a prime elliptic point by a small integer.
Parameters
[out] r - the result.
[in] p - the point to multiply.
[in] k - the integer.
Definition at line 691 of file relic_ep8_mul.c.
References bn_free, bn_new, bn_null, bn_rec_naf(), bn_set_dig(), ep8_add, ep8_copy(), ep8_dbl, ep8_free, ep8_is_infty(), ep8_new, ep8_norm(), ep8_null, ep8_set_infty(), ep8_sub(), ERR_CAUGHT, RLC_CATCH_ANY, RLC_DIG, RLC_FINALLY, RLC_THROW, and RLC_TRY.
Referenced by ep8_mul_basic().