RELIC: src/fpx/relic_fp6_mul.c File Reference
relic_fp6_mul.c File Reference
Extensions of prime fields
#include "relic_core.h"
#include "relic_fpx_low.h"
Functions
void fp6_mul_basic (fp6_t c, fp6_t a, fp6_t b)
void fp6_mul_unr (dv6_t c, fp6_t a, fp6_t b)
void fp6_mul_lazyr (fp6_t c, fp6_t a, fp6_t b)
void fp6_mul_dxs (fp6_t c, fp6_t a, fp6_t b)
void fp6_mul_art (fp6_t c, fp6_t a)
Detailed Description
Implementation of multiplication in a sextic extension of a prime field.
Version
Id
relic_fp6_mul.c 1867 2014-05-03 19:50:27Z dfaranha
Definition in file relic_fp6_mul.c.
Function Documentation
void fp6_mul_basic (fp6_t c, fp6_t a, fp6_t b)
Multiples two sextic extension field elements.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 41 of file relic_fp6_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_add, fp2_copy(), fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sub, THROW, and TRY.
void fp6_mul_unr (dv6_t c, fp6_t a, fp6_t b) inline
Multiples two sextic extension field elements without performing modular reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 112 of file relic_fp6_mul.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_addd_low(), fp2_addm_low(), fp2_addn_low(), fp2_free, fp2_mulc_low(), fp2_muln_low(), fp2_new, fp2_norh_low(), fp2_null, fp2_subc_low(), THROW, and TRY.
Referenced by fp12_mul_lazyr(), fp18_mul_dxs_lazyr(), fp18_mul_lazyr(), fp18_sqr_lazyr(), and fp6_mul_lazyr().
void fp6_mul_lazyr (fp6_t c, fp6_t a, fp6_t b)
Multiples two sextic extension field elements using lazy reduction.
Parameters
[out] c - the result.
[in] a - the sextic extension field element.
[in] b - the sextic extension field element.
Definition at line 195 of file relic_fp6_mul.c.
References CATCH_ANY, dv6_free, dv6_new, dv6_null, ERR_CAUGHT, FINALLY, fp2_rdcn_low(), fp6_mul_unr(), THROW, and TRY.
void fp6_mul_dxs (fp6_t c, fp6_t a, fp6_t b)
Multiples a dense sextic extension field element by a sparse element.
The sparse element must have a[2] = 0.
Parameters
[out] c - the result.
[in] a - a sextic extension field element.
[in] b - a sparse sextic extension field element.
Definition at line 215 of file relic_fp6_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_add, fp2_copy(), fp2_free, fp2_mul, fp2_mul_nor, fp2_new, fp2_null, fp2_sub, THROW, and TRY.
Referenced by fp12_mul_dxs_basic().
void fp6_mul_art (fp6_t c, fp6_t a)
Multiplies a sextic extension field element by the adjoined cube root.
Parameters
[out] c - the result.
[in] a - the sextic extension field element to multiply.
Definition at line 272 of file relic_fp6_mul.c.
References CATCH_ANY, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_mul_nor, fp2_new, fp2_null, THROW, and TRY.
Referenced by fp12_inv(), fp12_mul_basic(), fp12_mul_dxs_basic(), fp12_sqr_basic(), fp18_inv(), fp18_mul_basic(), fp18_mul_dxs_basic(), fp18_mul_dxs_lazyr(), fp18_sqr_basic(), fp18_sqr_cyc(), and fp18_sqr_pck().