RELIC: src/pp/relic_pp_dbl_k8.c File Reference
relic_pp_dbl_k8.c File Reference
Bilinear pairings over prime elliptic curves.
#include "relic_core.h"
#include "relic_pp.h"
#include "relic_fp_low.h"
#include "relic_fpx_low.h"
#include "relic_util.h"
Functions
void pp_dbl_k8_basic (fp8_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k8_projc_new (fp8_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k8_projc_basic (fp8_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k8_projc_lazyr (fp8_t l, ep2_t r, ep2_t q, ep_t p)
void pp_dbl_k8_projc_lazyr_new (fp8_t l, ep2_t r, ep2_t q, ep_t p)
Detailed Description
Implementation of Miller doubling for curves of embedding degree 2.
Definition in file relic_pp_dbl_k8.c.
Function Documentation
pp_dbl_k8_basic()
void pp_dbl_k8_basic (fp8_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using affine coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 44 of file relic_pp_dbl_k8.c.
References CATCH_ANY, ep2_copy(), ep2_curve_is_twist(), ep2_dbl_slp_basic(), ep2_null, EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_free, fp2_new, fp2_null, fp_copy(), THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, and ep_st::y.
pp_dbl_k8_projc_new()
void pp_dbl_k8_projc_new (fp8_t l, ep2_t r, ep2_t q, ep_t p)
Definition at line 84 of file relic_pp_dbl_k8.c.
References CATCH_ANY, ep2_curve_is_twist(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_free, fp2_mul_art(), fp2_new, fp2_null, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_dbl_k8_projc_basic()
void pp_dbl_k8_projc_basic (fp8_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 153 of file relic_pp_dbl_k8.c.
References CATCH_ANY, ep2_curve_is_twist(), ep_curve_get_a(), ep_curve_opt_a(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_mul_art(), fp2_new, fp2_null, fp2_zero(), fp_mul_dig(), RLC_ONE, RLC_TINY, RLC_ZERO, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_dbl_k8_projc_lazyr()
void pp_dbl_k8_projc_lazyr (fp8_t l, ep2_t r, ep2_t q, ep_t p)
Doubles a point and evaluates the corresponding line function at another point on an elliptic curve with embedding degree 8 using projective coordinates and lazy reduction.
Parameters
[out] l - the result of the evaluation.
[in,out] r - the resulting point.
[in] q - the point to double.
[in] p - the affine point to evaluate the line function.
Definition at line 261 of file relic_pp_dbl_k8.c.
References CATCH_ANY, dv2_free, dv2_new, dv2_null, ep2_curve_is_twist(), ep_curve_get_a(), ep_curve_opt_a(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_copy(), fp2_free, fp2_mul_art(), fp2_new, fp2_null, fp2_zero(), fp_mul_dig(), RLC_ONE, RLC_TINY, RLC_TWO, RLC_ZERO, THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.
pp_dbl_k8_projc_lazyr_new()
void pp_dbl_k8_projc_lazyr_new (fp8_t l, ep2_t r, ep2_t q, ep_t p)
Definition at line 375 of file relic_pp_dbl_k8.c.
References CATCH_ANY, dv2_new, dv2_null, ep2_curve_is_twist(), EP_MTYPE, ERR_CAUGHT, FINALLY, fp2_addc_low(), fp2_free, fp2_muln_low(), fp2_new, fp2_nord_low(), fp2_null, fp2_rdcn_low(), fp2_sqrn_low(), fp2_subc_low(), fp_hlvd_low(), THROW, TRY, ep2_st::x, ep_st::x, ep2_st::y, ep_st::y, and ep2_st::z.